export const airframeStructuresQuestions = [
  { id: 1, text: "The fuselage is the body of the aircraft to which all of the following attach EXCEPT:", options: ["Wings and tail", "Passengers only", "Engine and landing gear"], correctOptionIndex: 1 },
  { id: 2, text: "Stressed-skin type fuselages are used in:", options: ["Only light aircraft", "Modern transport aircraft", "Only vintage aircraft"], correctOptionIndex: 1 },
  { id: 3, text: "The main limitation of a stressed-skin structure is that:", options: ["It is too heavy", "It cannot tolerate any dents or deformation on its surface", "It requires frequent painting"], correctOptionIndex: 1 },
  { id: 4, text: "Most fuselages of transport aircraft are which type of structure?", options: ["Truss structures", "Semi-monocoque structures", "Monocoque structures only"], correctOptionIndex: 1 },
  { id: 5, text: "In a semi-monocoque fuselage, the shape is provided by:", options: ["Only frames", "A number of frames and stringers that keep each other at the correct distance", "Only stringers"], correctOptionIndex: 1 },
  { id: 6, text: "The skin panel is attached to stringers using:", options: ["Only welding", "Rivets or glue", "Only bolts"], correctOptionIndex: 1 },
  { id: 7, text: "Extra means of strengthening in the fuselage are necessary where:", options: ["No loads are applied", "Large forces are transmitted", "The skin is thinnest"], correctOptionIndex: 1 },
  { id: 8, text: "Large forces are transmitted at places where which of the following attach?", options: ["Only windows", "Wings, tail surfaces, engines and landing gears", "Only doors"], correctOptionIndex: 1 },
  { id: 9, text: "Weak spots in the construction are created where:", options: ["Frames are extra strong", "Frames and stringers are missing, such as doors, windows, and hatches", "Stringers are doubled"], correctOptionIndex: 1 },
  { id: 10, text: "The cabin floor structure divides the fuselage into:", options: ["Only passenger areas", "The main deck and the lower deck", "Only cargo areas"], correctOptionIndex: 1 },
  { id: 11, text: "The main deck includes:", options: ["Only cargo", "The flight deck and the cabin", "Only avionics"], correctOptionIndex: 1 },
  { id: 12, text: "The lower deck normally includes all of the following EXCEPT:", options: ["Avionics compartments", "Passenger seats", "Landing gear bays"], correctOptionIndex: 1 },
  { id: 13, text: "The cabin floor structure is supported by:", options: ["Only skin panels", "Support struts and crossbeams", "Only stringers"], correctOptionIndex: 1 },
  { id: 14, text: "The frames and the forward and aft pressure bulkheads are what type of structural components?", options: ["Secondary structural components", "Primary structural components", "Tertiary structural components"], correctOptionIndex: 1 },
  { id: 15, text: "Each frame is a 'Z' or other sectioned circumferential member carrying pressure loads in:", options: ["Compression", "Hoop tension", "Shear"], correctOptionIndex: 1 },
  { id: 16, text: "The frames are generally spaced at approximately what intervals along the fuselage?", options: ["Ten-inch intervals", "Twenty-inch intervals", "Thirty-inch intervals"], correctOptionIndex: 1 },
  { id: 17, text: "The bulkheads consist of webs that fit the:", options: ["Wing contour", "Sectional contours of the aircraft", "Engine shape"], correctOptionIndex: 1 },
  { id: 18, text: "Bulkheads are reinforced by:", options: ["Stringers", "Beams attached to the webs", "Skin panels"], correctOptionIndex: 1 },
  { id: 19, text: "Floor beams are primary structural components that carry:", options: ["Compression load", "Tension load", "Shear load"], correctOptionIndex: 1 },
  { id: 20, text: "Each floor beam is attached at its ends to:", options: ["A stringer", "A frame", "The skin"], correctOptionIndex: 1 },
  { id: 21, text: "Stringers are multiple failsafe longitudinal members designed to provide:", options: ["Only shape", "Stiffness to the skin and longitudinal strength to the fuselage", "Only compression strength"], correctOptionIndex: 1 },
  { id: 22, text: "Intercostals (or webs) are short longitudinal members that may span between:", options: ["Only one frame", "Only two adjacent frames", "Multiple frames"], correctOptionIndex: 1 },
  { id: 23, text: "Intercostals provide local structural reinforcement at or around:", options: ["Only spars", "Windows and doors", "Only wing roots"], correctOptionIndex: 1 },
  { id: 24, text: "A horizontal beam extends along each side of the fuselage level with the top of the floor. These beams are known as:", options: ["Stringers", "Crease beams", "Longerons"], correctOptionIndex: 1 },
  { id: 25, text: "Crease beams are attached to the fuselage skin at the 'crease' formed by the intersection between:", options: ["The wing and fuselage", "The upper and lower lobes of the fuselage cross-section", "The floor and wall"], correctOptionIndex: 1 },
  { id: 26, text: "The keel beams comprise the beam between:", options: ["The nose and tail", "The main landing gear wheel wells", "The wing tips"], correctOptionIndex: 1 },
  { id: 27, text: "The beam between the wheel wells is a reinforced box structure which carries:", options: ["Only wing loads", "Pressurisation loads originating on the sealed floor structure", "Only engine loads"], correctOptionIndex: 1 },
  { id: 28, text: "Both keel beams carry the bending loads acting along:", options: ["The upper fuselage", "The lower fuselage across the cavities for the centre wing box and the wheel well", "The flight deck"], correctOptionIndex: 1 },
  { id: 29, text: "Longerons are any longitudinal structural component that is:", options: ["Smaller than stringers", "Larger than the stringers", "The same size as stringers"], correctOptionIndex: 1 },
  { id: 30, text: "On the Boeing 737, the skin material used is:", options: ["7075-T6 only", "2024-T3", "7079-T6"], correctOptionIndex: 1 },
  { id: 31, text: "2024-T3 aluminium alloy has which characteristics?", options: ["Low fracture toughness", "Best fracture toughness and slow crack growth rate", "Poor fatigue life"], correctOptionIndex: 1 },
  { id: 32, text: "7075-T6 aluminium alloy has which characteristics?", options: ["Excellent fracture toughness", "Lower fracture toughness, use for tension applications where fatigue is not critical", "Best for all applications"], correctOptionIndex: 1 },
  { id: 33, text: "Aluminium-lithium alloys compared to conventional aluminium alloys are:", options: ["Heavier and less stiff", "10% lighter, 10% stiffer, and superior fatigue performance", "The same weight and stiffness"], correctOptionIndex: 1 },
  { id: 34, text: "PM aluminium compared to conventional aluminium alloys has:", options: ["Lower strength", "Higher strength, good fatigue life, good toughness", "Poor corrosion resistance"], correctOptionIndex: 1 },
  { id: 35, text: "7079-T6 aluminium has fracture toughness:", options: ["Better than both 7075 and 2024", "Between the 7075 and 2024", "Worse than both"], correctOptionIndex: 1 },
  { id: 36, text: "Doublers and waffles are sometimes bonded to the inside of fuselage skins. Their purpose is to:", options: ["Increase weight", "Stop or retard the growth of a crack", "Decrease strength"], correctOptionIndex: 1 },
  { id: 37, text: "This 'tear stopper' function provides:", options: ["No safety benefit", "Some failsafe element to the fuselage skin", "Only aesthetic improvement"], correctOptionIndex: 1 },
  { id: 38, text: "Blowout panels are provided wherever there is a danger of:", options: ["Fire", "Excessive pressure differential across a structural membrane", "Fuel leakage"], correctOptionIndex: 1 },
  { id: 39, text: "Blowout panels are provided in cabin floors should there be:", options: ["Fire in the cabin", "Sudden decompression in a cargo hold", "Engine failure"], correctOptionIndex: 1 },
  { id: 40, text: "The blowout panels 'blow out' to:", options: ["Increase pressure", "Release excess pressure and safeguard structural integrity", "Allow access"], correctOptionIndex: 1 },
  { id: 41, text: "Blowout panels can also be found on:", options: ["Only cargo doors", "Flight deck doors and other doors", "Only emergency exits"], correctOptionIndex: 1 },
  { id: 42, text: "The fitting and maintenance of blowout panels and their seals are:", options: ["Not important", "Critical", "Optional"], correctOptionIndex: 1 },
  { id: 43, text: "Retaining bolt torque loading for blowout panels must be applied:", options: ["Approximately", "In strict accordance with the applicable AMM", "By feel"], correctOptionIndex: 1 },
  { id: 44, text: "A bonded doubler on a Boeing 737 fuselage structure is used for:", options: ["Decoration", "Structural reinforcement", "Weight reduction"], correctOptionIndex: 1 },
  { id: 45, text: "A bonded waffle doubler on a Boeing 737 fuselage structure serves to:", options: ["Add weight", "Stop crack propagation", "Improve aerodynamics only"], correctOptionIndex: 1 },
  { id: 46, text: "To make it possible to use pressurized cabins, the front and rear of the fuselage construction are closed off by:", options: ["Stringers", "Pressure bulkhead", "Frames"], correctOptionIndex: 1 },
  { id: 47, text: "Which of the following is normally pressurized?", options: ["Radome", "Flight deck, cabin, avionics compartment and cargo compartments", "Landing gear bays"], correctOptionIndex: 1 },
  { id: 48, text: "Which of the following is normally NOT pressurized?", options: ["Cabin", "Radome, wing centre box, landing gear bays", "Avionics compartment"], correctOptionIndex: 1 },
  { id: 49, text: "Pressurisation is accomplished by:", options: ["Sealing the aircraft airtight", "Flowing more air into the cabin than is needed and allowing excess air to leak out", "Using only outflow valves"], correctOptionIndex: 1 },
  { id: 50, text: "There are two types of leakage in an aircraft pressure vessel:", options: ["Small and large", "Controlled and uncontrolled", "Internal and external"], correctOptionIndex: 1 },
  { id: 51, text: "Uncontrolled leakage is that in which air escapes around:", options: ["Only outflow valves", "Door and window seals, control cables and other openings", "Only safety valves"], correctOptionIndex: 1 },
  { id: 52, text: "Controlled leakage through the outflow valve and safety valve determines:", options: ["The fuel flow", "The amount of pressure in the cabin", "The engine power"], correctOptionIndex: 1 },
  { id: 53, text: "The wing-to-body fairings serve as:", options: ["Primary structure", "Aerodynamic fairings", "Fuel tanks"], correctOptionIndex: 1 },
  { id: 54, text: "Wing-to-body fairings are made of:", options: ["Only aluminium alloy", "Aluminium alloy or a honeycomb composite lay-up", "Only steel"], correctOptionIndex: 1 },
  { id: 55, text: "A cut-out in the wing-to-body fairing allows for the passage of:", options: ["Fuel lines", "The main landing gear", "Control cables"], correctOptionIndex: 1 },
  { id: 56, text: "For fire protection purposes, all compartments of an aircraft are classified as:", options: ["1, 2, 3 or 4", "A, B, C or E", "X, Y, Z or W"], correctOptionIndex: 1 },
  { id: 57, text: "Class A compartments have:", options: ["Built-in fire extinguishing system", "Visual detection of smoke and accessible in-flight fire extinguisher", "No fire protection"], correctOptionIndex: 1 },
  { id: 58, text: "Class B compartments have a separate approved smoke detector or fire detector system and:", options: ["No access in flight", "Sufficient access in flight for a crewmember to reach any part with a hand fire extinguisher", "No means to control ventilation"], correctOptionIndex: 1 },
  { id: 59, text: "Class C compartments have a separate approved smoke detector and:", options: ["No fire extinguishing system", "An approved built-in fire extinguishing or suppression system controllable from the flight deck", "Only hand extinguishers"], correctOptionIndex: 1 },
  { id: 60, text: "Class C compartments have means to exclude hazardous quantities of smoke, flames, or suppression agents from:", options: ["The cargo only", "Any compartment occupied by crew or passengers", "The lavatories only"], correctOptionIndex: 1 },
  { id: 61, text: "Class D classification was removed in:", options: ["1988", "1998", "2008"], correctOptionIndex: 1 },
  { id: 62, text: "Class E applies to:", options: ["Passenger aircraft", "Cargo-only aircraft", "Military aircraft only"], correctOptionIndex: 1 },
  { id: 63, text: "In Class E compartments, there are means to shut off ventilating airflow to or within the compartment, with controls accessible to:", options: ["Passengers", "Flight crew in the crew compartment", "Cabin crew only"], correctOptionIndex: 1 },
  { id: 64, text: "In Class E compartments, required crew emergency exits are accessible under:", options: ["Only normal loading conditions", "Any cargo loading condition", "Only empty conditions"], correctOptionIndex: 1 },
  { id: 65, text: "Fire protection in a typical cargo compartment includes:", options: ["Only smoke detectors", "Liners on the sidewalls and smoke detectors running overhead", "Only fire extinguishers"], correctOptionIndex: 1 },
  { id: 66, text: "In a butt joint, forward and aft skin panels are joined together by:", options: ["External strap", "An internal butt strap", "Welding only"], correctOptionIndex: 1 },
  { id: 67, text: "In a butt joint, the gap between forward and aft skin panels is filled with:", options: ["Metal filler", "Fillet seal", "Adhesive tape"], correctOptionIndex: 1 },
  { id: 68, text: "The butt joint type allows for:", options: ["No movement", "Expansion and contraction of the fuselage while providing adequate pressurisation sealing", "Only contraction"], correctOptionIndex: 1 },
  { id: 69, text: "Butt joints are used to join:", options: ["Skin panels at longitudinal edges", "Fuselage sections together", "Stringers to frames"], correctOptionIndex: 1 },
  { id: 70, text: "In a lap joint, the upper skin panel:", options: ["Butts against the lower panel", "Overlaps the lower skin panel", "Is separate from the lower panel"], correctOptionIndex: 1 },
  { id: 71, text: "During lap joint assembly, the upper skin and lower skin area of contact have applied to them:", options: ["No sealant", "A faying surface seal", "Only primer"], correctOptionIndex: 1 },
  { id: 72, text: "The lap joint is made while the sealant is:", options: ["Dry", "Still wet", "Cured"], correctOptionIndex: 1 },
  { id: 73, text: "Lap joints are used to join skin panels together at:", options: ["Circumferential sections", "The longitudinal edge", "The window openings"], correctOptionIndex: 1 },
  { id: 74, text: "Both butt and lap joints are important for:", options: ["Aerodynamics only", "Pressurisation sealing and structural integrity", "Weight reduction"], correctOptionIndex: 1 },
  { id: 75, text: "The fillet seal in a butt joint serves to:", options: ["Add weight", "Seal the gap between panels", "Provide electrical bonding"], correctOptionIndex: 1 },
  { id: 76, text: "The nose radome extends forward from:", options: ["The flight deck", "The forward pressure bulkhead", "The nose gear"], correctOptionIndex: 1 },
  { id: 77, text: "The two main functions of the radome are to serve as a fairing and to house:", options: ["Fuel tanks", "The weather radar antenna and glide slope antenna director bar", "Avionics equipment"], correctOptionIndex: 1 },
  { id: 78, text: "The radome is a cone-shaped structure made of:", options: ["Aluminium alloy", "Fibreglass", "Steel"], correctOptionIndex: 1 },
  { id: 79, text: "The radome is hinged at how many places?", options: ["One", "Two", "Four"], correctOptionIndex: 1 },
  { id: 80, text: "The radome is usually hinged to:", options: ["The fuselage skin", "The top side of the forward bulkhead", "The wing root"], correctOptionIndex: 1 },
  { id: 81, text: "Further attachment of the radome is by fasteners which screw into clips on the:", options: ["Stringers", "Bulkhead", "Frames"], correctOptionIndex: 1 },
  { id: 82, text: "In the open position, the radome is supported by:", options: ["Hydraulic struts", "Rods", "Cables"], correctOptionIndex: 1 },
  { id: 83, text: "The weather radar antenna is cantilevered from:", options: ["The radome tip", "The forward bulkhead", "The wing spar"], correctOptionIndex: 1 },
  { id: 84, text: "The nose of the radome is equipped with erosion protection and a layer of conductive spray paint provides:", options: ["Structural strength", "Static dissipation", "Heating"], correctOptionIndex: 1 },
  { id: 85, text: "The radome is provided with what on the exterior surface?", options: ["Heating elements", "Lightning diverter strips", "Reinforcing ribs"], correctOptionIndex: 1 },
  { id: 86, text: "One method that can be used to support the wing is:", options: ["Welded attachment", "A simple four-pin attachment method", "Glued attachment"], correctOptionIndex: 1 },
  { id: 87, text: "For big airliners, the simple four-pin design may not be sufficient because of:", options: ["Weight only", "Thrust and drag loads (fore and aft loading)", "Cost"], correctOptionIndex: 1 },
  { id: 88, text: "Another way of overcoming fore and aft loads is to attach fuselage frames to wing spars, known as:", options: ["Four-pin attachment", "Integral wing attachment", "Bolted attachment"], correctOptionIndex: 1 },
  { id: 89, text: "Bolted wing attachment is mainly used in:", options: ["Large aircraft", "Smaller aircraft", "All aircraft"], correctOptionIndex: 1 },
  { id: 90, text: "In the Saab 2000, how many wing-to-fuselage attachment fittings are on the mainframe?", options: ["Four", "Eight", "Six"], correctOptionIndex: 1 },
  { id: 91, text: "The attach fittings in the Saab 2000 transmit the load to the fuselage during flight for:", options: ["Weight reduction", "Multiple load path redundancy", "Aerodynamic reasons"], correctOptionIndex: 1 },
  { id: 92, text: "In integral wing attachment, the wing centre box structure extends across:", options: ["Only the wing", "The width of the fuselage", "Only the fuselage"], correctOptionIndex: 1 },
  { id: 93, text: "The wing centre box is a continuation of:", options: ["The fuselage frames", "The wing cantilever box", "The landing gear beam"], correctOptionIndex: 1 },
  { id: 94, text: "The wing box is usually attached to how many primary fuselage frames?", options: ["One", "Two", "Four"], correctOptionIndex: 1 },
  { id: 95, text: "The wing box distributes wing loads in the fuselage and can form:", options: ["A passenger compartment", "An optional integral fuel tank", "A cargo hold"], correctOptionIndex: 1 },
  { id: 96, text: "The landing gear loads are the ______ loads on the aircraft.", options: ["Smallest", "Largest", "Most insignificant"], correctOptionIndex: 1 },
  { id: 97, text: "Transferring landing gear loads to the fuselage shell requires:", options: ["No special measures", "Extensive local reinforcement", "Removal of structure"], correctOptionIndex: 1 },
  { id: 98, text: "The wing spars and additional structural members support and attach the main landing gear to:", options: ["The fuselage only", "The wings of larger transport aircraft", "The tail section"], correctOptionIndex: 1 },
  { id: 99, text: "Trunnion fittings support the upper shock strut. These are shafts that fit the shock strut and pass through fittings bolted to:", options: ["The wing", "The fuselage", "The engine pylon"], correctOptionIndex: 1 },
  { id: 100, text: "Modern high-speed transport category aircraft have adopted the use of:", options: ["Fixed stabiliser", "An adjustable stabiliser", "No stabiliser"], correctOptionIndex: 1 },
  { id: 101, text: "The aft portion of the adjustable stabiliser incorporates hinge assemblies attached to:", options: ["The wing", "The fuselage structure", "The engine"], correctOptionIndex: 1 },
  { id: 102, text: "The forward section of the adjustable stabiliser has a drive mechanism which changes:", options: ["The wing sweep", "The pitch of the stabiliser", "The rudder angle"], correctOptionIndex: 1 },
  { id: 103, text: "One method of vertical stabiliser construction is to attach the fore and aft spars to the fuselage using:", options: ["Welds", "Fittings", "Glue"], correctOptionIndex: 1 },
  { id: 104, text: "Another method of vertical stabiliser construction is to make it:", options: ["Removable only", "An integral part of the aft fuselage", "Separate from the fuselage"], correctOptionIndex: 1 },
  { id: 105, text: "When the vertical stabiliser is integral with the fuselage, the spars enter the fuselage and become part of:", options: ["The wing structure", "The aft fuselage frames", "The floor beams"], correctOptionIndex: 1 },
  { id: 106, text: "Doors that are part of the pressurised cabin include all EXCEPT:", options: ["Cabin doors", "Landing gear doors", "Cargo compartment doors"], correctOptionIndex: 1 },
  { id: 107, text: "Doors in the pressurised cabin must be opened and closed from:", options: ["The inside only", "The inside and the outside", "The outside only"], correctOptionIndex: 1 },
  { id: 108, text: "Instructions for closing and opening doors must be:", options: ["Complicated", "Easy to read and simple to understand", "In multiple languages only"], correctOptionIndex: 1 },
  { id: 109, text: "There must be an indication on the flight deck and a mechanical indication near the door itself that it is:", options: ["Open", "Properly closed", "Locked"], correctOptionIndex: 1 },
  { id: 110, text: "Cargo doors must be constructed so that, in the closed position, they are part of:", options: ["The wing structure", "The total strength of the fuselage construction", "The floor structure"], correctOptionIndex: 1 },
  { id: 111, text: "Doors in the pressurised cabin can be divided into two groups:", options: ["Large and small", "Plug-type and non-plug-type", "Metal and composite"], correctOptionIndex: 1 },
  { id: 112, text: "The door seal is usually made of:", options: ["Metal", "Silicone rubber integrated with fabric", "Plastic"], correctOptionIndex: 1 },
  { id: 113, text: "The door seal is a round hose-type with:", options: ["No openings", "Inflation holes", "Metal reinforcements"], correctOptionIndex: 1 },
  { id: 114, text: "When the cargo door is in the closed position, the door seal comes into contact with:", options: ["The door frame only", "The fuselage profile", "The floor"], correctOptionIndex: 1 },
  { id: 115, text: "Due to the higher internal pressure during flight, the door seal is inflated via the inflation holes so that:", options: ["The door opens", "The cargo compartment is sealed airtight", "The pressure decreases"], correctOptionIndex: 1 },
  { id: 116, text: "Plug-type doors close the fuselage from:", options: ["The outside", "The inside", "Either side"], correctOptionIndex: 1 },
  { id: 117, text: "Plug-type doors are a little ______ than the dimensions of the doorjamb.", options: ["Smaller", "Bigger", "The same size"], correctOptionIndex: 1 },
  { id: 118, text: "An advantage of a plug-type door is that the total load is distributed over:", options: ["The hinges only", "The whole doorjamb", "The locking mechanism only"], correctOptionIndex: 1 },
  { id: 119, text: "Another advantage of a plug-type door is that they close tighter as:", options: ["The aircraft speeds up", "The pressure increases", "The temperature decreases"], correctOptionIndex: 1 },
  { id: 120, text: "Non-plug-type doors close from:", options: ["The inside", "The outside", "The top"], correctOptionIndex: 1 },
  { id: 121, text: "Non-plug-type doors are mainly used for:", options: ["Passenger cabins", "Cargo compartments", "Flight deck"], correctOptionIndex: 1 },
  { id: 122, text: "Depending on dimensions, cargo doors are equipped with a counterbalance mechanism for manual operation, or:", options: ["No operation", "Electrical motor actuation or hydraulic actuation", "Pneumatic only"], correctOptionIndex: 1 },
  { id: 123, text: "The locking hooks keep each cargo door in the:", options: ["Open position", "Closed position", "Intermediate position"], correctOptionIndex: 1 },
  { id: 124, text: "Indication windows in the access panel of the cargo door show:", options: ["The door is open", "The locking condition", "The pressure level"], correctOptionIndex: 1 },
  { id: 125, text: "The green mark in the indication window shows that:", options: ["The door is open", "The safety mechanism locks each locking unit in its latched position", "The door is unlatched"], correctOptionIndex: 1 },
  { id: 126, text: "Red marks in the indication window show that:", options: ["The door is properly locked", "The locking units are not locked and satisfactory", "The door is sealed"], correctOptionIndex: 1 },
  { id: 127, text: "There is a vent door in each cargo door to balance the difference in pressure:", options: ["During flight only", "On the ground and in the cargo compartments", "During takeoff only"], correctOptionIndex: 1 },
  { id: 128, text: "The spring-loaded vent door opens inboard and remains in this position until:", options: ["The aircraft takes off", "The cargo door is correctly locked", "The cabin pressurises"], correctOptionIndex: 1 },
  { id: 129, text: "The drift pin mechanism decreases:", options: ["Door weight", "The contour offset between the fuselage and the door", "Door strength"], correctOptionIndex: 1 },
  { id: 130, text: "When the cargo door is correctly locked, the extended drift pins engage with:", options: ["The door frame", "The pockets of the fuselage frame", "The floor tracks"], correctOptionIndex: 1 },
  { id: 131, text: "Today, flight deck doors are made with various high-strength, lightweight composites capable of withstanding:", options: ["Only fire", "Bullets and small grenades", "Only pressure"], correctOptionIndex: 1 },
  { id: 132, text: "Flight deck doors have electrical locking latches controlled with a toggle switch usually found on:", options: ["The first officer's left side", "The captain's right-hand side", "The overhead panel"], correctOptionIndex: 1 },
  { id: 133, text: "Access to the flight deck can be requested by entering:", options: ["A key", "A unique numerical code on the keypad outside the door", "A verbal command"], correctOptionIndex: 1 },
  { id: 134, text: "When access is requested, a buzzer sounds and:", options: ["The door opens automatically", "Pilots decide whether to grant or deny access", "The door locks permanently"], correctOptionIndex: 1 },
  { id: 135, text: "Some flight deck doors have cameras to:", options: ["Record flight data", "See who is requesting access", "Monitor the cabin"], correctOptionIndex: 1 },
  { id: 136, text: "The three settings on flight deck doors are:", options: ["Open, closed, auto", "Norm, lock and unlock", "On, off, standby"], correctOptionIndex: 1 },
  { id: 137, text: "The flight deck has an emergency buzzer and pressure sensor that responds in the event of:", options: ["Fire", "Pressure loss in the cabin", "Engine failure"], correctOptionIndex: 1 },
  { id: 138, text: "In the 'norm' setting, the three additional door bolts are:", options: ["Activated", "Not activated", "Locked permanently"], correctOptionIndex: 1 },
  { id: 139, text: "If pilots switch to 'lock', what happens?", options: ["The door opens", "The additional three bolts activate", "The door unlocks"], correctOptionIndex: 1 },
  { id: 140, text: "If pilots do not react within 30 seconds to an access code, the door:", options: ["Remains locked", "Opens automatically", "Alarms only"], correctOptionIndex: 1 },
  { id: 141, text: "Flight deck windows are divided into two kinds:", options: ["Front and rear", "Windshield (front windows) and side windows", "Upper and lower"], correctOptionIndex: 1 },
  { id: 142, text: "Requirements that flight deck windows must meet are significantly more severe than those for:", options: ["Cargo doors", "Cabin windows", "Fuselage skin"], correctOptionIndex: 1 },
  { id: 143, text: "Windshields consist of layers of:", options: ["Only glass", "Toughened glass and plastics", "Only plastic"], correctOptionIndex: 1 },
  { id: 144, text: "There is a heating element between the outside window and the plastic layer made of:", options: ["Copper", "Gold, tin oxide or indium oxide", "Silver"], correctOptionIndex: 1 },
  { id: 145, text: "The outside window has a stiff, hard:", options: ["Plastic layer", "Scratch-resistant layer", "Metal mesh"], correctOptionIndex: 1 },
  { id: 146, text: "If the inside window breaks, the synthetic middle layer:", options: ["Falls out", "Keeps splinters from spreading in the flight deck", "Shatters completely"], correctOptionIndex: 1 },
  { id: 147, text: "Heating the windshields increases flexibility, keeps windows free of ice and:", options: ["Reduces weight", "Keeps windows from fogging over", "Increases strength"], correctOptionIndex: 1 },
  { id: 148, text: "The construction of the flight deck window consists of a glass pane laminated to each side of a:", options: ["Metal core", "Polyvinyl butylar (vinyl) interlayer or core", "Air gap"], correctOptionIndex: 1 },
  { id: 149, text: "The inner glass pane is the thicker of the two and is the:", options: ["Secondary load member", "Primary load-carrying member", "Non-structural member"], correctOptionIndex: 1 },
  { id: 150, text: "The vinyl interlayer acts as the 'fail-safe' load-carrying member and prevents:", options: ["Heating", "The window from shattering if the inner pane breaks", "Fogging"], correctOptionIndex: 1 },
  { id: 151, text: "The outer pane has no structural significance but provides:", options: ["Heating only", "Rigidity and a hard, scratch-resistant surface", "Insulation only"], correctOptionIndex: 1 },
  { id: 152, text: "To prevent layers from pulling against each other during temperature changes, windows have thin layers of slippery material called:", options: ["Lubricant", "Parting material or slip aeroplanes", "Separators"], correctOptionIndex: 1 },
  { id: 153, text: "Delamination can be caused by:", options: ["Only pressure", "Uneven heating, expansion, shrinkage, careless installation, ultraviolet rays", "Only humidity"], correctOptionIndex: 1 },
  { id: 154, text: "Delamination is characterised by:", options: ["Cracking only", "Separating a glass layer from the vinyl interlayer", "Scratching only"], correctOptionIndex: 1 },
  { id: 155, text: "Delamination can be confirmed by carrying out a reflection test using:", options: ["X-rays", "A flaw detector using a light beam", "Ultrasonic testing"], correctOptionIndex: 1 },
  { id: 156, text: "Scratches are defects in the surface of a panel. Hairline scratches:", options: ["Can be easily felt with fingernail", "Can be seen but is difficult to feel with a fingernail", "Are more than 0.254mm deep"], correctOptionIndex: 1 },
  { id: 157, text: "Light scratches are less than ______ deep and can be felt with a fingernail.", options: ["0.1 mm", "0.254 mm (0.010 inch)", "1.0 mm"], correctOptionIndex: 1 },
  { id: 158, text: "Chips are flakes or layers of glass broken from the surface. The two types are:", options: ["Round and square", "Conchoidal and V-shaped", "Deep and shallow"], correctOptionIndex: 1 },
  { id: 159, text: "Cracks in annealed glass may take the form of:", options: ["Only single cracks", "Single cracks or cracks forming an irregular criss-cross pattern", "No cracks possible"], correctOptionIndex: 1 },
  { id: 160, text: "Vinyl bubbling within the vinyl interlayer of electrically heated windscreens is usually due to:", options: ["Pressure", "Overheating conditions", "Scratching"], correctOptionIndex: 1 },
  { id: 161, text: "Cabin windows consist of how many windows?", options: ["One", "Three", "Five"], correctOptionIndex: 1 },
  { id: 162, text: "The outside and the middle window are installed in the construction of the fuselage but:", options: ["Are primary structure", "Are of no importance to the strength of the fuselage", "Carry all pressure loads"], correctOptionIndex: 1 },
  { id: 163, text: "The protective windows are installed in:", options: ["The fuselage skin", "The wall panels", "The frames"], correctOptionIndex: 1 },
  { id: 164, text: "There is a small ventilation hole in the inside window to allow adjustment for:", options: ["Temperature", "Pressure differences between the inside and the outside window", "Humidity"], correctOptionIndex: 1 },
  { id: 165, text: "Cabin windows are made of a particular synthetic. A disadvantage is that it is sensitive to:", options: ["Water only", "Solvents, stripping compounds, ultraviolet rays and air pollution", "Cold temperatures only"], correctOptionIndex: 1 },
  { id: 166, text: "Each window is made with two panes. Each of the two panes can carry:", options: ["No pressure", "The full differential cabin pressure independently", "Only half the pressure"], correctOptionIndex: 1 },
  { id: 167, text: "The panes are made of:", options: ["Tempered glass", "Stretched acrylic", "Polycarbonate"], correctOptionIndex: 1 },
  { id: 168, text: "Near the bottom of the inner pane, at the centre, there is a small vent hole to:", options: ["Increase pressure", "Equalise pressure between the panes in normal operating conditions", "Allow drainage"], correctOptionIndex: 1 },
  { id: 169, text: "The vent hole is not large enough to cause:", options: ["Condensation", "Significant pressure loss in the event of outer pane damage", "Fogging"], correctOptionIndex: 1 },
  { id: 170, text: "In maintenance areas where fumes of solvents occur, all cabin windows within a radius of ______ from the work spot must be covered.", options: ["1m", "5m", "10m"], correctOptionIndex: 1 },
  { id: 171, text: "A third pane, known as the acoustic or scratch pane, is made from:", options: ["Glass", "Polycarbonate", "Acrylic"], correctOptionIndex: 1 },
  { id: 172, text: "In areas where equipment and furnishings are located, cabin dummy windows are installed made of:", options: ["Plastic", "One layer of aluminium alloy plate", "Glass"], correctOptionIndex: 1 },
  { id: 173, text: "Warm water for cleaning acrylic windows should have a maximum temperature of:", options: ["30°C", "40°C", "50°C"], correctOptionIndex: 1 },
  { id: 174, text: "A dry cloth should never be used to remove dust or dirt from acrylic windows because:", options: ["It scratches", "A static charge builds up", "It leaves residue"], correctOptionIndex: 1 },
  { id: 175, text: "Stress crazing consists of multiple hairline surface cracks which act as:", options: ["Reinforcements", "Notches and may cause a serious drop in strength", "Decoration"], correctOptionIndex: 1 },
  { id: 176, text: "Passenger seats are attached to:", options: ["The fuselage skin", "Seat tracks in the floor", "The frames"], correctOptionIndex: 1 },
  { id: 177, text: "Seats may be rearranged for different passenger configurations by moving them forward or aft on:", options: ["Rails", "Seat tracks", "Floor beams"], correctOptionIndex: 1 },
  { id: 178, text: "Seat tracks are beams of a particular cross-section bolted to:", options: ["The wing", "The floor structure", "The bulkhead"], correctOptionIndex: 1 },
  { id: 179, text: "Tracks are provided with circular cut-outs for seat studs and lock pins. Cut-outs in the tracks are spaced ______ apart.", options: ["Half inch", "One inch", "Two inches"], correctOptionIndex: 1 },
  { id: 180, text: "Seat retention and locking are by a spring-loaded shear pin located at:", options: ["The front of each leg", "The rear of each leg", "The middle of each leg"], correctOptionIndex: 1 },
  { id: 181, text: "Gliders can be towed into the air by two methods: winch towing and:", options: ["Car towing", "Tug towing (aero tow)", "Rocket towing"], correctOptionIndex: 1 },
  { id: 182, text: "In winch towing, the glider pilot releases the winch cable, which descends to the ground with:", options: ["A weight", "A small parachute", "A flag"], correctOptionIndex: 1 },
  { id: 183, text: "The tow hook is positioned at or near the glider's:", options: ["Nose", "Centre of gravity", "Tail"], correctOptionIndex: 1 },
  { id: 184, text: "To prevent damage to the glider, a safety link in the form of a small metal plate is installed to break at:", options: ["Any load", "A specific load", "Maximum load only"], correctOptionIndex: 1 },
  { id: 185, text: "This 'weak link' is placed between the cable parachute and the glider to ensure that if cable tension exceeds limits:", options: ["The glider breaks", "The weak link breaks before any harm is done", "The cable breaks"], correctOptionIndex: 1 },
  { id: 186, text: "Weak links are colour-coded, with each colour indicating:", options: ["The length", "A specific breaking load", "The manufacturer"], correctOptionIndex: 1 },
  { id: 187, text: "The ultimate reference for weak link strength is:", options: ["Paint markings", "The glider's flight manual", "The launch marshal"], correctOptionIndex: 1 },
  { id: 188, text: "Safety link (weak link) at the glider end minimum strength is:", options: ["50% of glider's maximum certificated operating weight", "80% of glider's maximum certificated operating weight", "100% of glider's maximum certificated operating weight"], correctOptionIndex: 1 },
  { id: 189, text: "Safety link (weak link) at the glider end maximum strength is:", options: ["1.5 times the maximum certificated operating weight", "2 times the maximum certificated operating weight", "3 times the maximum certificated operating weight"], correctOptionIndex: 1 },
  { id: 190, text: "Two types of tow hooks commonly used in aviation are:", options: ["Boeing and Airbus", "Tost or Schweizer", "Cessna and Piper"], correctOptionIndex: 1 },
  { id: 191, text: "When inspecting the Schweizer tow hook, it is important to check for:", options: ["Only rust", "Damage, cracks, or deformation and free movement on pivot bolt", "Only colour"], correctOptionIndex: 1 },
  { id: 192, text: "The Schweizer tow ring is made of high-grade, quarter-inch steel that has been:", options: ["Painted", "Magnafluxed", "Welded"], correctOptionIndex: 1 },
  { id: 193, text: "The Tost tow ring is also made of high-grade steel and can be found in:", options: ["Hardware stores", "Most glider supply companies", "Automotive shops"], correctOptionIndex: 1 },
  { id: 194, text: "A Schweizer tow ring does not fit in a Tost tow hitch, but a Tost tow ring can be placed on:", options: ["Only Tost hitches", "A Schweizer-type tow hitch", "No other hitch"], correctOptionIndex: 1 },
  { id: 195, text: "Knots in the tow rope reduce its strength by up to:", options: ["25%", "50%", "75%"], correctOptionIndex: 1 },
  { id: 196, text: "Banner towing requires aircraft with stable flying characteristics, sufficient power, and:", options: ["No special equipment", "A quick-release hook at the tail", "Extra fuel tanks"], correctOptionIndex: 1 },
  { id: 197, text: "The grapple hook in banner towing is attached at the end of the tow rope, usually in the pilot's lap during:", options: ["Landing", "Take-off", "Cruise"], correctOptionIndex: 1 },
  { id: 198, text: "The grapple looks like a three-pronged anchor with prongs usually rounded and bent back towards the stock to prevent:", options: ["Slipping", "Digging into the ground", "Breaking"], correctOptionIndex: 1 },
  { id: 199, text: "Target tugs are aircraft used to tow crewless drones, fabric drogues, or other types of targets for:", options: ["Advertising", "Gun or missile target practice", "Research"], correctOptionIndex: 1 },
  { id: 200, text: "Today, more air forces have begun using civilian companies to provide target towing services using:", options: ["Military aircraft only", "Modified corporate jet aircraft", "Gliders"], correctOptionIndex: 1 },
  { id: 201, text: "Aviation authorities require safety equipment, including escape slides, to be deployed within ______ for all passengers to escape.", options: ["60 seconds", "90 seconds", "120 seconds"], correctOptionIndex: 1 },
  { id: 202, text: "The evacuation must be possible in complete darkness and with ______ of the exits blocked.", options: ["None", "Half", "All"], correctOptionIndex: 1 },
  { id: 203, text: "Some aircraft do not have escape slides because all exits are at a distance from the ground less than:", options: ["3 ft (0.9 m)", "6 ft (1.8 m)", "10 ft (3 m)"], correctOptionIndex: 1 },
  { id: 204, text: "Emergency escape slides are located within cabin doors or in:", options: ["Wing compartments", "External fuselage compartments", "Tail cone"], correctOptionIndex: 1 },
  { id: 205, text: "High-pressure carbon dioxide or nitrogen gas containers rapidly inflate the evacuation slides after:", options: ["Manual inflation", "A crew member opens the aircraft door during flight", "The aircraft lands"], correctOptionIndex: 1 },
  { id: 206, text: "The slide connects to the door with an interior lever called the:", options: ["Handle", "Girt", "Lanyard"], correctOptionIndex: 1 },
  { id: 207, text: "Newer slides have internal baffles to account for environmental factors such as wind by inflating:", options: ["The entire slide at once", "The end of the slide closest to the aircraft first", "Only the bottom"], correctOptionIndex: 1 },
  { id: 208, text: "Manufacturers make escape slides from carbon fibres and a nylon material coated in urethane and sprayed with:", options: ["Waterproofing", "Grey aluminised paint for fire resistance", "Lubricant"], correctOptionIndex: 1 },
  { id: 209, text: "The pressurised cylinders send ______ to an aspirator that utilises the Venturi effect.", options: ["1,000 psi", "3,000 psi", "5,000 psi"], correctOptionIndex: 1 },
  { id: 210, text: "According to regulations, if an emergency exit is located above 1.8m or 6 ft above ground level, there must be:", options: ["No special provision", "A means to assist passengers in evacuating", "Additional crew"], correctOptionIndex: 1 },
  { id: 211, text: "For Type C exits, assisting means must be automatically erected within ______ from the time the opening means of the exit is actuated.", options: ["6 seconds", "10 seconds", "15 seconds"], correctOptionIndex: 1 },
  { id: 212, text: "In the event of ditching, aircraft slides can be used as:", options: ["Life jackets", "Rafts", "Floats"], correctOptionIndex: 1 },
  { id: 213, text: "To identify slide rafts, look for dual-lane slides that are:", options: ["Smaller than normal", "Wider and larger than regular slides", "The same size"], correctOptionIndex: 1 },
  { id: 214, text: "The cylinder passes pressurised gas through flexible hoses connected to an aspirator. The aspirator has flaps that open due to:", options: ["Pressure from the cabin", "The vacuum created by high-speed air from the cylinder", "Manual operation"], correctOptionIndex: 1 },
  { id: 215, text: "Inadvertent slide deployment occurs when the operator tries to open the door while it is in:", options: ["Disarmed position", "Armed position", "Neutral position"], correctOptionIndex: 1 },
  { id: 216, text: "When the cabin is pressurised, a plug-type door cannot be opened due to:", options: ["Mechanical locks", "The force of cabin pressure holding it closed", "Electrical interlocks"], correctOptionIndex: 1 },
  { id: 217, text: "Overwing exit doors are outward-opening and hinged at the top. They are protected from opening during flight by:", options: ["Manual locks", "DC-activated electrical flight locks", "Hydraulic locks"], correctOptionIndex: 1 },
  { id: 218, text: "The locks are energised when both thrust levers are greater than ______ TLA position.", options: ["30°", "53°", "75°"], correctOptionIndex: 1 },
  { id: 219, text: "When there is no electrical power available to the locks, they are designed to be:", options: ["Locked", "Unlocked in a fail-safe manner", "Disabled"], correctOptionIndex: 1 },
  { id: 220, text: "Airbus uses a door damper and emergency operation cylinder. The cylinder is charged with pressurized nitrogen at:", options: ["1,000 psi", "2,000 psi", "3,000 psi"], correctOptionIndex: 1 },
  { id: 221, text: "In the \"ARMED\" position, a frangible disc in the head of the nitrogen cylinder is:", options: ["Opened electrically", "Mechanically ruptured with a pin", "Opened by pressure"], correctOptionIndex: 1 },
  { id: 222, text: "The Boeing 787 emergency power assist system is a sealed bottle of nitrogen electrically activated and:", options: ["Can be recharged", "Cannot be recharged and is one-time use", "Uses compressed air"], correctOptionIndex: 1 },
  { id: 223, text: "The Boeing 777 EPAS uses an independent battery pack to provide electrical power instead of relying on:", options: ["Hydraulic power", "The aircraft's electrical system", "Pneumatic power"], correctOptionIndex: 1 },
  { id: 224, text: "Emergency opening of a passenger entry door at normal and adverse attitudes takes less than:", options: ["2 seconds", "4 seconds", "6 seconds"], correctOptionIndex: 1 },
  { id: 225, text: "The EPAS actuator assembly provides full-stroke damping to prevent injury due to:", options: ["Fire", "Wind or accidental emergency actuation", "Pressure"], correctOptionIndex: 1 },
];
