import type { TestConfig } from "@shared/schema";

export const allTests: Record<string, TestConfig> = {
  "composite-materials": {
    id: "composite-materials",
    title: "Composite Materials",
    description: "Assessment on Composite Materials and structural materials in aviation. Answer all 57 questions about composites, resins, fibers, wooden structures, material properties and heat treatments. Time limit: 60 minutes.",
    durationMinutes: 60,
    questions: [
      {
        id: 1,
        text: "What is the primary reason for using composite materials in aircraft?",
        options: ["Lower production cost", "Weight reduction", "Easier repair"],
        correctOptionIndex: 1,
      },
      {
        id: 2,
        text: "Which of the following is a disadvantage of composites?",
        options: ["High strength-to-weight ratio", "Easy to repair", "Expensive materials and repair"],
        correctOptionIndex: 2,
      },
      {
        id: 3,
        text: "A composite material is typically made up of:",
        options: ["Metal and wood", "Matrix and reinforcing fibres", "Ceramics and elastomers"],
        correctOptionIndex: 1,
      },
      {
        id: 4,
        text: "Which fibre type is known for its high impact resistance and yellow colour?",
        options: ["Glass fibre", "Aramid (Kevlar)", "Carbon fibre"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "Which fibre is strongest in compression but brittle and corrosive to aluminium?",
        options: ["Glass fibre", "Aramid", "Carbon fibre"],
        correctOptionIndex: 2,
      },
      {
        id: 6,
        text: "Which type of glass fibre is most common for aeronautical GRP?",
        options: ["A-Glass", "E-Glass", "S-Glass"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "Which resin type is most widely used in aerospace adhesives and composites?",
        options: ["Polyester", "Epoxy", "Phenolic"],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "What is the purpose of a hardener in an epoxy resin system?",
        options: ["To colour the resin", "To initiate the curing reaction", "To reduce viscosity"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "Which resin type is known for low smoke and toxic gas emissions, making it suitable for cabin interiors?",
        options: ["Epoxy", "Polyurethane", "Phenolic"],
        correctOptionIndex: 2,
      },
      {
        id: 10,
        text: "How must prepreg materials be stored to prevent premature curing?",
        options: ["In a heated cabinet", "In a freezer at -18°C or below", "At room temperature in sealed bags"],
        correctOptionIndex: 1,
      },
      {
        id: 11,
        text: "What is the main advantage of using prepreg materials?",
        options: ["Lower cost", "Controlled resin-to-fibre ratio", "No need for refrigeration"],
        correctOptionIndex: 1,
      },
      {
        id: 12,
        text: "What is the typical shelf life of prepreg repair materials?",
        options: ["1–2 months", "6–12 months", "2–3 years"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "What is a monolithic composite structure?",
        options: ["A sandwich with a honeycomb core", "Multiple layers of laminate stacked together", "A single layer of fibre only"],
        correctOptionIndex: 1,
      },
      {
        id: 14,
        text: "What is the purpose of a honeycomb core in a sandwich structure?",
        options: ["To increase weight", "To increase stiffness without significant weight gain", "To make the structure flexible"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "Which of these is a common core material for sandwich structures?",
        options: ["Steel mesh", "Nomex honeycomb", "Rubber foam"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What does an autoclave provide during composite curing?",
        options: ["Only heat", "Heat and pressure", "Only vacuum"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "Which temperature range is typical for curing epoxy resins in an autoclave?",
        options: ["50°C–80°C", "120°C–180°C", "200°C–300°C"],
        correctOptionIndex: 1,
      },
      {
        id: 18,
        text: "What is the purpose of vacuum bagging in composite lay-up?",
        options: ["To add colour to the laminate", "To remove air and excess resin", "To speed up the curing time"],
        correctOptionIndex: 1,
      },
      {
        id: 19,
        text: "Which defect is a hidden failure between layers of fabric in a composite?",
        options: ["Crack", "Delamination", "Dent"],
        correctOptionIndex: 1,
      },
      {
        id: 20,
        text: "Which inspection method uses sound to detect delamination?",
        options: ["Light test", "Coin-tap test", "X-ray"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "Class 3 damage in composites is defined as:",
        options: ["Major structural damage", "Negligible damage within limits", "Damage requiring immediate repair"],
        correctOptionIndex: 1,
      },
      {
        id: 22,
        text: "What is the common name for polymethyl-methacrylate used in aircraft windows?",
        options: ["PVC", "Perspex/Acrylic", "Teflon"],
        correctOptionIndex: 1,
      },
      {
        id: 23,
        text: "Which plastic is known for its non-stick properties and high chemical resistance?",
        options: ["Polypropylene", "PTFE (Teflon)", "Nylon"],
        correctOptionIndex: 1,
      },
      {
        id: 24,
        text: "What causes crazing in acrylic windows?",
        options: ["Excessive heat only", "Contact with solvents or UV light", "High pressure"],
        correctOptionIndex: 1,
      },
      {
        id: 25,
        text: "Which elastomer is known for high-temperature resistance and is often called Viton?",
        options: ["Nitrile", "Fluoro-elastomer", "Silicone rubber"],
        correctOptionIndex: 1,
      },
      {
        id: 26,
        text: "Which rubber is resistant to phosphate ester hydraulic fluids like Skydrol?",
        options: ["Buna-S", "Neoprene", "Ethylene-propylene rubber"],
        correctOptionIndex: 2,
      },
      {
        id: 27,
        text: "What is the primary use of elastomers in aircraft?",
        options: ["Structural components", "Seals, adhesives, and flexible parts", "Window frames"],
        correctOptionIndex: 1,
      },
      {
        id: 28,
        text: "Which adhesive was first developed during WWII and is still used today?",
        options: ["Epoxy", "Redux", "Polyurethane"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "What is the primary function of a sealant in aircraft?",
        options: ["To provide electrical insulation", "To prevent air or fluid leakage", "To increase structural strength"],
        correctOptionIndex: 1,
      },
      {
        id: 30,
        text: "Which sealant type vulcanises at room temperature?",
        options: ["Polysulphide", "RTV silicone", "Epoxy paste"],
        correctOptionIndex: 1,
      },
      {
        id: 31,
        text: "Which wood type is traditionally considered best for aircraft construction?",
        options: ["Oak", "Sitka spruce", "Pine"],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is the maximum grain slope allowed for Grade A spruce?",
        options: ["1:8", "1:12", "1:15"],
        correctOptionIndex: 2,
      },
      {
        id: 33,
        text: "What defect appears as a separation along the annual rings of wood?",
        options: ["Heart shake", "Ring shake", "Knot"],
        correctOptionIndex: 1,
      },
      {
        id: 34,
        text: "Which glue is waterproof and highly resistant to temperature and chemicals?",
        options: ["Casein", "Resorcinol-formaldehyde", "Urea-formaldehyde"],
        correctOptionIndex: 1,
      },
      {
        id: 35,
        text: "What is the typical taper ratio for a scarf joint in wood?",
        options: ["5:1", "12:1 to 15:1", "20:1"],
        correctOptionIndex: 1,
      },
      {
        id: 36,
        text: "Why should sandpaper not be used on new timber before gluing?",
        options: ["It makes the wood too smooth", "It fills pores with dust and reduces adhesion", "It changes the colour of the wood"],
        correctOptionIndex: 1,
      },
      {
        id: 37,
        text: "What indicates dry rot in wood?",
        options: ["Dark discolouration along the grain", "Crumbling wood patches", "Blue stains"],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "What is compression shake in wood caused by?",
        options: ["Tension overload", "Compression overload along the grain", "Moisture absorption"],
        correctOptionIndex: 1,
      },
      {
        id: 39,
        text: "How can water penetration in a wooden structure be detected?",
        options: ["By tapping the surface", "By checking for corrosion on screws or bolts", "By applying a light coat of varnish"],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What is aircraft-grade plywood usually made from?",
        options: ["Spruce veneers", "Birch veneers", "Mahogany veneers"],
        correctOptionIndex: 1,
      },
      {
        id: 41,
        text: "How are veneers typically arranged in plywood?",
        options: ["All grains in the same direction", "Grains alternated at 90°", "Random orientation"],
        correctOptionIndex: 1,
      },
      {
        id: 42,
        text: "What is the main advantage of plywood over solid wood?",
        options: ["Lower cost", "Greater strength in multiple directions", "Lighter weight"],
        correctOptionIndex: 1,
      },
      {
        id: 43,
        text: "In the context of aluminum manufacturing, what does \"DC\" stand for in the provided abbreviations list?",
        options: ["Direct Current", "Direct Chili", "Double Coated"],
        correctOptionIndex: 1,
      },
      {
        id: 44,
        text: "Which abbreviation refers to the chemical compound used as a flux in aluminum smelting?",
        options: ["Al₂O₃", "Na₃AlF₃", "CO₂"],
        correctOptionIndex: 1,
      },
      {
        id: 45,
        text: "What density threshold is used to differentiate between lightweight and heavyweight metals in aircraft construction?",
        options: ["3.0 Kg/dm³", "5.0 Kg/dm³", "7.0 Kg/dm³"],
        correctOptionIndex: 1,
      },
      {
        id: 46,
        text: "Which of the following metals has the lowest density among those listed for aircraft structures?",
        options: ["Titanium", "Aluminum", "Magnesium"],
        correctOptionIndex: 2,
      },
      {
        id: 47,
        text: "What is the term for the undesirable property where a metal becomes brittle within a specific high-temperature range?",
        options: ["Cold shortness", "Hot shortness", "Thermal brittleness"],
        correctOptionIndex: 1,
      },
      {
        id: 48,
        text: "Which property describes a material's ability to be readily liquefied by heat for welding?",
        options: ["Fusibility", "Malleability", "Solubility"],
        correctOptionIndex: 0,
      },
      {
        id: 49,
        text: "In the formula for strain, what does \"e\" represent?",
        options: ["Original length", "Change in length", "Elastic modulus"],
        correctOptionIndex: 1,
      },
      {
        id: 50,
        text: "If a stress of 1 hbar is applied to a steel component, what is the resulting strain if Young's modulus for steel is 20,000 hbar?",
        options: ["1/20,000", "1/2,000", "1/200"],
        correctOptionIndex: 0,
      },
      {
        id: 51,
        text: "Which of the following is NOT listed as a typical load contributing to fatigue in aircraft structures?",
        options: ["Atmospheric gusts", "Engine start-up cycles", "Taxiing"],
        correctOptionIndex: 1,
      },
      {
        id: 52,
        text: "What microscopic feature is NOT cited as a potential initiation site for fatigue cracks?",
        options: ["Voids", "Grain boundaries", "Inclusion particles"],
        correctOptionIndex: 1,
      },
      {
        id: 53,
        text: "In the historical context provided, which civilization first perfected reliable steel manufacturing around AD 200?",
        options: ["Romans", "Celts", "Chinese"],
        correctOptionIndex: 1,
      },
      {
        id: 54,
        text: "What is the primary purpose of the blast furnace in iron production?",
        options: ["To cast iron into final shapes", "To convert iron ore into molten iron", "To refine steel into alloys"],
        correctOptionIndex: 1,
      },
      {
        id: 55,
        text: "Which alloying element, when added in approximately 35%, gives steel a nearly-zero expansion coefficient?",
        options: ["Nickel", "Chromium", "Cobalt"],
        correctOptionIndex: 0,
      },
      {
        id: 56,
        text: "Which element is noted for increasing steel's resistance to shock and fatigue, even when added in very low percentages?",
        options: ["Vanadium", "Tungsten", "Manganese"],
        correctOptionIndex: 0,
      },
      {
        id: 57,
        text: "In the cyanide hardening process, what is the typical temperature used?",
        options: ["750°C", "900°C", "1,000°C"],
        correctOptionIndex: 1,
      },
    ],
  },
  "ferrous-non-ferrous-metals": {
    id: "ferrous-non-ferrous-metals",
    title: "Ferrous and Non-Ferrous Metals",
    description: "Assessment on Ferrous and Non-Ferrous Metals in aviation, including aluminum, magnesium, titanium, nickel, copper alloys and heat treatment processes. Answer all 40 questions about metal properties, heat treatment, and aerospace applications. Time limit: 40 minutes.",
    durationMinutes: 40,
    questions: [
      {
        id: 1,
        text: "What is the primary reason aluminum alloys are extensively used in aircraft construction?",
        options: ["High magnetic properties", "Excellent strength-to-weight ratio and corrosion resistance", "Superior electrical insulation"],
        correctOptionIndex: 1,
      },
      {
        id: 2,
        text: "Which aluminum alloy series uses copper as its major alloying element and is commonly used for aircraft skins and structures?",
        options: ["5xxx series", "2xxx series", "3xxx series"],
        correctOptionIndex: 1,
      },
      {
        id: 3,
        text: "What does the temper designation \"-T6\" indicate for an aluminum alloy?",
        options: ["Annealed condition", "Solution heat-treated and artificially aged", "Strain-hardened only"],
        correctOptionIndex: 1,
      },
      {
        id: 4,
        text: "Which aluminum alloys are generally non-heat-treatable?",
        options: ["2xxx, 6xxx, 7xxx", "1xxx, 3xxx, 5xxx", "8xxx, 4xxx, 9xxx"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "What is the purpose of cladding aluminum alloy sheets with pure aluminum?",
        options: ["To increase electrical conductivity", "To improve corrosion resistance", "To enhance magnetic properties"],
        correctOptionIndex: 1,
      },
      {
        id: 6,
        text: "What is the maximum recommended number of heat treatments for clad aluminum materials?",
        options: ["One", "Three", "Five"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "What is a significant hazard when machining magnesium?",
        options: ["It becomes brittle at low temperatures", "It is highly flammable, especially as fine dust or swarf", "It emits toxic fumes when annealed"],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "Which element is the primary alloying agent in the 5xxx series aluminum alloys?",
        options: ["Silicon", "Magnesium", "Zinc"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "What does the alloy designation \"AZ31A-T4\" indicate for a magnesium alloy?",
        options: ["Contains 3% aluminum and 1% zinc, solution heat-treated", "Contains 31% aluminum, annealed", "Contains aluminum and zirconium, strain-hardened"],
        correctOptionIndex: 0,
      },
      {
        id: 10,
        text: "What is a key advantage of titanium alloys in aerospace applications?",
        options: ["Low cost and high availability", "High strength-to-weight ratio and excellent corrosion resistance", "High thermal and electrical conductivity"],
        correctOptionIndex: 1,
      },
      {
        id: 11,
        text: "Which of the following should NOT be used with titanium components due to risk of embrittlement?",
        options: ["Cadmium-coated fasteners", "Stainless steel fasteners", "Aluminum rivets"],
        correctOptionIndex: 0,
      },
      {
        id: 12,
        text: "What is a correct method for extinguishing a titanium fire?",
        options: ["Water or foam", "Dry asbestos wool and chalk powder", "Carbon dioxide (CO₂)"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "Which nickel alloy is known for its use in gas turbine blades and high-temperature applications?",
        options: ["Monel", "Nimonic", "Brass"],
        correctOptionIndex: 1,
      },
      {
        id: 14,
        text: "What is a primary characteristic of Inconel alloys?",
        options: ["High electrical conductivity", "Excellent heat and corrosion resistance", "Lightweight and low density"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "Which alloy is a nickel-copper combination often used for corrosion-resistant rivets?",
        options: ["Hastelloy", "K-Monel", "Incoloy"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What is a common use of beryllium bronze in aircraft?",
        options: ["Electrical wiring", "High-strength bearings and bushings", "Fuel lines"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "Why is Tungum alloy no longer used in aircraft hydraulic systems?",
        options: ["It is too heavy", "It becomes brittle over time", "It corrodes easily"],
        correctOptionIndex: 1,
      },
      {
        id: 18,
        text: "What is the greenish layer that forms on copper called?",
        options: ["Rust", "Verdigris", "Galvanic coating"],
        correctOptionIndex: 1,
      },
      {
        id: 19,
        text: "Why is depleted uranium (DU) handled with special precautions?",
        options: ["It is highly flammable", "It is toxic both chemically and radiologically", "It corrodes rapidly in air"],
        correctOptionIndex: 1,
      },
      {
        id: 20,
        text: "What is a primary use of cadmium in aviation?",
        options: ["As a balance weight material", "As a protective coating on steel fasteners", "As a high-temperature alloy in engines"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "According to the certification table, which license category has NO knowledge level requirement for testing ferrous materials for hardness, tensile strength, fatigue strength, and impact resistance?",
        options: ["A", "B1/B3", "B2/B2L"],
        correctOptionIndex: 0,
      },
      {
        id: 22,
        text: "In the stress-strain diagram, what does the \"necking\" region indicate?",
        options: ["The point where the material returns to its original length upon unloading.", "The onset of plastic deformation where strain increases without an increase in stress.", "The point where uniform plastic extension ends and localized deformation begins before fracture."],
        correctOptionIndex: 2,
      },
      {
        id: 23,
        text: "Which of the following statements about the microstructure of steel is FALSE?",
        options: ["Ferrite contains no more than 0.006% carbon and is soft and ductile.", "Cementite contains 6.67% carbon and is hard and brittle.", "Pearlite is a laminated structure of ferrite and austenite."],
        correctOptionIndex: 2,
      },
      {
        id: 24,
        text: "If a steel component is heated to 950°C and then quenched in oil, what is the most likely resulting microstructure if it contains 0.8% carbon?",
        options: ["Martensite", "Pearlite", "Austenite"],
        correctOptionIndex: 0,
      },
      {
        id: 25,
        text: "Which alloying element combination is primarily used to achieve \"austenitic\" stainless steel with non-magnetic properties?",
        options: ["18% Chromium, 8% Nickel", "12% Chromium, 0.5% Carbon", "15% Chromium, 5% Nickel"],
        correctOptionIndex: 0,
      },
      {
        id: 26,
        text: "Based on the table of alloying element effects, which element DECREASES machinability?",
        options: ["Chromium", "Molybdenum", "Nickel"],
        correctOptionIndex: 0,
      },
      {
        id: 27,
        text: "In the context of fatigue, what is represented by the \"ground-air-ground\" cycle?",
        options: ["The stress fluctuation during a single flight from takeoff to landing.", "The repeated pressurization and depressurization of the cabin.", "The transition from ground handling to in-flight maneuvering and back."],
        correctOptionIndex: 2,
      },
      {
        id: 28,
        text: "Which heat treatment process would you use to restore the crystalline structure of a cold-worked steel part that has become brittle, without making it as soft as fully annealed material?",
        options: ["Tempering", "Normalizing", "Case Hardening"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "According to the phase-equilibrium diagram for iron-carbon, what is the approximate lower critical temperature (A1) for steel?",
        options: ["723°C", "950°C", "1,200°C"],
        correctOptionIndex: 0,
      },
      {
        id: 30,
        text: "Which of the following statements about 9Ni-4Co-0.30C steel is FALSE?",
        options: ["It is used for elevated temperature applications up to 900°F.", "It is a precipitation-hardened stainless steel.", "It is heat treated to 220-240 KSI."],
        correctOptionIndex: 1,
      },
      {
        id: 31,
        text: "In the cyanide hardening process, why is sodium cyanide considered dangerous?",
        options: ["It releases toxic fumes when heated.", "It is highly poisonous and requires strict safety precautions.", "It is highly corrosive to steel."],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is the primary advantage of nitriding over carburizing for case hardening?",
        options: ["It produces a thicker hardened case.", "It operates at a lower temperature, reducing distortion.", "It is faster and cheaper."],
        correctOptionIndex: 1,
      },
      {
        id: 33,
        text: "Which steel would be LEAST suitable for a highly stressed aircraft fitting requiring both high strength and good corrosion resistance?",
        options: ["15-5PH", "4340M", "304 Stainless"],
        correctOptionIndex: 2,
      },
      {
        id: 34,
        text: "If a steel has an AISI/SAE designation of 52100, what is its primary alloying element and approximate carbon content?",
        options: ["Chromium, 1.00% carbon", "Molybdenum, 0.30% carbon", "Nickel, 1.00% carbon"],
        correctOptionIndex: 0,
      },
      {
        id: 35,
        text: "In the context of creep, what does the \"steady-state creep\" phase indicate?",
        options: ["The initial elastic deformation under load.", "A constant rate of deformation over time.", "The final rapid deformation leading to rupture."],
        correctOptionIndex: 1,
      },
      {
        id: 36,
        text: "What is the primary reason for using vacuum remelt steels (like 4330M and 4340M) in critical aircraft components?",
        options: ["To improve magnetic properties.", "To enhance purity and mechanical properties (ductility, fatigue resistance).", "To reduce weight."],
        correctOptionIndex: 1,
      },
      {
        id: 37,
        text: "According to the module, which of the following is NOT a typical application for 17-4PH stainless steel?",
        options: ["Control levers and fittings", "Landing gear legs", "Cast housings"],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "Which property is NOT typically associated with martensitic stainless steels?",
        options: ["Magnetic", "Hardenable by heat treatment", "Non-responsive to heat treatment"],
        correctOptionIndex: 2,
      },
      {
        id: 39,
        text: "In flame hardening, why is the quenching water jet integrated into the torch assembly?",
        options: ["To cool the torch and prevent overheating.", "To immediately quench the heated surface before the core temperature rises.", "To provide a protective steam layer."],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What does the \"T\" in the tempering colour chart (e.g., \"Straw\" at 430°F) indicate?",
        options: ["The temperature at which the steel should be quenched.", "The colour the steel surface oxidizes to at that temperature, used for temperature estimation.", "The colour of the steel after quenching."],
        correctOptionIndex: 1,
      },
    ],
  },
  "mathematics": {
    id: "mathematics",
    title: "Mathematics Symbols and Concepts",
    description: "Assessment on mathematical symbols, notation, and fundamental concepts. Answer all 114 questions about mathematical notation, number types, geometry, and operations. Time limit: 114 minutes.",
    durationMinutes: 114,
    questions: [
      { id: 1, text: "What does the symbol \"mod\" represent?", options: ["Multiplication", "Division", "Remainder calculation"], correctOptionIndex: 2 },
      { id: 2, text: "Which symbol means \"greater than or equal to\"?", options: [">", "≥", "≤"], correctOptionIndex: 1 },
      { id: 3, text: "What does the symbol \"±\" mean?", options: ["Plus and minus operations", "Multiplication", "Equals"], correctOptionIndex: 0 },
      { id: 4, text: "Which symbol is used for multiplication?", options: ["/", "÷", "×"], correctOptionIndex: 2 },
      { id: 5, text: "What does \"√a\" represent?", options: ["Cube root", "Square root", "Fourth root"], correctOptionIndex: 1 },
      { id: 6, text: "Which set of numbers includes {0, 1, 2, 3, …}?", options: ["Natural numbers", "Whole numbers", "Integers"], correctOptionIndex: 1 },
      { id: 7, text: "What are numbers that can be expressed as a ratio of two integers called?", options: ["Irrational numbers", "Rational numbers", "Real numbers"], correctOptionIndex: 1 },
      { id: 8, text: "Which type of number includes both real and imaginary parts?", options: ["Complex numbers", "Integers", "Natural numbers"], correctOptionIndex: 0 },
      { id: 9, text: "What does the symbol \"⊥\" represent?", options: ["Parallel lines", "Perpendicular lines", "Congruent shapes"], correctOptionIndex: 1 },
      { id: 10, text: "Which symbol represents an angle?", options: ["∆", "∠", "∥"], correctOptionIndex: 1 },
      { id: 11, text: "What does \"π\" represent?", options: ["Distance between two points", "Ratio of circumference to diameter of a circle", "Right angle"], correctOptionIndex: 1 },
      { id: 12, text: "Which symbol indicates that two shapes are similar but not necessarily the same size?", options: ["≅", "∼", "∥"], correctOptionIndex: 1 },
      { id: 13, text: "What does the symbol \"∝\" mean?", options: ["Approximately equal", "Proportional to", "Infinity"], correctOptionIndex: 1 },
      { id: 14, text: "What does \"∑\" represent?", options: ["Factorial", "Summation", "Absolute value"], correctOptionIndex: 1 },
      { id: 15, text: "Which symbol means \"much less than\"?", options: ["≫", "≈", "≪"], correctOptionIndex: 2 },
      { id: 16, text: "What does \"f(x)\" denote?", options: ["A constant", "A function of x", "A variable"], correctOptionIndex: 1 },
      { id: 17, text: "Which symbol rounds a number down to the nearest integer?", options: ["⌈x⌉", "⌊x⌋", "|x|"], correctOptionIndex: 1 },
      { id: 18, text: "Which symbol means \"not equal to\"?", options: ["=", "≠", "≈"], correctOptionIndex: 1 },
      { id: 19, text: "What does the symbol \"≤\" represent?", options: ["Less than", "Greater than or equal to", "Less than or equal to"], correctOptionIndex: 2 },
      { id: 20, text: "Which symbol is used for division in the form of a fraction (horizontal line)?", options: ["÷", "/", "—"], correctOptionIndex: 2 },
      { id: 21, text: "What does \"ppm\" stand for?", options: ["Parts-per-million", "Percent-per-meter", "Points-per-minute"], correctOptionIndex: 0 },
      { id: 22, text: "What is the cube root of 8?", options: ["2", "4", "±2"], correctOptionIndex: 0 },
      { id: 23, text: "Which set of numbers includes negative counting numbers and zero?", options: ["Natural numbers", "Whole numbers", "Integers"], correctOptionIndex: 2 },
      { id: 24, text: "What are real numbers that are not rational called?", options: ["Irrational numbers", "Imaginary numbers", "Complex numbers"], correctOptionIndex: 0 },
      { id: 25, text: "What does the symbol \"∡\" represent?", options: ["Angle", "Measured angle", "Right angle"], correctOptionIndex: 1 },
      { id: 26, text: "What is the symbol for parallel lines?", options: ["∥", "⊥", "≅"], correctOptionIndex: 0 },
      { id: 27, text: "Which symbol represents a line segment from point A to point B?", options: ["AB (with overline)", "→", "⌒"], correctOptionIndex: 0 },
      { id: 28, text: "What does \"rad\" stand for?", options: ["Radius", "Radians", "Right angle degree"], correctOptionIndex: 1 },
      { id: 29, text: "What does the symbol \"≡\" mean?", options: ["Approximately equal", "Identical to (equivalence)", "Proportional to"], correctOptionIndex: 1 },
      { id: 30, text: "What is the symbol for infinity?", options: ["∞", "≈", "∝"], correctOptionIndex: 0 },
      { id: 31, text: "What does the exclamation mark (!) represent in mathematics?", options: ["Absolute value", "Factorial", "Summation"], correctOptionIndex: 1 },
      { id: 32, text: "Which symbol represents the ceiling function, rounding up to the nearest integer?", options: ["⌊x⌋", "⌈x⌉", "|x|"], correctOptionIndex: 1 },
      { id: 33, text: "What does the symbol \"∓\" (minus-plus) represent?", options: ["Multiplication", "Both minus and plus operations", "Remainder calculation"], correctOptionIndex: 1 },
      { id: 34, text: "Which symbol is used for multiplication as an asterisk?", options: ["×", "*", "·"], correctOptionIndex: 1 },
      { id: 35, text: "What does the symbol \"·\" (dot) indicate in arithmetic?", options: ["Decimal point", "Division", "Multiplication"], correctOptionIndex: 2 },
      { id: 36, text: "Which symbol represents division in the form of a slash?", options: ["÷", "—", "/"], correctOptionIndex: 2 },
      { id: 37, text: "What does \"ppb\" stand for?", options: ["Parts-per-billion", "Percent-per-billion", "Points-per-billion"], correctOptionIndex: 0 },
      { id: 38, text: "What is the fourth root of 16?", options: ["2", "±2", "4"], correctOptionIndex: 1 },
      { id: 39, text: "Which symbol represents the n-th root (radical)?", options: ["√", "∛", "ⁿ√"], correctOptionIndex: 2 },
      { id: 40, text: "Which numbers are referred to as the counting numbers {1, 2, 3, …}?", options: ["Whole numbers", "Natural numbers", "Integers"], correctOptionIndex: 1 },
      { id: 41, text: "What type of numbers include both rational and irrational numbers?", options: ["Real numbers", "Complex numbers", "Imaginary numbers"], correctOptionIndex: 0 },
      { id: 42, text: "Which numbers are defined as the product of a real number and the square root of -1?", options: ["Imaginary numbers", "Complex numbers", "Irrational numbers"], correctOptionIndex: 0 },
      { id: 43, text: "What does the symbol \" ' \" (arcminute) represent?", options: ["1/60 of a degree", "1/60 of a radian", "1/360 of a circle"], correctOptionIndex: 0 },
      { id: 44, text: "Which symbol represents a ray starting from point A?", options: ["AB (line segment)", "→", "⌒"], correctOptionIndex: 1 },
      { id: 45, text: "What is the symbol for an arc from point A to point B?", options: ["↷", "⌒", "⇄"], correctOptionIndex: 1 },
      { id: 46, text: "In geometry, what does the symbol \"Δ\" represent?", options: ["Change or difference", "Triangle", "Distance"], correctOptionIndex: 1 },
      { id: 47, text: "Which notation represents the distance between points x and y?", options: ["d(x,y)", "|x-y|", "xy"], correctOptionIndex: 1 },
      { id: 48, text: "What is the symbol for a right angle (90°)?", options: ["∠", "⊥", "∟"], correctOptionIndex: 2 },
      { id: 49, text: "What does the symbol \"≅\" mean in geometry?", options: ["Similar", "Congruent", "Parallel"], correctOptionIndex: 1 },
      { id: 50, text: "What does the symbol \"~\" indicate in algebra?", options: ["Approximately equal (weak approximation)", "Proportional to", "Similarity"], correctOptionIndex: 0 },
      { id: 51, text: "Which symbol means \"much greater than\"?", options: ["≪", "≈", "≫"], correctOptionIndex: 2 },
      { id: 52, text: "What do braces \"{ }\" represent in algebra?", options: ["Parentheses for calculation", "Set notation", "Absolute value"], correctOptionIndex: 1 },
      { id: 53, text: "What does a single vertical bar \"|\" denote?", options: ["Factorial", "Absolute value", "Summation"], correctOptionIndex: 1 },
      { id: 54, text: "In algebra, what does the symbol \"Δ\" represent?", options: ["Triangle", "Change or difference", "Summation"], correctOptionIndex: 1 },
      { id: 55, text: "What is the value of 3±5 when the plus operation is used?", options: ["8", "–2", "Both 8 and –2"], correctOptionIndex: 0 },
      { id: 56, text: "If a number is a whole number, which of the following is necessarily true?", options: ["It is positive.", "It is non-negative.", "It is an integer."], correctOptionIndex: 1 },
      { id: 57, text: "In the expression 2^3, what does the caret (^) indicate?", options: ["Multiplication", "Exponentiation", "Division"], correctOptionIndex: 1 },
      { id: 58, text: "Which of the following is the correct notation for the cube root of 8?", options: ["√8", "∛8", "∜8"], correctOptionIndex: 1 },
      { id: 59, text: "How many degrees are in a right angle?", options: ["90°", "180°", "360°"], correctOptionIndex: 0 },
      { id: 60, text: "What does the symbol \"≈\" mean?", options: ["Approximately equal", "Identical to", "Proportional to"], correctOptionIndex: 0 },
      { id: 61, text: "Which of the following numbers is rational?", options: ["√2", "π", "0.75"], correctOptionIndex: 2 },
      { id: 62, text: "What is the purpose of parentheses in an arithmetic expression?", options: ["To indicate multiplication", "To group operations that should be performed first", "To denote a set"], correctOptionIndex: 1 },
      { id: 63, text: "If two lines are perpendicular, what is the measure of the angle between them?", options: ["0°", "90°", "180°"], correctOptionIndex: 1 },
      { id: 64, text: "In set notation, what does the ellipsis (…) indicate?", options: ["The set is empty", "The pattern continues indefinitely", "The set is finite"], correctOptionIndex: 1 },
      { id: 65, text: "If x=5 and y=3, what is the value of |x-y|?", options: ["2", "8", "15"], correctOptionIndex: 0 },
      { id: 66, text: "Evaluate: ⌈3.2⌉+⌊2.7⌋", options: ["5", "6", "7"], correctOptionIndex: 1 },
      { id: 67, text: "What is 10% of 50?", options: ["5", "10", "50"], correctOptionIndex: 0 },
      { id: 68, text: "If a circle has radius r, its circumference is given by:", options: ["πr", "2πr", "πr^2"], correctOptionIndex: 1 },
      { id: 69, text: "Which of the following represents a complex number with both real and imaginary parts?", options: ["3", "-5i", "2+3i"], correctOptionIndex: 2 },
      { id: 70, text: "Which symbol is used to denote arcsecond?", options: ["'", "\"", "°"], correctOptionIndex: 1 },
      { id: 71, text: "In the expression f(x)=x^2, what is f(3)?", options: ["6", "9", "3"], correctOptionIndex: 1 },
      { id: 72, text: "How many arcminutes are in one degree?", options: ["60", "360", "3600"], correctOptionIndex: 0 },
      { id: 73, text: "What is the value of 2^3?", options: ["6", "8", "9"], correctOptionIndex: 1 },
      { id: 74, text: "What is the measure in radians of a full circle (360°)?", options: ["π rad", "2π rad", "180 rad"], correctOptionIndex: 1 },
      { id: 75, text: "Given the expression 3∓5, which calculation pair is correct?", options: ["3-5=-2 and 3+5=8", "3-5=8 and 3+5=-2", "3×5=15 and 3÷5=0.6"], correctOptionIndex: 0 },
      { id: 76, text: "A number can be expressed as a/b where a and b are integers and b≠0. Which type of number must it be?", options: ["Always rational", "Always real", "Always integer"], correctOptionIndex: 0 },
      { id: 77, text: "If |x-7|=3, what are the possible values of x?", options: ["x=4 only", "x=10 only", "x=4 or x=10"], correctOptionIndex: 2 },
      { id: 78, text: "What does ∑_{i=1}^{4} (2i+1) equal?", options: ["24", "20", "18"], correctOptionIndex: 0 },
      { id: 79, text: "In geometry, if △ABC∼△XYZ, which of the following must be true?", options: ["Corresponding angles are equal, sides are proportional.", "Corresponding sides are equal, angles may differ.", "Both shapes have the same area."], correctOptionIndex: 0 },
      { id: 80, text: "Which of these numbers is both real and imaginary?", options: ["5", "-3i", "0"], correctOptionIndex: 2 },
      { id: 81, text: "The expression ⌊4.9⌋+⌈-2.3⌉ equals:", options: ["2", "3", "4"], correctOptionIndex: 0 },
      { id: 82, text: "If y∝x and k is the constant of proportionality, which equation is correct?", options: ["y=k+x", "y=k/x", "y=kx"], correctOptionIndex: 2 },
      { id: 83, text: "What is the value of 10 ppm × 5000?", options: ["0.05", "0.5", "50"], correctOptionIndex: 0 },
      { id: 84, text: "The fourth root of 81 is:", options: ["3 only", "±3", "9"], correctOptionIndex: 1 },
      { id: 85, text: "Which symbol set indicates \"calculate expression inside first\" in the order of operations?", options: ["(), [], {}", "+, -, ×, ÷", "=, ≠, >, <"], correctOptionIndex: 0 },
      { id: 86, text: "If ∠ABC=45° and ∠DBC is its complement, what is ∠DBC?", options: ["45°", "90°", "135°"], correctOptionIndex: 0 },
      { id: 87, text: "What does the symbol \"∡\" represent in the PDF?", options: ["Measured angle", "Right angle", "Parallel lines"], correctOptionIndex: 0 },
      { id: 88, text: "Evaluate 4!", options: ["16", "24", "256"], correctOptionIndex: 1 },
      { id: 89, text: "Which number type includes √2 but not 1/3?", options: ["Irrational numbers", "Rational numbers", "Integers"], correctOptionIndex: 0 },
      { id: 90, text: "If f(x)=2x+3, what is f^{-1}(7)?", options: ["2", "17", "5"], correctOptionIndex: 0 },
      { id: 91, text: "In the context of tolerance, 5±0.1 means:", options: ["Exactly 5", "Between 4.9 and 5.1 inclusive", "Between 4.5 and 5.5"], correctOptionIndex: 1 },
      { id: 92, text: "What is the principal cube root of -8?", options: ["-2", "2", "No real root"], correctOptionIndex: 0 },
      { id: 93, text: "If △ABC≅△DEF, which is necessarily true?", options: ["Same area only", "Same shape and size", "Same perimeter only"], correctOptionIndex: 1 },
      { id: 94, text: "Which symbol is used to denote \"much less than\"?", options: ["≪", "≫", "≈"], correctOptionIndex: 0 },
      { id: 95, text: "The symbol \"∓\" (minus-plus) is explicitly defined in the PDF as:", options: ["The same as ± but in reverse order", "Both minus and plus operations, where the upper sign is minus and the lower is plus", "A tolerance indicator for dimensions"], correctOptionIndex: 1 },
      { id: 96, text: "If a mod b=0, which of the following must be true?", options: ["a is less than b", "a is divisible by b", "a and b are both prime"], correctOptionIndex: 1 },
      { id: 97, text: "The radical expression ⁿ√a is equivalent to:", options: ["a^(1/n)", "a^n", "√a⋅n"], correctOptionIndex: 0 },
      { id: 98, text: "A number that can be written as a+bi where a and b are real and b≠0 is strictly called:", options: ["An imaginary number", "A non-real complex number", "A pure imaginary number"], correctOptionIndex: 1 },
      { id: 99, text: "In geometric notation, the symbol \"∡\" is specifically used to indicate:", options: ["An angle that has been measured numerically", "Any angle formed by two rays", "An angle of 90 degrees"], correctOptionIndex: 0 },
      { id: 100, text: "How many arcseconds are in 2.5 degrees?", options: ["9000", "150", "900"], correctOptionIndex: 0 },
      { id: 101, text: "Geometric congruence (≅) implies that two figures have:", options: ["The same area and perimeter", "Identical shape and size", "Proportional sides and equal angles"], correctOptionIndex: 1 },
      { id: 102, text: "The tilde (~) is defined in the algebra section as:", options: ["A weak approximation", "A strong approximation", "Proportionality"], correctOptionIndex: 0 },
      { id: 103, text: "The value of ⌊-7.8⌋+⌈3.2⌉ is:", options: ["–5", "–4", "–3"], correctOptionIndex: 1 },
      { id: 104, text: "In sigma notation, ∑_{k=1}^{n} k represents the sum of:", options: ["The first n integers", "The squares of the first n integers", "The reciprocals of the first n integers"], correctOptionIndex: 0 },
      { id: 105, text: "If y∝x and when x=4, y=12, what is the constant of proportionality k?", options: ["3", "8", "48"], correctOptionIndex: 0 },
      { id: 106, text: "Which of the following is an irrational number?", options: ["0.3̄ (repeating)", "√16", "∛2"], correctOptionIndex: 2 },
      { id: 107, text: "A concentration of 50 ppm means:", options: ["50 parts per hundred", "50 parts per million", "0.005%"], correctOptionIndex: 1 },
      { id: 108, text: "In geometry, the symbol \"L\" denotes:", options: ["A line", "A right angle (exactly 90°)", "An arc length"], correctOptionIndex: 1 },
      { id: 109, text: "The expression |x|=0 has how many real solutions?", options: ["0", "1", "2"], correctOptionIndex: 1 },
      { id: 110, text: "The factorial notation n! is defined as the product of:", options: ["All integers from 1 to n", "All even numbers up to n", "All prime numbers up to n"], correctOptionIndex: 0 },
      { id: 111, text: "According to the PDF, which number is both real and imaginary?", options: ["1", "–i", "0"], correctOptionIndex: 2 },
      { id: 112, text: "If two triangles are similar (∼), their corresponding sides are:", options: ["Equal", "Proportional", "Unrelated"], correctOptionIndex: 1 },
      { id: 113, text: "The infinity symbol (∞) is also called:", options: ["Lemniscate", "Omega", "Sigma"], correctOptionIndex: 0 },
      { id: 114, text: "For the ceiling function, ⌈-1.5⌉ equals:", options: ["–2", "–1", "1"], correctOptionIndex: 1 },
    ],
  },
  "human-factors": {
    id: "human-factors",
    title: "Human Factors",
    description: "Assessment on Human Factors in Aviation Maintenance. Answer all 45 review questions on human factors, human performance and social psychology. Time limit: 45 minutes.",
    durationMinutes: 45,
    questions: [
      {
        id: 1,
        text: "Why must human factors be taken into account in aviation maintenance?",
        options: ["Because maintenance personnel have no impact on system safety.", "To ensure equipment never requires maintenance.", "Because humans are a key point of interaction in systems, and their limitations can affect safety and reliability."],
        correctOptionIndex: 2,
      },
      {
        id: 2,
        text: "Approximately what percentage of aircraft accidents are primarily caused by flight crew actions?",
        options: ["20%", "Over 60%", "4%"],
        correctOptionIndex: 1,
      },
      {
        id: 3,
        text: "In accident statistics, maintenance is identified as the primary cause in what percentage of hull loss accidents?",
        options: ["4%", "12%", "22%"],
        correctOptionIndex: 0,
      },
      {
        id: 4,
        text: "What is one significant financial cost of a maintenance error?",
        options: ["Increased passenger satisfaction", "Flight delays or cancellations", "Reduced training requirements"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "What is 'human factors' in aviation maintenance?",
        options: ["The study of human capabilities and limitations in the workplace", "Only related to cockpit design and crew resource management", "A term used only for equipment design"],
        correctOptionIndex: 0,
      },
      {
        id: 6,
        text: "Which accident helped bring human factors in maintenance into sharp focus?",
        options: ["Japan Airlines 1985", "Aloha Airlines 1988", "British Airways 1990"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "What is a unique human factors issue in aviation maintenance?",
        options: ["Maintenance engineers work only in comfortable office environments.", "Maintenance technicians often work in hazardous, confined, or extreme temperature environments.", "Maintenance personnel do not require communication skills."],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "Which type of maintenance task is performed in response to unplanned events?",
        options: ["Scheduled maintenance", "Unscheduled maintenance", "Routine inspection"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "In the 1985 Japan Airlines Boeing 747 accident, what failed due to a previous repair error?",
        options: ["The rear pressure bulkhead", "The landing gear", "The flight control system"],
        correctOptionIndex: 0,
      },
      {
        id: 10,
        text: "In the Eastern Airlines L-1011 incident, what was missing from the magnetic chip detectors?",
        options: ["O-rings", "Electrical wiring", "Safety tags"],
        correctOptionIndex: 0,
      },
      {
        id: 11,
        text: "What was the primary cause of the Aloha Airlines Boeing 737 accident in 1988?",
        options: ["Failure to detect disbonding and fatigue damage in the fuselage", "Incorrect fuel loading", "Pilot error during takeoff"],
        correctOptionIndex: 0,
      },
      {
        id: 12,
        text: "In the British Airways BAC 1-11 accident, what was the cause of the windscreen blowout?",
        options: ["Incorrect window sealant", "Installation of undersized bolts", "Excessive cabin pressure"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "In the Air Midwest Beech 1900 accident, what was incorrectly rigged?",
        options: ["Elevator control cables", "Rudder cables", "Aileron controls"],
        correctOptionIndex: 0,
      },
      {
        id: 14,
        text: "What is the 'error chain' in aviation?",
        options: ["A single mechanical failure causing an accident", "A series of human-factor-related errors leading to an accident", "A sequence of automated system warnings"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "What is Murphy's Law?",
        options: ["'If anything can go right, it will.'", "'If anything can go wrong, it will.'", "'Errors only happen to careless people.'"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What part of the eye is responsible for focusing light onto the retina?",
        options: ["Retina", "Lens", "Cornea"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "What is myopia?",
        options: ["Short-sightedness", "Long-sightedness", "Astigmatism"],
        correctOptionIndex: 0,
      },
      {
        id: 18,
        text: "Where is the blind spot located in the eye?",
        options: ["Where the optic nerve meets the retina", "In the center of the cornea", "At the edge of the iris"],
        correctOptionIndex: 0,
      },
      {
        id: 19,
        text: "Which factor does NOT affect visual acuity?",
        options: ["Age", "Lighting", "Shoe size"],
        correctOptionIndex: 2,
      },
      {
        id: 20,
        text: "What is presbyopia?",
        options: ["A clouding of the lens", "Age-related long-sightedness", "Color blindness"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "What part of the ear contains the cochlea?",
        options: ["Outer ear", "Middle ear", "Inner ear"],
        correctOptionIndex: 2,
      },
      {
        id: 22,
        text: "What noise level is considered the threshold of pain?",
        options: ["90 dB", "100 dB", "120 dB"],
        correctOptionIndex: 2,
      },
      {
        id: 23,
        text: "What is presbycusis?",
        options: ["Noise-induced hearing loss", "Age-related hearing loss", "Temporary hearing loss from loud noise"],
        correctOptionIndex: 1,
      },
      {
        id: 24,
        text: "Which memory type lasts less than one second?",
        options: ["Sensory memory", "Short-term memory", "Long-term memory"],
        correctOptionIndex: 0,
      },
      {
        id: 25,
        text: "How many items can short-term memory typically hold?",
        options: ["3–4", "7±2", "15–20"],
        correctOptionIndex: 1,
      },
      {
        id: 26,
        text: "What is 'chunking' in memory?",
        options: ["Grouping information into meaningful units", "Repeating information over and over", "Forgetting unnecessary details"],
        correctOptionIndex: 0,
      },
      {
        id: 27,
        text: "Which is NOT a type of attention?",
        options: ["Selective attention", "Divided attention", "Permanent attention"],
        correctOptionIndex: 2,
      },
      {
        id: 28,
        text: "What is confirmation bias?",
        options: ["Ignoring all new information", "Seeking information that confirms existing beliefs", "Always changing your mind"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "What can help prevent memory-related errors in maintenance?",
        options: ["Using manuals and temporary notes", "Relying only on experience", "Avoiding written procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 30,
        text: "What is situation awareness in maintenance?",
        options: ["Understanding the current system status and predicting future states", "Only knowing your own task", "Memorizing all past procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 31,
        text: "What is claustrophobia?",
        options: ["Fear of heights", "Abnormal fear of enclosed spaces", "Fear of loud noises"],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is social loafing?",
        options: ["Working harder in a group", "Reducing effort when working in a group", "Always taking leadership in a team"],
        correctOptionIndex: 1,
      },
      {
        id: 33,
        text: "What is diffusion of responsibility?",
        options: ["Taking full responsibility as an individual", "Feeling less responsible in a group setting", "Assigning tasks clearly in a team"],
        correctOptionIndex: 1,
      },
      {
        id: 34,
        text: "What is the Hawthorne effect?",
        options: ["Improved performance due to increased attention from management", "Reduced performance due to poor lighting", "Peer pressure leading to errors"],
        correctOptionIndex: 0,
      },
      {
        id: 35,
        text: "Which is the highest level in Maslow's hierarchy of needs?",
        options: ["Safety needs", "Esteem needs", "Self-actualization"],
        correctOptionIndex: 2,
      },
      {
        id: 36,
        text: "What is extrinsic motivation?",
        options: ["Motivation driven by external rewards or punishments", "Motivation from personal satisfaction", "Motivation from team recognition only"],
        correctOptionIndex: 0,
      },
      {
        id: 37,
        text: "What did Solomon Asch's conformity experiments demonstrate?",
        options: ["People always make independent judgments.", "People often conform to group opinion even if it's wrong.", "Groups improve decision-making accuracy."],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "What is a 'just culture'?",
        options: ["A no-blame culture where all errors are ignored", "A culture where the line between acceptable and unacceptable behavior is clear", "A culture where all errors are punished"],
        correctOptionIndex: 1,
      },
      {
        id: 39,
        text: "According to Reason, what is a key component of a safety culture?",
        options: ["Ignoring near-misses", "A good reporting culture", "Punishing all errors"],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What is the 'substitution test' used for?",
        options: ["To determine if an error could have been made by others in the same situation", "To replace faulty equipment", "To test new procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 41,
        text: "Which is NOT one of the 'Big Five' personality traits?",
        options: ["Openness", "Conscientiousness", "Perfectionism"],
        correctOptionIndex: 2,
      },
      {
        id: 42,
        text: "Which personality type is often associated with accident proneness?",
        options: ["Stable introvert", "Unstable extrovert", "Stable extrovert"],
        correctOptionIndex: 1,
      },
      {
        id: 43,
        text: "What is a key element of effective teamwork?",
        options: ["Working in isolation", "Good communication", "Avoiding task delegation"],
        correctOptionIndex: 1,
      },
      {
        id: 44,
        text: "What is a supervisor's role in maintenance?",
        options: ["Only doing hands-on tasks", "Monitoring performance and maintaining safety culture", "Avoiding all management duties"],
        correctOptionIndex: 1,
      },
      {
        id: 45,
        text: "What does MRM stand for?",
        options: ["Maintenance Repair Manual", "Maintenance Resource Management", "Mandatory Regulatory Measures"],
        correctOptionIndex: 1,
      },
    ],
  },
  "human-factors-comprehensive": {
    id: "human-factors-comprehensive",
    title: "Human Factors in Maintenance - Comprehensive",
    description: "Comprehensive assessment on human factors in aviation maintenance covering general concepts, human performance, social psychology, and physical environment factors. Answer all 137 questions about maintenance safety, error prevention, and organizational culture. Time limit: 100 minutes.",
    durationMinutes: 100,
    questions: [
      { id: 1, text: "What is the primary focus of human factors in aviation maintenance?", options: ["Designing more efficient aircraft", "Optimizing the relationship between personnel and systems to improve safety", "Reducing maintenance costs through automation"], correctOptionIndex: 1 },
      { id: 2, text: "According to statistics, what percentage of accidents are primarily caused by maintenance?", options: ["4%", "20%", "60%"], correctOptionIndex: 0 },
      { id: 3, text: "What does the \"error chain\" concept refer to?", options: ["A series of mechanical failures leading to an accident", "Multiple human-factor-related events that contribute to an accident", "A single human error causing a catastrophic failure"], correctOptionIndex: 1 },
      { id: 4, text: "Which accident highlighted the danger of maintenance errors remaining dormant for long periods?", options: ["Aloha Airlines, 1988", "Japan Airlines, 1985", "British Airways, 1990"], correctOptionIndex: 1 },
      { id: 5, text: "Murphy's Law is best summarized as:", options: ["\"If anything can go wrong, it will.\"", "\"Human error is inevitable.\"", "\"Technology will always fail eventually.\""], correctOptionIndex: 0 },
      { id: 6, text: "What unique human factors issue do maintenance personnel face compared to pilots?", options: ["They can leave work with no future responsibility", "Their work must remain safe for months or years into the future", "They work in climate-controlled environments"], correctOptionIndex: 1 },
      { id: 7, text: "In the Eastern Airlines L-1011 incident, what was the root cause of the engine oil leaks?", options: ["Faulty engine design", "Magnetic chip detectors installed without O-rings", "Improper pilot handling"], correctOptionIndex: 1 },
      { id: 8, text: "The Air Midwest Beech 1900D crash was partly caused by:", options: ["Incorrect elevator cable rigging", "Pilot error during takeoff", "Structural failure of the wing"], correctOptionIndex: 0 },
      { id: 9, text: "What did the Aloha Airlines accident in 1988 primarily highlight?", options: ["The importance of cockpit communication", "Human factors in inspection and fatigue damage detection", "The dangers of volcanic ash"], correctOptionIndex: 1 },
      { id: 10, text: "According to statistics, what has been the trend in accidents caused by human error over time?", options: ["They have significantly decreased since 1900", "They have remained consistently high", "They now account for about 80% of accidents"], correctOptionIndex: 2 },
      { id: 11, text: "What percentage of accidents in the 1986 U.S. study were linked to maintenance and inspection deficiencies?", options: ["4%", "12%", "26%"], correctOptionIndex: 1 },
      { id: 12, text: "In the British Airways BAC 1-11 incident, why did the windscreen blow out?", options: ["Incorrect bolt diameter used (84 of 90 bolts too small)", "Pilot error during pressurization", "Manufacturing defect in the windscreen"], correctOptionIndex: 0 },
      { id: 13, text: "What type of maintenance error was highlighted in the Japan Airlines 747 accident?", options: ["Improper documentation", "Fatigue fracture in a poorly repaired pressure bulkhead", "Faulty engine installation"], correctOptionIndex: 1 },
      { id: 14, text: "According to the document, what is a key difference between maintenance personnel and pilots regarding error consequences?", options: ["Pilots' errors have immediate impact; maintenance errors may remain latent", "Maintenance errors are always immediately apparent", "Pilots are never held responsible for errors"], correctOptionIndex: 0 },
      { id: 15, text: "What was the primary human factor issue in the Excalibur Airways A320 incident?", options: ["Inadequate shift handover briefing about spoiler status", "Pilot fatigue", "Poor weather conditions"], correctOptionIndex: 0 },
      { id: 16, text: "In the Japan Airlines B747 accident (1985), the repair to the rear pressure bulkhead failed because:", options: ["The repair used a single splice plate instead of two, causing overloading", "The repair used two splice plates instead of one, concentrating stress on a single row of rivets", "The repair was not performed according to the maintenance manual at all"], correctOptionIndex: 1 },
      { id: 17, text: "What is the typical duration of short-term (working) memory?", options: ["2–5 seconds", "10–20 seconds", "1–2 minutes"], correctOptionIndex: 1 },
      { id: 18, text: "Which part of the eye is responsible for color vision?", options: ["Rods", "Cones", "Cornea"], correctOptionIndex: 1 },
      { id: 19, text: "What is presbycusis?", options: ["Age-related hearing loss", "Night blindness", "Color vision deficiency"], correctOptionIndex: 0 },
      { id: 20, text: "In information processing, what is \"sensory memory\"?", options: ["Long-term storage of experiences", "Brief retention of sensory impressions", "Conscious decision-making process"], correctOptionIndex: 1 },
      { id: 21, text: "Which factor does NOT typically affect visual acuity?", options: ["Age", "Blood type", "Lighting conditions"], correctOptionIndex: 1 },
      { id: 22, text: "What is \"night myopia\"?", options: ["Inability to see in bright light", "A form of near-sightedness that occurs in dim conditions", "Total loss of vision at night"], correctOptionIndex: 1 },
      { id: 23, text: "Where is the blind spot located in the eye?", options: ["In the center of the retina", "Where the optic nerve meets the retina", "At the edge of the cornea"], correctOptionIndex: 1 },
      { id: 24, text: "Sensory memory for touch is known as:", options: ["Iconic memory", "Echoic memory", "Haptic memory"], correctOptionIndex: 2 },
      { id: 25, text: "What is \"divided attention\"?", options: ["Focusing on a single task without distraction", "Monitoring multiple tasks simultaneously", "Ignoring all background stimuli"], correctOptionIndex: 1 },
      { id: 26, text: "What are \"motor programs\"?", options: ["New tasks requiring conscious effort", "Automatic routines stored in long-term memory through practice", "Short-term memory aids"], correctOptionIndex: 1 },
      { id: 27, text: "What is the term for the ability to maintain attention over long periods?", options: ["Selective attention", "Divided attention", "Sustained attention"], correctOptionIndex: 2 },
      { id: 28, text: "Which part of the ear contains the cochlea?", options: ["Outer ear", "Middle ear", "Inner ear"], correctOptionIndex: 2 },
      { id: 29, text: "What is the main purpose of the iris in the eye?", options: ["To focus light on the retina", "To control the amount of light entering through the pupil", "To detect color"], correctOptionIndex: 1 },
      { id: 30, text: "Which memory type stores motor skills like driving or swimming?", options: ["Semantic memory", "Episodic memory", "Motor programs"], correctOptionIndex: 2 },
      { id: 31, text: "What is \"temporary hearing loss\" often caused by?", options: ["Genetic factors", "Short exposure to loud sounds causing hair cell fatigue", "Earwax buildup"], correctOptionIndex: 1 },
      { id: 32, text: "What is \"social loafing\"?", options: ["Working harder in a group", "Reducing effort when working in a group", "Avoiding group tasks entirely"], correctOptionIndex: 1 },
      { id: 33, text: "According to Maslow, which need must be satisfied first?", options: ["Self-actualization", "Safety needs", "Physiological needs"], correctOptionIndex: 2 },
      { id: 34, text: "What is a \"just culture\"?", options: ["A blame-free environment", "A culture where all errors are punished", "A culture that distinguishes between acceptable and unacceptable behavior"], correctOptionIndex: 2 },
      { id: 35, text: "Peer pressure in maintenance can lead to:", options: ["Improved safety compliance", "Cutting corners to meet deadlines", "Increased manual documentation"], correctOptionIndex: 1 },
      { id: 36, text: "Which is an example of intrinsic motivation?", options: ["Working for a bonus", "Enjoying the task itself", "Following a supervisor's order"], correctOptionIndex: 1 },
      { id: 37, text: "What is \"organizational stress\"?", options: ["Stress caused only by personal life", "Pressure from management, deadlines, and company culture", "Stress that only affects supervisors"], correctOptionIndex: 1 },
      { id: 38, text: "In a team, what does \"diffusion of responsibility\" refer to?", options: ["Each member feels highly accountable", "No one feels personally responsible because others are present", "Responsibilities are clearly documented"], correctOptionIndex: 1 },
      { id: 39, text: "Which is a key component of a safety culture according to Professor Reason?", options: ["A blame-free culture only", "A just culture and learning culture", "Punishing all errors equally"], correctOptionIndex: 1 },
      { id: 40, text: "What is \"confirmation bias\"?", options: ["Seeking information that supports existing beliefs", "Making decisions based on peer pressure", "Ignoring all previous experiences"], correctOptionIndex: 0 },
      { id: 41, text: "Which is a key leadership quality in maintenance?", options: ["Avoiding all decision-making", "Motivating the team and leading by example", "Working independently from the team"], correctOptionIndex: 1 },
      { id: 42, text: "According to David Marx's scenarios, what distinguishes a blameworthy violation?", options: ["Following procedures exactly", "Deliberate non-compliance without justification", "System-induced equipment failure"], correctOptionIndex: 1 },
      { id: 43, text: "What is \"group polarization\"?", options: ["The tendency for groups to make more extreme decisions than individuals", "Equal distribution of responsibility in a team", "When a group always chooses the safest option"], correctOptionIndex: 0 },
      { id: 44, text: "Which of these is NOT a component of Professor Reason's safety culture?", options: ["A just culture", "A learning culture", "A punitive culture"], correctOptionIndex: 2 },
      { id: 45, text: "What does the \"substitution test\" ask peers after an unsafe act?", options: ["\"Could this have happened to you in the same circumstances?\"", "\"Who should be punished?\"", "\"Was the procedure clear?\""], correctOptionIndex: 0 },
      { id: 46, text: "Which personality trait combination is associated with accident-proneness?", options: ["Stable introverts", "Unstable extroverts", "Stable extroverts"], correctOptionIndex: 1 },
      { id: 47, text: "What is a common effect of fatigue?", options: ["Improved reaction time", "Reduced attention span", "Enhanced decision-making"], correctOptionIndex: 1 },
      { id: 48, text: "According to EASA, when should certifying staff NOT exercise their privileges?", options: ["When they feel slightly tired", "When they suspect their mental or physical condition is unfit", "Only after consuming alcohol"], correctOptionIndex: 1 },
      { id: 49, text: "Which is a recommended strategy for managing jet lag?", options: ["Drink caffeine before bedtime", "Adjust sleep schedule before travel", "Avoid sunlight upon arrival"], correctOptionIndex: 1 },
      { id: 50, text: "What is circadian rhythm?", options: ["A daily cycle of physiological processes", "A type of sleep disorder", "A measure of workload capacity"], correctOptionIndex: 0 },
      { id: 51, text: "Alcohol consumption before duty can:", options: ["Improve concentration", "Impair judgment and reaction time", "Have no effect if consumed moderately"], correctOptionIndex: 1 },
      { id: 52, text: "Which is a common symptom of stress?", options: ["Improved concentration", "Increased appetite for healthy foods", "Irritability and poor concentration"], correctOptionIndex: 2 },
      { id: 53, text: "What is a recommended method for managing workload overload?", options: ["Ignoring minor tasks completely", "Delegating tasks and seeking more time if needed", "Working faster without documentation"], correctOptionIndex: 1 },
      { id: 54, text: "During which sleep stage does dreaming typically occur?", options: ["Stage 3 (deep sleep)", "REM sleep", "Stage 1 (light sleep)"], correctOptionIndex: 1 },
      { id: 55, text: "What does the \"Holmes and Rahe Stress Scale\" measure?", options: ["Workplace noise levels", "The impact of life events on health", "Physical strength and endurance"], correctOptionIndex: 1 },
      { id: 56, text: "What is a \"staffing baseline\" used for?", options: ["Determining maximum overtime hours", "Setting minimum safe staffing levels for an organization", "Calculating salary budgets"], correctOptionIndex: 1 },
      { id: 57, text: "According to the Holmes and Rahe scale, what life event scores the highest stress points?", options: ["Divorce", "Death of a spouse", "Imprisonment"], correctOptionIndex: 1 },
      { id: 58, text: "What is the recommended daily alcohol limit for men according to the document?", options: ["1-2 units", "3-4 units", "5-6 units"], correctOptionIndex: 1 },
      { id: 59, text: "Which factor does NOT typically contribute to fatigue?", options: ["Regular sleep patterns", "Cumulative sleep loss", "Working night shifts"], correctOptionIndex: 0 },
      { id: 60, text: "What is \"arousal\" in the context of human performance?", options: ["The body's reaction to stress and motivation", "A state of deep relaxation", "The ability to multitask"], correctOptionIndex: 0 },
      { id: 61, text: "What does EASA Part-66.50 specifically require regarding certifying staff fitness?", options: ["Annual medical examination", "Not exercising privileges if unfit physically or mentally", "Mandatory drug testing"], correctOptionIndex: 1 },
      { id: 62, text: "At what noise level should hearing protection typically be used?", options: ["Above 60 dB", "Above 85 dB", "Above 120 dB"], correctOptionIndex: 1 },
      { id: 63, text: "Why is task lighting often necessary in hangars?", options: ["General hangar lighting is usually too bright", "Natural light is always sufficient", "Ceiling lights are often too high and dim for detailed work"], correctOptionIndex: 2 },
      { id: 64, text: "Working in confined spaces with fumes may require:", options: ["Additional lighting", "Breathing apparatus", "Noise-canceling headphones"], correctOptionIndex: 1 },
      { id: 65, text: "What is a key challenge of working on the airport apron?", options: ["Low lighting", "High noise levels", "Lack of tools"], correctOptionIndex: 1 },
      { id: 66, text: "Situational awareness in maintenance includes:", options: ["Knowing only your own task", "Understanding how your work affects other systems and people", "Focusing solely on written procedures"], correctOptionIndex: 1 },
      { id: 67, text: "Prolonged exposure to aircraft fuel fumes can cause:", options: ["Improved alertness", "Eye irritation and respiratory issues", "Enhanced sense of smell"], correctOptionIndex: 1 },
      { id: 68, text: "What effect can constant vibration have on maintenance personnel?", options: ["Improved concentration", "Fatigue and reduced manual dexterity", "Increased reaction time"], correctOptionIndex: 1 },
      { id: 69, text: "Why is proper illumination critical in maintenance?", options: ["It reduces the need for tools", "It helps detect fine details and cracks", "It eliminates the need for inspections"], correctOptionIndex: 1 },
      { id: 70, text: "How can noise above 85 dB affect communication?", options: ["It improves clarity of speech", "It masks warnings and interrupts verbal communication", "It has no effect on communication"], correctOptionIndex: 1 },
      { id: 71, text: "What is a common cause of poor situational awareness in maintenance?", options: ["Over-reliance on manuals", "Lack of sleep, stress, and distractions", "Excessive lighting"], correctOptionIndex: 1 },
      { id: 72, text: "At what noise level does the \"threshold of pain\" typically occur?", options: ["85 dB", "115 dB", "140 dB"], correctOptionIndex: 2 },
      { id: 73, text: "What is a major risk when working with aircraft fluids in confined spaces?", options: ["Improved ventilation", "Fume accumulation and inhalation", "Better lighting"], correctOptionIndex: 1 },
      { id: 74, text: "Which factor is NOT typically considered part of the physical working environment?", options: ["Temperature extremes", "Peer pressure", "Vibration from tools"], correctOptionIndex: 1 },
      { id: 75, text: "What is a key challenge of working on the aircraft \"crown\" (top of fuselage)?", options: ["Excessive noise", "Fear of heights for some engineers", "Poor tool access"], correctOptionIndex: 1 },
      { id: 76, text: "According to the NTSB Aloha report, what made inspections on top of the fuselage particularly difficult?", options: ["Lack of technical manuals", "Need for ropes and scaffolding in precarious positions", "Insufficient training"], correctOptionIndex: 1 },
      { id: 77, text: "According to Professor Reason's model, which element is NOT a component of a safety culture?", options: ["Just culture", "Reporting culture", "Punitive culture"], correctOptionIndex: 2 },
      { id: 78, text: "Which of the following best describes the \"inverted U-curve\" relationship between arousal and performance?", options: ["Performance increases linearly with arousal", "Performance is best at moderate arousal levels and poor at both low and high extremes", "Performance decreases as arousal increases"], correctOptionIndex: 1 },
      { id: 79, text: "In the Eastern Airlines L-1011 incident (1983), the investigation revealed that deeper organizational issues contributed to the error. Which of these was NOT a factor?", options: ["Management blamed mechanics rather than addressing procedural issues", "The airline had experienced similar incidents before but took no systemic action", "The maintenance engineers were improperly licensed for the task"], correctOptionIndex: 2 },
      { id: 80, text: "What is the primary difference between \"situational violations\" and \"routine violations\"?", options: ["Situational violations are deliberate shortcuts; routine violations are system-induced", "Situational violations are caused by system factors; routine violations are habitual non-compliance", "Situational violations are blameless; routine violations are always culpable"], correctOptionIndex: 1 },
      { id: 81, text: "According to the document, which of the following is a characteristic of \"claustrophobia\" in maintenance?", options: ["It is always present before employment and is easily screened", "It may first appear during an incident in a confined space", "It only affects engineers working in fuel tanks"], correctOptionIndex: 1 },
      { id: 82, text: "Which type of memory is most susceptible to interference when trying to remember a part number while simultaneously recalling a phone number?", options: ["Long-term memory", "Sensory memory", "Short-term (working) memory"], correctOptionIndex: 2 },
      { id: 83, text: "In the Air Midwest Beech 1900D accident, what step in the maintenance procedure was skipped, which might have prevented the accident?", options: ["A post-maintenance functional check of elevator travel range", "A duplicate inspection by a second engineer", "A pressure check of the hydraulic system"], correctOptionIndex: 0 },
      { id: 84, text: "According to Maslow's hierarchy, which need would a maintenance engineer fulfilling lower-level needs most likely be motivated by next?", options: ["Esteem needs (respect, recognition)", "Self-actualization (realizing full potential)", "Safety needs (job security, protection)"], correctOptionIndex: 0 },
      { id: 85, text: "Which of the following best describes the \"cocktail party effect\" in selective attention?", options: ["The ability to focus on one conversation while monitoring others for important cues (like your name)", "The tendency to become distracted by multiple conversations", "The inability to concentrate in noisy environments"], correctOptionIndex: 0 },
      { id: 86, text: "What is the primary reason that working rotating shifts towards earlier times (e.g., night → late → early) is generally discouraged?", options: ["It causes less disruption to circadian rhythms than rotating forward", "It is easier to adjust to earlier shifts than later ones", "It is more disruptive to circadian rhythms than rotating forward (early → late → night)"], correctOptionIndex: 2 },
      { id: 87, text: "In the British Midland B737-400 double engine oil loss incident, which factor was NOT listed as a common characteristic of the error?", options: ["The error occurred during night shift", "There was a failure to use approved data", "The engineers were unqualified for the task"], correctOptionIndex: 2 },
      { id: 88, text: "According to the document, what is the \"over-justification effect\" in motivation?", options: ["Offering external rewards for an intrinsically motivating task can reduce intrinsic motivation", "Punishment is more effective than reward in changing behavior", "Intrinsic motivation is always stronger than extrinsic motivation"], correctOptionIndex: 0 },
      { id: 89, text: "Which of the following is a recommended coping strategy for stress management?", options: ["Increased alcohol consumption", "Relaxation techniques and regular exercise", "Denial of the problem"], correctOptionIndex: 1 },
      { id: 90, text: "What does the \"time-weighted average (TWA) sound level\" of 85 dB over 8 hours indicate?", options: ["It is the threshold for immediate hearing damage", "It is the level at which hearing protection must be provided and risk assessed", "It is the level at which pain begins"], correctOptionIndex: 1 },
      { id: 91, text: "In the context of human information processing, what is \"confirmation bias\"?", options: ["The tendency to seek information that confirms existing beliefs", "The tendency to ignore all previous experience", "The inability to make decisions under pressure"], correctOptionIndex: 0 },
      { id: 92, text: "Which of the following is a key difference between CRM (Crew Resource Management) and MRM (Maintenance Resource Management)?", options: ["CRM focuses on individual performance; MRM focuses on team performance", "CRM errors are usually immediate; MRM errors may be latent", "CRM is for pilots only; MRM is for engineers only"], correctOptionIndex: 1 },
      { id: 93, text: "What is the primary purpose of a \"staffing baseline\" in maintenance organizations?", options: ["To determine the maximum number of staff that can be hired", "To set a minimum safe staffing level for operational safety", "To calculate overtime budgets"], correctOptionIndex: 1 },
      { id: 94, text: "According to the FAA MRM handbook, which of these is a characteristic of maintenance communications?", options: ["They are mostly synchronous and face-to-face", "They are often asynchronous (e.g., manuals, work cards)", "They require immediate verbal confirmation"], correctOptionIndex: 1 },
      { id: 95, text: "Which of the following is a recommended strategy for minimizing jet lag when flying east?", options: ["Go to bed later than usual before the flight", "Adjust your sleep schedule earlier before departure", "Consume caffeine before bedtime upon arrival"], correctOptionIndex: 1 },
      { id: 96, text: "Based on the error chain model presented in Module 9.1, which combination of factors would MOST likely create a \"window of accident opportunity\"?", options: ["Active failures only, with strong organizational defences", "Latent failures combined with inadequate defences and local triggers", "Single human error in a well-designed system with duplicate inspections"], correctOptionIndex: 1 },
      { id: 97, text: "In the Japan Airlines B747 accident, the repair remained undetected through multiple C-checks. What human factors principle does this BEST illustrate?", options: ["The limitations of scheduled maintenance in detecting latent errors", "The superiority of corrective maintenance over preventative maintenance", "The effectiveness of visual inspections in finding structural defects"], correctOptionIndex: 0 },
      { id: 98, text: "According to Professor Reason's just culture model, which scenario would MOST likely fall into the \"culpable\" category?", options: ["An engineer misses a crack during inspection but followed all procedures and used proper equipment", "An engineer deliberately uses incorrect bolts to save time, knowing the risk", "An engineer makes an arithmetic error in torque calculation due to fatigue"], correctOptionIndex: 1 },
      { id: 99, text: "Which of the following BEST describes the relationship between \"situation awareness\" and \"information processing\" in maintenance?", options: ["Situation awareness is independent of information processing capabilities", "Situation awareness is the output of effective information processing of environmental cues", "Information processing only affects short-term memory, not situation awareness"], correctOptionIndex: 1 },
      { id: 100, text: "In the context of workload management, which combination would create the HIGHEST risk of error according to the arousal-performance curve?", options: ["Low task complexity with high time pressure and moderate environmental stressors", "High task complexity with optimal time allocation and low environmental stressors", "Moderate task complexity with sleep deprivation and circadian low point (4 AM)"], correctOptionIndex: 2 },
      { id: 101, text: "Based on the document's discussion of sensory memory, which inspection scenario would be MOST vulnerable to missed defects?", options: ["Prolonged visual scanning of a known problem area", "Brief exposure to a component with subsequent detailed examination", "Intermittent glances at multiple components while multitasking"], correctOptionIndex: 2 },
      { id: 102, text: "What is the PRIMARY philosophical difference between a \"blame-free culture\" and a \"just culture\" according to David Marx's work?", options: ["Blame-free culture excuses all errors; just culture distinguishes between acceptable and unacceptable behavior", "Blame-free culture is more effective for safety reporting", "Just culture focuses only on punitive measures"], correctOptionIndex: 0 },
      { id: 103, text: "Which combination of factors from the Holmes and Rahe scale would MOST significantly impact a maintenance engineer's performance, assuming additive effects?", options: ["Marriage (50) + Change in living conditions (25)", "Personal injury or illness (53) + Change in work responsibilities (29)", "Death of close family member (63) + Troubles with boss (23)"], correctOptionIndex: 2 },
      { id: 104, text: "In the Eastern Airlines L-1011 incident, the NTSB noted that management blamed mechanics rather than addressing procedural issues. This is an example of:", options: ["Fundamental attribution error combined with organizational learning failure", "Effective error management through individual accountability", "Appropriate response to clear violations"], correctOptionIndex: 0 },
      { id: 105, text: "Which visual inspection scenario would be MOST affected by \"night myopia\"?", options: ["Daylight inspection of aircraft skin for cracks", "Using a flashlight to inspect engine components at night", "Reading maintenance manuals in a well-lit office"], correctOptionIndex: 1 },
      { id: 106, text: "Based on the document's discussion of memory, which task would be MOST susceptible to interference effects?", options: ["Recalling a frequently used torque specification while performing the task", "Remembering a new part number while simultaneously troubleshooting an unrelated system", "Following a well-practiced checklist from long-term memory"], correctOptionIndex: 1 },
      { id: 107, text: "According to the document, what is the PRIMARY reason that the \"can-do\" attitude can be problematic in maintenance organizations?", options: ["It reduces productivity and efficiency", "It may lead to normalization of deviance and procedural violations", "It decreases team cohesion and communication"], correctOptionIndex: 1 },
      { id: 108, text: "Which sleep stage disruption would MOST significantly affect an engineer's ability to learn new procedures the following day?", options: ["Reduction in Stage 3 (deep sleep)", "Disruption of REM sleep cycles", "Elimination of Stage 1 (transitional sleep)"], correctOptionIndex: 1 },
      { id: 109, text: "In the British Airways BAC 1-11 incident, multiple human factors contributed. Which combination represents BOTH individual and organizational factors?", options: ["Perceptual error in bolt identification AND lack of duplicate inspection requirement", "Poor lighting only", "Circadian effects only"], correctOptionIndex: 0 },
      { id: 110, text: "What is the CRITICAL difference between \"social loafing\" and \"diffusion of responsibility\" in team contexts?", options: ["Social loafing is about reduced individual effort; diffusion is about responsibility attribution", "They are identical concepts with different names", "Social loafing only occurs in large teams; diffusion occurs in small teams"], correctOptionIndex: 0 },
      { id: 111, text: "According to the document, which environmental factor has the GREATEST potential for creating cumulative, irreversible damage to maintenance personnel?", options: ["Intermittent high noise levels with hearing protection available", "Chronic exposure to chemical fumes at low concentrations", "Occasional work in temperature extremes"], correctOptionIndex: 1 },
      { id: 112, text: "Which scenario BEST illustrates the \"over-justification effect\" in maintenance motivation?", options: ["An engineer who enjoys troubleshooting receives a bonus for each problem solved", "An engineer receives additional training on a new aircraft system", "An engineer is praised for following safety procedures"], correctOptionIndex: 0 },
      { id: 113, text: "Based on circadian rhythm principles, which shift rotation pattern would create the LEAST disruption to performance?", options: ["Day → Night → Early, rotating backward", "Early → Late → Night, rotating forward", "Random assignment based on operational needs"], correctOptionIndex: 1 },
      { id: 114, text: "What is the PRIMARY limitation of using \"temporary side-memories\" (like notepads) in maintenance according to the document?", options: ["They are always more reliable than human memory", "They may become outdated or contain errors if not properly managed", "They eliminate the need for procedural documentation"], correctOptionIndex: 1 },
      { id: 115, text: "In the Air Midwest Beech 1900D accident, the skipped functional check might have been prompted by which human factors concept?", options: ["The substitution test principle", "Confirmation bias in procedure interpretation", "Social loafing during team tasks"], correctOptionIndex: 1 },
      { id: 116, text: "BONUS: Which combination of Maslow's hierarchy levels would MOST likely motivate an experienced engineer to engage in unsafe shortcuts?", options: ["Physiological needs threatening Esteem needs", "Safety needs conflicting with Self-actualization", "Esteem needs overriding Safety needs"], correctOptionIndex: 2 },
      { id: 117, text: "Considering the Aloha Airlines accident and subsequent investigations, which combination of factors BEST predicts the development of \"normalization of deviance\" in maintenance inspections?", options: ["High workload + clear procedural guidance + regular audits", "Repetitive inspections with consistently negative findings + time pressure + perceived management priorities", "Low turnover + comprehensive training + strong safety culture"], correctOptionIndex: 1 },
      { id: 118, text: "Based on Professor Reason's model and David Marx's scenarios, which error classification would be MOST difficult for an organization to address effectively?", options: ["Sabotage (clear culpability)", "Routine violation due to impractical procedures", "Skill-based slip during highly practiced task"], correctOptionIndex: 1 },
      { id: 119, text: "Using the information processing model, which combination would create the GREATEST risk during fault diagnosis of an intermittent electrical problem?", options: ["High expertise + low stress + good documentation", "Moderate expertise + circadian low point + confirmation bias", "Low expertise + optimal arousal + team collaboration"], correctOptionIndex: 1 },
      { id: 120, text: "In the Eastern Airlines L-1011 incident, management's repeated attribution of errors to mechanics rather than procedures exemplifies which SYSTEMIC organizational failure?", options: ["Fundamental attribution error institutionalized as management practice", "Appropriate accountability for individual performance", "Effective use of disciplinary action to modify behavior"], correctOptionIndex: 0 },
      { id: 121, text: "Which combination of visual limitations would be MOST problematic for an engineer inspecting composite structures for barely visible impact damage?", options: ["Presbyopia + standard hangar lighting", "Night myopia + task lighting at 45-degree angle", "Color deficiency + high-contrast lighting"], correctOptionIndex: 0 },
      { id: 122, text: "Based on the \"error chain\" concept and Swiss Cheese Model, which defensive layer is MOST vulnerable to erosion over time without active management?", options: ["Manufacturer's design safeguards", "Organizational safety culture", "Regulatory requirements"], correctOptionIndex: 1 },
      { id: 123, text: "An engineer with high conscientiousness but moderate neuroticism scores is assigned to a high-stakes troubleshooting task at 3 AM. According to the five-factor model and circadian principles, what is their MOST likely performance profile?", options: ["Methodical but increasingly error-prone due to anxiety and fatigue", "Rapid and accurate due to personality matching task demands", "Unaffected by time of day due to personality stability"], correctOptionIndex: 0 },
      { id: 124, text: "Which sleep architecture disruption would MOST significantly impair an engineer's ability to recognize novel failure patterns the following day?", options: ["30% reduction in Stage 4 sleep", "Fragmented REM sleep with multiple awakenings", "Extended Stage 1 sleep at sleep onset"], correctOptionIndex: 1 },
      { id: 125, text: "In the Japan Airlines B747 case, the repair error remained undetected for years through multiple inspections. This BEST illustrates which limitation of quality assurance systems?", options: ["Inadequate inspection techniques for the specific defect", "Assumption that previous inspections validate current condition", "Over-reliance on automated testing systems"], correctOptionIndex: 1 },
      { id: 126, text: "Which combination of stressors would likely produce the GREATEST performance degradation in complex manual tasks?", options: ["High thermal stress + moderate time pressure", "Moderate noise + high cognitive workload", "Low vibration + high emotional stress"], correctOptionIndex: 0 },
      { id: 127, text: "Based on the Holmes and Rahe scale, which life event sequence would create the HIGHEST cumulative risk of performance failure in maintenance?", options: ["Marriage (50) + Change in work responsibilities (29) + Vacation (13)", "Personal injury (53) + Change in living conditions (25) + Outstanding achievement (28)", "Death of spouse (100) + Retirement (45) + Change in residence (20)"], correctOptionIndex: 2 },
      { id: 128, text: "Which safety culture metric would be MOST predictive of latent organizational risk?", options: ["Number of reported near-misses per month", "Ratio of punitive actions to total reported incidents", "Time between procedural updates and implementation audits"], correctOptionIndex: 1 },
      { id: 129, text: "In the Air Midwest accident, the engineers' misinterpretation of the rigging procedure exemplifies which COGNITIVE error mechanism?", options: ["Confirmation bias reinforced by shared mental models", "Pure memory failure due to information overload", "Attention capture by salient but irrelevant information"], correctOptionIndex: 0 },
      { id: 130, text: "Which combination represents the GREATEST violation of circadian principles in shift scheduling?", options: ["Forward rotation (early→late→night) with 8-hour shifts", "Backward rotation (night→late→early) with 10-hour shifts", "Fixed night shift with consistent 12-hour duration"], correctOptionIndex: 1 },
      { id: 131, text: "An organization experiences increased \"corner-cutting\" during night shifts. Using Maslow's hierarchy, which intervention would likely be MOST effective?", options: ["Increase financial bonuses for timely task completion", "Enhance team recognition programs for procedural compliance", "Improve rest facilities and meal quality during shifts"], correctOptionIndex: 2 },
      { id: 132, text: "Which sensory memory characteristic creates the GREATEST risk during aircraft walk-around inspections?", options: ["Iconic memory duration (0.5 seconds) for scanning large areas", "Echoic memory capacity for simultaneous auditory monitoring", "Haptic memory interference when switching between tools"], correctOptionIndex: 0 },
      { id: 133, text: "Based on the MRM vs. CRM comparison, which maintenance communication characteristic creates the HIGHEST potential for error propagation?", options: ["Asynchronous nature allowing delayed error detection", "Diverse experience levels among team members", "Physical separation of team members during tasks"], correctOptionIndex: 0 },
      { id: 134, text: "Which combination of workload factors would likely produce the MOST dangerous form of \"underload\"?", options: ["Monotonous task + high consequence of error + circadian low point", "Complex task + moderate consequences + optimal arousal", "Variable task + low consequences + rested state"], correctOptionIndex: 0 },
      { id: 135, text: "Using the substitution test after an incident, which peer response would indicate the STRONGEST case for systemic rather than individual causation?", options: ["\"I probably would have made the same mistake\"", "\"I've seen others do similar things\"", "\"The procedure is confusing to everyone\""], correctOptionIndex: 2 },
      { id: 136, text: "Which perceptual illusion creates the GREATEST risk during maintenance documentation review?", options: ["Müller-Lyer illusion affecting measurement interpretation", "Expectation effects causing oversight of procedure changes", "Context effects altering interpretation of ambiguous instructions"], correctOptionIndex: 1 },
      { id: 137, text: "BONUS: Considering all major accidents in the document, which COMMON factor represents the MOST significant organizational predictor of catastrophic failure?", options: ["Single experienced individual making an error", "Multiple defensive layers failing simultaneously", "Absence of regulatory oversight"], correctOptionIndex: 1 },
    ],
  },
};

export const getTestByName = (testName: string | null): TestConfig | null => {
  if (!testName) return null;
  return allTests[testName] || null;
};

export const getAvailableTests = () => {
  return Object.keys(allTests).map(key => ({
    id: key,
    title: allTests[key].title,
    description: allTests[key].description,
    questionCount: allTests[key].questions.length,
    duration: allTests[key].durationMinutes,
  }));
};
