import type { TestConfig } from "@shared/schema";

export const allTests: Record<string, TestConfig> = {
  "composite-materials": {
    id: "composite-materials",
    title: "Composite Materials",
    description: "Assessment on Composite Materials and structural materials in aviation. Answer all 57 questions about composites, resins, fibers, wooden structures, material properties and heat treatments. Time limit: 60 minutes.",
    durationMinutes: 60,
    questions: [
      {
        id: 1,
        text: "What is the primary reason for using composite materials in aircraft?",
        options: ["Lower production cost", "Weight reduction", "Easier repair"],
        correctOptionIndex: 1,
      },
      {
        id: 2,
        text: "Which of the following is a disadvantage of composites?",
        options: ["High strength-to-weight ratio", "Easy to repair", "Expensive materials and repair"],
        correctOptionIndex: 2,
      },
      {
        id: 3,
        text: "A composite material is typically made up of:",
        options: ["Metal and wood", "Matrix and reinforcing fibres", "Ceramics and elastomers"],
        correctOptionIndex: 1,
      },
      {
        id: 4,
        text: "Which fibre type is known for its high impact resistance and yellow colour?",
        options: ["Glass fibre", "Aramid (Kevlar)", "Carbon fibre"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "Which fibre is strongest in compression but brittle and corrosive to aluminium?",
        options: ["Glass fibre", "Aramid", "Carbon fibre"],
        correctOptionIndex: 2,
      },
      {
        id: 6,
        text: "Which type of glass fibre is most common for aeronautical GRP?",
        options: ["A-Glass", "E-Glass", "S-Glass"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "Which resin type is most widely used in aerospace adhesives and composites?",
        options: ["Polyester", "Epoxy", "Phenolic"],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "What is the purpose of a hardener in an epoxy resin system?",
        options: ["To colour the resin", "To initiate the curing reaction", "To reduce viscosity"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "Which resin type is known for low smoke and toxic gas emissions, making it suitable for cabin interiors?",
        options: ["Epoxy", "Polyurethane", "Phenolic"],
        correctOptionIndex: 2,
      },
      {
        id: 10,
        text: "How must prepreg materials be stored to prevent premature curing?",
        options: ["In a heated cabinet", "In a freezer at -18°C or below", "At room temperature in sealed bags"],
        correctOptionIndex: 1,
      },
      {
        id: 11,
        text: "What is the main advantage of using prepreg materials?",
        options: ["Lower cost", "Controlled resin-to-fibre ratio", "No need for refrigeration"],
        correctOptionIndex: 1,
      },
      {
        id: 12,
        text: "What is the typical shelf life of prepreg repair materials?",
        options: ["1–2 months", "6–12 months", "2–3 years"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "What is a monolithic composite structure?",
        options: ["A sandwich with a honeycomb core", "Multiple layers of laminate stacked together", "A single layer of fibre only"],
        correctOptionIndex: 1,
      },
      {
        id: 14,
        text: "What is the purpose of a honeycomb core in a sandwich structure?",
        options: ["To increase weight", "To increase stiffness without significant weight gain", "To make the structure flexible"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "Which of these is a common core material for sandwich structures?",
        options: ["Steel mesh", "Nomex honeycomb", "Rubber foam"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What does an autoclave provide during composite curing?",
        options: ["Only heat", "Heat and pressure", "Only vacuum"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "Which temperature range is typical for curing epoxy resins in an autoclave?",
        options: ["50°C–80°C", "120°C–180°C", "200°C–300°C"],
        correctOptionIndex: 1,
      },
      {
        id: 18,
        text: "What is the purpose of vacuum bagging in composite lay-up?",
        options: ["To add colour to the laminate", "To remove air and excess resin", "To speed up the curing time"],
        correctOptionIndex: 1,
      },
      {
        id: 19,
        text: "Which defect is a hidden failure between layers of fabric in a composite?",
        options: ["Crack", "Delamination", "Dent"],
        correctOptionIndex: 1,
      },
      {
        id: 20,
        text: "Which inspection method uses sound to detect delamination?",
        options: ["Light test", "Coin-tap test", "X-ray"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "Class 3 damage in composites is defined as:",
        options: ["Major structural damage", "Negligible damage within limits", "Damage requiring immediate repair"],
        correctOptionIndex: 1,
      },
      {
        id: 22,
        text: "What is the common name for polymethyl-methacrylate used in aircraft windows?",
        options: ["PVC", "Perspex/Acrylic", "Teflon"],
        correctOptionIndex: 1,
      },
      {
        id: 23,
        text: "Which plastic is known for its non-stick properties and high chemical resistance?",
        options: ["Polypropylene", "PTFE (Teflon)", "Nylon"],
        correctOptionIndex: 1,
      },
      {
        id: 24,
        text: "What causes crazing in acrylic windows?",
        options: ["Excessive heat only", "Contact with solvents or UV light", "High pressure"],
        correctOptionIndex: 1,
      },
      {
        id: 25,
        text: "Which elastomer is known for high-temperature resistance and is often called Viton?",
        options: ["Nitrile", "Fluoro-elastomer", "Silicone rubber"],
        correctOptionIndex: 1,
      },
      {
        id: 26,
        text: "Which rubber is resistant to phosphate ester hydraulic fluids like Skydrol?",
        options: ["Buna-S", "Neoprene", "Ethylene-propylene rubber"],
        correctOptionIndex: 2,
      },
      {
        id: 27,
        text: "What is the primary use of elastomers in aircraft?",
        options: ["Structural components", "Seals, adhesives, and flexible parts", "Window frames"],
        correctOptionIndex: 1,
      },
      {
        id: 28,
        text: "Which adhesive was first developed during WWII and is still used today?",
        options: ["Epoxy", "Redux", "Polyurethane"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "What is the primary function of a sealant in aircraft?",
        options: ["To provide electrical insulation", "To prevent air or fluid leakage", "To increase structural strength"],
        correctOptionIndex: 1,
      },
      {
        id: 30,
        text: "Which sealant type vulcanises at room temperature?",
        options: ["Polysulphide", "RTV silicone", "Epoxy paste"],
        correctOptionIndex: 1,
      },
      {
        id: 31,
        text: "Which wood type is traditionally considered best for aircraft construction?",
        options: ["Oak", "Sitka spruce", "Pine"],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is the maximum grain slope allowed for Grade A spruce?",
        options: ["1:8", "1:12", "1:15"],
        correctOptionIndex: 2,
      },
      {
        id: 33,
        text: "What defect appears as a separation along the annual rings of wood?",
        options: ["Heart shake", "Ring shake", "Knot"],
        correctOptionIndex: 1,
      },
      {
        id: 34,
        text: "Which glue is waterproof and highly resistant to temperature and chemicals?",
        options: ["Casein", "Resorcinol-formaldehyde", "Urea-formaldehyde"],
        correctOptionIndex: 1,
      },
      {
        id: 35,
        text: "What is the typical taper ratio for a scarf joint in wood?",
        options: ["5:1", "12:1 to 15:1", "20:1"],
        correctOptionIndex: 1,
      },
      {
        id: 36,
        text: "Why should sandpaper not be used on new timber before gluing?",
        options: ["It makes the wood too smooth", "It fills pores with dust and reduces adhesion", "It changes the colour of the wood"],
        correctOptionIndex: 1,
      },
      {
        id: 37,
        text: "What indicates dry rot in wood?",
        options: ["Dark discolouration along the grain", "Crumbling wood patches", "Blue stains"],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "What is compression shake in wood caused by?",
        options: ["Tension overload", "Compression overload along the grain", "Moisture absorption"],
        correctOptionIndex: 1,
      },
      {
        id: 39,
        text: "How can water penetration in a wooden structure be detected?",
        options: ["By tapping the surface", "By checking for corrosion on screws or bolts", "By applying a light coat of varnish"],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What is aircraft-grade plywood usually made from?",
        options: ["Spruce veneers", "Birch veneers", "Mahogany veneers"],
        correctOptionIndex: 1,
      },
      {
        id: 41,
        text: "How are veneers typically arranged in plywood?",
        options: ["All grains in the same direction", "Grains alternated at 90°", "Random orientation"],
        correctOptionIndex: 1,
      },
      {
        id: 42,
        text: "What is the main advantage of plywood over solid wood?",
        options: ["Lower cost", "Greater strength in multiple directions", "Lighter weight"],
        correctOptionIndex: 1,
      },
      {
        id: 43,
        text: "In the context of aluminum manufacturing, what does \"DC\" stand for in the provided abbreviations list?",
        options: ["Direct Current", "Direct Chili", "Double Coated"],
        correctOptionIndex: 1,
      },
      {
        id: 44,
        text: "Which abbreviation refers to the chemical compound used as a flux in aluminum smelting?",
        options: ["Al₂O₃", "Na₃AlF₃", "CO₂"],
        correctOptionIndex: 1,
      },
      {
        id: 45,
        text: "What density threshold is used to differentiate between lightweight and heavyweight metals in aircraft construction?",
        options: ["3.0 Kg/dm³", "5.0 Kg/dm³", "7.0 Kg/dm³"],
        correctOptionIndex: 1,
      },
      {
        id: 46,
        text: "Which of the following metals has the lowest density among those listed for aircraft structures?",
        options: ["Titanium", "Aluminum", "Magnesium"],
        correctOptionIndex: 2,
      },
      {
        id: 47,
        text: "What is the term for the undesirable property where a metal becomes brittle within a specific high-temperature range?",
        options: ["Cold shortness", "Hot shortness", "Thermal brittleness"],
        correctOptionIndex: 1,
      },
      {
        id: 48,
        text: "Which property describes a material's ability to be readily liquefied by heat for welding?",
        options: ["Fusibility", "Malleability", "Solubility"],
        correctOptionIndex: 0,
      },
      {
        id: 49,
        text: "In the formula for strain, what does \"e\" represent?",
        options: ["Original length", "Change in length", "Elastic modulus"],
        correctOptionIndex: 1,
      },
      {
        id: 50,
        text: "If a stress of 1 hbar is applied to a steel component, what is the resulting strain if Young's modulus for steel is 20,000 hbar?",
        options: ["1/20,000", "1/2,000", "1/200"],
        correctOptionIndex: 0,
      },
      {
        id: 51,
        text: "Which of the following is NOT listed as a typical load contributing to fatigue in aircraft structures?",
        options: ["Atmospheric gusts", "Engine start-up cycles", "Taxiing"],
        correctOptionIndex: 1,
      },
      {
        id: 52,
        text: "What microscopic feature is NOT cited as a potential initiation site for fatigue cracks?",
        options: ["Voids", "Grain boundaries", "Inclusion particles"],
        correctOptionIndex: 1,
      },
      {
        id: 53,
        text: "In the historical context provided, which civilization first perfected reliable steel manufacturing around AD 200?",
        options: ["Romans", "Celts", "Chinese"],
        correctOptionIndex: 1,
      },
      {
        id: 54,
        text: "What is the primary purpose of the blast furnace in iron production?",
        options: ["To cast iron into final shapes", "To convert iron ore into molten iron", "To refine steel into alloys"],
        correctOptionIndex: 1,
      },
      {
        id: 55,
        text: "Which alloying element, when added in approximately 35%, gives steel a nearly-zero expansion coefficient?",
        options: ["Nickel", "Chromium", "Cobalt"],
        correctOptionIndex: 0,
      },
      {
        id: 56,
        text: "Which element is noted for increasing steel's resistance to shock and fatigue, even when added in very low percentages?",
        options: ["Vanadium", "Tungsten", "Manganese"],
        correctOptionIndex: 0,
      },
      {
        id: 57,
        text: "In the cyanide hardening process, what is the typical temperature used?",
        options: ["750°C", "900°C", "1,000°C"],
        correctOptionIndex: 1,
      },
    ],
  },
  
  "human-factors": {
    id: "human-factors",
    title: "Human Factors",
    description: "Assessment on Human Factors in Aviation Maintenance. Answer all 45 review questions on human factors, human performance and social psychology. Time limit: 45 minutes.",
    durationMinutes: 45,
    questions: [
      {
        id: 1,
        text: "Why must human factors be taken into account in aviation maintenance?",
        options: ["Because maintenance personnel have no impact on system safety.", "To ensure equipment never requires maintenance.", "Because humans are a key point of interaction in systems, and their limitations can affect safety and reliability."],
        correctOptionIndex: 2,
      },
      {
        id: 2,
        text: "Approximately what percentage of aircraft accidents are primarily caused by flight crew actions?",
        options: ["20%", "Over 60%", "4%"],
        correctOptionIndex: 1,
      },
      {
        id: 3,
        text: "In accident statistics, maintenance is identified as the primary cause in what percentage of hull loss accidents?",
        options: ["4%", "12%", "22%"],
        correctOptionIndex: 0,
      },
      {
        id: 4,
        text: "What is one significant financial cost of a maintenance error?",
        options: ["Increased passenger satisfaction", "Flight delays or cancellations", "Reduced training requirements"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "What is 'human factors' in aviation maintenance?",
        options: ["The study of human capabilities and limitations in the workplace", "Only related to cockpit design and crew resource management", "A term used only for equipment design"],
        correctOptionIndex: 0,
      },
      {
        id: 6,
        text: "Which accident helped bring human factors in maintenance into sharp focus?",
        options: ["Japan Airlines 1985", "Aloha Airlines 1988", "British Airways 1990"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "What is a unique human factors issue in aviation maintenance?",
        options: ["Maintenance engineers work only in comfortable office environments.", "Maintenance technicians often work in hazardous, confined, or extreme temperature environments.", "Maintenance personnel do not require communication skills."],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "Which type of maintenance task is performed in response to unplanned events?",
        options: ["Scheduled maintenance", "Unscheduled maintenance", "Routine inspection"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "In the 1985 Japan Airlines Boeing 747 accident, what failed due to a previous repair error?",
        options: ["The rear pressure bulkhead", "The landing gear", "The flight control system"],
        correctOptionIndex: 0,
      },
      {
        id: 10,
        text: "In the Eastern Airlines L-1011 incident, what was missing from the magnetic chip detectors?",
        options: ["O-rings", "Electrical wiring", "Safety tags"],
        correctOptionIndex: 0,
      },
      {
        id: 11,
        text: "What was the primary cause of the Aloha Airlines Boeing 737 accident in 1988?",
        options: ["Failure to detect disbonding and fatigue damage in the fuselage", "Incorrect fuel loading", "Pilot error during takeoff"],
        correctOptionIndex: 0,
      },
      {
        id: 12,
        text: "In the British Airways BAC 1-11 accident, what was the cause of the windscreen blowout?",
        options: ["Incorrect window sealant", "Installation of undersized bolts", "Excessive cabin pressure"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "In the Air Midwest Beech 1900 accident, what was incorrectly rigged?",
        options: ["Elevator control cables", "Rudder cables", "Aileron controls"],
        correctOptionIndex: 0,
      },
      {
        id: 14,
        text: "What is the 'error chain' in aviation?",
        options: ["A single mechanical failure causing an accident", "A series of human-factor-related errors leading to an accident", "A sequence of automated system warnings"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "What is Murphy's Law?",
        options: ["'If anything can go right, it will.'", "'If anything can go wrong, it will.'", "'Errors only happen to careless people.'"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What part of the eye is responsible for focusing light onto the retina?",
        options: ["Retina", "Lens", "Cornea"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "What is myopia?",
        options: ["Short-sightedness", "Long-sightedness", "Astigmatism"],
        correctOptionIndex: 0,
      },
      {
        id: 18,
        text: "Where is the blind spot located in the eye?",
        options: ["Where the optic nerve meets the retina", "In the center of the cornea", "At the edge of the iris"],
        correctOptionIndex: 0,
      },
      {
        id: 19,
        text: "Which factor does NOT affect visual acuity?",
        options: ["Age", "Lighting", "Shoe size"],
        correctOptionIndex: 2,
      },
      {
        id: 20,
        text: "What is presbyopia?",
        options: ["A clouding of the lens", "Age-related long-sightedness", "Color blindness"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "What part of the ear contains the cochlea?",
        options: ["Outer ear", "Middle ear", "Inner ear"],
        correctOptionIndex: 2,
      },
      {
        id: 22,
        text: "What noise level is considered the threshold of pain?",
        options: ["90 dB", "100 dB", "120 dB"],
        correctOptionIndex: 2,
      },
      {
        id: 23,
        text: "What is presbycusis?",
        options: ["Noise-induced hearing loss", "Age-related hearing loss", "Temporary hearing loss from loud noise"],
        correctOptionIndex: 1,
      },
      {
        id: 24,
        text: "Which memory type lasts less than one second?",
        options: ["Sensory memory", "Short-term memory", "Long-term memory"],
        correctOptionIndex: 0,
      },
      {
        id: 25,
        text: "How many items can short-term memory typically hold?",
        options: ["3–4", "7±2", "15–20"],
        correctOptionIndex: 1,
      },
      {
        id: 26,
        text: "What is 'chunking' in memory?",
        options: ["Grouping information into meaningful units", "Repeating information over and over", "Forgetting unnecessary details"],
        correctOptionIndex: 0,
      },
      {
        id: 27,
        text: "Which is NOT a type of attention?",
        options: ["Selective attention", "Divided attention", "Permanent attention"],
        correctOptionIndex: 2,
      },
      {
        id: 28,
        text: "What is confirmation bias?",
        options: ["Ignoring all new information", "Seeking information that confirms existing beliefs", "Always changing your mind"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "What can help prevent memory-related errors in maintenance?",
        options: ["Using manuals and temporary notes", "Relying only on experience", "Avoiding written procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 30,
        text: "What is situation awareness in maintenance?",
        options: ["Understanding the current system status and predicting future states", "Only knowing your own task", "Memorizing all past procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 31,
        text: "What is claustrophobia?",
        options: ["Fear of heights", "Abnormal fear of enclosed spaces", "Fear of loud noises"],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is social loafing?",
        options: ["Working harder in a group", "Reducing effort when working in a group", "Always taking leadership in a team"],
        correctOptionIndex: 1,
      },
      {
        id: 33,
        text: "What is diffusion of responsibility?",
        options: ["Taking full responsibility as an individual", "Feeling less responsible in a group setting", "Assigning tasks clearly in a team"],
        correctOptionIndex: 1,
      },
      {
        id: 34,
        text: "What is the Hawthorne effect?",
        options: ["Improved performance due to increased attention from management", "Reduced performance due to poor lighting", "Peer pressure leading to errors"],
        correctOptionIndex: 0,
      },
      {
        id: 35,
        text: "Which is the highest level in Maslow's hierarchy of needs?",
        options: ["Safety needs", "Esteem needs", "Self-actualization"],
        correctOptionIndex: 2,
      },
      {
        id: 36,
        text: "What is extrinsic motivation?",
        options: ["Motivation driven by external rewards or punishments", "Motivation from personal satisfaction", "Motivation from team recognition only"],
        correctOptionIndex: 0,
      },
      {
        id: 37,
        text: "What did Solomon Asch's conformity experiments demonstrate?",
        options: ["People always make independent judgments.", "People often conform to group opinion even if it's wrong.", "Groups improve decision-making accuracy."],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "What is a 'just culture'?",
        options: ["A no-blame culture where all errors are ignored", "A culture where the line between acceptable and unacceptable behavior is clear", "A culture where all errors are punished"],
        correctOptionIndex: 1,
      },
      {
        id: 39,
        text: "According to Reason, what is a key component of a safety culture?",
        options: ["Ignoring near-misses", "A good reporting culture", "Punishing all errors"],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What is the 'substitution test' used for?",
        options: ["To determine if an error could have been made by others in the same situation", "To replace faulty equipment", "To test new procedures"],
        correctOptionIndex: 0,
      },
      {
        id: 41,
        text: "Which is NOT one of the 'Big Five' personality traits?",
        options: ["Openness", "Conscientiousness", "Perfectionism"],
        correctOptionIndex: 2,
      },
      {
        id: 42,
        text: "Which personality type is often associated with accident proneness?",
        options: ["Stable introvert", "Unstable extrovert", "Stable extrovert"],
        correctOptionIndex: 1,
      },
      {
        id: 43,
        text: "What is a key element of effective teamwork?",
        options: ["Working in isolation", "Good communication", "Avoiding task delegation"],
        correctOptionIndex: 1,
      },
      {
        id: 44,
        text: "What is a supervisor's role in maintenance?",
        options: ["Only doing hands-on tasks", "Monitoring performance and maintaining safety culture", "Avoiding all management duties"],
        correctOptionIndex: 1,
      },
      {
        id: 45,
        text: "What does MRM stand for?",
        options: ["Maintenance Repair Manual", "Maintenance Resource Management", "Mandatory Regulatory Measures"],
        correctOptionIndex: 1,
      },
    ],
  },
  "ferrous-non-ferrous-metals": {
    id: "ferrous-non-ferrous-metals",
    title: "Ferrous and Non-Ferrous Metals",
    description: "Assessment on Ferrous and Non-Ferrous Metals in aviation, including aluminum, magnesium, titanium, nickel, copper alloys and heat treatment processes. Answer all 40 questions about metal properties, heat treatment, and aerospace applications. Time limit: 40 minutes.",
    durationMinutes: 40,
    questions: [
      {
        id: 1,
        text: "What is the primary reason aluminum alloys are extensively used in aircraft construction?",
        options: ["High magnetic properties", "Excellent strength-to-weight ratio and corrosion resistance", "Superior electrical insulation"],
        correctOptionIndex: 1,
      },
      {
        id: 2,
        text: "Which aluminum alloy series uses copper as its major alloying element and is commonly used for aircraft skins and structures?",
        options: ["5xxx series", "2xxx series", "3xxx series"],
        correctOptionIndex: 1,
      },
      {
        id: 3,
        text: "What does the temper designation \"-T6\" indicate for an aluminum alloy?",
        options: ["Annealed condition", "Solution heat-treated and artificially aged", "Strain-hardened only"],
        correctOptionIndex: 1,
      },
      {
        id: 4,
        text: "Which aluminum alloys are generally non-heat-treatable?",
        options: ["2xxx, 6xxx, 7xxx", "1xxx, 3xxx, 5xxx", "8xxx, 4xxx, 9xxx"],
        correctOptionIndex: 1,
      },
      {
        id: 5,
        text: "What is the purpose of cladding aluminum alloy sheets with pure aluminum?",
        options: ["To increase electrical conductivity", "To improve corrosion resistance", "To enhance magnetic properties"],
        correctOptionIndex: 1,
      },
      {
        id: 6,
        text: "What is the maximum recommended number of heat treatments for clad aluminum materials?",
        options: ["One", "Three", "Five"],
        correctOptionIndex: 1,
      },
      {
        id: 7,
        text: "What is a significant hazard when machining magnesium?",
        options: ["It becomes brittle at low temperatures", "It is highly flammable, especially as fine dust or swarf", "It emits toxic fumes when annealed"],
        correctOptionIndex: 1,
      },
      {
        id: 8,
        text: "Which element is the primary alloying agent in the 5xxx series aluminum alloys?",
        options: ["Silicon", "Magnesium", "Zinc"],
        correctOptionIndex: 1,
      },
      {
        id: 9,
        text: "What does the alloy designation \"AZ31A-T4\" indicate for a magnesium alloy?",
        options: ["Contains 3% aluminum and 1% zinc, solution heat-treated", "Contains 31% aluminum, annealed", "Contains aluminum and zirconium, strain-hardened"],
        correctOptionIndex: 0,
      },
      {
        id: 10,
        text: "What is a key advantage of titanium alloys in aerospace applications?",
        options: ["Low cost and high availability", "High strength-to-weight ratio and excellent corrosion resistance", "High thermal and electrical conductivity"],
        correctOptionIndex: 1,
      },
      {
        id: 11,
        text: "Which of the following should NOT be used with titanium components due to risk of embrittlement?",
        options: ["Cadmium-coated fasteners", "Stainless steel fasteners", "Aluminum rivets"],
        correctOptionIndex: 0,
      },
      {
        id: 12,
        text: "What is a correct method for extinguishing a titanium fire?",
        options: ["Water or foam", "Dry asbestos wool and chalk powder", "Carbon dioxide (CO₂)"],
        correctOptionIndex: 1,
      },
      {
        id: 13,
        text: "Which nickel alloy is known for its use in gas turbine blades and high-temperature applications?",
        options: ["Monel", "Nimonic", "Brass"],
        correctOptionIndex: 1,
      },
      {
        id: 14,
        text: "What is a primary characteristic of Inconel alloys?",
        options: ["High electrical conductivity", "Excellent heat and corrosion resistance", "Lightweight and low density"],
        correctOptionIndex: 1,
      },
      {
        id: 15,
        text: "Which alloy is a nickel-copper combination often used for corrosion-resistant rivets?",
        options: ["Hastelloy", "K-Monel", "Incoloy"],
        correctOptionIndex: 1,
      },
      {
        id: 16,
        text: "What is a common use of beryllium bronze in aircraft?",
        options: ["Electrical wiring", "High-strength bearings and bushings", "Fuel lines"],
        correctOptionIndex: 1,
      },
      {
        id: 17,
        text: "Why is Tungum alloy no longer used in aircraft hydraulic systems?",
        options: ["It is too heavy", "It becomes brittle over time", "It corrodes easily"],
        correctOptionIndex: 1,
      },
      {
        id: 18,
        text: "What is the greenish layer that forms on copper called?",
        options: ["Rust", "Verdigris", "Galvanic coating"],
        correctOptionIndex: 1,
      },
      {
        id: 19,
        text: "Why is depleted uranium (DU) handled with special precautions?",
        options: ["It is highly flammable", "It is toxic both chemically and radiologically", "It corrodes rapidly in air"],
        correctOptionIndex: 1,
      },
      {
        id: 20,
        text: "What is a primary use of cadmium in aviation?",
        options: ["As a balance weight material", "As a protective coating on steel fasteners", "As a high-temperature alloy in engines"],
        correctOptionIndex: 1,
      },
      {
        id: 21,
        text: "According to the certification table, which license category has NO knowledge level requirement for testing ferrous materials for hardness, tensile strength, fatigue strength, and impact resistance?",
        options: ["A", "B1/B3", "B2/B2L"],
        correctOptionIndex: 0,
      },
      {
        id: 22,
        text: "In the stress-strain diagram, what does the \"necking\" region indicate?",
        options: ["The point where the material returns to its original length upon unloading.", "The onset of plastic deformation where strain increases without an increase in stress.", "The point where uniform plastic extension ends and localized deformation begins before fracture."],
        correctOptionIndex: 2,
      },
      {
        id: 23,
        text: "Which of the following statements about the microstructure of steel is FALSE?",
        options: ["Ferrite contains no more than 0.006% carbon and is soft and ductile.", "Cementite contains 6.67% carbon and is hard and brittle.", "Pearlite is a laminated structure of ferrite and austenite."],
        correctOptionIndex: 2,
      },
      {
        id: 24,
        text: "If a steel component is heated to 950°C and then quenched in oil, what is the most likely resulting microstructure if it contains 0.8% carbon?",
        options: ["Martensite", "Pearlite", "Austenite"],
        correctOptionIndex: 0,
      },
      {
        id: 25,
        text: "Which alloying element combination is primarily used to achieve \"austenitic\" stainless steel with non-magnetic properties?",
        options: ["18% Chromium, 8% Nickel", "12% Chromium, 0.5% Carbon", "15% Chromium, 5% Nickel"],
        correctOptionIndex: 0,
      },
      {
        id: 26,
        text: "Based on the table of alloying element effects, which element DECREASES machinability?",
        options: ["Chromium", "Molybdenum", "Nickel"],
        correctOptionIndex: 0,
      },
      {
        id: 27,
        text: "In the context of fatigue, what is represented by the \"ground-air-ground\" cycle?",
        options: ["The stress fluctuation during a single flight from takeoff to landing.", "The repeated pressurization and depressurization of the cabin.", "The transition from ground handling to in-flight maneuvering and back."],
        correctOptionIndex: 2,
      },
      {
        id: 28,
        text: "Which heat treatment process would you use to restore the crystalline structure of a cold-worked steel part that has become brittle, without making it as soft as fully annealed material?",
        options: ["Tempering", "Normalizing", "Case Hardening"],
        correctOptionIndex: 1,
      },
      {
        id: 29,
        text: "According to the phase-equilibrium diagram for iron-carbon, what is the approximate lower critical temperature (A1) for steel?",
        options: ["723°C", "950°C", "1,200°C"],
        correctOptionIndex: 0,
      },
      {
        id: 30,
        text: "Which of the following statements about 9Ni-4Co-0.30C steel is FALSE?",
        options: ["It is used for elevated temperature applications up to 900°F.", "It is a precipitation-hardened stainless steel.", "It is heat treated to 220-240 KSI."],
        correctOptionIndex: 1,
      },
      {
        id: 31,
        text: "In the cyanide hardening process, why is sodium cyanide considered dangerous?",
        options: ["It releases toxic fumes when heated.", "It is highly poisonous and requires strict safety precautions.", "It is highly corrosive to steel."],
        correctOptionIndex: 1,
      },
      {
        id: 32,
        text: "What is the primary advantage of nitriding over carburizing for case hardening?",
        options: ["It produces a thicker hardened case.", "It operates at a lower temperature, reducing distortion.", "It is faster and cheaper."],
        correctOptionIndex: 1,
      },
      {
        id: 33,
        text: "Which steel would be LEAST suitable for a highly stressed aircraft fitting requiring both high strength and good corrosion resistance?",
        options: ["15-5PH", "4340M", "304 Stainless"],
        correctOptionIndex: 2,
      },
      {
        id: 34,
        text: "If a steel has an AISI/SAE designation of 52100, what is its primary alloying element and approximate carbon content?",
        options: ["Chromium, 1.00% carbon", "Molybdenum, 0.30% carbon", "Nickel, 1.00% carbon"],
        correctOptionIndex: 0,
      },
      {
        id: 35,
        text: "In the context of creep, what does the \"steady-state creep\" phase indicate?",
        options: ["The initial elastic deformation under load.", "A constant rate of deformation over time.", "The final rapid deformation leading to rupture."],
        correctOptionIndex: 1,
      },
      {
        id: 36,
        text: "What is the primary reason for using vacuum remelt steels (like 4330M and 4340M) in critical aircraft components?",
        options: ["To improve magnetic properties.", "To enhance purity and mechanical properties (ductility, fatigue resistance).", "To reduce weight."],
        correctOptionIndex: 1,
      },
      {
        id: 37,
        text: "According to the module, which of the following is NOT a typical application for 17-4PH stainless steel?",
        options: ["Control levers and fittings", "Landing gear legs", "Cast housings"],
        correctOptionIndex: 1,
      },
      {
        id: 38,
        text: "Which property is NOT typically associated with martensitic stainless steels?",
        options: ["Magnetic", "Hardenable by heat treatment", "Non-responsive to heat treatment"],
        correctOptionIndex: 2,
      },
      {
        id: 39,
        text: "In flame hardening, why is the quenching water jet integrated into the torch assembly?",
        options: ["To cool the torch and prevent overheating.", "To immediately quench the heated surface before the core temperature rises.", "To provide a protective steam layer."],
        correctOptionIndex: 1,
      },
      {
        id: 40,
        text: "What does the \"T\" in the tempering colour chart (e.g., \"Straw\" at 430°F) indicate?",
        options: ["The temperature at which the steel should be quenched.", "The colour the steel surface oxidizes to at that temperature, used for temperature estimation.", "The colour of the steel after quenching."],
        correctOptionIndex: 1,
      },
    ],
  },
  "mathematics": {
    id: "mathematics",
    title: "Mathematics Symbols and Concepts",
    description: "Assessment on mathematical symbols, notation, and fundamental concepts. Answer all 114 questions about mathematical notation, number types, geometry, and operations. Time limit: 114 minutes.",
    durationMinutes: 114,
    questions: [
      { id: 1, text: "What does the symbol \"mod\" represent?", options: ["Multiplication", "Division", "Remainder calculation"], correctOptionIndex: 2 },
      { id: 2, text: "Which symbol means \"greater than or equal to\"?", options: [">", "≥", "≤"], correctOptionIndex: 1 },
      { id: 3, text: "What does the symbol \"±\" mean?", options: ["Plus and minus operations", "Multiplication", "Equals"], correctOptionIndex: 0 },
      { id: 4, text: "Which symbol is used for multiplication?", options: ["/", "÷", "×"], correctOptionIndex: 2 },
      { id: 5, text: "What does \"√a\" represent?", options: ["Cube root", "Square root", "Fourth root"], correctOptionIndex: 1 },
      { id: 6, text: "Which set of numbers includes {0, 1, 2, 3, …}?", options: ["Natural numbers", "Whole numbers", "Integers"], correctOptionIndex: 1 },
      { id: 7, text: "What are numbers that can be expressed as a ratio of two integers called?", options: ["Irrational numbers", "Rational numbers", "Real numbers"], correctOptionIndex: 1 },
      { id: 8, text: "Which type of number includes both real and imaginary parts?", options: ["Complex numbers", "Integers", "Natural numbers"], correctOptionIndex: 0 },
      { id: 9, text: "What does the symbol \"⊥\" represent?", options: ["Parallel lines", "Perpendicular lines", "Congruent shapes"], correctOptionIndex: 1 },
      { id: 10, text: "Which symbol represents an angle?", options: ["∆", "∠", "∥"], correctOptionIndex: 1 },
      { id: 11, text: "What does \"π\" represent?", options: ["Distance between two points", "Ratio of circumference to diameter of a circle", "Right angle"], correctOptionIndex: 1 },
      { id: 12, text: "Which symbol indicates that two shapes are similar but not necessarily the same size?", options: ["≅", "∼", "∥"], correctOptionIndex: 1 },
      { id: 13, text: "What does the symbol \"∝\" mean?", options: ["Approximately equal", "Proportional to", "Infinity"], correctOptionIndex: 1 },
      { id: 14, text: "What does \"∑\" represent?", options: ["Factorial", "Summation", "Absolute value"], correctOptionIndex: 1 },
      { id: 15, text: "Which symbol means \"much less than\"?", options: ["≫", "≈", "≪"], correctOptionIndex: 2 },
      { id: 16, text: "What does \"f(x)\" denote?", options: ["A constant", "A function of x", "A variable"], correctOptionIndex: 1 },
      { id: 17, text: "Which symbol rounds a number down to the nearest integer?", options: ["⌈x⌉", "⌊x⌋", "|x|"], correctOptionIndex: 1 },
      { id: 18, text: "Which symbol means \"not equal to\"?", options: ["=", "≠", "≈"], correctOptionIndex: 1 },
      { id: 19, text: "What does the symbol \"≤\" represent?", options: ["Less than", "Greater than or equal to", "Less than or equal to"], correctOptionIndex: 2 },
      { id: 20, text: "Which symbol is used for division in the form of a fraction (horizontal line)?", options: ["÷", "/", "—"], correctOptionIndex: 2 },
      { id: 21, text: "What does \"ppm\" stand for?", options: ["Parts-per-million", "Percent-per-meter", "Points-per-minute"], correctOptionIndex: 0 },
      { id: 22, text: "What is the cube root of 8?", options: ["2", "4", "±2"], correctOptionIndex: 0 },
      { id: 23, text: "Which set of numbers includes negative counting numbers and zero?", options: ["Natural numbers", "Whole numbers", "Integers"], correctOptionIndex: 2 },
      { id: 24, text: "What are real numbers that are not rational called?", options: ["Irrational numbers", "Imaginary numbers", "Complex numbers"], correctOptionIndex: 0 },
      { id: 25, text: "What does the symbol \"∡\" represent?", options: ["Angle", "Measured angle", "Right angle"], correctOptionIndex: 1 },
      { id: 26, text: "What is the symbol for parallel lines?", options: ["∥", "⊥", "≅"], correctOptionIndex: 0 },
      { id: 27, text: "Which symbol represents a line segment from point A to point B?", options: ["AB (with overline)", "→", "⌒"], correctOptionIndex: 0 },
      { id: 28, text: "What does \"rad\" stand for?", options: ["Radius", "Radians", "Right angle degree"], correctOptionIndex: 1 },
      { id: 29, text: "What does the symbol \"≡\" mean?", options: ["Approximately equal", "Identical to (equivalence)", "Proportional to"], correctOptionIndex: 1 },
      { id: 30, text: "What is the symbol for infinity?", options: ["∞", "≈", "∝"], correctOptionIndex: 0 },
      { id: 31, text: "What does the exclamation mark (!) represent in mathematics?", options: ["Absolute value", "Factorial", "Summation"], correctOptionIndex: 1 },
      { id: 32, text: "Which symbol represents the ceiling function, rounding up to the nearest integer?", options: ["⌊x⌋", "⌈x⌉", "|x|"], correctOptionIndex: 1 },
      { id: 33, text: "What does the symbol \"∓\" (minus-plus) represent?", options: ["Multiplication", "Both minus and plus operations", "Remainder calculation"], correctOptionIndex: 1 },
      { id: 34, text: "Which symbol is used for multiplication as an asterisk?", options: ["×", "*", "·"], correctOptionIndex: 1 },
      { id: 35, text: "What does the symbol \"·\" (dot) indicate in arithmetic?", options: ["Decimal point", "Division", "Multiplication"], correctOptionIndex: 2 },
      { id: 36, text: "Which symbol represents division in the form of a slash?", options: ["÷", "—", "/"], correctOptionIndex: 2 },
      { id: 37, text: "What does \"ppb\" stand for?", options: ["Parts-per-billion", "Percent-per-billion", "Points-per-billion"], correctOptionIndex: 0 },
      { id: 38, text: "What is the fourth root of 16?", options: ["2", "±2", "4"], correctOptionIndex: 1 },
      { id: 39, text: "Which symbol represents the n-th root (radical)?", options: ["√", "∛", "ⁿ√"], correctOptionIndex: 2 },
      { id: 40, text: "Which numbers are referred to as the counting numbers {1, 2, 3, …}?", options: ["Whole numbers", "Natural numbers", "Integers"], correctOptionIndex: 1 },
      { id: 41, text: "What type of numbers include both rational and irrational numbers?", options: ["Real numbers", "Complex numbers", "Imaginary numbers"], correctOptionIndex: 0 },
      { id: 42, text: "Which numbers are defined as the product of a real number and the square root of -1?", options: ["Imaginary numbers", "Complex numbers", "Irrational numbers"], correctOptionIndex: 0 },
      { id: 43, text: "What does the symbol \" ' \" (arcminute) represent?", options: ["1/60 of a degree", "1/60 of a radian", "1/360 of a circle"], correctOptionIndex: 0 },
      { id: 44, text: "Which symbol represents a ray starting from point A?", options: ["AB (line segment)", "→", "⌒"], correctOptionIndex: 1 },
      { id: 45, text: "What is the symbol for an arc from point A to point B?", options: ["↷", "⌒", "⇄"], correctOptionIndex: 1 },
      { id: 46, text: "In geometry, what does the symbol \"Δ\" represent?", options: ["Change or difference", "Triangle", "Distance"], correctOptionIndex: 1 },
      { id: 47, text: "Which notation represents the distance between points x and y?", options: ["d(x,y)", "|x-y|", "xy"], correctOptionIndex: 1 },
      { id: 48, text: "What is the symbol for a right angle (90°)?", options: ["∠", "⊥", "∟"], correctOptionIndex: 2 },
      { id: 49, text: "What does the symbol \"≅\" mean in geometry?", options: ["Similar", "Congruent", "Parallel"], correctOptionIndex: 1 },
      { id: 50, text: "What does the symbol \"~\" indicate in algebra?", options: ["Approximately equal (weak approximation)", "Proportional to", "Similarity"], correctOptionIndex: 0 },
      { id: 51, text: "Which symbol means \"much greater than\"?", options: ["≪", "≈", "≫"], correctOptionIndex: 2 },
      { id: 52, text: "What do braces \"{ }\" represent in algebra?", options: ["Parentheses for calculation", "Set notation", "Absolute value"], correctOptionIndex: 1 },
      { id: 53, text: "What does a single vertical bar \"|\" denote?", options: ["Factorial", "Absolute value", "Summation"], correctOptionIndex: 1 },
      { id: 54, text: "In algebra, what does the symbol \"Δ\" represent?", options: ["Triangle", "Change or difference", "Summation"], correctOptionIndex: 1 },
      { id: 55, text: "What is the value of 3±5 when the plus operation is used?", options: ["8", "–2", "Both 8 and –2"], correctOptionIndex: 0 },
      { id: 56, text: "If a number is a whole number, which of the following is necessarily true?", options: ["It is positive.", "It is non-negative.", "It is an integer."], correctOptionIndex: 1 },
      { id: 57, text: "In the expression 2^3, what does the caret (^) indicate?", options: ["Multiplication", "Exponentiation", "Division"], correctOptionIndex: 1 },
      { id: 58, text: "Which of the following is the correct notation for the cube root of 8?", options: ["√8", "∛8", "∜8"], correctOptionIndex: 1 },
      { id: 59, text: "How many degrees are in a right angle?", options: ["90°", "180°", "360°"], correctOptionIndex: 0 },
      { id: 60, text: "What does the symbol \"≈\" mean?", options: ["Approximately equal", "Identical to", "Proportional to"], correctOptionIndex: 0 },
      { id: 61, text: "Which of the following numbers is rational?", options: ["√2", "π", "0.75"], correctOptionIndex: 2 },
      { id: 62, text: "What is the purpose of parentheses in an arithmetic expression?", options: ["To indicate multiplication", "To group operations that should be performed first", "To denote a set"], correctOptionIndex: 1 },
      { id: 63, text: "If two lines are perpendicular, what is the measure of the angle between them?", options: ["0°", "90°", "180°"], correctOptionIndex: 1 },
      { id: 64, text: "In set notation, what does the ellipsis (…) indicate?", options: ["The set is empty", "The pattern continues indefinitely", "The set is finite"], correctOptionIndex: 1 },
      { id: 65, text: "If x=5 and y=3, what is the value of |x-y|?", options: ["2", "8", "15"], correctOptionIndex: 0 },
      { id: 66, text: "Evaluate: ⌈3.2⌉+⌊2.7⌋", options: ["5", "6", "7"], correctOptionIndex: 1 },
      { id: 67, text: "What is 10% of 50?", options: ["5", "10", "50"], correctOptionIndex: 0 },
      { id: 68, text: "If a circle has radius r, its circumference is given by:", options: ["πr", "2πr", "πr^2"], correctOptionIndex: 1 },
      { id: 69, text: "Which of the following represents a complex number with both real and imaginary parts?", options: ["3", "-5i", "2+3i"], correctOptionIndex: 2 },
      { id: 70, text: "Which symbol is used to denote arcsecond?", options: ["'", "\"", "°"], correctOptionIndex: 1 },
      { id: 71, text: "In the expression f(x)=x^2, what is f(3)?", options: ["6", "9", "3"], correctOptionIndex: 1 },
      { id: 72, text: "How many arcminutes are in one degree?", options: ["60", "360", "3600"], correctOptionIndex: 0 },
      { id: 73, text: "What is the value of 2^3?", options: ["6", "8", "9"], correctOptionIndex: 1 },
      { id: 74, text: "What is the measure in radians of a full circle (360°)?", options: ["π rad", "2π rad", "180 rad"], correctOptionIndex: 1 },
      { id: 75, text: "Given the expression 3∓5, which calculation pair is correct?", options: ["3-5=-2 and 3+5=8", "3-5=8 and 3+5=-2", "3×5=15 and 3÷5=0.6"], correctOptionIndex: 0 },
      { id: 76, text: "A number can be expressed as a/b where a and b are integers and b≠0. Which type of number must it be?", options: ["Always rational", "Always real", "Always integer"], correctOptionIndex: 0 },
      { id: 77, text: "If |x-7|=3, what are the possible values of x?", options: ["x=4 only", "x=10 only", "x=4 or x=10"], correctOptionIndex: 2 },
      { id: 78, text: "What does ∑_{i=1}^{4} (2i+1) equal?", options: ["24", "20", "18"], correctOptionIndex: 0 },
      { id: 79, text: "In geometry, if △ABC∼△XYZ, which of the following must be true?", options: ["Corresponding angles are equal, sides are proportional.", "Corresponding sides are equal, angles may differ.", "Both shapes have the same area."], correctOptionIndex: 0 },
      { id: 80, text: "Which of these numbers is both real and imaginary?", options: ["5", "-3i", "0"], correctOptionIndex: 2 },
      { id: 81, text: "The expression ⌊4.9⌋+⌈-2.3⌉ equals:", options: ["2", "3", "4"], correctOptionIndex: 0 },
      { id: 82, text: "If y∝x and k is the constant of proportionality, which equation is correct?", options: ["y=k+x", "y=k/x", "y=kx"], correctOptionIndex: 2 },
      { id: 83, text: "What is the value of 10 ppm × 5000?", options: ["0.05", "0.5", "50"], correctOptionIndex: 0 },
      { id: 84, text: "The fourth root of 81 is:", options: ["3 only", "±3", "9"], correctOptionIndex: 1 },
      { id: 85, text: "Which symbol set indicates \"calculate expression inside first\" in the order of operations?", options: ["(), [], {}", "+, -, ×, ÷", "=, ≠, >, <"], correctOptionIndex: 0 },
      { id: 86, text: "If ∠ABC=45° and ∠DBC is its complement, what is ∠DBC?", options: ["45°", "90°", "135°"], correctOptionIndex: 0 },
      { id: 87, text: "What does the symbol \"∡\" represent in the PDF?", options: ["Measured angle", "Right angle", "Parallel lines"], correctOptionIndex: 0 },
      { id: 88, text: "Evaluate 4!", options: ["16", "24", "256"], correctOptionIndex: 1 },
      { id: 89, text: "Which number type includes √2 but not 1/3?", options: ["Irrational numbers", "Rational numbers", "Integers"], correctOptionIndex: 0 },
      { id: 90, text: "If f(x)=2x+3, what is f^{-1}(7)?", options: ["2", "17", "5"], correctOptionIndex: 0 },
      { id: 91, text: "In the context of tolerance, 5±0.1 means:", options: ["Exactly 5", "Between 4.9 and 5.1 inclusive", "Between 4.5 and 5.5"], correctOptionIndex: 1 },
      { id: 92, text: "What is the principal cube root of -8?", options: ["-2", "2", "No real root"], correctOptionIndex: 0 },
      { id: 93, text: "If △ABC≅△DEF, which is necessarily true?", options: ["Same area only", "Same shape and size", "Same perimeter only"], correctOptionIndex: 1 },
      { id: 94, text: "Which symbol is used to denote \"much less than\"?", options: ["≪", "≫", "≈"], correctOptionIndex: 0 },
      { id: 95, text: "The symbol \"∓\" (minus-plus) is explicitly defined in the PDF as:", options: ["The same as ± but in reverse order", "Both minus and plus operations, where the upper sign is minus and the lower is plus", "A tolerance indicator for dimensions"], correctOptionIndex: 1 },
      { id: 96, text: "If a mod b=0, which of the following must be true?", options: ["a is less than b", "a is divisible by b", "a and b are both prime"], correctOptionIndex: 1 },
      { id: 97, text: "The radical expression ⁿ√a is equivalent to:", options: ["a^(1/n)", "a^n", "√a⋅n"], correctOptionIndex: 0 },
      { id: 98, text: "A number that can be written as a+bi where a and b are real and b≠0 is strictly called:", options: ["An imaginary number", "A non-real complex number", "A pure imaginary number"], correctOptionIndex: 1 },
      { id: 99, text: "In geometric notation, the symbol \"∡\" is specifically used to indicate:", options: ["An angle that has been measured numerically", "Any angle formed by two rays", "An angle of 90 degrees"], correctOptionIndex: 0 },
      { id: 100, text: "How many arcseconds are in 2.5 degrees?", options: ["9000", "150", "900"], correctOptionIndex: 0 },
      { id: 101, text: "Geometric congruence (≅) implies that two figures have:", options: ["The same area and perimeter", "Identical shape and size", "Proportional sides and equal angles"], correctOptionIndex: 1 },
      { id: 102, text: "The tilde (~) is defined in the algebra section as:", options: ["A weak approximation", "A strong approximation", "Proportionality"], correctOptionIndex: 0 },
      { id: 103, text: "The value of ⌊-7.8⌋+⌈3.2⌉ is:", options: ["–5", "–4", "–3"], correctOptionIndex: 1 },
      { id: 104, text: "In sigma notation, ∑_{k=1}^{n} k represents the sum of:", options: ["The first n integers", "The squares of the first n integers", "The reciprocals of the first n integers"], correctOptionIndex: 0 },
      { id: 105, text: "If y∝x and when x=4, y=12, what is the constant of proportionality k?", options: ["3", "8", "48"], correctOptionIndex: 0 },
      { id: 106, text: "Which of the following is an irrational number?", options: ["0.3̄ (repeating)", "√16", "∛2"], correctOptionIndex: 2 },
      { id: 107, text: "A concentration of 50 ppm means:", options: ["50 parts per hundred", "50 parts per million", "0.005%"], correctOptionIndex: 1 },
      { id: 108, text: "In geometry, the symbol \"L\" denotes:", options: ["A line", "A right angle (exactly 90°)", "An arc length"], correctOptionIndex: 1 },
      { id: 109, text: "The expression |x|=0 has how many real solutions?", options: ["0", "1", "2"], correctOptionIndex: 1 },
      { id: 110, text: "The factorial notation n! is defined as the product of:", options: ["All integers from 1 to n", "All even numbers up to n", "All prime numbers up to n"], correctOptionIndex: 0 },
      { id: 111, text: "According to the PDF, which number is both real and imaginary?", options: ["1", "–i", "0"], correctOptionIndex: 2 },
      { id: 112, text: "If two triangles are similar (∼), their corresponding sides are:", options: ["Equal", "Proportional", "Unrelated"], correctOptionIndex: 1 },
      { id: 113, text: "The infinity symbol (∞) is also called:", options: ["Lemniscate", "Omega", "Sigma"], correctOptionIndex: 0 },
      { id: 114, text: "For the ceiling function, ⌈-1.5⌉ equals:", options: ["–2", "–1", "1"], correctOptionIndex: 1 },
    ],
  },
};

export const getTestByName = (testName: string | null): TestConfig | null => {
  if (!testName) return null;
  return allTests[testName] || null;
};

export const getAvailableTests = () => {
  return Object.keys(allTests).map(key => ({
    id: key,
    title: allTests[key].title,
    description: allTests[key].description,
    questionCount: allTests[key].questions.length,
    duration: allTests[key].durationMinutes,
  }));
};
