export const atomicStructureChemistryQuestions = [
  {
    id: 1,
    text: "Who was the first to call tiny discrete units of matter 'atomos'?",
    options: ["Aristotle", "Democritus", "Socrates"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "The Greek phrase 'atomos' means:",
    options: ["Small particle", "Not cut or indivisible", "Fundamental unit"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "Which particle has a relative mass of 1 and positive charge?",
    options: ["Electron", "Neutron", "Proton"],
    correctOptionIndex: 2,
  },
  {
    id: 4,
    text: "Which particle has a relative mass of 1 and zero charge?",
    options: ["Proton", "Neutron", "Electron"],
    correctOptionIndex: 1,
  },
  {
    id: 5,
    text: "Which particle has a relative mass of 1/1850 and negative charge?",
    options: ["Proton", "Neutron", "Electron"],
    correctOptionIndex: 2,
  },
  {
    id: 6,
    text: "Where are protons and neutrons located in an atom?",
    options: ["In electron shells", "In the nucleus", "In orbits around the nucleus"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "What determines the size of an atom?",
    options: ["Number of protons in the nucleus", "Number of neutrons in the nucleus", "Electron orbits"],
    correctOptionIndex: 2,
  },
  {
    id: 8,
    text: "What determines the substance (mass) of an atom?",
    options: ["Number of electron orbits", "Total number of protons and neutrons in the nucleus", "Number of electrons only"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "Which is the simplest atom with a single proton as its nucleus?",
    options: ["Helium", "Hydrogen", "Oxygen"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "A lead atom has how many protons and neutrons in its nucleus?",
    options: ["82 protons and 125 neutrons", "80 protons and 121 neutrons", "82 protons and 82 neutrons"],
    correctOptionIndex: 0,
  },
  {
    id: 11,
    text: "According to Dalton's theory, atoms are:",
    options: ["Divisible particles", "Indivisible particles", "Transformable particles"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "According to Dalton's theory, atoms of the same element are:",
    options: ["Different", "Identical", "Variable"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "According to Dalton's theory, molecules are:",
    options: ["Combination of any two or more atoms", "Single atoms", "Only compounds"],
    correctOptionIndex: 0,
  },
  {
    id: 14,
    text: "The law of conservation of mass is a consequence of which Dalton's principle?",
    options: ["Atoms are indivisible", "Atoms themselves do not change during chemical reactions", "All atoms of an element are identical"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "Like charges:",
    options: ["Attract each other", "Repel each other", "Have no effect on each other"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "Opposite charges:",
    options: ["Repel each other", "Attract each other", "Have no effect on each other"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "Approximately how many times smaller are electrons compared to protons and neutrons?",
    options: ["200 times smaller", "2,000 times smaller", "20,000 times smaller"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "What forms around the atomic nucleus due to electron movement?",
    options: ["Solid shell", "Electron cloud", "Magnetic field"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "The periodic table is ordered by:",
    options: ["Atomic mass", "Atomic number", "Date of discovery"],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "The rows of the periodic table are called:",
    options: ["Groups", "Periods", "Blocks"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "The columns of the periodic table are called:",
    options: ["Periods", "Groups", "Series"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "Group 17 elements are known as:",
    options: ["Alkali metals", "Halogens", "Noble gases"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "Group 18 elements are known as:",
    options: ["Halogens", "Alkali metals", "Noble gases"],
    correctOptionIndex: 2,
  },
  {
    id: 24,
    text: "Who published the first widely recognised periodic table in 1869?",
    options: ["John Dalton", "Dmitri Mendeleev", "Neils Bohr"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "Elements from atomic numbers 1 to what have been discovered or synthesised?",
    options: ["100", "118", "120"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "The first how many elements exist naturally?",
    options: ["82", "94", "103"],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "Which element does not readily fit into any group?",
    options: ["Helium", "Oxygen", "Hydrogen"],
    correctOptionIndex: 2,
  },
  {
    id: 28,
    text: "The group number equals the number of electrons in which shell?",
    options: ["Inner shell", "Outer shell", "Middle shell"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "What are the two classes of pure substances?",
    options: ["Elements and mixtures", "Elements and compounds", "Compounds and mixtures"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "An element is made up of atoms with:",
    options: ["Different numbers of protons", "The same number of protons", "Variable numbers of protons"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "Can an element be broken down into simpler matter by physical or chemical means?",
    options: ["Yes", "No", "Only by physical means"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "A mixture consists of two or more different elements or compounds that are:",
    options: ["Chemically bonded", "Not chemically bonded but physically intermingled", "Always in fixed ratios"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "Can a mixture be separated into its components by physical means?",
    options: ["No", "Yes", "Only by chemical means"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "A compound is made up of two or more kinds of:",
    options: ["Physically mixed atoms", "Chemically bonded atoms", "Separated atoms"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "The properties of a compound compared to the atoms that make it up are:",
    options: ["The same", "Different", "Similar"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "Can a compound be broken down by physical means?",
    options: ["Yes", "No, only by chemical means", "Yes, easily"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "A compound always contains:",
    options: ["Variable ratios of component atoms", "The same ratio of component atoms", "Only one type of atom"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "Approximately how many elements are there in our known universe?",
    options: ["50", "92", "118"],
    correctOptionIndex: 2,
  },
  {
    id: 39,
    text: "A molecule is two or more atoms that have:",
    options: ["Physically mixed", "Chemically bonded", "Separated"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "Diatomic molecules are made up of:",
    options: ["Three atoms", "Two atoms", "Four atoms"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "Which of these is a diatomic molecule?",
    options: ["Ozone (O₃)", "Oxygen (O₂)", "Water (H₂O)"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "Triatomic molecules are made up of:",
    options: ["Two atoms", "Three atoms", "Four atoms"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "Which is an example of a triatomic molecule?",
    options: ["Oxygen (O₂)", "Ozone (O₃)", "Hydrogen (H₂)"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "The chemical formula for water is:",
    options: ["H₂O₂", "H₂O", "CO₂"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "The chemical formula H₂O shows the ratio of hydrogen to oxygen as:",
    options: ["1:1", "2:1", "1:2"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "Which of these is an example of a compound?",
    options: ["Oxygen gas (O₂)", "Hydrogen gas (H₂)", "Sodium chloride (NaCl)"],
    correctOptionIndex: 2,
  },
  {
    id: 47,
    text: "Which of these is an example of an element?",
    options: ["Water (H₂O)", "Carbon dioxide (CO₂)", "Nitrogen gas (N₂)"],
    correctOptionIndex: 2,
  },
  {
    id: 48,
    text: "The substances initially involved in a chemical reaction are called:",
    options: ["Products", "Reactants or reagents", "Catalysts"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "The substances produced in a chemical reaction are called:",
    options: ["Reactants", "Reagents", "Products"],
    correctOptionIndex: 2,
  },
  {
    id: 50,
    text: "Reaction rates typically increase with increasing temperature because:",
    options: ["Molecules move slower", "More thermal energy is available to reach activation energy", "Bonds become stronger"],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "A catalyst:",
    options: ["Decreases reaction rate", "Increases reaction rate and is consumed", "Increases reaction rate and is not consumed"],
    correctOptionIndex: 2,
  },
  {
    id: 52,
    text: "Inhibitors are sometimes called:",
    options: ["Positive catalysts", "Negative catalysts", "Accelerators"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "The atomic number (Z) is the number of:",
    options: ["Neutrons in the nucleus", "Protons in the nucleus", "Electrons plus neutrons"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "In a neutral atom, the atomic number equals the number of:",
    options: ["Neutrons", "Protons plus neutrons", "Electrons"],
    correctOptionIndex: 2,
  },
  {
    id: 55,
    text: "The mass number (A) is the number of:",
    options: ["Protons only", "Neutrons only", "Protons and neutrons"],
    correctOptionIndex: 2,
  },
  {
    id: 56,
    text: "The number of neutrons in a nucleus is given by:",
    options: ["Z - A", "A - Z", "A + Z"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "Carbon-12 has how many protons and neutrons?",
    options: ["6 protons and 8 neutrons", "6 protons and 6 neutrons", "8 protons and 6 neutrons"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "Carbon-14 has how many protons and neutrons?",
    options: ["6 protons and 8 neutrons", "6 protons and 6 neutrons", "8 protons and 6 neutrons"],
    correctOptionIndex: 0,
  },
  {
    id: 59,
    text: "One atomic mass unit (AMU) is defined as:",
    options: ["The mass of a proton", "1/12 the mass of a carbon-12 atom", "The mass of a neutron"],
    correctOptionIndex: 1,
  },
  {
    id: 60,
    text: "The carbon-12 atom has how many protons and neutrons?",
    options: ["6 protons and 8 neutrons", "8 protons and 6 neutrons", "6 protons and 6 neutrons"],
    correctOptionIndex: 2,
  },
  {
    id: 61,
    text: "One AMU is approximately:",
    options: ["1.67 × 10⁻²⁷ kg", "1.67 × 10⁻²⁰ kg", "1.67 × 10⁻¹⁵ kg"],
    correctOptionIndex: 0,
  },
  {
    id: 62,
    text: "Isotopes are atoms of the same element with different numbers of:",
    options: ["Protons", "Neutrons", "Electrons"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "Isotopes of the same element have the same:",
    options: ["Mass number", "Atomic number", "Number of neutrons"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "Isotopes of the same element have different:",
    options: ["Atomic number", "Proton number", "Mass number"],
    correctOptionIndex: 2,
  },
  {
    id: 65,
    text: "The three isotopes of hydrogen are:",
    options: ["Hydrogen, helium, lithium", "Hydrogen, deuterium, tritium", "Protium, deuterium, tritium"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "How many neutrons does deuterium have?",
    options: ["0", "1", "2"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "How many neutrons does tritium have?",
    options: ["0", "1", "2"],
    correctOptionIndex: 2,
  },
  {
    id: 68,
    text: "How many neutrons does ordinary hydrogen have?",
    options: ["0", "1", "2"],
    correctOptionIndex: 0,
  },
  {
    id: 69,
    text: "The three isotopes of carbon found in nature are:",
    options: ["Carbon-10, Carbon-11, Carbon-12", "Carbon-12, Carbon-13, Carbon-14", "Carbon-12, Carbon-14, Carbon-16"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "Chemically, different isotopes of the same element are:",
    options: ["Different", "Identical", "Slightly different"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "The electron shells are lettered from the innermost outwards as:",
    options: ["A, B, C, D", "K, L, M, N", "1, 2, 3, 4"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "The maximum number of electrons in the first shell (K) is:",
    options: ["8", "2", "18"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "The maximum number of electrons in the second shell (L) is:",
    options: ["2", "8", "18"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "The maximum number of electrons in the third shell (M) is:",
    options: ["8", "18", "32"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "The maximum number of electrons in the fourth shell (N) is:",
    options: ["18", "32", "50"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "According to Pauli's exclusion principle, the maximum electrons in an orbit with number \"n\" is:",
    options: ["n²", "2n²", "2n"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "Electrons closest to the nucleus are:",
    options: ["Least tightly bound", "Most tightly bound", "Not bound at all"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "The subshells that hold electrons are named:",
    options: ["a, b, c, d", "s, p, d, f", "k, l, m, n"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "Which subshell has the lowest energy?",
    options: ["2s", "2p", "1s"],
    correctOptionIndex: 2,
  },
  {
    id: 80,
    text: "The electron configuration of hydrogen is written as:",
    options: ["1s²", "1s¹", "2s¹"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "The electron configuration of lithium is:",
    options: ["1s² 2s¹", "1s¹ 2s²", "1s² 2s²"],
    correctOptionIndex: 0,
  },
  {
    id: 82,
    text: "The electron configuration of phosphorus is:",
    options: ["1s² 2s² 2p⁶ 3s² 3p³", "1s² 2s² 2p⁶ 3s¹ 3p⁴", "1s² 2s² 2p⁶ 3s² 3p⁵"],
    correctOptionIndex: 0,
  },
  {
    id: 83,
    text: "A cation is:",
    options: ["A negatively charged ion", "A positively charged ion", "A neutral atom"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "An anion is:",
    options: ["A positively charged ion", "A negatively charged ion", "A neutral atom"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "Metals typically form:",
    options: ["Anions", "Cations", "Neutral atoms"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "Nonmetals typically form:",
    options: ["Cations", "Anions", "No ions"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "Valency can be simply defined as:",
    options: ["The number of electrons in an atom", "The number of hydrogen atoms an element can combine with", "The atomic number"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "What is the valency of helium, neon and argon?",
    options: ["1", "2", "0"],
    correctOptionIndex: 2,
  },
  {
    id: 89,
    text: "What is the valency of lithium, sodium and potassium?",
    options: ["0", "1", "2"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "What is the valency of beryllium, magnesium and calcium?",
    options: ["1", "2", "3"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "What is the valency of boron and aluminium?",
    options: ["2", "3", "4"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "What is the valency of carbon and silicon?",
    options: ["3", "4", "5"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "What is the normal valency of nitrogen and phosphorus?",
    options: ["5", "3", "4"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "What is the valency of oxygen and sulphur?",
    options: ["1", "2", "3"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "What is the valency of fluorine and chlorine?",
    options: ["2", "1", "3"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "An atom with 1 electron binding is called:",
    options: ["Divalent", "Monovalent", "Trivalent"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "An atom with 4 electron binding is called:",
    options: ["Tetravalent", "Trivalent", "Pentavalent"],
    correctOptionIndex: 0,
  },
  {
    id: 98,
    text: "Atoms with full electron shells (noble gases) are:",
    options: ["Highly reactive", "Chemically inert", "Moderately reactive"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "In a conductor, electric current can flow:",
    options: ["With difficulty", "Freely", "Not at all"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "Metals are classified as conductors because:",
    options: ["Their electrons are tightly bound", "Their outer electrons are loosely bound and free to move", "They have no electrons"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "Most nonmetallic solids are:",
    options: ["Good conductors", "Good insulators", "Semiconductors"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "The resistance of semiconductors as temperature increases:",
    options: ["Increases", "Decreases", "Stays the same"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "The resistance of metals as temperature increases:",
    options: ["Increases", "Decreases", "Stays the same"],
    correctOptionIndex: 0,
  },
  {
    id: 104,
    text: "The process of deliberately introducing impurities into a semiconductor crystal is called:",
    options: ["Bonding", "Doping", "Mixing"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Silicon and germanium have how many electrons in their outer shell?",
    options: ["3", "4", "5"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "Materials with atoms placed at random are called:",
    options: ["Crystalline", "Amorphous", "Lattice"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "Materials with atoms placed in a highly ordered structure are called:",
    options: ["Amorphous", "Crystalline", "Random"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "The forces that hold atoms together are called:",
    options: ["Physical bonds", "Chemical bonds", "Magnetic bonds"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "Cohesion is the intermolecular force between:",
    options: ["Dissimilar atoms", "Liquid particle types", "Gas particles"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "Adhesion is the intermolecular force between:",
    options: ["Similar atoms", "Dissimilar atoms", "Gas molecules"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "Noble gases exist as:",
    options: ["Molecules", "Single atoms", "Compounds"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "Covalent bonding involves:",
    options: ["Transfer of electrons", "Sharing of electrons", "Free electrons"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "Covalent bonding is usually formed between:",
    options: ["Two metallic elements", "Two non-metallic elements", "A metal and a non-metal"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "One single covalent bond is a sharing of:",
    options: ["One electron", "One pair of electrons", "Two pairs of electrons"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "Small covalent molecules have:",
    options: ["High melting and boiling points", "Low melting and boiling points", "Very high melting points"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "Diamond is an allotrope of:",
    options: ["Silicon", "Carbon", "Oxygen"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "Graphite is an allotrope of:",
    options: ["Silicon", "Carbon", "Boron"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "Ionic bonding involves:",
    options: ["Sharing of electrons", "Transfer of electrons", "Free electron cloud"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "In ionic bonding, the atom losing electrons forms a:",
    options: ["Negative ion (anion)", "Positive ion (cation)", "Neutral atom"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "In ionic bonding, the atom gaining electrons forms a:",
    options: ["Positive ion (cation)", "Negative ion (anion)", "Neutral atom"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "Sodium chloride (NaCl) is an example of:",
    options: ["Covalent bonding", "Ionic bonding", "Metallic bonding"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "Ionic compounds at room temperature are:",
    options: ["Gases", "Liquids", "Crystalline solids"],
    correctOptionIndex: 2,
  },
  {
    id: 123,
    text: "Solid ionic crystals do not conduct electricity because:",
    options: ["Electrons are free", "Ions are not free to move", "They have no ions"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "When ionic compounds are melted or dissolved in water, they:",
    options: ["Do not conduct electricity", "Conduct electricity", "Become gases"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "In metallic bonding, outer electrons are:",
    options: ["Tightly bound to atoms", "Free to move between positive metal ions", "Shared in pairs"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "The 'electron cloud' in metallic bonding refers to:",
    options: ["Bound electrons", "Free or de-localised electrons", "Shared electron pairs"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "Metals are good conductors of electricity because of:",
    options: ["Bound electrons", "Free electrons", "Ionic movement"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "In a solid, atoms or molecules are:",
    options: ["Far apart with random movement", "Packed closely together with fixed positions", "Free to move throughout the volume"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "In a liquid, particles are:",
    options: ["Fixed in position", "Free to move within the volume with a discrete surface", "Completely free with no surface"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "In a gas, atoms or molecules:",
    options: ["Have fixed positions", "Move freely without definite shape or volume", "Form a discrete surface"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "Plasma is typically:",
    options: ["A neutral gas", "An ionised gas", "A solid"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "The process of a solid becoming a gas without becoming liquid is called:",
    options: ["Condensation", "Sublimation", "Deposition"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "The process of a gas becoming a solid without going through liquid phase is called:",
    options: ["Sublimation", "Deposition", "Condensation"],
    correctOptionIndex: 1,
  },
  {
    id: 134,
    text: "Brownian motion is the random movement of particles in:",
    options: ["Solids only", "Fluids (liquids and gases)", "Vacuum"],
    correctOptionIndex: 1,
  },
  {
    id: 135,
    text: "Brownian motion is named after the botanist:",
    options: ["John Dalton", "Robert Brown", "Neils Bohr"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "When solids are heated, the atoms:",
    options: ["Expand", "Vibrate faster about their fixed points", "Stop moving"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "Liquids expand more than solids when heated because:",
    options: ["Atoms are larger", "Bonds between separate molecules are less tight", "They have more atoms"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "A liquid thermometer works on the principle of:",
    options: ["Contraction of solids", "Thermal expansion of liquids", "Gas pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "When gases in a fixed volume are heated:",
    options: ["Volume increases", "Pressure increases", "Pressure decreases"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "Acids turn blue litmus paper:",
    options: ["Blue", "Red", "Green"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "Acids have a pH:",
    options: ["Greater than 7", "Less than 7", "Equal to 7"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "Alkalis turn red litmus paper:",
    options: ["Red", "Blue", "Green"],
    correctOptionIndex: 1,
  },
  {
    id: 143,
    text: "Alkalis have a pH:",
    options: ["Less than 7", "Greater than 7", "Equal to 7"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "A neutral solution has a pH of:",
    options: ["0", "7", "14"],
    correctOptionIndex: 1,
  },
  {
    id: 145,
    text: "The pH scale ranges from:",
    options: ["1 to 10", "0 to 14", "0 to 7"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "Sulphuric acid is commonly found in:",
    options: ["Ni-Cad batteries", "Lead-acid batteries", "Drinking water"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "Potassium hydroxide is commonly found in:",
    options: ["Lead-acid batteries", "Ni-Cad batteries", "Vinegar"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "Vinegar is an example of:",
    options: ["Alkali", "Acid", "Neutral substance"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "Ammonia is an example of:",
    options: ["Acid", "Alkali", "Neutral substance"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "The universal indicator turns from green to red in:",
    options: ["Alkalis", "Acids", "Neutral solutions"],
    correctOptionIndex: 1,
  },
];
