export const avionicsQuestions = [
  { id: 1, text: "What is the primary purpose of an autopilot system?", options: ["To replace the pilot completely", "To reduce work strain and fatigue during long flights", "To increase aircraft speed"], correctOptionIndex: 1 },
  { id: 2, text: "An autopilot that controls only the ailerons is known as what?", options: ["Two-axis autopilot", "Single-axis autopilot or wing leveller", "Three-axis autopilot"], correctOptionIndex: 1 },
  { id: 3, text: "Two-axis autopilots control which flight control surfaces?", options: ["Ailerons and rudder", "Ailerons and elevators", "Elevators and rudder"], correctOptionIndex: 1 },
  { id: 4, text: "Three-axis autopilots control which flight control surfaces?", options: ["Ailerons only", "Ailerons, elevators, and rudder", "Elevators and rudder only"], correctOptionIndex: 1 },
  { id: 5, text: "What does an autothrottle function automatically control?", options: ["Flight path", "Engine thrust", "Landing gear"], correctOptionIndex: 1 },
  { id: 6, text: "What is a CAT IIIb landing also known as?", options: ["Manual landing", "Autoland", "Visual approach"], correctOptionIndex: 1 },
  { id: 7, text: "CAT IIIc would include what additional capability beyond CAT IIIb?", options: ["Automatic takeoff", "Landing, rollout, and taxi control to parking position", "Go-around capability"], correctOptionIndex: 1 },
  { id: 8, text: "Modern autopilots use what to control the aircraft?", options: ["Mechanical cams", "Computer software", "Hydraulic valves only"], correctOptionIndex: 1 },
  { id: 9, text: "Error in gyroscopes is known as what?", options: ["Precession", "Drift", "Inertia"], correctOptionIndex: 1 },
  { id: 10, text: "A six-dimensional Kalman filter typically resolves errors in which dimensions?", options: ["Latitude, longitude, and altitude only", "Roll, pitch, yaw, altitude, latitude, and longitude", "Speed, heading, and altitude only"], correctOptionIndex: 1 },
  { id: 11, text: "In CWS mode, how does the pilot control the autopilot?", options: ["Through the mode control panel only", "Through inputs on the yoke or stick", "Through radio tuning"], correctOptionIndex: 1 },
  { id: 12, text: "What does CMD mode stand for in autopilot operation?", options: ["Command mode where pilot has full control", "Command mode where autopilot has full control", "Compass mode"], correctOptionIndex: 1 },
  { id: 13, text: "In CWS mode, what does the autopilot do after the pilot makes an input?", options: ["Returns to manual mode", "Holds the specific heading and attitude until instructed otherwise", "Disengages completely"], correctOptionIndex: 1 },
  { id: 14, text: "What does CWS provide in terms of aircraft stability?", options: ["Only roll stability", "Stability in pitch and roll", "Only pitch stability"], correctOptionIndex: 1 },
  { id: 15, text: "Single-axis autopilot control is normally about which axis?", options: ["Pitch axis", "Roll axis", "Yaw axis"], correctOptionIndex: 1 },
  { id: 16, text: "What control surfaces form part of a single-axis autopilot loop?", options: ["Elevators", "Ailerons", "Rudder"], correctOptionIndex: 1 },
  { id: 17, text: "Heading-hold and radio-coupling are examples of what type of control?", options: ["Inner loop control", "Outer loop control", "Manual control"], correctOptionIndex: 1 },
  { id: 18, text: "Two-axis autopilot attitude control is normally about which axes?", options: ["Roll and yaw", "Roll and pitch", "Pitch and yaw"], correctOptionIndex: 1 },
  { id: 19, text: "Three-axis autopilot provides control about how many axes?", options: ["One", "Three", "Two"], correctOptionIndex: 1 },
  { id: 20, text: "What are the four basic subsections of an autopilot?", options: ["Gyros, computer, switches, motors", "Sensors, computer, controls, loads", "Transmitters, receivers, antennas, displays"], correctOptionIndex: 1 },
  { id: 21, text: "Which sensors are the most basic in an autopilot system?", options: ["Temperature sensors", "Gyros that sense pitch, roll, and heading", "Fuel flow sensors"], correctOptionIndex: 1 },
  { id: 22, text: "What provides altitude and speed sensor information to the autopilot?", options: ["GPS", "Air data computer", "Radar altimeter"], correctOptionIndex: 1 },
  { id: 23, text: "The controls subsection of an autopilot is known as what?", options: ["Control wheel", "Mode control panel (MCP)", "Circuit breakers"], correctOptionIndex: 1 },
  { id: 24, text: "What do the loads in an autopilot system consist of?", options: ["Electrical power supplies", "Flight control surfaces moved by actuators", "Display units"], correctOptionIndex: 1 },
  { id: 25, text: "Which navigation aids can the autopilot be connected to?", options: ["Only GPS", "VOR, GPS, ILS (LOC and GS)", "Only ADF"], correctOptionIndex: 1 },
  { id: 26, text: "How is radio coupling initiated by the pilot?", options: ["By turning the control wheel", "By selecting NAV, GPS, or APR buttons on the MCP", "By tuning the radio only"], correctOptionIndex: 1 },
  { id: 27, text: "The inner control loop stabilises the aircraft around which axes?", options: ["Yaw only", "Pitch or roll axis", "All three axes"], correctOptionIndex: 1 },
  { id: 28, text: "The outer control loop controls the aircraft in which directions?", options: ["Only vertical", "Lateral and vertical direction", "Only lateral"], correctOptionIndex: 1 },
  { id: 29, text: "Outer loop control includes parameters such as?", options: ["Only altitude", "Airspeed, altitude, track, and radio beam interception", "Only heading"], correctOptionIndex: 1 },
  { id: 30, text: "The output elements of an autopilot system are called what?", options: ["Actuators", "Servos", "Motors"], correctOptionIndex: 1 },
  { id: 31, text: "Cable-actuated systems typically utilise what type of servos?", options: ["Hydraulic only", "Electric servo motors or electro-pneumatic servos", "Manual only"], correctOptionIndex: 1 },
  { id: 32, text: "Hydraulic actuated flight control systems use what type of autopilot servos?", options: ["Electric motors", "Electrohydraulic autopilot servos", "Pneumatic servos"], correctOptionIndex: 1 },
  { id: 33, text: "When the autopilot is not operating, what must servos allow?", options: ["Complete lockout of controls", "Unimpeded control surface movement", "Reduced control movement"], correctOptionIndex: 1 },
  { id: 34, text: "One type of electric servo uses a constantly running motor geared to the output shaft through what?", options: ["Reduction gears only", "Two magnetic clutches", "Direct drive"], correctOptionIndex: 1 },
  { id: 35, text: "Electro-pneumatic servos are controlled by what?", options: ["Mechanical cables", "Electrical signals from the autopilot amplifier", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 36, text: "What provides position feedback to the autopilot computer in electro-hydraulic systems?", options: ["Pressure sensor", "Linear variable differential transducer (LVDT)", "Flow meter"], correctOptionIndex: 1 },
  { id: 37, text: "In its basic mode, an autoflight control system functions as what?", options: ["Navigation system", "Stability augmentation system (SAS)", "Communication system"], correctOptionIndex: 1 },
  { id: 38, text: "When a system is initially engaged, what attitude is maintained?", options: ["Pre-programmed attitude", "Manually trimmed attitude existing at engagement", "Level flight attitude only"], correctOptionIndex: 1 },
  { id: 39, text: "If attitude changes due to air disturbance, what detects this change?", options: ["The pilot", "Attitude sensing elements", "The servos"], correctOptionIndex: 1 },
  { id: 40, text: "The error signal is fed to which element for amplification?", options: ["Servo", "Relevant control channel amplifier", "Control panel"], correctOptionIndex: 1 },
  { id: 41, text: "What is the purpose of the feedback or follow-up element in the servo?", options: ["Increase error signal", "Reduce input error signal and limit control applied", "Amplify the command"], correctOptionIndex: 1 },
  { id: 42, text: "The feedback element produces a signal that is what to the input error?", options: ["Same direction", "Equal and opposite", "Random"], correctOptionIndex: 1 },
  { id: 43, text: "What allows the pilot to inject command signals into control channels?", options: ["Control wheel", "Flight control panel", "Rudder pedals"], correctOptionIndex: 1 },
  { id: 44, text: "The flight control panel may be considered the primary element in which control loop?", options: ["Inner loop", "Outer control loop", "Feedback loop"], correctOptionIndex: 1 },
  { id: 45, text: "In basic form, control panels have which two main control facilities?", options: ["Speed and altitude", "Turn control and pitch control", "Heading and nav"], correctOptionIndex: 1 },
  { id: 46, text: "The centre detent position of the turn control knob provides what?", options: ["Manual control", "Interlock for pre-selected heading data from compass system", "Disconnect"], correctOptionIndex: 1 },
  { id: 47, text: "When the turn control knob is displaced, what circuit is completed?", options: ["Compass circuit", "Command signal circuit to roll control channel", "Pitch control circuit"], correctOptionIndex: 1 },
  { id: 48, text: "The aircraft is rolled into a turn at an angle proportional to what?", options: ["Aircraft speed", "Amount of displacement of the control knob", "Altitude"], correctOptionIndex: 1 },
  { id: 49, text: "When the turn control knob is returned to detent, what happens?", options: ["Turn continues", "Roll command and attitude sensor signals oppose, ailerons return to neutral", "Autopilot disengages"], correctOptionIndex: 1 },
  { id: 50, text: "Pitch control comprises a control wheel that can be rotated in which plane?", options: ["Horizontal plane", "Vertical plane", "Diagonal plane"], correctOptionIndex: 1 },
  { id: 51, text: "In systems with altitude-hold and glide path coupling, the pitch control includes what?", options: ["Additional servos", "Interlock circuit that disconnects these facilities when pitch change selected", "Warning lights"], correctOptionIndex: 1 },
  { id: 52, text: "The autopilot is what type of control loop?", options: ["Open control loop", "Closed control loop", "Manual loop"], correctOptionIndex: 1 },
  { id: 53, text: "When the autopilot is not engaged, what is the state of the clutches?", options: ["Closed", "Open", "Partially engaged"], correctOptionIndex: 1 },
  { id: 54, text: "During autopilot disengagement, what does the system do with servo outputs?", options: ["Sets them to maximum", "Synchronises them to zero", "Disables them"], correctOptionIndex: 1 },
  { id: 55, text: "Pilot tasks include all of the following EXCEPT?", options: ["Mode selection and switching", "Flying the aircraft manually at all times", "Setting navigation parameters"], correctOptionIndex: 1 },
  { id: 56, text: "MCP stands for what?", options: ["Main Control Panel", "Mode Control Panel", "Master Control Panel"], correctOptionIndex: 1 },
  { id: 57, text: "Where are MCPs typically mounted?", options: ["Pedestal", "On the glare shield", "Side console"], correctOptionIndex: 1 },
  { id: 58, text: "The glare shield functions as what?", options: ["Sun shade only", "Shield against outside glare", "Display mount only"], correctOptionIndex: 1 },
  { id: 59, text: "How many course controls are on the Boeing 737 NG MCP?", options: ["One", "Two (one on each side)", "Four"], correctOptionIndex: 1 },
  { id: 60, text: "The left course selector is used for which display?", options: ["Right NAV display", "Left NAV display screen", "PFD only"], correctOptionIndex: 1 },
  { id: 61, text: "The course control consists of what components?", options: ["Push button and digital readout", "Rotary switch and LED 3-number readout", "Rotary knob only"], correctOptionIndex: 1 },
  { id: 62, text: "The course readout ranges from what to what?", options: ["0 to 180 degrees", "0 to 359 degrees", "0 to 360 degrees"], correctOptionIndex: 1 },
  { id: 63, text: "The FD switch operates what?", options: ["Autopilot", "Flight director", "Autothrottle"], correctOptionIndex: 1 },
  { id: 64, text: "The flight director is seen as what on the HSI display?", options: ["Green dot", "Magenta cross", "Yellow line"], correctOptionIndex: 1 },
  { id: 65, text: "When both FDs are operated together, what determines the master?", options: ["Captain's side always master", "The FD operated first or corresponding A/P set to CMD", "First officer's side always master"], correctOptionIndex: 1 },
  { id: 66, text: "If pitch difference between A and B computers exceeds approximately how many degrees, FD bars disappear?", options: ["1-2 degrees", "2-4 degrees", "5-6 degrees"], correctOptionIndex: 1 },
  { id: 67, text: "If roll difference exceeds how many degrees, FD bars disappear?", options: ["1-2 degrees", "3-9 degrees", "10-15 degrees"], correctOptionIndex: 1 },
  { id: 68, text: "The A/T switch engages or disengages what?", options: ["Autopilot", "Autothrust", "Flight director"], correctOptionIndex: 1 },
  { id: 69, text: "N1 approximates the speed of which engine component?", options: ["Turbine", "Engine fan", "Compressor"], correctOptionIndex: 1 },
  { id: 70, text: "When the N1 button is activated, what does the A/T maintain?", options: ["Selected airspeed", "N1 (thrust) limits selected in the FMC", "Selected altitude"], correctOptionIndex: 1 },
  { id: 71, text: "The speed control can only control speed under what condition?", options: ["Autopilot engaged", "A/T armed and engaged", "Flight director on"], correctOptionIndex: 1 },
  { id: 72, text: "When active, the A/T mode displays what?", options: ["A/T ON", "MCP SPD", "SPEED MODE"], correctOptionIndex: 1 },
  { id: 73, text: "The 3-digit LED presents what speed information?", options: ["Actual aircraft speed", "Target speed", "Ground speed"], correctOptionIndex: 1 },
  { id: 74, text: "When Mach number is displayed, it appears as what?", options: ["Knots", "Percentage of Mach 1", "Miles per hour"], correctOptionIndex: 1 },
  { id: 75, text: "The C/O button toggles between what?", options: ["IAS and GS", "Mach and IAS in knots", "TAS and GS"], correctOptionIndex: 1 },
  { id: 76, text: "LVL CHG stands for what?", options: ["Level control", "Level change", "Level climb"], correctOptionIndex: 1 },
  { id: 77, text: "The level change function works with what systems to initiate altitude change?", options: ["Only autopilot", "A/T and FMC", "Only flight director"], correctOptionIndex: 1 },
  { id: 78, text: "When LVL CHG is activated, what mode does the A/T enter?", options: ["Active mode", "Armed mode", "Standby mode"], correctOptionIndex: 1 },
  { id: 79, text: "VNAV stands for what?", options: ["Visual Navigation", "Vertical Navigation", "Velocity Navigation"], correctOptionIndex: 1 },
  { id: 80, text: "When VNAV is active and A/P is active, what is controlling the vertical profile?", options: ["Pilot", "FMC", "MCP selected altitude"], correctOptionIndex: 1 },
  { id: 81, text: "The heading control comprises what components?", options: ["Push button only", "3-digit LED display, rotary switch, and HDG SEL button", "Rotary switch only"], correctOptionIndex: 1 },
  { id: 82, text: "The heading display ranges from what to what?", options: ["0-180 degrees", "0-359 degrees", "0-360 degrees"], correctOptionIndex: 1 },
  { id: 83, text: "The rotary switch has an engraved scale indicating what?", options: ["Heading degrees", "Maximum bank angle", "Turn rate"], correctOptionIndex: 1 },
  { id: 84, text: "When HDG SEL is active (LED on), heading is controlled by what?", options: ["FMC", "Pilot selection on the display", "GPS"], correctOptionIndex: 1 },
  { id: 85, text: "When HDG SEL is off, heading is controlled by what?", options: ["Pilot", "Data in the FMC", "Last selected heading"], correctOptionIndex: 1 },
  { id: 86, text: "LNAV stands for what?", options: ["Lateral Navigation", "Lateral Navigation", "Longitudinal Navigation"], correctOptionIndex: 1 },
  { id: 87, text: "When LNAV is active, what is being controlled?", options: ["Vertical profile", "Lateral profile of the aircraft", "Speed profile"], correctOptionIndex: 1 },
  { id: 88, text: "Heading and track in LNAV mode are controlled by what?", options: ["Pilot heading selection", "Navigation data entered into the FMC", "VOR radial"], correctOptionIndex: 1 },
  { id: 89, text: "VOR LOC stands for what?", options: ["VOR location", "VOR/localiser capture", "VOR locator"], correctOptionIndex: 1 },
  { id: 90, text: "The VOR LOC function works with what?", options: ["Only GPS", "FMC and frequencies set on navigation radios", "Only ADF"], correctOptionIndex: 1 },
  { id: 91, text: "The system automatically selects VOR or ILS mode based on what?", options: ["Pilot selection", "The frequency set", "Aircraft position"], correctOptionIndex: 1 },
  { id: 92, text: "The function sends commands to intercept and track what?", options: ["A GPS waypoint", "A predetermined radial", "An altitude"], correctOptionIndex: 1 },
  { id: 93, text: "APP stands for what?", options: ["Approach", "Approach", "Application"], correctOptionIndex: 1 },
  { id: 94, text: "When APP is active, it uses what to follow an approach path?", options: ["GPS only", "ILS frequency for the specified runway", "VOR only"], correctOptionIndex: 1 },
  { id: 95, text: "When APP is active, what does it establish the aircraft on?", options: ["Localiser only", "Glide slope to track down to runway threshold", "Final approach fix"], correctOptionIndex: 1 },
  { id: 96, text: "Once localiser is captured, the APP button light does what?", options: ["Flashes", "Extinguishes", "Turns red"], correctOptionIndex: 1 },
  { id: 97, text: "How can APP be disconnected after glideslope capture?", options: ["By pressing APP button again", "Disengage A/P and both FDs, tune NAV frequencies out, or press TO/GA", "By changing heading"], correctOptionIndex: 1 },
  { id: 98, text: "The altitude control comprises what components?", options: ["Rotary switch only", "5-digit LED display, rotary switch, and ALT HLD button", "Push button only"], correctOptionIndex: 1 },
  { id: 99, text: "To execute the displayed altitude, what must be pressed?", options: ["ALT HLD", "LVL CHG button", "VNAV"], correctOptionIndex: 1 },
  { id: 100, text: "To hold the existing actual altitude, what can the pilot press?", options: ["LVL CHG", "ALT HLD button", "V/S"], correctOptionIndex: 1 },
  { id: 101, text: "When V/S mode is active, what does it automatically engage?", options: ["Autopilot", "A/T in speed mode", "Flight director"], correctOptionIndex: 1 },
  { id: 102, text: "If the selected vertical rate exceeds available thrust, what happens?", options: ["Autopilot disengages", "Speed will decrease", "Climb continues normally"], correctOptionIndex: 1 },
  { id: 103, text: "V/S mode will not operate under what conditions?", options: ["During climb", "If ALT HLD is engaged or following glideslope capture", "During descent"], correctOptionIndex: 1 },
  { id: 104, text: "Each A/P has a button marked CMD and a corresponding what?", options: ["A/P button", "CWS button", "FD button"], correctOptionIndex: 1 },
  { id: 105, text: "The pilot can override A/P in CMD mode into CWS by doing what?", options: ["Pressing the CWS button", "Applying sufficient force to the control column", "Disengaging the autopilot"], correctOptionIndex: 1 },
  { id: 106, text: "In CWS mode with roll attitude less than 6 degrees, what happens?", options: ["Autopilot disengages", "Aircraft will level wings and hold heading", "Aircraft continues turning"], correctOptionIndex: 1 },
  { id: 107, text: "The A/P disengage/engage bar in the DOWN position does what?", options: ["Engages autopilot", "Disconnects both A/Ps and prevents re-engagement", "Activates CWS mode"], correctOptionIndex: 1 },
  { id: 108, text: "Autothrottle, autopilot, and flight director modes are displayed where?", options: ["On the MCP only", "At the flight mode annunciator or integrated into PFD", "On the standby instruments"], correctOptionIndex: 1 },
  { id: 109, text: "FMGS stands for what?", options: ["Flight Management Guidance System", "Flight Management and Guidance System", "Flight Mode Guidance System"], correctOptionIndex: 1 },
  { id: 110, text: "The interactive FMGS provides predictions of what?", options: ["Only weather", "Flight time, mileage, speed, economy profiles, and altitude", "Only fuel consumption"], correctOptionIndex: 1 },
  { id: 111, text: "The flight plan is entered via what?", options: ["MCP", "Multifunction control and display units (MCDUs)", "PFD"], correctOptionIndex: 1 },
  { id: 112, text: "If one FMGC fails, what happens?", options: ["System shuts down", "The other FMGC can perform all operations", "Manual control required"], correctOptionIndex: 1 },
  { id: 113, text: "The FM part provides which functions?", options: ["Autopilot command only", "Navigation, performance prediction, flight planning, managed guidance computation, information display", "Yaw functions only"], correctOptionIndex: 1 },
  { id: 114, text: "The FG part provides which functions?", options: ["Navigation only", "Autopilot command, flight director command, auto thrust command", "Performance only"], correctOptionIndex: 1 },
  { id: 115, text: "The flight augmentation part provides which functions?", options: ["Navigation only", "Yaw functions, flight envelope functions, wind shear protection, low energy warning", "Autopilot only"], correctOptionIndex: 1 },
  { id: 116, text: "In take-off mode, what does the autoflight system provide?", options: ["Cruise guidance", "Steering signals for ground roll, rotation, lift-off, and climb-out", "Landing guidance"], correctOptionIndex: 1 },
  { id: 117, text: "In heading hold mode, what does the autopilot do?", options: ["Turns to selected heading", "Holds the aircraft's existing heading", "Follows GPS track"], correctOptionIndex: 1 },
  { id: 118, text: "When HDG hold is selected while in a roll, what happens first?", options: ["Turn continues", "Autoflight system levels the aircraft off", "Autopilot disengages"], correctOptionIndex: 1 },
  { id: 119, text: "Heading hold mode is the basic mode for which axis?", options: ["Pitch", "Roll", "Yaw"], correctOptionIndex: 1 },
  { id: 120, text: "In heading select mode, what does the autoflight system do?", options: ["Holds current heading", "Controls aircraft to capture and hold heading selected on MCP", "Follows FMC flight plan"], correctOptionIndex: 1 },
  { id: 121, text: "In altitude hold mode, what does the autoflight system do?", options: ["Climbs to selected altitude", "Levels off and holds altitude at which mode was initiated", "Descends to minimum altitude"], correctOptionIndex: 1 },
  { id: 122, text: "Altitude hold is initiated by doing what?", options: ["Selecting altitude on MCP", "Pressing the selector knob in momentarily", "Pressing LVL CHG"], correctOptionIndex: 1 },
  { id: 123, text: "In altitude select mode, what does the autoflight system do?", options: ["Holds current altitude", "Levels off at preselected altitude and holds it", "Climbs indefinitely"], correctOptionIndex: 1 },
  { id: 124, text: "Level change mode is a combination of what two modes?", options: ["Heading and altitude", "Speed mode and thrust mode", "Pitch and roll"], correctOptionIndex: 1 },
  { id: 125, text: "In level change mode, what controls the speed of the aircraft?", options: ["Throttles", "Elevator", "Ailerons"], correctOptionIndex: 1 },
  { id: 126, text: "In level change climb, autothrottle controls engines to what limit?", options: ["Cruise thrust", "Upper limit", "Idle"], correctOptionIndex: 1 },
  { id: 127, text: "In level change descent, autothrottle controls engines to what limit?", options: ["Maximum thrust", "Lower limit", "Cruise thrust"], correctOptionIndex: 1 },
  { id: 128, text: "Vertical speed select mode is selected with which selector?", options: ["Altitude selector", "V/S selector", "Heading selector"], correctOptionIndex: 1 },
  { id: 129, text: "The read-out shows current vertical speed and does what?", options: ["Disengages autopilot", "Selects the V/S mode", "Engages autothrottle"], correctOptionIndex: 1 },
  { id: 130, text: "In navigation mode, who gives steering signals to flight control computers?", options: ["Pilot", "Flight management computer", "MCP"], correctOptionIndex: 1 },
  { id: 131, text: "In profile mode, who gives vertical steering and thrust commands?", options: ["Pilot", "FMS", "MCP"], correctOptionIndex: 1 },
  { id: 132, text: "In profile mode, the FMS does what?", options: ["Only altitude holds", "All altitude changes, captures, and holds", "Only climbs"], correctOptionIndex: 1 },
  { id: 133, text: "High-speed jet aircraft with swept-back wings have the undesirable problem of what?", options: ["Porpoising", "Dutch roll", "Phugoid oscillation"], correctOptionIndex: 1 },
  { id: 134, text: "Dutch roll is what type of oscillatory flight condition?", options: ["Pitch oscillation", "Yawing-rolling oscillation", "Longitudinal oscillation"], correctOptionIndex: 1 },
  { id: 135, text: "To counteract Dutch roll, aircraft are equipped with what?", options: ["Pitch dampers", "Yaw dampers", "Roll dampers"], correctOptionIndex: 1 },
  { id: 136, text: "For some aircraft, natural damping of Dutch roll depends on what?", options: ["Only aircraft weight", "Size of vertical stabiliser, rudder, and aircraft speed", "Only flap position"], correctOptionIndex: 1 },
  { id: 137, text: "The yaw damper system can be operated how?", options: ["Only with autopilot engaged", "Independently of the automatic control system", "Only on ground"], correctOptionIndex: 1 },
  { id: 138, text: "What senses the rate of yaw in a yaw damper system?", options: ["Accelerometer", "Rate gyro", "Air data computer"], correctOptionIndex: 1 },
  { id: 139, text: "The yaw damper provides what functions?", options: ["Only Dutch roll damping", "Dutch roll damping, turn coordination, engine failure compensation", "Only turn coordination"], correctOptionIndex: 1 },
  { id: 140, text: "A flight director system is essentially what without the servos?", options: ["Autothrottle system", "Autopilot system", "Navigation system"], correctOptionIndex: 1 },
  { id: 141, text: "In a flight director system, who controls the aircraft?", options: ["Autopilot", "Pilot following commands on instrument panel", "Flight computer"], correctOptionIndex: 1 },
  { id: 142, text: "Flight director information is displayed on which instrument?", options: ["Airspeed indicator", "Instrument that displays aircraft's attitude", "Heading indicator"], correctOptionIndex: 1 },
  { id: 143, text: "The instrument that displays flight director commands is known as what?", options: ["HSI", "FDI, ADI, EADI, or PFD", "ND"], correctOptionIndex: 1 },
  { id: 144, text: "Computed command indications relieve the pilot of what?", options: ["Aircraft control", "Many mental calculations for instrument flights", "Radio communication"], correctOptionIndex: 1 },
  { id: 145, text: "A radio wave is what type of wave?", options: ["Mechanical", "Electromagnetic", "Pressure"], correctOptionIndex: 1 },
  { id: 146, text: "The relationship between frequency and wavelength is what?", options: ["Directly proportional", "Inversely proportional", "Equal"], correctOptionIndex: 1 },
  { id: 147, text: "A high-frequency wave has what type of wavelength?", options: ["Long", "Short", "Medium"], correctOptionIndex: 1 },
  { id: 148, text: "A low-frequency wave has what type of wavelength?", options: ["Short", "Long", "Variable"], correctOptionIndex: 1 },
  { id: 149, text: "Radio waves propagate into space at what speed?", options: ["1,000 miles per second", "186,000 miles per second", "300,000 miles per hour"], correctOptionIndex: 1 },
  { id: 150, text: "The electric and electromagnetic field components of a radio wave are oriented at what angle to each other?", options: ["45°", "90°", "180°"], correctOptionIndex: 1 },
  { id: 151, text: "VLF, LF, and MF waves are known as what?", options: ["Sky waves", "Ground waves or surface waves", "Space waves"], correctOptionIndex: 1 },
  { id: 152, text: "Ground waves follow what as they travel?", options: ["Straight line", "The curvature of the earth", "The ionosphere"], correctOptionIndex: 1 },
  { id: 153, text: "Which navigation system uses ground waves?", options: ["VOR", "Automatic direction finders (ADF)", "GPS"], correctOptionIndex: 1 },
  { id: 154, text: "HF radio waves are known as what?", options: ["Ground waves", "Sky waves", "Space waves"], correctOptionIndex: 1 },
  { id: 155, text: "HF waves extend their range by doing what?", options: ["Following earth's curve", "Bouncing off the ionosphere", "Traveling through the earth"], correctOptionIndex: 1 },
  { id: 156, text: "HF frequency range is between what values?", options: ["118-136 MHz", "2 to 25 MHz", "300 MHz-3 GHz"], correctOptionIndex: 1 },
  { id: 157, text: "Above HF, radio waves are known as what?", options: ["Ground waves", "Space waves", "Sky waves"], correctOptionIndex: 1 },
  { id: 158, text: "Space waves are only capable of what type of transmission?", options: ["Over-the-horizon", "Line-of-sight", "Ground wave"], correctOptionIndex: 1 },
  { id: 159, text: "VHF communication radios operate in what frequency range?", options: ["30-88 MHz", "118.0 MHz to 136.975 MHz", "225-400 MHz"], correctOptionIndex: 1 },
  { id: 160, text: "How many channels are designated in the VHF range with 25 kHz spacing?", options: ["360", "720", "1,440"], correctOptionIndex: 1 },
  { id: 161, text: "In Europe, what spacing separates VHF communication channels?", options: ["25 kHz", "8.33 kHz", "50 kHz"], correctOptionIndex: 1 },
  { id: 162, text: "What converts audio pressure waves into electrical signals?", options: ["Transmitter", "Microphone", "Antenna"], correctOptionIndex: 1 },
  { id: 163, text: "What generates a radio carrier wave and combines voice signals?", options: ["Antenna", "Transmitter", "Receiver"], correctOptionIndex: 1 },
  { id: 164, text: "What converts electrical signals into electromagnetic waves?", options: ["Transmitter", "Transmitter antenna", "Microphone"], correctOptionIndex: 1 },
  { id: 165, text: "PTT stands for what?", options: ["Power to transmit", "Push-to-transmit", "Primary transmit trigger"], correctOptionIndex: 1 },
  { id: 166, text: "Where is the PTT switch usually mounted?", options: ["On the instrument panel", "On the control wheel", "On the throttle quadrant"], correctOptionIndex: 1 },
  { id: 167, text: "What separates the voice signal from the carrier wave at the receiver?", options: ["Antenna", "Receiver", "Speaker"], correctOptionIndex: 1 },
  { id: 168, text: "A combined transmitter and receiver is known as what?", options: ["Transmitter", "Transceiver", "Duplexer"], correctOptionIndex: 1 },
  { id: 169, text: "A combined microphone and headset is known as what?", options: ["Headset", "Boomset", "Combo set"], correctOptionIndex: 1 },
  { id: 170, text: "Can a single antenna both transmit and receive at the same time?", options: ["Yes", "No, not at the same time", "Only on VHF"], correctOptionIndex: 1 },
  { id: 171, text: "What is a major source of radio interference on aircraft?", options: ["Engine noise", "Discharge of static electricity from the aircraft", "GPS signals"], correctOptionIndex: 1 },
  { id: 172, text: "How is static charge produced on an aircraft?", options: ["By engines", "By friction from traveling through rain, dust, or pollutants", "By radio transmissions"], correctOptionIndex: 1 },
  { id: 173, text: "Static charge is more prevalent on aircraft capable of what speed?", options: ["100 kts or greater", "200 kts or greater", "300 kts or greater"], correctOptionIndex: 1 },
  { id: 174, text: "Static charge will not produce radio interference if what condition exists?", options: ["It discharges rapidly", "The charge remains stationary", "It is high voltage"], correctOptionIndex: 1 },
  { id: 175, text: "What do static dischargers do to the discharge current?", options: ["Increase it", "Lower the amount of discharge current", "Eliminate it completely"], correctOptionIndex: 1 },
  { id: 176, text: "With static dischargers, discharge occurs at what current level?", options: ["Higher current level", "Lower current level", "Same current level"], correctOptionIndex: 1 },
  { id: 177, text: "With static dischargers, discharge occurs how frequently?", options: ["Less frequently", "Much more frequently", "Same frequency"], correctOptionIndex: 1 },
  { id: 178, text: "Where are static dischargers mounted?", options: ["Only on wing tips", "Trailing edges and tips of wings, vertical and horizontal stabilisers, and control surfaces", "Only on the tail"], correctOptionIndex: 1 },
  { id: 179, text: "VHF is used for what type of communications?", options: ["Long-range worldwide", "Short-range voice and data communications", "Satellite communications"], correctOptionIndex: 1 },
  { id: 180, text: "VHF frequency range is what?", options: ["2-30 MHz", "118.000 - 136.975 MHz", "960-1215 MHz"], correctOptionIndex: 1 },
  { id: 181, text: "VHF transmissions are what type?", options: ["Sky wave", "Line-of-sight", "Ground wave"], correctOptionIndex: 1 },
  { id: 182, text: "Typical range of VHF signals is what?", options: ["50-75 nm", "100-150 nm", "200-300 nm"], correctOptionIndex: 1 },
  { id: 183, text: "What does the frequency select panel allow?", options: ["Only active frequency selection", "Standby frequency selection while operating on active frequency", "Only standby selection"], correctOptionIndex: 1 },
  { id: 184, text: "Most aircraft have a minimum of how many VHF communication systems?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 185, text: "Larger airliners typically have how many VHF communication systems?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 186, text: "HF system allows what type of voice communications?", options: ["Short-range only", "Long-distance worldwide", "Satellite only"], correctOptionIndex: 1 },
  { id: 187, text: "HF frequency range is what?", options: ["118-136 MHz", "2 - 29.999 MHz AM", "960-1215 MHz"], correctOptionIndex: 1 },
  { id: 188, text: "What reflects HF radio waves back to earth?", options: ["The ground", "The ionosphere", "The stratosphere"], correctOptionIndex: 1 },
  { id: 189, text: "The HF antenna must be matched to the transmission frequency using what?", options: ["A tuner in the cockpit", "An antenna coupler near the antenna", "A matching transformer"], correctOptionIndex: 1 },
  { id: 190, text: "Before transmission, the HF antenna is tuned automatically within how long?", options: ["Milliseconds", "A few seconds", "Minutes"], correctOptionIndex: 1 },
  { id: 191, text: "PTT changes the system from reception mode to what?", options: ["Standby", "Transmission mode", "Off"], correctOptionIndex: 1 },
  { id: 192, text: "SELCAL stands for what?", options: ["Selective Call", "Selective-calling radio system", "Selector caller"], correctOptionIndex: 1 },
  { id: 193, text: "SELCAL allows a ground station to do what?", options: ["Transmit continuously", "Alert an aircraft's crew that they wish to communicate", "Control the aircraft"], correctOptionIndex: 1 },
  { id: 194, text: "SELCAL operates on which frequency bands?", options: ["Only VHF", "HF or VHF", "Only UHF"], correctOptionIndex: 1 },
  { id: 195, text: "Why is SELCAL useful for HF radio?", options: ["HF has clear audio", "HF often has high background noise", "HF is not used"], correctOptionIndex: 1 },
  { id: 196, text: "An individual aircraft has its own assigned what?", options: ["Frequency", "SELCAL code", "Squawk code"], correctOptionIndex: 1 },
  { id: 197, text: "The SELCAL code consists of how many letters?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 198, text: "How are the audio tones transmitted?", options: ["All four tones simultaneously", "First pair simultaneously, silence, then second pair simultaneously", "One after another sequentially"], correctOptionIndex: 1 },
  { id: 199, text: "When a SELCAL decoder receives its code, how does it alert the crew?", options: ["Only a light", "Sounding a chime, activating a light, or both", "Only a chime"], correctOptionIndex: 1 },
  { id: 200, text: "The CALL legend flashes what color in the cockpit when SELCAL is received?", options: ["Red", "Amber", "Green"], correctOptionIndex: 1 },
  { id: 201, text: "SATCOM provides what type of services?", options: ["Only voice", "Continuous voice and data communications worldwide", "Only data"], correctOptionIndex: 1 },
  { id: 202, text: "The space segment comprises satellites in what type of orbit?", options: ["Low earth orbit", "Geosynchronous orbit", "Polar orbit"], correctOptionIndex: 1 },
  { id: 203, text: "Satellites function as what for communications?", options: ["Amplifiers", "Communication transponders", "Switches"], correctOptionIndex: 1 },
  { id: 204, text: "INMARSAT stands for what?", options: ["International Maritime Satellite Organization", "International Maritime Satellite Organization", "International Marine Satellite Association"], correctOptionIndex: 1 },
  { id: 205, text: "GES stands for what?", options: ["Ground Earth Station", "Ground Earth Station", "Ground Electronic System"], correctOptionIndex: 1 },
  { id: 206, text: "AES stands for what?", options: ["Aircraft Earth Station", "Aircraft Earth Station", "Airborne Electronic System"], correctOptionIndex: 1 },
  { id: 207, text: "The aircraft is connected to a GES via what?", options: ["Direct cable", "An 'in-view' satellite", "HF link"], correctOptionIndex: 1 },
  { id: 208, text: "ACARS stands for what?", options: ["Aircraft Communication And Reporting System", "Aircraft Communication Addressing and Reporting System", "Aviation Communication And Reporting System"], correctOptionIndex: 1 },
  { id: 209, text: "ACARS is an air-ground communication what?", options: ["Voice network", "Data link network", "Satellite network"], correctOptionIndex: 1 },
  { id: 210, text: "ACARS is dedicated to what purposes?", options: ["Only passenger communication", "Maintenance, operation, and commercial purposes", "Only air traffic control"], correctOptionIndex: 1 },
  { id: 211, text: "ACARS can transmit or receive via what systems?", options: ["Only VHF", "VHF transceiver or SATCOM", "Only HF"], correctOptionIndex: 1 },
  { id: 212, text: "ARINC operates ACARS and stands for what?", options: ["Aeronautical Radio Incorporated", "Aeronautical Radio Incorporated", "Aviation Radio Network"], correctOptionIndex: 1 },
  { id: 213, text: "SITA operates AIRCOM and stands for what?", options: ["Societe International de Telecomunication Aérienne", "Societe International de Telecomunication Aérienne", "Satellite International Transmission Association"], correctOptionIndex: 1 },
  { id: 214, text: "SITA-AIRCOM operates at what frequency in most of the world?", options: ["118.000 MHz", "131.725 MHz", "121.5 MHz"], correctOptionIndex: 1 },
  { id: 215, text: "ARINC-ACARS in the USA operates at what frequency?", options: ["131.725 MHz", "131.550 MHz", "121.5 MHz"], correctOptionIndex: 1 },
  { id: 216, text: "CPDLC stands for what?", options: ["Controller-Pilot Data Link Communications", "Controller-Pilot Data Link Communications", "Command Pilot Data Link Control"], correctOptionIndex: 1 },
  { id: 217, text: "CPDLC allows for what between controllers and pilots?", options: ["Voice communication", "Digital messaging", "Video communication"], correctOptionIndex: 1 },
  { id: 218, text: "CPDLC reduces what for pilots and controllers?", options: ["Flying time", "Workload", "Fuel consumption"], correctOptionIndex: 1 },
  { id: 219, text: "CPDLC is perhaps best known for use in what type of airspace?", options: ["Terminal areas", "Oceanic and remote airspace", "Dense continental airspace"], correctOptionIndex: 1 },
  { id: 220, text: "One primary advantage of CPDLC is what?", options: ["Faster voice communication", "Improved efficiency and accuracy compared to voice", "Lower cost"], correctOptionIndex: 1 },
  { id: 221, text: "DLIC stands for what?", options: ["Data Link Initiation Capability", "Data Link Initiation Capability", "Digital Link Interface Control"], correctOptionIndex: 1 },
  { id: 222, text: "ACM stands for what?", options: ["ATC Communications Management Service", "ATC Communications Management Service", "Airborne Communications Module"], correctOptionIndex: 1 },
  { id: 223, text: "ACL stands for what?", options: ["ATC Clearance Service", "ATC Clearances Service", "Airborne Control Link"], correctOptionIndex: 1 },
  { id: 224, text: "AMC stands for what?", options: ["ATC Microphone Check Service", "ATC Microphone Check Service", "Audio Management Control"], correctOptionIndex: 1 },
  { id: 225, text: "An audio management unit allows the pilot to do what?", options: ["Control engine noise", "Select the source of communication using the audio control panel", "Adjust radio volume only"], correctOptionIndex: 1 },
  { id: 226, text: "ACP stands for what?", options: ["Audio Control Panel", "Audio Control Panel", "Aircraft Control Panel"], correctOptionIndex: 1 },
  { id: 227, text: "What can the pilot select besides HF and VHF radios?", options: ["Only interphone", "Interphone, passenger address, cabin interphone, service interphone", "Only passenger address"], correctOptionIndex: 1 },
  { id: 228, text: "The audio control panel allows selection of what input devices?", options: ["Only microphone", "Hand-held microphone, boomset, smoke masks", "Only headset"], correctOptionIndex: 1 },
  { id: 229, text: "ELT stands for what?", options: ["Emergency Landing Transmitter", "Emergency Locator Transmitter", "Electronic Location Transmitter"], correctOptionIndex: 1 },
  { id: 230, text: "ELTs transmit a radio signal for what purpose?", options: ["Normal communications", "Allow rescue services to locate a crashed aircraft", "Weather reporting"], correctOptionIndex: 1 },
  { id: 231, text: "ELTs can be activated how?", options: ["Only manually", "Manually, by inertia switch, or by contact with water", "Only by inertia switch"], correctOptionIndex: 1 },
  { id: 232, text: "The 'golden day' refers to what?", options: ["First day of flying", "First 24 hours following a traumatic event when survivors can be saved", "Last day of search"], correctOptionIndex: 1 },
  { id: 233, text: "Where is the ELT normally located on an aircraft?", options: ["In the cockpit", "Near the back, least likely to be damaged", "In the nose"], correctOptionIndex: 1 },
  { id: 234, text: "ELT batteries can transmit for at least how long continuously?", options: ["12 hours", "24 hours", "48 hours"], correctOptionIndex: 1 },
  { id: 235, text: "121.5 MHz is what type of frequency?", options: ["Military only", "Standard emergency frequency monitored by civilian rescue stations", "Satellite only"], correctOptionIndex: 1 },
  { id: 236, text: "406 MHz is what type of signal?", options: ["Analogue voice", "Digital signal monitored by COSPAS-SARSAT satellites", "Military only"], correctOptionIndex: 1 },
  { id: 237, text: "COSPAS-SARSAT stands for what?", options: ["Cosmic Space Rescue System", "Cosmicheskaya Sistyema Poiska Avariynich Sudov - Search and Rescue Satellite-Aided Tracking", "Cooperative Satellite Rescue System"], correctOptionIndex: 1 },
  { id: 238, text: "In Europe and USA, all aircraft are required to have ELT transmitting on what frequency?", options: ["121.5 MHz only", "406 MHz", "243 MHz only"], correctOptionIndex: 1 },
  { id: 239, text: "CVR stands for what?", options: ["Cockpit Video Recorder", "Cockpit Voice Recorder", "Communications Voice Recorder"], correctOptionIndex: 1 },
  { id: 240, text: "EASA requires CVR for multi-engine turbine aircraft with MTOW over what?", options: ["2,700 kg", "5,700 kg", "10,000 kg"], correctOptionIndex: 1 },
  { id: 241, text: "CVR must retain recorded information over the last how many hours?", options: ["30 minutes", "2 hours", "25 hours"], correctOptionIndex: 1 },
  { id: 242, text: "For aircraft under 5,700 kg, recording time may be limited to what?", options: ["15 minutes", "30 minutes", "1 hour"], correctOptionIndex: 1 },
  { id: 243, text: "CVR must automatically begin recording before what event?", options: ["Takeoff", "Aircraft first moves under its own power", "Engine start"], correctOptionIndex: 1 },
  { id: 244, text: "CVR must continue recording until when?", options: ["Landing", "Aircraft no longer capable of moving under own power", "Engine shutdown"], correctOptionIndex: 1 },
  { id: 245, text: "CVR container is painted what color?", options: ["Black", "Distinctive orange or yellow", "Red"], correctOptionIndex: 1 },
  { id: 246, text: "Where is the CVR typically installed?", options: ["Nose section", "As far aft as practicable, near rear pressure bulkhead", "Cockpit"], correctOptionIndex: 1 },
  { id: 247, text: "How many inputs are there to the recording heads?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 248, text: "The microphones in the cockpit are always what?", options: ["Keyed by PTT", "'Hot' and do not require keying", "Only active during transmission"], correctOptionIndex: 1 },
  { id: 249, text: "VOR stands for what?", options: ["Visual Omni Range", "Very High-Frequency Omnidirectional Range", "Variable Omni Receiver"], correctOptionIndex: 1 },
  { id: 250, text: "VOR has been a reliable navigation source since when?", options: ["1940s", "1960s", "1980s"], correctOptionIndex: 1 },
  { id: 251, text: "What is often collocated with a VOR to give distance information?", options: ["GPS", "Distance Measuring Equipment (DME)", "ADF"], correctOptionIndex: 1 },
  { id: 252, text: "Each VOR has its own what to identify itself?", options: ["Color code", "Morse code identifier", "Number"], correctOptionIndex: 1 },
  { id: 253, text: "The VOR ground station emits how many signals?", options: ["One", "Two (360° sweeping variable and omni-directional reference)", "Three"], correctOptionIndex: 1 },
  { id: 254, text: "The aircraft's receiver compares the signals and measures what?", options: ["Signal strength", "Phase difference", "Frequency difference"], correctOptionIndex: 1 },
  { id: 255, text: "The CDI on a VOR indicator shows deviation from being on course. Each graduation represents how many degrees?", options: ["1°", "2°", "5°"], correctOptionIndex: 1 },
  { id: 256, text: "OBS stands for what?", options: ["Omni Bearing Selector", "Omni Bearing Selector", "Orientation Bearing System"], correctOptionIndex: 1 },
  { id: 257, text: "The OBS can be rotated to two positions where the CDI will centre. These positions are how many degrees apart?", options: ["90°", "180°", "360°"], correctOptionIndex: 1 },
  { id: 258, text: "The RMI is a compass repeater fitted with how many VOR pointers?", options: ["One", "Two (one for each VOR system)", "Three"], correctOptionIndex: 1 },
  { id: 259, text: "ADF stands for what?", options: ["Automatic Direction Finder", "Automatic Direction Finder", "Aviation Direction Finder"], correctOptionIndex: 1 },
  { id: 260, text: "NDB stands for what?", options: ["Non-Directional Beacon", "Non-Directional Beacon", "Navigation Data Beacon"], correctOptionIndex: 1 },
  { id: 261, text: "The ADF receives radio signals with how many antennas?", options: ["One", "Two (loop antenna and sense antenna)", "Three"], correctOptionIndex: 1 },
  { id: 262, text: "What does the loop antenna determine?", options: ["Whether toward or away from station", "The strength of signal to determine direction", "The frequency"], correctOptionIndex: 1 },
  { id: 263, text: "What does the sense antenna determine?", options: ["Direction", "Whether aircraft is moving toward or away from station", "Distance"], correctOptionIndex: 1 },
  { id: 264, text: "NDB operates on frequencies between what range?", options: ["118-136 MHz", "190-535 KHz", "960-1215 MHz"], correctOptionIndex: 1 },
  { id: 265, text: "NDB signals follow what?", options: ["Straight line", "The curvature of the Earth", "The ionosphere"], correctOptionIndex: 1 },
  { id: 266, text: "Homing to an NDB by simply pointing the aircraft in the direction of the arrow creates what pattern?", options: ["Straight line", "Arc pattern", "Spiral pattern"], correctOptionIndex: 1 },
  { id: 267, text: "ILS stands for what?", options: ["Instrument Landing System", "Instrument Landing System", "Integrated Landing System"], correctOptionIndex: 1 },
  { id: 268, text: "The descent axis in ILS is determined by the intersection of what two beams?", options: ["VOR and DME", "Localiser beam and glideslope beam", "Marker and localiser"], correctOptionIndex: 1 },
  { id: 269, text: "ILS is tuned via which panel?", options: ["COMM panel", "VHF NAV panel (shared with VOR)", "ADF panel"], correctOptionIndex: 1 },
  { id: 270, text: "Each glideslope channel is paired with what?", options: ["A separate frequency", "A specific localiser frequency", "A marker frequency"], correctOptionIndex: 1 },
  { id: 271, text: "Glideslope frequency is in which range?", options: ["VHF", "UHF", "HF"], correctOptionIndex: 1 },
  { id: 272, text: "DH stands for what?", options: ["Decision Height", "Decision Height", "Descent Height"], correctOptionIndex: 1 },
  { id: 273, text: "RVR stands for what?", options: ["Runway Visual Range", "Runway Visual Range", "Radar Visual Reference"], correctOptionIndex: 1 },
  { id: 274, text: "Category II ILS permits a DH of not lower than what?", options: ["200 ft", "100 ft", "50 ft"], correctOptionIndex: 1 },
  { id: 275, text: "Category IIIA requires RVR not less than what?", options: ["100m", "200m", "300m"], correctOptionIndex: 1 },
  { id: 276, text: "Category IIIB permits a DH below what?", options: ["100 ft", "50 ft", "0 ft"], correctOptionIndex: 1 },
  { id: 277, text: "Marker beacons operate at what frequency?", options: ["75 kHz", "75 MHz", "75 GHz"], correctOptionIndex: 1 },
  { id: 278, text: "Marker beacons use what type of antenna systems?", options: ["Directional", "Designed to propagate vertical beams", "Omni-directional"], correctOptionIndex: 1 },
  { id: 279, text: "The marker receiver output goes to what?", options: ["Only the display", "Headphones/speaker and display unit", "Only the audio system"], correctOptionIndex: 1 },
  { id: 280, text: "Outer marker light is what color?", options: ["Amber", "Blue", "White"], correctOptionIndex: 1 },
  { id: 281, text: "Middle marker light is what color?", options: ["Blue", "Amber", "White"], correctOptionIndex: 1 },
  { id: 282, text: "Inner marker light is what color?", options: ["Blue", "White", "Amber"], correctOptionIndex: 1 },
  { id: 283, text: "The HIGH sensitivity setting provides what?", options: ["Narrower dwell", "Earlier indication when nearing a marker", "No change"], correctOptionIndex: 1 },
  { id: 284, text: "MLS stands for what?", options: ["Microwave Landing System", "Microwave Landing System", "Multi-frequency Landing System"], correctOptionIndex: 1 },
  { id: 285, text: "MLS offers how many channels?", options: ["40", "200", "720"], correctOptionIndex: 1 },
  { id: 286, text: "MLS operates in what frequency range?", options: ["118-136 MHz", "5,031 to 5,091 MHz", "960-1215 MHz"], correctOptionIndex: 1 },
  { id: 287, text: "The azimuth coverage extends laterally at least how many degrees on either side?", options: ["20°", "40°", "90°"], correctOptionIndex: 1 },
  { id: 288, text: "The DME/P used with MLS stands for what?", options: ["DME Precision", "DME Precision", "DME Primary"], correctOptionIndex: 1 },
  { id: 289, text: "DME provides what type of distance readout?", options: ["Horizontal distance", "Slant range distance", "Great circle distance"], correctOptionIndex: 1 },
  { id: 290, text: "The onboard interrogator sends pulses to the ground station. What does the ground station do?", options: ["Transmits continuously", "Replies to the interrogation", "Ignores the signal"], correctOptionIndex: 1 },
  { id: 291, text: "The interrogator determines distance from the time difference between what?", options: ["Transmission and GPS signal", "Interrogation and reply", "Two replies"], correctOptionIndex: 1 },
  { id: 292, text: "The internal delay of the DME ground station is what?", options: ["25 μs", "50 μs", "100 μs"], correctOptionIndex: 1 },
  { id: 293, text: "RNAV stands for what?", options: ["Radio Navigation", "Area Navigation", "Radar Navigation"], correctOptionIndex: 1 },
  { id: 294, text: "RNAV allows aircraft to follow what type of flight paths?", options: ["Only ground-based navaid routes", "Precise flight paths and optimize routes", "Only straight lines"], correctOptionIndex: 1 },
  { id: 295, text: "Basic RNAV uses what as its basic signal inputs?", options: ["GPS only", "VOR bearing, DME slant ranging, and barometric altitude", "INS only"], correctOptionIndex: 1 },
  { id: 296, text: "FMS stands for what?", options: ["Flight Monitoring System", "Flight Management System", "Frequency Management System"], correctOptionIndex: 1 },
  { id: 297, text: "The FMS can be thought of as the what of the aircraft navigation system?", options: ["Muscles", "Brain", "Eyes"], correctOptionIndex: 1 },
  { id: 298, text: "The FMS shows flight plan information on what?", options: ["PFD only", "Control Display Unit (CDU)", "MCP"], correctOptionIndex: 1 },
  { id: 299, text: "CDU stands for what?", options: ["Control Display Unit", "Control Display Unit", "Central Display Unit"], correctOptionIndex: 1 },
  { id: 300, text: "The FMS gives steering and thrust commands to what?", options: ["Flight controls directly", "Auto Flight System (AFS)", "Throttles only"], correctOptionIndex: 1 },
  { id: 301, text: "Flight plan and navaid data must be updated how often?", options: ["Every 14 days", "Every 28 days", "Every 56 days"], correctOptionIndex: 1 },
  { id: 302, text: "SID stands for what?", options: ["Standard Instrument Departure", "Standard Instrument Departure", "Standard Initial Departure"], correctOptionIndex: 1 },
  { id: 303, text: "STAR stands for what?", options: ["Standard Terminal Arrival Route", "Standard Terminal Arrival Route", "Standard Track Arrival Route"], correctOptionIndex: 1 },
  { id: 304, text: "ICAO refers to satellite navigation systems as what?", options: ["GPS", "Global Navigation Satellite Systems (GNSS)", "SatNav"], correctOptionIndex: 1 },
  { id: 305, text: "GPS typically provides position accuracy within what range?", options: ["1-2 meters", "5-10 meters", "50-100 meters"], correctOptionIndex: 1 },
  { id: 306, text: "Galileo improves accuracy to what range?", options: ["5-10 meters", "1 meter or less", "10-20 meters"], correctOptionIndex: 1 },
  { id: 307, text: "GPS uses how many satellites in orbit at any one time?", options: ["18", "24", "30"], correctOptionIndex: 1 },
  { id: 308, text: "GPS satellites orbit at what altitude?", options: ["10,000 km", "20,200 km", "35,000 km"], correctOptionIndex: 1 },
  { id: 309, text: "A minimum of how many satellite receptions will provide present position and altitude?", options: ["3", "4", "5"], correctOptionIndex: 1 },
  { id: 310, text: "The ATC transponder is interrogated by what?", options: ["GPS satellites", "Radar pulses from ground station", "Other aircraft"], correctOptionIndex: 1 },
  { id: 311, text: "The transponder automatically replies with what?", options: ["Voice message", "A series of pulses", "Continuous wave"], correctOptionIndex: 1 },
  { id: 312, text: "Mode A interrogation pulses are spaced how many microseconds apart?", options: ["21 microseconds", "8 microseconds", "15 microseconds"], correctOptionIndex: 1 },
  { id: 313, text: "Mode C interrogation pulses are spaced how many microseconds apart?", options: ["8 microseconds", "21 microseconds", "30 microseconds"], correctOptionIndex: 1 },
  { id: 314, text: "Mode A provides what information?", options: ["Altitude", "Basic ATC identity (squawk code)", "Speed"], correctOptionIndex: 1 },
  { id: 315, text: "Mode C provides what information?", options: ["Identification", "Pressure altitude", "Heading"], correctOptionIndex: 1 },
  { id: 316, text: "Squawk codes are four-digit what type of numbers?", options: ["Decimal", "Octal (digits 0-7)", "Hexadecimal"], correctOptionIndex: 1 },
  { id: 317, text: "Mode S provides what additional capabilities?", options: ["Only altitude", "Selected altitude, roll angle, ground speed, magnetic heading, IAS, Mach number, vertical rate", "Only identification"], correctOptionIndex: 1 },
  { id: 318, text: "Mode S transmits a 24-bit address consisting of what?", options: ["Random code", "Nationality code and identification number", "Aircraft type code"], correctOptionIndex: 1 },
  { id: 319, text: "The generic term for collision avoidance systems is what?", options: ["TCAS", "ACAS (Airborne Collision Avoidance System)", "CAS"], correctOptionIndex: 1 },
  { id: 320, text: "TCAS operates on what frequencies?", options: ["118 MHz and 136 MHz", "1030 MHz (interrogation) and 1090 MHz (reply)", "960 MHz and 1215 MHz"], correctOptionIndex: 1 },
  { id: 321, text: "ACAS I gives approximately how many seconds warning of possible collision?", options: ["20 seconds", "40 seconds", "60 seconds"], correctOptionIndex: 1 },
  { id: 322, text: "A non-threat traffic symbol on TCAS display is what?", options: ["Solid yellow circle", "Open white (or blue) diamond", "Red square"], correctOptionIndex: 1 },
  { id: 323, text: "A proximate traffic symbol (within safe zone but not a threat) is what?", options: ["Open diamond", "Solid diamond", "Yellow circle"], correctOptionIndex: 1 },
  { id: 324, text: "A traffic advisory (potential threat) symbol is what?", options: ["Red square", "Solid yellow circle", "White diamond"], correctOptionIndex: 1 },
  { id: 325, text: "A resolution advisory (collision threat) symbol is what?", options: ["Yellow circle", "Red square", "White diamond"], correctOptionIndex: 1 },
  { id: 326, text: "The aural \"Traffic Traffic\" is associated with what?", options: ["Resolution Advisory", "Traffic Advisory", "Proximate traffic"], correctOptionIndex: 1 },
  { id: 327, text: "WXR stands for what?", options: ["Weather X-Ray Radar", "Weather Radar", "Wave Xmission Radar"], correctOptionIndex: 1 },
  { id: 328, text: "Weather radar operates at what frequency?", options: ["1 GHz", "9.4 GHz (microwaves)", "100 MHz"], correctOptionIndex: 1 },
  { id: 329, text: "The WXR antenna scans side to side approximately how many times per minute?", options: ["10 times", "20 times", "60 times"], correctOptionIndex: 1 },
  { id: 330, text: "Water droplet density is displayed in which colours?", options: ["Blue, white, grey", "Green, yellow, red (magenta for turbulence)", "Orange, purple, brown"], correctOptionIndex: 1 },
  { id: 331, text: "The pilot can set the WXR antenna to tilt up or down. When tilted down 15°, what will it indicate?", options: ["High altitude clouds", "Ground features such as coastlines", "Upper winds"], correctOptionIndex: 1 },
  { id: 332, text: "The WXR is automatically stabilised using pitch and roll information from where?", options: ["Air data computer", "Inertial reference unit", "GPS"], correctOptionIndex: 1 },
  { id: 333, text: "Radio altimeter determines height above what?", options: ["Sea level", "Terrain", "Standard datum"], correctOptionIndex: 1 },
  { id: 334, text: "Radio altimeter operates at what frequency?", options: ["9.4 GHz", "4.3 GHz", "75 MHz"], correctOptionIndex: 1 },
  { id: 335, text: "Maximum height for typical radio altimeter is what?", options: ["500 feet", "2,500 feet", "10,000 feet"], correctOptionIndex: 1 },
  { id: 336, text: "The principle of radio altimeter is based on what?", options: ["Pressure measurement", "Time between transmission and reception of reflected signal", "Phase comparison"], correctOptionIndex: 1 },
  { id: 337, text: "The transmitter sends a signal that changes from 4,250 MHz to 4,350 MHz and back how many times per second?", options: ["50 times", "100 times", "200 times"], correctOptionIndex: 1 },
  { id: 338, text: "Radio altimeter requires how many antennas?", options: ["One", "Two (mounted on bottom of fuselage)", "Four"], correctOptionIndex: 1 },
  { id: 339, text: "The DH light illuminates when aircraft height is what?", options: ["Above selected decision height", "Equal to or lower than selected decision height", "At sea level"], correctOptionIndex: 1 },
  { id: 340, text: "Below what height does the rising runway appear on PFD?", options: ["500 feet", "200 feet", "100 feet"], correctOptionIndex: 1 },
  { id: 341, text: "INS stands for what?", options: ["Inertial Navigation System", "Inertial Navigation System", "Integrated Navigation System"], correctOptionIndex: 1 },
  { id: 342, text: "Newton's first law of motion states what?", options: ["Force equals mass times acceleration", "A body continues in a state of rest or uniform motion unless acted upon by external force", "For every action there is equal opposite reaction"], correctOptionIndex: 1 },
  { id: 343, text: "Newton's second law of motion states what?", options: ["A body continues in state of rest", "Acceleration is proportional to sum of forces acting on body", "For every action there is equal opposite reaction"], correctOptionIndex: 1 },
  { id: 344, text: "Newton's third law of motion states what?", options: ["Acceleration equals force/mass", "For every action there is equal and opposite reaction", "Bodies in motion stay in motion"], correctOptionIndex: 1 },
  { id: 345, text: "The basic measuring instrument of INS is what?", options: ["Gyroscope", "Accelerometer", "Altimeter"], correctOptionIndex: 1 },
  { id: 346, text: "How many accelerometers are mounted in an INS?", options: ["One", "Two (north-south and east-west)", "Three"], correctOptionIndex: 1 },
  { id: 347, text: "The accelerometer is basically what type of device?", options: ["Rotary", "Pendulous device", "Thermal"], correctOptionIndex: 1 },
  { id: 348, text: "Integration of acceleration gives what?", options: ["Distance only", "Velocity, then distance", "Speed only"], correctOptionIndex: 1 },
  { id: 349, text: "The platform in INS has which three axes?", options: ["Pitch, roll, yaw", "X (north-south), Y (east-west), Z (up-down)", "Longitudinal, lateral, vertical"], correctOptionIndex: 1 },
  { id: 350, text: "What keeps the accelerometers level in a gimballed system?", options: ["Springs", "Gyroscopes", "Motors"], correctOptionIndex: 1 },
  { id: 351, text: "When IRS is switched on, alignment takes how long?", options: ["2 minutes", "10 minutes", "30 minutes"], correctOptionIndex: 1 },
  { id: 352, text: "When aircraft power fails, IRU switches to battery power for how long maximum?", options: ["10 minutes", "30 minutes", "60 minutes"], correctOptionIndex: 1 },
  { id: 353, text: "In a strapdown inertial reference system, gyros and accelerometers are mounted how?", options: ["On a gimballed platform", "Solidly to the system chassis, which is solidly to aircraft", "On separate platforms"], correctOptionIndex: 1 },
  { id: 354, text: "How many accelerometers and gyros are needed in a strapdown system?", options: ["Two of each", "Three of each", "Four of each"], correctOptionIndex: 1 },
  { id: 355, text: "A strapdown system is generally called what?", options: ["INS", "Inertial Reference System (IRS)", "ADIRS"], correctOptionIndex: 1 },
  { id: 356, text: "IRS integrated with ADC is known as what?", options: ["INS", "Air Data Inertial Reference System (ADIRS)", "GPS/IRS"], correctOptionIndex: 1 },
  { id: 357, text: "Laser gyro measures what?", options: ["Linear acceleration", "Angular rate of rotation about a single axis", "Temperature"], correctOptionIndex: 1 },
  { id: 358, text: "Laser gyro is made of what material?", options: ["Metal", "Triangular block of temperature-stable glass", "Plastic"], correctOptionIndex: 1 },
  { id: 359, text: "What gas is inserted into the laser gyro?", options: ["Neon only", "Helium-neon", "Argon"], correctOptionIndex: 1 },
  { id: 360, text: "How many beams of light are generated in a laser gyro?", options: ["One", "Two, travelling in opposite directions", "Three"], correctOptionIndex: 1 },
  { id: 361, text: "When the laser gyro rotates, what happens to the beams?", options: ["They stop", "They change wavelength very slightly", "They merge"], correctOptionIndex: 1 },
  { id: 362, text: "No radio installation is better than its what?", options: ["Transmitter", "Antenna", "Receiver"], correctOptionIndex: 1 },
  { id: 363, text: "Antennas mounted on the exterior are either what type?", options: ["Fixed only", "Blade (rigid) or whip (flexible)", "Dish only"], correctOptionIndex: 1 },
  { id: 364, text: "VHF communication antenna is used for what?", options: ["Navigation", "Communication within range up to about 300 NM", "Weather detection"], correctOptionIndex: 1 },
  { id: 365, text: "DME antenna is used for what?", options: ["Communication", "Detecting distance to ground stations", "Traffic alert"], correctOptionIndex: 1 },
  { id: 366, text: "ADF antenna is used for what?", options: ["Satellite communication", "Navigation for short and medium range", "Weather radar"], correctOptionIndex: 1 },
  { id: 367, text: "A pitot/static leak test set consists of what two reservoirs?", options: ["Pressure and temperature", "Vacuum reservoir and pressure reservoir", "Hydraulic and pneumatic"], correctOptionIndex: 1 },
  { id: 368, text: "The test set contains calibrated what?", options: ["Only altimeter", "Altimeter, airspeed indicator, and vertical speed indicator", "Only airspeed indicator"], correctOptionIndex: 1 },
  { id: 369, text: "Pitot and static port adapters are generally what?", options: ["Universal", "Aircraft type-specific", "Manufacturer-specific only"], correctOptionIndex: 1 },
  { id: 370, text: "A pitot/static test set can also test what other systems?", options: ["Only altimeters", "Engine pressure ratio (EPR) systems and manifold pressure gauges", "Only airspeed indicators"], correctOptionIndex: 1 },
  { id: 371, text: "Modern pitot static test sets are fully compliant with what requirements?", options: ["VFR only", "RVSM requirements", "IFR only"], correctOptionIndex: 1 },
  { id: 372, text: "Bryans leak test set comprises what three elements?", options: ["Pump, gauge, hose", "Control valve, indicator, hand pump", "Motor, reservoir, display"], correctOptionIndex: 1 },
  { id: 373, text: "The hand pump is what type?", options: ["Single-acting", "Double-acting to provide both pressure and suction", "Rotary"], correctOptionIndex: 1 },
  { id: 374, text: "The indicator is a modified what?", options: ["Altimeter", "Airspeed indicator", "Pressure gauge"], correctOptionIndex: 1 },
  { id: 375, text: "Barfield 1811 G model uses what type of pumps?", options: ["Electric pumps only", "Hand-operated pumps", "Engine-driven pumps"], correctOptionIndex: 1 },
  { id: 376, text: "Barfield 1811 H model uses what type of pumps?", options: ["Hand-operated only", "Electrically operated pumps", "Pneumatic pumps"], correctOptionIndex: 1 },
  { id: 377, text: "The test set is equipped with what?", options: ["Digital readouts only", "Reference master instruments with calibration cards", "Only pressure gauges"], correctOptionIndex: 1 },
  { id: 378, text: "How many metering valves control pneumatic functions?", options: ["Three", "Six", "Nine"], correctOptionIndex: 1 },
  { id: 379, text: "A deadweight tester is a calibration standard method that uses what?", options: ["Electronic sensors", "Piston-cylinder with weights to create equilibrium with pressure", "Spring mechanism"], correctOptionIndex: 1 },
  { id: 380, text: "Deadweight testers are known as what type of standards?", options: ["Secondary standards", "Primary standards", "Working standards"], correctOptionIndex: 1 },
  { id: 381, text: "Pressure measured by deadweight tester is defined through what quantities?", options: ["Pressure and temperature", "Length, mass, and time", "Force and area"], correctOptionIndex: 1 },
  { id: 382, text: "Deadweight testers can attain accuracy of between what values?", options: ["1% and 5%", "0.005% and 0.1%", "0.5% and 1%"], correctOptionIndex: 1 },
  { id: 383, text: "During measurement, the piston should be rotated to do what?", options: ["Increase pressure", "Minimise friction", "Reduce weight"], correctOptionIndex: 1 },
  { id: 384, text: "IFR NAV-402 ramp test set is designed to test what systems?", options: ["Only communication", "Category I and II ILS, COMM, NAV, and marker systems", "Only navigation"], correctOptionIndex: 1 },
  { id: 385, text: "The NAV-402 has a six-digit counter that indicates what?", options: ["Only frequency", "RF of signal generator, COM transmitter frequency, external signal, or VOR bearing", "Only VOR bearing"], correctOptionIndex: 1 },
  { id: 386, text: "The built-in RF power meter measures COM transmitter power from what range?", options: ["0-1 W or 0-10 W", "0-10 W or 0-100 W", "0-50 W only"], correctOptionIndex: 1 },
  { id: 387, text: "The moving-iron meter operates on what principle?", options: ["Electromagnetic induction", "Magnetic repulsion between like poles", "Thermal expansion"], correctOptionIndex: 1 },
  { id: 388, text: "In a moving-iron meter, the current flows through what?", options: ["Permanent magnet", "A coil, producing a magnetic field", "The pointer"], correctOptionIndex: 1 },
  { id: 389, text: "Moving-iron meters may be used on what type of current?", options: ["DC only", "AC or DC", "AC only"], correctOptionIndex: 1 },
  { id: 390, text: "A disadvantage of moving-iron meters is what?", options: ["Low power requirement", "High reluctance requires more power, reducing sensitivity", "High sensitivity"], correctOptionIndex: 1 },
  { id: 391, text: "The D'Arsonval meter is what type of meter movement?", options: ["Moving iron", "Moving coil", "Electrodynamic"], correctOptionIndex: 1 },
  { id: 392, text: "In a D'Arsonval meter, what creates the reference magnetic field?", options: ["Electromagnet", "Horseshoe-shaped permanent magnet", "Coil"], correctOptionIndex: 1 },
  { id: 393, text: "Current enters and leaves the coil through what?", options: ["Brushes", "Calibrated hairsprings", "Direct connections"], correctOptionIndex: 1 },
  { id: 394, text: "The moving coil meter cannot be used on AC because of what?", options: ["High frequency", "Polarity sensitivity", "Low current"], correctOptionIndex: 1 },
  { id: 395, text: "The three forces in a meter movement are what?", options: ["Magnetic, electrical, mechanical", "Deflecting force, controlling force, damping force", "Push, pull, twist"], correctOptionIndex: 1 },
  { id: 396, text: "Damping in a moving coil meter is achieved how?", options: ["By mechanical friction", "By eddy currents in aluminium bobbin", "By air damping"], correctOptionIndex: 1 },
  { id: 397, text: "The clamp meter is what type of meter?", options: ["Moving iron", "Transformer/rectifier type", "Electrostatic"], correctOptionIndex: 1 },
  { id: 398, text: "The clamp meter enables current measurement how?", options: ["By connecting in series", "By enclosing the conductor in the clamp", "By touching probes to the conductor"], correctOptionIndex: 1 },
  { id: 399, text: "The cable circled by the core constitutes what?", options: ["Secondary winding", "Primary winding of the transformer", "Shunt"], correctOptionIndex: 1 },
  { id: 400, text: "DMM stands for what?", options: ["Digital Meter Multimeter", "Digital Multimeter", "Dual Mode Meter"], correctOptionIndex: 1 },
  { id: 401, text: "Digital multimeters display results in what form?", options: ["Analogue scale", "Mathematical digits on LCD or LED", "Bar graph"], correctOptionIndex: 1 },
  { id: 402, text: "The critical process in a DMM for any measurement is what?", options: ["Current measurement", "Voltage measurement", "Resistance measurement"], correctOptionIndex: 1 },
  { id: 403, text: "SAR in DMMs stands for what?", options: ["Sample And Register", "Successive Approximation Register", "Sequential Analog Reader"], correctOptionIndex: 1 },
  { id: 404, text: "Typical resolution levels of DMMs are how many bits?", options: ["8 bits", "16 bits", "32 bits"], correctOptionIndex: 1 },
  { id: 405, text: "Flash AD converter uses what components?", options: ["Inductors and capacitors", "Comparators, encoders, and digital display", "Resistors only"], correctOptionIndex: 1 },
  { id: 406, text: "A digital ammeter uses what to produce calibrated voltage?", options: ["Series resistor", "Shunt resistor", "Transformer"], correctOptionIndex: 1 },
  { id: 407, text: "A digital ohmmeter uses a resistance network comprising what?", options: ["Only known resistance", "Known resistance and unknown resistance", "Only unknown resistance"], correctOptionIndex: 1 },
  { id: 408, text: "Before carrying out tests, what should be examined for signs of damage?", options: ["Only visible wiring", "All aircraft circuits, plugs, sockets, terminal blocks, equipment terminals", "Only power sources"], correctOptionIndex: 1 },
  { id: 409, text: "The primary purpose of inspection is to determine what?", options: ["Circuit voltage", "Physical state of wiring system", "Current capacity"], correctOptionIndex: 1 },
  { id: 410, text: "All circuit testing should be carried out in what sequence?", options: ["Functional, continuity, insulation, bonding", "Visual inspection, bonding, continuity, insulation, functional", "Insulation, continuity, bonding, functional"], correctOptionIndex: 1 },
  { id: 411, text: "Bonding is the electrical interconnection of what?", options: ["Only electronic equipment", "All metal parts of an aircraft", "Only the engine"], correctOptionIndex: 1 },
  { id: 412, text: "Bonding gives a low resistance path for what?", options: ["Only lightning", "Earth return circuits", "Only static discharge"], correctOptionIndex: 1 },
  { id: 413, text: "Bonding reduces radio interference by preventing what?", options: ["High current", "Difference of potential between metal surfaces causing sparks", "High voltage"], correctOptionIndex: 1 },
  { id: 414, text: "Primary conductors are required to carry what?", options: ["Normal operating currents", "Lightning strike currents", "Radio frequencies"], correctOptionIndex: 1 },
  { id: 415, text: "Primary copper conductors should have cross-sectional area not less than what?", options: ["1 mm²", "3 mm² (6 mm² for isolated section)", "10 mm²"], correctOptionIndex: 1 },
  { id: 416, text: "Secondary copper conductors should have cross-sectional area not less than what?", options: ["0.5 mm²", "1 mm²", "2 mm²"], correctOptionIndex: 1 },
  { id: 417, text: "An electrical contact with resistance less than what is considered satisfactory?", options: ["0.5 ohm", "0.05 ohm", "0.005 ohm"], correctOptionIndex: 1 },
  { id: 418, text: "Braided copper or aluminium cords are known as what?", options: ["Ground wires", "Bonding jumpers", "Shunts"], correctOptionIndex: 1 },
  { id: 419, text: "Intermittent contact is considered what?", options: ["Acceptable", "Worse than no contact at all", "Better than continuous contact"], correctOptionIndex: 1 },
  { id: 420, text: "Bonding jumpers for control surfaces should be what?", options: ["Rigid and short", "As flexible and as short as possible, not tinned", "Long and coiled"], correctOptionIndex: 1 },
  { id: 421, text: "The bond test meter consists of what?", options: ["Battery and voltmeter", "Single nickel alkaline cell and low reading ohmmeter", "Power supply and ammeter"], correctOptionIndex: 1 },
  { id: 422, text: "One lead is how long and what type?", options: ["6 ft with single prod", "18.3 m (60 ft) with single prod", "10 m with double prod"], correctOptionIndex: 1 },
  { id: 423, text: "The other lead is how long and what type?", options: ["60 ft with single prod", "1.82 m (6 ft) with double prod", "3 m with single prod"], correctOptionIndex: 1 },
  { id: 424, text: "On all-metal aircraft, bond resistance should not exceed what?", options: ["0.5 Ω", "0.05 Ω", "0.005 Ω"], correctOptionIndex: 1 },
  { id: 425, text: "BT51 Low Resistance Ohmmeter makes measurements by doing what?", options: ["Measuring voltage only", "Passing current through conductor and monitoring voltage across it", "Measuring resistance directly"], correctOptionIndex: 1 },
  { id: 426, text: "The BT51 test current is maintained at what nominal value?", options: ["1 A", "2 A", "5 A"], correctOptionIndex: 1 },
  { id: 427, text: "The BT51 has resolution of what?", options: ["0.1 mΩ", "0.01 mΩ", "1 mΩ"], correctOptionIndex: 1 },
  { id: 428, text: "A continuity tester typically consists of what?", options: ["High voltage source", "Low-voltage battery (2-5 V) and test lamp or low reading voltmeter", "Megger"], correctOptionIndex: 1 },
  { id: 429, text: "Current in test lamp circuits should be limited to what to prevent damage?", options: ["50 mA", "120 mA", "500 mA"], correctOptionIndex: 1 },
  { id: 430, text: "Before testing, what should be done with main electrical supply?", options: ["Left on", "Switched off or disconnected", "Increased"], correctOptionIndex: 1 },
  { id: 431, text: "An approximate guide for millivolt drop test is what?", options: ["1 mV / 10 A", "5 mV / 10 A flowing", "10 mV / 1 A"], correctOptionIndex: 1 },
  { id: 432, text: "Insulation resistance is measured in what units?", options: ["Volts", "Ohms", "Amps"], correctOptionIndex: 1 },
  { id: 433, text: "Test sets consist of what type of indicator?", options: ["Moving coil", "Ratiometer type indicator", "Digital"], correctOptionIndex: 1 },
  { id: 434, text: "General-purpose insulation test set generator output voltage is either what?", options: ["50 V, 100 V, or 250 V", "250 V, 500 V, or 1,000 V", "1,000 V only"], correctOptionIndex: 1 },
  { id: 435, text: "In common parlance, insulation testers are referred to as what?", options: ["Ohm meters", "Meggers", "Hi-pot testers"], correctOptionIndex: 1 },
  { id: 436, text: "With a perfect insulator (infinite resistance), what happens?", options: ["Deflecting coil has maximum current", "No current through deflecting coil, pointer at infinity", "Both coils have equal current"], correctOptionIndex: 1 },
  { id: 437, text: "With a bad insulator (zero resistance), what happens?", options: ["Pointer at infinity", "Maximum deflecting torque, pointer towards zero", "No deflection"], correctOptionIndex: 1 },
  { id: 438, text: "The 250 V test set has a constant voltage feature achieved by what?", options: ["Voltage regulator", "Silicon carbide voltage limiting device", "Zener diode"], correctOptionIndex: 1 },
  { id: 439, text: "Battery operated Meggers are available in what voltage versions?", options: ["100 V, 250 V only", "50 V, 250 V, 500 V DC", "1,000 V only"], correctOptionIndex: 1 },
  { id: 440, text: "Before conducting tests, what precautions should be taken?", options: ["Only equipment precautions", "All precautions for aircraft and personnel safety", "Only personnel precautions"], correctOptionIndex: 1 },
  { id: 441, text: "Whenever possible, functioning tests should use what power source?", options: ["Aircraft batteries", "External supply coupled to ground supply connector", "Engine-driven generators"], correctOptionIndex: 1 },
  { id: 442, text: "Tests must ensure proper functioning of what?", options: ["Only individual circuits", "Individual and integrated sections of circuits", "Only integrated sections"], correctOptionIndex: 1 },
  { id: 443, text: "After normal functioning test, what should be done to check isolation?", options: ["Leave circuit on", "Remove fuse or trip circuit breaker and switch circuit on again", "Disconnect battery"], correctOptionIndex: 1 },
  { id: 444, text: "When circuit operation depends on inherent resistance value, what should be used?", options: ["Standard multimeter", "Low reading ohm-meter (like bonding tester)", "Megger"], correctOptionIndex: 1 },
];
