export const combustionTurbineExhaustLubricationQuestions = [
  {
    id: 1,
    text: "What is the primary purpose of the combustion section in a gas-turbine engine?",
    options: ["To compress incoming air to a higher pressure", "To add heat energy to flowing gases, causing expansion and acceleration into the turbine section", "To reduce the velocity of gases before they enter the atmosphere"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "Approximately what percentage of compressor airflow is used as primary air for the combustion process?",
    options: ["70-80%", "20-30%", "50-50%"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "Why are diffusers used at the front of the combustor (the snout)?",
    options: ["To increase air velocity for better fuel mixing", "To reduce air velocity for correct and stable combustion", "To increase the pressure of the fuel before injection"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "What is the ideal air-to-fuel ratio for complete combustion of a kerosene-air mixture mentioned in the text?",
    options: ["5:1", "15:1", "25:1"],
    correctOptionIndex: 1,
  },
  {
    id: 5,
    text: "What is the function of the toroidal vortex in the primary zone?",
    options: ["To increase the air velocity for faster combustion", "To stabilise and anchor the flame, preventing it from moving away from the fuel nozzle area", "To cool the flame tube walls directly"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "According to the document, what happens to the pressure during the combustion process in an ideal gas turbine engine?",
    options: ["It increases significantly", "It remains almost constant", "It decreases to zero"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "Which gas law explains that if gas is held at constant pressure, its volume is directly proportional to its absolute temperature?",
    options: ["Boyle's Law", "Charles's Law", "The Combined Gas Law"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "What is the typical pressure loss range as gas passes through the swirls and restrictor in the combustion chamber?",
    options: ["1-2%", "3-8%", "10-15%"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "What happens to the velocity of gas flow at the very end of the combustion chamber due to its convergent shape?",
    options: ["It continues to decrease", "It increases", "It remains constant"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "The incoming air velocity from the compressor is approximately 115 m/sec. What velocity does the diffuser aim to achieve?",
    options: ["2-15 m/sec", "50 m/sec", "25 m/sec"],
    correctOptionIndex: 2,
  },
  {
    id: 11,
    text: "What is the purpose of the secondary airflow (70-80%) in the combustion chamber?",
    options: ["To increase the flame temperature", "Mainly for cooling the combustion chamber and mixing in the dilution zone", "To provide additional oxygen for primary combustion"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "What material are combustion chambers typically made of, often referred to by the trading name 'Inconel'?",
    options: ["Stainless steel and iron alloys", "Nickel and titanium-based alloys", "Aluminum and copper alloys"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "What is the purpose of the whitish coating called magnesium zirconate applied to some combustion liners?",
    options: ["To increase the strength of the liner", "To help combat carbon deposits by wearing away and taking carbon with it", "To improve fuel atomization"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "What is transpiration cooling as described in the text?",
    options: ["Using ceramic-coated tiles fixed to the interior walls", "A film of air flowing between laminations in the flame tube wall to form an insulating film", "Injecting fuel directly onto the flame tube walls"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "Why are nickel-based alloys generally used for combustion liners today?",
    options: ["They are cheaper than stainless steel", "They are non-corrosive and can be worked in thin, weldable sheets", "They have a higher iron content for better strength"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "On which type of compressor are multiple-can combustors typically found?",
    options: ["Axial compressors", "Centrifugal compressors", "Mixed-flow compressors"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "What is a key advantage of the multiple-can combustor design?",
    options: ["Very low weight and space requirements", "Good structural strength and individual replacement of cans", "No complex compressor ducting is needed"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "How does the can-annular combustion chamber differ from the multiple-can design?",
    options: ["It has individual air casings for each flame tube", "It has a common outer and inner casing for all flame tubes", "It uses reverse flow exclusively"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "Which engine is mentioned as an example that uses a can-annular combustor (PW JT8D)?",
    options: ["Rolls Royce Dart", "PW PT6", "MD80 powered by PW JT8D"],
    correctOptionIndex: 2,
  },
  {
    id: 20,
    text: "What is a major advantage of the modern annular combustion chamber compared to can-annular types?",
    options: ["It is 75% shorter", "It is easier to remove for maintenance", "It has better structural strength"],
    correctOptionIndex: 0,
  },
  {
    id: 21,
    text: "In the Rolls-Royce T700 annular combustion chamber, where are the fuel spray nozzles installed?",
    options: ["Through bosses in the compressor casing", "Through 24 openings in the combustion outer case", "Through the inner liner directly"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "In the reverse flow combustion chamber (e.g., PW PT6), what happens to the expanding gases after combustion?",
    options: ["They flow directly rearward to the exhaust", "They are turned 180° inward to flow forward through the compressor turbine", "They are vented overboard for cooling"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "In the PT6 combustion section, approximately how much of the total airflow is used as a cooling air blanket?",
    options: ["25%", "50%", "75%"],
    correctOptionIndex: 2,
  },
  {
    id: 24,
    text: "What is a disadvantage of the annular combustion chamber?",
    options: ["Poor thermal load distribution for the turbine", "Difficult and time-consuming removal, though compensated by high service life", "Large and heavy design"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "Which of the following is NOT listed as a main pollutant in exhaust gas from gas turbine engines?",
    options: ["Hydrocarbons (HC)", "Sulfur dioxide (SO2)", "Nitrogen oxides (NOx)"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "What is the consequence of a 'rich mixture' (too much fuel) in the combustion chamber?",
    options: ["Lower carbon monoxide emissions", "Some fuel cannot be burned, leading to unburned fuel and carbon monoxide in the exhaust", "The flame will certainly blow out"],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "What effect does a low combustion temperature have on emissions?",
    options: ["It decreases nitrogen oxides but significantly increases carbon monoxide emissions", "It decreases both carbon monoxide and nitrogen oxides", "It has no effect on emissions"],
    correctOptionIndex: 0,
  },
  {
    id: 28,
    text: "What does DAC stand for in relation to combustion chambers (e.g., CFM56-7B)?",
    options: ["Direct Air Capture", "Dual Annular Combustion", "Digital Actuation Control"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "How does a Dual Annular Combustion (DAC) chamber reduce nitrogen oxide (NOx) emissions?",
    options: ["By increasing the combustion temperature", "By being much shorter, reducing the time exhaust gas spends in the hot area", "By using a single, larger combustion zone"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "In a DAC chamber, which stage operates only during high-power conditions?",
    options: ["The pilot stage", "The main stage", "The cooling stage"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "How many fuel nozzles total are used in the CFM56-7B (DAC) combustion chamber?",
    options: ["20", "40", "10"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "The combustion case in the CFM56-7B transmits the engine's __________ loads.",
    options: ["Axial", "Radial", "Torsional"],
    correctOptionIndex: 0,
  },
  {
    id: 33,
    text: "The combustion chamber in the CFM56-7B is coated with what type of material?",
    options: ["Magnesium zirconate", "A thermal barrier material", "A ceramic tile only"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "The combustion chamber in the CFM56-7B is made of a nickel-chrome alloy and is described as a __________ structure.",
    options: ["Long can-annular", "Short annular", "Reverse flow annular"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "What components are incorporated into the combustion case of the CFM56-7B?",
    options: ["Only the fuel nozzles", "Compressor outlet guide vanes and a diffuser", "The turbine blades"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "When can the ignition system normally be switched off during engine operation?",
    options: ["As soon as the starter motor begins to turn", "As soon as the engine has attained self-sustaining speed", "Only after the aircraft has taken off"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "What is a 'flameout' as described in the text?",
    options: ["The intentional shutdown of the engine", "The extinction of the flame due to unusual occurrences like ingesting large amounts of water", "The moment the afterburner is lit"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "As air mass flow increases, what happens to the range between the rich and weak combustion limits?",
    options: ["It widens", "It remains the same", "It is reduced (narrower limits)"],
    correctOptionIndex: 2,
  },
  {
    id: 39,
    text: "According to the stability limits, what is generally more difficult?",
    options: ["Sustaining combustion once it has started", "Starting the combustion initially", "Cooling the combustion chamber"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "Combustion stability means smooth burning and the ability to remain alight over a wide range of __________.",
    options: ["Fuel temperatures only", "Air/fuel ratios and air mass flow", "Compressor speeds only"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "What is the primary application of a radial turbine in gas turbine engines?",
    options: ["Main propulsion of large turbofan engines", "Auxiliary power units (APUs) and small gas turbine engines", "High-pressure compressor drive in all engines"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "What is a major disadvantage of the radial inflow turbine compared to an axial flow turbine?",
    options: ["It extracts less than 50% of kinetic energy", "High centrifugal loads on the disk lead to short service life under high temperature", "It cannot be manufactured as a single stage"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "Why do modern high-bypass-ratio engines allow a smaller turbine diameter for a given thrust?",
    options: ["They use radial turbines instead of axial turbines", "Their much greater propulsive efficiency breaks the vicious circle of stress vs. speed", "They operate at lower rotational speeds"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "What happens to gas flow when it passes through the turbine nozzle guide vanes?",
    options: ["It is decelerated and static pressure increases", "It is accelerated and static pressure decreases", "It remains at constant velocity and pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "How does increasing the number of turbine stages affect turbine diameter and power output?",
    options: ["Increases diameter and decreases power", "Decreases diameter and increases power output", "Has no effect on diameter but reduces power"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "What identifies an impulse turbine blade when comparing inlet and outlet areas between two rotor blades?",
    options: ["Outlet area is larger than inlet area", "Inlet area and outlet area are the same size", "Inlet area is larger than outlet area"],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "Where are impulse-type turbine blades commonly used today according to the document?",
    options: ["Main high-pressure turbine stages", "Air starter motors", "Low-pressure turbine final stages"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "In a pure reaction turbine, how do the nozzle guide vanes affect the gas flow?",
    options: ["They accelerate the gas toward the rotor blades", "They divert the gas flow direction without altering gas pressure", "They convert all kinetic energy into pressure energy"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "Which law of motion is the force acting on a reaction turbine blade based on?",
    options: ["Newton's second law (F = ma)", "Newton's third law (action and reaction)", "Newton's first law (inertia)"],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "Why do impulse/reaction turbine blades have a twist from base to tip?",
    options: ["To reduce manufacturing cost", "To ensure gas flow does equal work along the blade length and provides uniform axial velocity", "To increase the impulse effect at the tip only"],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "During expansion in the turbine, what happens to pressure, temperature, and volume of the gas?",
    options: ["Pressure and temperature increase, volume decreases", "Pressure and temperature decrease, volume increases", "Pressure increases, temperature and volume decrease"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "Which turbine blade fixing method is most commonly used on modern engines?",
    options: ["De Laval bulb root", "Fir-tree fixing", "BMW hollow blade root"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "In the CFM56-7B example, what keeps the HPT turbine blade in place after assembly?",
    options: ["Lock wire and rivets", "A blade retainer", "Welding at the root"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "Why is the fir-tree serration design important?",
    options: ["It allows the blade to expand radially without any constraint", "It ensures that enormous centrifugal loads are shared equally between serrations", "It simplifies the casting process"],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "What is the function of the seal at the blade root in the CFM56-7B HPT?",
    options: ["To lock the blade axially", "To assure that air passes only through the blade (not leaking around)", "To reduce the blade weight"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "What is the approximate maximum temperature limit for superalloy blades without internal cooling?",
    options: ["800°C", "1,100°C", "1,425°C"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "Which crystal structure type was introduced in 1977 and requires internal cooling?",
    options: ["Directionally solidified structure", "Equiaxed crystal mixture", "Single crystal"],
    correctOptionIndex: 2,
  },
  {
    id: 58,
    text: "What is a key advantage of the directionally solidified (DS) structure?",
    options: ["It has many grain boundaries for flexibility", "It has long slender crystals aligned in columns, fewer grain boundaries, and is very creep-resistant", "It is the cheapest to manufacture"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "Which turbine blade material/structure virtually eliminates corrosion and has no grain boundaries?",
    options: ["Equiaxed crystal", "Directionally solidified", "Single crystal"],
    correctOptionIndex: 2,
  },
  {
    id: 60,
    text: "What is the service life achieved by the first directional solidified blades introduced in 1979?",
    options: ["10,000 hours", "20,000 hours", "30,000 hours"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "What phenomenon causes a turbine blade to permanently stretch beyond its original length under heat and centrifugal load?",
    options: ["Fatigue", "Creep", "Corrosion"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "Creep is a function of which three factors?",
    options: ["Pressure, temperature, and time", "Centrifugal force, material temperature, and time", "Torque, rotational speed, and blade length"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "Which stage of creep occurs relatively quickly during the engine's first run?",
    options: ["Secondary creep", "Tertiary creep", "Primary creep"],
    correctOptionIndex: 2,
  },
  {
    id: 64,
    text: "On which creep stage do engine manufacturers typically base the turbine's service life?",
    options: ["Primary creep", "Secondary creep (flat portion of strain/time graph)", "Tertiary creep"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "What can cause accelerated (tertiary) creep during engine service life?",
    options: ["Operating at idle power for extended periods", "Hot starts, over-temperatures, extended high power operation, or sand ingestion", "Using too much oil in the bearing sump"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "What material are the low-pressure turbine (LPT) blades in the CFM56-5A made of, and what feature do they have at the tip?",
    options: ["Titanium alloy with a ceramic tip", "Nickel alloy with a shroud and two seal teeth", "Stainless steel with a fir-tree tip"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "Why is anodisation coating applied to LPT rotor stages 1 and 2 in the CFM56-5A?",
    options: ["To change the colour for identification only", "To increase corrosion and wear resistance", "To reduce the blade weight"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "High-pressure turbine (HPT) blades in the CFM56-5A are normally not shrouded. How many tip wear notches do four blades (90° apart) have?",
    options: ["One notch each", "Three tip wear notches each", "Five tip wear notches each"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "What are the two main reasons for cooling turbines in modern engines?",
    options: ["Increase thrust and reduce noise", "Increase service life and improve turbine efficiency (including active clearance control)", "Reduce weight and simplify manufacturing"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "In the CFM56-5A, which turbine stages typically require extra cooling?",
    options: ["Only the LPT stages", "The first two stages (two HPT stages or one HPT + one LPT)", "Only the third and fourth LPT stages"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "What cooling method uses an insert with many small jet holes to direct air against the inner walls of turbine aerofoils?",
    options: ["Convection cooling", "Impingement cooling", "Film cooling"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "Which cooling method blows air through small holes in the aerofoil to form a thin air film on the outer walls, preventing direct contact with hot gas?",
    options: ["Convection cooling", "Impingement cooling", "Film cooling"],
    correctOptionIndex: 2,
  },
  {
    id: 73,
    text: "What is a disadvantage of film cooling?",
    options: ["It requires too much cooling air, reducing turbine power", "The small drill holes are difficult and expensive to make", "It cannot be used on rotor blades, only on nozzle guide vanes"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "In convection cooling, where does the cooling air finally exit after flowing through hollow nozzle vanes and rotor blades?",
    options: ["Through the blade root only", "At the trailing edges and blade tips, mixing with the hot gas flow", "Through the disk center into the bearing cavity"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "Which cooling method is described as the most effective because it achieves maximum cooling effect with minimum cooling air?",
    options: ["Convection cooling", "Impingement cooling", "Film cooling"],
    correctOptionIndex: 2,
  },
  {
    id: 76,
    text: "What is the maximum blade tip speed mentioned during regular engine operation?",
    options: ["300 m/sec", "460 m/sec", "600 m/sec"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "What is the approximate centrifugal load that a small turbine blade (60 g stationary) can exceed along its length at maximum speed?",
    options: ["500 kg", "2 tons", "10 tons"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "What property is most required for nozzle guide vanes since they do not suffer rotational stresses?",
    options: ["High tensile strength", "Heat resistance", "Low weight"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "In the CFM56-5A, what air source cools the first stage rotor blades?",
    options: ["Only low-pressure compressor air", "Partly secondary air from the combustion chamber and compressor discharge pressure (CDP) air", "External ambient air"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "Which cooling methods are used for the first stage nozzle according to the document?",
    options: ["Only convection", "Convection, impingement, and film cooling", "Only impingement and film cooling"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "What is the main task of the exhaust system on a jet engine?",
    options: ["To cool the turbine blades", "To accelerate the airflow from the turbine to make thrust efficiently", "To reduce fuel consumption by recirculating exhaust gases"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "Which type of exhaust nozzle is used on a single-spool turbojet?",
    options: ["Convergent/divergent nozzle", "Convergent exhaust nozzle", "Variable area nozzle"],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "Which engine is an example of a high-bypass twin-spool long-duct turbofan with a mixed exhaust nozzle?",
    options: ["CFM56-7B on B737NG", "CFM56-5C and RR T700 on A330/A340", "PW JT8D on MD80"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "What is the purpose of the swirl vanes fitted at the exhaust of some turboprop engines?",
    options: ["To increase exhaust gas velocity", "To create suction from the oil-cooler-air-intake duct", "To reduce noise from the propeller"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "How does an APU exhaust system reduce noise?",
    options: ["By using chevrons on the nacelle", "By using mufflers in the exhaust duct", "By mixing hot and cold streams externally"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "What is the function of the inner cone in the exhaust casing?",
    options: ["To increase gas velocity", "To shield the turbine disc from exhaust gases and smooth gas flow", "To support the thrust reverser actuators"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "What shape is a subsonic exhaust nozzle?",
    options: ["Divergent", "Convergent", "Parallel"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "What is the maximum velocity achievable across a convergent nozzle?",
    options: ["Mach 2.0", "Mach 1.0", "Mach 0.5"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "How can the nozzle area be adjusted on some engines for trimming?",
    options: ["By changing the fuel nozzle size", "By using adjustable tabs/flaps or moveable plates called eyelids", "By replacing the entire exhaust casing"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "What supports the inner cone in the exhaust casing?",
    options: ["The turbine shaft", "Thin struts of symmetrical aerofoil section", "The outer casing only"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "What is the purpose of a lobe mixer (corrugated exhaust) on engines like CFM56-5C4?",
    options: ["To reduce engine weight", "To allow better mixing of hot primary gas and cold fan air", "To increase exhaust gas temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "Which of the following is an advantage of a lobe mixer?",
    options: ["Lower fuel consumption", "Jet noise reduction and thrust augmentation", "Simpler construction than a common nozzle"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "In the CFM56-5A exhaust, what does the centre body do?",
    options: ["It mixes the bypass and primary air", "It calibrates the exhaust areas and smooths primary exhaust gases", "It acts as a thrust reverser"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "What material is the PW PT6 exhaust duct made of?",
    options: ["Stainless steel", "Heat-resistant sheet nickel alloy", "Titanium alloy"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "In a turboprop like the PW PT6, approximately what percentage of gas energy is extracted for driving the propeller?",
    options: ["50%", "90%", "75%"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "Why is a turboshaft exhaust pipe usually divergent rather than convergent?",
    options: ["To increase jet thrust", "To nullify thrust and improve hover capabilities", "To reduce noise"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "What happens when an exhaust nozzle becomes choked?",
    options: ["Gas velocity exceeds Mach 2", "Exhaust gas velocity equals the speed of sound (Mach 1) at the smallest area", "The nozzle stops flowing air"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "At what pressure ratio does a convergent nozzle typically become choked?",
    options: ["1.1:1", "Around 2:1", "3:1"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "What happens if the nozzle exit pressure is greater than ambient pressure?",
    options: ["Thrust increases linearly", "The exhaust jet bursts in all directions, reducing efficiency", "The nozzle automatically adjusts area"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "According to Bernoulli's principle in a convergent duct with subsonic flow, as the pipe narrows:",
    options: ["Velocity decreases and pressure increases", "Velocity increases (kinetic energy increases)", "Both velocity and pressure remain constant"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "In a high-bypass turbofan with unmixed exhaust, how are the hot and cold streams exhausted?",
    options: ["Through a common nozzle", "Through co-axial nozzles, mixing externally", "Through a single lobed mixer"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "Which engine is an example of a high-bypass turbofan with unmixed exhaust?",
    options: ["CFM56-5C on A340", "CFM56-7 on B737", "RR T700 on A330"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "What is a disadvantage of mixed exhaust systems (e.g., CFM56-5C)?",
    options: ["Higher noise levels", "Heavier and more fuel consumption", "Lower propulsion efficiency"],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "Why do turbofans have higher propulsive efficiency than turbojets?",
    options: ["Because they have higher exhaust velocity", "Because exhaust gas velocity and temperature are lower, closer to aircraft speed", "Because they use afterburners"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "In a low-bypass engine with a common exhaust nozzle, which type of thrust reverser is often used?",
    options: ["Fan air reverser only", "Clamshell door or bucket door type", "Blocker door reverser"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "Convergent/divergent (CD) nozzles are used for pressure ratios greater than:",
    options: ["1.5:1", "2:1", "3:1"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "What is the advantage of a CD nozzle over a convergent nozzle?",
    options: ["Lower weight", "Further increase in exhaust gas velocity and thrust at supersonic speeds", "Simpler construction"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "In an ejector nozzle, what induces the secondary flow?",
    options: ["A mechanical fan", "Suction from the primary gas stream", "Hydraulic actuators"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "What is a disadvantage of the variable-flap ejector nozzle?",
    options: ["It cannot be used at supersonic speeds", "Requires large amount of secondary air, causing high aerodynamic drag", "It is not adjustable"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "Which nozzle type is considered one of the most efficient and is used on the F-15, F-16, and B-1B?",
    options: ["Ejector nozzle", "Iris nozzle", "Variable-flap nozzle"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "What are the two primary sources of noise in a gas turbine engine?",
    options: ["Fuel pumps and gearboxes", "Fans/compressors/turbines and mixing of jet efflux with ambient air", "Combustion chamber and exhaust casing"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "How does increasing the perimeter of the exhaust stream reduce noise?",
    options: ["By lowering exhaust temperature", "By raising the frequency (breaking large vortices into fine-grain turbulence)", "By reducing mass flow"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "What materials are used for noise absorption in the hot sections of an engine?",
    options: ["Lightweight composite materials", "Fibrous metallic material", "Honeycomb plastic"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "What is the effect of deep corrugations or lobes on a nozzle?",
    options: ["Decrease noise but increase performance penalties (drag, weight)", "Increase noise and decrease thrust", "No effect on noise"],
    correctOptionIndex: 0,
  },
  {
    id: 115,
    text: "What are chevrons on a jet engine nozzle?",
    options: ["Acoustic panels inside the intake", "Sawtooth patterns on trailing edges that smooth mixing and reduce noise", "Variable geometry flaps"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "What is a primary purpose of thrust reversers?",
    options: ["To increase takeoff thrust", "To aid in braking and directional control during landing, reduce brake maintenance", "To cool the turbine during flight"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "On modern jet engines, when can thrust reversers be used?",
    options: ["In flight at any altitude", "Only on the ground", "Only during rejected takeoff below V1"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "How many independent locks typically keep the reverser stowed during flight on modern engines?",
    options: ["One", "Three", "Five"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "Which safeguard prevents reverse thrust from being selected above idle power?",
    options: ["Air/ground logic interlock", "Throttle lever must be at idle", "Weight-on-wheels switch"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "If a reverser inadvertently deploys in flight on a modern aircraft, what happens?",
    options: ["The engine automatically shuts down", "The throttle may automatically close to idle or the reverser automatically restows", "The pilot must manually override"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "Which three types of thrust reversers are commonly used?",
    options: ["Clamshell door, bucket door, fan air reverser", "Cascade vane, blocker door, target door", "Pneumatic, hydraulic, electric"],
    correctOptionIndex: 0,
  },
  {
    id: 122,
    text: "On a high bypass turbofan with separate exhausts, a core reverser is rarely used because:",
    options: ["It reverses too much thrust", "It is expensive and the core stream produces only ~20% of thrust", "It is not certified"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "Which reverser type is typically pneumatically operated on older low-bypass engines?",
    options: ["Bucket door", "Clamshell door", "Cascade vane"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "The bucket door type reverser is typically operated by:",
    options: ["Bleed air", "Aircraft hydraulic system", "Electric motors"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "What do fan air reversers (cascade vane type) reverse?",
    options: ["Both core and fan air", "Only the fan air", "Only the core air"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "On the JT8D-MD80 bucket door reverser, what provides backup hydraulic source to stow actuators during flight?",
    options: ["A second engine-driven pump", "An accumulator", "A manual hand pump"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "What does the \"REVERS UNLOCK\" light indicate on the MD80?",
    options: ["Hydraulic pressure low", "Either latch has unlocked", "Reverser fully deployed"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "What prevents the reverser doors from slamming during deployment?",
    options: ["A flow regulator in the stow pressure lines", "Mechanical stops", "Rubber bumpers"],
    correctOptionIndex: 0,
  },
  {
    id: 129,
    text: "The interlock mechanism on the JT8D reverser prevents power application until:",
    options: ["The engine is at idle", "The reverser doors are fully deployed", "The aircraft is on the ground"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "In flight, the solenoid on the JT8D reverser control valve is energised via ground sensing. What does it do?",
    options: ["Deploys the reverser", "Ports accumulator pressure to the stow side of actuators", "Locks the throttle"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "On the Boeing 727 clamshell reverser, what operates the actuator?",
    options: ["Hydraulic pressure", "Bleed air", "Electric motor"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "The forward thrust lever must be at which position before the reverse thrust lever can be operated?",
    options: ["Full forward", "IDLE", "Cut-off"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "When the reverse thrust lever is moved to \"REVERSE INTERLOCK\" position, what happens first?",
    options: ["Engine speed increases", "Bleed air unlocks the mechanical lock and extends clamshell doors", "The fuel is shut off"],
    correctOptionIndex: 1,
  },
  {
    id: 134,
    text: "On the B727, where are the gases deflected for the centre engine?",
    options: ["Above and below the engine", "Out of the sides of the aft fuselage", "Straight down"],
    correctOptionIndex: 1,
  },
  {
    id: 135,
    text: "When the clamshell doors reach the forward thrust position during stow, what engages?",
    options: ["The accumulator", "The mechanical lock", "The throttle interlock"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "On the PW4068 fan reverser, what moves rearwards to uncover the cascade vanes?",
    options: ["Blocker doors", "Translating cowl sleeves", "Bucket doors"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "What is the purpose of the translating cowl lock system (TLS) on the PW4068?",
    options: ["To lock the cowl in deployed position", "To inhibit inadvertent in-flight reverser operation", "To lock the cascade vanes"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "What inputs does the TLS use?",
    options: ["Engine EGT and N1", "Radio altimeter and flight control primary computer (FCPC) information", "Throttle lever position only"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "How many hydraulic actuators drive each translating cowl on the PW4068?",
    options: ["Two", "Six", "Four"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "What is the function of the blocker doors in this reverser?",
    options: ["To direct air into the core", "To block the fan discharge duct and divert fan air through cascades", "To cool the turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "What material are the cascades on the PW4068 reverser made of?",
    options: ["Nickel alloy", "Resin transfer moulded graphite epoxy with graphite fibre reinforcement", "Stainless steel"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "How many different cascade types exist on the PW4068, and how many cascades per reverser door?",
    options: ["3 types, 6 cascades", "6 types, 9 cascades", "9 types, 12 cascades"],
    correctOptionIndex: 1,
  },
  {
    id: 143,
    text: "What is the purpose of the synchronous shaft in the PW4068 reverser?",
    options: ["To lock the translating cowl", "To keep speed and travel of actuators synchronised for smooth deployment", "To provide hydraulic pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "What does the feedback actuator contain that the EEC monitors to determine translating cowl position?",
    options: ["A potentiometer", "A linear variable differential transducer (LVDT)", "A proximity switch"],
    correctOptionIndex: 1,
  },
  {
    id: 145,
    text: "On the PW4068, the translating cowl locking system (TLS) uses a locking pawl that engages a structural load plate. What visible indicator shows lock status?",
    options: ["A warning light on the flight deck", "An externally visible indicator on the fan cowl", "A flag on the throttle lever"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "Which Airbus engines use the blocker-door type reverser?",
    options: ["IAE V2500", "CFM or RR engines", "PW4000"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "On the RR T700 reverser, each pivoting door is maintained in stow position by how many locks?",
    options: ["One", "Three (primary hydraulic, secondary hydraulic, electrical tertiary)", "Two"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "Which hydraulic systems supply the HCS for engine 1 and engine 2 on the RR T700?",
    options: ["Green and yellow", "Blue (engine 1) and yellow (engine 2)", "Red and blue"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "What does the ICU (isolation control unit) do in the RR T700 reverser system?",
    options: ["Controls the deploy speed", "Lets hydraulic pressure go to DCU or isolates the supply", "Monitors door position"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "What indicates the actual state of the thrust reverser on the EWD (Electronic Warning Display)?",
    options: ["\"REV\" indication in the middle of the EPR dial", "A green \"REV\" light", "The word \"DEPLOY\""],
    correctOptionIndex: 0,
  },
  {
    id: 151,
    text: "What does V1 represent in take-off?",
    options: ["Rotation speed", "The highest speed at which the flight crew has a choice between continuing or stopping take-off", "Minimum take-off speed"],
    correctOptionIndex: 1,
  },
  {
    id: 152,
    text: "When deactivating a reverser for flight, what must be installed on the moving parts (e.g., translating cowl)?",
    options: ["A lock wire", "A mechanical lock, often a red pin visible from outside", "A safety tag only"],
    correctOptionIndex: 1,
  },
  {
    id: 153,
    text: "Deactivating a reverser for flight typically reduces which take-off speed?",
    options: ["V2", "V1", "VR"],
    correctOptionIndex: 1,
  },
  {
    id: 154,
    text: "If only one reverser is deactivated on some engines, what does the MEL advise?",
    options: ["Do not use reverse thrust at all", "Use only the good reverser at first detent, not full reverse on contaminated runways", "Increase V1 speed"],
    correctOptionIndex: 1,
  },
  {
    id: 155,
    text: "Where is the deactivation lever for isolating hydraulic/air supply typically located?",
    options: ["On the flight deck", "On the isolation valve (IV) near the engine", "On the landing gear"],
    correctOptionIndex: 1,
  },
  {
    id: 156,
    text: "What are the three positions of the reverse thrust levers?",
    options: ["Stowed, reverse idle, full reverse", "Deploy, hold, stow", "Idle, climb, reverse"],
    correctOptionIndex: 0,
  },
  {
    id: 157,
    text: "What does the throttle interlock mechanism do?",
    options: ["Prevents engine overspeed", "Locks the reverser control system while transitioning from stowed to deployed position", "Disables the reverser in flight"],
    correctOptionIndex: 1,
  },
  {
    id: 158,
    text: "The lever interlock system ensures that:",
    options: ["Both forward and reverse thrust levers can be used simultaneously", "Forward and reverse thrust levers cannot be activated simultaneously", "Reverse thrust cannot exceed forward thrust"],
    correctOptionIndex: 1,
  },
  {
    id: 159,
    text: "On some aircraft (Airbus), only the outer engines' reverser levers are protected by throttle interlock. Why?",
    options: ["To save weight", "Because asymmetric thrust from an outboard engine failure is more dangerous (yaw)", "Inner engines cannot be reversed"],
    correctOptionIndex: 1,
  },
  {
    id: 160,
    text: "On FADEC-controlled engines, who typically controls and monitors reverser operation?",
    options: ["The pilot", "The engine electronic controller (EEC/ECU)", "The hydraulic control unit"],
    correctOptionIndex: 1,
  },
  {
    id: 161,
    text: "In a turboshaft engine, why is no jet thrust obtained?",
    options: ["The exhaust is directed sideways", "The turbine extracts all gas energy to drive a gearbox", "The exhaust nozzle is blocked"],
    correctOptionIndex: 1,
  },
  {
    id: 162,
    text: "What is the function of an ejector on an APU exhaust system?",
    options: ["To increase thrust", "To draw ambient air into the exhaust stream for cooling", "To reduce fuel flow"],
    correctOptionIndex: 1,
  },
  {
    id: 163,
    text: "In a convergent nozzle, when gas velocity is subsonic, which energy is greater?",
    options: ["Kinetic energy", "Potential energy", "Both are equal"],
    correctOptionIndex: 1,
  },
  {
    id: 164,
    text: "At the choked condition, potential and kinetic energy of the gas are in:",
    options: ["Imbalance", "Equilibrium", "Zero"],
    correctOptionIndex: 1,
  },
  {
    id: 165,
    text: "The forward force due to pressure difference across the nozzle area is given by F = ANOZ (PNOZ - PA). This force acts on which part?",
    options: ["The compressor", "The turbine rear side", "The exhaust cone"],
    correctOptionIndex: 1,
  },
  {
    id: 166,
    text: "What noise reduction strategy uses honeycomb materials in intakes and casings?",
    options: ["Chevrons", "Acoustic liners", "Lobed mixers"],
    correctOptionIndex: 1,
  },
  {
    id: 167,
    text: "Low-frequency noise remains at relatively high volume. How is it reduced?",
    options: ["By lowering engine RPM", "By raising the frequency (increasing perimeter of exhaust stream)", "By adding mufflers"],
    correctOptionIndex: 1,
  },
  {
    id: 168,
    text: "What is the effect of chevrons on the 787?",
    options: ["Increase thrust", "Reduce engine noise levels, allowing less sound insulation in fuselage", "Improve fuel efficiency"],
    correctOptionIndex: 1,
  },
  {
    id: 169,
    text: "Why are performance penalties a limiting factor for deep corrugations or lobes?",
    options: ["They increase exhaust temperature", "They cause excessive drag and weight", "They reduce thrust reverser effectiveness"],
    correctOptionIndex: 1,
  },
  {
    id: 170,
    text: "What is the main noise source on a turboprop engine?",
    options: ["Jet efflux", "The propeller", "The exhaust nozzle"],
    correctOptionIndex: 1,
  },
  {
    id: 171,
    text: "On the JT8D reverser, what does the \"REVERS ACCUMULATOR LOW\" light indicate?",
    options: ["Accumulator needs servicing", "Accumulator pressure has dropped too much", "Accumulator is overcharged"],
    correctOptionIndex: 1,
  },
  {
    id: 172,
    text: "On the RR T700 reverser, what does each pivoting door have to provide position to the EEC?",
    options: ["A pressure switch", "A stow switch and a rotary variable transducer (RVT)", "A potentiometer"],
    correctOptionIndex: 1,
  },
  {
    id: 173,
    text: "On the RR T700, what does the tertiary locking system (TLS) provide?",
    options: ["Hydraulic lock", "An independent electrical lock", "A mechanical lock"],
    correctOptionIndex: 1,
  },
  {
    id: 174,
    text: "When reverser is deactivated for flight, what must be entered into the aircraft logbook?",
    options: ["A maintenance request", "A remark and the reverser control marked with a red INOP tag", "A performance calculation"],
    correctOptionIndex: 1,
  },
  {
    id: 175,
    text: "On the CFM56-5A, the centre body is open at the aft end to:",
    options: ["Mix hot and cold air", "Let engine vent to atmosphere", "Attach the reverser"],
    correctOptionIndex: 1,
  },
  {
    id: 176,
    text: "On the CFM56-5C4, what is a disadvantage of the lobe mixer compared to RR's common nozzle assembly?",
    options: ["Higher noise", "Heavier", "Lower thrust"],
    correctOptionIndex: 1,
  },
  {
    id: 177,
    text: "The RR Trent 700 common nozzle assembly (CNA) uses which method for noise damping?",
    options: ["Lobes", "Acoustic panels", "Chevrons"],
    correctOptionIndex: 1,
  },
  {
    id: 178,
    text: "In the PW PT6 exhaust, what does the insulation blanket protect?",
    options: ["The gas generator case", "The power turbine shaft and reduction gearbox from high temperature", "The exhaust ports"],
    correctOptionIndex: 1,
  },
  {
    id: 179,
    text: "On a turboshaft helicopter exhaust, why is a scalloped outer perimeter used on newer designs?",
    options: ["For thrust augmentation", "For noise suppression", "For cooling"],
    correctOptionIndex: 1,
  },
  {
    id: 180,
    text: "According to the document, the MEL for an A330 T700 engine with one reverser deactivated may require the flight crew to:",
    options: ["Not use reverse thrust on any engine", "Use only the good reverser at first detent if runway is contaminated", "Increase landing distance by 50%"],
    correctOptionIndex: 1,
  },
  {
    id: 181,
    text: "Which type of lubricating oil is used on all modern gas turbine engines?",
    options: ["Mineral oil", "Vegetable oil", "Synthetic oil"],
    correctOptionIndex: 2,
  },
  {
    id: 182,
    text: "What is the most important characteristic of engine oil?",
    options: ["Flash point", "Viscosity", "Pour point"],
    correctOptionIndex: 1,
  },
  {
    id: 183,
    text: "What is the pour point of typical Type 3 jet engine oils?",
    options: ["–40°C", "–62°C", "–80°C"],
    correctOptionIndex: 1,
  },
  {
    id: 184,
    text: "Why should the flash point of engine oil be as high as possible?",
    options: ["To improve viscosity index", "To avoid fire in the oil system", "To prevent oxidation"],
    correctOptionIndex: 1,
  },
  {
    id: 185,
    text: "Thermal stability of oil describes its resistance to:",
    options: ["Reaction with oxygen", "Decomposition of oil compounds at high temperatures", "Freezing at low temperatures"],
    correctOptionIndex: 1,
  },
  {
    id: 186,
    text: "Type 3 oils can resist chemical decomposition at temperatures up to:",
    options: ["220°C", "250°C", "340°C"],
    correctOptionIndex: 2,
  },
  {
    id: 187,
    text: "Which MIL-PRF specification oil is designed for low-temperature environments allowing cold starts down to –51°C?",
    options: ["MIL-PRF-23699 Type 2", "MIL-PRF-7808", "MIL-PRF-23699 Type 3 HTS"],
    correctOptionIndex: 1,
  },
  {
    id: 188,
    text: "HTS oils (Type 3) have superior resistance to:",
    options: ["Low temperature gelling", "Coke formation at elevated temperatures", "Water contamination"],
    correctOptionIndex: 1,
  },
  {
    id: 189,
    text: "Viscosity Index (VI) is a measure of:",
    options: ["Oil thickness at room temperature", "Change in viscosity relative to temperature change", "Oil pressure resistance"],
    correctOptionIndex: 1,
  },
  {
    id: 190,
    text: "Oxidation resistance is important because it influences:",
    options: ["The oil's flash point", "The oil's durability", "The oil's pour point"],
    correctOptionIndex: 1,
  },
  {
    id: 191,
    text: "Which additive allows oil to hold sludge or debris in suspension?",
    options: ["Extreme pressure additive", "Detergent additive", "Anti-corrosion additive"],
    correctOptionIndex: 1,
  },
  {
    id: 192,
    text: "Extreme pressure additives are typically added to oil used in:",
    options: ["High-bypass turbofans", "Turboprops with heavily loaded gear trains", "APU gearboxes"],
    correctOptionIndex: 1,
  },
  {
    id: 193,
    text: "If synthetic turbine oil contacts the eye, the recommended action is:",
    options: ["Rub the eye vigorously", "Wash with water and obtain medical advice", "Apply oil-based ointment"],
    correctOptionIndex: 1,
  },
  {
    id: 194,
    text: "When servicing a gas-turbine lubrication system, servicing equipment should:",
    options: ["Be used for multiple oil types to save cost", "Be marked for the type of oil to be used", "Be cleaned with kerosene between uses"],
    correctOptionIndex: 1,
  },
  {
    id: 195,
    text: "Synthetic turbine oil containers are typically available in sizes including:",
    options: ["5 quarts, 10 litres, 5 gallons", "1 US quart, 1 litre, 1 gallon", "500 ml, 2 litres, 20 litres"],
    correctOptionIndex: 2,
  },
  {
    id: 196,
    text: "Water in lubricating oil can cause all of the following EXCEPT:",
    options: ["Breakdown of lubrication on heavily loaded surfaces", "Increase in oil viscosity due to thickening", "Excessive frothing and loss of oil through vent system"],
    correctOptionIndex: 1,
  },
  {
    id: 197,
    text: "A quick test for finely divided water in oil is to heat a small quantity to 200°C. If water is present, the oil:",
    options: ["Turns black", "Crackles", "Emits a sweet smell"],
    correctOptionIndex: 1,
  },
  {
    id: 198,
    text: "Contamination by other fluids (kerosene, hydraulic fluid) may cause:",
    options: ["Lower fire risk", "Breakdown of additives and possible seal failure", "Improved viscosity"],
    correctOptionIndex: 1,
  },
  {
    id: 199,
    text: "After draining and flushing a contaminated oil system, the engine should be ground-run and then monitored every 10 hours for the next:",
    options: ["50 hours", "100 hours", "200 hours"],
    correctOptionIndex: 1,
  },
  {
    id: 200,
    text: "If oil looks misty instead of bright and clear, it may indicate:",
    options: ["Overheating", "Finely divided water in suspension", "Additive depletion"],
    correctOptionIndex: 1,
  },
  {
    id: 201,
    text: "Which property of fuel should be as high as possible to reduce fire hazards?",
    options: ["Specific gravity", "Flashpoint", "Freezing point"],
    correctOptionIndex: 1,
  },
  {
    id: 202,
    text: "The ideal fuel should permit engine starting at all ground conditions and give:",
    options: ["Maximum exhaust temperature", "Satisfactory flight relighting characteristics", "Minimum specific gravity"],
    correctOptionIndex: 1,
  },
  {
    id: 203,
    text: "Which of the following is a property usually listed in fuel specifications?",
    options: ["Colour index", "Sulphur content", "Octane number"],
    correctOptionIndex: 1,
  },
  {
    id: 204,
    text: "Jet A and Jet A-1 are classified as:",
    options: ["Wide-cut fuels", "Low-temperature kerosene fuels", "High-octane gasoline blends"],
    correctOptionIndex: 1,
  },
  {
    id: 205,
    text: "The freezing point of Jet A-1 is:",
    options: ["–40°C", "–47°C", "–60°C"],
    correctOptionIndex: 1,
  },
  {
    id: 206,
    text: "Jet B and JP-4 are described as wide-cut fuels, blending approximately:",
    options: ["50% kerosene and 50% gasoline", "30% kerosene and 70% gasoline", "70% kerosene and 30% gasoline"],
    correctOptionIndex: 1,
  },
  {
    id: 207,
    text: "Which additive eliminates the hazardous effects of static electricity generated by fuel movement?",
    options: ["Anti-oxidant", "Static dissipater", "Metal deactivator"],
    correctOptionIndex: 1,
  },
  {
    id: 208,
    text: "Prist is a well-known additive that protects against:",
    options: ["Corrosion only", "Fungicides and freezing of entrained water", "Static discharge"],
    correctOptionIndex: 1,
  },
  {
    id: 209,
    text: "Biocide additives (e.g., Biopor) reduce the risk of:",
    options: ["Fuel oxidation", "Microbiological growth in fuel systems", "Metal corrosion"],
    correctOptionIndex: 1,
  },
  {
    id: 210,
    text: "Fuel system icing inhibitors reduce the freezing point of:",
    options: ["The fuel itself", "Water precipitated by the fuel as it cools", "The engine oil"],
    correctOptionIndex: 1,
  },
  {
    id: 211,
    text: "When pressure refuelling, the earthing wire on the refuelling pipe should be connected:",
    options: ["After connecting the refuelling pipe", "Before connecting the refuelling pipe", "Only after fuelling is complete"],
    correctOptionIndex: 1,
  },
  {
    id: 212,
    text: "During refuelling or defuelling, radio and radar equipment should be:",
    options: ["Operated only in standby mode", "Not operated", "Operated at reduced power"],
    correctOptionIndex: 1,
  },
  {
    id: 213,
    text: "When working inside a fuel tank, what must be used at all times?",
    options: ["Cotton overalls", "An air-fed vapour mask", "Leather gloves"],
    correctOptionIndex: 1,
  },
  {
    id: 214,
    text: "Which type of tools should be used when working near fuel?",
    options: ["Standard electric tools", "Spark-free power tools", "Pneumatic tools only"],
    correctOptionIndex: 1,
  },
  {
    id: 215,
    text: "If fuel is spilled on clothing, you should:",
    options: ["Continue wearing it until it dries", "Remove immediately and clean before re-use", "Sprinkle water on it"],
    correctOptionIndex: 1,
  },
  {
    id: 216,
    text: "A Hydrokit (Exxon) test detects undissolved water in turbine fuel at levels of:",
    options: ["10 ppm or more", "30 ppm or more", "50 ppm or more"],
    correctOptionIndex: 1,
  },
  {
    id: 217,
    text: "Microbiological contamination in fuel is usually caused by a fungus called:",
    options: ["Aspergillus niger", "Cladosporium Resinae", "Penicillium chrysogenum"],
    correctOptionIndex: 1,
  },
  {
    id: 218,
    text: "The fungus Cladosporium Resinae needs free water and a temperature range of:",
    options: ["0°C to 10°C", "25°C to 35°C", "40°C to 50°C"],
    correctOptionIndex: 1,
  },
  {
    id: 219,
    text: "Ethylene glycol monomethyl ether (EGME) is used as an anti-icing additive and biocide at a concentration of:",
    options: ["0.05% by volume", "0.15% by volume", "0.5% by volume"],
    correctOptionIndex: 1,
  },
  {
    id: 220,
    text: "When using Biobor on an intermittent basis (every two months), the maximum concentration is:",
    options: ["135 ppm", "270 ppm", "540 ppm"],
    correctOptionIndex: 1,
  },
  {
    id: 221,
    text: "Which of the following is a basic requirement of a lubrication system?",
    options: ["Oil should be supplied at variable pressure depending on RPM", "Each bearing should receive a predetermined flow of oil", "Oil temperature should be as low as possible at all times"],
    correctOptionIndex: 1,
  },
  {
    id: 222,
    text: "What is one function of lubricating oil in a gas turbine engine?",
    options: ["To increase friction in bearings", "To reduce temperature", "To increase contamination"],
    correctOptionIndex: 1,
  },
  {
    id: 223,
    text: "Which characteristic is required for lubricating oil used in gas turbine engines?",
    options: ["High viscosity at all temperatures", "Chemically stable over a wide range of operating temperatures", "Derived from vegetable sources"],
    correctOptionIndex: 1,
  },
  {
    id: 224,
    text: "Low-pressure air passed over bearing housings helps to:",
    options: ["Increase oil viscosity", "Cool and pressurise the housing, reducing leakage", "Lubricate the bearings directly"],
    correctOptionIndex: 1,
  },
  {
    id: 225,
    text: "Synthetic lubricating oils are preferred because they have:",
    options: ["Low heat capacity", "High heat capacity and chemical stability", "High viscosity at low temperatures"],
    correctOptionIndex: 1,
  },
  {
    id: 226,
    text: "A wet-sump lubrication system stores the lubricating oil:",
    options: ["In an external tank mounted on the engine", "Inside the engine", "In the fuel tank"],
    correctOptionIndex: 1,
  },
  {
    id: 227,
    text: "In a hot-tank lubrication system, the oil cooler is located:",
    options: ["In the scavenge subsystem after the tank", "In the pressure subsystem, and scavenged oil is not cooled before returning to tank", "Between the scavenge pump and the tank"],
    correctOptionIndex: 1,
  },
  {
    id: 228,
    text: "In a cold-tank lubrication system, the oil cooler is placed:",
    options: ["After the pressure pump but before the tank", "In the scavenge line before the oil tank", "Inside the oil tank"],
    correctOptionIndex: 1,
  },
  {
    id: 229,
    text: "In a hot-tank system, if the oil temperature is low, the temperature bypass valve:",
    options: ["Forces oil through the cooler", "Opens and allows oil to flow directly to bearings", "Closes the filter bypass"],
    correctOptionIndex: 1,
  },
  {
    id: 230,
    text: "In a cold-tank system, if oil is too hot, the temperature bypass valve:",
    options: ["Opens to allow more flow to the tank", "Closes, forcing oil through the cooler", "Diverts oil to the pressure relief valve"],
    correctOptionIndex: 1,
  },
  {
    id: 231,
    text: "A sight glass in the oil reservoir is used to indicate:",
    options: ["Oil pressure", "Oil level", "Oil temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 232,
    text: "The deaeration tray inside the oil reservoir is used to:",
    options: ["Add air to the oil", "Separate air from returned oil", "Filter large debris"],
    correctOptionIndex: 1,
  },
  {
    id: 233,
    text: "The engine-driven pressure pump is usually a:",
    options: ["Centrifugal pump", "Gear-type pump", "Piston pump"],
    correctOptionIndex: 1,
  },
  {
    id: 234,
    text: "A characteristic of the pressure relief system is that indicated oil pressure is:",
    options: ["Directly proportional to engine RPM", "Independent of engine RPM", "Inversely proportional to engine RPM"],
    correctOptionIndex: 1,
  },
  {
    id: 235,
    text: "Calibrated spray jets or metering devices ensure that:",
    options: ["Oil pressure is constant", "Each bearing receives the designed quantity of oil", "Oil is filtered before reaching bearings"],
    correctOptionIndex: 1,
  },
  {
    id: 236,
    text: "Scavenge pumps generally have a capacity at least how many times greater than pressure pumps?",
    options: ["1.0 times", "1.5 times", "2.0 times"],
    correctOptionIndex: 1,
  },
  {
    id: 237,
    text: "Why do scavenge pumps have greater capacity?",
    options: ["To increase oil pressure", "To accommodate increased volume due to aeration and temperature rise", "To reduce oil consumption"],
    correctOptionIndex: 1,
  },
  {
    id: 238,
    text: "Individual scavenge filters help to:",
    options: ["Increase oil temperature", "Identify and localise wear debris from failed bearings", "Reduce oil viscosity"],
    correctOptionIndex: 1,
  },
  {
    id: 239,
    text: "The vent subsystem in some engines vents seal leakage air:",
    options: ["Back to the compressor", "Overboard", "Into the oil tank"],
    correctOptionIndex: 1,
  },
  {
    id: 240,
    text: "In the RB211-700, the LP turbine bearing does not have an air vent line because:",
    options: ["It is sealed with carbon seals", "It is small enough to transmit air with oil back to the tank", "It uses a separate breather system"],
    correctOptionIndex: 1,
  },
  {
    id: 241,
    text: "Which lubrication system type is most widely used on gas turbine engines?",
    options: ["Full-flow system", "Pressure relief system", "Total loss system"],
    correctOptionIndex: 1,
  },
  {
    id: 242,
    text: "In a pressure relief valve system, the oil pressure regulator is a spring-loaded valve that:",
    options: ["Increases oil pressure with RPM", "Returns excessive oil to the pump inlet", "Diverts oil to the scavenge system"],
    correctOptionIndex: 1,
  },
  {
    id: 243,
    text: "A disadvantage of the pressure relief valve system is that it:",
    options: ["Cannot maintain pressure at high RPM", "Over-oils at low RPM and slightly under-oils at maximum RPM after relief valve cuts in", "Requires a larger oil tank"],
    correctOptionIndex: 1,
  },
  {
    id: 244,
    text: "In a full-flow system, the pressure relief valve:",
    options: ["Opens during regular operation to regulate pressure", "Is fitted as a safety device and cannot open during regular operation", "Is not installed"],
    correctOptionIndex: 1,
  },
  {
    id: 245,
    text: "The full-flow system has a pressure pump that is:",
    options: ["Larger than in a pressure relief system", "Not as large as in a pressure relief system", "The same size"],
    correctOptionIndex: 1,
  },
  {
    id: 246,
    text: "Which bearing lubrication method uses a small spray jet directing oil onto rolling elements?",
    options: ["Splash oil", "Spray jet/pressure-fed", "Metered oil film"],
    correctOptionIndex: 1,
  },
  {
    id: 247,
    text: "Splash lubrication is typically used for:",
    options: ["Main engine bearings", "Gears inside the gearbox", "Turbine bearings"],
    correctOptionIndex: 1,
  },
  {
    id: 248,
    text: "Metered oil feed is used to supply bearings with correct oil quantity in relation to:",
    options: ["Oil temperature", "Engine speed", "Oil pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 249,
    text: "In film lubrication, the most important oil property is:",
    options: ["Flash point", "Viscosity", "Pour point"],
    correctOptionIndex: 1,
  },
  {
    id: 250,
    text: "What is the purpose of a squeeze film bearing?",
    options: ["To increase friction", "To dampen radial motion and dynamic loads, reducing vibration", "To reduce oil consumption"],
    correctOptionIndex: 1,
  },
  {
    id: 251,
    text: "In a dry sump system, the oil supply reservoir is generally classified as:",
    options: ["Wet or dry", "Hot-tank or cold-tank", "Pressurised or unpressurised"],
    correctOptionIndex: 1,
  },
  {
    id: 252,
    text: "The anti-syphon tube in an oil tank is required to:",
    options: ["Prevent oil from foaming", "Break a syphon action on engine shutdown", "Increase oil pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 253,
    text: "A scupper drain in the gravity filler collects:",
    options: ["Air from the tank", "Spilt oil during replenishment", "Fuel contamination"],
    correctOptionIndex: 1,
  },
  {
    id: 254,
    text: "Some manufacturers specify reading oil level not before 10 minutes and not longer than one hour after shutdown. This is because:",
    options: ["Oil needs to cool completely", "Oil level measurement calibration depends on time after shutdown", "The oil tank must depressurise"],
    correctOptionIndex: 1,
  },
  {
    id: 255,
    text: "After maintenance, a complete top-up is carried out after the minimum time after shutdown shown in the AMM, following:",
    options: ["A high-power engine run", "An idle RPM run to establish a warm datum", "A cold soak period"],
    correctOptionIndex: 1,
  },
  {
    id: 256,
    text: "The most common oil pumps in gas turbine engines are vane, gerotor, and gear types. All are:",
    options: ["Centrifugal pumps", "Positive displacement pumps", "Variable displacement pumps"],
    correctOptionIndex: 1,
  },
  {
    id: 257,
    text: "A vane pump is considered more tolerant of debris in scavenge oil and offers:",
    options: ["Higher pressure output", "Lighter weight and slimmer profile", "Greater mechanical strength"],
    correctOptionIndex: 1,
  },
  {
    id: 258,
    text: "In a vane pump, the downstream resistance to flow determines pump output pressure unless:",
    options: ["A filter is present", "A relief valve regulates pressure", "The pump speed changes"],
    correctOptionIndex: 1,
  },
  {
    id: 259,
    text: "Multiple vane pumps generally contain one pressure element and one or more scavenge elements:",
    options: ["Driven by separate shafts", "All mounted on a common shaft", "Driven by electric motors"],
    correctOptionIndex: 1,
  },
  {
    id: 260,
    text: "Vane pumps may not have the mechanical strength of:",
    options: ["Centrifugal pumps", "Gerotor or gear pumps", "Piston pumps"],
    correctOptionIndex: 1,
  },
  {
    id: 261,
    text: "A gerotor pump uses a lobe-shaped drive gear within an elliptically-shaped idler gear. The inner driving gear has six lobes; the outer idler gear has:",
    options: ["Six openings", "Seven openings", "Eight openings"],
    correctOptionIndex: 1,
  },
  {
    id: 262,
    text: "In a gerotor pump, the volume of oil pumped per revolution is determined by:",
    options: ["The pressure setting", "The volume of the missing tooth multiplied by number of lobes in outer gear", "The pump speed"],
    correctOptionIndex: 1,
  },
  {
    id: 263,
    text: "In a gear-type pump, the idler gear seals the inlet from the outlet, which:",
    options: ["Reduces flow", "Prevents fluid backup and doubles capacity per revolution", "Increases pressure ripple"],
    correctOptionIndex: 1,
  },
  {
    id: 264,
    text: "For large engines, it is normal to have up to how many scavenge pumps in one assembly?",
    options: ["Three", "Seven", "Ten"],
    correctOptionIndex: 1,
  },
  {
    id: 265,
    text: "The most common pump assembly seen on gas turbine engines is a dual pump with:",
    options: ["Two pressure elements", "Pressure and scavenge elements", "Two scavenge elements"],
    correctOptionIndex: 1,
  },
  {
    id: 266,
    text: "Cleanable screen filters (woven wire) cannot generally filter below:",
    options: ["15 microns", "40 microns", "100 microns"],
    correctOptionIndex: 1,
  },
  {
    id: 267,
    text: "Fibre filters can screen down to 15 microns and are:",
    options: ["Reusable after cleaning", "Disposable", "Cleanable in an ultrasonic bath"],
    correctOptionIndex: 1,
  },
  {
    id: 268,
    text: "Thread filters are also known as:",
    options: ["Primary filters", "Last-chance filters", "Scavenge screens"],
    correctOptionIndex: 1,
  },
  {
    id: 269,
    text: "Scavenge screen filters are coarse mesh filters that often accommodate:",
    options: ["Pressure relief valves", "Magnetic chip detectors", "Temperature sensors"],
    correctOptionIndex: 1,
  },
  {
    id: 270,
    text: "Delta P indication on a filter shows that the filter:",
    options: ["Is clean", "Will imminently bypass", "Has failed"],
    correctOptionIndex: 1,
  },
  {
    id: 271,
    text: "A fuel-cooled oil cooler (FCOC) serves two purposes: cooling oil and:",
    options: ["Heating the fuel to prevent freezing", "Warming the fuel to prevent ice formation in LP fuel filter", "Cooling the fuel"],
    correctOptionIndex: 1,
  },
  {
    id: 272,
    text: "The FCOC is always located in the fuel system immediately before:",
    options: ["The HP fuel pump", "The LP fuel filter", "The fuel nozzles"],
    correctOptionIndex: 1,
  },
  {
    id: 273,
    text: "If oil quantity increases, a failed FCOC matrix would be suspected because:",
    options: ["Oil is leaking into the fuel", "Fuel is leaking into the oil", "The cooler is blocked"],
    correctOptionIndex: 1,
  },
  {
    id: 274,
    text: "Some larger engines have a secondary air-oil cooler that is activated:",
    options: ["At low power conditions", "Under high-power conditions", "Only during starting"],
    correctOptionIndex: 1,
  },
  {
    id: 275,
    text: "Not all FCOCs have thermostatic valves; some have a Delta P bypass for:",
    options: ["Hot oil", "Cold oil causing a pressure differential", "Fuel contamination"],
    correctOptionIndex: 1,
  },
  {
    id: 276,
    text: "A deaerator tray in the oil tank is used to:",
    options: ["Add air to the oil", "Remove air from the oil before recirculation", "Filter oil"],
    correctOptionIndex: 1,
  },
  {
    id: 277,
    text: "The gearbox usually contains an air/oil centrifugal breather that:",
    options: ["Adds air to the gearbox", "Separates oil from the air mist and returns oil to the tank", "Vents oil overboard"],
    correctOptionIndex: 1,
  },
  {
    id: 278,
    text: "The air-oil heat exchanger (AOHE) is controlled by the EEC using:",
    options: ["Oil pressure as primary control parameter", "Oil temperature as primary control parameter", "Fuel flow as primary control parameter"],
    correctOptionIndex: 1,
  },
  {
    id: 279,
    text: "The air-modulating valve for the AOHE is actuated by a hydraulic actuator using:",
    options: ["Hydraulic fluid", "Fuel as servo pressure", "Compressed air"],
    correctOptionIndex: 1,
  },
  {
    id: 280,
    text: "When oil temperature is within nominal limits, the EEC sends a signal to:",
    options: ["Open the air-modulating valve", "Close the air-modulating valve", "Bypass the AOHE"],
    correctOptionIndex: 1,
  },
  {
    id: 281,
    text: "The anti-syphon device prevents tank drainage due to:",
    options: ["High oil pressure", "Syphoning action through the oil-out tube when engine is shut down", "Thermal expansion"],
    correctOptionIndex: 1,
  },
  {
    id: 282,
    text: "The anti-syphon device is located approximately:",
    options: ["At the bottom of the tank", "Halfway through the oil-out elbow", "In the filler neck"],
    correctOptionIndex: 1,
  },
  {
    id: 283,
    text: "On engine shutdown, when pressure in the internal duct decreases, what happens?",
    options: ["Oil continues to flow to the pump", "Air moves from the top of the tank to the oil-out elbow, un-priming the system", "A valve closes to prevent drainage"],
    correctOptionIndex: 1,
  },
  {
    id: 284,
    text: "The funnel-shaped lower end of the anti-syphon tube is protected by:",
    options: ["A filter", "A screen", "A valve"],
    correctOptionIndex: 1,
  },
  {
    id: 285,
    text: "During regular operation, pressurised oil bypassed from the aft sump supply line flows:",
    options: ["To the pressure pump inlet", "Back to the top of the tank through an internal line", "Directly to the bearings"],
    correctOptionIndex: 1,
  },
  {
    id: 286,
    text: "Chip detectors are a point of frequent inspection to detect:",
    options: ["Oil contamination", "Early signs of main bearing failure", "Filter blockage"],
    correctOptionIndex: 1,
  },
  {
    id: 287,
    text: "Small fuzzy particles or grey metallic paste on a chip detector are generally considered:",
    options: ["Sign of serious failure", "Result of normal wear", "Contamination from fuel"],
    correctOptionIndex: 1,
  },
  {
    id: 288,
    text: "Metallic chips or flakes on a chip detector indicate:",
    options: ["Normal operation", "Serious internal wear or malfunction", "Need for oil change"],
    correctOptionIndex: 1,
  },
  {
    id: 289,
    text: "A safety precaution when fitting bayonet-type MCDs is:",
    options: ["Use a torque wrench", "Ensure serviceable seals are fitted and bayonet prongs are secure", "Apply thread lock"],
    correctOptionIndex: 1,
  },
  {
    id: 290,
    text: "In an indicating magnetic chip detector, when debris bridges the gap between electrodes:",
    options: ["The pump stops", "A warning light activates in the flight deck", "The filter bypasses"],
    correctOptionIndex: 1,
  },
  {
    id: 291,
    text: "A pulsed chip detector can discriminate between:",
    options: ["Ferrous and non-ferrous particles only", "Small non-failure-related particles and larger failure-indicating particles", "Oil and water"],
    correctOptionIndex: 1,
  },
  {
    id: 292,
    text: "The pulsed chip detector is powered by:",
    options: ["Engine-driven generator", "Aircraft 28 V DC bus", "Battery backup"],
    correctOptionIndex: 1,
  },
  {
    id: 293,
    text: "In manual mode, the operator initiates a pulse to:",
    options: ["Reset the warning light", "Burn off small debris bridging the gap", "Test the circuit"],
    correctOptionIndex: 1,
  },
  {
    id: 294,
    text: "If after burn-off the warning light does not go out or repeatedly comes on, the operator should:",
    options: ["Ignore it", "Take appropriate action such as reducing power or shutting down engine", "Reset the system again"],
    correctOptionIndex: 1,
  },
  {
    id: 295,
    text: "In automatic mode, if the gap is bridged by small debris, what happens before the time-delay relay activates?",
    options: ["The warning light illuminates immediately", "A pulse of electrical energy discharges to burn off debris, preventing warning light illumination", "The engine automatically shuts down"],
    correctOptionIndex: 1,
  },
  {
    id: 296,
    text: "Which type of pump uses a rotor with sliding vanes and is considered more tolerant of debris?",
    options: ["Gerotor pump", "Vane pump", "Gear pump"],
    correctOptionIndex: 1,
  },
  {
    id: 297,
    text: "In a gerotor pump, the inter-lobe space increases from minimum to maximum volume between:",
    options: ["0° and 90°", "0° and 180°", "180° and 360°"],
    correctOptionIndex: 1,
  },
  {
    id: 298,
    text: "A gear-type pump with pressure relief valve in its housing returns unwanted oil to:",
    options: ["The tank", "The pump inlet", "The scavenge line"],
    correctOptionIndex: 1,
  },
  {
    id: 299,
    text: "Scavenge screen filters are used to catch large debris from:",
    options: ["Fuel system", "Bearings, e.g., labyrinth seal damage", "Combustion section"],
    correctOptionIndex: 1,
  },
  {
    id: 300,
    text: "A mechanical popout indicator or electrical signal for Delta P warns that:",
    options: ["Filter is clean", "Filter will imminently bypass", "Oil pressure is low"],
    correctOptionIndex: 1,
  },
  {
    id: 301,
    text: "Oil pressure transmitters provide signals for display on:",
    options: ["Engine vibration monitor", "Flight deck instruments", "Maintenance laptop"],
    correctOptionIndex: 1,
  },
  {
    id: 302,
    text: "A rotating centrifugal breather in the vent system is used to:",
    options: ["Add air to the oil", "Separate oil from air", "Increase oil pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 303,
    text: "The oil quantity transmitter is typically a:",
    options: ["Pressure sensor", "Ladder of resistors", "Thermocouple"],
    correctOptionIndex: 1,
  },
  {
    id: 304,
    text: "On some engines, the AMM specifies a minimum time (e.g., 30 minutes) after shutdown before reading oil level to:",
    options: ["Allow oil to cool", "Allow oil to drain back to the tank", "Prevent burns"],
    correctOptionIndex: 1,
  },
  {
    id: 305,
    text: "Pressure fill and overflow ports allow the tank to be filled using a pressurised cart until:",
    options: ["The tank is full", "Oil flows from the overflow port", "Pressure reaches a set value"],
    correctOptionIndex: 1,
  },
  {
    id: 306,
    text: "In a squeeze film bearing, the clearance between outer race and housing is filled with:",
    options: ["Grease", "Oil", "Air"],
    correctOptionIndex: 1,
  },
  {
    id: 307,
    text: "Heavily loaded gears (e.g., reduction gears in a turboprop) are lubricated by:",
    options: ["Splash oil", "Spray jet/pressure-fed oil", "Metered oil film"],
    correctOptionIndex: 1,
  },
  {
    id: 308,
    text: "Metered oil feed is used for bearings such as:",
    options: ["Turbine rear bearings", "Compressor front bearings (e.g., RR Spey)", "Gearbox bearings"],
    correctOptionIndex: 1,
  },
  {
    id: 309,
    text: "With perfect film lubrication, bearing surfaces should not wear except possibly:",
    options: ["At high RPM", "On starting", "During overspeed"],
    correctOptionIndex: 1,
  },
  {
    id: 310,
    text: "The oil jets are positioned to ensure oil is accurately sprayed onto bearing surfaces to:",
    options: ["Cool the housing", "Penetrate around the rolling surfaces", "Lubricate the seals"],
    correctOptionIndex: 1,
  },
  {
    id: 311,
    text: "In a hot-tank system, the oil cooler bypass valve opens if:",
    options: ["Oil temperature is high", "The cooler clogs", "Pressure is low"],
    correctOptionIndex: 1,
  },
  {
    id: 312,
    text: "In a cold-tank system, oil returns to the tank through the temperature bypass valve when:",
    options: ["Oil is too hot", "Oil is cool enough", "The cooler is blocked"],
    correctOptionIndex: 1,
  },
  {
    id: 313,
    text: "The pressure relief valve in a lubrication system returns excess oil to:",
    options: ["The oil tank", "The inlet side of the pump", "The scavenge line"],
    correctOptionIndex: 1,
  },
  {
    id: 314,
    text: "A filter bypass valve off-seats and allows unfiltered oil to flow if:",
    options: ["Oil temperature is low", "The filter clogs", "Oil pressure is high"],
    correctOptionIndex: 1,
  },
  {
    id: 315,
    text: "Individual scavenge pumps are used to ensure:",
    options: ["Oil pressure is equalised", "Each bearing is correctly emptied", "Oil is cooled evenly"],
    correctOptionIndex: 1,
  },
  {
    id: 316,
    text: "The oil reservoir in a dry sump system is usually located above the pump assembly to:",
    options: ["Reduce weight", "Enable gravity to assist oil flow", "Improve cooling"],
    correctOptionIndex: 1,
  },
  {
    id: 317,
    text: "A float valve in the gravity filler neck prevents:",
    options: ["Overfilling", "Significant oil loss if cap is not fitted correctly", "Air entering the system"],
    correctOptionIndex: 1,
  },
  {
    id: 318,
    text: "The deaeration tray separates air from returned oil. The extracted air is:",
    options: ["Recirculated to the compressor", "Either vented or regulated to maintain slight positive pressurisation", "Returned to the pump inlet"],
    correctOptionIndex: 1,
  },
  {
    id: 319,
    text: "In a full-flow system, the pressure relief valve is fitted as a safety device and:",
    options: ["Opens at low RPM", "Cannot open during regular operation", "Regulates oil temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 320,
    text: "The purpose of the air-oil heat exchanger (AOHE) is to keep oil temperature within limits when:",
    options: ["Fuel flow is high", "Fuel flow through FOHE is low (e.g., at idle)", "Oil pressure is low"],
    correctOptionIndex: 1,
  },
];
