export const easaModule102CertifyingStaffQuestions = [
  {
    id: 1,
    text: "What is Part-66 in relation to Regulation (EU) 1321/2014?",
    options: ["Annex I of the Regulation", "Annex III of the Regulation", "Annex V of the Regulation"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "What is the purpose of Part-66?",
    options: ["To define aircraft maintenance procedures", "To establish knowledge, skills, and experience requirements for certifying staff", "To regulate air operator certificates"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "Which regulation contains the current amendment to Part-66 with effective date 12 June 2024?",
    options: ["Regulation (EU) 2020/1150", "Regulation (EU) 2023/989", "Regulation (EU) 2019/1383"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "What must a person hold to issue a Certificate of Release to Service (CRS)?",
    options: ["A Part-145 approval only", "A Part-66 Basic license with aircraft type/task endorsement", "A university degree in engineering"],
    correctOptionIndex: 1,
  },
  {
    id: 5,
    text: "What is the definition of \"maintenance\" according to Part-66?",
    options: ["Only major repairs and modifications", "Overhaul, repair, inspection, replacement, modification, or defect rectification except pre-flight inspection", "Only scheduled inspections"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "What is specifically excluded from the definition of maintenance?",
    options: ["Component replacement", "Pre-flight inspection", "Defect rectification"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "What does \"component\" mean in Part-66 terminology?",
    options: ["Only engines and propellers", "Any engine, propeller, part, or appliance", "Only structural parts"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "What is Commercial Air Transport (CAT)?",
    options: ["Any private flying activity", "Transport of passengers, cargo, or mail for remuneration or other valuable consideration", "Training flights only"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "What is the maximum take-off mass for an ELA1 aeroplane?",
    options: ["600 kg", "1,200 kg", "2,000 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "What is the maximum take-off mass for an ELA2 aeroplane?",
    options: ["1,200 kg", "2,000 kg", "2,730 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "What is the maximum take-off mass for an ELA2 very light rotorcraft?",
    options: ["600 kg", "1,200 kg", "2,000 kg"],
    correctOptionIndex: 0,
  },
  {
    id: 12,
    text: "What is the maximum hot air balloon volume for ELA1 classification?",
    options: ["1,050 m³", "3,400 m³", "5,000 m³"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "What is the maximum gas balloon volume for ELA1 classification?",
    options: ["300 m³", "1,050 m³", "3,400 m³"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "What is the maximum take-off mass for a Light Sport Aeroplane (LSA)?",
    options: ["450 kg", "600 kg", "750 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "What is the maximum stalling speed for an LSA aircraft?",
    options: ["35 knots CAS", "45 knots CAS", "55 knots CAS"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "What is the maximum seating capacity for an LSA aircraft?",
    options: ["One person", "Two persons including the pilot", "Four persons"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "What is the maximum take-off mass threshold for an aeroplane to be classified as complex?",
    options: ["3,175 kg", "5,700 kg", "12,500 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "What passenger seating configuration defines a complex aeroplane?",
    options: ["More than 9 passengers", "More than 12 passengers", "More than 19 passengers"],
    correctOptionIndex: 2,
  },
  {
    id: 19,
    text: "What is the maximum take-off mass threshold for a complex helicopter?",
    options: ["2,730 kg", "3,175 kg", "5,700 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "What passenger seating configuration defines a complex helicopter?",
    options: ["More than 4 passengers", "More than 9 passengers", "More than 12 passengers"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "Which of the following is always classified as a complex motor-powered aircraft?",
    options: ["Single-engine piston aircraft", "Tilt-rotor aircraft", "Sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "What is line maintenance?",
    options: ["Any maintenance carried out in a hangar", "Any maintenance carried out before flight to ensure the aircraft is fit for the intended flight", "Major structural repairs"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "Which of the following is NOT typically considered line maintenance?",
    options: ["Troubleshooting", "Component replacement", "Extensive structural disassembly"],
    correctOptionIndex: 2,
  },
  {
    id: 24,
    text: "Under what condition can base maintenance tasks be performed by a line maintenance organization?",
    options: ["Never", "For temporary or occasional cases when accepted by the quality manager", "Only for single-engine aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "Base maintenance is defined as:",
    options: ["Maintenance carried out at the main base only", "Any maintenance tasks falling outside the line maintenance criteria", "Only C and D checks"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "What does an electrical system include according to Part-66?",
    options: ["Only the power supply source", "Power supply source, distribution system, and relevant connectors", "Only wiring and cables"],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "What is an avionics system?",
    options: ["Any electrical system in the aircraft", "A system that transfers, processes, displays, or stores analogue or digital data", "Only communication radios"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "Which of the following is an example of an avionics system?",
    options: ["Landing gear", "Autoflight", "Hydraulic pumps"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "What is a simple test?",
    options: ["Any test using BITE", "A test described in approved maintenance data with Go No-Go indication and not more than 10 actions", "A test requiring specialized training"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "How many actions maximum can a simple test involve?",
    options: ["5 actions", "10 actions", "15 actions"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "Does a simple test include configuring the aircraft before the test?",
    options: ["Yes, all actions count", "No, configuring the aircraft is not included in the 10 actions", "Only if specified in the manual"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "What is troubleshooting?",
    options: ["Replacing components until the defect is fixed", "Procedures and actions to identify the root cause of a defect using approved maintenance data", "Only visual inspections"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "May troubleshooting include the use of BITE?",
    options: ["No, BITE is only for flight crew", "Yes, it may include BITE or external test equipment", "Only if approved by the manufacturer"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "Who may carry out a repetitive pre-flight airworthiness directive if specifically stated?",
    options: ["Any licensed engineer", "The flight crew", "The quality manager"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "When an aircraft is grounded away from base with no appropriate certifying staff, who may be authorized with at least 3 years experience?",
    options: ["Any person with a driver's license", "Any person with a valid ICAO aircraft maintenance license rated for the aircraft type", "The aircraft owner only"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "What is the maximum take-off mass for aircraft eligible for pilot-owner maintenance?",
    options: ["Any aircraft regardless of mass", "Complex motor-powered aircraft only", "2,730 kg MTOM and below, not used in CAT operations"],
    correctOptionIndex: 2,
  },
  {
    id: 37,
    text: "What is the minimum age to apply for a Part-66 licence?",
    options: ["16 years", "18 years", "21 years"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "What is the minimum age to certify maintenance with a licence according to 145.A.35?",
    options: ["18 years", "21 years", "25 years"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "Can examinations and experience be gained before reaching the minimum age for licence application?",
    options: ["No, all requirements must be met after age 18", "Yes, experience and examinations can be gained before this age", "Only examinations can be taken before age 18"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "Within what time must personnel provide their license when requested by authorized personnel?",
    options: ["Immediately", "Within 24 hours", "Within 7 days"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "What is the Category A licence designation for?",
    options: ["Base Maintenance Certifying Technician", "Line Maintenance Certifying Mechanic", "Base Maintenance Certifying Engineer"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "What is the Category B1 licence designation for?",
    options: ["Line Maintenance Certifying Mechanic", "Base Maintenance Certifying Technician (Mechanical)", "Base Maintenance Certifying Engineer"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "What is the Category B2 licence designation for?",
    options: ["Light aircraft mechanical technician", "Base Maintenance Certifying Technician (Avionic)", "Line maintenance mechanic"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "What is the Category B3 licence designation for?",
    options: ["Complex aircraft technician", "Maintenance Certifying Technician (Light Aircraft)", "Avionic technician"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "What is the Category C licence designation for?",
    options: ["Line Maintenance Certifying Mechanic", "Base Maintenance Certifying Engineer", "Light aircraft technician"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "What is the B2L licence for?",
    options: ["Complex aircraft avionics", "Light aircraft avionics", "Helicopter avionics"],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "What is the Category L licence for?",
    options: ["Large aircraft", "Sailplanes, balloons, and airships", "Light jets"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "What is subcategory A1?",
    options: ["Aeroplanes - Piston", "Aeroplanes - Turbine", "Helicopters - Turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "What is subcategory A2?",
    options: ["Aeroplanes - Piston", "Helicopters - Piston", "Aeroplanes - Turbine"],
    correctOptionIndex: 0,
  },
  {
    id: 50,
    text: "What is subcategory A3?",
    options: ["Aeroplanes - Turbine", "Helicopters - Piston", "Helicopters - Turbine"],
    correctOptionIndex: 2,
  },
  {
    id: 51,
    text: "What is subcategory A4?",
    options: ["Aeroplanes - Piston", "Helicopters - Piston", "Helicopters - Turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "What is subcategory B1.1?",
    options: ["Aeroplanes - Piston", "Aeroplanes - Turbine", "Helicopters - Turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "What is subcategory B1.2?",
    options: ["Aeroplanes - Piston", "Helicopters - Piston", "Aeroplanes - Turbine"],
    correctOptionIndex: 0,
  },
  {
    id: 54,
    text: "What is subcategory B1.3?",
    options: ["Aeroplanes - Turbine", "Helicopters - Turbine", "Helicopters - Piston"],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "What is subcategory B1.4?",
    options: ["Aeroplanes - Piston", "Helicopters - Piston", "Aeroplanes - Turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "What is subcategory L1 for?",
    options: ["Hot-air balloons", "Sailplanes", "Gas airships"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "What is subcategory L1C for?",
    options: ["Metal sailplanes", "Composite sailplanes", "Wooden sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "What is subcategory L2 for?",
    options: ["Sailplanes only", "Powered sailplanes and ELA1 aeroplanes", "Hot-air balloons"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "What is subcategory L2C for?",
    options: ["Composite powered sailplanes and composite ELA1 aeroplanes", "Metal powered sailplanes", "Hot-air airships"],
    correctOptionIndex: 0,
  },
  {
    id: 60,
    text: "What is subcategory L3H for?",
    options: ["Gas balloons", "Hot-air balloons", "Sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "What is subcategory L3G for?",
    options: ["Hot-air balloons", "Gas balloons", "Airships"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "What is subcategory L4H for?",
    options: ["Gas balloons", "Hot-air airships", "Sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "What is subcategory L4G for?",
    options: ["Hot-air airships", "ELA2 gas airships", "Gas balloons"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "What is subcategory L5 for?",
    options: ["Hot-air balloons", "Gas airships other than ELA2", "Composite sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "Which aircraft are classified as Group 1?",
    options: ["Piston engine aeroplanes only", "Complex motor-powered aircraft, multi-engine helicopters, aircraft above FL290, and fly-by-wire aircraft", "Sailplanes and balloons"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "What is Subgroup 2a?",
    options: ["Single-piston helicopters", "Single turbopropeller aeroplanes", "Multi-engine helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "What is Subgroup 2b?",
    options: ["Single-turbine engine helicopters", "Single-piston helicopters", "Multi-engine helicopters"],
    correctOptionIndex: 0,
  },
  {
    id: 68,
    text: "What is Subgroup 2c?",
    options: ["Single-turbine helicopters", "Single-piston engine helicopters", "Multi-engine helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "What is Group 3?",
    options: ["Turboprop aeroplanes", "Piston-engine aeroplanes other than those in Group 1", "Helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "What is Group 4?",
    options: ["Complex motor-powered aircraft", "Sailplanes, powered sailplanes, balloons, and airships other than Group 1", "Piston-engine aeroplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "What can a Category A licence holder certify?",
    options: ["Base maintenance on all aircraft systems", "Minor scheduled line maintenance and simple defect rectification tasks personally performed", "Major modifications"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "Where must a Category A licence holder perform maintenance to exercise certification privileges?",
    options: ["Any location worldwide", "Within a Part-145, Part-ML, or Part-CAO organization", "Only at the main base"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "What can a Category B1 licence holder certify?",
    options: ["Only avionics systems", "Maintenance on aircraft structure, powerplant, mechanical and electrical systems", "Only line maintenance"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "What is the extent of B1 privileges regarding avionics systems?",
    options: ["Full avionics troubleshooting", "Work requiring only simple tests to prove serviceability, not troubleshooting", "No avionics work at all"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "Does Category B1 include compass compensation and adjustment?",
    options: ["No, that requires a separate license", "Yes, compass compensation and adjustment are within B1 privileges", "Only for B2 license holders"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "Does Category B1 include the corresponding Category A subcategory?",
    options: ["No, they are separate", "Yes, Category B1 includes the corresponding Category A subcategory", "Only for turbine aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "What can a Category B2 licence holder certify?",
    options: ["Mechanical systems only", "Maintenance on avionic and electrical systems", "Structure and powerplant"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "Can a B2 licence holder perform electrical and avionics tasks within powerplant and mechanical systems?",
    options: ["No, never", "Yes, if requiring only simple tests to prove serviceability", "Only after additional mechanical training"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "Does Category B2 automatically include any Category A privileges?",
    options: ["Yes, it includes A license privileges", "No, it does not automatically include any Category A privileges", "Only for piston aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "Does Category B2 include compass compensation and adjustment?",
    options: ["No", "Yes, compass compensation and adjustment are within Category B2 licence", "Only when combined with B1"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "What system ratings can a B2L licence include?",
    options: ["Only communication/navigation", "Communication/navigation, instruments, autoflight, surveillance, and airframe systems", "Only airframe systems"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "What is the minimum requirement for a B2L licence?",
    options: ["All five system ratings", "At least one system rating", "At least three system ratings"],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "When holding the \"airframe system\" rating, what additional tasks can a B2L holder perform?",
    options: ["Full mechanical repairs", "Electrical and avionics tasks within powerplant and mechanical systems requiring simple tests", "Structural repairs"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "What happens when a person holds a B2 license with specific aircraft ratings regarding B2L?",
    options: ["They must apply separately for B2L", "They automatically have B2L privileges for all system ratings for the same aircraft ratings", "They cannot hold both licenses"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "What aircraft can a Category B3 licence holder certify?",
    options: ["All aircraft types", "Piston engine non-pressurised aircraft less than 2,000 kg MTOM", "Turbine aircraft under 2,000 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "Does B3 allow avionic troubleshooting?",
    options: ["Yes, full avionic troubleshooting", "No, it does not allow avionic troubleshooting", "Only for communication systems"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "Does B3 include any subcategory of Category A?",
    options: ["Yes, all A subcategories", "No, B3 does not include any subcategory of Category A", "Only A2"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "Can a B3 holder apply for L1 and L2 subcategory licenses?",
    options: ["No, never", "Yes, holders of B1.2 or B3 with appropriate ratings can apply for L1 and L2", "Only after additional examinations"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "What can a Category C licence holder certify?",
    options: ["Line maintenance only", "Base maintenance of the entire aircraft with a single certificate of release to service", "Only component maintenance"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "Who acts as support staff for Category C during base maintenance?",
    options: ["Only unlicensed mechanics", "Category B1, B2, and B3 personnel", "The quality manager"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "Can Category C personnel with Category B1 or B2 qualifications perform both roles?",
    options: ["No, they must choose one role", "Yes, they may perform both roles in base maintenance", "Only if approved by EASA"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "What must Category C certifying staff verify before issuing a CRS?",
    options: ["That all invoices are paid", "That all necessary maintenance tasks have been completed and approved by B1 and B2 staff", "That the aircraft is clean"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "What can a Category L licence holder certify?",
    options: ["All aircraft types", "Maintenance on aircraft structure, powerplant, mechanical and electrical systems, plus ELT and transponder systems", "Only avionics systems"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "What avionics work can Category L holders perform?",
    options: ["Full avionics troubleshooting", "Work on ELT and transponder systems, plus other avionics requiring simple tests", "No avionics work"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "Which subcategory includes L1?",
    options: ["L2 includes L1", "L3 includes L1", "L4 includes L1"],
    correctOptionIndex: 0,
  },
  {
    id: 96,
    text: "What is required to maintain mixed balloons (gas and hot air)?",
    options: ["Only L3G license", "Only L3H license", "Both L3G and L3H subcategories"],
    correctOptionIndex: 2,
  },
  {
    id: 97,
    text: "What is the recency requirement for exercising certification privileges?",
    options: ["3 months experience in the last year", "6 months maintenance experience in the preceding two-year period", "12 months experience in the last 5 years"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "What language proficiency must certifying staff have?",
    options: ["Only the local language", "Read, write, and communicate in the language of technical documentation", "Fluency in three languages"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "When must certifying staff NOT exercise certification privileges?",
    options: ["When on vacation", "If they know or suspect their physical or mental condition renders them unfit", "Only when formally suspended"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "Within what time must all modules be passed after passing the first module?",
    options: ["5 years", "10 years", "No time limit"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "Where can examinations be taken?",
    options: ["Only at EASA headquarters", "At EASA competent authorities or approved Part-147 training organizations", "Only at approved airlines"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "Is it necessary to have studied at a Part-147 organization to sit exams there?",
    options: ["Yes, mandatory", "No, it is not necessary", "Only for type ratings"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "What is EASA Form 148?",
    options: ["The aircraft maintenance license", "Certificate of recognition for Module exams passed", "The application form"],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "Who is deemed to meet Category L basic knowledge requirements if holding B1.2 or B3?",
    options: ["No exemption", "The holder is deemed to meet L1C, L1, L2C, and L2 requirements", "Only L1 requirements"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "How many essay questions are required in Module 7?",
    options: ["1 essay", "2 essays", "3 essays"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "How many essay questions are required in Module 9?",
    options: ["1 essay", "2 essays", "No essays"],
    correctOptionIndex: 0,
  },
  {
    id: 107,
    text: "How many essay questions are required in Module 10?",
    options: ["1 essay", "2 essays", "3 essays"],
    correctOptionIndex: 0,
  },
  {
    id: 108,
    text: "What is the time allowed per multiple-choice question?",
    options: ["60 seconds", "75 seconds", "90 seconds"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "What is the time allowed for essay questions?",
    options: ["10 minutes", "20 minutes", "30 minutes"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "What is the passing mark for examinations?",
    options: ["70%", "75%", "80%"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "Is there a penalty for incorrect answers?",
    options: ["Yes, points are deducted", "No, there is no penalty", "Only for essay questions"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "What is the definition of a \"skilled worker\"?",
    options: ["Anyone with 5 years experience", "Person with training acceptable to competent authority involving manufacturing, repairing, overhauling or inspecting mechanical, electrical or electronic equipment", "University graduate"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "What percentage of recent experience must be gained within the last 12 months?",
    options: ["25%", "50%", "75%"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "Within what period must the other 50% of experience be acquired?",
    options: ["Within the last 3 years", "Within the last 7 years", "Within the last 10 years"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "What is the experience requirement for Category A with no previous technical training?",
    options: ["1 year", "2 years", "3 years"],
    correctOptionIndex: 2,
  },
  {
    id: 116,
    text: "What is the experience requirement for Category A with relevant skilled worker training?",
    options: ["1 year", "2 years", "3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "What is the experience requirement for Category A with Part-147 basic training?",
    options: ["6 months", "1 year", "2 years"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "What experience is required for the B1/B2 route to Category C on large aircraft?",
    options: ["1 year as certifying technician", "3 years as B1.1, B1.3, or B2 certifying technician", "5 years as B1.2"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "What experience is required for the graduate route to Category C?",
    options: ["1 year experience", "3 years experience including 6 months observation of base maintenance", "5 years experience"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "Can a person qualified through the graduate route automatically get a B1 license?",
    options: ["Yes, immediately", "No, they must meet B1 requirements independently", "After 1 year of experience"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "What is the minimum additional experience required for licence extension?",
    options: ["Always 1 year", "At least 3 months", "At least 6 months"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "By what percentage can experience be reduced if the applicant completed a relevant Part-147 course?",
    options: ["25%", "50%", "75%"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "Does Category A licence include type ratings?",
    options: ["Yes, for all aircraft", "No, Category A does not include type ratings", "Only for turbine aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "What is required for Group 1 aircraft type rating?",
    options: ["Total group rating", "Appropriate aircraft type rating", "Manufacturer subgroup rating only"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "What rating applies to Category B3?",
    options: ["All aircraft under 2,000 kg", "Piston-engine non-pressurised aeroplanes of 2,000 kg MTOM and below", "All light aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "Who carries out type training?",
    options: ["Any maintenance organization", "Part-147 training organization approved by competent authority", "The aircraft manufacturer only"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "Is practical training required for Category C type training?",
    options: ["Yes, full practical training", "No, no requirement for practical training for Category C", "Only for first type rating"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "Does B3 require a specific aircraft-type course for endorsement?",
    options: ["Yes, for each aircraft type", "No, B3 type endorsement does not require a specific aircraft-type course", "Only for pressurized aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "What is required for obtaining the first aircraft type rating?",
    options: ["Only theoretical training", "Successful completion of corresponding on-the-job training (OJT)", "No additional requirements"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "What is generally considered acceptable experience duration for aircraft rating?",
    options: ["2 weeks", "4 months", "1 year"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "What is the minimum experience that may be accepted if the applicant already holds a similar type?",
    options: ["1 week", "2 weeks", "1 month"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "What does Part-147 govern?",
    options: ["Maintenance organizations", "Maintenance training organization approval", "Certifying staff licensing"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "How often must new essay questions be raised?",
    options: ["Every 3 months", "Every 6 months", "Every year"],
    correctOptionIndex: 1,
  },
  {
    id: 134,
    text: "To whom must initial Part-66 licence application be made?",
    options: ["EASA directly", "Any EASA competent authority member state", "ICAO"],
    correctOptionIndex: 1,
  },
  {
    id: 135,
    text: "Can a person hold Part-66 licences from two different EASA member states?",
    options: ["Yes, multiple licences are allowed", "No, a holder cannot hold a licence issued by another member state", "Only with special permission"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "What form is used to apply for a Part-66 licence?",
    options: ["EASA Form 1", "EASA Form 19", "EASA Form 26"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "What is EASA Form 26?",
    options: ["The application form", "The aircraft maintenance licence booklet", "The examination certificate"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "After how many years does a Part-66 licence become invalid if not submitted for verification?",
    options: ["3 years", "5 years", "10 years"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "What language must the licence contain for use in other member states?",
    options: ["Only the national language", "English translation must be attached", "French translation"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "Is the Part-66 licence recognized in all EU member states?",
    options: ["No, only in the issuing state", "Yes, it is recognized in all EU member states", "Only in Schengen countries"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "Who is ultimately responsible for issuing the aircraft maintenance licence?",
    options: ["The Part-145 organization", "The competent authority of the member state", "EASA"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "What does the \"communication/navigation\" system rating cover?",
    options: ["Only communication radios", "Com/nav systems including related components", "Only navigation systems"],
    correctOptionIndex: 1,
  },
  {
    id: 143,
    text: "What does the \"instruments\" system rating cover?",
    options: ["Only flight instruments", "Instruments including electromechanical and pitot-static components", "Only engine instruments"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "What does the \"autoflight\" system rating cover?",
    options: ["Only autopilot", "Autoflight systems including autopilot, flight directors, and automatic throttle systems", "Only flight directors"],
    correctOptionIndex: 1,
  },
  {
    id: 145,
    text: "What limitations may apply to Group 3 rating for B1 if no evidence of appropriate experience?",
    options: ["No limitations", "Pressurised, metal-structure, composite-structure, wooden-structure, and fabric-covered limitations", "Only turbine engine limitation"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "What limitations may apply to B3 rating if no evidence of appropriate experience?",
    options: ["No limitations", "Wooden-structure, metal-tubing with fabric, metal-structure, and composite-structure limitations", "Only weight limitations"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "For L1 and L2 ratings, what limitations apply if no evidence of appropriate experience?",
    options: ["No limitations", "Wooden-structure with fabric, metal-tubing with fabric, metal-structure, and composite-structure limitations", "Only weight limitations"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "What is the role of support staff during base maintenance?",
    options: ["To supervise the work", "To certify tasks as B1, B2, or B3 personnel before Category C certifies the entire aircraft", "To order parts"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "Can licensed staff without certification privileges still be considered support staff?",
    options: ["No, they must have privileges", "Yes, they are considered support staff", "Only if they have type ratings"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "What does the term \"powered sailplane\" include?",
    options: ["Only self-launching sailplanes", "Self-launching sailplanes, self-sustaining sailplanes, and touring motor gliders (TMGs)", "Only touring motor gliders"],
    correctOptionIndex: 1,
  },
];
