export const electricalPowerQuestions = [
  { id: 1, text: "Direct current (DC) remains at what type of voltage level?", options: ["Varying", "Constant", "Pulsating"], correctOptionIndex: 1 },
  { id: 2, text: "What type of batteries always supply DC?", options: ["Only lead-acid batteries", "All batteries", "Only nickel-cadmium batteries"], correctOptionIndex: 1 },
  { id: 3, text: "What device converts AC to DC?", options: ["Inverter", "Transformer rectifier unit (TRU)", "Generator"], correctOptionIndex: 1 },
  { id: 4, text: "What is the usual waveform of an AC power circuit?", options: ["Square wave", "Sine wave", "Triangular wave"], correctOptionIndex: 1 },
  { id: 5, text: "What device converts DC to AC?", options: ["Rectifier", "Inverter", "Transformer"], correctOptionIndex: 1 },
  { id: 6, text: "Small turboprop aircraft usually have what type of electrical systems?", options: ["115 V AC", "28 V DC", "200 V AC"], correctOptionIndex: 1 },
  { id: 7, text: "Large transport aircraft systems generally use what voltages?", options: ["28 V DC and 115 V AC", "115 V and 200 V AC", "14 V DC and 28 V DC"], correctOptionIndex: 1 },
  { id: 8, text: "The frequency of AC power in large transport aircraft is held constant at what value?", options: ["60 Hz", "400 Hz (±5%)", "50 Hz"], correctOptionIndex: 1 },
  { id: 9, text: "Some instrument systems use what AC voltage?", options: ["115 V AC", "26 V AC", "200 V AC"], correctOptionIndex: 1 },
  { id: 10, text: "In a single-phase AC power system, when does voltage peak?", options: ["At 45° and 135°", "At 90° and 270°", "At 0° and 180°"], correctOptionIndex: 1 },
  { id: 11, text: "A complete cycle in a single-phase system occurs at what angle?", options: ["180°", "360°", "90°"], correctOptionIndex: 1 },
  { id: 12, text: "In a three-phase system, how many power wires are there?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 13, text: "In a three-phase system, each phase is how many degrees out of phase with each other?", options: ["90°", "120°", "180°"], correctOptionIndex: 1 },
  { id: 14, text: "By what angle have all three phases of power entered the cycle?", options: ["90°", "120°", "180°"], correctOptionIndex: 1 },
  { id: 15, text: "In a three-phase system, how many times has each phase peaked in voltage by the time a complete 360° cycle has completed?", options: ["Once", "Twice", "Three times"], correctOptionIndex: 1 },
  { id: 16, text: "Each phase in a three-phase aircraft system is how many volts?", options: ["28 V", "115 V", "200 V"], correctOptionIndex: 1 },
  { id: 17, text: "Using any two phases in a three-phase system can achieve what combined voltage?", options: ["115 V", "208 V", "230 V"], correctOptionIndex: 1 },
  { id: 18, text: "What are the three sources of electrical power on aeroplanes?", options: ["Generator, alternator, battery", "Battery, ground power, generator", "APU, GPU, RAT"], correctOptionIndex: 1 },
  { id: 19, text: "Ground power is supplied from what unit?", options: ["APU", "Ground power unit (GPU)", "Battery cart"], correctOptionIndex: 1 },
  { id: 20, text: "The use of ground power is preferred when?", options: ["During flight", "When the aeroplane's generator is not operating, especially during engine starting", "Only for maintenance"], correctOptionIndex: 1 },
  { id: 21, text: "What is a 'starter-generator'?", options: ["A generator that also charges the battery", "A unit that operates as a starter motor and then switches to operate as a generator", "A separate starter motor and generator combined"], correctOptionIndex: 1 },
  { id: 22, text: "What is the open-circuit voltage of carbon-zinc cells?", options: ["1.2 V", "1.5 V", "2.1 V"], correctOptionIndex: 1 },
  { id: 23, text: "What determines the amount of current a cell can produce?", options: ["Voltage rating", "Amount of active ingredients in the cell", "Cell size only"], correctOptionIndex: 1 },
  { id: 24, text: "Alkaline-manganese cells have what open circuit voltage?", options: ["1.2 V", "1.5 V", "1.4 V"], correctOptionIndex: 1 },
  { id: 25, text: "Mercury cells have what open-circuit voltage?", options: ["1.5 V", "1.4 V", "1.55 V"], correctOptionIndex: 1 },
  { id: 26, text: "What is an important characteristic of mercury cells?", options: ["Voltage drops steadily", "Voltage remains almost constant until cell is practically used up", "Voltage increases with discharge"], correctOptionIndex: 1 },
  { id: 27, text: "Silver oxide cells have what open-circuit voltage?", options: ["1.4 V", "1.55 V", "1.5 V"], correctOptionIndex: 1 },
  { id: 28, text: "Lithium cells have an open-circuit voltage between what values?", options: ["1.5 and 2.0 V", "2.8 and 3.6 V", "3.6 and 4.2 V"], correctOptionIndex: 1 },
  { id: 29, text: "In a secondary cell, the electrochemical action is what?", options: ["Non-reversible", "Reversible", "Permanent"], correctOptionIndex: 1 },
  { id: 30, text: "The two most commonly used secondary cells are what?", options: ["Carbon-zinc and alkaline-manganese", "Lead-acid and sintered-plate nickel-cadmium", "Mercury and silver oxide"], correctOptionIndex: 1 },
  { id: 31, text: "The electrolyte in lead-acid batteries is a mixture of what?", options: ["Potassium hydroxide and water", "Sulphuric acid and water", "Hydrochloric acid and water"], correctOptionIndex: 1 },
  { id: 32, text: "When a lead-acid cell is fully charged, the specific gravity of the electrolyte is around what?", options: ["1.150", "1.285", "1.000"], correctOptionIndex: 1 },
  { id: 33, text: "When a lead-acid cell is completely discharged, the specific gravity drops to approximately what?", options: ["1.285", "1.150", "1.000"], correctOptionIndex: 1 },
  { id: 34, text: "NiCad stands for what?", options: ["Nickel-Cadmium", "Nickel-Cadmium", "Nickel-Calcium"], correctOptionIndex: 1 },
  { id: 35, text: "NiCad batteries in long-term storage are typically stored how?", options: ["Fully charged", "Fully discharged", "Partially charged"], correctOptionIndex: 1 },
  { id: 36, text: "Compared to lead-acid batteries, NiCad batteries have what advantage?", options: ["Lower cost", "Much higher energy density, smaller and lighter", "Simpler charging circuit"], correctOptionIndex: 1 },
  { id: 37, text: "CAP 747 requires that in the event of total failure of the main electrical generating system, an adequate supply must be available for a minimum period of how long?", options: ["15 minutes", "30 minutes", "60 minutes"], correctOptionIndex: 1 },
  { id: 38, text: "Lead-acid cells have an open-circuit voltage of about how many volts?", options: ["1.5 V", "2.1 V", "1.2 V"], correctOptionIndex: 1 },
  { id: 39, text: "The positive plates in a lead-acid cell are packed with what material?", options: ["Spongy lead (Pb)", "Lead peroxide (PbO₂)", "Lead sulphate (PbSO₄)"], correctOptionIndex: 1 },
  { id: 40, text: "The negative plates in a lead-acid cell are packed with what material?", options: ["Lead peroxide (PbO₂)", "Pure spongy lead (Pb)", "Lead sulphate (PbSO₄)"], correctOptionIndex: 1 },
  { id: 41, text: "When discharging a lead-acid cell, both plates are converted to what?", options: ["Lead peroxide", "Lead sulphate (PbSO₄)", "Spongy lead"], correctOptionIndex: 1 },
  { id: 42, text: "What gas is released during the charging process of a lead-acid cell?", options: ["Nitrogen and oxygen", "Hydrogen and oxygen", "Carbon dioxide"], correctOptionIndex: 1 },
  { id: 43, text: "The constant stream of bubbles at the end of charge is known as what?", options: ["Boiling", "Gassing", "Venting"], correctOptionIndex: 1 },
  { id: 44, text: "A typical aircraft lead-acid battery consists of how many cells to give 24 V nominal?", options: ["20 cells", "12 cells", "24 cells"], correctOptionIndex: 1 },
  { id: 45, text: "RE technology in sealed lead-acid batteries stands for what?", options: ["Rapid Electrolyte", "Recombination Electrolyte", "Regulated Energy"], correctOptionIndex: 1 },
  { id: 46, text: "One major difference between lead-acid and NiCad batteries is what?", options: ["NiCad cells cannot be replaced individually", "Defective NiCad cells can be changed independently; defective lead-acid cells require whole battery replacement", "Lead-acid cells can be changed independently"], correctOptionIndex: 1 },
  { id: 47, text: "The positive plates in a NiCad cell contain what material?", options: ["Cadmium hydroxide", "Nickel hydroxide Ni(OH)₂", "Potassium hydroxide"], correctOptionIndex: 1 },
  { id: 48, text: "The negative plates in a NiCad cell contain what material?", options: ["Nickel hydroxide", "Cadmium hydroxide Cd(OH)₂", "Nickel oxide"], correctOptionIndex: 1 },
  { id: 49, text: "The electrolyte in a NiCad cell is a solution of what?", options: ["Sulphuric acid and water", "Potassium hydroxide and distilled water", "Hydrochloric acid and water"], correctOptionIndex: 1 },
  { id: 50, text: "NiCad cell vents typically open at what pressure?", options: ["1-2 psi", "6 ± 4 psi", "10-15 psi"], correctOptionIndex: 1 },
  { id: 51, text: "During charging of a NiCad cell, what gas is evolved at the negative plates?", options: ["Oxygen", "Hydrogen", "Nitrogen"], correctOptionIndex: 1 },
  { id: 52, text: "During charging of a NiCad cell, what gas is evolved at the positive plates?", options: ["Hydrogen", "Oxygen", "Carbon dioxide"], correctOptionIndex: 1 },
  { id: 53, text: "The electrolyte in a NiCad cell does what during charge/discharge?", options: ["Changes specific gravity", "Does not play an active part in chemical reaction; specific gravity does not change", "Becomes more concentrated"], correctOptionIndex: 1 },
  { id: 54, text: "A fully discharged NiCad cell voltage is what?", options: ["1.2 V", "1.0 V", "1.5 V"], correctOptionIndex: 1 },
  { id: 55, text: "Nominal voltage of a NiCad cell is what?", options: ["1.0 V", "1.2 V", "1.5 V"], correctOptionIndex: 1 },
  { id: 56, text: "A fully charged NiCad cell voltage is what?", options: ["1.2 V", "1.5 V", "1.8 V"], correctOptionIndex: 1 },
  { id: 57, text: "Thermal runaway in a NiCad battery is caused by what condition?", options: ["Low charging rate", "Excessively high charging rate causing overheating and lower internal resistance", "Cold temperatures"], correctOptionIndex: 1 },
  { id: 58, text: "Cell memory in NiCad batteries causes what problem?", options: ["Complete failure", "Loss of capacity if repeatedly discharged and charged to only a small percentage of capacity", "Overheating"], correctOptionIndex: 1 },
  { id: 59, text: "Deep cycling a NiCad cell means what?", options: ["Charging at low rate", "Completely discharging then overcharging to approximately 140% of rated capacity", "Discharging partially only"], correctOptionIndex: 1 },
  { id: 60, text: "In a NiCad battery, when is the electrolyte level lowest?", options: ["When fully charged", "When fully discharged", "At nominal voltage"], correctOptionIndex: 1 },
  { id: 61, text: "A NiCad battery has how many cells to give a nominal voltage of 24 V?", options: ["12 cells", "20 cells", "24 cells"], correctOptionIndex: 1 },
  { id: 62, text: "Battery capacity is measured in what units?", options: ["Volts", "Ampere-hours", "Watts"], correctOptionIndex: 1 },
  { id: 63, text: "A battery rated at 20 Ah at the 5-hour rate will deliver what?", options: ["20 amps for 1 hour", "4 amps for 5 hours", "5 amps for 4 hours"], correctOptionIndex: 1 },
  { id: 64, text: "Most aircraft batteries are rated at what rate?", options: ["5-hour rate", "1-hour rate", "10-hour rate"], correctOptionIndex: 1 },
  { id: 65, text: "For a lead-acid battery, the discharged voltage value is what?", options: ["20 V (1 V/cell)", "21.6 V (1.8 V/cell)", "24 V (2.0 V/cell)"], correctOptionIndex: 1 },
  { id: 66, text: "For a NiCad battery, the discharged voltage value is what?", options: ["21.6 V (1.8 V/cell)", "20 V (1 V/cell)", "24 V (1.2 V/cell)"], correctOptionIndex: 1 },
  { id: 67, text: "Generally, the minimum acceptable capacity for aircraft use is what percentage?", options: ["100%", "80%", "50%"], correctOptionIndex: 1 },
  { id: 68, text: "In cell balance test for NiCads, each cell is shorted out with what resistor?", options: ["10 Ω, 10-watt", "1 Ω, 2-watt", "100 Ω, 1-watt"], correctOptionIndex: 1 },
  { id: 69, text: "In cell balance test, each cell voltage should be less than what after 15-24 hours?", options: ["100 mV", "50 mV", "10 mV"], correctOptionIndex: 1 },
  { id: 70, text: "Minimum acceptable insulation resistance for lead-acid battery is what?", options: ["10 MΩ", "1 MΩ", "100 kΩ"], correctOptionIndex: 1 },
  { id: 71, text: "Minimum acceptable insulation resistance for NiCad battery with steel case is what?", options: ["1 MΩ", "10 MΩ", "100 MΩ"], correctOptionIndex: 1 },
  { id: 72, text: "Cell vent pressure test for lead-acid cells: pressurise to how much?", options: ["1 psi", "2 psi", "5 psi"], correctOptionIndex: 1 },
  { id: 73, text: "NiCad cell vents typically open between what pressures?", options: ["1-5 psi", "2-10 psi", "10-20 psi"], correctOptionIndex: 1 },
  { id: 74, text: "Thermal runaway can be initiated by what combination of factors?", options: ["Low busbar voltage, cold temperature", "High busbar voltage, excessive ambient temperature, inability to dissipate heat", "Low charging current"], correctOptionIndex: 1 },
  { id: 75, text: "Most modern systems have what to prevent thermal runaway?", options: ["Low voltage disconnect", "Temperature monitoring system", "Current limiter"], correctOptionIndex: 1 },
  { id: 76, text: "The high overcharge current causes heat generation rate that is greater than what?", options: ["Charging rate", "Heat dissipation rate", "Current flow"], correctOptionIndex: 1 },
  { id: 77, text: "Batteries are normally mounted and clamped to what?", options: ["Directly to structure", "A tray secured to aircraft structure", "The floor"], correctOptionIndex: 1 },
  { id: 78, text: "Gases generated by the battery are usually vented where?", options: ["Into the cockpit", "To atmosphere via holes in fuselage", "Into the cabin"], correctOptionIndex: 1 },
  { id: 79, text: "Acid traps contain what to prevent acid being sprayed on fuselage?", options: ["Water", "A neutralising agent", "Oil"], correctOptionIndex: 1 },
  { id: 80, text: "Batteries are usually connected to the aircraft DC system using what?", options: ["Screw terminals", "Single screw-attached two-pole plug", "Soldered connections"], correctOptionIndex: 1 },
  { id: 81, text: "Connecting batteries in parallel provides what?", options: ["Higher voltage", "Greater capacity (Ah)", "Lower resistance"], correctOptionIndex: 1 },
  { id: 82, text: "What are the three methods of charging a battery on an aircraft?", options: ["High rate, low rate, trickle", "Constant voltage, constant current, pulse", "AC, DC, pulsed DC"], correctOptionIndex: 1 },
  { id: 83, text: "Constant voltage charging refers to a method where the supply is of what?", options: ["Varying potential", "Constant potential", "Pulsed potential"], correctOptionIndex: 1 },
  { id: 84, text: "In constant voltage charging, as charging proceeds, what happens to charging current?", options: ["Increases", "Continual decrease", "Stays constant"], correctOptionIndex: 1 },
  { id: 85, text: "If DC generator output is set too low in constant voltage charging, what happens?", options: ["Battery overcharges", "Battery will not receive a full charge", "Battery overheats"], correctOptionIndex: 1 },
  { id: 86, text: "In constant current charging, the charger maintains what?", options: ["Constant voltage", "Pre-determined and relatively constant current", "Pulsed output"], correctOptionIndex: 1 },
  { id: 87, text: "Constant current charging is generally slower or faster than constant voltage?", options: ["Faster", "Slower", "Same speed"], correctOptionIndex: 1 },
  { id: 88, text: "Constant current charging is the preferred method for what battery type?", options: ["Lead-acid", "NiCad", "Lithium"], correctOptionIndex: 1 },
  { id: 89, text: "In order for a NiCad battery to deliver 100% capacity, it has to be recharged to what percentage?", options: ["100%", "140%", "120%"], correctOptionIndex: 1 },
  { id: 90, text: "When checking electrolyte level, distilled water must only be added when?", options: ["Battery is discharged", "Battery is fully charged", "Any time"], correctOptionIndex: 1 },
  { id: 91, text: "After adding water, battery should stand idle for how long with vent caps loosened?", options: ["30 minutes to 1 hour", "2 to 4 hours", "12 hours"], correctOptionIndex: 1 },
  { id: 92, text: "For lead-acid electrolyte spillage, what neutralising agent should be used?", options: ["Acetic acid", "Sodium bicarbonate powder", "Water only"], correctOptionIndex: 1 },
  { id: 93, text: "For NiCad electrolyte spillage, what neutralising agent should be used?", options: ["Sodium bicarbonate", "5% solution of acetic acid or vinegar", "Water only"], correctOptionIndex: 1 },
  { id: 94, text: "When using a hydrometer, add how much to reading for every 4°C above 15°C?", options: ["0.001", "0.003", "0.005"], correctOptionIndex: 1 },
  { id: 95, text: "When using a hydrometer, subtract how much from reading for every 4°C below 15°C?", options: ["0.001", "0.003", "0.005"], correctOptionIndex: 1 },
  { id: 96, text: "Lead-acid batteries should be stored in an area entirely separate from what?", options: ["Lithium batteries", "Nickel-cadmium batteries", "Alkaline batteries"], correctOptionIndex: 1 },
  { id: 97, text: "Charged lead-acid batteries should be given a freshening charge how often?", options: ["Every day", "Every 2-4 weeks", "Every 6 months"], correctOptionIndex: 1 },
  { id: 98, text: "NiCad batteries should be stored in what condition?", options: ["Fully charged", "Filled with electrolyte, discharged, with shorting strips fitted", "Dry"], correctOptionIndex: 1 },
  { id: 99, text: "Recommended temperature for long-term storage of NiCad batteries is what?", options: ["0°C", "20°C", "40°C"], correctOptionIndex: 1 },
  { id: 100, text: "All electricity produced by magnetic generators is what type initially?", options: ["DC", "AC", "Pulsed DC"], correctOptionIndex: 1 },
  { id: 101, text: "What are the two types of rectifiers mentioned?", options: ["Half-wave and full-wave", "Mechanical and semiconductor", "Bridge and center-tap"], correctOptionIndex: 1 },
  { id: 102, text: "By adding more coils, what happens to the output voltage?", options: ["Ripple frequency decreases", "Ripple frequency increases and output becomes smoother", "Voltage decreases"], correctOptionIndex: 1 },
  { id: 103, text: "A typical generator consists of what two major assemblies?", options: ["Rotor and stator", "Fixed stator (yoke) and rotating armature assembly", "Field and armature"], correctOptionIndex: 1 },
  { id: 104, text: "Typical input speed range for generators on turboprop aircraft is what?", options: ["1,000-3,000 RPM", "4,500-8,500 RPM", "10,000-15,000 RPM"], correctOptionIndex: 1 },
  { id: 105, text: "Interference to radio reception is suppressed by what components?", options: ["Inductors", "Capacitors", "Resistors"], correctOptionIndex: 1 },
  { id: 106, text: "How are generators cooled?", options: ["By liquid coolant", "By ram air effect", "By convection only"], correctOptionIndex: 1 },
  { id: 107, text: "Initial excitation in DC generators is derived from what?", options: ["Battery", "Residual magnetism in field winding cores", "External power"], correctOptionIndex: 1 },
  { id: 108, text: "Generator field flashing is required when what condition exists?", options: ["Generator output is too high", "Insufficient residual magnetism prevents voltage build-up", "Generator is new"], correctOptionIndex: 1 },
  { id: 109, text: "Commutator surface should be what colour with a distinctive bluish sheen?", options: ["Black", "Dark brown", "Copper colour"], correctOptionIndex: 1 },
  { id: 110, text: "Each brush should be examined for what?", options: ["Only length", "Chipping, pitting, burning, contamination by grease or oil", "Only spring tension"], correctOptionIndex: 1 },
  { id: 111, text: "When changing brushes, new brushes must be what?", options: ["Installed directly", "'Bedded in' to the shape of the commutator", "Soaked in oil"], correctOptionIndex: 1 },
  { id: 112, text: "A guidance value for insulation resistance given by CAA for a 28V machine is what?", options: ["1 MΩ", "Whichever is greater of (rated voltage/150) or 0.5 Megohms", "10 MΩ"], correctOptionIndex: 1 },
  { id: 113, text: "Generator fields are self-excited. What does this mean?", options: ["Field current comes from battery", "Field current comes from the armature", "Field current comes from external source"], correctOptionIndex: 1 },
  { id: 114, text: "In an A-circuit type generator system, where are the field coils connected?", options: ["To the grounded brush", "To the insulated brush inside the generator", "Directly to the busbar"], correctOptionIndex: 1 },
  { id: 115, text: "In a B-circuit type generator system, where are the field coils connected?", options: ["To the insulated brush", "To the grounded brush", "To the armature"], correctOptionIndex: 1 },
  { id: 116, text: "The zero-centre ammeter shows what?", options: ["Voltage only", "Amount of current flowing from battery to bus (-) or from generator to battery (+)", "Resistance"], correctOptionIndex: 1 },
  { id: 117, text: "DC alternators have how many primary advantages over generators?", options: ["One", "Three", "Five"], correctOptionIndex: 1 },
  { id: 118, text: "In a DC alternator, where is the high current produced?", options: ["In the rotor", "In the stationary stator component", "In the slip rings"], correctOptionIndex: 1 },
  { id: 119, text: "The rotor in a DC alternator is made of what?", options: ["Single iron piece", "Two end pieces of iron that form magnetic poles", "Copper windings only"], correctOptionIndex: 1 },
  { id: 120, text: "Some rotors have how many pairs of poles?", options: ["2-3 pairs", "4-7 pairs", "8-10 pairs"], correctOptionIndex: 1 },
  { id: 121, text: "The stator windings are arranged in what type of circuit?", options: ["Single-phase", "Three-phase Y-connected", "Delta connected"], correctOptionIndex: 1 },
  { id: 122, text: "The AC output is converted to DC by how many diodes?", options: ["Four", "Six", "Eight"], correctOptionIndex: 1 },
  { id: 123, text: "Starter-generators have an extra set of what type of windings?", options: ["Shunt windings", "Series windings", "Compound windings"], correctOptionIndex: 1 },
  { id: 124, text: "During engine starting, which windings are switched into the circuit?", options: ["Shunt windings", "Series motor windings", "Both shunt and series"], correctOptionIndex: 1 },
  { id: 125, text: "In AC generators, the rotating part is called what?", options: ["Stator", "Rotor", "Armature"], correctOptionIndex: 1 },
  { id: 126, text: "In AC generators, the stationary part is called what?", options: ["Rotor", "Stator", "Field"], correctOptionIndex: 1 },
  { id: 127, text: "What are the three basic types of AC generators?", options: ["Single-phase, two-phase, three-phase", "Permanent magnet, rotating armature, rotating field", "Brushed, brushless, induction"], correctOptionIndex: 1 },
  { id: 128, text: "In a permanent magnet generator, what is the rotor?", options: ["An electromagnet", "A permanent magnet", "A coil"], correctOptionIndex: 1 },
  { id: 129, text: "In a rotating armature generator, what rotates?", options: ["Field", "Armature with windings", "Permanent magnets"], correctOptionIndex: 1 },
  { id: 130, text: "EMF is picked off via what components?", options: ["Brushes and commutator", "Slip-rings", "Direct connection"], correctOptionIndex: 1 },
  { id: 131, text: "The formula for frequency is f = Np/60. What does p represent?", options: ["Speed in RPM", "Number of pairs of poles", "Phase angle"], correctOptionIndex: 1 },
  { id: 132, text: "A two-pole machine must be driven at what RPM to produce 400 Hz?", options: ["12,000 RPM", "24,000 RPM", "6,000 RPM"], correctOptionIndex: 1 },
  { id: 133, text: "In a three-phase generator, the coils are spaced at what angle to each other?", options: ["90°", "120°", "180°"], correctOptionIndex: 1 },
  { id: 134, text: "Three-phase supplies are used extensively on aircraft because?", options: ["They are simpler", "They are more efficient than single or two-phase", "They require less wiring"], correctOptionIndex: 1 },
  { id: 135, text: "Generators are rated in what units for small units?", options: ["Watts", "Volt-amperes (VA)", "Amperes"], correctOptionIndex: 1 },
  { id: 136, text: "For large units, generators are rated in what?", options: ["kW", "Kilovolt-amperes (kVA)", "kVAr"], correctOptionIndex: 1 },
  { id: 137, text: "In a two-phase generator, the windings are physically at what angle to each other?", options: ["120°", "90°", "180°"], correctOptionIndex: 1 },
  { id: 138, text: "The outputs of each phase in a two-phase generator are how many degrees apart?", options: ["120°", "90°", "60°"], correctOptionIndex: 1 },
  { id: 139, text: "In a two-phase, three-wire generator, the output at C (across both phases) is how many times the voltage of either phase?", options: ["1.0 times", "1.414 times", "1.73 times"], correctOptionIndex: 1 },
  { id: 140, text: "In a three-phase generator, voltage in any one phase is displaced by how many degrees from the other two?", options: ["90°", "120°", "180°"], correctOptionIndex: 1 },
  { id: 141, text: "In a star (Y) connection, the line voltage is how many times the phase voltage?", options: ["1.0 times", "1.73 times (√3)", "1.414 times"], correctOptionIndex: 1 },
  { id: 142, text: "In a star connection, line current equals what?", options: ["1.73 times phase current", "Phase current", "0.577 times phase current"], correctOptionIndex: 1 },
  { id: 143, text: "In a delta connection, line voltage equals what?", options: ["1.73 times phase voltage", "Phase voltage", "0.577 times phase voltage"], correctOptionIndex: 1 },
  { id: 144, text: "In a delta connection, line current equals what?", options: ["Phase current", "1.73 times phase current", "0.577 times phase current"], correctOptionIndex: 1 },
  { id: 145, text: "Aircraft AC generators are generally connected in what configuration?", options: ["Delta", "Star", "Single-phase"], correctOptionIndex: 1 },
  { id: 146, text: "True power in a balanced three-phase system is given by what formula?", options: ["V × I", "√3 × V_L × I_L × cos Φ", "3 × V_ph × I_ph"], correctOptionIndex: 1 },
  { id: 147, text: "Reactive power is measured in what units?", options: ["Watts", "Volt-amps-reactive (VAR)", "Volt-amps (VA)"], correctOptionIndex: 1 },
  { id: 148, text: "Apparent power is measured in what units?", options: ["Watts", "Volt-amps (VA)", "VAR"], correctOptionIndex: 1 },
  { id: 149, text: "Power factor is the ratio of what to what?", options: ["Reactive power to apparent power", "True power to apparent power", "Apparent power to true power"], correctOptionIndex: 1 },
  { id: 150, text: "When phase angle θ = 0°, what is the power factor?", options: ["0", "1", "0.5"], correctOptionIndex: 1 },
  { id: 151, text: "When phase angle θ = 90°, what is the power factor?", options: ["1", "0", "0.5"], correctOptionIndex: 1 },
  { id: 152, text: "Aircraft generation systems typically have a power factor between what values?", options: ["0.5 to 0.7", "0.75 to 0.9", "0.9 to 1.0"], correctOptionIndex: 1 },
  { id: 153, text: "Frequency wild systems can be used when the load is only what type?", options: ["Inductive", "Resistive", "Capacitive"], correctOptionIndex: 1 },
  { id: 154, text: "The first AC generators used on aircraft were what type?", options: ["Constant speed", "Frequency wild rotating field", "Variable frequency"], correctOptionIndex: 1 },
  { id: 155, text: "These generators were preferred to DC systems because of what advantage?", options: ["Simpler construction", "Better power to weight ratio and less affected by poor brush performance at high altitudes", "Lower cost"], correctOptionIndex: 1 },
  { id: 156, text: "A typical small brushless DC generator has how many diodes in the rectifier assembly?", options: ["Three", "Six", "Nine"], correctOptionIndex: 1 },
  { id: 157, text: "Small brushless DC generators require initial excitation from where?", options: ["Permanent magnets", "The aircraft busbar (battery or external power)", "Residual magnetism"], correctOptionIndex: 1 },
  { id: 158, text: "The frequency wild three-phase generator has a speed range of what?", options: ["3,000-6,000 RPM", "6,700-10,700 RPM", "10,000-15,000 RPM"], correctOptionIndex: 1 },
  { id: 159, text: "Constant-speed generators are driven by an engine through what?", options: ["Direct drive", "A special constant-speed drive unit", "Belt drive"], correctOptionIndex: 1 },
  { id: 160, text: "A brushless generator consists of what three principal components?", options: ["Rotor, stator, exciter", "Pilot exciter, main exciter and rotating rectifier, main generator", "PMG, control unit, rectifier"], correctOptionIndex: 1 },
  { id: 161, text: "The purpose of the pilot exciter is to provide what?", options: ["Main output", "Magnetic field for initial excitation of the main exciter", "Cooling"], correctOptionIndex: 1 },
  { id: 162, text: "The pilot exciter comprises what?", options: ["Rotor and stator only", "A stator and a permanent magnet rotor", "Field coils only"], correctOptionIndex: 1 },
  { id: 163, text: "The rotating rectifier assembly usually consists of how many silicon diodes?", options: ["Three", "Six", "Twelve"], correctOptionIndex: 1 },
  { id: 164, text: "The main generator consists of what?", options: ["Rotor only", "Three-phase, star-wound stator, rotor and associated field windings", "Stator only"], correctOptionIndex: 1 },
  { id: 165, text: "After generator removal, what should be checked on drive belts or coupling splines?", options: ["Colour", "Wear against wear limits in the manual", "Temperature"], correctOptionIndex: 1 },
  { id: 166, text: "Integrated drive generator units have what mechanism for isolation from engine?", options: ["Manual disconnect only", "Electrically-operated disconnect mechanism", "Automatic fuse"], correctOptionIndex: 1 },
  { id: 167, text: "The constant-speed drive can normally only be re-engaged when?", options: ["In flight", "With engine at rest", "At any time"], correctOptionIndex: 1 },
  { id: 168, text: "Voltage regulation is accomplished by varying what?", options: ["Generator speed", "Field strength of the AC generator's exciter field", "Load"], correctOptionIndex: 1 },
  { id: 169, text: "What are the two main methods of voltage regulation?", options: ["Series and shunt", "Error sensing bridge and pulse width modulation", "Feedback and feedforward"], correctOptionIndex: 1 },
  { id: 170, text: "Carbon-pile regulator operation is based on what fact?", options: ["Carbon discs generate voltage", "Contact electrical resistance between carbon discs varies with pressure", "Carbon discs change colour with current"], correctOptionIndex: 1 },
  { id: 171, text: "Variation of pile compression is made through what medium?", options: ["Manual adjustment", "An electromagnet opposing a control spring", "Thermal expansion"], correctOptionIndex: 1 },
  { id: 172, text: "The electromagnet is energised by a voltage coil connected where?", options: ["Across the field", "Across the generator output terminals", "In series with the load"], correctOptionIndex: 1 },
  { id: 173, text: "Vibrator-type regulator consists of what units?", options: ["Voltage regulator only", "Voltage regulator, current limiter, and reverse current cut-out relay", "Current limiter only"], correctOptionIndex: 1 },
  { id: 174, text: "The voltage coil senses what?", options: ["Current", "Output voltage from the generator", "Temperature"], correctOptionIndex: 1 },
  { id: 175, text: "The contact points in a vibrator-type regulator do what?", options: ["Stay closed", "Continually vibrate open and closed", "Stay open"], correctOptionIndex: 1 },
  { id: 176, text: "The three-unit regulator includes which units?", options: ["Voltage regulator, overvoltage protector, reverse current relay", "Voltage regulator, current limiter, reverse current cut-out", "Voltage regulator, frequency regulator, phase detector"], correctOptionIndex: 1 },
  { id: 177, text: "The current limiter is actuated by what?", options: ["Line voltage", "Line current", "Temperature"], correctOptionIndex: 1 },
  { id: 178, text: "The reverse current cut-out relay disconnects what?", options: ["Generator from field", "Battery from generator when generator voltage is less than battery voltage", "Load from busbar"], correctOptionIndex: 1 },
  { id: 179, text: "The voltage winding in reverse current cut-out has what characteristics?", options: ["Few turns of heavy wire", "Large number of turns of fine wire", "Single turn of heavy wire"], correctOptionIndex: 1 },
  { id: 180, text: "The current winding in reverse current cut-out has what characteristics?", options: ["Large number of turns of fine wire", "Few turns of heavy wire", "No turns, it's a shunt"], correctOptionIndex: 1 },
  { id: 181, text: "Reverse current cut-out contacts close when what condition exists?", options: ["Generator voltage equals battery voltage", "Generator voltage is greater than battery voltage", "Generator voltage is less than battery voltage"], correctOptionIndex: 1 },
  { id: 182, text: "In error sensing bridge method, two constant voltage tubes each maintain what voltage?", options: ["170 V", "85 V", "200 V"], correctOptionIndex: 1 },
  { id: 183, text: "If there is an increase in line voltage, what happens in the error sensing bridge?", options: ["Point B becomes positive to A", "Point A becomes positive with respect to point B", "No current flows"], correctOptionIndex: 1 },
  { id: 184, text: "Current flowing through the control winding in one direction does what?", options: ["Increases generator output", "Reduces current in exciter field and reduces generator output", "Has no effect"], correctOptionIndex: 1 },
  { id: 185, text: "Solid-state voltage regulators fall into what two categories?", options: ["Analog and digital", "Transistorised with electromagnetic sensing, and fully solid-state with Zener diode sensing", "Linear and switching"], correctOptionIndex: 1 },
  { id: 186, text: "Pulse width modulation varies what aspect of the pulses?", options: ["Amplitude", "Width (duration) of the pulses", "Frequency"], correctOptionIndex: 1 },
  { id: 187, text: "When generator loading increases, terminal voltage decreases. The regulator does what?", options: ["Decreases pulse width", "Increases pulse width", "Keeps pulse width constant"], correctOptionIndex: 1 },
  { id: 188, text: "A Zener diode allows free flow of electrons in one direction but blocks reverse flow until what happens?", options: ["Current reaches a limit", "Voltage rises to its breakdown or Zener voltage", "Temperature rises"], correctOptionIndex: 1 },
  { id: 189, text: "Magnetic amplifier voltage regulator derives its AC power from where?", options: ["Battery", "Generator output", "External source"], correctOptionIndex: 1 },
  { id: 190, text: "The reactive load division circuitry provides what during parallel operation?", options: ["Real load sharing", "Balanced kVAR loading", "Frequency control"], correctOptionIndex: 1 },
  { id: 191, text: "During parallel operations, what provides a corrective signal to maintain proper reactive load division?", options: ["Voltage sensor", "Current transformer and reactor package", "Frequency sensor"], correctOptionIndex: 1 },
  { id: 192, text: "Negative sequence voltage is produced only during what condition?", options: ["Normal operation", "Unbalanced line-to-line or line-to-earth fault", "Overvoltage"], correctOptionIndex: 1 },
  { id: 193, text: "The DC bias supply obtains power from where?", options: ["Battery", "Three-phase transformer connected to generator terminals", "PMG"], correctOptionIndex: 1 },
  { id: 194, text: "Current transformers mounted on generator feeders are connected in series with what?", options: ["The field", "The low potential ends of the power transformer secondary windings", "The load"], correctOptionIndex: 1 },
  { id: 195, text: "The nominal frequency required from an aircraft alternator is what?", options: ["60 Hz", "400 Hz", "50 Hz"], correctOptionIndex: 1 },
  { id: 196, text: "Frequency tolerance is usually what range?", options: ["390-410 Hz", "380-420 Hz (±5%)", "400-440 Hz"], correctOptionIndex: 1 },
  { id: 197, text: "A CSDU consists of what components?", options: ["Electric motor and gearbox", "Variable hydraulic pump and motor", "Belt drive and pulleys"], correctOptionIndex: 1 },
  { id: 198, text: "An IDG combines what two units in one compact unit?", options: ["Generator and voltage regulator", "Alternator and CSDU", "Generator and battery charger"], correctOptionIndex: 1 },
  { id: 199, text: "The speed of the generator can be what values depending on type?", options: ["3,000, 6,000, or 12,000 RPM", "12,000, 6,000, or 8,000 RPM", "24,000 RPM only"], correctOptionIndex: 1 },
  { id: 200, text: "The CSDU can add or subtract from input speed (4,300 to 8,600 RPM) to maintain generator speed at what?", options: ["12,000 RPM", "6,000 RPM", "24,000 RPM"], correctOptionIndex: 1 },
  { id: 201, text: "What condition is called straight drive?", options: ["Engine speed is maximum", "Engine input speed is exactly that required by the generator", "Generator is offline"], correctOptionIndex: 1 },
  { id: 202, text: "When engine speed reduces, the governor supplies fluid to increase pump wobbler plate angle. This is called what?", options: ["Underdrive", "Overdrive", "Straight drive"], correctOptionIndex: 1 },
  { id: 203, text: "When engine speed is faster than straight drive speed, the pump wobbler plate moves to cause what condition?", options: ["Overdrive", "Underdrive", "Neutral"], correctOptionIndex: 1 },
  { id: 204, text: "The governor assembly senses what parameter?", options: ["Input speed", "Output speed", "Oil pressure"], correctOptionIndex: 1 },
  { id: 205, text: "Flyweights are connected to which shaft?", options: ["Input shaft", "Rotating shaft (output)", "Pump shaft"], correctOptionIndex: 1 },
  { id: 206, text: "The significant difference in a paralleled system governor is what?", options: ["Larger flyweights", "Magnetic trim system", "Electronic control"], correctOptionIndex: 1 },
  { id: 207, text: "The magnetic trim allows fine-tuning for what purpose?", options: ["Voltage adjustment", "Ensure correct real-load sharing", "Frequency adjustment"], correctOptionIndex: 1 },
  { id: 208, text: "Nominal charge pressure in the IDG is what?", options: ["140 psi", "250 psi", "400 psi"], correctOptionIndex: 1 },
  { id: 209, text: "If oil pressure falls below 140 psi, what happens?", options: ["Generator shuts down", "Drive light in IDG disconnect switch comes on", "Warning horn sounds"], correctOptionIndex: 1 },
  { id: 210, text: "IDG input speed range is what?", options: ["3,000-6,000 RPM", "4,500-9,120 RPM", "10,000-15,000 RPM"], correctOptionIndex: 1 },
  { id: 211, text: "IDG output speed is constant at what?", options: ["6,000 RPM", "12,000 ± 120 RPM", "24,000 RPM"], correctOptionIndex: 1 },
  { id: 212, text: "Output frequency of IDG is constant at what?", options: ["60 ± 1 Hz", "400 ± 4 Hz", "400 ± 20 Hz"], correctOptionIndex: 1 },
  { id: 213, text: "IDG disconnection in flight is what?", options: ["Reversible", "Irreversible", "Automatic only"], correctOptionIndex: 1 },
  { id: 214, text: "IDG can only be reconnected when?", options: ["In flight", "On ground with engines shut down", "At any time"], correctOptionIndex: 1 },
  { id: 215, text: "At what pressure does the low-pressure warning light typically activate?", options: ["250 psi", "Approximately 140 psi", "100 psi"], correctOptionIndex: 1 },
  { id: 216, text: "At what temperature does the high oil temperature light typically activate?", options: ["100°C", "157°C", "200°C"], correctOptionIndex: 1 },
  { id: 217, text: "A normal temperature rise through the CSDU is how many degrees?", options: ["1-2°C", "5-10°C", "15-20°C"], correctOptionIndex: 1 },
  { id: 218, text: "A brushless alternator consists of how many separate fields?", options: ["Two", "Three (permanent magnetic, exciter field, main output field)", "Four"], correctOptionIndex: 1 },
  { id: 219, text: "The permanent magnets furnish magnetic flux for what purpose?", options: ["Main output", "To start generator producing output before field current flows", "Cooling"], correctOptionIndex: 1 },
  { id: 220, text: "The three-phase output of AC alternators typically have what voltage across each phase winding?", options: ["28 V", "120 V", "208 V"], correctOptionIndex: 1 },
  { id: 221, text: "With windings connected in star, the output between terminals is what voltage?", options: ["120 V", "208 V", "115 V"], correctOptionIndex: 1 },
  { id: 222, text: "The stationary magnet type generator has how many main parts?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 223, text: "The PMG type has how many main parts?", options: ["Two", "Three (rotating PMG, main exciter, main AC generator)", "Four"], correctOptionIndex: 1 },
  { id: 224, text: "The PMG supplies the exciter field through what?", options: ["Direct connection", "Generator control relay (GCR) and rectifier unit", "Transformer"], correctOptionIndex: 1 },
  { id: 225, text: "The normal power supply for the GCU is from where?", options: ["Generator output", "Aircraft battery", "PMG"], correctOptionIndex: 1 },
  { id: 226, text: "Excitation control and regulation module keep voltage at nominal value at what point?", options: ["Generator terminals", "Point of regulation (POR)", "Busbar"], correctOptionIndex: 1 },
  { id: 227, text: "VSCF systems eliminate what component?", options: ["Generator", "Constant speed drive unit (CSDU)", "Voltage regulator"], correctOptionIndex: 1 },
  { id: 228, text: "VSCF uses what type of generator?", options: ["Constant speed AC generator", "Large DC alternator not reliant on constant input speed", "Frequency wild AC generator"], correctOptionIndex: 1 },
  { id: 229, text: "The DC output is sent to what device to convert to constant 400 Hz AC?", options: ["Rectifier", "Inverter", "Transformer"], correctOptionIndex: 1 },
  { id: 230, text: "Typical mass of a VSCF unit is about what?", options: ["30 kg", "63.5 kg", "100 kg"], correctOptionIndex: 1 },
  { id: 231, text: "The speed increaser provides what speed ratio?", options: ["1:1", "2.96:1", "5:1"], correctOptionIndex: 1 },
  { id: 232, text: "Generator rotor operates at speeds between what?", options: ["6,000-12,000 RPM", "13,705-26,120 RPM", "24,000-30,000 RPM"], correctOptionIndex: 1 },
  { id: 233, text: "T1, T2, T3 are what type of terminals?", options: ["Neutral", "Power terminals", "Control"], correctOptionIndex: 1 },
  { id: 234, text: "T4, T5, T6 are what type of terminals?", options: ["Power", "Neutral terminals", "Ground"], correctOptionIndex: 1 },
  { id: 235, text: "Flight-line BIT is done using what type of switch?", options: ["Rotary switch", "Two-throw, centre off switch", "Push button"], correctOptionIndex: 1 },
  { id: 236, text: "BIT fault data is displayed by how many red LEDs?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 237, text: "One LED is labelled \"VSCF Fault Detected\" and illuminates when?", options: ["During lamp test", "With switch in \"INDICATE\" position if BIT has detected a fault", "Continuously"], correctOptionIndex: 1 },
  { id: 238, text: "Second level of BIT is intended for whom?", options: ["Pilots", "Workshop technician on removed unit", "Flight engineer"], correctOptionIndex: 1 },
  { id: 239, text: "Airbus A380 VFG rated output is what?", options: ["90 kVA", "150 kVA", "200 kVA"], correctOptionIndex: 1 },
  { id: 240, text: "VFG frequency range is what?", options: ["380-420 Hz", "370-770 Hz", "400-800 Hz"], correctOptionIndex: 1 },
  { id: 241, text: "RAT is deployed by what mechanism during emergency?", options: ["Electric motor", "Spring-loaded actuator", "Manual crank"], correctOptionIndex: 1 },
  { id: 242, text: "Turbine diameters of about what size are common?", options: ["40 cm", "80 cm", "120 cm"], correctOptionIndex: 1 },
  { id: 243, text: "A380 RAT turbine diameter is what?", options: ["80 cm", "162 cm", "200 cm"], correctOptionIndex: 1 },
  { id: 244, text: "RAT speed is governed in proportion to what factors?", options: ["Only airspeed", "Turbine diameter, airspeed, and emergency load requirement", "Only load requirement"], correctOptionIndex: 1 },
  { id: 245, text: "RAT power output is approximately what percentage of full requirements?", options: ["5%", "10%", "25%"], correctOptionIndex: 1 },
  { id: 246, text: "Larger aircraft primary power source is what?", options: ["DC generators", "AC generators producing 115/200 V 400 Hz", "Batteries"], correctOptionIndex: 1 },
  { id: 247, text: "Many systems use what DC voltage?", options: ["14 V DC", "28 V DC", "115 V DC"], correctOptionIndex: 1 },
  { id: 248, text: "Diodes allow electricity to flow in how many directions?", options: ["Two", "One direction only", "Either direction depending on voltage"], correctOptionIndex: 1 },
  { id: 249, text: "Three-phase rectification needs how many diodes?", options: ["Four", "Six", "Eight"], correctOptionIndex: 1 },
  { id: 250, text: "The purpose of two different secondaries with separate rectification in a TRU is what?", options: ["Higher voltage", "Less power ripple of the rectified 28 V DC output", "Higher current"], correctOptionIndex: 1 },
  { id: 251, text: "Old aircraft use what type of inverters?", options: ["Static inverters", "Rotary inverters (motor-generator units)", "Solid-state inverters"], correctOptionIndex: 1 },
  { id: 252, text: "Rotary inverters consist of what?", options: ["Transformer and rectifier", "DC motor with AC generator armature on its shaft", "Oscillator and transformer"], correctOptionIndex: 1 },
  { id: 253, text: "Static inverters consist of what?", options: ["DC motor and AC generator", "Oscillator, transformer, and filter", "Rectifier and transformer"], correctOptionIndex: 1 },
  { id: 254, text: "Power switching from aircraft power to external source produces power transients of how long?", options: ["10 ms", "100 ms", "1 second"], correctOptionIndex: 1 },
  { id: 255, text: "In DC ground power plug, how many pins are there?", options: ["Two", "Three (two positive, one negative)", "Four"], correctOptionIndex: 1 },
  { id: 256, text: "The short positive pin in DC ground power plug serves what purpose?", options: ["Main power", "Energises external power relay before main pins engage", "Ground"], correctOptionIndex: 1 },
  { id: 257, text: "For paralleling external power with APU, frequency difference should be less than what?", options: ["1 Hz", "0.5 Hz", "5 Hz"], correctOptionIndex: 1 },
  { id: 258, text: "Phase angle difference for paralleling should be less than what?", options: ["5°", "15°", "30°"], correctOptionIndex: 1 },
  { id: 259, text: "Synchronisation may take up to how long for APU GEN with GPU?", options: ["5 seconds", "15 seconds", "30 seconds"], correctOptionIndex: 1 },
  { id: 260, text: "What are busbars used for?", options: ["To generate power", "To distribute electrical power around the aircraft and connect consumer equipment", "To store power"], correctOptionIndex: 1 },
  { id: 261, text: "What protects circuits and equipment from electrical overload?", options: ["Switches", "Fuses or circuit breakers", "Relays"], correctOptionIndex: 1 },
  { id: 262, text: "Circuit breakers are always placed between what?", options: ["Generator and battery", "Electrical equipment and the busbar to which it is connected", "Battery and ground"], correctOptionIndex: 1 },
  { id: 263, text: "What are the two basic types of circuit breakers?", options: ["Push-pull and toggle", "Those that operate on heat and those opened by magnetic field", "Thermal and mechanical"], correctOptionIndex: 1 },
  { id: 264, text: "Push-pull circuit breakers have what visual aid when popped?", options: ["Red band", "White band", "Yellow band"], correctOptionIndex: 1 },
  { id: 265, text: "A design requirement is that circuit breakers must not allow what?", options: ["Automatic reset", "Pilot to hold them closed with thumb or finger pressure", "Visual indication"], correctOptionIndex: 1 },
  { id: 266, text: "Relays allow what to be switched using a small current?", options: ["Small current", "A large current", "Voltage only"], correctOptionIndex: 1 },
  { id: 267, text: "A freewheel diode across a contactor coil prevents what?", options: ["Overheating", "Voltage spike damage when current is interrupted", "Arcing"], correctOptionIndex: 1 },
  { id: 268, text: "The economy coil in a relay does what?", options: ["Increases closing force", "Reduces current consumption when contactor is closed", "Provides faster opening"], correctOptionIndex: 1 },
  { id: 269, text: "Current limiters are used to protect what type of circuits?", options: ["Low power circuits", "Heavy-duty power distribution circuits", "Instrument circuits"], correctOptionIndex: 1 },
  { id: 270, text: "An ammeter shows what?", options: ["Voltage", "If alternator/generator is producing adequate power and if battery is charging", "Resistance"], correctOptionIndex: 1 },
  { id: 271, text: "If ammeter needle indicates a minus value, what does this mean?", options: ["Battery is charging", "Generator output is inadequate, energy drawn from battery", "Generator is overloaded"], correctOptionIndex: 1 },
  { id: 272, text: "All electrical services are wired in what configuration?", options: ["Series", "Parallel to each other", "Series-parallel"], correctOptionIndex: 1 },
  { id: 273, text: "The aluminium airframe forms what part of the circuit?", options: ["Positive supply", "Return circuit (ground)", "Insulation"], correctOptionIndex: 1 },
  { id: 274, text: "The differential cut-out has how many coils?", options: ["One", "Two (differential coil and series coil)", "Three"], correctOptionIndex: 1 },
  { id: 275, text: "The differential coil consists of what?", options: ["One large turn", "Many turns of fine wire", "Few turns of heavy wire"], correctOptionIndex: 1 },
  { id: 276, text: "The series coil consists of what?", options: ["Many turns of fine wire", "One large turn", "Several turns of medium wire"], correctOptionIndex: 1 },
  { id: 277, text: "At approximately what voltage does the under-voltage relay pull in?", options: ["28 V", "22 V", "14 V"], correctOptionIndex: 1 },
  { id: 278, text: "When generator voltage exceeds bus bar voltage by how much, does the cut-out connect generator to bus bar?", options: ["0.1-0.2 V", "0.5-0.75 V", "1-2 V"], correctOptionIndex: 1 },
  { id: 279, text: "When reverse current of what value flows, does the cut-out disconnect generator?", options: ["5-10 amps", "15-20 amps", "25-30 amps"], correctOptionIndex: 1 },
  { id: 280, text: "Short circuit and overload fuses have a fusible element with what characteristic?", options: ["High melting point", "Predetermined low melting point", "Variable melting point"], correctOptionIndex: 1 },
  { id: 281, text: "Heavy duty fuses have the tube filled with what?", options: ["Air", "Packing medium like granular quartz or chalk to dampen arc", "Oil"], correctOptionIndex: 1 },
  { id: 282, text: "Current limiters have a time/current characteristic that allows what?", options: ["Instantaneous rupture", "Considerable overload current before rupturing", "No overload capability"], correctOptionIndex: 1 },
  { id: 283, text: "Limiting resistors protect circuits with what characteristic?", options: ["Low starting current", "High initial starting current", "Constant current"], correctOptionIndex: 1 },
  { id: 284, text: "Manually operated circuit breakers are of what type to ensure they cannot be held closed against a fault?", options: ["Thermal only", "Trip free type", "Magnetic only"], correctOptionIndex: 1 },
  { id: 285, text: "Three pole circuit breakers have contacts that open and close together within what time difference?", options: ["1 ms", "5-0 ms", "10 ms"], correctOptionIndex: 1 },
  { id: 286, text: "Protection against sudden severe overloads is given by what element?", options: ["Thermal element", "Magnetic trip", "Bimetal strip"], correctOptionIndex: 1 },
  { id: 287, text: "When generator voltage rises above battery voltage, what happens?", options: ["Relay opens", "Voltage coil causes armature to close contacts, placing generator on busbar", "Generator shuts down"], correctOptionIndex: 1 },
  { id: 288, text: "When generator voltage decays below battery voltage, what happens?", options: ["Contacts stay closed", "Reverse current flows, causing opposite magnetic field and contacts open", "Battery charges"], correctOptionIndex: 1 },
  { id: 289, text: "Overvoltage can occur due to what fault?", options: ["Load increase", "Internal grounding of field windings or open circuit in voltage regulator sensing lines", "Low speed"], correctOptionIndex: 1 },
  { id: 290, text: "In a typical overvoltage protection circuit, if generator output rises to predetermined value, what happens?", options: ["Field current increases", "Both relay coils energise, opening generator field circuit", "Warning light only"], correctOptionIndex: 1 },
  { id: 291, text: "In a twin-engined light aircraft, when is the under-volt relay de-energised and warning light illuminated?", options: ["During normal operation", "When engine and generator are at rest, or generator isolated or faulty", "During overvoltage"], correctOptionIndex: 1 },
  { id: 292, text: "Under/over frequency protection is required only in what type of systems?", options: ["DC systems", "AC power supply systems", "Battery systems"], correctOptionIndex: 1 },
  { id: 293, text: "Before carrying out maintenance, what must be ensured?", options: ["Power is on", "System is de-energised and no external supplies connected", "Batteries are connected"], correctOptionIndex: 1 },
  { id: 294, text: "If a circuit breaker trips again shortly after resetting, what must be assumed?", options: ["It's normal", "A fault condition exists", "Breaker is weak"], correctOptionIndex: 1 },
  { id: 295, text: "If there is an asymmetrical load in AC distribution, what will flow through aircraft structure?", options: ["No current", "A neutral current", "Voltage"], correctOptionIndex: 1 },
  { id: 296, text: "In DC distribution, the aircraft structure is used as what?", options: ["Positive supply", "Return conductor to negative pole", "Insulation"], correctOptionIndex: 1 },
  { id: 297, text: "In a split bus system, the bus system is divided into what?", options: ["Three sides", "Two sides (left and right)", "Four sides"], correctOptionIndex: 1 },
  { id: 298, text: "The only time the two sides are connected is when?", options: ["During takeoff", "One or both engine generators is off-line", "During landing"], correctOptionIndex: 1 },
  { id: 299, text: "The bus tie breakers (BTB) are closed automatically by what?", options: ["Pilot", "A bus control system", "Generator"], correctOptionIndex: 1 },
  { id: 300, text: "In a split bus system, what provides DC power from the AC system?", options: ["Inverters", "Transformer rectifier units (TRU)", "Batteries"], correctOptionIndex: 1 },
  { id: 301, text: "The disadvantage of split bus configuration is what?", options: ["Complexity", "Interruption to half of electrical services during generator failure", "High weight"], correctOptionIndex: 1 },
  { id: 302, text: "In a transfer bus system, if a main engine generator fails, what happens?", options: ["All power lost", "Transfer bus automatically transfers power to opposite side generator bus", "APU starts automatically"], correctOptionIndex: 1 },
  { id: 303, text: "The APU generator can feed both main busbars when what condition exists?", options: ["Engines running", "On ground with APU running, GCBs open, BTBs closed", "In flight only"], correctOptionIndex: 1 },
  { id: 304, text: "An interlock system prevents what?", options: ["Battery charging", "Any two sources of power being paralleled to one another", "Generator starting"], correctOptionIndex: 1 },
  { id: 305, text: "The generator control units (GCUs) provide what functions?", options: ["Only voltage regulation", "Automatic control and protection, including voltage regulation and fault protection", "Only load sharing"], correctOptionIndex: 1 },
  { id: 306, text: "The bus power control unit (BPCU) contains circuitry for what?", options: ["Only generator control", "External power monitoring, load shedding, tie bus differential protection", "Only battery charging"], correctOptionIndex: 1 },
  { id: 307, text: "Load shedding reduces demand by switching out what?", options: ["Essential services", "Non-essential services such as galleys", "All services"], correctOptionIndex: 1 },
  { id: 308, text: "The circuit breakers used for GCBs, BTBs, and APB are of what type?", options: ["Thermal only", "'Latched' type with permanent magnet holding force", "Magnetic only"], correctOptionIndex: 1 },
  { id: 309, text: "The ground handling busbar is supplied from where?", options: ["Main generators", "External power or APU", "Battery"], correctOptionIndex: 1 },
  { id: 310, text: "A320 engine generators are rated at what output?", options: ["60 kVA", "90 kVA", "115 kVA"], correctOptionIndex: 1 },
  { id: 311, text: "The emergency generator is driven by what?", options: ["Engine", "Hydraulic system", "APU"], correctOptionIndex: 1 },
  { id: 312, text: "Emergency generator output is what?", options: ["10 kVA", "5 kVA", "15 kVA"], correctOptionIndex: 1 },
  { id: 313, text: "Static inverter transforms DC from battery 1 into what?", options: ["28 V AC", "Single phase 115 V, 400 Hz AC", "Three-phase 200 V AC"], correctOptionIndex: 1 },
  { id: 314, text: "When aircraft speed is more than 50 kts, static inverter is automatically activated if what condition exists?", options: ["Engines running", "Only batteries are supplying the aircraft", "APU running"], correctOptionIndex: 1 },
  { id: 315, text: "Two main batteries have normal capacity of what?", options: ["12 Ah", "23 Ah", "40 Ah"], correctOptionIndex: 1 },
  { id: 316, text: "BCL stands for what?", options: ["Battery Control Light", "Battery Charge Limiter", "Bus Control Logic"], correctOptionIndex: 1 },
  { id: 317, text: "Before generators can be connected onto a common bus, what conditions must apply?", options: ["Same manufacturer", "Same output voltage, same frequency, in-phase, same phase rotation", "Same age"], correctOptionIndex: 1 },
  { id: 318, text: "One advantage of parallel system is what?", options: ["Simpler wiring", "If one generator fails, others pick up load without interrupting primary electrical services", "Lower cost"], correctOptionIndex: 1 },
  { id: 319, text: "In parallel system, each engine generator is connected to its own AC bus via what?", options: ["BTB", "Generator breaker (GB)", "Contactor"], correctOptionIndex: 1 },
  { id: 320, text: "If a generator goes out-of-phase, what happens?", options: ["System continues", "Its generator breaker opens, generator shuts down", "Warning light only"], correctOptionIndex: 1 },
  { id: 321, text: "External power cannot be paralleled with what?", options: ["APU generator", "Any of the aircraft's engine generators", "Battery"], correctOptionIndex: 1 },
  { id: 322, text: "The lamps dark method for paralleling means closing contactor when lamps are what?", options: ["Bright", "Out", "Flashing"], correctOptionIndex: 1 },
  { id: 323, text: "Attempting to parallel without meeting conditions results in what?", options: ["No effect", "Large circulating current, possible loss of power and damage", "Automatic correction"], correctOptionIndex: 1 },
  { id: 324, text: "In Boeing 727 manual paralleling, when No. 1 is selected for paralleling, the two lamps receive supplies from which phases?", options: ["All three phases", "Phases A and C of the two generators", "Phase B only"], correctOptionIndex: 1 },
  { id: 325, text: "In automatic paralleling, the device closes the GCB when frequency difference is less than what?", options: ["1 Hz", "3-5 Hz", "10 Hz"], correctOptionIndex: 1 },
  { id: 326, text: "Phase voltage difference must be less than what for automatic paralleling?", options: ["5 V", "10 V", "20 V"], correctOptionIndex: 1 },
  { id: 327, text: "Out-of-phase angle difference must be less than what for automatic paralleling?", options: ["45°", "90°", "180°"], correctOptionIndex: 1 },
  { id: 328, text: "To ensure each generator shares real and reactive components equally, how many load-sharing circuits are required?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 329, text: "A sensing current transformer (CT) is mounted where?", options: ["On neutral line", "On one phase line of the generator", "On the busbar"], correctOptionIndex: 1 },
  { id: 330, text: "The sensing loop current is always what value?", options: ["Maximum of CT secondary currents", "The average of CT secondary currents", "Minimum of CT secondary currents"], correctOptionIndex: 1 },
  { id: 331, text: "Reactive-load sharing control modifies what?", options: ["Generator speed", "Generator excitation", "Load"], correctOptionIndex: 1 },
  { id: 332, text: "Real-load sharing control modifies what?", options: ["Generator excitation", "Generator drive torque", "Voltage"], correctOptionIndex: 1 },
  { id: 333, text: "Two protection circuits found only in paralleled systems are what?", options: ["Overvoltage and undervoltage", "Overexcitation and under excitation", "Overfrequency and underfrequency"], correctOptionIndex: 1 },
  { id: 334, text: "If overexcitation is sensed, what happens?", options: ["Generator shuts down immediately", "BTB trips, generator feeds its own busbar in isolation", "Warning only"], correctOptionIndex: 1 },
  { id: 335, text: "Electrical load control unit (ELCU) connects what loads to the main generator?", options: ["Essential flight instruments", "Aircraft galley load and electrically driven hydraulic pumps", "Flight controls"], correctOptionIndex: 1 },
  { id: 336, text: "Load shedding ensures electrical loading stays within limits during what conditions?", options: ["Only normal conditions", "Both normal and abnormal operating conditions", "Only emergency"], correctOptionIndex: 1 },
  { id: 337, text: "Load reduction is achieved by selectively de-energising what?", options: ["Essential loads", "Non-essential loads and buses", "All loads"], correctOptionIndex: 1 },
  { id: 338, text: "Overvoltage protection typically trips at what voltage?", options: ["115 V", "130 V", "200 V"], correctOptionIndex: 1 },
  { id: 339, text: "Undervoltage protection typically trips at what voltage?", options: ["115 V", "100 V", "90 V"], correctOptionIndex: 1 },
  { id: 340, text: "Under-frequency protection typically trips at what frequency?", options: ["380 Hz", "365 Hz", "400 Hz"], correctOptionIndex: 1 },
  { id: 341, text: "Over-frequency protection typically trips at what frequency?", options: ["420 Hz", "430 Hz", "440 Hz"], correctOptionIndex: 1 },
  { id: 342, text: "Open phase protection trips when lowest phase is below what?", options: ["1 amp", "6 amps", "10 amps"], correctOptionIndex: 1 },
  { id: 343, text: "Differential protection compares what?", options: ["Voltage at generator and busbar", "Current going to and leaving the generator", "Frequency of different phases"], correctOptionIndex: 1 },
  { id: 344, text: "In differential protection, when fault current is typically what value, does relay energise?", options: ["5-10 amps", "20-40 amps", "50-100 amps"], correctOptionIndex: 1 },
  { id: 345, text: "Merz-Price system provides protection against what type of faults?", options: ["Overvoltage only", "Faults between phases or between one phase and ground", "Underfrequency only"], correctOptionIndex: 1 },
  { id: 346, text: "In Merz-Price system, two current transformers are connected where?", options: ["At the generator only", "One at each end of the line", "At the load only"], correctOptionIndex: 1 },
  { id: 347, text: "When currents at each end are equal, what happens?", options: ["Relay energises", "Induced EMFs are in balance, no current flows through relay coils", "System trips"], correctOptionIndex: 1 },
  { id: 348, text: "Three actions which will trip the GCR and GCB are what?", options: ["Overload, short circuit, ground fault", "Switching generator OFF, operating CSDU disconnect switch, pulling fire handle", "Low voltage, low frequency, high temperature"], correctOptionIndex: 1 },
  { id: 349, text: "GCUs and BPCU store fault results in what memory?", options: ["RAM", "Non-volatile memory (NVM)", "ROM"], correctOptionIndex: 1 },
  { id: 350, text: "The alphanumeric display on BPCU has how many characters?", options: ["16", "24", "32"], correctOptionIndex: 1 },
  { id: 351, text: "Pressing and releasing the BIT switch retrieves fault messages stored for how long?", options: ["Current flight only", "Stored in GCU and BPCU NVMs for faults detected", "Last 10 flights"], correctOptionIndex: 1 },
  { id: 352, text: "Previous flight data is retrievable for up to how many flights?", options: ["Three", "Six", "Ten"], correctOptionIndex: 1 },
  { id: 353, text: "The reset switch clears memories each time it is pushed. This action makes previous memory entries how?", options: ["Stored permanently", "Inaccessible", "Transferred to CMC"], correctOptionIndex: 1 },
  { id: 354, text: "Ground tests are selected from where on the CDU?", options: ["Main menu", "CMC menu", "Setup menu"], correctOptionIndex: 1 },
  { id: 355, text: "On Boeing 747 Classic flight engineer's panel, pressing the kVARS button allows meters to read what?", options: ["kW only", "kVAR instead of kW", "Volts"], correctOptionIndex: 1 },
  { id: 356, text: "On modern aircraft, electrical system control is so automated that flight deck controls are what?", options: ["Complex", "Very basic", "Manual only"], correctOptionIndex: 1 },
  { id: 357, text: "The electrical control panel on Airbus A320 is usually located where?", options: ["Pedestal", "Overhead panel", "Glareshield"], correctOptionIndex: 1 },
  { id: 358, text: "The generator drive disconnect button may be covered for what reason?", options: ["To prevent accidental use", "To prevent inadvertent operation", "For aesthetics"], correctOptionIndex: 1 },
  { id: 359, text: "The bus tie button connects left and right sides in what event?", options: ["Normal operation", "Generator failure, or supply from APU or external power", "Battery charging"], correctOptionIndex: 1 },
  { id: 360, text: "The external power light indicates what?", options: ["Power is connected", "External power is available", "Power is in use"], correctOptionIndex: 1 },
  { id: 361, text: "Galley services load-shed button disconnects what?", options: ["All galley power", "Non-essential services in galley during electrical supply failure", "Essential galley loads"], correctOptionIndex: 1 },
];
