import { Question } from "@shared/schema";

export const electrostaticDischargeQuestions: Question[] = [
  {
    id: 1,
    text: "Static electricity is best described as:",
    options: [
      "A flow of current through a conductor",
      "An electrical charge at rest stored on nonconductive materials",
      "A magnetic field generated by moving electrons"
    ],
    correctOptionIndex: 1
  },
  {
    id: 2,
    text: "Static charge is generated whenever two materials are:",
    options: [
      "Heated to a high temperature",
      "Rubbed together or pulled apart",
      "Immersed in a conductive liquid"
    ],
    correctOptionIndex: 1
  },
  {
    id: 3,
    text: "The miniature lightning shock experienced when walking on a nylon carpet and touching a door handle is an example of:",
    options: [
      "Electromagnetic induction",
      "A controlled electrical circuit",
      "Static electricity and its accompanying discharge"
    ],
    correctOptionIndex: 2
  },
  {
    id: 4,
    text: "The triboelectric series shows:",
    options: [
      "The resistance of different materials to static charge",
      "Different charge levels of materials with respect to cotton",
      "The temperature at which materials generate static"
    ],
    correctOptionIndex: 1
  },
  {
    id: 5,
    text: "According to the triboelectric series, what happens when two materials far apart on the table are brought together?",
    options: [
      "No discharge occurs",
      "A smaller charge and discharge",
      "A greater charge and more significant discharge"
    ],
    correctOptionIndex: 2
  },
  {
    id: 6,
    text: "What is the approximate static sensitivity range for a Field-effect transistor (MOS/FET)?",
    options: [
      "4,000 – 15,000 V",
      "150 – 1,000 V",
      "250 – 1,000 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 7,
    text: "Which device has the highest static sensitivity range (most resistant to damage)?",
    options: [
      "CMOS",
      "Thin film resistors",
      "Bipolar transistors"
    ],
    correctOptionIndex: 2
  },
  {
    id: 8,
    text: "The microscopic effect of an electrostatic discharge on a microelectronic circuit can resemble:",
    options: [
      "A perfectly smooth surface",
      "A bomb crater effect with rupturing of the oxide film",
      "A uniform discoloration"
    ],
    correctOptionIndex: 1
  },
  {
    id: 9,
    text: "At 10-20% relative humidity, walking over a carpet can generate up to:",
    options: [
      "1,500 V",
      "12,000 V",
      "35,000 V"
    ],
    correctOptionIndex: 2
  },
  {
    id: 10,
    text: "At 65-90% relative humidity, the static voltage generated by a worker at a bench is:",
    options: [
      "6,000 V",
      "1,500 V",
      "100 V"
    ],
    correctOptionIndex: 2
  },
  {
    id: 11,
    text: "Static electricity is primarily a:",
    options: [
      "Internal phenomenon within the material",
      "Surface phenomenon",
      "Magnetic phenomenon"
    ],
    correctOptionIndex: 1
  },
  {
    id: 12,
    text: "The first level of protection for electrostatic sensitive devices is usually:",
    options: [
      "A thick plastic coating",
      "Buffer or bypass circuitry designed into the devices",
      "The metal casing of the aircraft"
    ],
    correctOptionIndex: 1
  },
  {
    id: 13,
    text: "What are the two primary models used to characterise and classify the sensitivity of components to ESD?",
    options: [
      "The aircraft model and the ground crew model",
      "The human body model (HBM) and the charged device model (CDM)",
      "The high voltage model and the low voltage model"
    ],
    correctOptionIndex: 1
  },
  {
    id: 14,
    text: "The human body model (HBM) simulates an ESD event from:",
    options: [
      "A charged machine",
      "The discharge from the fingertip of a standing individual",
      "A charged device contacting a metal surface"
    ],
    correctOptionIndex: 1
  },
  {
    id: 15,
    text: "In the human body model (HBM), the capacitor used to represent the human body has a value of:",
    options: [
      "200 pF",
      "100 pF",
      "50 pF"
    ],
    correctOptionIndex: 1
  },
  {
    id: 16,
    text: "In the human body model (HBM), what is the value of the series resistor representing the body's resistance?",
    options: [
      "0 Ω",
      "1.5 kΩ",
      "1 MΩ"
    ],
    correctOptionIndex: 1
  },
  {
    id: 17,
    text: "The charged device model (CDM) simulates an event where:",
    options: [
      "A person touches a device",
      "A device becomes charged and then rapidly discharges to a conductive surface",
      "A machine with a capacitor discharges into a device"
    ],
    correctOptionIndex: 1
  },
  {
    id: 18,
    text: "A CDM discharge can be more destructive than HBM for some devices because:",
    options: [
      "It has a higher voltage",
      "The peak current can reach several tens of amperes in less than one nanosecond",
      "It uses a larger capacitor"
    ],
    correctOptionIndex: 1
  },
  {
    id: 19,
    text: "The machine model (MM) consists of a 200 pF capacitor discharged with:",
    options: [
      "A 1.5 kΩ series resistor",
      "No series DC resistor",
      "A 1 MΩ series resistor"
    ],
    correctOptionIndex: 1
  },
  {
    id: 20,
    text: "According to the HBM classification, what is the voltage range for Class 1A?",
    options: [
      "< 250 volts",
      "250 volts to < 500 volts",
      "500 volts to < 1,000 volts"
    ],
    correctOptionIndex: 1
  },
  {
    id: 21,
    text: "According to the HBM classification, what is the voltage range for Class 2?",
    options: [
      "1,000 volts to < 2,000 volts",
      "2,000 volts to < 4,000 volts",
      "4,000 volts to < 8,000 volts"
    ],
    correctOptionIndex: 1
  },
  {
    id: 22,
    text: "According to the CDM classification, which class covers components with sensitivity from 125 volts to < 250 volts?",
    options: [
      "Class C1",
      "Class C2",
      "Class C3"
    ],
    correctOptionIndex: 1
  },
  {
    id: 23,
    text: "According to the CDM classification, components with a sensitivity of ≥ 2,000 volts are classified as:",
    options: [
      "Class C5",
      "Class C6",
      "Class C7"
    ],
    correctOptionIndex: 2
  },
  {
    id: 24,
    text: "According to the table of source threats, which model is associated with the \"Operator\" as a threat source?",
    options: [
      "CDM only",
      "HBM only",
      "HBM, MM, and CDM"
    ],
    correctOptionIndex: 2
  },
  {
    id: 25,
    text: "A \"hard failure\" caused by ESD results in:",
    options: [
      "An intermittent fault that is difficult to detect",
      "A catastrophic failure that is easily detected",
      "A temporary performance degradation"
    ],
    correctOptionIndex: 1
  },
  {
    id: 26,
    text: "\"Soft failures\" are caused by ESD at much lower voltages, typically:",
    options: [
      "100 V – 150 V",
      "25 V – 30 V",
      "4,000 V – 15,000 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 27,
    text: "Soft failures are more challenging to detect and remedy because they:",
    options: [
      "Cause visible physical damage",
      "Lead to latent, intermittent faults",
      "Immediately destroy the component"
    ],
    correctOptionIndex: 1
  },
  {
    id: 28,
    text: "Which type of device is particularly prone to damage from ESD, with voltages as low as 100 V causing hard failure?",
    options: [
      "Bipolar transistors",
      "Silicon controlled rectifiers",
      "Unipolar devices such as CMOS or FET"
    ],
    correctOptionIndex: 2
  },
  {
    id: 29,
    text: "A latent defect from a soft failure may cause a product to:",
    options: [
      "Fail immediately during final inspection",
      "Pass inspection but later cause mysterious problems for the customer",
      "Have a completely dead circuit"
    ],
    correctOptionIndex: 1
  },
  {
    id: 30,
    text: "How are assemblies containing ESDs typically identified?",
    options: [
      "With a red paint mark",
      "With special decals affixed to packaging and assemblies",
      "With a barcode on the back"
    ],
    correctOptionIndex: 1
  },
  {
    id: 31,
    text: "What is the purpose of the packaging used for ESD devices?",
    options: [
      "To be completely rigid",
      "To be made from a quasi-conductive material that bleeds off charges in milliseconds",
      "To be fully insulating to prevent any charge movement"
    ],
    correctOptionIndex: 1
  },
  {
    id: 32,
    text: "What is \"pink poly\"?",
    options: [
      "A type of coloured foam for cushioning",
      "A polyethylene resin impregnated with an organic antistatic substance",
      "A conductive aluminium bag"
    ],
    correctOptionIndex: 1
  },
  {
    id: 33,
    text: "What is the purpose of a \"shunt\" placed over the edge connector of a PCB?",
    options: [
      "To protect against physical damage only",
      "To keep all connector contacts at the same potential and protect against physical damage",
      "To provide a handle for insertion"
    ],
    correctOptionIndex: 1
  },
  {
    id: 34,
    text: "For complete electronic box assemblies, protective covers over connectors are often treated with:",
    options: [
      "A permanent rubber coating",
      "A liquid conducting film that has a certain life",
      "A thick layer of insulating paint"
    ],
    correctOptionIndex: 1
  },
  {
    id: 35,
    text: "If a non-conductive cover is used on an ESDS unit's connector, what must be indicated on it?",
    options: [
      "The part number",
      "The treatment date",
      "The manufacturer's name"
    ],
    correctOptionIndex: 1
  },
  {
    id: 36,
    text: "A static-free work station includes a conducting work surface connected to:",
    options: [
      "The positive terminal of a battery",
      "The ground via a conducting mat",
      "A high voltage source"
    ],
    correctOptionIndex: 1
  },
  {
    id: 37,
    text: "What must an operative wear when handling ESDS devices at a work station?",
    options: [
      "Cotton gloves",
      "A grounded wrist strap on their bare wrist",
      "Rubber-soled shoes only"
    ],
    correctOptionIndex: 1
  },
  {
    id: 38,
    text: "What is the purpose of an ioniser at a static-free work station?",
    options: [
      "To increase the humidity",
      "To neutralise incidental charges on devices or assemblies",
      "To provide a bright light source"
    ],
    correctOptionIndex: 1
  },
  {
    id: 39,
    text: "An ioniser generates:",
    options: [
      "Only negative ions",
      "Positive and negative ions and blows the charged air across the work area",
      "Ozone to clean the air"
    ],
    correctOptionIndex: 1
  },
  {
    id: 40,
    text: "According to the wrist strap warning, what must be true of the grounding lead resistance?",
    options: [
      "It must be less than 1 ohm",
      "It must be greater than 1 Megohm",
      "It must be exactly 1,500 ohms"
    ],
    correctOptionIndex: 1
  },
  {
    id: 41,
    text: "When removing a card containing ESDS devices, the wrist strap should be connected to:",
    options: [
      "Any metal part of the aircraft structure",
      "A convenient grounding point on the unit containing the card (e.g., an electrostatic jack point)",
      "The battery negative terminal"
    ],
    correctOptionIndex: 1
  },
  {
    id: 42,
    text: "The wrist strap used for ESD protection contains:",
    options: [
      "A high voltage capacitor",
      "A slow-discharge resistor",
      "A battery"
    ],
    correctOptionIndex: 1
  },
  {
    id: 43,
    text: "How often should the wrist strap resistor be tested to ensure its resistance is a minimum of 1 Megohm?",
    options: [
      "Annually",
      "Before every use, or at a minimum daily",
      "Only when a failure occurs"
    ],
    correctOptionIndex: 1
  },
  {
    id: 44,
    text: "What should be used to seal a conductive bag containing an ESDS PCB?",
    options: [
      "Staples",
      "Adhesive tape",
      "An integral plastic zip mechanism or 100% cotton twine"
    ],
    correctOptionIndex: 2
  },
  {
    id: 45,
    text: "When removing or installing complete metal-encased ESDS LRUs, why is it often not necessary to wear a wrist strap?",
    options: [
      "Because the unit is not sensitive",
      "Because the metallic mass of the component can serve as a ground for discharging any static",
      "Because the unit is always powered on"
    ],
    correctOptionIndex: 1
  },
  {
    id: 46,
    text: "When handling a metal-encased ESDS LRU, what caution is given regarding connector pins?",
    options: [
      "They should be cleaned with alcohol",
      "Do not touch the connector pins or other exposed conductors",
      "They should be shorted together with a wire"
    ],
    correctOptionIndex: 1
  },
  {
    id: 47,
    text: "What is the first step before removing a PCB containing ESDS devices?",
    options: [
      "Remove the wrist strap",
      "Remove the system electrical power and tag it",
      "Open the conductive bag"
    ],
    correctOptionIndex: 1
  },
  {
    id: 48,
    text: "After removing a PCB, what should be done immediately?",
    options: [
      "Test it on the bench",
      "Insert it into a conductive bag and identify it with an ESDS label",
      "Place it on a metal workbench"
    ],
    correctOptionIndex: 1
  },
  {
    id: 49,
    text: "According to the removal procedure, staples and adhesive tape should not be used to close a conductive bag because:",
    options: [
      "They are too expensive",
      "Damage to the bag may expose the PCB to electrostatic discharge",
      "They are difficult to remove"
    ],
    correctOptionIndex: 1
  },
  {
    id: 50,
    text: "After bagging a removed PCB, it should be placed in a rigid container to:",
    options: [
      "Make it easier to carry",
      "Maintain the integrity of the conductive bag during transportation",
      "Allow for better organisation"
    ],
    correctOptionIndex: 1
  },
  {
    id: 51,
    text: "Before installing a new PCB, what must be checked regarding the new part?",
    options: [
      "Its weight",
      "The documentation (EASA Form 1), part number, and serial number",
      "Its colour"
    ],
    correctOptionIndex: 1
  },
  {
    id: 52,
    text: "When removing a new PCB from its conductive bag, what caution must be observed?",
    options: [
      "Do not expose it to sunlight",
      "Do not touch connector pins or other exposed conductors",
      "Do not remove the bag until the power is on"
    ],
    correctOptionIndex: 1
  },
  {
    id: 53,
    text: "What should be done after installing a replacement PCB?",
    options: [
      "Immediately close the unit without testing",
      "Reinstall power and carry out a functional check or BIT check per the AMM",
      "Disconnect the wrist strap before securing the unit"
    ],
    correctOptionIndex: 1
  },
  {
    id: 54,
    text: "Before installing a PCB, the inside of the receptacle should be inspected for:",
    options: [
      "The correct colour of the slideways",
      "Clear slideways, undamaged connectors, and signs of contamination or burning",
      "The presence of a wrist strap jack"
    ],
    correctOptionIndex: 1
  },
  {
    id: 55,
    text: "During PCB installation, the technician should use the provided extractors to:",
    options: [
      "Lift the board out",
      "Slide the board effortlessly into position",
      "Test the board's function"
    ],
    correctOptionIndex: 1
  },
  {
    id: 56,
    text: "When removing a metal-encased LRU with an ESDS label, what should be done immediately after removal?",
    options: [
      "Place it on a conductive mat",
      "Install dust caps on all connectors without touching the pins",
      "Connect it to a wrist strap"
    ],
    correctOptionIndex: 1
  },
  {
    id: 57,
    text: "What is the caution regarding connector pins when removing a metal-encased ESDS LRU?",
    options: [
      "Clean them with a brush",
      "Do not touch the connector pins or other exposed conductors",
      "Apply conductive grease to them"
    ],
    correctOptionIndex: 1
  },
  {
    id: 58,
    text: "When installing a metal-encased ESDS LRU, what must be checked on the unit before installation?",
    options: [
      "The weight",
      "The unit for any signs of damage and the store's documentation (EASA Form 1)",
      "The colour of the dust caps"
    ],
    correctOptionIndex: 1
  },
  {
    id: 59,
    text: "On equipment containing circuits carrying more than 50 V (RMS or DC), what is the maximum acceptable contact resistance for bonding?",
    options: [
      "0.5 ohms",
      "0.05 ohms",
      "1.0 ohms"
    ],
    correctOptionIndex: 1
  },
  {
    id: 60,
    text: "What is the primary risk during aircraft refuelling and de-fuelling?",
    options: [
      "Fuel spillage onto the ramp",
      "Unintended ignition of fuel vapour by a single spark",
      "Damage to the fuel hose"
    ],
    correctOptionIndex: 1
  },
  {
    id: 61,
    text: "A spark of sufficient intensity to ignite fuel vapour can result from:",
    options: [
      "Static discharge from a mobile phone only",
      "Discharge of electrostatic energy created from fuel movement or accumulation on surfaces",
      "The heat of the engine"
    ],
    correctOptionIndex: 1
  },
  {
    id: 62,
    text: "What is the purpose of electrical bonding during refuelling?",
    options: [
      "To ensure the fuel flows faster",
      "To eliminate the hazard of accumulated surface static charge",
      "To ground the aircraft's electrical system"
    ],
    correctOptionIndex: 1
  },
  {
    id: 63,
    text: "When must bonding cables be connected during refuelling?",
    options: [
      "After the filler caps are removed",
      "Before filler caps are removed and before the start of fuelling",
      "Only after a static discharge is observed"
    ],
    correctOptionIndex: 1
  },
  {
    id: 64,
    text: "When should bonding cables be disconnected after refuelling?",
    options: [
      "Immediately after fuelling starts",
      "After fuelling is complete and the filler caps have been replaced",
      "Before the fuel truck drives away"
    ],
    correctOptionIndex: 1
  },
  {
    id: 65,
    text: "Can conductive fuel hoses be used as a substitute for dedicated bonding clips and wires?",
    options: [
      "Yes, they are designed for this purpose",
      "No, they are not suitable substitutes",
      "Yes, but only for small aircraft"
    ],
    correctOptionIndex: 1
  },
  {
    id: 66,
    text: "What is the function of a static dissipater additive in turbine fuel?",
    options: [
      "To increase the fuel's octane rating",
      "To reduce the risk of ignition from electrostatic discharge inside the tank",
      "To make the fuel burn cleaner"
    ],
    correctOptionIndex: 1
  },
  {
    id: 67,
    text: "Where should the bonding cable be connected on the aircraft?",
    options: [
      "To the fuel hydrant pit",
      "To designated points or clean unpainted metal surfaces on the airframe",
      "To the aircraft's main battery"
    ],
    correctOptionIndex: 1
  },
  {
    id: 68,
    text: "On no account should either the fuelling vehicle or the aircraft be bonded to:",
    options: [
      "The ground",
      "The fuel hydrant pit",
      "Each other"
    ],
    correctOptionIndex: 2
  },
  {
    id: 69,
    text: "What is a particular concern regarding personal electronic devices (PEDs) during refuelling?",
    options: [
      "They can distract the crew",
      "Below-specification mobile telephone batteries that may fail dangerously",
      "They can cause fuel to spill"
    ],
    correctOptionIndex: 1
  },
  {
    id: 70,
    text: "PEDs close to or onboard modern aircraft may interfere with:",
    options: [
      "The cabin lighting",
      "Fuel gauges, navigation equipment, and cause false fire warnings",
      "The seat recline mechanism"
    ],
    correctOptionIndex: 1
  },
  {
    id: 71,
    text: "What is recommended regarding PEDs in the apron area during refuelling operations?",
    options: [
      "They should be used only for emergency calls",
      "They should be prohibited in the vicinity of refuelling operations",
      "They should be kept in a metal container"
    ],
    correctOptionIndex: 1
  },
  {
    id: 72,
    text: "If refuelling is permitted with passengers on board, what must aircraft operators have?",
    options: [
      "A special fuelling truck",
      "Their own procedures, including emergency evacuation, in the operations and cabin crew manuals",
      "Permission from air traffic control"
    ],
    correctOptionIndex: 1
  },
  {
    id: 73,
    text: "When refuelling with passengers on board, who should remain on the flight deck?",
    options: [
      "All flight crew",
      "At least one flight crew member",
      "No flight crew members"
    ],
    correctOptionIndex: 1
  },
  {
    id: 74,
    text: "What is the purpose of the classification system for ESD sensitivity?",
    options: [
      "To determine the price of the component",
      "To allow easy grouping and indicate the level of ESD protection required",
      "To identify the manufacturer of the component"
    ],
    correctOptionIndex: 1
  },
  {
    id: 75,
    text: "A fully characterised component should be classified using which models?",
    options: [
      "HBM and MM",
      "HBM and CDM",
      "MM and CDM"
    ],
    correctOptionIndex: 1
  },
  {
    id: 76,
    text: "What is the purpose of a wrist strap's grounding lead resistance being greater than 1 Megohm?",
    options: [
      "To allow a high current to flow",
      "To protect the wearer from shock hazard in case of contact with high voltage",
      "To ensure a faster discharge"
    ],
    correctOptionIndex: 1
  },
  {
    id: 77,
    text: "Why is it important that staples and adhesive tape are not used to close conductive bags?",
    options: [
      "They are difficult to open",
      "They can damage the bag, exposing the PCB to electrostatic discharge",
      "They are too conductive"
    ],
    correctOptionIndex: 1
  },
  {
    id: 78,
    text: "What should be used to transport a bagged ESDS PCB?",
    options: [
      "A cardboard box without any padding",
      "A rigid container to maintain the bag's integrity",
      "A plastic grocery bag"
    ],
    correctOptionIndex: 1
  },
  {
    id: 79,
    text: "When installing a PCB, why must the technician not touch the connector pins?",
    options: [
      "To avoid leaving fingerprints",
      "To prevent electrostatic damage to components",
      "To prevent corrosion"
    ],
    correctOptionIndex: 1
  },
  {
    id: 80,
    text: "What is a \"latent failure\" in the context of ESD damage?",
    options: [
      "A failure that occurs immediately",
      "A failure that is intermittent and difficult to detect",
      "A failure that causes the device to catch fire"
    ],
    correctOptionIndex: 1
  },
  {
    id: 81,
    text: "According to the table of source threats, which model is associated with the \"Device package\"?",
    options: [
      "HBM",
      "MM",
      "CDM"
    ],
    correctOptionIndex: 2
  },
  {
    id: 82,
    text: "According to the table of source threats, which models are associated with \"Mate/de-mate of harness\"?",
    options: [
      "HBM only",
      "HBM, MM, and CDM",
      "MM only"
    ],
    correctOptionIndex: 1
  },
  {
    id: 83,
    text: "In a static-free work station, what is the purpose of a conductive chair or stool?",
    options: [
      "For comfort",
      "To be grounded, preventing static build-up on the operative",
      "To provide a place to store tools"
    ],
    correctOptionIndex: 1
  },
  {
    id: 84,
    text: "What is the typical life of a liquid conducting film sprayed on protective covers?",
    options: [
      "Permanent",
      "Has a certain life, requiring the treatment date to be indicated",
      "Only one week"
    ],
    correctOptionIndex: 1
  },
  {
    id: 85,
    text: "What is the purpose of a conductive foam material used to store devices?",
    options: [
      "To provide cushioning only",
      "To short the leads or pins together and protect against static, without causing corrosion",
      "To clean the leads"
    ],
    correctOptionIndex: 1
  },
  {
    id: 86,
    text: "What is the function of the aluminium layer in some ESD bags?",
    options: [
      "To make the bag transparent",
      "To provide a conductive shield",
      "To make the bag stronger"
    ],
    correctOptionIndex: 1
  },
  {
    id: 87,
    text: "Why must all test data sheets and documentation at a work station be in antistatic envelopes?",
    options: [
      "To keep them organised",
      "To prevent them from becoming charged and causing an ESD event",
      "To protect them from spills"
    ],
    correctOptionIndex: 1
  },
  {
    id: 88,
    text: "What is the typical static voltage generated by a common poly bag picked up from a bench at 10-20% relative humidity?",
    options: [
      "1,200 V",
      "20,000 V",
      "600 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 89,
    text: "What is the typical static voltage generated by a worker at a bench at 10-20% relative humidity?",
    options: [
      "100 V",
      "6,000 V",
      "1,500 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 90,
    text: "Why is static an ever-present hazard in handling microelectronic devices?",
    options: [
      "Because static is invisible",
      "Because the handling time is much shorter than the static bleed-off time",
      "Because microelectronic devices generate static"
    ],
    correctOptionIndex: 1
  },
  {
    id: 91,
    text: "What is the sensitivity range for thin film resistors?",
    options: [
      "4,000 – 15,000 V",
      "150 – 1,000 V",
      "250 – 1,000 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 92,
    text: "According to the HBM classification, what is the voltage range for Class 3A?",
    options: [
      "2,000 volts to < 4,000 volts",
      "4,000 volts to < 8,000 volts",
      "≥ 8,000 volts"
    ],
    correctOptionIndex: 1
  },
  {
    id: 93,
    text: "According to the CDM classification, which class covers components with sensitivity from 1,000 volts to < 1,500 volts?",
    options: [
      "Class C4",
      "Class C5",
      "Class C6"
    ],
    correctOptionIndex: 1
  },
  {
    id: 94,
    text: "What is the sensitivity range for CMOS?",
    options: [
      "150 – 1,000 V",
      "250 – 1,000 V",
      "4,000 – 15,000 V"
    ],
    correctOptionIndex: 0
  },
  {
    id: 95,
    text: "What is the sensitivity range for silicon controlled rectifiers?",
    options: [
      "150 – 1,000 V",
      "4,000 – 15,000 V",
      "250 – 1,000 V"
    ],
    correctOptionIndex: 1
  },
  {
    id: 96,
    text: "According to the table of source threats, which models are associated with \"Automatic test equipment\"?",
    options: [
      "HBM and CDM",
      "MM and CDM",
      "HBM and MM"
    ],
    correctOptionIndex: 1
  },
  {
    id: 97,
    text: "According to the table of source threats, which models are associated with \"Pick and place machine\"?",
    options: [
      "HBM only",
      "MM and CDM",
      "HBM, MM, and CDM"
    ],
    correctOptionIndex: 2
  },
  {
    id: 98,
    text: "What is the purpose of the \"slow-discharge resistor\" in a wrist strap?",
    options: [
      "To increase the discharge current",
      "To limit the current during an ESD event, protecting the device and the wearer",
      "To store energy"
    ],
    correctOptionIndex: 1
  },
  {
    id: 99,
    text: "When removing a PCB, what should be done if it feels obstructed?",
    options: [
      "Pull harder to free it",
      "Check for any possible obstruction and clear it",
      "Cut the board to remove it"
    ],
    correctOptionIndex: 1
  },
  {
    id: 100,
    text: "During fuelling, what is recommended if wide-cut fuel is being supplied or is already present in the tanks?",
    options: [
      "Increase the fuel flow rate",
      "Substantially reduce the fuel flow rate",
      "Add more static dissipater additive"
    ],
    correctOptionIndex: 1
  }
];
