export const euRegulation965Questions = [
  {
    id: 1,
    text: "What is the main objective of Regulation (EU) No 965/2012?",
    options: ["To standardize airport security screening procedures.", "To ensure a high level of safety in civil aviation throughout the EU.", "To regulate the licensing of all European pilots."],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "Regulation (EU) No 965/2012 is also known by which of the following names?",
    options: ["The Basic Regulation.", "The Airworthiness Directive Regulation.", "The Air Operations Regulation or IR-OPS."],
    correctOptionIndex: 2,
  },
  {
    id: 3,
    text: "The implementation of the Air Operations Regulation requires airlines to establish which proactive safety system?",
    options: ["A Quality Control system.", "A Safety Management System (SMS).", "A Flight Time Limitation scheme."],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "According to the document, what is one of the key impacts of Regulation (EU) No 965/2012 on the aviation industry?",
    options: ["It has led to a standardized framework for air operations across the EU.", "It has increased the number of individual national regulations.", "It has reduced the need for aircraft maintenance."],
    correctOptionIndex: 0,
  },
  {
    id: 5,
    text: "How many annexes (parts) does Regulation (EU) No 965/2012 consist of?",
    options: ["Six annexes.", "Eight annexes.", "Ten annexes."],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "What is the primary focus of the articles within Regulation (EU) No 965/2012?",
    options: ["To provide definitions for terms used in the annexes.", "To establish organisational requirements for air operators.", "To lay down the subject matter, scope, and definitions for the regulation."],
    correctOptionIndex: 2,
  },
  {
    id: 7,
    text: "To which types of aircraft does Regulation (EU) No 965/2012 NOT apply?",
    options: ["Sailplanes.", "Airships.", "Helicopters."],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "According to the document, what are the four general types of air operations defined by the Regulation?",
    options: ["CAT, NCC, NCO, and SPO.", "Commercial, Private, Military, and Cargo.", "VFR, IFR, Night, and Specialized."],
    correctOptionIndex: 0,
  },
  {
    id: 9,
    text: "What is the definition of a 'commercial operation'?",
    options: ["Any operation of an aircraft for public service.", "Any operation of an aircraft, in return for remuneration or other valuable consideration, which is available to the public.", "An operation to transport passengers, cargo, or mail for remuneration."],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "How is 'commercial air transport (CAT) operation' specifically defined?",
    options: ["An aircraft operation to transport passengers, cargo, or mail for remuneration or other valuable consideration.", "Any operation of an aircraft for hire or reward.", "An operation where the customer has no control over the operator."],
    correctOptionIndex: 0,
  },
  {
    id: 11,
    text: "An aeroplane with a maximum certificated take-off mass exceeding 5,700 kg is classified as:",
    options: ["A complex motor-powered aircraft.", "A large aircraft.", "An other-than-complex motor-powered aircraft."],
    correctOptionIndex: 0,
  },
  {
    id: 12,
    text: "A helicopter certificated for a maximum take-off mass exceeding 3,175 kg is considered:",
    options: ["A transport helicopter.", "A complex motor-powered aircraft.", "A heavy helicopter."],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "What term is used for aircraft that do not meet the criteria for a complex motor-powered aircraft?",
    options: ["Light aircraft.", "Simple aircraft.", "Other-than-complex motor-powered aircraft."],
    correctOptionIndex: 2,
  },
  {
    id: 14,
    text: "The term 'specialised operations (SPO)' includes activities such as:",
    options: ["Low-visibility approaches.", "Aerial work, parachute dropping, or towing gliders.", "Transport of passengers on scheduled flights."],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "Annex I of Regulation (EU) No 965/2012 is known as Part-DEF. What does it contain?",
    options: ["Requirements for commercial air transport operations.", "Definitions for terms used in Annexes II-VIII.", "Authority requirements for air operations."],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "Annex II (Part-ARO) establishes requirements for whom?",
    options: ["Air operators.", "The national aviation authorities of EASA member states.", "Aircraft maintenance organisations."],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "Which annex lays down the organisational requirements for an air operator, including the rules for an Air Operator Certificate (AOC)?",
    options: ["Annex II (Part-ARO).", "Annex III (Part-ORO).", "Annex IV (Part-CAT)."],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "Part-CAT (Annex IV) applies to which type of operations?",
    options: ["Non-commercial operations with complex motor-powered aircraft.", "Commercial air transport operations.", "Specialised operations."],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "An operator wishing to conduct Extended Range Operations (ETOPS) must comply with the requirements of which annex?",
    options: ["Annex IV (Part-CAT).", "Annex V (Part-SPA).", "Annex VIII (Part-SPO)."],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "Annex VI (Part-NCC) provides requirements for:",
    options: ["Non-commercial air operations with complex motor-powered aircraft.", "Commercial air transport operations.", "Specialised operations with balloons."],
    correctOptionIndex: 0,
  },
  {
    id: 21,
    text: "Part-NCO (Annex VII) applies to which of the following operations?",
    options: ["Non-commercial operations with other-than-complex motor-powered aircraft.", "Commercial operations with other-than-complex motor-powered aircraft.", "All specialised operations."],
    correctOptionIndex: 0,
  },
  {
    id: 22,
    text: "Part-SPO (Annex VIII) establishes operational requirements for:",
    options: ["Commercial air transport operations only.", "Non-commercial operations with complex aircraft only.", "Specialised operations."],
    correctOptionIndex: 2,
  },
  {
    id: 23,
    text: "What is an Air Operator Certificate (AOC)?",
    options: ["A certificate that an aircraft is airworthy.", "An approval granted to an operator to allow it to use aircraft for commercial purposes.", "A licence for a pilot to operate commercially."],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "The requirements for obtaining an AOC include:",
    options: ["Having a minimum of 10 aircraft in the fleet.", "Having sufficient personnel, airworthy aircraft, and a quality system.", "Operating only within the borders of one's own country."],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "An AOC remains valid subject to the operator remaining in compliance and:",
    options: ["The certificate being renewed every 2 years.", "The certificate not being surrendered or revoked.", "The operator maintaining a fleet of at least 5 aircraft."],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "What is Flight Data Monitoring (FDM)?",
    options: ["A mandatory system for all commercial aircraft to record cockpit voice.", "The systematic, proactive use of digital flight data from routine operations to improve aviation safety.", "A system used only for accident investigation."],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "For which aeroplanes must an operator establish and maintain a Flight Data Monitoring system?",
    options: ["All turbo-jet aeroplanes.", "Aeroplanes with a maximum certificated take-off mass of more than 27,000 kg.", "Aeroplanes with an MOPSC of more than 19."],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "The operator's Minimum Equipment List (MEL) is based on which document?",
    options: ["The Aircraft Flight Manual (AFM).", "The Master Minimum Equipment List (MMEL).", "The Configuration Deviation List (CDL)."],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "What must an operator establish for each inoperative item listed in the MEL?",
    options: ["An immediate repair before the next flight.", "A rectification interval.", "A new flight manual procedure."],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "For commercial air transport, technical crew members in HEMS operations must be:",
    options: ["At least 21 years of age.", "Checked as proficient to perform assigned duties.", "Licensed pilots."],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "Who bears the legal responsibility for the continuing airworthiness of an aircraft according to EU regulations?",
    options: ["The pilot-in-command.", "The owner or, if designated by contract, the lessee.", "The maintenance organisation that last worked on it."],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "A Continuing Airworthiness Management Organisation (CAMO) is responsible for:",
    options: ["Piloting the aircraft.", "Developing and controlling a maintenance programme for the aircraft.", "Providing in-flight catering services."],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "According to CAT.GEN.MPA.125, who is permitted to taxi an aeroplane on the movement area of an aerodrome?",
    options: ["Any member of the ground crew.", "An appropriately qualified pilot or a person trained and designated by the operator.", "Only the pilot-in-command."],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "Which document must be carried on each flight as an original or copy?",
    options: ["The pilot's personal logbook.", "The original Certificate of Airworthiness.", "The aircraft's maintenance schedule."],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "Following an accident, how long must the operator preserve the original flight recorder recordings, unless otherwise directed?",
    options: ["30 days.", "60 days.", "90 days."],
    correctOptionIndex: 2,
  },
  {
    id: 36,
    text: "Under CAT.OP.MPA.195, when is refuelling with passengers on board prohibited?",
    options: ["When using any type of jet fuel.", "When using Avgas or wide-cut fuel.", "During night operations."],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "The commander must not start a take-off if the aircraft is contaminated with:",
    options: ["Any deposit that might adversely affect performance or controllability.", "More than a trace of frost.", "Any amount of rain."],
    correctOptionIndex: 0,
  },
  {
    id: 38,
    text: "Mass and balance principles require that the loading, mass, and CG of an aircraft comply with limitations specified in the:",
    options: ["Minimum Equipment List.", "Aircraft Flight Manual or Operations Manual.", "Certificate of Registration."],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "How often must an aircraft's mass and CG be established by actual weighing if individual aircraft masses are used?",
    options: ["Every 2 years.", "Every 4 years.", "Every 9 years."],
    correctOptionIndex: 2,
  },
  {
    id: 40,
    text: "The accuracy of weighing equipment for a scale load below 2,000 kg should be:",
    options: ["± 0.1%.", "± 20 kg.", "± 1%."],
    correctOptionIndex: 2,
  },
  {
    id: 41,
    text: "If the number of passenger seats available is less than 10 for aeroplanes, passenger mass may be calculated based on:",
    options: ["A standard mass of 88 kg for all adults.", "A statement by or on behalf of each passenger, plus a predetermined mass for hand baggage and clothing.", "The average mass from the last 100 flights."],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "Which document, manual, or information may be retained at the aerodrome for local VFR day flights with other-than-complex aircraft?",
    options: ["The Certificate of Airworthiness.", "The Aircraft Flight Manual.", "The Noise Certificate."],
    correctOptionIndex: 2,
  },
  {
    id: 43,
    text: "A flight cannot be started when any required instrument is inoperative unless:",
    options: ["The commander gives special permission.", "The aeroplane is operated per the operator's approved MEL.", "The next maintenance base is less than one hour away."],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "According to CAT.IDE.A.110, the number of spare fuses required for each rating is the higher of 10% or:",
    options: ["One fuse for each rating.", "Three fuses for each rating.", "Five fuses for each rating."],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "Aeroplanes with an MCTOM of more than 5,700 kg must be equipped at each pilot station with:",
    options: ["A head-up display.", "A means to maintain a clear portion of the windshield during precipitation.", "An additional attitude indicator."],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "Turbine-powered aeroplanes with an MCTOM of more than 5,700 kg or an MOPSC of more than 19 must be equipped with:",
    options: ["A ground proximity warning system.", "An airborne collision avoidance system (ACAS II).", "A weather radar."],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "For aeroplanes first issued with a C of A on or after 1 April 1998, the cockpit voice recorder must be capable of retaining data for at least:",
    options: ["The preceding 30 minutes.", "The preceding 2 hours.", "The preceding 25 hours."],
    correctOptionIndex: 2,
  },
  {
    id: 48,
    text: "When must a flight data recorder (FDR) start recording?",
    options: ["After take-off when the aircraft reaches 10,000 feet.", "Before the aeroplane is capable of moving under its own power.", "Once the aircraft is airborne."],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "The number of first-aid kits required for an aeroplane with 150 passenger seats installed is:",
    options: ["1.", "2.", "3."],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "An emergency medical kit is required for aeroplanes with an MOPSC of more than 30 when the planned route is more than how far from an aerodrome with medical assistance?",
    options: ["30 minutes flying time.", "60 minutes flying time.", "120 minutes flying time."],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "Pressurised aeroplanes operated above 25,000 ft with a cabin crew must have first-aid oxygen for what percentage of passengers?",
    options: ["1%.", "2%.", "5%."],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "Aeroplanes with an MOPSC of more than 60 and carrying at least one passenger must be equipped with how many megaphones?",
    options: ["1 for 61-99 seats, 2 for 100 or more.", "2 for all configurations.", "1 for every 50 passengers."],
    correctOptionIndex: 0,
  },
  {
    id: 53,
    text: "Aeroplanes with an MOPSC of more than nine are equipped with an emergency lighting system to:",
    options: ["Provide reading lights for all passengers.", "Facilitate the evacuation of the aeroplane.", "Illuminate the cabin during night flights."],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "Landplanes operated over water at a distance of more than 50 NM from shore must be equipped with:",
    options: ["A life-raft for all persons on board.", "A life-jacket for each person on board.", "A survival ELT."],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "Aeroplanes operated over water at a distance greater than 120 minutes from land must be equipped with:",
    options: ["Life rafts in sufficient numbers to carry all persons on board.", "An additional crew member.", "A water landing procedure in the manual."],
    correctOptionIndex: 0,
  },
  {
    id: 56,
    text: "Which of the following is NOT required equipment for an aeroplane operated under VFR by day?",
    options: ["A means of measuring and displaying magnetic heading.", "A means of measuring and displaying Mach number.", "A means of measuring and displaying vertical speed."],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "The emergency lighting system for aeroplanes with an MOPSC of more than 19 must include:",
    options: ["Individual passenger reading lights.", "Illuminated emergency exit marking and locating signs.", "Strobe lights on the wingtips."],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "Crash axes or crowbars in the passenger compartment must not be:",
    options: ["Used by flight attendants.", "Visible to passengers.", "Painted in bright colours."],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "Aeroplanes with passenger emergency exit sill heights of more than 1.83 m (6 ft) must be equipped with:",
    options: ["An evacuation slide.", "A warning horn.", "A secondary exit."],
    correctOptionIndex: 0,
  },
  {
    id: 60,
    text: "The ELT required for modern aircraft must be able to transmit simultaneously on 121.5 MHz and which other frequency?",
    options: ["243.0 MHz.", "406 MHz.", "121.6 MHz."],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "RVSM allows for a reduced vertical separation minimum of 1,000 ft between which flight levels?",
    options: ["FL 180 and FL 280.", "FL 290 and FL 410.", "FL 350 and FL 600."],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "To obtain RVSM operational approval, an operator must provide evidence that includes:",
    options: ["A minimum fleet size of 10 aircraft.", "RVSM airworthiness approval has been obtained.", "All pilots have over 5,000 hours of flight time."],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "What equipment is required for operations in RVSM airspace?",
    options: ["A weather radar system.", "Two independent altitude measurement systems and an altitude alerting system.", "A GPS with terrain mapping."],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "The skin area around which component is considered an RVSM critical area requiring special inspections?",
    options: ["The cockpit windows.", "The static vents.", "The landing gear doors."],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "What does the acronym ETOPS stand for?",
    options: ["Extended-range Twin-engine Operational Performance Standards.", "Extended-range Twin Operations.", "Extended Range Operations with Two-Engine Aeroplanes."],
    correctOptionIndex: 2,
  },
  {
    id: 66,
    text: "An ETOPS maintenance programme must include procedures to:",
    options: ["Reduce the frequency of A-checks.", "Preclude identical action applied to multiple similar elements in any ETOPS critical system.", "Allow only licensed engineers to work on the aircraft."],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "An ETOPS service check should be accomplished and signed off:",
    options: ["Once a month.", "Immediately before an ETOPS flight.", "After every third flight."],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "In the context of Low Visibility Operations, what is a Decision Height (DH)?",
    options: ["The height at which the landing gear must be extended.", "The lowest height at which a missed approach must be initiated if the required visual reference is not established.", "The minimum altitude for go-around manoeuvres."],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "A CAT I ILS approach requires a Decision Height of not less than:",
    options: ["100 ft.", "200 ft.", "50 ft."],
    correctOptionIndex: 0,
  },
  {
    id: 70,
    text: "For a CAT II operation, the RVR requirement is:",
    options: ["Not less than 550 m.", "Not less than 350 m.", "Not less than 200 m."],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "Which system is mandatory for performing CAT III operations?",
    options: ["A flight director system.", "An automatic landing system.", "A head-up display (HUD)."],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "For CAT III operations, a fail-operational automatic landing system is required for decision heights below:",
    options: ["200 ft.", "100 ft.", "50 ft."],
    correctOptionIndex: 2,
  },
  {
    id: 73,
    text: "What is the foundation for the Performance-Based Navigation (PBN) concept?",
    options: ["VOR/DME navigation.", "Area navigation (RNAV).", "Inertial navigation systems."],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "Basic Area Navigation (B-RNAV) requires a track-keeping accuracy equal to or better than:",
    options: ["+/- 1 NM for 95% of flight time.", "+/- 5 NM for 95% of flight time.", "+/- 10 NM for 99% of flight time."],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "The Master Minimum Equipment List (MMEL) is a master list for an aircraft type that is developed by whom?",
    options: ["The airline operator.", "The national aviation authority.", "The type certificate holder."],
    correctOptionIndex: 2,
  },
  {
    id: 76,
    text: "An operator's Minimum Equipment List (MEL) must be based on the relevant MMEL but:",
    options: ["May be less restrictive than the MMEL.", "Must be no less restrictive than the MMEL.", "Is only applicable for 30 days."],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "In an MEL, a \"B\" category item must be rectified within:",
    options: ["3 consecutive calendar days, excluding the day of discovery.", "10 consecutive calendar days, excluding the day of discovery.", "120 consecutive calendar days, excluding the day of discovery."],
    correctOptionIndex: 0,
  },
  {
    id: 78,
    text: "The Configuration Deviation List (CDL) is a list of:",
    options: ["Inoperative equipment and systems.", "Non-structural external parts that may be missing.", "Approved modifications and repairs."],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "A missing part listed in the CDL represents:",
    options: ["An unsafe condition requiring immediate grounding.", "A new certificated aircraft configuration.", "A maintenance error."],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "In the context of MEL procedures, what does an \"O\" in the remarks column signify?",
    options: ["A maintenance action is required.", "The flight crew must accomplish a specific operating procedure.", "The item is optional for the flight."],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "An aircraft instrument marking must be:",
    options: ["Etched onto the instrument glass.", "Clearly visible to the appropriate crew member.", "Checked annually for accuracy."],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "According to CS-25, each marking and placard on an aircraft must be:",
    options: ["Written in two languages.", "Displayed in a conspicuous place and not easily erased or obscured.", "Made of fireproof material."],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "Which of the following documents must be carried on board as an original during a CAT flight?",
    options: ["A certified true copy of the Air Operator Certificate (AOC).", "A copy of the flight crew licenses.", "The aircraft's maintenance manual."],
    correctOptionIndex: 0,
  },
  {
    id: 84,
    text: "An Airworthiness Review Certificate (ARC) is used to:",
    options: ["Certify that a pilot is fit to fly.", "Validate a non-expiring Certificate of Airworthiness.", "Authorise a specific flight for a non-airworthy aircraft."],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "How long may an Airworthiness Review Certificate (ARC) be extended if the aircraft is maintained within a controlled environment?",
    options: ["Up to 1 year.", "Up to 2 years.", "Up to 3 years."],
    correctOptionIndex: 2,
  },
  {
    id: 86,
    text: "When may an EASA Permit to Fly be issued?",
    options: ["For any aircraft that is more than 20 years old.", "For an aircraft to fly when a valid airworthiness certificate is not currently in force.", "For all new aircraft before their first flight."],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "The Certificate of Registration must be:",
    options: ["Renewed every year.", "Accessible and stored with other airworthiness certificates in the cockpit.", "Displayed on the exterior of the aircraft."],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "The requirement for an aircraft to have a radio licence originates from which international organisation?",
    options: ["The International Civil Aviation Organization (ICAO).", "The International Telecommunication Union (ITU).", "The European Union Aviation Safety Agency (EASA)."],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "A Weight and Balance report must be prepared before each flight to enable the commander to determine that:",
    options: ["The fuel is sufficient for the journey.", "The load and its distribution are within the aircraft's mass and balance limits.", "The cargo is properly secured."],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "How often must fleet mass values for aeroplanes be updated?",
    options: ["Every 12 months.", "Every 24 months.", "At least at the end of each fleet mass evaluation, which should not exceed 48 months."],
    correctOptionIndex: 2,
  },
  {
    id: 91,
    text: "What is a key characteristic of a specialised operation (SPO)?",
    options: ["The aircraft is flown at high altitudes.", "Persons may enter or leave the aircraft during flight.", "The operation is always non-commercial."],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "For helicopters, which specific approval is required for operations using Night Vision Imaging Systems?",
    options: ["SPO.NVIS.100.", "SPA.NVIS.", "CAT.NVIS.110."],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "Helicopter Emergency Medical Service operations (HEMS) fall under which part of the regulation?",
    options: ["Part-CAT.", "Part-SPA.", "Part-NCC."],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "Which subpart of Part-ORO deals with technical crew members?",
    options: ["Subpart FC.", "Subpart TC.", "Subpart CC."],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "A technical crew member in HHO (Helicopter Hoist Operations) must be at least:",
    options: ["18 years of age.", "21 years of age.", "25 years of age."],
    correctOptionIndex: 0,
  },
  {
    id: 96,
    text: "Before being assigned duties, a technical crew member must have:",
    options: ["A commercial pilot's licence.", "Completed all applicable training to perform the assigned duties.", "At least 5 years of experience in the role."],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "Push-back and towing procedures for aeroplanes must be conducted:",
    options: ["At the discretion of the ground crew.", "In accordance with established aviation standards and procedures.", "Only under the command of the pilot."],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "Refuelling with wide-cut fuel is only permitted if:",
    options: ["The passengers are kept away from the aircraft.", "The operator has established appropriate procedures considering the high risk.", "It is done during daylight hours."],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "The person at the controls during taxiing must be trained in all of the following EXCEPT:",
    options: ["Use of the radiotelephone.", "Aircraft refuelling procedures.", "Aerodrome layout, routes, signs, and markings."],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "In-flight loading changes must be taken into account for which type of aircraft?",
    options: ["Aeroplanes with a high wing loading.", "Helicopters.", "Gliders."],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "An altitude alerting system is required for turbine propeller-powered aeroplanes with an MCTOM of more than 5,700 kg or with an MOPSC of more than:",
    options: ["Nine.", "Nineteen.", "Thirty."],
    correctOptionIndex: 0,
  },
  {
    id: 102,
    text: "Which class of Terrain Awareness Warning System (TAWS) is required for turbine-powered aeroplanes with an MCTOM of more than 5,700 kg?",
    options: ["Class A.", "Class B.", "Class C."],
    correctOptionIndex: 0,
  },
  {
    id: 103,
    text: "Aeroplanes with an MOPSC of more than 19 must be equipped with a:",
    options: ["Flight crew interphone system only.", "Public address system.", "Crash axe in the cabin."],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "For aeroplanes first issued with an individual C of A on or after 1 January 2016, the FDR must retain data for at least the preceding:",
    options: ["10 hours.", "25 hours.", "30 hours."],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Aeroplanes with an MOPSC of 19 or less, first issued with a C of A after 1 July 2008, must be equipped with at least:",
    options: ["One automatic ELT.", "Two ELTs, one of which is automatic.", "One ELT of any type."],
    correctOptionIndex: 0,
  },
  {
    id: 106,
    text: "According to the document, continuing airworthiness is a shared responsibility between all of the following EXCEPT:",
    options: ["The aircraft type certificate holder.", "The passengers on board.", "The maintenance organisation."],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "What is the main role of the approved Continuing Airworthiness Management Organisation (CAMO)?",
    options: ["To fly the aircraft.", "To implement continuing airworthiness management tasks.", "To sell aircraft parts."],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "For an aircraft in an \"uncontrolled environment\", how often must the owner or operator contract a CAMO to conduct a full airworthiness review?",
    options: ["Every 6 months.", "Every 12 months.", "Every 24 months."],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "The accumulated effects of modifications and repairs on an aircraft's mass and balance must be:",
    options: ["Ignored if the aircraft was recently weighed.", "Accounted for and properly documented.", "Reported only to the manufacturer."],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "Who is responsible for establishing an effective rectification programme for tracking inoperative items listed in the MEL?",
    options: ["The competent authority.", "The operator.", "The aircraft manufacturer."],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "The operator must report RVSM height-keeping errors to the competent authority within:",
    options: ["24 hours.", "72 hours.", "7 days."],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "An operator's ETOPS manual should be submitted to the authority how long before the implementation of ETOPS flights?",
    options: ["7 days.", "30 days.", "90 days."],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "Part-NCC applies to non-commercial operations with what type of aircraft?",
    options: ["Other-than-complex motor-powered aircraft.", "Complex motor-powered aircraft.", "Any aircraft under 5,700 kg."],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "Part-NCO applies to operations with other-than-complex motor-powered aircraft, including:",
    options: ["Specialised and non-specialised operations.", "Commercial air transport only.", "Only operations with balloons."],
    correctOptionIndex: 0,
  },
  {
    id: 115,
    text: "Subpart E of Part-NCO contains specific requirements for:",
    options: ["ETOPS operations.", "Helicopter external sling load operations (HESLO).", "Low visibility operations."],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "The operator must ensure that the aircraft's loading is performed under the supervision of:",
    options: ["The pilot-in-command.", "Qualified personnel.", "A representative from the aviation authority."],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "The fuel load mass can be determined by using actual density or, if not known:",
    options: ["An estimate based on previous flights.", "The density calculated per a method specified in the operations manual.", "A standard density of 0.8 kg/litre for all fuels."],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "When weighing an aircraft, standard precautions include all of the following EXCEPT:",
    options: ["Ensuring the aircraft is clean.", "Performing the weighing in windy conditions outside the hangar.", "Checking for completeness of the aircraft and equipment."],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "For a fleet of 10 or more aeroplanes, the minimum number of weighings to obtain fleet values is calculated as:",
    options: ["(n + 3) ÷ 2.", "(n + 51) ÷ 10.", "n ÷ 4."],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "The dry operating mass of an aircraft includes:",
    options: ["Passengers and their baggage.", "Crew, crew baggage, and removable passenger service equipment.", "Fuel and oil."],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "What is the standard mass for a male passenger on all flights except holiday charters, for aircraft with 20 or more passenger seats?",
    options: ["84 kg.", "88 kg.", "76 kg."],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "The data link recorder must be able to retain data for at least the same duration as which other recorder?",
    options: ["The flight data recorder (FDR).", "The cockpit voice recorder (CVR).", "The aircraft's maintenance log."],
    correctOptionIndex: 0,
  },
  {
    id: 123,
    text: "Aeroplanes with an MOPSC of more than 200 require an additional crash axe or crowbar to be installed:",
    options: ["In the flight crew compartment.", "In or near the rearmost galley area.", "At the main passenger door."],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "Markings on the fuselage for break-in by rescue crews, if used, must be marked in a specific pattern. What is the maximum spacing for the corner marks?",
    options: ["1 metre.", "2 metres.", "3 metres."],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "The operator must notify the competent authority of any extension authorised for an MEL rectification interval within:",
    options: ["5 days.", "10 days.", "15 days."],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "A flight cannot be started after the expiry of the rectification interval specified in the MEL unless:",
    options: ["The commander gives written permission.", "The defect has been rectified or the interval has been extended per requirements.", "The aircraft is flying to a main base for repair."],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "In the context of PBN, what does RNP stand for?",
    options: ["Required Navigation Performance.", "Radio Navigation Point.", "Required NAVAID Performance."],
    correctOptionIndex: 0,
  },
  {
    id: 128,
    text: "ICAO classifies ILS approaches into categories based on:",
    options: ["The aircraft weight.", "Decision Height and RVR requirements.", "The type of autopilot installed."],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "A CAT III B operation has a decision height of less than 50 ft or no DH and requires an RVR of not less than:",
    options: ["200 m.", "75 m (EU-OPS spec) or 50 m.", "350 m."],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "According to the document, the primary goal of an ETOPS reliability programme should be:",
    options: ["Reducing fuel costs.", "The early identification and prevention of ETOPS-related problems.", "Increasing the number of flight cycles."],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "A Certificate of Airworthiness is issued to certify that:",
    options: ["The pilot is qualified to fly the aircraft.", "An aircraft conforms to its type design and is in a condition for safe operation.", "The aircraft has no missing parts."],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "According to the document, the operator's flight data monitoring systems must be:",
    options: ["Used to assess pilot performance for disciplinary action.", "Non-punitive and contain adequate safeguards to protect the source(s) of the data.", "Accessible to the public upon request."],
    correctOptionIndex: 1,
  },
];
