export const flightControlsQuestions = [
  { id: 1, text: "An aircraft is free to rotate around how many axes that intersect at its centre of gravity?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 2, text: "The lateral axis passes through an aircraft from where to where?", options: ["Nose to tail", "Wingtip to wingtip", "Top to bottom"], correctOptionIndex: 1 },
  { id: 3, text: "Rotation about the lateral axis is called what?", options: ["Roll", "Pitch", "Yaw"], correctOptionIndex: 1 },
  { id: 4, text: "What are the primary control surfaces for pitch?", options: ["Ailerons", "Elevators", "Rudder"], correctOptionIndex: 1 },
  { id: 5, text: "The longitudinal axis passes through an aircraft from where to where?", options: ["Wingtip to wingtip", "Nose to tail", "Top to bottom"], correctOptionIndex: 1 },
  { id: 6, text: "Rotation about the longitudinal axis is called what?", options: ["Pitch", "Roll", "Yaw"], correctOptionIndex: 1 },
  { id: 7, text: "What are the primary control surfaces for roll?", options: ["Elevators", "Ailerons", "Rudder"], correctOptionIndex: 1 },
  { id: 8, text: "The vertical axis passes through an aircraft from where to where?", options: ["Nose to tail", "Top to bottom", "Wingtip to wingtip"], correctOptionIndex: 1 },
  { id: 9, text: "Rotation about the vertical axis is called what?", options: ["Pitch", "Yaw", "Roll"], correctOptionIndex: 1 },
  { id: 10, text: "What is the primary control for yaw?", options: ["Ailerons", "Rudder", "Elevators"], correctOptionIndex: 1 },
  { id: 11, text: "Where are ailerons mounted?", options: ["On the leading edge of each wing", "On the trailing edge of each wing near the wingtips", "On the vertical stabiliser"], correctOptionIndex: 1 },
  { id: 12, text: "When the pilot moves the stick left, what happens to the ailerons?", options: ["Left aileron goes down, right aileron goes up", "Left aileron goes up, right aileron goes down", "Both ailerons go up"], correctOptionIndex: 1 },
  { id: 13, text: "A raised aileron does what to lift on that wing?", options: ["Increases lift", "Reduces lift", "Has no effect on lift"], correctOptionIndex: 1 },
  { id: 14, text: "Where are elevators mounted?", options: ["On the trailing edge of the vertical stabiliser", "On the trailing edge of the horizontal stabiliser on each side of the fin", "On the wing trailing edge"], correctOptionIndex: 1 },
  { id: 15, text: "When the pilot pulls the stick backwards, what do the elevators do?", options: ["Go down", "Go up", "Remain neutral"], correctOptionIndex: 1 },
  { id: 16, text: "Raised elevators push down on the tail and cause the nose to do what?", options: ["Pitch down", "Pitch up", "Yaw left"], correctOptionIndex: 1 },
  { id: 17, text: "A stabilator is what?", options: ["A type of aileron", "A moveable horizontal stabiliser that replaces an elevator", "A type of rudder"], correctOptionIndex: 1 },
  { id: 18, text: "Where is the rudder typically mounted?", options: ["On the horizontal stabiliser", "On the trailing edge of the vertical stabiliser", "On the wing trailing edge"], correctOptionIndex: 1 },
  { id: 19, text: "When the pilot pushes the left pedal, what does the rudder do?", options: ["Deflects right", "Deflects left", "Remains neutral"], correctOptionIndex: 1 },
  { id: 20, text: "Deflecting the rudder right pushes the tail left and causes the nose to do what?", options: ["Yaw left", "Yaw right", "Pitch up"], correctOptionIndex: 1 },
  { id: 21, text: "Using ailerons causes what type of yaw?", options: ["Proverse yaw", "Adverse yaw", "Neutral yaw"], correctOptionIndex: 1 },
  { id: 22, text: "Adverse yaw means the nose yaws in what direction relative to the aileron application?", options: ["Same direction", "Opposite direction", "Vertical direction"], correctOptionIndex: 1 },
  { id: 23, text: "When moving the stick left to bank left, adverse yaw moves the nose to the?", options: ["Left", "Right", "Down"], correctOptionIndex: 1 },
  { id: 24, text: "Differential ailerons are rigged such that the down-going aileron deflects how much compared to the upward-moving one?", options: ["More", "Less", "The same amount"], correctOptionIndex: 1 },
  { id: 25, text: "If rudder is continuously applied in level flight, after a few seconds the aircraft will tend to bank in what direction?", options: ["Opposite to the yaw", "The direction of yaw", "Neither direction"], correctOptionIndex: 1 },
  { id: 26, text: "In an aircraft with dihedral, the left-hand wing will have increased angle of attack during a skid, resulting in roll to which side?", options: ["Left", "Right", "No roll"], correctOptionIndex: 1 },
  { id: 27, text: "With aircraft, the turn is caused by what component of lift?", options: ["Vertical component", "Horizontal component", "Induced component"], correctOptionIndex: 1 },
  { id: 28, text: "To maintain level flight in a bank, what must be increased?", options: ["Rudder input", "Positive elevator to increase angle of attack", "Aileron input"], correctOptionIndex: 1 },
  { id: 29, text: "Beyond a certain angle of bank, the aircraft will suffer what if the pilot attempts to generate enough lift?", options: ["Overspeed", "An accelerated stall", "Dutch roll"], correctOptionIndex: 1 },
  { id: 30, text: "Delta wing aircraft may have what combined control surfaces at the back of the wing?", options: ["Flaperons", "Elevons", "Spoilerons"], correctOptionIndex: 1 },
  { id: 31, text: "On low drag aircraft like sailplanes, what is used to disrupt airflow over the wing and increase drag?", options: ["Flaps", "Spoilers", "Slats"], correctOptionIndex: 1 },
  { id: 32, text: "Spoilers are sometimes called what?", options: ["Air brakes", "Lift dumpers", "Speed brakes"], correctOptionIndex: 1 },
  { id: 33, text: "Spoilers that can be used asymmetrically are sometimes called what?", options: ["Flaperons", "Spoilerons", "Elevons"], correctOptionIndex: 1 },
  { id: 34, text: "Where are flaps mounted?", options: ["On the leading edge", "On the trailing edge of each wing on the inboard section", "On the wingtips"], correctOptionIndex: 1 },
  { id: 35, text: "Flaps raise the maximum lift coefficient and therefore reduce what?", options: ["Drag", "Stalling speed", "Weight"], correctOptionIndex: 1 },
  { id: 36, text: "Slats are also known as what?", options: ["Trailing edge devices", "Leading edge devices", "Lift dumpers"], correctOptionIndex: 1 },
  { id: 37, text: "On a typical airliner, spoilers are a series of panels on what surface of the wing?", options: ["Lower surface", "Upper surface", "Leading edge"], correctOptionIndex: 1 },
  { id: 38, text: "Ground spoilers deploy upon touchdown to do what?", options: ["Increase lift", "Dump lift and place aircraft weight on wheels", "Increase roll rate"], correctOptionIndex: 1 },
  { id: 39, text: "Elevator trim balances the control force necessary to maintain what?", options: ["Roll attitude", "Aerodynamic downforce on the tail", "Yaw stability"], correctOptionIndex: 1 },
  { id: 40, text: "Except for very light aircraft, what is made adjustable in pitch to provide appropriate trim force?", options: ["The entire vertical tailplane", "The entire horizontal tailplane", "The ailerons"], correctOptionIndex: 1 },
  { id: 41, text: "A control horn is a section of control surface that projects where?", options: ["Behind the pivot point", "Ahead of the pivot point", "Below the pivot point"], correctOptionIndex: 1 },
  { id: 42, text: "Control horns may incorporate a counterweight to prevent what?", options: ["Overtravel", "Fluttering in the airstream", "Stalling"], correctOptionIndex: 1 },
  { id: 43, text: "In the simplest cases, trimming is done by what type of device that adds appropriate force?", options: ["Hydraulic actuator", "Mechanical spring (or bungee)", "Electric motor"], correctOptionIndex: 1 },
  { id: 44, text: "What are the two types of pilot inputs in common use on light aircraft?", options: ["Steering wheel and joystick", "Control yoke and control stick", "Sidestick and centre stick"], correctOptionIndex: 1 },
  { id: 45, text: "Moving the control yoke forward does what to the elevator?", options: ["Raises it", "Lowers it", "Has no effect"], correctOptionIndex: 1 },
  { id: 46, text: "Rotating the yoke clockwise does what to the ailerons?", options: ["Raises left aileron, lowers right aileron", "Raises right aileron, lowers left aileron", "Raises both ailerons"], correctOptionIndex: 1 },
  { id: 47, text: "Moving the control stick to the right does what?", options: ["Raises left aileron, lowers right aileron", "Raises right aileron, lowers left aileron", "Raises both ailerons"], correctOptionIndex: 1 },
  { id: 48, text: "The left rudder pedal moves the rudder which way?", options: ["Right", "Left", "Neutral"], correctOptionIndex: 1 },
  { id: 49, text: "Rudder pedals have what two secondary functions?", options: ["Speed brake and flap control", "Nose wheel steering and main wheel braking", "Trim and autopilot control"], correctOptionIndex: 1 },
  { id: 50, text: "What activates the hydraulic brake system?", options: ["Pushing the pedal forward", "Toe-force applied at the top of the rudder pedal", "Pulling the pedal backward"], correctOptionIndex: 1 },
  { id: 51, text: "Adverse aileron yaw is caused by what?", options: ["Difference in weight distribution", "Difference in lift and drag of each wing", "Engine torque"], correctOptionIndex: 1 },
  { id: 52, text: "Coupled ailerons and rudder systems are also known as what?", options: ["Yaw dampers", "Aileron-to-rudder mixing", "Turn coordinators"], correctOptionIndex: 1 },
  { id: 53, text: "Coupled ailerons-rudder are mechanically linked using what components?", options: ["Hydraulic actuators", "Rudder-aileron interconnect springs", "Electric motors"], correctOptionIndex: 1 },
  { id: 54, text: "Transport aircraft are usually trimmable in how many axes?", options: ["One", "Three", "Two"], correctOptionIndex: 1 },
  { id: 55, text: "Trim tabs are normally used for roll and yaw trimming on what type of aircraft?", options: ["Hydraulically operated", "Cable-controlled aircraft", "Fly-by-wire aircraft"], correctOptionIndex: 1 },
  { id: 56, text: "Boosted or hydraulically operated aileron and rudder systems are usually trimmed by moving what?", options: ["Trim tabs", "Artificial feel and centring unit out of its centre position", "Control cables"], correctOptionIndex: 1 },
  { id: 57, text: "Fly-by-wire operated systems trim ailerons by doing what?", options: ["Moving trim tabs", "Roll control computers sending re-positioning signal to aileron servo control units", "Manual adjustment"], correctOptionIndex: 1 },
  { id: 58, text: "An electrical trim system is operated from what?", options: ["A lever", "A trim switch", "A wheel"], correctOptionIndex: 1 },
  { id: 59, text: "For elevator trim, where is the trim switch located?", options: ["On the centre console", "On the control yoke or stick", "On the overhead panel"], correctOptionIndex: 1 },
  { id: 60, text: "The trim switch is often called a what?", options: ["Toggle switch", "Hat switch", "Rocker switch"], correctOptionIndex: 1 },
  { id: 61, text: "Where is the rudder trim switch usually located?", options: ["On the control yoke", "On the centre console", "On the rudder pedals"], correctOptionIndex: 1 },
  { id: 62, text: "What is 'trim runaway'?", options: ["Normal trim operation", "Malfunction causing uncommanded trim operation", "Pilot-initiated trim movement"], correctOptionIndex: 1 },
  { id: 63, text: "In a dual switch trim system, how many separate electrical circuits are incorporated?", options: ["One", "Two (ARM and direction)", "Three"], correctOptionIndex: 1 },
  { id: 64, text: "The trim interrupt button is usually labelled what?", options: ["TRIM OFF", "TRIM INT", "TRIM STOP"], correctOptionIndex: 1 },
  { id: 65, text: "Most electrical trim mechanisms have a slip-clutch that allows what?", options: ["Faster trim operation", "Pilot to grab mechanical trim wheel and overpower the electric motor", "Automatic trim operation"], correctOptionIndex: 1 },
  { id: 66, text: "A trim fail warning light may illuminate if what condition exists?", options: ["Trim is operating normally", "Elevator input is increasing opposite to trim input for a sustained period", "Battery is low"], correctOptionIndex: 1 },
  { id: 67, text: "Spring bias trim system is what type of system?", options: ["Aerodynamic", "Mechanical", "Hydraulic"], correctOptionIndex: 1 },
  { id: 68, text: "The spring assembly consists of what?", options: ["Single spring", "A pair of springs attached to the control system", "Hydraulic cylinder"], correctOptionIndex: 1 },
  { id: 69, text: "Spring bias system is most often used on what trim systems?", options: ["Elevator only", "Aileron and rudder trim systems", "Flap trim"], correctOptionIndex: 1 },
  { id: 70, text: "Trim tab system is preferred for the elevator because it is aerodynamic and increases effectiveness as what increases?", options: ["Altitude", "Airspeed", "Weight"], correctOptionIndex: 1 },
  { id: 71, text: "Larger transport aircraft are trimmed longitudinally by adjusting the position of what?", options: ["Elevator trim tab", "Leading edge of the horizontal stabiliser", "Rudder"], correctOptionIndex: 1 },
  { id: 72, text: "The stabiliser pivots about the rear spar and what controlled from the cockpit raises or lowers the leading edge?", options: ["Hydraulic cylinder", "Jack-screw", "Electric motor"], correctOptionIndex: 1 },
  { id: 73, text: "Raising the leading edge of the stabiliser gives what trim?", options: ["Nose-up", "Nose-down", "No change"], correctOptionIndex: 1 },
  { id: 74, text: "During manual movement of the THS, what sounds in the cockpit?", options: ["Warning horn", "An audible signal", "Bell"], correctOptionIndex: 1 },
  { id: 75, text: "The versine signal is derived from what?", options: ["Airspeed", "Bank angle signal from a vertical gyro", "Altitude"], correctOptionIndex: 1 },
  { id: 76, text: "The versine signal is generally proportional to what function of the bank angle?", options: ["Sine", "(1 - cosine)", "Tangent"], correctOptionIndex: 1 },
  { id: 77, text: "Flaps which only increase the camber have what type of hinge point?", options: ["Moving hinge", "Fixed hinge", "Variable hinge"], correctOptionIndex: 1 },
  { id: 78, text: "Flaps which increase both surface area and camber have what type of mechanism?", options: ["Fixed hinges", "Rollers installed in specially formed tracks", "Direct drive"], correctOptionIndex: 1 },
  { id: 79, text: "What type of system is often used to prevent flap loads feeding back to the control system?", options: ["Hydraulic system", "Screw type system", "Cable system"], correctOptionIndex: 1 },
  { id: 80, text: "VFE stands for what?", options: ["Variable flap extension", "Maximum speed for slats/flaps extended", "Vertical flap efficiency"], correctOptionIndex: 1 },
  { id: 81, text: "Leading edge flaps are also known as what?", options: ["Slats", "Krueger flaps", "Droop flaps"], correctOptionIndex: 1 },
  { id: 82, text: "Where are leading edge flaps installed?", options: ["Above the wing", "Below the forward wing edge", "At the wingtip"], correctOptionIndex: 1 },
  { id: 83, text: "Slats are installed on tracks attached to where?", options: ["Trailing edge of each wing", "Leading edge of each wing", "Fuselage"], correctOptionIndex: 1 },
  { id: 84, text: "Generally, extension of slats and flaps must be done at the same time, so there is how many control handles?", options: ["Two separate handles", "One control handle", "Three handles"], correctOptionIndex: 1 },
  { id: 85, text: "Signal transmission for flap position can be done mechanically by steel cables or electrically by what?", options: ["Direct wire", "Position pickup unit and electrical indicator", "Radio signal"], correctOptionIndex: 1 },
  { id: 86, text: "After a failure in the driving mechanism, a difference in flap position might cause what?", options: ["Increased lift", "A dangerous roll moment", "Pitch change"], correctOptionIndex: 1 },
  { id: 87, text: "In aircraft with a driving axle system, asymmetry is measured how?", options: ["Mechanically", "Electrically", "Hydraulically"], correctOptionIndex: 1 },
  { id: 88, text: "APPU stands for what?", options: ["Automatic position pickup unit", "Asymmetry position pick-off unit", "Aileron position pickup unit"], correctOptionIndex: 1 },
  { id: 89, text: "FPPU stands for what?", options: ["Flap position pickup unit", "Feedback position pick-off units", "Forward position pickup unit"], correctOptionIndex: 1 },
  { id: 90, text: "LVDT stands for what?", options: ["Linear voltage differential transformer", "Linear variable differential transducer", "Longitudinal velocity detection transducer"], correctOptionIndex: 1 },
  { id: 91, text: "WTB stands for what?", options: ["Wing trim brake", "Wingtip brake", "Weight on wheels brake"], correctOptionIndex: 1 },
  { id: 92, text: "The WTB is what type of brake?", options: ["Mechanical only", "Electro-hydraulic pressure-on brake", "Pneumatic"], correctOptionIndex: 1 },
  { id: 93, text: "What is the most widely used linkage in primary flight control systems?", options: ["Push-pull rods", "Cables", "Hydraulic lines"], correctOptionIndex: 1 },
  { id: 94, text: "Cables can only provide what type of force?", options: ["Push", "Pull", "Both push and pull"], correctOptionIndex: 1 },
  { id: 95, text: "How many cable runs are always required for each control surface?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 96, text: "The second cable run is known as what?", options: ["Redundant cable", "Balance cable", "Secondary cable"], correctOptionIndex: 1 },
  { id: 97, text: "Aircraft control cables are fabricated from what materials?", options: ["Copper or brass", "Carbon steel or stainless steel", "Aluminium"], correctOptionIndex: 1 },
  { id: 98, text: "What component is used to alter the direction of the transmission?", options: ["Pulley", "Bell-crank lever", "Turnbuckle"], correctOptionIndex: 1 },
  { id: 99, text: "What component is used to adjust cable tension?", options: ["Pulley", "Turnbuckle", "Fairlead"], correctOptionIndex: 1 },
  { id: 100, text: "What component is used to guide the cable and prevent sagging?", options: ["Pulley", "Fairlead", "Torque tube"], correctOptionIndex: 1 },
  { id: 101, text: "What component converts linear force into torsional motion?", options: ["Bell-crank", "Torque tube", "Turnbuckle"], correctOptionIndex: 1 },
  { id: 102, text: "The function of a chain and sprocket is to convert what?", options: ["Rotational to linear motion only", "Linear motion into rotational motion, and vice versa", "Force to pressure"], correctOptionIndex: 1 },
  { id: 103, text: "Push-pull rods have what advantage over cable systems?", options: ["They are lighter", "They can provide both push and pull force, requiring only one control run", "They require less maintenance"], correctOptionIndex: 1 },
  { id: 104, text: "Push-pull rods are usually made of what material?", options: ["Steel", "Aluminium alloy", "Titanium"], correctOptionIndex: 1 },
  { id: 105, text: "What component is used to change a pull force into a push force or vice versa?", options: ["Bell-crank", "Idler lever", "Torque tube"], correctOptionIndex: 1 },
  { id: 106, text: "What limits the range of movement of the control surface?", options: ["Control cables", "Limit stops", "Actuators"], correctOptionIndex: 1 },
  { id: 107, text: "Where are primary stops located?", options: ["In the cockpit", "At or very near the control surface", "At the control column"], correctOptionIndex: 1 },
  { id: 108, text: "Where are secondary stops located?", options: ["At the control surface", "At or very near the pilot's input in the cockpit", "Along the cable run"], correctOptionIndex: 1 },
  { id: 109, text: "What is the purpose of secondary stops?", options: ["To limit control surface movement", "To prevent pilot damaging control system by putting too much force when surface is against primary stop", "To provide emergency stopping"], correctOptionIndex: 1 },
  { id: 110, text: "What is the purpose of gust locks?", options: ["To assist in turning", "To lock flight controls when aircraft is parked", "To improve aerodynamics"], correctOptionIndex: 1 },
  { id: 111, text: "Most modern large jet aircraft do not need gust locks because when hydraulic system is at rest, what happens?", options: ["Controls are free to move", "A dampening device in the actuator locks the flight control in neutral position", "Mechanical pins engage automatically"], correctOptionIndex: 1 },
  { id: 112, text: "In cable-operated systems with gust locks, the pins are spring loaded to what position in flight?", options: ["On (locked)", "Off (unlocked)", "Neutral"], correctOptionIndex: 1 },
  { id: 113, text: "A hydraulically powered control system is said to be what type of system?", options: ["Reversible", "Irreversible", "Semi-reversible"], correctOptionIndex: 1 },
  { id: 114, text: "In an irreversible system, aerodynamic loads on control surfaces are not transferred back to whom?", options: ["The autopilot", "The pilot", "The computer"], correctOptionIndex: 1 },
  { id: 115, text: "'Q' feel varies with what?", options: ["Altitude", "Dynamic pressure of the air", "Temperature"], correctOptionIndex: 1 },
  { id: 116, text: "'Q' is represented by what formula?", options: ["ρV", "½ρV²", "ρV²"], correctOptionIndex: 1 },
  { id: 117, text: "The typical artificial feel system uses both spring feel and what?", options: ["Cable tension", "Hydraulic feel", "Pneumatic feel"], correctOptionIndex: 1 },
  { id: 118, text: "Many high-speed jet aircraft with swept-back wings have what undesirable problem?", options: ["Porpoising", "Dutch roll", "Phugoid oscillation"], correctOptionIndex: 1 },
  { id: 119, text: "What senses the rate of yaw in a yaw damper system?", options: ["Accelerometer", "Rate gyro", "Air data computer"], correctOptionIndex: 1 },
  { id: 120, text: "The yaw damper sends a signal to what servo?", options: ["Aileron", "Rudder", "Elevator"], correctOptionIndex: 1 },
  { id: 121, text: "Why does an aircraft need Mach speed trim?", options: ["Due to engine efficiency changes", "Due to behaviour of wing centre of pressure as speed changes", "Due to weight changes"], correctOptionIndex: 1 },
  { id: 122, text: "As speed increases, the centre of pressure begins to do what?", options: ["Move forward", "Move aft", "Remain stationary"], correctOptionIndex: 1 },
  { id: 123, text: "As the CP moves aft, what happens to elevator effectiveness?", options: ["Increases", "Decreases", "Remains same"], correctOptionIndex: 1 },
  { id: 124, text: "The difference in location between CP and CG causes the aircraft nose to do what?", options: ["Pitch up", "Pitch down", "Yaw"], correctOptionIndex: 1 },
  { id: 125, text: "Why are large aircraft provided with a rudder travel limiter?", options: ["To improve turn performance", "To protect the empennage from overload at high speed", "To reduce pilot workload"], correctOptionIndex: 1 },
  { id: 126, text: "In older aircraft, the rudder limiter operates by what?", options: ["Electrical signals", "Ram air pressure from its own pitot tube", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 127, text: "Modern aircraft have a computer controlled rudder limiter that receives signals from where?", options: ["GPS", "Air data system", "Inertial reference system"], correctOptionIndex: 1 },
  { id: 128, text: "VS (stall velocity) is defined as what?", options: ["Maximum steady flight speed", "Calibrated stalling speed or minimum steady flight speed", "Cruising speed"], correctOptionIndex: 1 },
  { id: 129, text: "Most stall warning systems operate as a function of what?", options: ["Altitude", "Aircraft indicated airspeed", "Weight"], correctOptionIndex: 1 },
  { id: 130, text: "A stick shaker is a mechanical device to do what?", options: ["Increase control feel", "Rapidly and noisily vibrate the control yoke to warn of imminent stall", "Assist in turning"], correctOptionIndex: 1 },
  { id: 131, text: "The stick shaker is composed of what?", options: ["Hydraulic motor", "Electric motor connected to an unbalanced flywheel", "Solenoid"], correctOptionIndex: 1 },
  { id: 132, text: "In a hydraulically assisted control system, a hydraulic actuator is in what configuration with the mechanical operation?", options: ["In series", "In parallel", "Independent"], correctOptionIndex: 1 },
  { id: 133, text: "In a hydraulically actuated system with direct cable backup, what happens in case of hydraulic power failure?", options: ["Controls lock", "Hydraulic actuator is bypassed and input force goes directly to control surface", "Autopilot takes over"], correctOptionIndex: 1 },
  { id: 134, text: "In the event of hydraulic system failure, controls are operated with what?", options: ["Electric motors", "Servo tabs", "Pneumatic system"], correctOptionIndex: 1 },
  { id: 135, text: "A follow-up system is used to do what?", options: ["Increase control force", "Close the control valve when it has reached the desired position", "Provide backup control"], correctOptionIndex: 1 },
  { id: 136, text: "One key advantage of pneumatic flight control systems is what?", options: ["Faster response than hydraulic", "High resistance to failures and malfunctions", "Lower weight than hydraulic"], correctOptionIndex: 1 },
  { id: 137, text: "Why are pneumatic systems now mostly found in aircraft museums?", options: ["They are too heavy", "Hydraulic fluid's incompressibility provides quicker and more precise response", "They are too expensive"], correctOptionIndex: 1 },
  { id: 138, text: "Active load control is a system whereby stresses placed on wings are what?", options: ["Increased", "Redistributed to reduce focus of loads during manoeuvres", "Ignored"], correctOptionIndex: 1 },
  { id: 139, text: "RMLA stands for what?", options: ["Roll manoeuvre load actuator", "Roll manoeuvre load alleviation", "Rapid manoeuvre load adjustment"], correctOptionIndex: 1 },
  { id: 140, text: "On Airbus A320, active load control is also known as what function?", options: ["Load reduction function", "Load alleviation function (LAF)", "Load distribution function"], correctOptionIndex: 1 },
  { id: 141, text: "How many specific accelerometers are installed in the forward fuselage for load alleviation?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 142, text: "Spoilers used for lateral control augmentation are also known as what?", options: ["Flight spoilers", "Roll spoilers", "Ground spoilers"], correctOptionIndex: 1 },
  { id: 143, text: "During flight, manually moving the pedestal-mounted lever aft will extend flight spoilers to serve as what?", options: ["Roll control", "Speed brakes", "Lift dumpers"], correctOptionIndex: 1 },
  { id: 144, text: "Speed brake surfaces are extended how, as per the handle position?", options: ["Asymmetrically", "Symmetrically", "Independently"], correctOptionIndex: 1 },
  { id: 145, text: "Ground spoilers will fully extend to about what angle?", options: ["35°", "60°", "45°"], correctOptionIndex: 1 },
  { id: 146, text: "Torque limiting safeguards against what condition?", options: ["Normal operation", "Servo system runaway causing control surfaces to displace to maximum positions", "Low hydraulic pressure"], correctOptionIndex: 1 },
  { id: 147, text: "A stick pusher is a device installed to prevent what?", options: ["Overspeed", "Aircraft from entering an aerodynamic stall", "Dutch roll"], correctOptionIndex: 1 },
  { id: 148, text: "When a stall condition is detected, the stick pusher actuator does what?", options: ["Pulls the control column back", "Moves the control column forward", "Vibrates the control column"], correctOptionIndex: 1 },
  { id: 149, text: "To activate the stick pusher on some systems, how many computers must detect high angle of attack?", options: ["One", "Both computers", "Three"], correctOptionIndex: 1 },
  { id: 150, text: "Stall strips on smaller aircraft produce a small vortex that reaches where?", options: ["The wingtips", "The horizontal stabiliser", "The ailerons"], correctOptionIndex: 1 },
  { id: 151, text: "FBW stands for what?", options: ["Fly-by-wire", "Fly-by-wire", "Flight-by-wire"], correctOptionIndex: 1 },
  { id: 152, text: "Which of the following is NOT a reason manufacturers are switching to FBW?", options: ["Flight test savings", "Increased mechanical complexity", "Weight and complexity savings"], correctOptionIndex: 1 },
  { id: 153, text: "FBW along with FADEC technology reduces requirement for what?", options: ["Hydraulic systems", "Direct cable linkages between flight deck and engines/control surfaces", "Electrical power"], correctOptionIndex: 1 },
  { id: 154, text: "A 'triplex' system means how many channels are being used?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 155, text: "In an analogue FBW system, the computer receives signals, performs a calculation to find what?", options: ["Maximum voltage", "Mean average voltage", "Minimum voltage"], correctOptionIndex: 1 },
  { id: 156, text: "Potentiometers in the actuator send what type of signal back to the computer?", options: ["Positive voltage", "Negative voltage (feedback)", "Zero voltage"], correctOptionIndex: 1 },
  { id: 157, text: "When the actuator reaches desired position, the two signals do what?", options: ["Add together", "Cancel each other out", "Multiply"], correctOptionIndex: 1 },
  { id: 158, text: "Aircraft systems may be quadruplexed, meaning how many independent channels?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 159, text: "Airbus aircraft maintain a mechanical control to which surfaces?", options: ["Ailerons and elevators", "Rudder and trimmable horizontal stabiliser", "Spoilers only"], correctOptionIndex: 1 },
  { id: 160, text: "In Airbus FBW, flight control surfaces are electrically-controlled and how activated?", options: ["Electrically-activated", "Hydraulically-activated", "Pneumatically-activated"], correctOptionIndex: 1 },
  { id: 161, text: "What do pilots use to fly the aircraft in pitch and roll on Airbus aircraft?", options: ["Control yokes", "Sidesticks", "Control wheels"], correctOptionIndex: 1 },
  { id: 162, text: "How many sidestick controllers are there on Airbus aircraft?", options: ["One", "Two (one for each pilot)", "Three"], correctOptionIndex: 1 },
  { id: 163, text: "Are the two sidestick controllers coupled mechanically?", options: ["Yes", "No", "Only in emergency"], correctOptionIndex: 1 },
  { id: 164, text: "How many flight control computers process pilot and autopilot inputs on Airbus A320?", options: ["Five", "Seven", "Nine"], correctOptionIndex: 1 },
  { id: 165, text: "ELAC stands for what?", options: ["Elevator aileron computer", "Elevator aileron computer", "Electrical aileron computer"], correctOptionIndex: 1 },
  { id: 166, text: "SEC stands for what?", options: ["Spoiler elevator computer", "Spoilers elevator computer", "Secondary elevator computer"], correctOptionIndex: 1 },
  { id: 167, text: "FAC stands for what?", options: ["Flight aileron computer", "Flight augmentation computer", "Final approach computer"], correctOptionIndex: 1 },
  { id: 168, text: "What controls the aircraft in pitch on Airbus FBW?", options: ["Elevators only", "Two elevators and the Trimmable Horizontal Stabiliser (THS)", "Stabiliser only"], correctOptionIndex: 1 },
  { id: 169, text: "Maximum elevator deflection is how many degrees nose up?", options: ["11°", "30°", "13.5°"], correctOptionIndex: 1 },
  { id: 170, text: "Maximum elevator deflection is how many degrees nose down?", options: ["4°", "11°", "30°"], correctOptionIndex: 1 },
  { id: 171, text: "In normal operations, which computer controls the elevators and horizontal stabiliser?", options: ["ELAC1", "ELAC2", "SEC1"], correctOptionIndex: 1 },
  { id: 172, text: "If ELAC2 fails, which computer takes over pitch control?", options: ["SEC1", "ELAC1", "FAC1"], correctOptionIndex: 1 },
  { id: 173, text: "Mechanical control of the THS from the pitch trim wheel is available when?", options: ["Only on ground", "At any time if either green or yellow hydraulic system is functioning", "Only in emergency"], correctOptionIndex: 1 },
  { id: 174, text: "How many electrically-controlled hydraulic servo jacks drive each elevator?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 175, text: "In normal operation, one jack is in active mode, the other is in what mode?", options: ["Centring mode", "Damping mode", "Standby mode"], correctOptionIndex: 1 },
  { id: 176, text: "How many ailerons and spoilers on each wing control roll?", options: ["One aileron and two spoilers", "One aileron and four spoilers", "Two ailerons and four spoilers"], correctOptionIndex: 1 },
  { id: 177, text: "Maximum deflection of ailerons is how many degrees?", options: ["35°", "25°", "45°"], correctOptionIndex: 1 },
  { id: 178, text: "Ailerons extend 5° down when flaps are extended. This is called what?", options: ["Flap droop", "Aileron droop", "Spoiler droop"], correctOptionIndex: 1 },
  { id: 179, text: "Which computer normally controls the ailerons?", options: ["ELAC2", "ELAC1", "SEC1"], correctOptionIndex: 1 },
  { id: 180, text: "If both ELACs fail, what happens to ailerons?", options: ["They lock", "Revert to damping mode", "Become inactive"], correctOptionIndex: 1 },
  { id: 181, text: "Speedbrakes are actually which spoilers?", options: ["1, 2 and 3", "2, 3 and 4", "4, 5 and 6"], correctOptionIndex: 1 },
  { id: 182, text: "The maximum speedbrake deflection in manual flight for spoilers 3 and 4 is how many degrees?", options: ["20°", "40°", "25°"], correctOptionIndex: 1 },
  { id: 183, text: "When a speedbrake surface on one wing fails, what happens to the symmetric one on the other wing?", options: ["It operates normally", "It is inhibited", "It increases deflection"], correctOptionIndex: 1 },
  { id: 184, text: "Spoilers 1 to 5 act as what when on ground?", options: ["Speed brakes", "Ground spoilers", "Roll spoilers"], correctOptionIndex: 1 },
  { id: 185, text: "The pilot arms the ground spoilers by doing what?", options: ["Pushing a button", "Pulling the speedbrake control lever up into the armed position", "Turning a switch"], correctOptionIndex: 1 },
  { id: 186, text: "Ground spoilers automatically extend during rejected takeoff at what speed?", options: ["Greater than 50 knots", "Greater than 72 knots", "Greater than 100 knots"], correctOptionIndex: 1 },
  { id: 187, text: "In autoland, ground spoilers fully extend at half speed how long after both main landing gear touch down?", options: ["Immediately", "One second", "Two seconds"], correctOptionIndex: 1 },
  { id: 188, text: "Ground spoilers partially extend to what angle when reverse is selected on at least one engine?", options: ["5°", "10°", "15°"], correctOptionIndex: 1 },
  { id: 189, text: "How many rudder surfaces control yaw?", options: ["Two", "One", "Three"], correctOptionIndex: 1 },
  { id: 190, text: "The yaw damping and turn coordination functions are what?", options: ["Manual", "Automatic", "Pilot-selectable"], correctOptionIndex: 1 },
  { id: 191, text: "How many independent hydraulic servo jacks actuate the rudder?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 192, text: "The servo jacks operate in what configuration?", options: ["Series", "Parallel", "Independently"], correctOptionIndex: 1 },
  { id: 193, text: "Under normal law, load factor is automatically limited to what for clean configuration?", options: ["+2.0g to -0.5g", "+2.5g to -1g", "+3.0g to -1.5g"], correctOptionIndex: 1 },
  { id: 194, text: "Pitch attitude is limited to how many degrees nose up in flap configuration 0 to 3?", options: ["25°", "30°", "13°"], correctOptionIndex: 1 },
  { id: 195, text: "Pitch attitude is limited to how many degrees nose down?", options: ["10°", "13°", "15°"], correctOptionIndex: 1 },
  { id: 196, text: "When angle of attack becomes greater than α_prot, the system switches to what mode?", options: ["Alternate law", "Protection mode", "Direct law"], correctOptionIndex: 1 },
  { id: 197, text: "In protection mode, the angle of attack is proportional to what?", options: ["Airspeed", "Sidestick deflection", "Altitude"], correctOptionIndex: 1 },
  { id: 198, text: "To deactivate angle of attack protection, the pilot must push the sidestick more than how many degrees forward?", options: ["4°", "8°", "12°"], correctOptionIndex: 1 },
  { id: 199, text: "α_floor function is available from lift-off to what height before landing?", options: ["50 feet RA", "100 feet RA", "200 feet RA"], correctOptionIndex: 1 },
  { id: 200, text: "When high-speed protection is activated, the bank angle limit is reduced from 67° to what?", options: ["33°", "45°", "30°"], correctOptionIndex: 1 },
  { id: 201, text: "ECAM displays an \"OVERSPEED\" warning at VMO + how many knots?", options: ["2 knots", "4 knots", "6 knots"], correctOptionIndex: 1 },
  { id: 202, text: "When the aircraft is on ground, the sidestick commands aileron and roll spoiler surface deflection based on what?", options: ["Altitude", "Aircraft speed", "Weight"], correctOptionIndex: 1 },
  { id: 203, text: "The roll rate requested by pilot during flight is proportional to sidestick deflection, with maximum rate of how many degrees per second?", options: ["10°", "15°", "20°"], correctOptionIndex: 1 },
  { id: 204, text: "Inside normal flight envelope, the system maintains positive spiral static stability for bank angles above what value?", options: ["45°", "33°", "67°"], correctOptionIndex: 1 },
  { id: 205, text: "If pilot holds full lateral sidestick deflection, bank angle goes to what value?", options: ["45°", "67°", "90°"], correctOptionIndex: 1 },
  { id: 206, text: "With Boeing 777, pilots can do what regarding the computerized flight-control system?", options: ["Cannot override it", "Completely override it during emergencies", "Only override in alternate law"], correctOptionIndex: 1 },
  { id: 207, text: "Boeing 777 uses what type of cockpit control?", options: ["Sidestick", "Conventional control column and yoke", "Centre stick"], correctOptionIndex: 1 },
  { id: 208, text: "In Airbus airliners, the flight-envelope control system retains ultimate control when flying under what law?", options: ["Alternate law", "Normal law", "Direct law"], correctOptionIndex: 1 },
  { id: 209, text: "A340-600 has what type of backup rudder control system?", options: ["Mechanical", "Purely electrical (not electronic)", "Hydraulic"], correctOptionIndex: 1 },
  { id: 210, text: "In Airbus philosophy, sidestick displacement is a command for what?", options: ["Force", "Rate", "Position"], correctOptionIndex: 1 },
  { id: 211, text: "What phenomenon occurs at specific high speeds and can cause vibration of the airframe?", options: ["Dutch roll", "Control surface flutter", "Phugoid oscillation"], correctOptionIndex: 1 },
  { id: 212, text: "One remedy for flutter is to set a specific mass where relative to the control surface hinge-line?", options: ["Behind the hinge-line", "Some distance ahead of the hinge-line", "At the hinge-line"], correctOptionIndex: 1 },
  { id: 213, text: "On directly operated cable systems, what is connected between structure and control surface to prevent flutter?", options: ["Springs", "Separate dampers", "Mass balances"], correctOptionIndex: 1 },
  { id: 214, text: "The force necessary to rotate the damper drive shaft is proportional to what?", options: ["Position", "Speed of the motion", "Temperature"], correctOptionIndex: 1 },
  { id: 215, text: "Aircraft rigging primarily involves adjustment of what?", options: ["Engine controls", "Flight control surface's range of movement and neutral position", "Landing gear"], correctOptionIndex: 1 },
  { id: 216, text: "Rigging involves setting what?", options: ["Only cable tension", "Cable tension, travel limits, and primary/secondary stops", "Only travel limits"], correctOptionIndex: 1 },
  { id: 217, text: "Tools for measuring surface travel include what?", options: ["Only rulers", "Protractors, rigging fixtures, contour templates, and rulers", "Only protractors"], correctOptionIndex: 1 },
  { id: 218, text: "When is rigging and adjustment carried out?", options: ["Only at specified intervals", "At specified intervals and after disturbing any part of the control system", "Only after component replacement"], correctOptionIndex: 1 },
  { id: 219, text: "Before operating any flying control system, what must be checked first?", options: ["Hydraulic pressure", "That there are no obstructions which could damage control surface", "Electrical power"], correctOptionIndex: 1 },
  { id: 220, text: "In rigging an aircraft control system, it is sometimes necessary to do what to the aircraft?", options: ["Jack it up", "Level it both laterally and longitudinally", "Drain fuel"], correctOptionIndex: 1 },
  { id: 221, text: "The first action in rigging is to set the cockpit to neutral and lock it using what?", options: ["Control lock", "Equipment provided for the particular system", "Tape"], correctOptionIndex: 1 },
  { id: 222, text: "Rigging pins are used for what purpose?", options: ["To lock control surfaces in place for flight", "To positively locate and lock control system in neutral during rigging", "To secure cables"], correctOptionIndex: 1 },
  { id: 223, text: "The first pins, called the No. 1 or master pin, is fitted where?", options: ["At the control surface", "At the cockpit end of the control run", "At the midpoint of the cable run"], correctOptionIndex: 1 },
  { id: 224, text: "When all rigging pins have been fitted, what has been achieved?", options: ["System is ready for flight", "That particular control run has been adjusted to and locked in neutral", "Maximum travel has been set"], correctOptionIndex: 1 },
  { id: 225, text: "What is vital to check on completion of rigging work?", options: ["Cable tension", "That complete set of rigging pins are removed", "That all fasteners are tight"], correctOptionIndex: 1 },
  { id: 226, text: "Control surface setting gauges are used to check what?", options: ["Cable tension", "Neutral and maximum travel position of controllable aerofoil surfaces", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 227, text: "Checking for the sense of movement is vital to prevent what?", options: ["Overspeed", "Inadvertent cross-over of connections that would reverse control surface movement", "Stall"], correctOptionIndex: 1 },
  { id: 228, text: "Maximum travel of a primary control surface is limited by what?", options: ["Pilot input", "Primary mechanical (limit) stops", "Aerodynamic forces"], correctOptionIndex: 1 },
  { id: 229, text: "Secondary stops or 'override stops' are fitted to do what?", options: ["Limit control surface movement", "Limit pilot's control movement should the main stop fail", "Provide emergency stopping"], correctOptionIndex: 1 },
  { id: 230, text: "Break-out force represents what?", options: ["Running friction", "Amount of static friction in the system", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 231, text: "The force required to keep the control system moving represents what?", options: ["Static friction", "Running friction", "Break-out force"], correctOptionIndex: 1 },
];
