export const fuelSystemsQuestions = [
  { id: 1, text: "The weight of fuel may range from about what percentage of gross weight for small personal aeroplanes to more than what percentage for some business jets?", options: ["5% to 20%", "10% to 40%", "15% to 50%"], correctOptionIndex: 1 },
  { id: 2, text: "What has caused more aircraft accidents than failures of any other single system?", options: ["Engine failures", "Improper management of the fuel system", "Landing gear failures"], correctOptionIndex: 1 },
  { id: 3, text: "What may clog strainers and shut off fuel flow to engines?", options: ["Air bubbles", "Contamination in the fuel", "High temperature"], correctOptionIndex: 1 },
  { id: 4, text: "Water in turbine-powered aircraft is a special problem because jet fuel holds water in what form?", options: ["Large droplets", "Entrained in tiny particles that do not easily settle out", "Dissolved completely"], correctOptionIndex: 1 },
  { id: 5, text: "At high altitude, water may form ice crystals which can do what?", options: ["Melt and cause problems", "Freeze on fuel filters and shut off fuel flow", "Evaporate"], correctOptionIndex: 1 },
  { id: 6, text: "According to regulations, no pump can draw fuel from more than how many tanks at a time?", options: ["Two", "One", "Three"], correctOptionIndex: 1 },
  { id: 7, text: "Turbine-powered aircraft must be capable of sustained operation when there is at least how much free water per gallon of fuel?", options: ["0.50 cc", "0.75 cc", "1.00 cc"], correctOptionIndex: 1 },
  { id: 8, text: "Each fuel system of a multi-engine aircraft must be arranged so that failure of any one component (except the fuel tank) will not cause more than how many engines to lose power?", options: ["Two engines", "One engine", "All engines"], correctOptionIndex: 1 },
  { id: 9, text: "Tanks used in multi-engine fuel systems must have how many vents arranged so they are not likely to both become plugged at the same time?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 10, text: "A pump feed fuel system must be able to flow what percentage of the takeoff fuel flow required for a jet engine?", options: ["100%", "125%", "150%"], correctOptionIndex: 1 },
  { id: 11, text: "If a selector valve allows operation from more than one tank, the system must not cause loss of power for more than how many seconds for a single-engine aircraft?", options: ["5 seconds", "10 seconds", "20 seconds"], correctOptionIndex: 1 },
  { id: 12, text: "For a multi-engine aircraft, the loss of power when switching tanks must not exceed how many seconds?", options: ["10 seconds", "20 seconds", "30 seconds"], correctOptionIndex: 1 },
  { id: 13, text: "Turbine-powered aircraft must have a fuel system that will supply what percentage of fuel required in all flight attitudes?", options: ["125%", "100%", "150%"], correctOptionIndex: 1 },
  { id: 14, text: "Each fuel tank must have what percentage expansion space that cannot be filled with fuel?", options: ["1%", "2%", "5%"], correctOptionIndex: 1 },
  { id: 15, text: "For reciprocating engines, the strainer should have what mesh element?", options: ["4 to 8-mesh", "8 to 16-mesh", "16 to 24-mesh"], correctOptionIndex: 1 },
  { id: 16, text: "CDCCL stands for what?", options: ["Critical Design Configuration Control Limitations", "Critical Design Configuration Control Limitations", "Critical Design Control Limitations"], correctOptionIndex: 1 },
  { id: 17, text: "CDCCLs are a means of identifying design features intended to preclude what?", options: ["Engine failure", "Fuel tank ignition source for the operational life of the aeroplane", "Structural failure"], correctOptionIndex: 1 },
  { id: 18, text: "CDCCLs are mandatory and cannot be changed without approval from whom?", options: ["The airline", "The authority responsible for the aeroplane type certificate", "The manufacturer"], correctOptionIndex: 1 },
  { id: 19, text: "In larger long-range aircraft, additional tanks can be installed where for centre of gravity control?", options: ["In the wings only", "In the horizontal stabiliser", "In the fuselage only"], correctOptionIndex: 1 },
  { id: 20, text: "The fuel system consists of which subsystems?", options: ["Only storage and feed", "Storage and ventilation, feed, refuelling/defueling, quantity indication, jettison, longitudinal trim", "Only pumps and valves"], correctOptionIndex: 1 },
  { id: 21, text: "In general, the number of main tanks present in an aeroplane is determined by what?", options: ["Wing size", "Number of engines", "Fuselage length"], correctOptionIndex: 1 },
  { id: 22, text: "Each engine is supplied with fuel from where?", options: ["Any available tank", "Its own main tank", "The centre tank"], correctOptionIndex: 1 },
  { id: 23, text: "The APU is generally supplied with fuel from where?", options: ["Its own dedicated tank", "A main tank", "The centre tank"], correctOptionIndex: 1 },
  { id: 24, text: "If auxiliary tanks are filled, the general rule is that they should be emptied how?", options: ["Last", "As quickly as possible by pumping to main tanks", "Simultaneously with main tanks"], correctOptionIndex: 1 },
  { id: 25, text: "Fuel tanks are manufactured from materials that will not do what?", options: ["Conduct electricity", "React chemically with any aviation fuel", "Corrode"], correctOptionIndex: 1 },
  { id: 26, text: "What is provided at the lowest point in the tank?", options: ["Vent", "Sumps and drains", "Filler cap"], correctOptionIndex: 1 },
  { id: 27, text: "What is fitted in all except the smallest of tanks to resist fuel surging?", options: ["Pumps", "Baffles", "Valves"], correctOptionIndex: 1 },
  { id: 28, text: "An expansion space is provided in fuel tanks to allow for what?", options: ["Air expansion", "Increase in fuel volume due to expansion", "Pressure changes"], correctOptionIndex: 1 },
  { id: 29, text: "Dump valves make it possible to do what during flight?", options: ["Transfer fuel", "Jettison fuel to reduce weight to specified landing weight", "Check fuel quantity"], correctOptionIndex: 1 },
  { id: 30, text: "Where are the operating controls for dump valves located?", options: ["Outside the aircraft", "Within reach of the pilot, co-pilot or flight engineer", "In the cabin"], correctOptionIndex: 1 },
  { id: 31, text: "Main tanks are of what type?", options: ["Bladder type", "Integral type", "Rigid type"], correctOptionIndex: 1 },
  { id: 32, text: "What type of tank has the advantage of using maximum space and minimum weight?", options: ["Bladder tank", "Integral fuel tank", "Rigid tank"], correctOptionIndex: 1 },
  { id: 33, text: "In an integral tank, what prevents fuel from surging towards the wing tip when the aircraft rolls?", options: ["Baffles", "Gravity-closed flapper valves", "Pumps"], correctOptionIndex: 1 },
  { id: 34, text: "For maintenance purposes, panels are provided where?", options: ["Only on upper side", "Usually on lower side, some on upper side", "Only on the ends"], correctOptionIndex: 1 },
  { id: 35, text: "The most popular sealing method for tank access panels these days is what?", options: ["Gasket type", "O-ring type", "Sealant only"], correctOptionIndex: 1 },
  { id: 36, text: "When installing a removed tank access panel, what must be used?", options: ["Old gasket if still good", "A new gasket/O-ring", "Sealant only"], correctOptionIndex: 1 },
  { id: 37, text: "Why is it important to install the correct bolt length for access panels?", options: ["For appearance", "To prevent damage to panel or dome nut resulting in a leak", "For weight reasons"], correctOptionIndex: 1 },
  { id: 38, text: "Tank access panels are what type of members of the wing?", options: ["Non-structural", "Structural", "Aerodynamic"], correctOptionIndex: 1 },
  { id: 39, text: "Bladder tanks are made of what material?", options: ["Metal", "Thin fabric impregnated with neoprene", "Rigid plastic"], correctOptionIndex: 1 },
  { id: 40, text: "How is the bladder installed into the cavity?", options: ["As a rigid unit", "By folding it and inserting through an inspection opening", "By inflating it"], correctOptionIndex: 1 },
  { id: 41, text: "Bladder tanks should never be allowed to stand empty for what period?", options: ["Short period", "Extended period", "Any period"], correctOptionIndex: 1 },
  { id: 42, text: "The fuel feed or supply system transports fuel to what?", options: ["Only the engines", "The engines and the auxiliary power unit (APU)", "Only the APU"], correctOptionIndex: 1 },
  { id: 43, text: "The feed system includes which parts?", options: ["Only pumps and valves", "Fuel pumps, non-return valves, fire shut-off valves, crossfeed system", "Only pipes and tanks"], correctOptionIndex: 1 },
  { id: 44, text: "In modern turbine-powered aircraft, fuel is usually contained in several integral tanks located where?", options: ["Only in the wings", "In the wings, centre section, and occasionally in the fin and/or horizontal stabiliser", "Only in the fuselage"], correctOptionIndex: 1 },
  { id: 45, text: "Crossfeed and inter-engine valves may be provided to enable what?", options: ["Faster refuelling", "Engines to be fed from any desired group of tanks and fuel transfer between tanks", "Fuel dumping"], correctOptionIndex: 1 },
  { id: 46, text: "In the case of full tanks, fuel from main tanks must be consumed before they are refilled from where?", options: ["Centre tank", "Auxiliary tanks", "APU tank"], correctOptionIndex: 0 },
  { id: 47, text: "How many booster pumps are typically fitted in each tank?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 48, text: "In the event of failure of both pumps in a tank, fuel can be drawn by the engine-driven pump via what?", options: ["Bypass line", "Suction valve", "Check valve"], correctOptionIndex: 1 },
  { id: 49, text: "In some instances, the motor is of the flooded type, which means what?", options: ["It is sealed from fuel", "The motor runs submerged in fuel, eliminating need for seals", "It is cooled by air"], correctOptionIndex: 1 },
  { id: 50, text: "Overheat protectors cut off power when pump temperature rises above what?", options: ["A specified temperature", "A predetermined value", "Ambient temperature"], correctOptionIndex: 1 },
  { id: 51, text: "Pumps are often fitted in isolation chambers to allow what?", options: ["Easier access", "Removal and refitting without draining the tank", "Better cooling"], correctOptionIndex: 1 },
  { id: 52, text: "The purpose of the low-pressure fuel pump is to feed fuel from tanks to the engine pump to prevent what?", options: ["Overheating", "Cavitation and formation of vapour", "Leakage"], correctOptionIndex: 1 },
  { id: 53, text: "For quick replacement during ground time, the pump can be removed without doing what?", options: ["Depressurizing", "Draining the tanks", "Shutting down engines"], correctOptionIndex: 1 },
  { id: 54, text: "The most common type of auxiliary fuel pump on large aircraft is what?", options: ["Vane pump", "Centrifugal pump", "Pulsating pump"], correctOptionIndex: 1 },
  { id: 55, text: "Centrifugal pumps are most frequently located how?", options: ["Outside the tank only", "Submerged in the fuel tank or just outside with inlet extending into tank", "In the cockpit"], correctOptionIndex: 1 },
  { id: 56, text: "If the pump is mounted outside the tank, what is installed so the pump can be removed without draining the tank?", options: ["Check valve", "Pump removal valve", "Drain valve"], correctOptionIndex: 1 },
  { id: 57, text: "A centrifugal boost pump is what type of displacement pump?", options: ["Constant displacement", "Variable displacement", "Fixed displacement"], correctOptionIndex: 0 },
  { id: 58, text: "What prevents fuel from flowing back through a centrifugal pump?", options: ["Bypass valve", "Outlet non-return valve", "Pressure relief valve"], correctOptionIndex: 1 },
  { id: 59, text: "The inlet of centrifugal pumps is covered with what to prevent ingestion of foreign matter?", options: ["Filter", "A screen", "Strainer"], correctOptionIndex: 1 },
  { id: 60, text: "Ejector pumps are also known as what?", options: ["Transfer pumps", "Jet pumps", "Boost pumps"], correctOptionIndex: 1 },
  { id: 61, text: "An ejector pump uses what principle to draw fuel?", options: ["Bernoulli principle", "Venturi principle", "Pascal principle"], correctOptionIndex: 1 },
  { id: 62, text: "Where might you find ejector pumps used?", options: ["In main feed lines", "In vent surge tanks or centre tanks where no direct engine feed takes place", "In engine-driven pumps"], correctOptionIndex: 1 },
  { id: 63, text: "The ejector pump has two fuel inlets: the motive-flow inlet and what?", options: ["Return inlet", "Suction inlet", "Bypass inlet"], correctOptionIndex: 1 },
  { id: 64, text: "The motive-flow inlet receives fuel from where?", options: ["The tank", "The electrically driven fuel pump", "The engine"], correctOptionIndex: 1 },
  { id: 65, text: "The mixed flow becomes stable in the mixing tube and slows down in the diffuser before going where?", options: ["Overboard", "Into the connected tank", "Back to the pump"], correctOptionIndex: 1 },
  { id: 66, text: "Smaller turbine aircraft often use what type of auxiliary fuel pump?", options: ["Centrifugal", "Pulsating electric pump or plunger-type", "Vane-type"], correctOptionIndex: 1 },
  { id: 67, text: "The pulsating electric pump is plumbed in what configuration with the engine-driven pump?", options: ["Series", "Parallel", "Independently"], correctOptionIndex: 1 },
  { id: 68, text: "The pulsating electric pump uses what to draw fuel in and push it out?", options: ["Impeller", "Plunger", "Vanes"], correctOptionIndex: 1 },
  { id: 69, text: "The pump is powered by a solenoid that alternates between being energised and de-energised, creating what type of motion?", options: ["Rotary", "Pulsating", "Continuous"], correctOptionIndex: 1 },
  { id: 70, text: "The single-acting pulsating electric pump responds to what at its outlet?", options: ["Temperature", "Pressure of the fuel", "Flow rate"], correctOptionIndex: 1 },
  { id: 71, text: "Vane-type fuel pumps are what type of displacement pump?", options: ["Variable displacement", "Constant displacement", "Pulsating displacement"], correctOptionIndex: 1 },
  { id: 72, text: "Vane-type pumps move a constant volume of fuel with each what?", options: ["Cycle", "Revolution of the pump", "Pulse"], correctOptionIndex: 1 },
  { id: 73, text: "In a vane pump, an eccentric rotor is driven inside what?", options: ["A housing", "A cylinder", "A chamber"], correctOptionIndex: 0 },
  { id: 74, text: "Most vane pumps have what feature to regulate flow?", options: ["Bypass valve", "Adjustable pressure relief", "Flow control valve"], correctOptionIndex: 1 },
  { id: 75, text: "The pressure relief valve returns excess fuel to where?", options: ["Tank", "Inlet side of the pump", "Engine"], correctOptionIndex: 1 },
  { id: 76, text: "What allows fuel to flow through the pump during starting or if the pump is inoperative?", options: ["Relief valve", "Bypass valve", "Check valve"], correctOptionIndex: 1 },
  { id: 77, text: "Compensated vane-type pumps are used when the vane pump is what?", options: ["Auxiliary pump", "Engine-driven primary fuel pump", "Transfer pump"], correctOptionIndex: 1 },
  { id: 78, text: "Float-operated switches are often of what type to isolate the electrical mechanism from the fuel tank?", options: ["Mechanical type", "Magnetic type", "Hydraulic type"], correctOptionIndex: 1 },
  { id: 79, text: "Upward movement of the float brings the armature closer to what?", options: ["Switch", "The magnet", "Contact"], correctOptionIndex: 1 },
  { id: 80, text: "Pressure switches are installed to monitor what?", options: ["Tank level", "Output pressure of each fuel pump", "Temperature"], correctOptionIndex: 1 },
  { id: 81, text: "For quick replacement without entering the tank, pressure switches are often placed where?", options: ["Inside the tank", "Outside of the fuel tank", "On the engine"], correctOptionIndex: 1 },
  { id: 82, text: "The primary components of the pressure switch are the body and what?", options: ["The sensor", "The adapter", "The valve"], correctOptionIndex: 0 },
  { id: 83, text: "The body of a pressure switch contains what?", options: ["Only the switch", "Flexible diaphragm, switch mechanism, and electrical microswitch", "Only the diaphragm"], correctOptionIndex: 1 },
  { id: 84, text: "The flexible diaphragm isolates what from the fuel?", options: ["The pressure", "The switch mechanism and microswitch", "The body"], correctOptionIndex: 1 },
  { id: 85, text: "Low-pressure valves, cross feed valves, and inter-engine valves are usually what type?", options: ["Gate type", "Ball-type, full-flow valves", "Butterfly type"], correctOptionIndex: 1 },
  { id: 86, text: "Ball-type valves may be either mechanically or how operated?", options: ["Hydraulically", "Electrically", "Pneumatically"], correctOptionIndex: 1 },
  { id: 87, text: "When the valve is electrically operated, what type of motor drives it?", options: ["Induction motor", "Reversible electric motor with electromagnetic brake", "Stepper motor"], correctOptionIndex: 1 },
  { id: 88, text: "Limit switches cut off power at what positions?", options: ["Mid-travel", "Fully-open and fully-closed", "25% and 75%"], correctOptionIndex: 1 },
  { id: 89, text: "Suction valves are fitted to enable what?", options: ["Fuel transfer", "Fuel to be drawn from tanks by engine-driven pumps", "Refuelling"], correctOptionIndex: 1 },
  { id: 90, text: "A suction valve is what type of valve?", options: ["Ball type", "Simple flap type", "Gate type"], correctOptionIndex: 1 },
  { id: 91, text: "The suction valve closes when pressure exists and opens when what is applied?", options: ["Vacuum", "Suction", "Heat"], correctOptionIndex: 0 },
  { id: 92, text: "Non-return valves are fitted to provide flow in how many directions?", options: ["Two", "One direction only", "Both directions"], correctOptionIndex: 1 },
  { id: 93, text: "The casing of a non-return valve is marked with what to show direction of flow?", options: ["A dot", "An arrow", "A line"], correctOptionIndex: 1 },
  { id: 94, text: "The air release valve releases what trapped in the engine fuel feed line?", options: ["Fuel vapour", "Air", "Water"], correctOptionIndex: 1 },
  { id: 95, text: "Where is the air release valve installed?", options: ["At the pump outlet", "At the highest point of the fuel line", "At the tank outlet"], correctOptionIndex: 1 },
  { id: 96, text: "The fire shut-off valve is also called what?", options: ["Emergency valve", "Low pressure shut-off valve", "Safety valve"], correctOptionIndex: 1 },
  { id: 97, text: "The function of the fire shut-off valve is to cut off fuel supply in case of what?", options: ["Engine overspeed", "External fire or defect requiring engine isolation", "Fuel leak"], correctOptionIndex: 1 },
  { id: 98, text: "There is at least how many fire shut-off valves in each supply line?", options: ["None", "One", "Two"], correctOptionIndex: 1 },
  { id: 99, text: "The APU fire shut-off valve is generally operated how?", options: ["Mechanically", "Electrically", "Hydraulically"], correctOptionIndex: 1 },
  { id: 100, text: "If valves are electrically driven, how many actuators are installed for redundancy?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 101, text: "The two actuators are supplied from where?", options: ["The same source", "Different power sources", "Battery only"], correctOptionIndex: 1 },
  { id: 102, text: "A light aircraft fuel filter normally consists of what components?", options: ["Only a housing", "Housing, filter element, sediment bowl, and drain valve", "Only a filter element"], correctOptionIndex: 1 },
  { id: 103, text: "Where are light aircraft filters often placed?", options: ["In the pressure line", "In the suction line to the pump", "At the tank outlet"], correctOptionIndex: 1 },
  { id: 104, text: "Main filters on turbine engines may incorporate what to operate an icing warning lamp?", options: ["Temperature switch", "Differential pressure switch", "Flow switch"], correctOptionIndex: 1 },
  { id: 105, text: "Rigid pipes in aircraft fuel systems are generally manufactured from what material?", options: ["Copper", "Aluminium alloy tubing", "Steel"], correctOptionIndex: 1 },
  { id: 106, text: "Fire resistant and fireproof materials such as stainless steel or titanium must be used where?", options: ["Throughout the system", "Forward of the engine bulkhead and other specified areas", "Only in the tanks"], correctOptionIndex: 1 },
  { id: 107, text: "Flexible couplings provide for what types of movement?", options: ["Only angular movement", "Misalignment, angular and axial movement", "Only axial movement"], correctOptionIndex: 1 },
  { id: 108, text: "In a Vee-clamp coupling, what forms the seal?", options: ["Gasket", "O-ring", "Metal-to-metal contact"], correctOptionIndex: 1 },
  { id: 109, text: "Bonding of fuel system pipes is very important to prevent what in the explosive atmosphere?", options: ["Corrosion", "Static electricity causing sparks", "Leakage"], correctOptionIndex: 1 },
  { id: 110, text: "What are used to form a conducting path across couplings and between pipes and structure?", options: ["Wires", "Bonding strips or cables", "Clamps"], correctOptionIndex: 1 },
  { id: 111, text: "The identification label for fuel is what colour?", options: ["Blue", "Red", "Yellow"], correctOptionIndex: 2 },
  { id: 112, text: "The fuel label is marked with what word?", options: ["GAS", "FUEL", "PETROL"], correctOptionIndex: 1 },
  { id: 113, text: "Cross-feed refers to utilizing fuel from one tank to do what?", options: ["Feed one engine only", "Supply engines on both sides simultaneously", "Transfer to another tank"], correctOptionIndex: 1 },
  { id: 114, text: "What do aircraft fuel systems incorporate to allow cross-feed?", options: ["Transfer pumps", "Cross-feed valves", "Non-return valves"], correctOptionIndex: 1 },
  { id: 115, text: "Fuel transfer involves moving fuel between tanks to do what?", options: ["Increase fuel capacity", "Shift the centre of gravity or supply engines during specific flight phases", "Cool the fuel"], correctOptionIndex: 1 },
  { id: 116, text: "To facilitate fuel transfer, aircraft employ what?", options: ["Gravity only", "Transfer pumps", "Siphon systems"], correctOptionIndex: 1 },
  { id: 117, text: "Fuel cross-feed and transfer is typically initiated by what?", options: ["Gravity", "Booster pumps", "Engine pumps"], correctOptionIndex: 1 },
  { id: 118, text: "Light aircraft fuel tanks are usually filled through what type of filler caps?", options: ["Pressure", "Over-wing", "Under-wing"], correctOptionIndex: 1 },
  { id: 119, text: "On large transport aircraft, refuelling is normally carried out through what connections?", options: ["Over-wing", "Pressure refuelling connections in lower wing or fuselage surfaces", "Under-wing"], correctOptionIndex: 1 },
  { id: 120, text: "Refuelling rates of up to what may be achieved using pressure refuelling?", options: ["500 gal/min", "1,000 gal/min", "1,500 gal/min"], correctOptionIndex: 1 },
  { id: 121, text: "Defueling is carried out using the same system but with what applied to the pressure connections?", options: ["Pressure", "Suction", "Heat"], correctOptionIndex: 1 },
  { id: 122, text: "The system includes pressure connections, individual refuel/defuel valves, and what else?", options: ["Pumps only", "A load control panel", "Indicators only"], correctOptionIndex: 1 },
  { id: 123, text: "Refuelling points should be marked with what?", options: ["Only the capacity", "The type of fuel to be used", "Only the pressure rating"], correctOptionIndex: 1 },
  { id: 124, text: "Over-wing filling points should be marked with what?", options: ["Fuel type only", "Capacity of each tank", "Pressure rating"], correctOptionIndex: 1 },
  { id: 125, text: "A refuel/defuel system controls the flow of fuel into or out of the aircraft from where?", options: ["The cockpit", "A refuel control panel near the pressure coupling", "The wing"], correctOptionIndex: 1 },
  { id: 126, text: "Aircraft with large tank capacity can have how many refuel/defuel hoses connected to keep turnaround times short?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 127, text: "What are the two procedures to refuel an aircraft?", options: ["Gravity and pressure", "Pressure refuelling and over-wing refuelling", "Manual and automatic"], correctOptionIndex: 1 },
  { id: 128, text: "What are the two procedures to defuel an aircraft?", options: ["Gravity and suction", "Pressure defueling and suction defueling", "Manual and automatic"], correctOptionIndex: 1 },
  { id: 129, text: "The pressure fuelling system consists of pressure coupling, fuelling panel, manifolds, shut-off valves, fuel quantity system, and what else?", options: ["Pumps", "High-level sensing system", "Filters"], correctOptionIndex: 1 },
  { id: 130, text: "On the load control panel, fuel contents gauges are what type of instruments?", options: ["Single pointer", "Dual pointer", "Digital only"], correctOptionIndex: 1 },
  { id: 131, text: "One pointer indicates actual tank contents, and the other pointer is used for what?", options: ["Temperature", "Preselecting the required quantity", "Pressure"], correctOptionIndex: 1 },
  { id: 132, text: "When the quantity of fuel pre-selected for a tank has been uplifted, what happens?", options: ["Warning light illuminates", "Micro-switch circuit breaks and refuel/defuel valve closes", "Pump stops"], correctOptionIndex: 1 },
  { id: 133, text: "Aviation fuels are both highly flammable and what?", options: ["Stable", "Volatile", "Inert"], correctOptionIndex: 1 },
  { id: 134, text: "What type of fire extinguisher should be available when fuelling?", options: ["Water type", "Proper type for fuel fires", "CO₂ only"], correctOptionIndex: 1 },
  { id: 135, text: "Where should aircraft never be serviced with fuel?", options: ["Outdoors", "Inside a hangar or closed area", "On the ramp"], correctOptionIndex: 1 },
  { id: 136, text: "What is a less visible but obvious source of ignition during fuelling?", options: ["Cigarettes", "Sparks created by static electricity", "Open flames"], correctOptionIndex: 1 },
  { id: 137, text: "What may be expected when handling turbine fuels compared to aviation gasoline?", options: ["Less static generation", "Greater generation of static electricity", "Same static generation"], correctOptionIndex: 1 },
  { id: 138, text: "To minimise static hazard, what must be done?", options: ["Use special nozzles", "Bond and ground all components of the fuelling system", "Fuel slowly"], correctOptionIndex: 1 },
  { id: 139, text: "The earthing wire should be connected in what sequence during refuelling?", options: ["Fueller to aircraft first", "Fueller to ground, then fueller to aircraft", "Aircraft to ground only"], correctOptionIndex: 1 },
  { id: 140, text: "Before opening an over-wing fuel filler cap, what must be connected?", options: ["Fuel hose", "Nozzle ground to the aircraft", "Vent hose"], correctOptionIndex: 1 },
  { id: 141, text: "Should nozzles ever be propped open while fuelling?", options: ["Yes, if supervised", "No, never", "Only for large aircraft"], correctOptionIndex: 1 },
  { id: 142, text: "Leaving a filler cap off an aircraft fuel tank can be what?", options: ["Acceptable", "Very dangerous", "Normal procedure"], correctOptionIndex: 1 },
  { id: 143, text: "The combustion process in the jet engine requires complicated precision fuel control systems that are more sensitive to what?", options: ["Temperature", "Fuel quality and cleanliness", "Pressure"], correctOptionIndex: 1 },
  { id: 144, text: "A particle of dirt or water settles out of aviation gasoline how many times faster than in turbine fuels?", options: ["Two times", "Four times", "Ten times"], correctOptionIndex: 2 },
  { id: 145, text: "Solid contaminants may be thought of as those which will not do what in fuel?", options: ["Float", "Dissolve", "Settle"], correctOptionIndex: 1 },
  { id: 146, text: "The most common solid contaminants are what?", options: ["Plastic and rubber", "Iron rust, scale, sand, and dirt", "Fibre and lint"], correctOptionIndex: 1 },
  { id: 147, text: "Surfactants is a contraction of what words?", options: ["Surface friction agents", "Surface active agents", "Surface treatment agents"], correctOptionIndex: 1 },
  { id: 148, text: "Surfactants are usually more soluble in what than in fuel?", options: ["Oil", "Water", "Air"], correctOptionIndex: 1 },
  { id: 149, text: "Surfactants reduce what between water and fuel?", options: ["Viscosity", "Interfacial tension", "Density"], correctOptionIndex: 1 },
  { id: 150, text: "Surfactants can cause what type of problems?", options: ["Engine failure", "Fuel gauge problems", "Pump failure"], correctOptionIndex: 1 },
  { id: 151, text: "Water in fuel is a major hazard because of the possibility of what interrupting fuel flow?", options: ["Corrosion", "Ice crystals", "Sludge"], correctOptionIndex: 1 },
  { id: 152, text: "How many different species of micro-organisms can live in free water in fuel tanks?", options: ["Less than 50", "Over 100", "Over 500"], correctOptionIndex: 1 },
  { id: 153, text: "The principle effects of micro-organisms include formation of sludge, emulsification of fuel, and what else?", options: ["Fuel degradation", "Creation of corrosive compounds", "Colour change"], correctOptionIndex: 1 },
  { id: 154, text: "Severe corrosion of aircraft tanks has been attributed to what?", options: ["Water", "Micro-organisms", "Fuel additives"], correctOptionIndex: 1 },
  { id: 155, text: "The most important preventive step for microbial contamination is what?", options: ["Using biocides", "Keeping the amount of water in fuel storage tanks as low as possible", "Frequent tank cleaning"], correctOptionIndex: 1 },
  { id: 156, text: "Since biocides are toxic, any water containing them must be what?", options: ["Reused", "Disposed of appropriately", "Stored"], correctOptionIndex: 1 },
  { id: 157, text: "Aviation gasoline is generally considered 'clean' if a one-quart sample is what?", options: ["Coloured correctly", "Clear of any sediment when viewed in a clean glass container", "Free of odour"], correctOptionIndex: 1 },
  { id: 158, text: "The aviation industry has adopted what test for checking turbine fuel cleanliness?", options: ["Colour test", "Millipore test", "Smell test"], correctOptionIndex: 1 },
  { id: 159, text: "The Millipore test can detect contaminants down to what size?", options: ["0.08 micron", "0.8 micron", "8 micron"], correctOptionIndex: 1 },
  { id: 160, text: "The 'white bucket' test is particularly helpful in detecting what?", options: ["Water", "Surfactants", "Solids"], correctOptionIndex: 0 },
  { id: 161, text: "The greatest single danger to aircraft safety from contaminated fuels is attributed to what?", options: ["Micro-organisms", "Human error", "Water"], correctOptionIndex: 2 },
  { id: 162, text: "'Clear and bright' means fuel is completely free of visible solid contamination and what?", options: ["Odour", "Water", "Colour"], correctOptionIndex: 1 },
  { id: 163, text: "Cloudy or hazy fuel is usually caused by what?", options: ["Temperature", "Free and dispersed water", "Air bubbles"], correctOptionIndex: 1 },
  { id: 164, text: "The Shell Water Detector (SWD) uses a small yellow capsule that changes to what colour when water is present?", options: ["Blue", "Green", "Red"], correctOptionIndex: 2 },
  { id: 165, text: "The SWD detects water contamination at around what concentration?", options: ["10 ppm", "30 ppm", "50 ppm"], correctOptionIndex: 1 },
  { id: 166, text: "In the Hydrokit test, the powder changes from white to what colour if fuel contains about 30 ppm or more of free water?", options: ["Blue", "Pink", "Yellow"], correctOptionIndex: 1 },
  { id: 167, text: "If using a Hydrokit and the powder stays white, what does this indicate?", options: ["Water is present", "The sample is fuel", "The test failed"], correctOptionIndex: 1 },
  { id: 168, text: "The flammability of a fuel depends largely on what?", options: ["Colour", "Flash point", "Viscosity"], correctOptionIndex: 1 },
  { id: 169, text: "Which is safer to handle, kerosene or gasoline?", options: ["Gasoline", "Kerosene", "Both are equally safe"], correctOptionIndex: 1 },
  { id: 170, text: "The aircraft should be electrically earthed, and ground equipment should be earthed to what?", options: ["Ground", "The aircraft", "Each other"], correctOptionIndex: 0 },
  { id: 171, text: "What type of lamps and torches should be used?", options: ["Standard", "Explosion-proof", "LED only"], correctOptionIndex: 1 },
  { id: 172, text: "What should be worn in areas of high vapour concentration near an open tank access hole?", options: ["Safety glasses", "Air-fed respirators", "Gloves"], correctOptionIndex: 1 },
  { id: 173, text: "Refuelling and defuelling should normally be carried out where?", options: ["In a hangar", "In the open air", "Anywhere"], correctOptionIndex: 1 },
  { id: 174, text: "The earthing wire should remain in position until after what?", options: ["Refuelling starts", "The refuelling pipe is disconnected or filler cap replaced", "The aircraft departs"], correctOptionIndex: 1 },
  { id: 175, text: "Should radio or radar equipment be operated while refuelling is taking place?", options: ["Yes, if needed", "No", "Only VHF"], correctOptionIndex: 1 },
  { id: 176, text: "Where lagging has become contaminated with fuel, what should be done?", options: ["Leave it to dry", "Remove and clean the lagging, mop up residual fuel", "Cover it"], correctOptionIndex: 1 },
  { id: 177, text: "What material should NOT be used for blanking purposes in fuel systems?", options: ["Metal", "Cotton, paper, wood, and cork", "Plastic"], correctOptionIndex: 1 },
  { id: 178, text: "Blanks must be designed so that it is impossible to do what?", options: ["Remove them", "Re-connect the attaching component with a blank in place", "Identify them"], correctOptionIndex: 1 },
  { id: 179, text: "When jointing compound is used, what must be avoided?", options: ["Using any compound", "Using excessive amount that may enter the system", "Using sealant"], correctOptionIndex: 1 },
  { id: 180, text: "Fuel samples are normally collected in what container?", options: ["Metal can", "Glass jar", "Plastic bottle"], correctOptionIndex: 1 },
  { id: 181, text: "If microbiological contamination is found, what must be done?", options: ["Add biocide only", "Visually inspect for fungal deposits and remove them", "Drain fuel"], correctOptionIndex: 1 },
  { id: 182, text: "To remove a component, it will usually first be necessary to do what?", options: ["Depressurize system", "Drain some or all fuel in a tank or isolate part of the system", "Remove access panels"], correctOptionIndex: 1 },
  { id: 183, text: "The normal defueling system should be used to remove what?", options: ["Small quantities", "Large quantities of fuel", "Water only"], correctOptionIndex: 1 },
  { id: 184, text: "When removing union nuts, what is recommended to avoid twisting pipes?", options: ["One spanner", "Use of two spanners", "Pliers"], correctOptionIndex: 1 },
  { id: 185, text: "New seals and gaskets should be fitted, and blanks should be what?", options: ["Left in place", "Removed", "Replaced"], correctOptionIndex: 1 },
  { id: 186, text: "Where recommended, anti-seize compound should be applied to where?", options: ["Inside the pipe", "Threads", "Seals"], correctOptionIndex: 1 },
  { id: 187, text: "Seals should normally be lubricated with what?", options: ["Oil", "Mineral jelly or approved alternative", "Grease"], correctOptionIndex: 1 },
  { id: 188, text: "Pressure tests are normally required at regular intervals, after repairs, and when?", options: ["Before first flight", "Whenever leakage is suspected", "After every flight"], correctOptionIndex: 1 },
  { id: 189, text: "Test rigs should include an accurate pressure gauge, relief valve, and what else?", options: ["Thermometer", "Flowmeter", "Timer"], correctOptionIndex: 1 },
  { id: 190, text: "The vent, feed, and transfer systems are usually tested separately because different test pressures are prescribed and for what reason?", options: ["Different fluids used", "Different test pressures generally prescribed", "Different times required"], correctOptionIndex: 1 },
  { id: 191, text: "For vent system pressure test, all vent openings should be what?", options: ["Open", "Blanked", "Connected"], correctOptionIndex: 1 },
  { id: 192, text: "For feed system pressure test, the crossfeed and inter-engine valves should be what?", options: ["Open", "Closed", "Removed"], correctOptionIndex: 1 },
  { id: 193, text: "For all flow tests, the aircraft should be levelled laterally and longitudinally, and fuel tanks should contain what?", options: ["Full tanks", "Minimum quantity of fuel (unusable plus sufficient for test only)", "Half full"], correctOptionIndex: 1 },
  { id: 194, text: "A full flow test is normally only required after initial installation or what?", options: ["Every flight", "Major breakdown of the system", "Every 100 hours"], correctOptionIndex: 1 },
  { id: 195, text: "A limited flow test is often considered satisfactory after what?", options: ["Every flight", "A component has been changed", "Every 500 hours"], correctOptionIndex: 1 },
  { id: 196, text: "To check a gravity feed system, the feed pipe should be disconnected where?", options: ["At the tank", "At the carburettor", "At the pump"], correctOptionIndex: 1 },
  { id: 197, text: "DC quantity indicating systems consist of what as a tank unit?", options: ["Capacitor", "Variable resistor", "Inductor"], correctOptionIndex: 1 },
  { id: 198, text: "The tank unit uses a wiper arm driven by what to change resistance?", options: ["Motor", "A float", "Pressure"], correctOptionIndex: 1 },
  { id: 199, text: "The ratio meter-type minimises error that would be caused by variations in what?", options: ["Temperature", "System voltage", "Pressure"], correctOptionIndex: 1 },
  { id: 200, text: "Capacitance-type fuel quantity systems accurately determine what?", options: ["Volume of fuel", "Weight of the fuel in the tanks", "Density of fuel"], correctOptionIndex: 1 },
  { id: 201, text: "The measuring element (probe) in a tank consists of what?", options: ["Single tube", "Two concentrically mounted tubes", "Flat plates"], correctOptionIndex: 1 },
  { id: 202, text: "The tubes form what of a capacitor?", options: ["Dielectric", "The plates", "Insulator"], correctOptionIndex: 1 },
  { id: 203, text: "The capacity of a capacitor depends on area of plates, distance between plates, and what?", options: ["Temperature", "Dielectric constant of material between plates", "Pressure"], correctOptionIndex: 1 },
  { id: 204, text: "The only variable factor in a tank is what?", options: ["Plate area", "Dielectric constant", "Plate separation"], correctOptionIndex: 1 },
  { id: 205, text: "When the tank is empty, the plates are separated by air which has a dielectric constant of what?", options: ["Zero", "One", "Two"], correctOptionIndex: 1 },
  { id: 206, text: "When the tank is full, the dielectric is the fuel which has a constant of approximately what?", options: ["One", "Two", "Three"], correctOptionIndex: 2 },
  { id: 207, text: "A compensator is built into the bottom of one of the tank units to cancel changes in dielectric constant due to what?", options: ["Pressure", "Temperature of the fuel", "Viscosity"], correctOptionIndex: 1 },
  { id: 208, text: "The indicator in a digital fuel quantity system contains a power supply unit, probe driver, A/D converter, and what?", options: ["Display only", "A processor unit", "Memory"], correctOptionIndex: 1 },
  { id: 209, text: "The compensator senses what to calculate fuel weight?", options: ["Temperature", "Dielectric constant of the fuel", "Pressure"], correctOptionIndex: 1 },
  { id: 210, text: "The analogue signals from probes and compensator are converted to digital by what?", options: ["Processor", "A/D converter", "Driver"], correctOptionIndex: 1 },
  { id: 211, text: "What compensates for influences of pitch and roll angles on fuel quantity measurement?", options: ["Compensator", "Aircraft attitude signal", "Temperature sensor"], correctOptionIndex: 1 },
  { id: 212, text: "What senses the density of the fuel for fuel weight determination?", options: ["Compensator", "Densitometer", "Probe"], correctOptionIndex: 1 },
  { id: 213, text: "Ultrasonic fuel gauging relies on what phenomenon?", options: ["Electrical capacitance", "Sound energy transmitted through liquid and reflected", "Resistance change"], correctOptionIndex: 1 },
  { id: 214, text: "The velocity of sound in fuel is inversely proportional to what?", options: ["Pressure", "Temperature", "Density"], correctOptionIndex: 2 },
  { id: 215, text: "Ultrasonic fuel gauging depends on two measurements: speed of ultrasound and what?", options: ["Fuel temperature", "Round-trip time for sound to travel to fuel surface and back", "Fuel pressure"], correctOptionIndex: 1 },
  { id: 216, text: "Why is it not practical to use ultrasonic techniques from the top of the tank through the ullage?", options: ["Too expensive", "Very high energy required to transmit through air/vapour mixture", "Too inaccurate"], correctOptionIndex: 1 },
  { id: 217, text: "The velocimeter acts as what using a fixed target?", options: ["Level sensor", "Speed of sound calibration", "Temperature sensor"], correctOptionIndex: 1 },
  { id: 218, text: "The purpose of the stillwell is to reduce the effects of what?", options: ["Temperature changes", "Ripples and slosh", "Pressure changes"], correctOptionIndex: 1 },
  { id: 219, text: "At altitude, the reflected sound comprises direct path and what other signal?", options: ["Secondary reflection", "Zigzag (secondary) signal", "Tertiary signal"], correctOptionIndex: 1 },
  { id: 220, text: "The presence of large bubbles in the stillwell must be avoided because they cause what?", options: ["Fuel contamination", "Premature signal returns", "Pump cavitation"], correctOptionIndex: 1 },
  { id: 221, text: "The ultrasonic probe transducer features what type of disk?", options: ["Capacitive", "Piezoelectric ceramic", "Magnetic"], correctOptionIndex: 1 },
  { id: 222, text: "Typical resonant frequency of the crystal is between what values?", options: ["100 Hz and 1 kHz", "1 and 10 MHz", "100 MHz and 1 GHz"], correctOptionIndex: 1 },
  { id: 223, text: "The purpose of the stillwell is to collimate sound and provide what?", options: ["Temperature measurement", "A sheltered area to make measurements", "Pressure regulation"], correctOptionIndex: 1 },
  { id: 224, text: "A drip stick consists of a short outer tube and a long inner tube calibrated in what?", options: ["Pressure units", "Gallons or inches", "Pounds"], correctOptionIndex: 1 },
  { id: 225, text: "To check fuel contents with a drip stick, what is done?", options: ["Push the tube in", "Withdraw the inner tube slowly downwards until fuel drains", "Read the top of the tube"], correctOptionIndex: 1 },
  { id: 226, text: "The fuel float stick is also called what?", options: ["Dipstick", "Magnetic dip stick", "Level stick"], correctOptionIndex: 0 },
  { id: 227, text: "The float stick is operated how?", options: ["Electrically", "Manually", "Hydraulically"], correctOptionIndex: 1 },
  { id: 228, text: "A permanent magnet is installed where on the float stick?", options: ["At the bottom", "At the top of the stick (stick armature)", "On the float"], correctOptionIndex: 1 },
  { id: 229, text: "The float stick is unlocked by what action?", options: ["Pulling only", "Pressing and twisting", "Turning only"], correctOptionIndex: 1 },
  { id: 230, text: "When the float stick is unlocked and pulled down, the magnets stick together at what point?", options: ["When the stick is fully out", "When the float magnet and stick magnet align", "When the stick hits the bottom"], correctOptionIndex: 1 },
  { id: 231, text: "To determine aircraft position for float stick reading, what is used?", options: ["GPS", "A spirit level located in the aeroplane", "Inclinometer"], correctOptionIndex: 1 },
  { id: 232, text: "Wings of commercial jetliners normally have what?", options: ["Anhedral", "Positive dihedral", "No dihedral"], correctOptionIndex: 1 },
  { id: 233, text: "If an aeroplane has negative dihedral, it is termed what?", options: ["Dihedral", "Anhedral", "Cathédrale"], correctOptionIndex: 1 },
  { id: 234, text: "To find the correct stick to read, you should do what?", options: ["Read any stick", "Pull each stick and find the one in the floating state", "Read the innermost stick"], correctOptionIndex: 1 },
  { id: 235, text: "The cockpit indications for the fuel system are shown on what display?", options: ["PFD", "ECAM System Display (SD) Fuel page", "ND"], correctOptionIndex: 1 },
  { id: 236, text: "The external indications for the fuel system are shown on what?", options: ["The cockpit panel", "The refuel panel", "The engine"], correctOptionIndex: 1 },
  { id: 237, text: "Water droplets in fuel may freeze when fuel temperature falls below what?", options: ["10°C", "0°C", "-10°C"], correctOptionIndex: 2 },
  { id: 238, text: "Fuel heaters are usually what type of devices?", options: ["Electric heaters", "Heat-exchangers", "Chemical heaters"], correctOptionIndex: 1 },
  { id: 239, text: "Fuel heaters may utilise hydraulic oil, engine oil, or what as heating medium?", options: ["Electric current", "Air tapped from engine compressors", "Exhaust gas"], correctOptionIndex: 1 },
  { id: 240, text: "In a manually controlled fuel heating system, when fuel flow becomes restricted by ice, what operates?", options: ["Temperature switch", "Pressure differential switch on the fuel filter", "Flow switch"], correctOptionIndex: 1 },
  { id: 241, text: "The purpose of the ventilation system is to prevent structural damage by what?", options: ["Overheating", "Under-pressure or over-pressure", "Corrosion"], correctOptionIndex: 1 },
  { id: 242, text: "Each fuel tank must have an expansion space of not less than what percentage?", options: ["1%", "2%", "5%"], correctOptionIndex: 1 },
  { id: 243, text: "The vent surge tank is installed where?", options: ["At the wing root", "At the wing tips", "In the fuselage"], correctOptionIndex: 0 },
  { id: 244, text: "Between the ram air ports and the vent surge tank, what is installed in the ventilation line to keep flames from entering the tank?", options: ["Check valve", "Flame arrestor (fine-meshed screen)", "Non-return valve"], correctOptionIndex: 1 },
  { id: 245, text: "If fuel exists in the surge tanks, when will they be emptied?", options: ["Immediately", "When the engines are running", "On the ground"], correctOptionIndex: 1 },
  { id: 246, text: "A ram air intake maintains what in the vent system to decrease fuel vaporisation?", options: ["Vacuum", "Slight positive pressure", "Neutral pressure"], correctOptionIndex: 1 },
  { id: 247, text: "In some aircraft, the vent system also prevents building up of dangerous pressures during refuelling by doing what?", options: ["Warning the crew", "Dumping excess fuel", "Closing valves"], correctOptionIndex: 1 },
  { id: 248, text: "The float valves have a float that senses what?", options: ["Pressure", "Fuel level in the tank", "Temperature"], correctOptionIndex: 1 },
  { id: 249, text: "If an uncoordinated manoeuvre occurs, fuel goes to the lower wing tip and the float valve does what?", options: ["Opens", "Closes", "Remains unchanged"], correctOptionIndex: 1 },
  { id: 250, text: "Non-return valves ensure that vent lines will be emptied back to the tank if what happens?", options: ["Pressure drops", "Fuel should ever be present in them", "Temperature rises"], correctOptionIndex: 1 },
  { id: 251, text: "In each vent surge tank, pressure relief valves and disks are installed to protect against what?", options: ["Overheating", "Excessive pressure difference", "Corrosion"], correctOptionIndex: 1 },
  { id: 252, text: "Where burst disks are used to relieve overboard, the disk is usually marked with what for better viewing?", options: ["A dot", "A cross", "A circle"], correctOptionIndex: 1 },
  { id: 253, text: "The tank drain valve can be found where?", options: ["On top of each wing", "On the underside of each wing or tank", "In the cockpit"], correctOptionIndex: 1 },
  { id: 254, text: "Since water has higher density than fuel, it will accumulate where?", options: ["At the top of the tank", "At the lowest point of the tank", "Evenly throughout"], correctOptionIndex: 1 },
  { id: 255, text: "Where drain valves are not placed on the lowest point, what type of drain valves are used?", options: ["Direct", "Indirect", "Gravity"], correctOptionIndex: 1 },
  { id: 256, text: "Drain valves are usually equipped with what to allow removal without emptying the tank if leaking?", options: ["Isolation valve", "Non-return valve", "Shut-off valve"], correctOptionIndex: 1 },
  { id: 257, text: "The fuel jettison system is also known as what?", options: ["Transfer system", "Dump system", "Vent system"], correctOptionIndex: 1 },
  { id: 258, text: "Dumping fuel is only done in case of what?", options: ["Normal operations", "Serious malfunctions or medical reasons requiring speedy landing", "Fuel imbalance"], correctOptionIndex: 1 },
  { id: 259, text: "Aircraft whose landing weights are close to the maximum take-off weight do not have what?", options: ["Vent system", "A fuel jettison system", "Transfer system"], correctOptionIndex: 1 },
  { id: 260, text: "The jettison system ensures that a predetermined quantity of fuel remains by using what?", options: ["Low level sensors", "A stand pipe", "Float switches"], correctOptionIndex: 1 },
  { id: 261, text: "One type of jettison system makes use of what gallery pipe extended to near each wing tip?", options: ["Feed", "Refuelling", "Vent"], correctOptionIndex: 2 },
  { id: 262, text: "For economy reasons, modern aircraft are equipped with what type of jettison systems?", options: ["Manual", "Automatic", "Semi-automatic"], correctOptionIndex: 2 },
  { id: 263, text: "The jettison gross weight is usually entered using either a rotating knob or what?", options: ["Push button", "MCDU interface", "Lever"], correctOptionIndex: 1 },
  { id: 264, text: "The fuel tank inerting system replaces the flammable gas space with what?", options: ["Oxygen", "Non-flammable atmosphere", "Hydrogen"], correctOptionIndex: 1 },
  { id: 265, text: "Fuel tank inerting systems displace oxygen in the tank with what?", options: ["Carbon dioxide", "Nitrogen", "Argon"], correctOptionIndex: 1 },
  { id: 266, text: "OBIGGS stands for what?", options: ["On-board inert gas generating system", "On-board inert gas generating system", "Oxygen bleeding inert gas system"], correctOptionIndex: 0 },
  { id: 267, text: "OBIGGS produces a flow of what to protect the aircraft?", options: ["Oxygen enriched air", "Nitrogen enriched air (NEA)", "Carbon dioxide"], correctOptionIndex: 1 },
  { id: 268, text: "OBIGGS includes a filtration system, pressure and temperature controller, oxygen sensor, and what?", options: ["Pumps", "Air separation modules", "Valves"], correctOptionIndex: 1 },
  { id: 269, text: "Compressed air is tapped from where and transformed into NEA?", options: ["Engines", "Aircraft pneumatic system", "APU"], correctOptionIndex: 1 },
  { id: 270, text: "In the Airbus A350 inert gas distribution system, what prevents fuel reverse flow from fuel tanks to IGDS?", options: ["Pumps", "Non-return valves", "Shut-off valves"], correctOptionIndex: 1 },
  { id: 271, text: "The inert gas system operates only in what condition?", options: ["On ground", "In flight", "During refuelling"], correctOptionIndex: 1 },
  { id: 272, text: "Temperature isolation valves (TIV) control what?", options: ["NEA flow to tanks", "Conditioned air supply to air separation modules", "Fuel flow"], correctOptionIndex: 1 },
  { id: 273, text: "Dual flow shut off valves (DFSOV) control what?", options: ["Conditioned air supply", "NEA flow to fuel tanks", "Fuel flow"], correctOptionIndex: 1 },
  { id: 274, text: "The centre of gravity (CG) is the point where what is considered to be located?", options: ["The fuel", "All the weight of the aircraft", "The engines"], correctOptionIndex: 1 },
  { id: 275, text: "To operate an aircraft economically, the CG should be held in a range where the horizontal stabiliser is how?", options: ["Deflected", "As streamlined as possible", "At maximum trim"], correctOptionIndex: 1 },
  { id: 276, text: "This means that the stabiliser trim settings should be close to what in cruise?", options: ["Maximum", "Zero", "Minimum"], correctOptionIndex: 1 },
  { id: 277, text: "The aircraft's CG is determined by the manufacturer upon delivery and is used as what?", options: ["The final CG", "The base for the loading sheets", "The in-flight CG"], correctOptionIndex: 1 },
  { id: 278, text: "Parameters that change the centre of gravity include passenger loading, cargo loading, and what?", options: ["Weather", "Refuelling", "Altitude"], correctOptionIndex: 1 },
  { id: 279, text: "The resulting centre of gravity from these parameters is called what?", options: ["Take-off CG", "Zero-fuel weight centre of gravity (ZFW-CG)", "Landing CG"], correctOptionIndex: 1 },
  { id: 280, text: "The centre of gravity location is referred to as a percentage of what?", options: ["Total length", "Mean aerodynamic chord (MAC)", "Wingspan"], correctOptionIndex: 1 },
  { id: 281, text: "Fuel control and monitoring computers control CG position by fuel transfer from and to what?", options: ["Main tanks only", "The trim tank", "Centre tank"], correctOptionIndex: 1 },
  { id: 282, text: "CG control depends on zero fuel weight, ZFW-CG, fuel quantity in each tank, and what?", options: ["Altitude", "Fuel flow signals", "Airspeed"], correctOptionIndex: 1 },
  { id: 283, text: "The actual CG position and gross weight are displayed where?", options: ["On the engine", "In the cockpit", "On the refuel panel"], correctOptionIndex: 1 },
  { id: 284, text: "CG is indicated in what units?", options: ["Inches", "% MAC", "Feet"], correctOptionIndex: 1 },
  { id: 285, text: "Gross weight is indicated in what units?", options: ["Pounds only", "Tons", "Kilograms only"], correctOptionIndex: 0 },
  { id: 286, text: "CG control is started after what phase?", options: ["Before take-off", "After take-off", "During landing"], correctOptionIndex: 1 },
  { id: 287, text: "The computer activates corresponding valves and pumps to transfer fuel to maintain CG within a tolerance of MAC of what?", options: ["Current CG", "The target CG", "Zero CG"], correctOptionIndex: 1 },
  { id: 288, text: "In case of a CG control system failure, the computer switches to alternate mode or fault mode which consists of what?", options: ["Stopping all transfer", "Emptying the trim tank", "Using manual control"], correctOptionIndex: 1 },
];
