export const fundamentalsGasTurbineEnginesQuestions = [
  {
    id: 1,
    text: "Who are recognised as the co-inventors of the jet engine?",
    options: ["Ernst Heinkel and Herbert Wagner", "Sir Frank Whittle and Dr Hans-Joachim Pabst von Ohain", "Wernher von Braun and Leonardo da Vinci"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "Who was the first to design and develop a turbojet engine to power an aircraft?",
    options: ["Sir Frank Whittle", "Hans von Ohain", "Herbert Wagner"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "In what year did the Heinkel He-178 make the first successful flight of a jet-powered aircraft?",
    options: ["1937", "1939", "1941"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "Sir Frank Whittle patented his design for a gas-turbine engine for jet propulsion in England in which year?",
    options: ["1930", "1932", "1937"],
    correctOptionIndex: 0,
  },
  {
    id: 5,
    text: "Which engine powered the first flight of the Gloster E28/39 test aircraft in May 1941?",
    options: ["He S-1", "W.1 turbojet", "Jumo 004"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "Who is credited as the \"father of the turboprop engine\" and patented it in 1935?",
    options: ["Anselm Franz", "Dr Herbert Wagner", "Ernst Heinkel"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "The Jumo 004 axial gas-turbine engine, developed by Anselm Franz, powered which aircraft?",
    options: ["Heinkel He-178", "Gloster E28/39", "Messerschmitt ME-262"],
    correctOptionIndex: 2,
  },
  {
    id: 8,
    text: "What was the thrust produced by the He S-1 turbojet engine tested at the end of February 1937?",
    options: ["250 pounds at 10,000 rpm", "500 pounds at 15,000 rpm", "100 pounds at 8,000 rpm"],
    correctOptionIndex: 0,
  },
  {
    id: 9,
    text: "Who designed the V2, the first long-range ballistic missile?",
    options: ["Hans von Ohain", "Wernher von Braun", "Frank Whittle"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "Heron's aeropile, an early reaction device, used which principle?",
    options: ["Compressed air from a fan", "Expelling steam from boiling water", "Burning gunpowder"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "Which type of jet engine is a non-air-breathing engine?",
    options: ["Ramjet", "Rocket engine", "Pulsejet"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "The ramjet is also known as:",
    options: ["Athodyd (aero-thermodynamic duct)", "Stovepipe cycle", "Scramjet"],
    correctOptionIndex: 0,
  },
  {
    id: 13,
    text: "Ramjets work most efficiently at speeds around:",
    options: ["Mach 1", "Mach 3", "Mach 7"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "What is a key characteristic of a pulsejet that distinguishes it from a ramjet?",
    options: ["Continuous combustion", "Spring-loaded valves in the air intake", "No moving parts"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "During WWII, pulsejets were used to power which weapon?",
    options: ["V2 rocket", "German V1 flying bombs", "Messerschmitt ME-262"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "What is the nickname given to pulsejets during WWII due to their distinctive noise?",
    options: ["Buzz bombs", "Doodlebugs", "Flying bombs"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "A scramjet differs from a ramjet primarily because:",
    options: ["It has no moving parts", "Combustion occurs at supersonic speeds", "It uses a centrifugal compressor"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "What fuel is usually used in scramjets due to high air intake temperatures?",
    options: ["Kerosene", "Hydrogen", "Methane"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "The minimum functional speed required for a scramjet to operate is approximately:",
    options: ["Mach 3 to 4", "Mach 7 to 8", "Mach 1 to 2"],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "Ramjets have been used successfully, though not efficiently, as:",
    options: ["APU starters", "Tip jets on helicopter rotors", "Afterburners on fighters"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "The rocket engine carries its own oxidiser, which allows it to:",
    options: ["Operate outside the earth's atmosphere", "Be more fuel-efficient than a turbofan", "Have no moving parts"],
    correctOptionIndex: 0,
  },
  {
    id: 22,
    text: "The V2 rocket was capable of what speed?",
    options: ["2,500 kmph", "5,760 kmph", "10,000 kmph"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "A pulsejet engine has the potential to operate from standstill up to:",
    options: ["Subsonic speeds only", "Supersonic speeds", "Hypersonic speeds only"],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "In a ramjet, the combustion process is:",
    options: ["Intermittent", "Continuous", "Isothermal"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "Scramjet stands for:",
    options: ["Supersonic combustion ramjet", "Subsonic combustion ramjet", "Supercharged ramjet"],
    correctOptionIndex: 0,
  },
  {
    id: 26,
    text: "Which section of a gas-turbine engine is called the \"gas generator\"?",
    options: ["Compressor, combustion chamber, and turbine combined", "Air inlet and exhaust nozzle only", "Fan and bypass duct"],
    correctOptionIndex: 0,
  },
  {
    id: 27,
    text: "In a turbojet engine, the converging exhaust nozzle converts heat and pressure into:",
    options: ["Mechanical work", "Velocity", "Pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "What is the typical residual jet thrust of a turboprop engine compared to a similar-sized turbojet?",
    options: ["30–40%", "50–60%", "10–15%"],
    correctOptionIndex: 2,
  },
  {
    id: 29,
    text: "In a turbofan engine, the bypass airflow is also referred to as:",
    options: ["Primary airflow", "Secondary airflow", "Core airflow"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "In modern commercial high-bypass turbofans, the fan typically delivers what percentage of total thrust?",
    options: ["50% to 60%", "75% to 85%", "90% to 99%"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "A turboshaft engine is similar to a turboprop but is typically used to drive:",
    options: ["A propeller", "Anything other than a propeller (e.g., helicopter rotor, APU)", "A fan only"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "What component is used to lower the output shaft speed in a turboprop engine?",
    options: ["Free power turbine", "Reduction gearbox", "Diffuser"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "A turbojet engine that allows all air to flow through the compressor and hot section is often called a:",
    options: ["Bypass engine", "Straight jet", "Free turbine engine"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "In a turbofan, if the fan and core have separate nozzles, the engine is said to be:",
    options: ["Mixed", "Unmixed", "Long ducted"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "Military turbofans generally have:",
    options: ["High bypass ratios", "Low bypass ratios", "No afterburner"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "The flame temperature in the combustion chamber of a gas turbine can reach up to:",
    options: ["1,500 K", "2,300 K", "3,500 K"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "In a turboprop with a free power turbine, the power turbine:",
    options: ["Is rigidly connected to the compressor", "Turns independently of the gas generator turbine", "Drives the compressor directly"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "Afterburning (reheating) increases exhaust velocity but has a significant negative impact on:",
    options: ["Thrust", "Fuel efficiency", "Turbine temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "The Pratt & Whitney PT-6 turboprop engine features which type of turbine arrangement?",
    options: ["Single spool", "Free power turbine", "Coupled type"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "In a turbofan, the bypass ratio (BPR) refers to the portion of:",
    options: ["Mass flow bypassing the core engine", "Fuel bypassing the combustor", "Air used for cooling the turbine"],
    correctOptionIndex: 0,
  },
  {
    id: 41,
    text: "What is the purpose of a diffuser duct between the compressor and combustion section?",
    options: ["Increase velocity", "Convert kinetic energy to potential energy (pressure)", "Mix fuel and air"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "Turboshaft engines are commonly used in:",
    options: ["Supersonic fighters", "Helicopters and APUs", "High-bypass commercial jets"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "The Allied Signal APU described in the document has a load section that provides:",
    options: ["Only hydraulic power", "115 VAC / 400 Hz electrical power", "Only bleed air"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "On most commercial turbofans, the thrust reverser acts primarily on:",
    options: ["The core airflow only", "The fan (cold) airflow", "The turbine section"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "The turbojet has been largely outdated by the turbofan for most applications because the turbofan is:",
    options: ["Simpler to manufacture", "More fuel-efficient", "Capable of higher supersonic speeds"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "A turboprop engine extracts maximum heat energy from the exhaust gas to:",
    options: ["Produce pure jet thrust", "Drive the propeller", "Cool the turbine blades"],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "In a turbofan engine, the fan may be driven by:",
    options: ["The high-pressure compressor only", "The low-pressure compressor or a separate turbine section", "An electric motor"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "The exhaust section of a turbojet is called a nozzle (or jet pipe) when:",
    options: ["The exhaust gas is used for propulsive force", "It only expels hot gases without producing thrust", "It has an afterburner"],
    correctOptionIndex: 0,
  },
  {
    id: 49,
    text: "Concorde used turbojet engines because they are better suited for:",
    options: ["Low-speed cruise", "High flight speeds (e.g., M2.0)", "Short takeoff and landing"],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "A twin-spool engine has:",
    options: ["Two separate shafts connecting separate turbine and compressor sections", "Two combustion chambers", "Two separate exhaust nozzles"],
    correctOptionIndex: 0,
  },
  {
    id: 51,
    text: "Newton's first law is also called the law of:",
    options: ["Acceleration", "Inertia", "Action and reaction"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "A passenger being thrown forward when an aircraft suddenly stops is an example of:",
    options: ["Newton's second law", "Newton's first law", "Newton's third law"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "Newton's second law is expressed mathematically as:",
    options: ["F = m × a", "F = m / a", "F = m + a"],
    correctOptionIndex: 0,
  },
  {
    id: 54,
    text: "According to Newton's second law, if the net force on an object is zero, the acceleration is:",
    options: ["Zero", "Constant positive", "Variable"],
    correctOptionIndex: 0,
  },
  {
    id: 55,
    text: "Newton's third law states that:",
    options: ["Force equals mass times acceleration", "Every action has an equal and opposite reaction", "A body at rest stays at rest"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "The thrust formula derived from Newton's second and third laws for a propeller is:",
    options: ["T = m × (u - v)/t", "T = m × (u + v)/t", "T = m × v × t"],
    correctOptionIndex: 0,
  },
  {
    id: 57,
    text: "In a turbojet, the term \"ram drag\" refers to:",
    options: ["The gross thrust from the exhaust", "The reduction in thrust due to incoming air velocity", "The friction in the compressor"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "A propeller produces thrust by:",
    options: ["Accelerating a small mass of air with high acceleration", "Accelerating a large mass of air with relatively small acceleration", "Burning fuel in a confined space"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "During a static engine test (initial velocity = 0), the thrust is equal to:",
    options: ["Ram drag only", "Gross thrust", "Zero"],
    correctOptionIndex: 1,
  },
  {
    id: 60,
    text: "If a jet engine has a mass airflow of 23 kg/sec and exhaust velocity of 580 m/sec (static test), the thrust is:",
    options: ["13,340 N", "23,000 N", "580 N"],
    correctOptionIndex: 0,
  },
  {
    id: 61,
    text: "The net forward force on an aircraft accelerating down the runway equals:",
    options: ["Thrust + Drag", "Thrust – Drag", "Mass × Drag"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "A horse can move a wagon forward because the ground exerts a forward reaction force on its hooves that is:",
    options: ["Less than the wagon's backward pull", "Equal to the wagon's backward pull", "Greater than the wagon's backward pull"],
    correctOptionIndex: 2,
  },
  {
    id: 63,
    text: "In canoeing, the paddle pushes water backwards, and the water reacts by pushing the paddle forwards. This illustrates:",
    options: ["Newton's first law", "Newton's second law", "Newton's third law"],
    correctOptionIndex: 2,
  },
  {
    id: 64,
    text: "A jet engine produces thrust by imparting:",
    options: ["A small change in velocity to a large air mass", "A significant change in velocity to a relatively small air mass", "No change in velocity to the air mass"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "In the thrust formula T = (m/t)v – (m/t)u, the term (m/t)v is called:",
    options: ["Ram drag", "Gross thrust", "Net thrust"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "Entropy in any closed system always:",
    options: ["Decreases", "Increases", "Remains constant"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "The Zeroth law of thermodynamics establishes:",
    options: ["The conservation of energy", "Temperature as a fundamental and measurable property", "That entropy never decreases"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "The first law of thermodynamics is a statement of:",
    options: ["The conservation of energy", "The increase of entropy", "The impossibility of absolute zero"],
    correctOptionIndex: 0,
  },
  {
    id: 69,
    text: "The second law of thermodynamics explains why:",
    options: ["Heat energy cannot be transferred from a colder to a hotter body without added energy", "A perpetual motion machine is possible", "Entropy always decreases"],
    correctOptionIndex: 0,
  },
  {
    id: 70,
    text: "An isentropic process is one in which:",
    options: ["Temperature remains constant", "Entropy remains constant", "Pressure remains constant"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "An adiabatic process is defined as:",
    options: ["Constant temperature", "No heat transfer into or out of the system", "Constant volume"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "The compression stroke in an internal combustion engine is nearly:",
    options: ["Isothermal", "Adiabatic", "Isobaric"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "An isochoric process is a:",
    options: ["Constant pressure process", "Constant volume process", "Constant temperature process"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "Enthalpy (H) is defined as:",
    options: ["Internal energy minus pressure-volume product", "Internal energy plus pressure-volume product", "Temperature plus entropy"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "For an ideal gas undergoing an isothermal process, the change in internal energy is:",
    options: ["Zero", "Positive", "Negative"],
    correctOptionIndex: 0,
  },
  {
    id: 76,
    text: "The third law of thermodynamics states that at absolute zero, the entropy of a pure crystal is:",
    options: ["Zero", "Maximum", "Infinite"],
    correctOptionIndex: 0,
  },
  {
    id: 77,
    text: "A reversible process is one that:",
    options: ["Occurs quickly with entropy production", "Is always at equilibrium and represents maximum efficiency", "Cannot be performed in a finite time"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "Thermal energy, as a concept, is not well-defined in thermodynamics because:",
    options: ["Internal energy can change without changing temperature", "Heat is not a form of energy", "Temperature cannot be measured"],
    correctOptionIndex: 0,
  },
  {
    id: 79,
    text: "In an isobaric process, which quantity remains constant?",
    options: ["Volume", "Pressure", "Temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "The first law of thermodynamics can be written as:",
    options: ["ΔU = Q – W", "ΔU = Q + W", "ΔU = W – Q"],
    correctOptionIndex: 0,
  },
  {
    id: 81,
    text: "Avogadro's law states that equal volumes of all gases at the same temperature and pressure have the same number of:",
    options: ["Atoms", "Molecules", "Electrons"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "Boyle's law states that at constant temperature, volume is:",
    options: ["Directly proportional to pressure", "Inversely proportional to pressure", "Independent of pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "Boyle's law is an example of which thermodynamic process?",
    options: ["Isobaric", "Isothermal", "Adiabatic"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "Charles' law states that at constant pressure, volume is:",
    options: ["Directly proportional to temperature", "Inversely proportional to temperature", "Proportional to pressure"],
    correctOptionIndex: 0,
  },
  {
    id: 85,
    text: "Charles' law is an example of which process?",
    options: ["Isochoric", "Isothermal", "Isobaric"],
    correctOptionIndex: 2,
  },
  {
    id: 86,
    text: "Gay-Lussac's law states that at constant volume, pressure is:",
    options: ["Inversely proportional to temperature", "Proportional to temperature", "Constant"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "The combined gas law is expressed as:",
    options: ["P₁V₁/T₁ = P₂V₂/T₂", "P₁V₁T₁ = P₂V₂T₂", "P₁/T₁ = P₂/T₂"],
    correctOptionIndex: 0,
  },
  {
    id: 88,
    text: "In gas law calculations, temperature must always be in:",
    options: ["Celsius", "Fahrenheit", "Kelvin (absolute)"],
    correctOptionIndex: 2,
  },
  {
    id: 89,
    text: "Dalton's law states that the total pressure of a gas mixture is equal to:",
    options: ["The product of partial pressures", "The sum of the partial pressures", "The difference between partial pressures"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "If a gas is compressed under adiabatic conditions, its temperature:",
    options: ["Rises", "Falls", "Remains constant"],
    correctOptionIndex: 0,
  },
  {
    id: 91,
    text: "In an adiabatic expansion, the gas does work on its surroundings, and its temperature:",
    options: ["Rises", "Falls", "Remains constant"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "Boyle's law is difficult to achieve in practice because compressing a gas naturally causes its temperature to:",
    options: ["Decrease", "Increase", "Stay the same"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "A quasi-static process is one that is performed:",
    options: ["Very quickly", "Infinitely slowly", "At constant volume"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "According to Charles' law, if the temperature of a gas is doubled (in Kelvin) at constant pressure, the volume will:",
    options: ["Halve", "Double", "Remain the same"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "An air compressor that compresses air so quickly that no heat escapes comes close to an:",
    options: ["Isothermal process", "Adiabatic process", "Isochoric process"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "Potential energy (Epot) is defined as:",
    options: ["½ mv²", "mgh", "F × d"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "Kinetic energy (Ekin) is defined as:",
    options: ["mgh", "½ mv²", "F × t"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "The SI unit for energy and work is the:",
    options: ["Watt", "Newton", "Joule"],
    correctOptionIndex: 2,
  },
  {
    id: 99,
    text: "Power is defined as:",
    options: ["Force × distance", "Work / Time", "Mass × acceleration"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "One metric horsepower is equivalent to:",
    options: ["550 ft.lbs/sec", "736 watts", "1,000 watts"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "Thrust for a static jet engine (not moving) can be calculated as:",
    options: ["F = ṁ × (VE – VI)", "F = ṁ × VE (since VI = 0)", "F = ½ ṁ × VE²"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "In a jet engine, the formula for thrust including pressure and velocity is:",
    options: ["F = (A × P) + (ṁ × VE)", "F = (A × V) + (ṁ × P)", "F = ṁ × (VE – VI)"],
    correctOptionIndex: 0,
  },
  {
    id: 103,
    text: "Why are the terms \"power\" and \"horsepower\" inappropriate for a static turbojet?",
    options: ["Because no movement (distance/time) occurs, so no power is developed", "Because jet engines cannot produce power", "Because thrust cannot be measured"],
    correctOptionIndex: 0,
  },
  {
    id: 104,
    text: "The law of conservation of energy states that energy:",
    options: ["Can be created but not destroyed", "Can neither be created nor destroyed", "Is always lost as heat"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Work done is calculated as:",
    options: ["Force × Distance", "Force / Distance", "Mass × Acceleration"],
    correctOptionIndex: 0,
  },
  {
    id: 106,
    text: "If a jet engine accelerates 50 kg/sec of air from 0 to 540 m/sec, the kinetic energy added per second is:",
    options: ["0.81 MJ", "7.29 MJ", "27,000 J"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "For the same amount of thrust, a propeller is more efficient than a turbojet because:",
    options: ["It gives a small acceleration to a large air mass, wasting less energy", "It gives a high acceleration to a small air mass", "It has no moving parts"],
    correctOptionIndex: 0,
  },
  {
    id: 108,
    text: "Engine Pressure Ratio (EPR) is an indication of thrust based on:",
    options: ["RPM only", "Differential pressure across the engine (inlet vs outlet)", "Exhaust gas temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "In a turbofan, RPM for the low-pressure spool is indicated as:",
    options: ["N2", "N1", "EPR"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "The formula F = ṁ × (VE – VI) is derived directly from:",
    options: ["Newton's first law", "Newton's second law", "The first law of thermodynamics"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "For subsonic airflow, a convergent duct will:",
    options: ["Increase velocity and decrease pressure", "Decrease velocity and increase pressure", "Keep velocity constant"],
    correctOptionIndex: 0,
  },
  {
    id: 112,
    text: "For subsonic airflow, a divergent duct will:",
    options: ["Increase velocity and decrease pressure", "Decrease velocity and increase pressure", "Keep pressure constant"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "A nozzle is said to be \"choked\" when the gas reaches:",
    options: ["Subsonic speed", "Sonic speed (speed of sound)", "Hypersonic speed"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "To accelerate a gas to supersonic speed, a convergent-divergent duct is used. The convergent section accelerates the gas to:",
    options: ["Subsonic speed", "Sonic speed", "Supersonic speed"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "Choked convergent-divergent nozzles are commonly used on:",
    options: ["Turboprop engines", "Supersonic military aircraft and rockets", "High-bypass turbofans"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "The Otto cycle is also known as a:",
    options: ["Constant pressure cycle", "Constant volume cycle", "Constant temperature cycle"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "The Otto cycle is used in:",
    options: ["Gas turbine engines", "Four-stroke petrol engines", "Diesel engines"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "The Brayton cycle is also known as the:",
    options: ["Constant volume cycle", "Gas-turbine cycle", "Diesel cycle"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "In a gas-turbine engine, combustion occurs at approximately:",
    options: ["Constant volume", "Constant pressure", "Constant temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "In a piston engine, combustion occurs at approximately:",
    options: ["Constant pressure", "Constant volume", "Constant entropy"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "The Brayton cycle consists of which processes?",
    options: ["Induction, compression, combustion, exhaust", "Compression, heat addition at constant pressure, expansion, heat rejection", "Compression, heat addition at constant volume, expansion"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "Aviation gas-turbine engines operate on an:",
    options: ["Closed Brayton cycle", "Open Brayton cycle", "Otto cycle"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "In the Brayton cycle, the compressor uses work (WIN) and the turbine extracts work (WOUT). The residual energy is:",
    options: ["Lost as heat", "Available as useful work (thrust or shaft power)", "Used to restart the engine"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "Peak pressures in a piston engine can exceed 1,000 lb/in², whereas in a gas turbine, combustion occurs at constant pressure, allowing:",
    options: ["Heavier construction", "Light fabricated combustion chambers", "Higher octane fuel"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "On a PV diagram for a heat engine, the total work of the cycle is proportional to:",
    options: ["The maximum pressure", "The total area of the diagram", "The maximum volume"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "A pure turbojet engine has:",
    options: ["A fan and bypass duct", "Only one gas path (core)", "A free power turbine"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "A twin-spool axial flow front fan engine with high bypass ratio is a type of:",
    options: ["Turbojet", "Turbofan", "Turboprop"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "A twin-spool turboshaft engine with free power turbine is typically used to drive:",
    options: ["A propeller", "A helicopter rotor or industrial load", "A fan only"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "The HF120 fan engine features a single-stage, high-pressure ratio:",
    options: ["Steel impeller", "Titanium impeller", "Aluminum impeller"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "In a low-bypass afterburning turbofan, the afterburner is located:",
    options: ["Between the fan and the compressor", "Between the mixing point and the nozzle", "Before the combustion chamber"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "According to the certification statement, which EASA regulation's Annex III (Part-66) Appendix I do these study notes comply with?",
    options: ["(EU) No. 2018/1142", "(EU) No. 1321/2014", "(EU) No. 748/2012"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "What is the Part-66 reference for the Inlet topic in Module 15.3?",
    options: ["15.2", "15.3", "15.4"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "Which part of the engine is generally considered engine station number one?",
    options: ["The compressor", "The intake", "The combustion chamber"],
    correctOptionIndex: 1,
  },
  {
    id: 134,
    text: "What must the turbine engine inlet provide to the compressor for stall-free performance?",
    options: ["A constant supply of fuel", "A constant supply of air", "A constant supply of oil"],
    correctOptionIndex: 1,
  },
  {
    id: 135,
    text: "How must the inlet duct be maintained to deliver air with minimum turbulence?",
    options: ["As close to new condition as possible", "With a rough internal surface", "With a larger diameter than the compressor"],
    correctOptionIndex: 0,
  },
  {
    id: 136,
    text: "What is recommended to promote cleanliness and prevent corrosion and abrasion of the inlet?",
    options: ["An inlet cover", "A constant wash with soapy water", "A layer of grease on the lip"],
    correctOptionIndex: 0,
  },
  {
    id: 137,
    text: "What shape do the inlet ducts on business and commercial jet aircraft have?",
    options: ["Convergent", "Divergent", "Parallel"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "The divergent shape of a subsonic inlet is sometimes called what?",
    options: ["The bell-mouth type", "The pitot type", "The S-duct type"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "What effect does the diverging duct (inlet diffuser) have on the incoming air?",
    options: ["It decreases static pressure", "It increases static pressure", "It maintains ambient pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "What happens to inlet pressure as the aircraft reaches its desired cruising speed?",
    options: ["It decreases significantly", "It increases significantly", "It remains constant"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "When can crosswind cause the airflow through S-shaped intakes to become unstable?",
    options: ["During high-speed cruise", "During crosswind take-off", "During landing rollout"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "According to the text, a typical duct inefficiency of 1% causes what percentage of thrust loss?",
    options: ["0.5%", "1.0%", "1.5%"],
    correctOptionIndex: 2,
  },
  {
    id: 143,
    text: "What is the typical efficiency range for a Pitot type inlet?",
    options: ["80-89%", "87-95%", "96-99%"],
    correctOptionIndex: 2,
  },
  {
    id: 144,
    text: "What is the typical efficiency range for a Side inlet?",
    options: ["80-89%", "87-95%", "96-99%"],
    correctOptionIndex: 0,
  },
  {
    id: 145,
    text: "What is the typical efficiency range for a Turboprop annular inlet?",
    options: ["74-82%", "80-89%", "87-95%"],
    correctOptionIndex: 0,
  },
  {
    id: 146,
    text: "What device uses a set of compressor bleed air directed through a nozzle to break up the ground vortex?",
    options: ["A vortex generator", "A vortex dissipater (blow away jet)", "A boundary layer bleeder"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "The vortex dissipater is controlled by a valve linked to which switch?",
    options: ["The landing gear position switch", "The weight-on-wheels switch", "The throttle position switch"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "On the windward side of the inlet during a crosswind, what can happen if the crosswind is strong enough?",
    options: ["The airflow stops completely", "The airflow exceeds the speed of sound locally", "The airflow reverses direction"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "What is the suction effect acting in the direction of engine thrust, caused by pressure drop at the inlet lip, called?",
    options: ["Ram drag", "Nose suction", "Boundary layer suction"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "What are secondary inlet doors, which open inwards at high thrust and low forward speed, called?",
    options: ["Blow-in doors", "Blow-out doors", "Spill doors"],
    correctOptionIndex: 0,
  },
  {
    id: 151,
    text: "How do blow-in doors close as forward speed increases?",
    options: ["By an electric motor", "By a spring", "By hydraulic pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 152,
    text: "What is the formula for Net thrust?",
    options: ["Net thrust = Gross thrust + Intake momentum drag", "Net thrust = Gross thrust - Intake momentum drag", "Net thrust = Intake momentum drag - Gross thrust"],
    correctOptionIndex: 1,
  },
  {
    id: 153,
    text: "At approximately what speed does the ram effect (ram recovery) start to produce greater engine power for engines with pitot intakes?",
    options: ["100-150 knots", "200-250 knots", "300-350 knots"],
    correctOptionIndex: 2,
  },
  {
    id: 154,
    text: "What principle is used by acoustic liners for the dissipation of incident acoustic energy?",
    options: ["The Doppler effect", "The Helmholtz resonance principle", "The Bernoulli principle"],
    correctOptionIndex: 1,
  },
  {
    id: 155,
    text: "An acoustic liner is a sandwich panel made of a porous face sheet, a honeycomb structure, and an impervious layer called what?",
    options: ["Base-skin", "Back-sheet or back-skin", "Core-sheet"],
    correctOptionIndex: 1,
  },
  {
    id: 156,
    text: "What is the name for an acoustic liner made with two layers of honeycomb cells divided by a porous septum?",
    options: ["Single degree of freedom (SDOF) liner", "Double degree of freedom (DDOF) liner", "Zero-splice liner"],
    correctOptionIndex: 1,
  },
  {
    id: 157,
    text: "What is the name for a modern acoustic panel that is made without structural joins that cause partial loss of the acoustic area?",
    options: ["Zero-splice liner", "Single-splice liner", "Double-splice liner"],
    correctOptionIndex: 0,
  },
  {
    id: 158,
    text: "Where are bell-mouth air inlets primarily used?",
    options: ["On supersonic fighter jets", "On engine test cells and some low-speed aircraft like helicopters", "On all commercial airliners"],
    correctOptionIndex: 1,
  },
  {
    id: 159,
    text: "What is the main disadvantage of a bell-mouth inlet for aeroplanes in forward flight?",
    options: ["It creates too much drag", "It is too heavy", "It causes compressor stall"],
    correctOptionIndex: 0,
  },
  {
    id: 160,
    text: "Duct loss in a bell-mouth inlet design is considered to be what?",
    options: ["Very high", "Moderate", "Zero"],
    correctOptionIndex: 2,
  },
  {
    id: 161,
    text: "On what types of aircraft are compressor inlet screens usually limited to?",
    options: ["Large turbofan aircraft", "Rotorcraft and turboprop engines", "Supersonic aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 162,
    text: "Why are inlet screens not generally used on large turbofan engines?",
    options: ["They are too expensive", "The disadvantages (e.g., failure) outweigh the advantages", "They are illegal"],
    correctOptionIndex: 1,
  },
  {
    id: 163,
    text: "What makes turboprop air inlets sometimes quite complex?",
    options: ["The need for afterburners", "The propeller gearbox disturbs the inlet air", "Their extremely high speed"],
    correctOptionIndex: 1,
  },
  {
    id: 164,
    text: "Which type of turboprop inlet is described as the most efficient but complex to maintain and anti-ice?",
    options: ["Conical spinner inlet", "Under scoop inlet", "Ducted spinner inlet"],
    correctOptionIndex: 2,
  },
  {
    id: 165,
    text: "On what type of aircraft are inlet filters (particle separators) most commonly fitted due to low altitude operation?",
    options: ["Long-range airliners", "Business jets", "Helicopters"],
    correctOptionIndex: 2,
  },
  {
    id: 166,
    text: "Inlet filters and traps that force air around sharp bends use what principle to remove contaminants?",
    options: ["Contaminants are heavier than air and are centrifuged out", "Contaminants are lighter than air and float away", "Contaminants are electrically attracted to the filter"],
    correctOptionIndex: 0,
  },
  {
    id: 167,
    text: "What does EAPS stand for in the context of vortex tubes?",
    options: ["Engine Air Particle Separator", "Emergency Air Pressure System", "Engine Anti-ice Protection System"],
    correctOptionIndex: 0,
  },
  {
    id: 168,
    text: "What type of APU air intake uses a flap and actuator and is described as having a curved shape like a wing flap?",
    options: ["The scoop-type inlet", "The NACA intake", "The bell-mouth intake"],
    correctOptionIndex: 1,
  },
  {
    id: 169,
    text: "When an aircraft travels at the same speed as sound (M = 1), all sound waves are compressed into a strong wavefront called what?",
    options: ["The Mach cone", "The Doppler effect", "A normal shockwave"],
    correctOptionIndex: 2,
  },
  {
    id: 170,
    text: "What is the conical surface that travels with an aircraft flying at supersonic speed, enveloping all the wavefronts, called?",
    options: ["The Doppler cone", "The Mach cone", "The shock cone"],
    correctOptionIndex: 1,
  },
  {
    id: 171,
    text: "For a normal shockwave, what happens to the airflow downstream of the shock front?",
    options: ["It becomes supersonic", "It is always subsonic", "It stops completely"],
    correctOptionIndex: 1,
  },
  {
    id: 172,
    text: "How is a normal shockwave orientated relative to the flow direction?",
    options: ["Parallel", "Perpendicular", "At a 45-degree angle"],
    correctOptionIndex: 1,
  },
  {
    id: 173,
    text: "What is the name of a shockwave that is inclined at some angle to the free stream direction?",
    options: ["A normal shockwave", "An oblique shockwave", "A Mach shockwave"],
    correctOptionIndex: 1,
  },
  {
    id: 174,
    text: "At what speed must the airflow onto the compressor face be, regardless of the aircraft speed, to keep rotating airfoils free of shock wave accumulation?",
    options: ["Supersonic (Mach > 1.0)", "Sonic (Mach 1.0)", "Subsonic (normally Mach 0.4)"],
    correctOptionIndex: 2,
  },
  {
    id: 175,
    text: "What type of intake is most effective at supersonic speeds but inefficient at subsonic speeds?",
    options: ["Pitot intake", "Bell-mouth intake", "Convergent-divergent intake"],
    correctOptionIndex: 2,
  },
  {
    id: 176,
    text: "On the Concorde, what percentage of thrust was derived from the intakes at supersonic cruise speed (Mach 2.0)?",
    options: ["21%", "63%", "82%"],
    correctOptionIndex: 1,
  },
  {
    id: 177,
    text: "What is the name for the condition where the normal shockwave in a supersonic intake is expelled forward and oscillates at high frequency, causing severe damage?",
    options: ["Intake surge", "Intake or diffuser buzz", "Compressor stall"],
    correctOptionIndex: 1,
  },
  {
    id: 178,
    text: "According to the text, icing conditions exist below what temperature with visible moisture?",
    options: ["0°C", "+5°C", "+10°C"],
    correctOptionIndex: 2,
  },
  {
    id: 179,
    text: "What is the principle where ice is prevented from building up on a surface called?",
    options: ["De-icing", "Anti-icing", "Defrosting"],
    correctOptionIndex: 1,
  },
  {
    id: 180,
    text: "Why is anti-icing generally used on the inlet of gas turbine engines instead of de-icing?",
    options: ["It is cheaper to operate", "Ice blocks falling into the compressor could cause severe damage", "De-icing systems are not effective on inlets"],
    correctOptionIndex: 1,
  },
  {
    id: 181,
    text: "What component is typically used to direct hot air radially inward to heat all surfaces where ice might form on the engine inlet case?",
    options: ["A venturi tube", "A piccolo tube", "A vortex tube"],
    correctOptionIndex: 1,
  },
  {
    id: 182,
    text: "Why are anti-iced areas on the inlet cowl often left unpainted?",
    options: ["To save weight", "To facilitate the hot air anti-icing", "For aerodynamic reasons"],
    correctOptionIndex: 1,
  },
  {
    id: 183,
    text: "In large commercial aircraft, the hot air for thermal anti-icing (TAI) of the intake lip is generally taken from which part of the engine?",
    options: ["The fan", "The turbine", "The HP compressor"],
    correctOptionIndex: 2,
  },
  {
    id: 184,
    text: "On the CFM-56 engine, from which stage of the HP compressor is air bled for the engine anti-ice system?",
    options: ["3rd stage", "5th stage", "7th stage"],
    correctOptionIndex: 1,
  },
  {
    id: 185,
    text: "On the V2500 engine, from which stage of the compressor is air bled for the engine anti-ice system?",
    options: ["5th stage", "7th stage", "9th stage"],
    correctOptionIndex: 1,
  },
  {
    id: 186,
    text: "On the Boeing 737 with CFM56 engines, what is the maximum regulated pressure for the Inlet Cowl Thermal Anti-Ice (ICTAI) system?",
    options: ["40 psi", "50 psi", "65 psi"],
    correctOptionIndex: 1,
  },
  {
    id: 187,
    text: "On the Boeing ICTAI system, what illuminates an amber \"COWL ANTI-ICE\" light?",
    options: ["The valve failing to open", "An overpressure condition exceeding 65 psi", "The valve being manually locked closed"],
    correctOptionIndex: 1,
  },
  {
    id: 188,
    text: "On the Boeing ICTAI system, when the COWL VALVE OPEN light illuminates a dim blue, what does it indicate?",
    options: ["The valve is in transit", "The valve is open and agrees with the switch", "A system failure"],
    correctOptionIndex: 1,
  },
  {
    id: 189,
    text: "A disadvantage of hot air anti-ice systems is a slight power loss. What do some manufacturers use to avoid this loss?",
    options: ["Oil heating", "Electrical heating elements", "Exhaust gas recirculation"],
    correctOptionIndex: 1,
  },
  {
    id: 190,
    text: "Where are electrical ice protection systems more commonly found?",
    options: ["On large turbofan engine intakes", "On turboprop intakes", "On supersonic intakes"],
    correctOptionIndex: 1,
  },
  {
    id: 191,
    text: "What are electrical heating pads for ice protection bonded to?",
    options: ["The inner surface of the cowling", "The outer skin of the cowlings", "The compressor blades"],
    correctOptionIndex: 1,
  },
  {
    id: 192,
    text: "What is the advantage of using the engine oil system for ice protection?",
    options: ["It provides more heat than hot air", "It requires no control system (always on) and has no adverse effect on engine performance", "It is lighter than electrical systems"],
    correctOptionIndex: 1,
  },
  {
    id: 193,
    text: "What can damage to the intake or any roughness inside it cause?",
    options: ["Increased thrust", "Turbulent airflow, causing the compressor to surge or stall", "A reduction in fuel consumption"],
    correctOptionIndex: 1,
  },
  {
    id: 194,
    text: "Which engine mounting location suffers much less from foreign object damage?",
    options: ["Wing-mounted engines", "Tail (aft)-mounted engines", "Fuselage-mounted engines"],
    correctOptionIndex: 1,
  },
  {
    id: 195,
    text: "When should intake and exhaust covers be fitted?",
    options: ["Before engine start", "During engine run-up", "After the flight"],
    correctOptionIndex: 2,
  },
  {
    id: 196,
    text: "What should engine power be kept to during taxi to avoid damage from debris?",
    options: ["Maximum", "A minimum", "Reverse thrust only"],
    correctOptionIndex: 1,
  },
  {
    id: 197,
    text: "What is the effect of a very small discontinuity of airflow in the inlet duct?",
    options: ["No significant effect", "Can cause significant efficiency loss and engine performance problems", "Only affects fuel economy at idle"],
    correctOptionIndex: 1,
  },
  {
    id: 198,
    text: "What happens to the pressure at the compressor inlet while the engine is running on a stationary aircraft?",
    options: ["It is above ambient (ram pressure)", "It is below ambient (partial vacuum)", "It is equal to ambient pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 199,
    text: "What is 'ram recovery' also known as when referring to jet engines?",
    options: ["Ram drag", "Ram rise", "Ram pressure loss"],
    correctOptionIndex: 1,
  },
  {
    id: 200,
    text: "What happens to sound waves in front of a source moving through air at rest at less than the speed of sound (< M1)?",
    options: ["They are expanded", "They are compressed", "They are not affected"],
    correctOptionIndex: 1,
  },
  {
    id: 201,
    text: "What is the name of the perforated tube inside the inlet leading edge used for hot air anti-icing?",
    options: ["A venturi tube", "A piccolo tube", "A pitot tube"],
    correctOptionIndex: 1,
  },
  {
    id: 202,
    text: "On the Boeing ICTAI system, what does a green \"TAI\" message on the upper EICAS indicate?",
    options: ["The system is selected off", "The ICTAI valve is open", "There is a valve disagreement"],
    correctOptionIndex: 1,
  },
  {
    id: 203,
    text: "What is the purpose of a 'joggled lip' on the inside of some engine intakes?",
    options: ["To increase thrust", "To allow anti-icing air to exit into the intake itself", "To reduce noise"],
    correctOptionIndex: 1,
  },
  {
    id: 204,
    text: "How is the anti-ice valve on the CFM-56 engine (for the Airbus example) positioned when electrical power is lost, provided bleed air pressure is high enough?",
    options: ["It closes", "It fully opens", "It remains in its last position"],
    correctOptionIndex: 1,
  },
  {
    id: 205,
    text: "What type of valve is used for the Inlet Cowl Thermal Anti-Ice (ICTAI) system on the Boeing?",
    options: ["An electrically operated gate valve", "A pneumatically operated butterfly valve", "A hydraulically operated ball valve"],
    correctOptionIndex: 1,
  },
  {
    id: 206,
    text: "What is the function of the honeycomb layer in an acoustic liner?",
    options: ["To provide structural strength", "To act as a resonance chamber to trap and destroy sound energy", "To channel hot air for anti-icing"],
    correctOptionIndex: 1,
  },
  {
    id: 207,
    text: "What can the low-pressure core of a ground vortex do?",
    options: ["Improve engine cooling", "Aid the ingestion of foreign object debris into the inlet", "Increase thrust at takeoff"],
    correctOptionIndex: 1,
  },
  {
    id: 208,
    text: "What is the main challenge for designers of supersonic intakes regarding shockwaves?",
    options: ["Eliminating all shockwaves", "Forming an oblique shockwave", "Creating a normal shockwave at the lip"],
    correctOptionIndex: 1,
  },
  {
    id: 209,
    text: "In the super-critical condition of a supersonic intake, what happens to the normal shockwave?",
    options: ["It is expelled forward", "It is drawn further into the inlet", "It disappears"],
    correctOptionIndex: 1,
  },
  {
    id: 210,
    text: "How can the problem of repositioning the shockwave for changing Mach numbers be overcome in a supersonic intake?",
    options: ["By using blow-in doors", "By automatically moving the cone in and out (axial translation)", "By using a bell-mouth inlet"],
    correctOptionIndex: 1,
  },
  {
    id: 211,
    text: "What material are honeycomb cells in acoustic liners typically made from?",
    options: ["Plastic or rubber", "Aluminium or glass fibre", "Steel or titanium"],
    correctOptionIndex: 1,
  },
  {
    id: 212,
    text: "What is the primary purpose of fitting inlet screens on a static engine in a test cell?",
    options: ["To increase airflow", "To prevent foreign object ingestion", "To reduce noise"],
    correctOptionIndex: 1,
  },
  {
    id: 213,
    text: "What is the effect of a split intake duct on performance, even when flying straight?",
    options: ["It increases thrust", "It suffers losses due to boundary layer effects from the fuselage skin", "It has no effect on performance"],
    correctOptionIndex: 1,
  },
  {
    id: 214,
    text: "In a helicopter, when is the risk of foreign object ingestion highest?",
    options: ["During high-speed cruise", "During take-off and landing due to rotor downwash", "During autorotation"],
    correctOptionIndex: 1,
  },
  {
    id: 215,
    text: "On the Concorde, at what Mach number do the ramps begin to move as shock waves start forming on the intakes?",
    options: ["Mach 0.93", "Mach 1.1", "Mach 1.3"],
    correctOptionIndex: 2,
  },
  {
    id: 216,
    text: "What is the main disadvantage of using a large radius inlet lip?",
    options: ["It causes more drag at low speeds", "It degrades performance at high speeds", "It is too heavy"],
    correctOptionIndex: 1,
  },
  {
    id: 217,
    text: "What does the auxiliary inlet vane on the Concorde do as the Mach number builds?",
    options: ["It opens wider", "It begins to close", "It oscillates"],
    correctOptionIndex: 1,
  },
  {
    id: 218,
    text: "What is the function of the spill valve on a supersonic intake?",
    options: ["To increase air pressure", "To dump any unwanted air", "To heat the inlet lip"],
    correctOptionIndex: 1,
  },
  {
    id: 219,
    text: "What do some turboprop inlets use vanes for, that can be lowered into the airstream?",
    options: ["To increase thrust", "To deflect foreign objects and ice due to their greater momentum", "To reduce noise"],
    correctOptionIndex: 1,
  },
  {
    id: 220,
    text: "In a vortex tube assembly (EAPS), what spins the influent air to centrifuge particles?",
    options: ["A turbine wheel", "A four-bladed helical vane", "A high-speed fan"],
    correctOptionIndex: 1,
  },
  {
    id: 221,
    text: "What is the purpose of a manual override device on an APU air intake flap?",
    options: ["To open the flap wider for more power", "To operate the flap in case of a flap actuator failure", "To lock the flap closed permanently"],
    correctOptionIndex: 1,
  },
  {
    id: 222,
    text: "What happens to the airflow's kinetic energy when it passes through a normal shockwave?",
    options: ["It is all converted to pressure energy", "A lot of it is converted into heat energy", "It is completely destroyed"],
    correctOptionIndex: 1,
  },
  {
    id: 223,
    text: "According to the text, why must great care be exercised when operating near running engines?",
    options: ["The noise can damage hearing", "Personnel have been sucked into the intakes, causing deaths and injuries", "The exhaust gases are toxic"],
    correctOptionIndex: 1,
  },
  {
    id: 224,
    text: "What is the shape of the APU intake flap when it is closed and faired?",
    options: ["Flat", "Curved like a wing flap", "Pointed like a cone"],
    correctOptionIndex: 1,
  },
  {
    id: 225,
    text: "On the Boeing ICTAI system, how is the air routed to the cowling?",
    options: ["From a dedicated pneumatic system", "Directly from the engine bleed supply, upstream of the engine bleed valve", "From the air conditioning packs"],
    correctOptionIndex: 1,
  },
  {
    id: 226,
    text: "What is the purpose of the anti-ingestion screen sometimes fitted to a bell-mouth inlet on a test cell?",
    options: ["To increase airflow calibration accuracy", "To prevent debris from being sucked into the engine", "To reduce noise from the test cell"],
    correctOptionIndex: 1,
  },
  {
    id: 227,
    text: "In a supersonic intake with an oblique twin-shock diffuser, what is the condition called when the oblique shock has contacted the inlet lip, preventing spillage?",
    options: ["Super-critical condition", "Critical condition", "Subcritical condition"],
    correctOptionIndex: 1,
  },
  {
    id: 228,
    text: "What type of system uses strip conductors sandwiched between neoprene layers for ice protection?",
    options: ["Hot air system", "Electrical system", "Oil system"],
    correctOptionIndex: 1,
  },
  {
    id: 229,
    text: "According to the text, when is the anti-icing system typically turned on by the flight crew?",
    options: ["After entering the icing condition", "Before entering the icing condition", "Only when ice is visibly accumulating"],
    correctOptionIndex: 1,
  },
  {
    id: 230,
    text: "What is the primary function of the load compressor in an APU?",
    options: ["To start the main engine", "To supply customer bleed air for systems like air conditioning and wing anti-ice", "To generate electrical power"],
    correctOptionIndex: 1,
  },
  {
    id: 231,
    text: "What is the main risk if ice is allowed to form unevenly on compressor rotor blades?",
    options: ["Overheating of the blades", "Balance and control problems", "Reduced fuel efficiency"],
    correctOptionIndex: 1,
  },
  {
    id: 232,
    text: "What are the two basic types of compressors found in a gas-turbine engine?",
    options: ["Rotary and reciprocating", "Centrifugal flow and axial flow", "Single-stage and multi-stage"],
    correctOptionIndex: 1,
  },
  {
    id: 233,
    text: "What component in a centrifugal flow compressor accelerates the air?",
    options: ["Diffuser", "Impeller", "Scroll manifold"],
    correctOptionIndex: 1,
  },
  {
    id: 234,
    text: "What is a primary advantage of a centrifugal compressor?",
    options: ["Very high maximum compression ratio (over 30:1)", "Small engine diameter", "Robust construction, resilient to foreign object damage"],
    correctOptionIndex: 2,
  },
  {
    id: 235,
    text: "What is a primary disadvantage of an axial flow compressor?",
    options: ["High specific fuel consumption", "Critical to surge", "Large engine diameter"],
    correctOptionIndex: 1,
  },
  {
    id: 236,
    text: "What is the typical maximum compression ratio achievable with a dual-stage centrifugal compressor?",
    options: ["7:1", "15:1", "30:1"],
    correctOptionIndex: 1,
  },
  {
    id: 237,
    text: "What happens to Specific Fuel Consumption (SFC) as compressor pressure ratio increases?",
    options: ["SFC increases", "SFC decreases", "SFC remains unchanged"],
    correctOptionIndex: 1,
  },
  {
    id: 238,
    text: "What is the typical compression ratio range for a single-stage centrifugal compressor?",
    options: ["10:1 to 15:1", "5:1 to 6:1", "1.2:1 to 2.5:1"],
    correctOptionIndex: 1,
  },
  {
    id: 239,
    text: "What is the function of the front diffuser or shroud on a centrifugal compressor?",
    options: ["To collect air from the diffuser", "To prevent air leakage over the impeller vanes", "To convert pressure into velocity"],
    correctOptionIndex: 1,
  },
  {
    id: 240,
    text: "What material is typically sprayed onto the shroud of a centrifugal compressor as an abradable coating?",
    options: ["Titanium alloy", "Nickel alloy", "Silicon aluminium"],
    correctOptionIndex: 2,
  },
  {
    id: 241,
    text: "What is the function of the compressor manifold (scroll)?",
    options: ["To accelerate air into the impeller", "To collect air from the diffuser and turn it towards the combustion chamber", "To house the variable inlet guide vanes"],
    correctOptionIndex: 1,
  },
  {
    id: 242,
    text: "In an axial flow compressor, what does one \"stage\" consist of?",
    options: ["One rotor assembly only", "One row of rotating blades followed by one row of stator vanes", "One stator vane assembly only"],
    correctOptionIndex: 1,
  },
  {
    id: 243,
    text: "What is the \"design point\" of a compressor based on?",
    options: ["Maximum takeoff thrust only", "Cruise speed and altitude (air density)", "Ground idle RPM only"],
    correctOptionIndex: 1,
  },
  {
    id: 244,
    text: "Why is the air annulus area gradually reduced from the front to the rear of an axial compressor?",
    options: ["To decrease air density", "To maintain a nearly constant air axial velocity as density increases", "To increase the temperature of the air"],
    correctOptionIndex: 1,
  },
  {
    id: 245,
    text: "What limits the RPM of a compressor due to tip speed?",
    options: ["Fuel flow", "Turbine inlet temperature", "Mach 0.85, where shock waves are produced"],
    correctOptionIndex: 2,
  },
  {
    id: 246,
    text: "What is a multi-spool compressor designed to achieve?",
    options: ["Lower overall pressure ratios", "Higher pressure ratios and greater operating flexibility", "Simpler construction and lower cost"],
    correctOptionIndex: 1,
  },
  {
    id: 247,
    text: "In a high bypass ratio turbofan, what are the two airflows called?",
    options: ["Hot flow and cold flow", "Primary airflow (core) and secondary airflow (bypass)", "Compressor flow and turbine flow"],
    correctOptionIndex: 1,
  },
  {
    id: 248,
    text: "What are the most common types of rotor blade root fixings mentioned?",
    options: ["Screw thread and welded", "Dovetail, fir tree, de Laval bulb, and solid root", "Bolted flange and riveted"],
    correctOptionIndex: 1,
  },
  {
    id: 249,
    text: "What is a \"blisk\" (bladed disk)?",
    options: ["A rotor blade with a dovetail root", "An integrated cast disk with blades, used on smaller engine compressors", "A stator vane assembly"],
    correctOptionIndex: 1,
  },
  {
    id: 250,
    text: "On a CFM 56-5a engine, what material is the fan blade made of?",
    options: ["Nickel alloy", "Titanium alloy", "Steel alloy"],
    correctOptionIndex: 1,
  },
  {
    id: 251,
    text: "What is the purpose of a snubber (mid-span shroud) on a fan blade?",
    options: ["To increase the blade's weight", "To support the blade and reduce vibration", "To improve fuel efficiency"],
    correctOptionIndex: 1,
  },
  {
    id: 252,
    text: "How is a wide chord fan blade constructed?",
    options: ["Solid titanium forging", "Steel alloy with nickel coating", "A honeycomb core sandwiched between two outer titanium skins"],
    correctOptionIndex: 2,
  },
  {
    id: 253,
    text: "What is the function of the last row of stator vanes in an axial compressor?",
    options: ["To increase air velocity", "To act as air straighteners, removing swirl before the combustion system", "To decrease air pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 254,
    text: "What is the typical total pressure ratio increase per stage in an axial compressor?",
    options: ["5:1 to 6:1", "10:1 to 15:1", "1.1:1 to 2.5:1"],
    correctOptionIndex: 2,
  },
  {
    id: 255,
    text: "According to Compressor Fact 1, what happens when compressor inlet pressure increases?",
    options: ["Outlet pressure decreases", "Outlet pressure increases", "Outlet pressure remains the same"],
    correctOptionIndex: 1,
  },
  {
    id: 256,
    text: "According to Compressor Fact 2, what happens when compressor inlet temperature decreases?",
    options: ["The compressor's capacity to compress air pressure increases", "The compressor's capacity to compress air pressure decreases", "There is no change in compression capacity"],
    correctOptionIndex: 0,
  },
  {
    id: 257,
    text: "According to Compressor Fact 3, how does compressor capacity to compress air increase with RPM?",
    options: ["Linearly with RPM", "With the square of RPM", "Exponentially with RPM"],
    correctOptionIndex: 1,
  },
  {
    id: 258,
    text: "What is the difference between a compressor stall and a compressor surge?",
    options: ["A stall is complete, a surge affects one blade", "A surge is a stall of the entire compressor", "There is no difference"],
    correctOptionIndex: 1,
  },
  {
    id: 259,
    text: "What is a common cause of compressor stall/surge?",
    options: ["Low crosswinds on the ground", "Rapid throttle movements", "Decreased fuel flow"],
    correctOptionIndex: 1,
  },
  {
    id: 260,
    text: "What is a typical indication of a compressor stall/surge?",
    options: ["Decreased EGT", "Abnormal noises such as bangs or rumbles", "Increased throttle response"],
    correctOptionIndex: 1,
  },
  {
    id: 261,
    text: "On a stall/surge margin graph, what does the \"normal operating line\" represent?",
    options: ["The maximum compression ratio possible", "Where the engine operates with correctly matched compression ratio and air mass", "The point where a stall is guaranteed"],
    correctOptionIndex: 1,
  },
  {
    id: 262,
    text: "What does the \"stall margin zone\" on a compressor map allow for?",
    options: ["Increased thrust", "Reductions in compressor efficiency and fluctuations in atmosphere/fuel system", "Higher RPM operation"],
    correctOptionIndex: 1,
  },
  {
    id: 263,
    text: "What is a consequence of a dirty compressor on the stall/surge map?",
    options: ["The surge/stall line moves away from the normal operating line", "The surge/stall line approaches the normal operating line, reducing the stall margin zone", "The normal operating line moves higher"],
    correctOptionIndex: 1,
  },
  {
    id: 264,
    text: "What systems are fitted to an engine to ensure surge and stall do not happen?",
    options: ["Afterburners and reheat systems", "Multi-spool compressors, VIGV, VSV, VBV, and bleed valves", "Thrust reversers and noise suppressors"],
    correctOptionIndex: 1,
  },
  {
    id: 265,
    text: "How do multi-spool compressors help prevent stall?",
    options: ["By increasing the overall engine weight", "By maintaining optimum blade angle of attack over a greater RPM range", "By decreasing the number of compressor stages"],
    correctOptionIndex: 1,
  },
  {
    id: 266,
    text: "What is the purpose of a compressor bleed valve?",
    options: ["To increase mass airflow through the engine", "To allow excessive airflow from forward stages to escape, preventing blockage in aft stages at low RPM", "To cool the turbine section"],
    correctOptionIndex: 1,
  },
  {
    id: 267,
    text: "What is a disadvantage of opening a compressor bleed valve?",
    options: ["Decreased EGT", "Increased thrust for a given throttle setting", "Decreased mass airflow and increased SFC"],
    correctOptionIndex: 2,
  },
  {
    id: 268,
    text: "In the Pratt & Whitney PT6 compressor section, what material are the first-stage blades made of?",
    options: ["Stainless steel", "Aluminium alloy", "Titanium"],
    correctOptionIndex: 2,
  },
  {
    id: 269,
    text: "On a CFM-56 engine, when are the Variable Bleed Valves (VBV) fully closed?",
    options: ["At idle speed", "At approximately 85-88% N1 speed", "During engine start"],
    correctOptionIndex: 1,
  },
  {
    id: 270,
    text: "What controls the Variable Bleed Valves (VBV) on newer CFM-56 engines?",
    options: ["A purely mechanical linkage", "A FADEC system controlling an HMU", "A pneumatic governor"],
    correctOptionIndex: 1,
  },
  {
    id: 271,
    text: "What is the function of Variable Stator Vanes (VSV)?",
    options: ["To decrease the compressor pressure ratio", "To schedule the correct angle of attack between airflow and rotor blades, especially at low speeds", "To act as fuel metering devices"],
    correctOptionIndex: 1,
  },
  {
    id: 272,
    text: "On a typical variable vane schedule, at what N2 speed do the vanes start to open?",
    options: ["At idle (approx. 20% N2)", "Up to 65% N2 (closed), then start to open", "Only above 100% N2"],
    correctOptionIndex: 1,
  },
  {
    id: 273,
    text: "What sensor is used to reset the vane-open schedule to match ambient temperature changes?",
    options: ["Exhaust Gas Temperature (EGT) sensor", "Compressor Inlet Temperature (CIT) sensor", "Oil pressure sensor"],
    correctOptionIndex: 1,
  },
  {
    id: 274,
    text: "What happens to the variable vane schedule if the ambient temperature drops below ISA conditions?",
    options: ["The vanes start to open at a lower N2 speed", "The vanes remain closed for longer", "The vanes do not open at all"],
    correctOptionIndex: 0,
  },
  {
    id: 275,
    text: "What is the primary advantage of using FADEC for airflow control?",
    options: ["Simpler mechanical systems", "Better and more precise control using multiple input parameters", "Lower manufacturing cost"],
    correctOptionIndex: 1,
  },
  {
    id: 276,
    text: "What happens to the variable vanes if the electrical signal to the actuator is lost on a FADEC-controlled system (PW4168)?",
    options: ["The vanes go to the fully closed position", "The vanes automatically open", "The vanes stay in their last commanded position"],
    correctOptionIndex: 1,
  },
  {
    id: 277,
    text: "During thrust reverse on a PW4168 engine, what is the position of the Variable Bleed Valves (VBVs)?",
    options: ["Fully closed", "100% open", "Modulated between 50% and 80%"],
    correctOptionIndex: 1,
  },
  {
    id: 278,
    text: "What is the purpose of the three-shot (plot) method for fan balancing?",
    options: ["To balance the low-pressure turbine", "To find the phase angle of the imbalance when no onboard equipment is available", "To dynamically balance the engine during flight"],
    correctOptionIndex: 1,
  },
  {
    id: 279,
    text: "What is a major disadvantage of the three-shot fan balancing method?",
    options: ["It requires special software", "It is extremely expensive due to the required engine runs and risky calculations", "It cannot be performed on modern engines"],
    correctOptionIndex: 1,
  },
  {
    id: 280,
    text: "What is the advantage of the one-shot fan trim balancing method over the three-shot method?",
    options: ["It requires adding test weights", "Measurements can be done during a routine flight or ground run without adding weights", "It is less accurate"],
    correctOptionIndex: 1,
  },
  {
    id: 281,
    text: "What is the function of the diffuser vanes in a centrifugal compressor?",
    options: ["To accelerate the air to supersonic speeds", "To form divergent nozzles that convert velocity energy into pressure energy", "To mix fuel with the air"],
    correctOptionIndex: 1,
  },
  {
    id: 282,
    text: "What is a typical material for an impeller in a centrifugal compressor?",
    options: ["Aluminium alloy", "Stainless steel or titanium", "Composite material"],
    correctOptionIndex: 1,
  },
  {
    id: 283,
    text: "In an axial compressor, what is the function of the rotor blades?",
    options: ["To convert velocity energy into pressure energy", "To add mechanical energy, converting it into kinetic and potential energy", "To act as air straighteners"],
    correctOptionIndex: 1,
  },
  {
    id: 284,
    text: "What is the function of the stator vanes in an axial compressor?",
    options: ["To add mechanical energy to the airflow", "To convert velocity energy into pressure energy", "To increase the airflow velocity"],
    correctOptionIndex: 1,
  },
  {
    id: 285,
    text: "What is a primary advantage of an axial compressor over a centrifugal compressor?",
    options: ["Lower manufacturing cost", "Small frontal area and ability to achieve higher pressure ratios", "Less susceptible to foreign object damage"],
    correctOptionIndex: 1,
  },
  {
    id: 286,
    text: "What is a primary disadvantage of a centrifugal compressor compared to an axial compressor?",
    options: ["It is more difficult to manufacture", "It has a large engine diameter and is limited to a low overall compression ratio", "It has a very high specific fuel consumption"],
    correctOptionIndex: 1,
  },
  {
    id: 287,
    text: "In a compound compressor, how are axial and centrifugal designs combined?",
    options: ["Centrifugal compressor boosts pressure into an axial compressor", "Axial compressor boosts inlet pressure of a centrifugal compressor", "They operate on separate shafts independently"],
    correctOptionIndex: 1,
  },
  {
    id: 288,
    text: "What is the clearance between the impeller and diffuser in a centrifugal compressor critical for?",
    options: ["Fuel flow", "Preventing aerodynamic buffeting and vibration", "Ignition timing"],
    correctOptionIndex: 1,
  },
  {
    id: 289,
    text: "What are the two types of airflow in a turbofan engine that are also called primary and secondary airflow?",
    options: ["Hot and cold", "Core (primary) and bypass (secondary)", "Compressed and expanded"],
    correctOptionIndex: 1,
  },
  {
    id: 290,
    text: "What component separates the primary and secondary airflow in a CFM 56-5a engine's LP section?",
    options: ["The splitter fairing", "The outlet guide vane (OGV)", "The labyrinth seal"],
    correctOptionIndex: 0,
  },
  {
    id: 291,
    text: "What material are the Outlet Guide Vanes (OGVs) made of on a CFM 56-5a engine?",
    options: ["Titanium alloy", "Nickel alloy", "Composite material"],
    correctOptionIndex: 2,
  },
  {
    id: 292,
    text: "Why are nickel alloys used for rotor blades in the rear stages of a high-pressure compressor?",
    options: ["They are lighter than titanium", "They can withstand the higher temperatures in the rear stages", "They are cheaper to machine"],
    correctOptionIndex: 1,
  },
  {
    id: 293,
    text: "Why is titanium unsuitable for manufacturing smaller vanes further into the engine compressor?",
    options: ["It is too heavy", "The high compression temperature can adversely affect it", "It is too expensive for small parts"],
    correctOptionIndex: 1,
  },
  {
    id: 294,
    text: "What is the effect of a successful stall recovery by a pilot?",
    options: ["Increase power and continue in adverse weather", "Quickly reduce power, then carefully accelerate, avoiding adverse weather", "Immediately shut down the engine"],
    correctOptionIndex: 1,
  },
  {
    id: 295,
    text: "What does a decrease in compressor pressure ratio cause on a stall map?",
    options: ["An increase in mass airflow", "A decrease in mass airflow", "No change in mass airflow"],
    correctOptionIndex: 1,
  },
  {
    id: 296,
    text: "What is the name for the bleed valve system that can be fully varied to bleed the required amount of air?",
    options: ["Compressor Bleed Valve (CBV)", "Variable Bleed Valve (VBV)", "Handling Bleed Valve"],
    correctOptionIndex: 1,
  },
  {
    id: 297,
    text: "What type of signal does a feedback cable provide to the fuel control on a CFM-56 VBV system?",
    options: ["An electrical signal of N2 speed", "A constant mechanical signal of the bleed valve position", "A pneumatic signal of compressor discharge pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 298,
    text: "What type of transformer provides feedback from the VBVs to the FADEC system on newer engines?",
    options: ["Linear Variable Differential Transformer (LVDT)", "Rotary Variable Differential Transformer (RVDT)", "Constant Variable Transformer (CVT)"],
    correctOptionIndex: 1,
  },
  {
    id: 299,
    text: "What is the effect of a variable vane getting stuck in a 40° closed position instead of 30° at idle?",
    options: ["Inlet velocity would increase", "Effective angle of attack would increase from 15° to 25°, risking a stall", "Compression would increase significantly"],
    correctOptionIndex: 1,
  },
  {
    id: 300,
    text: "On a fixed stator vane engine, what does the operating line C-D represent?",
    options: ["The surge line", "A standard compressor ratio to mass airflow relationship", "The stall margin zone"],
    correctOptionIndex: 1,
  },
  {
    id: 301,
    text: "With variable vanes installed, the operating line can be safely raised to position E-F because the vane system automatically schedules what?",
    options: ["Higher fuel flow", "Correct CPR and mass airflow for any given RPM", "Lower turbine temperatures"],
    correctOptionIndex: 1,
  },
  {
    id: 302,
    text: "How are variable inlet guide vanes (VIGV) typically actuated on a small engine anti-stall system?",
    options: ["Electrically by the FADEC", "By fuel pressure commanded by the power lever", "By a mechanical cable from the cockpit"],
    correctOptionIndex: 1,
  },
  {
    id: 303,
    text: "What is the purpose of the CIT sensor in a General Electric CF6 turbofan VIGV/VSV system?",
    options: ["To measure turbine exhaust temperature", "To reset the vane-open schedule to match changes in ambient temperature and mass airflow", "To control fuel shut-off"],
    correctOptionIndex: 1,
  },
  {
    id: 304,
    text: "What happens to the variable vanes if the EEC/ECU on a PW4168 engine senses a surge?",
    options: ["The vanes move to the fully open position", "The vanes start to close", "The vanes start to oscillate"],
    correctOptionIndex: 1,
  },
  {
    id: 305,
    text: "What is the name for the muscle pressure used to close pneumatic/spring-actuated poppet-type bleed valves?",
    options: ["Ps3", "P2.5", "Px"],
    correctOptionIndex: 0,
  },
  {
    id: 306,
    text: "On a PW4168 engine, at what N2 speed do the 2.9 bleed valves close during engine start?",
    options: ["At idle speed (approx. 60% N2)", "At approximately 2% N2 below idle speed", "At 100% N2"],
    correctOptionIndex: 1,
  },
  {
    id: 307,
    text: "What sensors sense the position of the actuator piston rod in a FADEC-controlled VIGV/VGV system?",
    options: ["Thermocouples", "Temperature-compensated dual LVDTs", "Pressure transducers"],
    correctOptionIndex: 1,
  },
  {
    id: 308,
    text: "What system usually receives vibration data from the Engine Vibration Monitoring System (EVMS)?",
    options: ["The fuel control unit", "The Aircraft Condition Monitoring System (ACMS)", "The ignition system"],
    correctOptionIndex: 1,
  },
  {
    id: 309,
    text: "Why must vibration levels be periodically checked on an engine?",
    options: ["To increase fuel efficiency", "To prevent any adverse trends and verify the vibration rate is not accelerating due to a fault", "To comply with noise regulations"],
    correctOptionIndex: 1,
  },
  {
    id: 310,
    text: "What is required for the one-shot fan trim balancing method?",
    options: ["Three separate engine runs with different test weights", "Knowledge of all current balancing weights and their position on the fan", "A special heavy test fan blade"],
    correctOptionIndex: 1,
  },
  {
    id: 311,
    text: "What is the function of the labyrinth seal in a compressor spool (e.g., CFM 56-5a)?",
    options: ["To retain the rotor blades", "To provide an air seal between compressor stages", "To dampen vibrations"],
    correctOptionIndex: 1,
  },
  {
    id: 312,
    text: "What is the purpose of a plenum chamber in a dual-entry centrifugal compressor?",
    options: ["To increase air velocity", "To supply air to the rear section of a double-entry impeller", "To collect exhaust gases"],
    correctOptionIndex: 1,
  },
  {
    id: 313,
    text: "What is a convergent-divergent metering orifice used for in a bleed valve system (e.g., PT6)?",
    options: ["To increase airflow", "To modify pressure over the engine operating range to maintain a fixed P3/Px ratio", "To cool the bleed valve piston"],
    correctOptionIndex: 1,
  },
  {
    id: 314,
    text: "What does the FADEC system use to control small electro-hydraulic servo valves (EHSV) inside the HMU?",
    options: ["Mechanical feedback cables", "Signals from electrical sensors (N2 speed, fan discharge temperature)", "Pneumatic pressure from the compressor"],
    correctOptionIndex: 1,
  },
  {
    id: 315,
    text: "What is the effect of a decrease in compressor inlet temperature on the compression in the rear stages of a compressor?",
    options: ["Compression decreases", "Compression increases", "There is no effect on compression"],
    correctOptionIndex: 1,
  },
  {
    id: 316,
    text: "What does the ECU/EEC do if a total electrical failure occurs on a FADEC airflow control system?",
    options: ["Shuts down the engine", "Moves all airflow controls to safe positions", "Locks all valves in their last position"],
    correctOptionIndex: 1,
  },
  {
    id: 317,
    text: "From where can an engineer select built-in test equipment (BITE) tests for the airflow system?",
    options: ["The engine's HMU", "The aircraft's Multipurpose Control Display Unit (MCDU)", "The aircraft's landing gear control panel"],
    correctOptionIndex: 1,
  },
  {
    id: 318,
    text: "What is the function of the air filter in the FADEC airflow control system on a PW4168?",
    options: ["To clean fuel going to the HMU", "To remove contamination from HPC discharge airflow (Ps3) used as muscle pressure", "To filter oil for the actuator"],
    correctOptionIndex: 1,
  },
  {
    id: 319,
    text: "What is the main reason for using a dual-entry centrifugal compressor?",
    options: ["To achieve a higher pressure ratio", "When a large air volume is needed", "To simplify the inlet duct design"],
    correctOptionIndex: 1,
  },
  {
    id: 320,
    text: "What is the typical outlet pressure of a single-stage centrifugal compressor with a 5:1 ratio and 14.7 psi inlet?",
    options: ["29.4 psi", "73.5 psi", "147 psi"],
    correctOptionIndex: 1,
  },
  {
    id: 321,
    text: "If a first-stage centrifugal compressor has a 4:1 ratio and a second stage has a 3:1 ratio, what is the total engine compressor ratio?",
    options: ["7:1", "12:1", "1.33:1"],
    correctOptionIndex: 1,
  },
  {
    id: 322,
    text: "What is the primary function of the fuel-driven motor in a CFM-56 VBV system?",
    options: ["To drive the fuel pump", "To power the mechanical actuator and flexible shaft that operates the bleed valves", "To control the variable inlet guide vanes"],
    correctOptionIndex: 1,
  },
  {
    id: 323,
    text: "What does the feedback cable in a CFM-56 VBV system allow the fuel control to do?",
    options: ["Increase fuel flow", "Constantly compare the bleed valve position against automatic signals of speed and temperature", "Bypass the engine oil cooler"],
    correctOptionIndex: 1,
  },
  {
    id: 324,
    text: "What is the primary role of Variable Inlet Guide Vanes (VIGV) in the compressor of a jet engine?",
    options: ["To increase fuel efficiency at all speeds", "To schedule the blade angle of attack for optimum stall margin across the engine operating envelope", "To provide mechanical support for the compressor casing"],
    correctOptionIndex: 1,
  },
  {
    id: 325,
    text: "At what operational condition is a centrifugal compressor typically most efficient?",
    options: ["At idle power settings with maximum blade angle", "At its design point where pressure ratio, mass airflow, and RPM are optimally matched", "Only at maximum RPM regardless of pressure requirements"],
    correctOptionIndex: 1,
  },
];
