export const icaoEasaRegulationsQuestions = [
  {
    id: 1,
    text: "What type of organization is the ICAO?",
    options: ["A regulatory authority with enforcement powers", "A specialized agency of the United Nations", "An international court for aviation disputes"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "Does the ICAO have the power to impose regulations on member nations?",
    options: ["Yes, it can impose binding regulations on all members", "No, it does not have the power to impose regulations", "Only on nations that have violated aviation standards"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "What does the ICAO conduct to ensure compliance with international aviation standards?",
    options: ["Criminal prosecutions", "Audits of its member states", "Financial penalties"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "Where is the ICAO headquarters located?",
    options: ["New York, USA", "Geneva, Switzerland", "Montreal, Canada"],
    correctOptionIndex: 2,
  },
  {
    id: 5,
    text: "In which year was the ICAO established?",
    options: ["1944", "1947", "1950"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "When was the Chicago Convention signed?",
    options: ["December 7, 1941", "December 7, 1944", "April 4, 1947"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "How many states originally signed the Chicago Convention?",
    options: ["36 states", "52 states", "193 states"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "What is each member country of the ICAO known as?",
    options: ["A signatory nation", "A contracting state", "A participating member"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "After how many ratifications did the ICAO come into existence?",
    options: ["26 ratifications", "36 ratifications", "52 ratifications"],
    correctOptionIndex: 0,
  },
  {
    id: 10,
    text: "What is the highest governing body of the ICAO?",
    options: ["The Council", "The Assembly", "The Secretariat"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "How often does the ICAO Assembly convene?",
    options: ["Every year", "Every three years", "Every five years"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "How many states serve on the ICAO Council?",
    options: ["36 states", "52 states", "193 states"],
    correctOptionIndex: 0,
  },
  {
    id: 13,
    text: "For how long are ICAO Council members elected?",
    options: ["Two-year term", "Three-year term", "Five-year term"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "Who heads the ICAO Secretariat?",
    options: ["The President of the Council", "The Secretary-General", "The Assembly Chairman"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "How many Annexes to the Chicago Convention have been created?",
    options: ["12 Annexes", "15 Annexes", "19 Annexes"],
    correctOptionIndex: 2,
  },
  {
    id: 16,
    text: "What is the difference between a Standard and a Recommended Practice?",
    options: ["Standards are optional, Recommended Practices are mandatory", "Standards are essential, Recommended Practices are desirable", "Both are equally mandatory"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "If a member state has a standard different from the ICAO, what must it do?",
    options: ["Immediately change to ICAO standards", "Inform the ICAO of the difference", "Pay a penalty"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "How often must countries update their Aeronautical Information Publication (AIP)?",
    options: ["Every 14 days", "Every 28 days", "Every 60 days"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "Which ICAO Annex contains requirements for personnel licensing?",
    options: ["Annex 1", "Annex 6", "Annex 8"],
    correctOptionIndex: 0,
  },
  {
    id: 20,
    text: "Which ICAO Annex addresses the airworthiness of aircraft?",
    options: ["Annex 6", "Annex 8", "Annex 19"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "Which ICAO Annex deals with Safety Management Systems?",
    options: ["Annex 6", "Annex 8", "Annex 19"],
    correctOptionIndex: 2,
  },
  {
    id: 22,
    text: "Which ICAO Annex covers aircraft accident and incident investigation?",
    options: ["Annex 12", "Annex 13", "Annex 14"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "What type of approach does SMS use for managing safety risks?",
    options: ["Reactive only", "Proactive and systematic", "Punitive"],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "Who is responsible for SMS implementation in an organization?",
    options: ["The quality manager", "The accountable manager", "All staff equally"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "How many components make up the ICAO SMS framework?",
    options: ["Three components", "Four components", "Five components"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "Which of the following is NOT one of the four SMS components?",
    options: ["Safety policy and objectives", "Safety risk management", "Financial assurance"],
    correctOptionIndex: 2,
  },
  {
    id: 27,
    text: "SMS implementation should be proportionate to what factors?",
    options: ["The age of the organization", "The size of the organization and complexity of services", "The number of aircraft maintained"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "How many member states currently comprise the European Union?",
    options: ["19 member states", "27 member states", "28 member states"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "How often is the European Parliament elected?",
    options: ["Every three years", "Every four years", "Every five years"],
    correctOptionIndex: 2,
  },
  {
    id: 30,
    text: "Which treaty established the European Union under its current name?",
    options: ["The Treaty of Rome", "The Maastricht Treaty", "The Treaty of Lisbon"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "In which year did the Treaty of Lisbon come into effect?",
    options: ["1993", "2000", "2009"],
    correctOptionIndex: 2,
  },
  {
    id: 32,
    text: "Which institution serves as the executive branch of the European Union?",
    options: ["The European Parliament", "The European Commission", "The Council of the European Union"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "What is the European Council's role?",
    options: ["Proposing new laws", "Highest political authority setting policy agenda", "Managing the day-to-day operations of the EU"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "How many Commissioners serve on the European Commission?",
    options: ["27 Commissioners, one from each member state", "36 Commissioners", "15 Commissioners from largest member states"],
    correctOptionIndex: 0,
  },
  {
    id: 35,
    text: "Where is the European Central Bank located?",
    options: ["Brussels", "Frankfurt", "Luxembourg"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "Where does the European Parliament hold its plenary sessions?",
    options: ["Brussels", "Luxembourg", "Strasbourg"],
    correctOptionIndex: 2,
  },
  {
    id: 37,
    text: "What \"right\" does the European Commission hold regarding legislation?",
    options: ["The right of veto", "The right of initiative", "The right of enforcement only"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "What is the Commission's role as \"Guardian of the Treaties\"?",
    options: ["Proposing new treaties", "Ensuring member countries enforce EU laws accurately", "Representing the EU internationally"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "Which institution has the sole power to dismiss the European Commission?",
    options: ["The European Council", "The European Parliament", "The Court of Justice"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "What is an EU Regulation?",
    options: ["A legal act that requires national transposition", "A legal act that applies uniformly to all EU countries without national transposition", "A non-binding recommendation"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "What is an EU Directive?",
    options: ["Automatically applicable in all member states", "Stipulates outcomes but allows member states to decide how to achieve them", "Binding only on specific individuals"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "What is the process called when EU countries incorporate directives into national law?",
    options: ["Implementation", "Transposition", "Adoption"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "Within what period must transposition of a directive into national law occur?",
    options: ["One year of adoption", "Two years of adoption", "Three years of adoption"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "What is a Decision in EU law?",
    options: ["Binding only on those it specifies", "A non-binding suggestion", "Requires transposition into national law"],
    correctOptionIndex: 0,
  },
  {
    id: 45,
    text: "When did the new numbering system for EU legal acts begin?",
    options: ["January 1, 2010", "January 1, 2015", "January 1, 2020"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "When was EASA established?",
    options: ["15 July 2003", "20 February 2008", "11 September 2018"],
    correctOptionIndex: 0,
  },
  {
    id: 47,
    text: "When did EASA become fully functional?",
    options: ["2003", "2008", "2010"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "What organization did EASA take over functions from?",
    options: ["ICAO", "Joint Aviation Authorities (JAA)", "FAA"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "Where is the EASA headquarters located?",
    options: ["Brussels, Belgium", "Cologne, Germany", "Paris, France"],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "Which regulation originally established EASA in 2002?",
    options: ["Regulation (EC) No. 1592/2002", "Regulation (EC) No. 216/2008", "Regulation (EU) 2018/1139"],
    correctOptionIndex: 0,
  },
  {
    id: 51,
    text: "Which regulation is currently the Basic Regulation?",
    options: ["Regulation (EC) No. 216/2008", "Regulation (EU) 2018/1139", "Regulation (EU) No. 1321/2014"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "How many EU member states are part of EASA?",
    options: ["19", "27", "31"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "How many EFTA associates participate in EASA activities?",
    options: ["2", "4", "6"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "Which of the following is an EFTA country participating in EASA?",
    options: ["United Kingdom", "Switzerland", "Turkey"],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "When did the JAA cease to exist?",
    options: ["2003", "2008", "2009"],
    correctOptionIndex: 2,
  },
  {
    id: 56,
    text: "What was the key difference between EASA and JAA?",
    options: ["EASA only covers Western Europe", "EASA has legal regulatory authority within the EU", "JAA had enforcement powers that EASA lacks"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "What certificates does EASA grant?",
    options: ["Only pilot licenses", "New type certificates and design-related airworthiness approvals", "Only maintenance organization approvals"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "What are NAAs of EU member states also known as?",
    options: ["Regulatory bodies", "Competent authorities", "Oversight offices"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "When did EASA assume direct responsibility for airworthiness certification?",
    options: ["15 July 2003", "28 September 2003", "20 February 2008"],
    correctOptionIndex: 1,
  },
  {
    id: 60,
    text: "What does EASA issue to correct potentially unsafe situations?",
    options: ["Safety alerts", "Airworthiness directives", "Service bulletins"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "Which regulation lists aircraft exempt from EASA rules?",
    options: ["Article 2 of Regulation (EU) 2018/1139", "Annex I of Regulation (EU) 2018/1139", "Article 77 of Regulation (EU) 2018/1139"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "Aircraft used by military, customs, and police are classified as what?",
    options: ["Private aircraft", "Government aircraft", "State aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "What percentage of an amateur-built aircraft must be built by the amateur?",
    options: ["At least 25%", "At least 51%", "At least 75%"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "What is the maximum take-off mass for single and two-seater gyroplanes exempt from EASA rules?",
    options: ["495 kg", "560 kg", "600 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "For how long is a type certificate issued?",
    options: ["5 years", "10 years", "Unlimited duration"],
    correctOptionIndex: 2,
  },
  {
    id: 66,
    text: "When does a type certificate change?",
    options: ["Every 5 years", "When a significant change is made to the aircraft", "When the aircraft changes ownership"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "What does an NAA maintain for its respective state?",
    options: ["Only pilot licenses", "An aircraft register", "International aviation standards"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "What authority does the US Federal Aviation Administration represent?",
    options: ["EASA member state authority", "National Aviation Authority of the USA", "International aviation regulator"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "What is a BASA?",
    options: ["Bilateral Aviation Safety Agreement", "Basic Aviation Standards Agreement", "European Aviation Safety Agreement"],
    correctOptionIndex: 0,
  },
  {
    id: 70,
    text: "Who signs a Bilateral Aviation Safety Agreement?",
    options: ["EASA directly with foreign authorities", "The EU along with its member states and non-EU countries", "Individual member states with foreign countries"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "What is a Working Arrangement (WA)?",
    options: ["A legally binding treaty between the EU and non-EU countries", "A technical agreement between EASA and a non-EU authority", "An internal EU procedure document"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "Do Working Arrangements allow for mutual recognition of certificates?",
    options: ["Yes, they provide full mutual recognition", "No, they do not allow mutual recognition", "Only for maintenance organizations"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "Where are EASA's international offices located?",
    options: ["London, Tokyo, Sydney, Sao Paulo", "Washington, Beijing, Montreal, Singapore", "Moscow, Dubai, Johannesburg, New Delhi"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "What is the main objective of the Basic Regulation?",
    options: ["To establish pilot licensing requirements", "To establish and maintain a high uniform level of civil aviation safety in the Union", "To regulate airport operations"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "Which article of the Basic Regulation directs EASA to perform functions of the state of design?",
    options: ["Article 1", "Article 77", "Article 80"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "Which article grants EASA responsibility to certify pilots?",
    options: ["Article 77", "Article 78", "Article 80"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "Which article extends EASA's responsibility to ATM/ANS organizations?",
    options: ["Article 78", "Article 80", "Article 81"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "What does Regulation (EU) No. 748/2012 address?",
    options: ["Continuing airworthiness", "Initial airworthiness", "Air operations"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "Which Annex of Regulation 748/2012 contains Part-21?",
    options: ["Annex I", "Annex II", "Annex III"],
    correctOptionIndex: 0,
  },
  {
    id: 80,
    text: "In the USA, what regulation contains similar provisions to Part-21?",
    options: ["FAR Part 25", "FAR Part 21", "FAR Part 43"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "Which Subpart of Part-21 addresses Design Organisation Approval?",
    options: ["Subpart G", "Subpart H", "Subpart J"],
    correctOptionIndex: 2,
  },
  {
    id: 82,
    text: "Which Subpart of Part-21 addresses Production Organisation Approval?",
    options: ["Subpart G", "Subpart H", "Subpart J"],
    correctOptionIndex: 0,
  },
  {
    id: 83,
    text: "What are Certification Specifications also known as?",
    options: ["Implementing rules", "Airworthiness codes", "Guidance materials"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "Which CS covers Large Aeroplanes?",
    options: ["CS-23", "CS-25", "CS-27"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "Which CS covers Small Rotorcraft?",
    options: ["CS-25", "CS-27", "CS-29"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "Which CS covers Engines?",
    options: ["CS-E", "CS-P", "CS-36"],
    correctOptionIndex: 0,
  },
  {
    id: 87,
    text: "Which CS covers Propellers?",
    options: ["CS-E", "CS-P", "CS-34"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "What does Regulation (EU) No. 1321/2014 address?",
    options: ["Initial airworthiness", "Continuing airworthiness", "Air crew licensing"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "How many Annexes does Regulation (EU) No. 1321/2014 have?",
    options: ["5 Annexes", "6 Annexes", "8 Annexes"],
    correctOptionIndex: 2,
  },
  {
    id: 90,
    text: "Which Annex contains Part-M (Continuing Airworthiness Management)?",
    options: ["Annex I", "Annex II", "Annex III"],
    correctOptionIndex: 0,
  },
  {
    id: 91,
    text: "Which Annex contains Part-145 (Maintenance Organisation Approval)?",
    options: ["Annex I", "Annex II", "Annex III"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "Which Annex contains Part-66 (Certifying Staff)?",
    options: ["Annex II", "Annex III", "Annex IV"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "Which Annex contains Part-147 (Training Organisation Requirements)?",
    options: ["Annex III", "Annex IV", "Annex V"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "Which Annex contains Part-T (Third-country Registered Aircraft)?",
    options: ["Annex IV", "Annex Va", "Annex Vb"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "Which Annex contains Part-ML (Light Aircraft)?",
    options: ["Annex Va", "Annex Vb", "Annex Vc"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "Which Annex contains Part-CAMO?",
    options: ["Annex Vb", "Annex Vc", "Annex Vd"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "Which Annex contains Part-CAO?",
    options: ["Annex Vc", "Annex Vd", "Annex Va"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "What does Part-66 establish requirements for?",
    options: ["Maintenance organizations", "Certifying staff", "Training organizations"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "What are the different licence categories in Part-66 distinguished by?",
    options: ["Age of the engineer", "Level of technical and practical knowledge", "Type of aircraft only"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "What document must an organization submit to obtain Part-145 approval?",
    options: ["Quality manual", "Maintenance Organisation Exposition (MOE)", "Training manual"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "According to Part-145, how long must maintenance records be kept?",
    options: ["1 year", "2 years", "3 years"],
    correctOptionIndex: 2,
  },
  {
    id: 102,
    text: "How often does Part-145 require recurring training for personnel?",
    options: ["Every year", "At least every 2 years", "Every 3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "What is the maximum take-off mass for aeroplanes under Part-ML?",
    options: ["1,200 kg", "2,730 kg", "3,175 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "What is the maximum take-off mass for rotorcraft under Part-ML?",
    options: ["1,200 kg", "2,730 kg", "3,175 kg"],
    correctOptionIndex: 0,
  },
  {
    id: 105,
    text: "Who is responsible for the continuing airworthiness of the aircraft under ML.A.201?",
    options: ["The maintenance organization", "The owner", "The manufacturer"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "What is Regulation (EU) No. 965/2012 commonly known as?",
    options: ["EASA Part-66", "EASA AIR OPS", "EASA Part-145"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "What does \"commercial operations\" refer to in this regulation?",
    options: ["Operations for training purposes", "Transportation of passengers, cargo, or mail for remuneration or hire", "Private flying activities"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "What does Regulation (EU) No. 1178/2011 address?",
    options: ["Maintenance organizations", "Air crew licensing", "Continuing airworthiness"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "Which Annex of Regulation 1178/2011 contains Part-FCL?",
    options: ["Annex I", "Annex II", "Annex III"],
    correctOptionIndex: 0,
  },
  {
    id: 110,
    text: "Which Annex contains Part-MED (medical requirements)?",
    options: ["Annex III", "Annex IV", "Annex V"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "When was Regulation (EU) No. 376/2014 adopted?",
    options: ["April 3, 2014", "June 29, 2015", "July 4, 2018"],
    correctOptionIndex: 0,
  },
  {
    id: 112,
    text: "What directive did Regulation 376/2014 supersede?",
    options: ["Directive 2003/42/EC", "Directive 2014/30/EU", "Directive 2008/100/EC"],
    correctOptionIndex: 0,
  },
  {
    id: 113,
    text: "Within how many hours must occurrences be reported?",
    options: ["24 hours", "48 hours", "72 hours"],
    correctOptionIndex: 2,
  },
  {
    id: 114,
    text: "What is the European Central Repository?",
    options: ["A library of aviation documents", "A database where all occurrence reports collected in the EU are stored", "A training facility for investigators"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "Within how many days must occurrence reports be transferred to the European Central Repository?",
    options: ["14 days", "30 days", "60 days"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "What is \"hard law\" in EASA regulations?",
    options: ["Recommendations and guidance", "Mandatory regulations established by EU Commission, Parliament, or Council", "Certification specifications"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "What is \"soft law\" in EASA regulations?",
    options: ["Regulations that are optional for member states", "AMC, GM, and CS which are not mandatory", "Only guidance material"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "What does AMC stand for?",
    options: ["Aircraft Maintenance Criteria", "Acceptable Means of Compliance", "Aviation Management Committee"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "If an applicant correctly implements an AMC issued by EASA, what happens?",
    options: ["Their compliance is guaranteed to be accepted", "They must still seek individual approval", "They may be subject to additional audits"],
    correctOptionIndex: 0,
  },
  {
    id: 120,
    text: "What does GM stand for?",
    options: ["General Maintenance", "Guidance Material", "Government Mandate"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "What does Subpart A of each Part typically contain?",
    options: ["Requirements for competent authorities", "Implementing rules for personnel and organizations", "Definitions only"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "What does Subpart B of each Part typically contain?",
    options: ["Requirements for personnel", "Implementing rules for competent authorities", "Certification specifications"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "Where are EASA regulations published?",
    options: ["Only on the EASA website", "In the Official Journal of the European Union", "In national aviation authority publications"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "What is EUR-Lex?",
    options: ["An aircraft leasing company", "A website providing access to EU laws", "A training organization database"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "What is the maximum take-off mass defining a complex aeroplane?",
    options: ["2,730 kg", "3,175 kg", "5,700 kg"],
    correctOptionIndex: 2,
  },
  {
    id: 126,
    text: "What is the maximum take-off mass defining a complex helicopter?",
    options: ["1,200 kg", "3,175 kg", "5,700 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "What passenger seating configuration defines a complex aeroplane?",
    options: ["More than 9 passengers", "More than 12 passengers", "More than 19 passengers"],
    correctOptionIndex: 2,
  },
  {
    id: 128,
    text: "Which regulations stipulate the requirement to implement SMS?",
    options: ["Only Regulation 965/2012", "Regulations (EU) 1321/2014 and 748/2012", "Only Regulation 1178/2011"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "Are SMS requirements introduced in Part-147 (Training Organisations)?",
    options: ["Yes, fully implemented", "No, not introduced in Part-147", "Only for type training"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "Are SMS requirements introduced in Part-CAO?",
    options: ["Yes", "No, not introduced in Part-CAO", "Only for commercial operations"],
    correctOptionIndex: 1,
  },
];
