export const instrumentSystemsQuestions = [
  { id: 1, text: "What does the flight environment data system comprise?", options: ["Pitot-static system and outside air temperature sensing", "Only pitot pressure measurement", "Radar and GPS systems"], correctOptionIndex: 0 },
  { id: 2, text: "Which of the following is NOT determined from atmospheric raw data?", options: ["Altitude", "Aircraft weight", "Airspeed"], correctOptionIndex: 1 },
  { id: 3, text: "In a basic aircraft system, the Pitot tube is connected directly to which instrument?", options: ["Altimeter", "Airspeed indicator", "Vertical speed indicator"], correctOptionIndex: 1 },
  { id: 4, text: "How many flush static ports are typically installed on a small jet aircraft?", options: ["One on the fuselage", "Two, one on either side of the fuselage", "Four, two on each side"], correctOptionIndex: 1 },
  { id: 5, text: "What is the purpose of the alternate static air valve?", options: ["To increase static pressure", "To supply static air if outside static ports become blocked with ice", "To drain water from the system"], correctOptionIndex: 1 },
  { id: 6, text: "Where does the alternate static air come from?", options: ["Outside the aircraft", "Directly from the cockpit", "From the engine compressor"], correctOptionIndex: 1 },
  { id: 7, text: "What is an altitude encoder also known as?", options: ["Pressure transmitter", "Blind encoder", "Static converter"], correctOptionIndex: 1 },
  { id: 8, text: "What does the altitude encoder convert air pressure signals into?", options: ["Visual altitude display", "Digitally encoded altitude", "Radio signals"], correctOptionIndex: 1 },
  { id: 9, text: "When should draining pitot-static lines be required?", options: ["Every pre-flight inspection", "Only if airspeed indicator or altimeter appears erratic", "After every flight"], correctOptionIndex: 1 },
  { id: 10, text: "How are static ports and pitot tubes protected from ice?", options: ["By heating elements, controlled by a switch", "By chemical de-icing fluid", "By rubber covers"], correctOptionIndex: 0 },
  { id: 11, text: "In older large aircraft, what is the purpose of the third (auxiliary) pitot tube?", options: ["Only for the co-pilot instruments", "For autopilot, overspeed warning, and flight recorder", "For cabin pressurization"], correctOptionIndex: 1 },
  { id: 12, text: "How are static ports configured in large aircraft systems?", options: ["Single port on the nose", "Duplicated interconnected pairs on left and right sides", "Four ports all on the same side"], correctOptionIndex: 1 },
  { id: 13, text: "One pair of static ports provides primary equalized ambient pressure to which instruments?", options: ["Only the altimeter", "Airspeed indicator, vertical speed indicator, and altimeter", "Only the airspeed indicator"], correctOptionIndex: 1 },
  { id: 14, text: "What provides pressure to the co-pilot instruments in a large aircraft system?", options: ["The same pair as the captain's instruments", "The other pair of static ports", "A separate pitot tube only"], correctOptionIndex: 1 },
  { id: 15, text: "How are alternate static ports activated?", options: ["Automatically", "Switched by the pilots", "By a separate valve in the tail"], correctOptionIndex: 1 },
  { id: 16, text: "Newer aircraft with EFIS have what component instead of direct instrument connections?", options: ["Mechanical computer", "Air data computer (ADC)", "Vacuum pump"], correctOptionIndex: 1 },
  { id: 17, text: "In modern aircraft with EFIS, where are pitot and static pressures connected?", options: ["Directly to the display units", "To an air data computer or air data module", "To the attitude indicator"], correctOptionIndex: 1 },
  { id: 18, text: "What does the air data computer convert pressure signals into?", options: ["Mechanical movements", "Digital electronic data", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 19, text: "What does the air data computer compute for display on EFIS?", options: ["Only altitude", "Altitude, airspeed, and vertical speed", "Only heading"], correctOptionIndex: 1 },
  { id: 20, text: "Where is the data from the ADC displayed in a glass cockpit?", options: ["On a separate mechanical gauge", "On the primary flight display (PFD)", "Only on the engine display"], correctOptionIndex: 1 },
  { id: 21, text: "An altimeter is essentially what type of instrument?", options: ["Thermometer", "Barometer that measures absolute air pressure", "Hygrometer"], correctOptionIndex: 1 },
  { id: 22, text: "What causes the pressure that the altimeter measures?", options: ["The aircraft's engine", "The weight of the air above the instrument", "The aircraft's speed"], correctOptionIndex: 1 },
  { id: 23, text: "As an aircraft climbs above the earth's surface, what happens to absolute pressure?", options: ["It increases", "It decreases", "It remains constant"], correctOptionIndex: 1 },
  { id: 24, text: "The standard altimeter uses what component to measure pressure changes?", options: ["Liquid mercury column", "Evacuated bellows", "Bimetallic strip"], correctOptionIndex: 1 },
  { id: 25, text: "What measures the expansion and contraction of the bellows in an altimeter?", options: ["Electronic sensors", "Gears and levers", "Capacitors"], correctOptionIndex: 1 },
  { id: 26, text: "Is the pressure lapse rate linear with altitude?", options: ["Yes, it is perfectly linear", "No, it is not linear", "It is linear only above 10,000 feet"], correctOptionIndex: 1 },
  { id: 27, text: "How are altimeter bellows designed to compensate for non-linear pressure changes?", options: ["With electronic correction circuits", "With corrugations that allow linear expansion with altitude change", "With temperature compensation coils"], correctOptionIndex: 1 },
  { id: 28, text: "Approximately how much pressure decrease per 1,000 feet near sea level?", options: ["10 inches of mercury", "One inch of mercury", "5 inches of mercury"], correctOptionIndex: 1 },
  { id: 29, text: "The aneroid altimeter is calibrated according to which standard?", options: ["Local weather conditions", "International Standard Atmosphere (ISA)", "Pilot's preference"], correctOptionIndex: 1 },
  { id: 30, text: "What is the small window on an altimeter face called that displays reference pressure?", options: ["Setting window", "Kollsman window", "Baro port"], correctOptionIndex: 1 },
  { id: 31, text: "What units are used for reference pressure in Canada and the US?", options: ["Millibars", "Inches of mercury", "Hectopascals"], correctOptionIndex: 1 },
  { id: 32, text: "What units are used for reference pressure in most countries outside the US?", options: ["Inches of mercury", "Hectopascals (previously millibars)", "Pounds per square inch"], correctOptionIndex: 1 },
  { id: 33, text: "A sensitive pneumatic altimeter uses what to drive the pointers?", options: ["Electric motor", "A stack of bellows", "Hydraulic pressure"], correctOptionIndex: 1 },
  { id: 34, text: "Why do jet aircraft often require instrument panel vibrators?", options: ["To warn pilots of malfunctions", "To keep the altimeter reading accurately due to lack of engine vibration", "To provide power to the instrument"], correctOptionIndex: 1 },
  { id: 35, text: "The sensitive altimeter employs a minimum of how many aneroid capsules?", options: ["One", "Two", "Four"], correctOptionIndex: 1 },
  { id: 36, text: "What is fitted within the mechanical linkage of an altimeter to compensate for temperature changes?", options: ["Heating element", "Bi-metallic insert", "Cooling coil"], correctOptionIndex: 1 },
  { id: 37, text: "As the aircraft climbs and air pressure falls, what happens to the capsules?", options: ["They contract", "They expand", "They remain unchanged"], correctOptionIndex: 1 },
  { id: 38, text: "As the aircraft descends and static pressure increases, what happens to the capsules?", options: ["They expand", "They contract", "They rotate"], correctOptionIndex: 1 },
  { id: 39, text: "What mechanism allows adjustment of the altimeter to indicate zero feet on the ground?", options: ["Zero adjustment screw", "Barometric subscale mechanism", "Pointer calibration knob"], correctOptionIndex: 1 },
  { id: 40, text: "Pressure altitude is the altitude above what datum?", options: ["Mean sea level", "Standard datum 1013.25 hPa", "Ground level"], correctOptionIndex: 1 },
  { id: 41, text: "What is the standard pressure datum in inches of mercury?", options: ["29.00 inches", "29.92 inches", "30.00 inches"], correctOptionIndex: 1 },
  { id: 42, text: "Density altitude is pressure altitude corrected for what?", options: ["Humidity", "Temperature", "Wind speed"], correctOptionIndex: 1 },
  { id: 43, text: "When temperature rises above standard, what happens to density altitude?", options: ["It decreases", "It increases", "It remains the same"], correctOptionIndex: 1 },
  { id: 44, text: "QNH setting allows the altimeter to measure what?", options: ["Height above ground", "Altitude above sea level", "Pressure altitude"], correctOptionIndex: 1 },
  { id: 45, text: "What does the airport control tower give to pilots for altimeter setting?", options: ["Field elevation", "Local barometric pressure corrected to sea level", "Standard pressure"], correctOptionIndex: 1 },
  { id: 46, text: "When the aircraft is on the ground with local altimeter setting, what should it indicate?", options: ["Zero feet", "Surveyed elevation of the parking space", "Field pressure altitude"], correctOptionIndex: 1 },
  { id: 47, text: "STD setting uses what barometric pressure?", options: ["Local sea level pressure", "29.92 inches of mercury or 1013.2 hPa", "Field pressure"], correctOptionIndex: 1 },
  { id: 48, text: "Flight Level 320 corresponds to what pressure altitude?", options: ["3,200 feet", "32,000 feet", "320,000 feet"], correctOptionIndex: 1 },
  { id: 49, text: "QFE setting causes the altimeter to show what on the ground?", options: ["Sea level altitude", "Zero", "Field elevation above sea level"], correctOptionIndex: 1 },
  { id: 50, text: "What has largely replaced the QFE baro setting?", options: ["GPS altitude", "Radio altimeters", "Pressure altimeters"], correctOptionIndex: 1 },
  { id: 51, text: "Altitude is defined as vertical distance between aircraft and what?", options: ["The terrain", "Sea level", "The nearest cloud"], correctOptionIndex: 1 },
  { id: 52, text: "Height is defined as vertical distance between aircraft and what?", options: ["Sea level", "The terrain", "Standard datum"], correctOptionIndex: 1 },
  { id: 53, text: "The rate-of-climb indicator is more properly called what?", options: ["Climb meter", "Vertical speed indicator", "Altitude rate indicator"], correctOptionIndex: 1 },
  { id: 54, text: "What is the operating mechanism of a VSI?", options: ["Electric motor", "Bellows or pressure capsule", "Gyroscope"], correctOptionIndex: 1 },
  { id: 55, text: "Unlike an altimeter capsule, the VSI capsule is:", options: ["Evacuated and sealed", "Vented to the instrument case through a calibrated leak", "Filled with fluid"], correctOptionIndex: 1 },
  { id: 56, text: "What is the calibrated leak in the VSI called?", options: ["Venturi", "Diffuser", "Orifice"], correctOptionIndex: 1 },
  { id: 57, text: "When an aircraft begins to climb, what happens to pressure inside the VSI capsule?", options: ["It increases", "It decreases below case pressure", "It equalizes immediately"], correctOptionIndex: 1 },
  { id: 58, text: "When the aircraft climbs, does the capsule compress or expand?", options: ["Expand", "Compress", "Remain unchanged"], correctOptionIndex: 1 },
  { id: 59, text: "When the aircraft levels off, what happens to pressures inside and outside the capsule?", options: ["They remain different", "They equalize", "They reverse"], correctOptionIndex: 1 },
  { id: 60, text: "When leveled off, what does the indicator show?", options: ["Last rate of climb", "Zero rate of change", "Small positive rate"], correctOptionIndex: 1 },
  { id: 61, text: "IVSI is also referred to as what?", options: ["Rapid VSI", "Inertial lead vertical speed indicator (ILVSI)", "Advanced VSI"], correctOptionIndex: 1 },
  { id: 62, text: "The IVSI is fitted with what additional unit?", options: ["Heating element", "Accelerometer unit", "GPS receiver"], correctOptionIndex: 1 },
  { id: 63, text: "What does the accelerometer unit in an IVSI consist of?", options: ["Electronic gyroscopes", "Two small cylinders or dashpots with inertial pistons", "Piezoelectric crystals"], correctOptionIndex: 1 },
  { id: 64, text: "How are the pistons in the accelerometer held in balance?", options: ["By magnets", "By springs and their own mass", "By hydraulic pressure"], correctOptionIndex: 1 },
  { id: 65, text: "When the aircraft noses over to begin a descent, what does the accelerometer piston do?", options: ["Moves downward", "Moves upward", "Stays stationary"], correctOptionIndex: 1 },
  { id: 66, text: "The movement of the accelerometer piston instantaneously does what?", options: ["Decreases capsule pressure", "Increases pressure inside the capsule", "Has no effect on pressure"], correctOptionIndex: 1 },
  { id: 67, text: "The airspeed indicator measures what pressure differential?", options: ["Static vs. cabin pressure", "Pitot pressure vs. static pressure", "Dynamic vs. impact pressure"], correctOptionIndex: 1 },
  { id: 68, text: "The formula PT = ½ρV² + PS represents what?", options: ["Static pressure formula", "Total pressure formula", "Dynamic pressure only"], correctOptionIndex: 1 },
  { id: 69, text: "In the formula, what does PT represent?", options: ["Static pressure", "Total or pitot pressure", "Temperature pressure"], correctOptionIndex: 1 },
  { id: 70, text: "In the formula, what does PS represent?", options: ["Pitot pressure", "Static pressure", "Speed pressure"], correctOptionIndex: 1 },
  { id: 71, text: "In the formula, what does ρ represent?", options: ["Pressure ratio", "Air density", "Relative humidity"], correctOptionIndex: 1 },
  { id: 72, text: "In the formula, what does V represent?", options: ["Ground speed", "True airspeed", "Indicated airspeed"], correctOptionIndex: 1 },
  { id: 73, text: "Rearranging the formula, pitot minus static pressure equals what?", options: ["Static pressure", "½ρV² (dynamic pressure)", "Total pressure"], correctOptionIndex: 1 },
  { id: 74, text: "An airspeed indicator is what type of pressure gauge?", options: ["Absolute pressure gauge", "Differential pressure gauge", "Gauge pressure gauge"], correctOptionIndex: 1 },
  { id: 75, text: "In an ASI, where is pitot pressure taken?", options: ["Into the instrument case", "Into the capsule", "Into both capsule and case"], correctOptionIndex: 1 },
  { id: 76, text: "In an ASI, where is static pressure connected?", options: ["Into the capsule only", "To the inside of the case", "To the outside of the instrument"], correctOptionIndex: 1 },
  { id: 77, text: "The principle of what point is used in airspeed measurement?", options: ["Venturi point", "Stagnation point", "Boundary point"], correctOptionIndex: 1 },
  { id: 78, text: "In the ASI, static pressure is fed to both sides of the capsule to achieve what?", options: ["Increase sensitivity", "Cancel out static pressure effect", "Provide damping"], correctOptionIndex: 1 },
  { id: 79, text: "The airspeed indicator is actually a measure of what?", options: ["True airspeed", "Dynamic pressure", "Static pressure"], correctOptionIndex: 1 },
  { id: 80, text: "Stalling speed is always measured in what type of airspeed?", options: ["True airspeed", "Indicated airspeed", "Ground speed"], correctOptionIndex: 1 },
  { id: 81, text: "For the same weight, stalling speed remains fairly constant regardless of what?", options: ["Temperature only", "Altitude", "Wind direction"], correctOptionIndex: 1 },
  { id: 82, text: "Indicated airspeed (IAS) is the dynamic pressure calibrated to what conditions?", options: ["Current altitude conditions", "ISA mean sea level conditions", "Standard temperature at altitude"], correctOptionIndex: 1 },
  { id: 83, text: "Calibrated airspeed (CAS) is IAS corrected for what?", options: ["Density only", "Instrument and position errors", "Temperature only"], correctOptionIndex: 1 },
  { id: 84, text: "CAS is sometimes called what, especially when air data computers are involved?", options: ["True airspeed", "Computed airspeed", "Equivalent airspeed"], correctOptionIndex: 1 },
  { id: 85, text: "Equivalent airspeed (EAS) is CAS corrected for what?", options: ["Position error", "Compressibility", "Instrument error"], correctOptionIndex: 1 },
  { id: 86, text: "Compressibility becomes significant at airspeeds above what value?", options: ["100 knots", "200 knots", "500 knots"], correctOptionIndex: 1 },
  { id: 87, text: "True airspeed (TAS) is EAS corrected for what?", options: ["Compressibility", "Density", "Position error"], correctOptionIndex: 1 },
  { id: 88, text: "What is the ISA sea level density?", options: ["0.001 kg/m³", "1.225 kg/m³", "10 kg/m³"], correctOptionIndex: 1 },
  { id: 89, text: "At 40,000 feet, the density ratio is approximately what?", options: ["1.0", "0.25", "0.5"], correctOptionIndex: 1 },
  { id: 90, text: "At 40,000 feet, TAS is how many times EAS?", options: ["Equal to EAS", "Twice EAS", "Half EAS"], correctOptionIndex: 1 },
  { id: 91, text: "The memory aid ICE-T stands for what sequence?", options: ["Indicated - Computed - Estimated - True", "Indicated - Calibrated - Equivalent - True", "Indicated - Corrected - Effective - True"], correctOptionIndex: 1 },
  { id: 92, text: "Ground speed can be determined by the vector sum of what two factors?", options: ["Altitude and heading", "True airspeed and wind speed/direction", "Indicated airspeed and temperature"], correctOptionIndex: 1 },
  { id: 93, text: "A headwind has what effect on ground speed?", options: ["Adds to ground speed", "Subtracts from ground speed", "Has no effect"], correctOptionIndex: 1 },
  { id: 94, text: "A tailwind has what effect on ground speed?", options: ["Subtracts from ground speed", "Adds to ground speed", "Has no effect"], correctOptionIndex: 1 },
  { id: 95, text: "On a light aircraft, what speed is usually shown in the cockpit?", options: ["TAS", "IAS", "GS"], correctOptionIndex: 1 },
  { id: 96, text: "On a large transport aircraft, what is the primary airspeed indication on the PFD?", options: ["TAS", "IAS", "GS"], correctOptionIndex: 1 },
  { id: 97, text: "On the navigation display, what speeds are typically shown?", options: ["IAS only", "TAS and GS", "CAS only"], correctOptionIndex: 1 },
  { id: 98, text: "Mach number compares aircraft speed with what?", options: ["Speed of light", "Speed of sound", "Speed of wind"], correctOptionIndex: 1 },
  { id: 99, text: "Mach 1 occurs when the aircraft is flying at what speed?", options: ["Twice the speed of sound", "The speed of sound", "Half the speed of sound"], correctOptionIndex: 1 },
  { id: 100, text: "A typical Mach meter consists of how many capsule assemblies?", options: ["One", "Two placed at 90° to each other", "Three placed at 120° to each other"], correctOptionIndex: 1 },
  { id: 101, text: "The first capsule unit in a Mach meter is what type?", options: ["Aneroid capsule", "Airspeed capsule", "Temperature capsule"], correctOptionIndex: 0 },
  { id: 102, text: "The second capsule unit in a Mach meter is what type?", options: ["Airspeed capsule", "Aneroid capsule responding to static pressure", "Pitot capsule"], correctOptionIndex: 1 },
  { id: 103, text: "The critical Mach number is indicated by what on the Mach meter?", options: ["Red line", "Specially shaped lubber mark", "Digital readout"], correctOptionIndex: 1 },
  { id: 104, text: "A gyroscope is a spinning wheel in which the axis of rotation is free to do what?", options: ["Remain fixed relative to the aircraft", "Assume any orientation by itself", "Rotate only in one plane"], correctOptionIndex: 1 },
  { id: 105, text: "Gyroscopes are useful for measuring or maintaining what?", options: ["Temperature", "Orientation", "Pressure"], correctOptionIndex: 1 },
  { id: 106, text: "A gyroscope is mounted in what type of pivoted supports?", options: ["Bearings", "Gimbals", "Housings"], correctOptionIndex: 1 },
  { id: 107, text: "A set of three gimbals allows the wheel to have orientation independent of what?", options: ["Gravity", "Its support orientation in space", "Magnetic fields"], correctOptionIndex: 1 },
  { id: 108, text: "The axle of the spinning wheel defines what?", options: ["Gimbal axis", "Spin axis", "Precession axis"], correctOptionIndex: 1 },
  { id: 109, text: "The rotor possesses how many degrees of rotational freedom with three gimbals?", options: ["Two", "Three", "One"], correctOptionIndex: 1 },
  { id: 110, text: "The rotor of a gyroscopic instrument must rotate at what speed to maintain rigidity?", options: ["Low rpm", "Very high rpm", "Variable rpm"], correctOptionIndex: 1 },
  { id: 111, text: "Rigidity in a gyroscope is also called what?", options: ["Momentum", "Inertia", "Force"], correctOptionIndex: 1 },
  { id: 112, text: "Which factor does NOT influence gyroscopic rigidity?", options: ["Mass of the rotor", "Color of the rotor", "Rpm or angular velocity"], correctOptionIndex: 1 },
  { id: 113, text: "What is precession in a gyroscope?", options: ["The rotor speeding up", "Apparent displacement of force 90° in direction of motion", "The rotor stopping"], correctOptionIndex: 1 },
  { id: 114, text: "When force is applied to a spinning gyro rim, the rotor tilts as if the force was where?", options: ["At the same point", "90° further in the direction of motion", "180° opposite"], correctOptionIndex: 1 },
  { id: 115, text: "Which is NOT a gyro instrument?", options: ["Heading indicator", "Magnetic compass", "Attitude indicator"], correctOptionIndex: 1 },
  { id: 116, text: "Each gyro instrument contains a gyro rotor driven by what?", options: ["Only electricity", "Air or electricity", "Only air"], correctOptionIndex: 1 },
  { id: 117, text: "The attitude indicator is also known as what?", options: ["Direction indicator", "Artificial horizon", "Turn coordinator"], correctOptionIndex: 1 },
  { id: 118, text: "The purpose of the attitude indicator is to present what to the pilot?", options: ["Heading information", "Continuous picture of aircraft attitude relative to earth's surface", "Airspeed"], correctOptionIndex: 1 },
  { id: 119, text: "The small knob near the bottom of the attitude indicator is used for what?", options: ["Setting heading", "Vertical adjustment of the miniature aircraft", "Adjusting brightness"], correctOptionIndex: 1 },
  { id: 120, text: "The magnetic compass is prone to errors due to what factors?", options: ["Only temperature", "Acceleration and turbulence", "Only pressure changes"], correctOptionIndex: 1 },
  { id: 121, text: "The direction indicator is based on what principle?", options: ["Magnetic sensing", "Gyroscopic rigidity", "Pressure measurement"], correctOptionIndex: 1 },
  { id: 122, text: "The turn coordinator indicates what?", options: ["Angle of bank", "Rate of turn", "Slip only"], correctOptionIndex: 1 },
  { id: 123, text: "What does the slip indicator in a turn coordinator show?", options: ["Rate of turn", "Sideways forces", "Airspeed"], correctOptionIndex: 1 },
  { id: 124, text: "In a coordinated turn, where should the slip indicator show?", options: ["Full left", "In the centre", "Full right"], correctOptionIndex: 1 },
  { id: 125, text: "Pitch attitudes are depicted by the miniature aircraft's movement relative to what?", options: ["Compass card", "Horizon bar", "Airspeed scale"], correctOptionIndex: 1 },
  { id: 126, text: "At least how many pitch reference lines are incorporated into the attitude indicator?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 127, text: "The bank indicator has index marks spaced at what intervals?", options: ["5° intervals", "10° intervals through 30°", "15° intervals"], correctOptionIndex: 1 },
  { id: 128, text: "The sky is represented by what color on the attitude indicator?", options: ["Black", "Light blue", "Green"], correctOptionIndex: 1 },
  { id: 129, text: "The earth is shown by what color on the attitude indicator?", options: ["Blue", "Black or brown shading", "White"], correctOptionIndex: 1 },
  { id: 130, text: "An erection mechanism automatically rights the gyro when what occurs?", options: ["Power failure", "Precession due to manoeuvres or friction", "Overheating"], correctOptionIndex: 1 },
  { id: 131, text: "Warning flags on an attitude indicator may indicate what?", options: ["Low altitude", "Inadequate electrical power or gyro problem", "High airspeed"], correctOptionIndex: 1 },
  { id: 132, text: "The attitude indicator uses what type of gyro?", options: ["Rate gyro", "Vertical gyro", "Directional gyro"], correctOptionIndex: 1 },
  { id: 133, text: "The vertical gyro senses the relationship between what axes and a vertical line?", options: ["Only pitch", "Pitch and roll axes", "Only yaw"], correctOptionIndex: 1 },
  { id: 134, text: "The vertical gyro has how many degrees of freedom?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 135, text: "The axle of the vertical gyro wheel is always in what orientation?", options: ["Horizontal", "Vertical", "Variable"], correctOptionIndex: 1 },
  { id: 136, text: "Vertical gyro signals are used for what purposes?", options: ["Only artificial horizons", "Artificial horizons, autopilots, flight directors, and weather radar stabilization", "Only autopilots"], correctOptionIndex: 1 },
  { id: 137, text: "The heading indicator was formerly called what?", options: ["Magnetic compass", "Directional gyro", "Turn indicator"], correctOptionIndex: 1 },
  { id: 138, text: "The heading indicator uses what gyroscopic principle?", options: ["Precession", "Rigidity", "Flexibility"], correctOptionIndex: 1 },
  { id: 139, text: "Real precession and apparent precession may cause the heading indicator to do what?", options: ["Stop", "Drift", "Reverse"], correctOptionIndex: 1 },
  { id: 140, text: "Because the heading indicator has no direction-seeking qualities, it must be set to agree with what?", options: ["GPS", "Magnetic compass", "True north"], correctOptionIndex: 1 },
  { id: 141, text: "When should the heading indicator be set to agree with the magnetic compass?", options: ["During turns", "On ground or straight-and-level unaccelerated flight", "During climb"], correctOptionIndex: 1 },
  { id: 142, text: "In a light aircraft, how often should the heading indicator be checked against the magnetic compass?", options: ["Every 5 minutes", "At least every 15 minutes", "Every hour"], correctOptionIndex: 1 },
  { id: 143, text: "The heading indicator gyroscope is spun how?", options: ["Only by air", "Electrically or using filtered air flow", "Only by electricity"], correctOptionIndex: 1 },
  { id: 144, text: "In a vertical card directional gyro, what replaces the simple lubber line?", options: ["A dot", "A symbol of an aircraft on the face", "An arrow"], correctOptionIndex: 1 },
  { id: 145, text: "The HSI is normally mounted below what instrument?", options: ["Airspeed indicator", "Artificial horizon", "Altimeter"], correctOptionIndex: 1 },
  { id: 146, text: "The HSI combines a heading indicator with what display?", options: ["ADF display", "VOR-ILS display", "DME display"], correctOptionIndex: 1 },
  { id: 147, text: "On the HSI, the aircraft is represented by what?", options: ["A dot", "A schematic figure in the centre", "An arrow"], correctOptionIndex: 1 },
  { id: 148, text: "The heading indicator on an HSI usually slaves to what?", options: ["GPS", "A remote compass", "True north"], correctOptionIndex: 1 },
  { id: 149, text: "On a conventional VOR indicator, left-right must be interpreted in context of what?", options: ["Heading", "Selected course", "Altitude"], correctOptionIndex: 1 },
  { id: 150, text: "On an HSI, if the triangular arrowhead points to the same side as the course selector, it means what?", options: ["FROM", "TO", "OFF"], correctOptionIndex: 1 },
  { id: 151, text: "When an attitude director incorporates command bars, it is known as what?", options: ["HSI", "ADI (Attitude Director Indicator)", "EHSI"], correctOptionIndex: 1 },
  { id: 152, text: "Command bars on an ADI are operated by what?", options: ["Autopilot only", "Flight director", "Heading bug"], correctOptionIndex: 1 },
  { id: 153, text: "The most modern ADI displays are what type?", options: ["CRT", "Solid state LCD (EADI)", "Mechanical"], correctOptionIndex: 1 },
  { id: 154, text: "AHRS consists of sensors on how many axes?", options: ["One", "Three", "Two"], correctOptionIndex: 1 },
  { id: 155, text: "AHRS provides attitude information including what parameters?", options: ["Only roll", "Roll, pitch, and yaw", "Only heading"], correctOptionIndex: 1 },
  { id: 156, text: "AHRS are designed to replace what type of instruments?", options: ["Pressure instruments", "Traditional mechanical gyroscopic flight instruments", "Magnetic compasses"], correctOptionIndex: 1 },
  { id: 157, text: "AHRS information is sent to what sections of an EFIS?", options: ["Engine display", "Attitude and heading sections", "Navigation map only"], correctOptionIndex: 1 },
  { id: 158, text: "AHRS can be combined with air data computers to form what?", options: ["GPS system", "ADAHRS (Air Data, Attitude and Heading Reference System)", "TCAS"], correctOptionIndex: 1 },
  { id: 159, text: "To provide reference to Earth's magnetic field, AHRS must be connected to what?", options: ["GPS", "Magnetometer", "Flux capacitor"], correctOptionIndex: 1 },
  { id: 160, text: "The turn and slip indicator actually contains how many instruments in one housing?", options: ["One", "Two (gyro and inclinometer)", "Three"], correctOptionIndex: 1 },
  { id: 161, text: "The inclinometer is a curved glass tube filled with what?", options: ["Mercury", "Damping liquid", "Air"], correctOptionIndex: 1 },
  { id: 162, text: "What rides inside the curved glass tube of the inclinometer?", options: ["A steel ball", "A black glass ball", "A bubble"], correctOptionIndex: 1 },
  { id: 163, text: "When the aircraft is perfectly level, where does the ball rest?", options: ["At either end", "In the bottom centre of the tube", "At the top"], correctOptionIndex: 1 },
  { id: 164, text: "In flight, the ball indicates the relationship between what two forces?", options: ["Lift and drag", "Gravity (G) and centrifugal force (Z)", "Thrust and weight"], correctOptionIndex: 1 },
  { id: 165, text: "A coordinated turn is one where what condition exists?", options: ["Ball is at full left", "Bank angle is correct for rate of turn, ball remains centred", "Ball is at full right"], correctOptionIndex: 1 },
  { id: 166, text: "The gyroscopic rotor in a turn and slip indicator has its spin axis parallel to what axis?", options: ["Longitudinal axis", "Lateral axis", "Vertical axis"], correctOptionIndex: 1 },
  { id: 167, text: "The single gimbal axis in a turn and slip indicator is parallel to what axis?", options: ["Lateral axis", "Longitudinal axis", "Vertical axis"], correctOptionIndex: 1 },
  { id: 168, text: "A centring spring holds the gimbal level when what condition exists?", options: ["In a turn", "No outside force acting on it", "During climb"], correctOptionIndex: 1 },
  { id: 169, text: "What smooths out the force and restricts gimbal tilt in a turn indicator?", options: ["Spring only", "Dashpot and calibrated spring", "Magnetic damping"], correctOptionIndex: 1 },
  { id: 170, text: "The mechanism of a turn coordinator is similar to turn and slip, but its gimbal axis is tilted how many degrees?", options: ["15 degrees", "About 30 degrees", "45 degrees"], correctOptionIndex: 1 },
  { id: 171, text: "The tilt of the turn coordinator gyro allows it to precess when the aircraft does what?", options: ["Only yaws", "Rolls as well as yaws", "Only pitches"], correctOptionIndex: 1 },
  { id: 172, text: "The turn coordinator uses what type of indicator instead of a needle?", options: ["A digital readout", "A small symbolic aircraft", "A vertical tape"], correctOptionIndex: 1 },
  { id: 173, text: "A standard rate turn for light aircraft is defined as how many degrees per second?", options: ["2° per second", "3° per second", "6° per second"], correctOptionIndex: 1 },
  { id: 174, text: "A 2-minute turn completes a 360° turn in how long?", options: ["1 minute", "2 minutes", "4 minutes"], correctOptionIndex: 1 },
  { id: 175, text: "Rate one turn is equal to how many degrees per minute?", options: ["90°/minute", "180°/minute", "360°/minute"], correctOptionIndex: 1 },
  { id: 176, text: "For heavy aircraft, a standard rate turn is a how many minute turn?", options: ["2-minute", "4-minute", "6-minute"], correctOptionIndex: 1 },
  { id: 177, text: "A rate half turn is how many degrees per second?", options: ["1° per second", "1.5° per second", "3° per second"], correctOptionIndex: 0 },
  { id: 178, text: "The direct reading compass is also known by what names?", options: ["Flux gate, gyro compass", "Magnetic compass, standby compass, whisky compass, 'E' type compass", "Remote compass, slaved compass"], correctOptionIndex: 1 },
  { id: 179, text: "The main body of a direct reading compass is made of what material?", options: ["Steel", "Cast aluminium", "Plastic"], correctOptionIndex: 1 },
  { id: 180, text: "One end of the compass housing is covered with what?", options: ["Steel plate", "Glass lens", "Plastic cover"], correctOptionIndex: 1 },
  { id: 181, text: "What is the vertical reference mark across the glass lens called?", options: ["Index line", "Lubber line", "Reference mark"], correctOptionIndex: 1 },
  { id: 182, text: "Inside the housing, what does the small brass float ride on?", options: ["Ball bearings", "A steel pivot in a jewel post", "Fluid pressure"], correctOptionIndex: 1 },
  { id: 183, text: "How many marks are around the full 360° of the dial?", options: ["18 marks", "36 marks", "72 marks"], correctOptionIndex: 1 },
  { id: 184, text: "Zero degrees on the compass is what direction?", options: ["East", "North", "South"], correctOptionIndex: 1 },
  { id: 185, text: "What is soldered to the bottom of the float, aligned with north and south?", options: ["Brass weights", "Two small bar-type permanent magnets", "Steel plates"], correctOptionIndex: 1 },
  { id: 186, text: "The compass housing is filled with what type of fluid?", options: ["Water", "Compass fluid similar to kerosene", "Alcohol"], correctOptionIndex: 1 },
  { id: 187, text: "The direct reading compass is accurate only under what conditions?", options: ["Only when level", "Aircraft horizontal, no acceleration, corrected with correction card", "Only when straight"], correctOptionIndex: 1 },
  { id: 188, text: "The direct reading compass requires electrical power for what purpose?", options: ["Operation", "Illumination at night only", "Damping"], correctOptionIndex: 1 },
  { id: 189, text: "A remote reading compass measures heading relative to what?", options: ["True north", "Earth's magnetic field", "GPS north"], correctOptionIndex: 1 },
  { id: 190, text: "Early analogue remote compass devices were called what?", options: ["Magnetometers", "Flux valves or flux gates", "Compass slaves"], correctOptionIndex: 1 },
  { id: 191, text: "Flux valves provided what type of signal proportional to magnetic field direction?", options: ["Single phase", "Three-phase", "DC signal"], correctOptionIndex: 1 },
  { id: 192, text: "The flux valve output is used to adjust what instrument?", options: ["Altimeter", "Gyroscope which provides heading change information", "Airspeed indicator"], correctOptionIndex: 1 },
  { id: 193, text: "On small aircraft without a flux valve, how often must the pilot adjust the heading indicator?", options: ["Once per flight", "Before take-off and at least every 15 minutes during flight", "Every 5 minutes"], correctOptionIndex: 1 },
  { id: 194, text: "Modern aircraft use what solid-state device for remote heading sensing?", options: ["Flux valve", "Magnetometer", "Gyro compass"], correctOptionIndex: 1 },
  { id: 195, text: "A magnetometer is also called what?", options: ["Flux gate", "Magnetic heading sensor or electronic compass", "Directional gyro"], correctOptionIndex: 1 },
  { id: 196, text: "The basic-T arrangement consists of how many flight instruments in a standardized pattern?", options: ["Three", "Four", "Six"], correctOptionIndex: 1 },
  { id: 197, text: "In the basic-T, where is the attitude indicator located?", options: ["Bottom centre", "Top centre", "Left side"], correctOptionIndex: 1 },
  { id: 198, text: "In the basic-T, where is the airspeed indicator located?", options: ["Right of attitude indicator", "Left of attitude indicator", "Below attitude indicator"], correctOptionIndex: 1 },
  { id: 199, text: "In the basic-T, where is the altimeter located?", options: ["Left of attitude indicator", "Right of attitude indicator", "Below attitude indicator"], correctOptionIndex: 1 },
  { id: 200, text: "In the basic-T, where is the heading indicator located?", options: ["Top centre", "Under the attitude indicator", "Left of attitude indicator"], correctOptionIndex: 1 },
  { id: 201, text: "Where is the magnetic compass typically located?", options: ["In the basic-T", "Above the instrument panel, often on windscreen centre post", "Below the glareshield"], correctOptionIndex: 1 },
  { id: 202, text: "Visual Flight Rules (VFR) require what minimum instruments?", options: ["Attitude indicator, heading indicator, altimeter", "Airspeed indicator, altimeter, compass", "Turn coordinator, VSI, clock"], correctOptionIndex: 1 },
  { id: 203, text: "Instrument Flight Rules (IFR) additionally require what gyroscopic instruments?", options: ["Only attitude indicator", "Attitude indicator, directional gyro, rate of turn indicator", "Only heading indicator"], correctOptionIndex: 1 },
  { id: 204, text: "The stall warning system is sensitive to what parameter?", options: ["Airspeed", "Aircraft's angle of attack", "Altitude"], correctOptionIndex: 1 },
  { id: 205, text: "Where is the lift detector switch located?", options: ["Trailing edge of the wing", "Leading edge of the wing", "Fuselage nose"], correctOptionIndex: 1 },
  { id: 206, text: "In normal flight, what forces the switch paddle down?", options: ["Spring pressure", "The airflow", "Centrifugal force"], correctOptionIndex: 1 },
  { id: 207, text: "At a pre-defined high angle of attack, what happens to the switch paddle?", options: ["It stays down", "Airflow approaches from beneath and lifts it up", "It vibrates"], correctOptionIndex: 1 },
  { id: 208, text: "When the paddle lifts, what happens to the electrical circuit?", options: ["It opens", "The switch closes the circuit", "It shorts out"], correctOptionIndex: 1 },
  { id: 209, text: "The audio warning can be either a screeching sound or what?", options: ["A bell", "A recorded voice saying \"Stall!\"", "A horn"], correctOptionIndex: 1 },
  { id: 210, text: "Larger aircraft use what system in addition to aural and visual annunciation?", options: ["Stick puller", "Stick shaker system", "Stick lock"], correctOptionIndex: 1 },
  { id: 211, text: "A stick shaker is designed to do what?", options: ["Increase control feel", "Rapidly and noisily vibrate the control yoke", "Lock the controls"], correctOptionIndex: 1 },
  { id: 212, text: "The stick shaker is connected to what part of the aircraft?", options: ["Rudder pedals", "Control column", "Throttles"], correctOptionIndex: 1 },
  { id: 213, text: "Angle of attack sensors can be mounted where?", options: ["Only on wings", "Fuselage or wing-mounted", "Only on tail"], correctOptionIndex: 1 },
  { id: 214, text: "When data indicates an imminent stall, the computer activates what?", options: ["Only an auditory alert", "Both stick shaker and auditory alert", "Only stick shaker"], correctOptionIndex: 1 },
  { id: 215, text: "The stick shaker consists of what components?", options: ["Hydraulic actuator", "Electric motor connected to unbalanced flywheel", "Solenoid and spring"], correctOptionIndex: 1 },
  { id: 216, text: "The shaking frequency matches what natural phenomenon?", options: ["Engine vibration", "Stick shaking from airflow separation in low-speed aircraft", "Turbulence"], correctOptionIndex: 1 },
  { id: 217, text: "Some stall protection systems also include what to automatically push forward on elevator?", options: ["Stick shaker", "Stick pusher system", "Auto throttle"], correctOptionIndex: 1 },
  { id: 218, text: "An angle of attack indicator uses a pickup similar to what?", options: ["Pitot tube", "Electric stall warning vane", "Static port"], correctOptionIndex: 1 },
  { id: 219, text: "Instead of a micro-switch, the vane moves what type of sensor?", options: ["Potentiometer", "Synchro position sensor", "Capacitor"], correctOptionIndex: 1 },
  { id: 220, text: "Angle of attack vanes are often called what?", options: ["Beta vanes", "Alpha (α) vanes", "Gamma vanes"], correctOptionIndex: 1 },
  { id: 221, text: "The alpha angle signal can be supplied to what computer?", options: ["Flight management computer", "Stall computer", "Air data computer"], correctOptionIndex: 1 },
  { id: 222, text: "What are 'alpha Prot' and 'alpha MAX' associated with?", options: ["Auto throttle systems", "Stall protection systems", "Autopilot modes"], correctOptionIndex: 1 },
  { id: 223, text: "EFIS stands for what?", options: ["Electronic Flight Information System", "Electronic Flight Instrument System", "Enhanced Flight Instrument System"], correctOptionIndex: 1 },
  { id: 224, text: "EFIS normally consists of what three components?", options: ["PFD, ND, EICAS", "PFD, MFD, EIS", "ADI, HSI, EICAS"], correctOptionIndex: 0 },
  { id: 225, text: "On a light aircraft, the EIS is normally integrated into what?", options: ["PFD", "MFD", "Standby instruments"], correctOptionIndex: 0 },
  { id: 226, text: "The first EFIS units used what type of display technology?", options: ["LED", "Cathode Ray Tube (CRT)", "Plasma"], correctOptionIndex: 1 },
  { id: 227, text: "What display technology is now exclusively used in EFIS?", options: ["CRT", "Liquid Crystal Display (LCD)", "OLED"], correctOptionIndex: 1 },
  { id: 228, text: "What is a common term for traditional mechanical instruments?", options: ["Glass cockpit", "Steam gauges", "Analogue dials"], correctOptionIndex: 1 },
  { id: 229, text: "The Garmin G1000 typically consists of how many display units?", options: ["One", "Two", "Four"], correctOptionIndex: 1 },
  { id: 230, text: "In a typical G1000, one display serves as PFD and the other as what?", options: ["EICAS", "Multi-function display (MFD)", "Standby display"], correctOptionIndex: 1 },
  { id: 231, text: "Both PFD and MFD have how many slots for SD memory cards?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 232, text: "The top SD card slot is used to update what database?", options: ["Terrain database", "Jeppesen aviation database (NavData)", "Obstacle database"], correctOptionIndex: 1 },
  { id: 233, text: "How often must the aviation database be updated for IFR GPS navigation?", options: ["Every 14 days", "Every 28 days", "Every 56 days"], correctOptionIndex: 1 },
  { id: 234, text: "The bottom SD card slot houses what databases?", options: ["NavData only", "World terrain and Jeppesen obstacle databases", "Airport diagrams only"], correctOptionIndex: 1 },
  { id: 235, text: "The PFD shows the basic six flight instruments in what configuration?", options: ["Circular pattern", "Basic-T configuration", "Linear pattern"], correctOptionIndex: 1 },
  { id: 236, text: "What small map can be enabled in the corner of the PFD?", options: ["Weather map", "Inset map", "Terrain map"], correctOptionIndex: 1 },
  { id: 237, text: "The buttons on the PFD are used to set what code?", options: ["VOR frequency", "Squawk code on the transponder", "GPS waypoint"], correctOptionIndex: 1 },
  { id: 238, text: "Reversionary mode on the PFD allows it to display what?", options: ["Only basic instruments", "Information normally shown on MFD", "Only engine gauges"], correctOptionIndex: 1 },
  { id: 239, text: "The MFD typically shows a moving map on the right and what on the left?", options: ["Blank screen", "Engine instrumentation", "Checklist"], correctOptionIndex: 1 },
  { id: 240, text: "Most other screens in the G1000 are accessed by turning what?", options: ["Bezel button", "Knob on the lower right corner", "Remote control"], correctOptionIndex: 1 },
  { id: 241, text: "MEMS stands for what?", options: ["Mechanical Electronic Micro Systems", "Microelectromechanical systems", "Miniature Electric Motion Sensors"], correctOptionIndex: 1 },
  { id: 242, text: "MEMS technology in aviation uses what type of sensors?", options: ["Mechanical with moving parts", "Solid-state with no moving parts", "Hydraulic"], correctOptionIndex: 1 },
  { id: 243, text: "MEMS gyros and pressure sensors utilize what technology?", options: ["Electromagnetic", "Piezoelectric", "Thermoelectric"], correctOptionIndex: 1 },
  { id: 244, text: "The AHRS uses what type of sensors to measure aircraft attitude?", options: ["Mechanical gyros", "Solid-state (MEMS) sensors", "Laser ring gyros"], correctOptionIndex: 1 },
  { id: 245, text: "AHRS provides outputs to what systems?", options: ["Only display units", "Autopilot and display units", "Only engine instruments"], correctOptionIndex: 1 },
  { id: 246, text: "Some manufacturers combine AHRS and ADC into what unit?", options: ["Integrated avionics unit", "ADAHRS", "Central computer"], correctOptionIndex: 1 },
  { id: 247, text: "The magnetometer measures what?", options: ["Airspeed", "Aircraft heading", "Altitude"], correctOptionIndex: 1 },
  { id: 248, text: "The magnetometer uses MEMS technology so it has what characteristic?", options: ["Moving parts", "No moving parts", "Fluid damping"], correctOptionIndex: 1 },
  { id: 249, text: "Where is the magnetometer typically located?", options: ["Near the cockpit", "In a remote part of the airframe, often a wing tip", "In the tail cone"], correctOptionIndex: 1 },
  { id: 250, text: "Why is the magnetometer located remotely?", options: ["For better visibility", "To be far from aircraft electrical components that may cause magnetic deviation", "For easier maintenance"], correctOptionIndex: 1 },
  { id: 251, text: "Mode-C transponder replies to what?", options: ["GPS signals", "ATC interrogations", "Weather radar"], correctOptionIndex: 1 },
  { id: 252, text: "Mode-S transponder can do what without prior interrogation?", options: ["Transmit GPS position", "Announce itself spontaneously via 'squittering'", "Receive weather data"], correctOptionIndex: 1 },
  { id: 253, text: "What type of transponder is required for traffic awareness systems?", options: ["Mode-A only", "Mode-S", "Mode-C only"], correctOptionIndex: 1 },
  { id: 254, text: "If the outboard display unit (PFD) fails, what happens?", options: ["All displays go blank", "Information automatically switches to the working MFD", "Standby instruments only work"], correctOptionIndex: 1 },
  { id: 255, text: "In reversionary mode, the MFD typically maintains what information?", options: ["Only navigation", "Engine instrumentation and possibly inset navigation screen", "Only weather"], correctOptionIndex: 1 },
  { id: 256, text: "When an LRU fails, how is it indicated on the display?", options: ["Blank screen", "Bold red cross flag with text indicating failed unit", "Flashing display"], correctOptionIndex: 1 },
  { id: 257, text: "Newest Garmin EFIS use what technology?", options: ["CRT", "Touchscreen LCD", "Mechanical knobs only"], correctOptionIndex: 1 },
  { id: 258, text: "Touchscreen EFIS reduces what?", options: ["Screen size", "Number of knobs and keys around the bezel", "Display brightness"], correctOptionIndex: 1 },
  { id: 259, text: "The screens use what technology to operate buttons?", options: ["Capacitive", "Infrared", "Resistive"], correctOptionIndex: 1 },
  { id: 260, text: "EICAS originally was a Boeing term meaning what?", options: ["Engine Instrument Crew Alert System", "Engine Indicating and Crew Alerting System", "Electronic Instrument Crew Alert System"], correctOptionIndex: 1 },
  { id: 261, text: "Engine and airframe parameters are displayed where?", options: ["Only on PFD", "On dedicated EICAS display or pilot-selectable page on MFD", "Only on standby instruments"], correctOptionIndex: 1 },
  { id: 262, text: "The engine/airframe unit measures what parameters?", options: ["Only engine rpm", "Engine rpm, manifold pressure, oil temperature, CHT, EGT, fuel level", "Only fuel level"], correctOptionIndex: 1 },
  { id: 263, text: "What transducers are used to measure oil pressure and temperature?", options: ["MEMS only", "Conventional transducers", "Piezoelectric only"], correctOptionIndex: 1 },
  { id: 264, text: "For trim position sensing, what type of transducer may be used?", options: ["Potentiometer", "Linear Variable Differential Transducer (LVDT)", "Thermocouple"], correctOptionIndex: 1 },
  { id: 265, text: "Terrain depiction systems show terrain in colour codes similar to what?", options: ["Road maps", "Sectional charts", "Weather maps"], correctOptionIndex: 1 },
  { id: 266, text: "Topography is an optional overlay on which page?", options: ["PFD", "MFD MAP page", "EICAS page"], correctOptionIndex: 1 },
  { id: 267, text: "The TAWS computer receives position information from what source?", options: ["Inertial navigation only", "GPS receiver (with WAAS/SBAS)", "VOR only"], correctOptionIndex: 1 },
  { id: 268, text: "The terrain and obstacle database is stored on what media?", options: ["Internal hard drive", "SD card", "DVD"], correctOptionIndex: 1 },
  { id: 269, text: "Class-B TAWS includes how many basic functions?", options: ["Three", "Four", "Five"], correctOptionIndex: 1 },
  { id: 270, text: "Class-A TAWS requires how many functions?", options: ["Four", "Five", "Six"], correctOptionIndex: 1 },
  { id: 271, text: "The fifth function in Class-A TAWS is what?", options: ["Premature descent alert", "Terrain awareness display", "Attention alerts"], correctOptionIndex: 1 },
  { id: 272, text: "GPWS stands for what?", options: ["Global Positioning Warning System", "Ground Proximity Warning System", "General Purpose Warning System"], correctOptionIndex: 1 },
  { id: 273, text: "More advanced systems introduced in 1996 are known as what?", options: ["Advanced GPWS", "Enhanced Ground Proximity Warning Systems (EGPWS)", "Terrain GPWS"], correctOptionIndex: 1 },
  { id: 274, text: "What type of warning attracts attention more quickly than visual indications?", options: ["Flashing lights", "Human voice aural warnings", "Horns"], correctOptionIndex: 1 },
  { id: 275, text: "GPWS monitors what instrument to determine height above ground?", options: ["Pressure altimeter", "Radio altimeter", "GPS altitude"], correctOptionIndex: 1 },
  { id: 276, text: "Mode-1 GPWS warnings occur when what condition exists?", options: ["Terrain rising too fast", "Excessive rate of descent below 2,450 feet", "Altitude loss after takeoff"], correctOptionIndex: 1 },
  { id: 277, text: "Mode-2 GPWS warnings occur when what condition exists?", options: ["Excessive rate of descent", "Terrain rising at excessively fast rate", "Loss of altitude after takeoff"], correctOptionIndex: 1 },
  { id: 278, text: "Mode-3 GPWS warnings occur when what condition exists?", options: ["Terrain rising too fast", "Altitude loss after takeoff or missed approach", "Insufficient terrain clearance on landing"], correctOptionIndex: 1 },
  { id: 279, text: "Mode-4 GPWS warnings occur during what phase?", options: ["Climb", "Landing phase", "Cruise"], correctOptionIndex: 1 },
  { id: 280, text: "Mode-5 GPWS warnings occur when what condition exists on ILS approach?", options: ["Excessive speed", "Aircraft sinks below glideslope", "Incorrect heading"], correctOptionIndex: 1 },
  { id: 281, text: "Mode 6 provides alerts for what?", options: ["Only altitude loss", "Descent below predefined altitudes, decision height, and excessive bank angle", "Only terrain closure"], correctOptionIndex: 1 },
  { id: 282, text: "Mode 7 produces alerts for what condition?", options: ["Terrain proximity", "Flight into excessive wind shear conditions", "Low altitude"], correctOptionIndex: 1 },
  { id: 283, text: "Windshear detection is active during what phases of flight?", options: ["Cruise only", "Initial takeoff and final approach", "Climb only"], correctOptionIndex: 1 },
  { id: 284, text: "EGPWS uses aircraft inputs including what?", options: ["Only position", "Position, attitude, airspeed, and glideslope", "Only attitude"], correctOptionIndex: 1 },
  { id: 285, text: "EGPWS uses what databases to predict conflicts?", options: ["Only airport database", "Internal terrain, obstacles, and airport databases", "Only terrain database"], correctOptionIndex: 1 },
  { id: 286, text: "Compared to GPWS, EGPWS requires what additional systems?", options: ["More powerful computer", "Terrain database, display unit, and GPS", "Additional antennas"], correctOptionIndex: 1 },
  { id: 287, text: "The terrain database divides the earth's surface into what?", options: ["Zones", "Grid sets referenced on geographic coordinates", "Sections"], correctOptionIndex: 1 },
  { id: 288, text: "Higher resolution grids are used where?", options: ["Over oceans", "Around airports", "Over remote areas"], correctOptionIndex: 1 },
  { id: 289, text: "Lower resolution grids are used where?", options: ["Around airports", "Outside airport areas where en route aircraft altitude makes accidents unlikely", "Over mountains"], correctOptionIndex: 1 },
  { id: 290, text: "The global EGPWS terrain database is stored in how much non-volatile memory?", options: ["10 MByte", "20 MByte", "50 MByte"], correctOptionIndex: 1 },
  { id: 291, text: "Database updates are done using what media?", options: ["USB drive", "Single PCMCIA card", "CD-ROM"], correctOptionIndex: 1 },
  { id: 292, text: "The caution envelope boundary generates what aural message?", options: ["Pull up!", "Caution terrain! Caution terrain!", "Terrain ahead"], correctOptionIndex: 1 },
  { id: 293, text: "When the caution envelope is penetrated, conflicting terrain areas show in what color?", options: ["Red", "Solid yellow", "Green"], correctOptionIndex: 1 },
  { id: 294, text: "The warning envelope boundary generates what aural message?", options: ["Caution terrain", "Terrain, terrain - pull up!", "Sink rate"], correctOptionIndex: 1 },
  { id: 295, text: "When the warning envelope is penetrated, conflicting terrain shows in what color?", options: ["Yellow", "Solid red", "Magenta"], correctOptionIndex: 1 },
  { id: 296, text: "Solid red warning terrain indicates approximately how long until impact?", options: ["15 seconds", "30 seconds", "60 seconds"], correctOptionIndex: 1 },
  { id: 297, text: "Solid yellow caution terrain indicates approximately how long until impact?", options: ["30 seconds", "60 seconds", "90 seconds"], correctOptionIndex: 1 },
  { id: 298, text: "Black terrain on the ND indicates what?", options: ["Unknown terrain", "No close terrain", "Water"], correctOptionIndex: 1 },
  { id: 299, text: "Magenta terrain on the ND indicates what?", options: ["No close terrain", "Unknown terrain", "Water"], correctOptionIndex: 1 },
  { id: 300, text: "TCF creates an increasing terrain clearance envelope around what?", options: ["Mountains", "Intended airport runway", "All terrain"], correctOptionIndex: 1 },
  { id: 301, text: "TCF is active during what phases of flight?", options: ["Only approach", "Takeoff, cruise, and final approach", "Only takeoff"], correctOptionIndex: 1 },
  { id: 302, text: "SVT stands for what?", options: ["Standard Vision Technology", "Synthetic Vision Technology", "System Vision Technology"], correctOptionIndex: 1 },
  { id: 303, text: "SVT is also known as what?", options: ["Enhanced vision", "Synthetic Vision System (SVS)", "Night vision"], correctOptionIndex: 1 },
  { id: 304, text: "SVT uses what to provide situational awareness?", options: ["Live camera feed", "Terrain, obstacle, geopolitical, and other databases", "Radar only"], correctOptionIndex: 1 },
  { id: 305, text: "Navigation for SVT is obtained using what?", options: ["Inertial only", "GPS", "VOR only"], correctOptionIndex: 1 },
  { id: 306, text: "The terrain and obstruction data for SVT comes from what existing system?", options: ["Weather radar", "Terrain Awareness and Warning System (TAWS) database", "Flight management system"], correctOptionIndex: 1 },
  { id: 307, text: "Pathway guidance symbols are also known as what?", options: ["Flight path markers", "Highway-in-the-sky (HITS)", "Approach gates"], correctOptionIndex: 1 },
  { id: 308, text: "TIS stands for what?", options: ["Traffic Information Sensor", "Traffic Information Service", "Terminal Information Service"], correctOptionIndex: 1 },
  { id: 309, text: "TIS uses what system for the traffic data link?", options: ["VHF radio", "Mode-S transponder", "Satellite"], correctOptionIndex: 1 },
  { id: 310, text: "TIS receives traffic information from where?", options: ["Other aircraft directly", "Ground stations", "Satellite"], correctOptionIndex: 1 },
  { id: 311, text: "TIS is updated at what interval?", options: ["Every second", "Every five seconds", "Every ten seconds"], correctOptionIndex: 1 },
  { id: 312, text: "A typical EFIS displays up to how many TIS traffic targets?", options: ["Five", "Eight", "Twelve"], correctOptionIndex: 1 },
  { id: 313, text: "TAS stands for what?", options: ["Traffic Alert System", "Traffic Advisory System", "Terminal Advisory System"], correctOptionIndex: 1 },
  { id: 314, text: "TAS is based on technology originally developed for what system?", options: ["GPWS", "TCAS", "Weather radar"], correctOptionIndex: 1 },
  { id: 315, text: "TAS uses how many blade antennas?", options: ["One", "Two", "Four"], correctOptionIndex: 1 },
  { id: 316, text: "Each TAS antenna scans at what electronic sweep angle?", options: ["45°", "90°", "180°"], correctOptionIndex: 1 },
  { id: 317, text: "TCAS stands for what?", options: ["Traffic Collision Alert System", "Traffic Collision Avoidance System", "Terminal Collision Avoidance System"], correctOptionIndex: 1 },
  { id: 318, text: "TCAS is designed to reduce the incidence of what?", options: ["Bird strikes", "Mid-air collisions", "Ground collisions"], correctOptionIndex: 1 },
  { id: 319, text: "TCAS is mandated by ICAO for aircraft with MTOM over what weight?", options: ["2,500 kg", "5,700 kg", "10,000 kg"], correctOptionIndex: 1 },
  { id: 320, text: "TCAS is based on what type of transponder signals?", options: ["Primary radar", "Secondary Surveillance Radar (SSR) transponder", "ADS-B only"], correctOptionIndex: 1 },
  { id: 321, text: "TCAS can provide what type of avoidance instructions?", options: ["Only traffic alerts", "Resolution Advisory (RA) with suggestive action", "Only visual warnings"], correctOptionIndex: 1 },
  { id: 322, text: "TA stands for what in TCAS terminology?", options: ["Terminal Advisory", "Traffic Advisory", "Threat Alert"], correctOptionIndex: 1 },
  { id: 323, text: "RA stands for what in TCAS terminology?", options: ["Radar Advisory", "Resolution Advisory", "Route Advisory"], correctOptionIndex: 1 },
  { id: 324, text: "TCAS uses how many antennas?", options: ["One", "Two (one above, one below)", "Four"], correctOptionIndex: 1 },
  { id: 325, text: "A non-threat traffic symbol appears as what on TCAS display?", options: ["Red square", "Open white (or blue) diamond", "Yellow circle"], correctOptionIndex: 1 },
  { id: 326, text: "A proximate traffic symbol (within safe zone but not a threat) appears as what?", options: ["Open diamond", "Solid diamond", "Yellow circle"], correctOptionIndex: 1 },
  { id: 327, text: "A traffic advisory (potential threat) symbol appears as what?", options: ["Red square", "Solid yellow circle", "White diamond"], correctOptionIndex: 1 },
  { id: 328, text: "A resolution advisory (collision threat) symbol appears as what?", options: ["Yellow circle", "Red square", "White diamond"], correctOptionIndex: 1 },
  { id: 329, text: "Why are turbine engines fitted with vibration indicators?", options: ["Because they vibrate more than piston engines", "Because low vibration level changes may go unnoticed", "For performance calculation"], correctOptionIndex: 1 },
  { id: 330, text: "Early vibration transducers were of what type?", options: ["Piezoelectric only", "Moving coil type", "Capacitive"], correctOptionIndex: 1 },
  { id: 331, text: "An alternative vibration transducer uses what type of crystal?", options: ["Quartz oscillator", "Piezoelectric crystal", "Silicon"], correctOptionIndex: 1 },
  { id: 332, text: "AVM stands for what?", options: ["Aviation Vibration Monitor", "Airborne Vibration Monitoring", "Automatic Vibration Measurement"], correctOptionIndex: 1 },
  { id: 333, text: "Modern AVM systems have how many piezoelectric crystals in one housing?", options: ["One", "A pair (for dual channel redundancy)", "Three"], correctOptionIndex: 1 },
  { id: 334, text: "Airlines download vibration data to plot what against time?", options: ["Engine hours", "Trend graphs", "Fuel flow"], correctOptionIndex: 1 },
  { id: 335, text: "Trends are analysed to determine what?", options: ["Fuel efficiency", "Incipient failure of engine components", "Takeoff performance"], correctOptionIndex: 1 },
  { id: 336, text: "SAT stands for what?", options: ["Surface Air Temperature", "Static Air Temperature", "Standard Air Temperature"], correctOptionIndex: 1 },
  { id: 337, text: "SAT is the temperature of what?", options: ["Compressed air", "Real undisturbed air around the aircraft", "Engine intake air"], correctOptionIndex: 1 },
  { id: 338, text: "TAT stands for what?", options: ["True Air Temperature", "Total Air Temperature", "Turbine Air Temperature"], correctOptionIndex: 1 },
  { id: 339, text: "TAT is the temperature of air compressed by what?", options: ["Engine compression", "Impact of the flying aircraft", "Cabin pressurization"], correctOptionIndex: 1 },
  { id: 340, text: "The difference between TAT and SAT is called what?", options: ["Delta T", "Ram Rise (RR)", "Compression factor"], correctOptionIndex: 1 },
  { id: 341, text: "Ram rise is negligible for aircraft flying below what Mach number?", options: ["Mach 0.1", "Mach 0.2", "Mach 0.5"], correctOptionIndex: 1 },
  { id: 342, text: "Most temperature sensors use what type of wire element?", options: ["Copper", "Platinum", "Nickel"], correctOptionIndex: 1 },
  { id: 343, text: "The recovery factor of a flush bulb sensor varies between what values?", options: ["0.5 to 0.75", "0.75 to 0.90", "0.9 to 1.0"], correctOptionIndex: 1 },
  { id: 344, text: "TAT probes have what type of time-lag?", options: ["Large time-lag", "Virtually zero time-lag", "Variable time-lag"], correctOptionIndex: 1 },
  { id: 345, text: "TAT probes have a recovery factor of approximately what?", options: ["0.75", "One", "0.9"], correctOptionIndex: 1 },
  { id: 346, text: "Separation of water droplets in a TAT probe is achieved how?", options: ["By heating", "By causing air to turn through 90° before passing over sensing element", "By filtration"], correctOptionIndex: 1 },
  { id: 347, text: "TAT probes have what to prevent ice forming?", options: ["De-icing boots", "A heating element", "Alcohol spray"], correctOptionIndex: 1 },
  { id: 348, text: "The heater has minimal effect on indicated temperature - typical values at Mach 1.0?", options: ["0.9°C", "0.15°C", "1.0°C"], correctOptionIndex: 1 },
  { id: 349, text: "EASA requires FDR for turbine aircraft with takeoff weight greater than what?", options: ["2,700 kg", "5,700 kg", "10,000 kg"], correctOptionIndex: 1 },
  { id: 350, text: "The FDR must retain data from at least the last how many hours?", options: ["10 hours", "25 hours", "50 hours"], correctOptionIndex: 1 },
  { id: 351, text: "For aircraft under 5,700 kg, the retention time may be reduced to how many hours?", options: ["5 hours", "10 hours", "15 hours"], correctOptionIndex: 1 },
  { id: 352, text: "For aircraft over 27,000 kg, additional parameters must be recorded including what?", options: ["Only primary flight controls", "Primary flight control positions, pitch trim, primary navigation information, flight deck warnings", "Only landing gear position"], correctOptionIndex: 1 },
  { id: 353, text: "Recording must begin before the aircraft can do what?", options: ["Take off", "Move under its own power", "Start engines"], correctOptionIndex: 1 },
  { id: 354, text: "Recording ceases after what event?", options: ["Landing", "Aircraft no longer capable of moving under its own power", "Engine shutdown"], correctOptionIndex: 1 },
  { id: 355, text: "The FDR container is painted what color?", options: ["Black", "Distinctive orange or yellow", "Red"], correctOptionIndex: 1 },
  { id: 356, text: "The underwater locator beacon transmits at what frequency?", options: ["25 kHz", "37.5 kHz", "50 kHz"], correctOptionIndex: 1 },
  { id: 357, text: "The underwater locator beacon operates for approximately how many days?", options: ["15 days", "30 days", "60 days"], correctOptionIndex: 1 },
  { id: 358, text: "The three-axis accelerometer detects acceleration along what axes?", options: ["Pitch, roll, yaw", "Longitudinal, lateral, and vertical", "X, Y, and rotational"], correctOptionIndex: 1 },
  { id: 359, text: "The accelerometer unit is located where in the aircraft?", options: ["Nose", "Centre of gravity", "Tail"], correctOptionIndex: 1 },
  { id: 360, text: "What changes when the bar in the sensor bends due to acceleration?", options: ["Capacitance", "Resistance value of the strain gauge", "Inductance"], correctOptionIndex: 1 },
  { id: 361, text: "DFDRS stands for what?", options: ["Digital Flight Data Recording System", "Digital Flight Data Recorder System", "Data Flight Digital Recorder System"], correctOptionIndex: 0 },
  { id: 362, text: "The DFDRS includes what main components?", options: ["Only recorder", "Flight Data Acquisition Unit, Flight Data Recorder, linear accelerometer, EVENT button, control panel", "Only FDAU and recorder"], correctOptionIndex: 1 },
  { id: 363, text: "FDAU stands for what?", options: ["Flight Data Acquisition Unit", "Flight Data Acquisition Unit", "Flight Digital Acquisition Unit"], correctOptionIndex: 0 },
  { id: 364, text: "The flight data recorder is located where in the aircraft?", options: ["Nose section", "Rear part of the aircraft", "Wing root"], correctOptionIndex: 1 },
  { id: 365, text: "The EVENT push button is located where?", options: ["Overhead panel", "On the pedestal", "Instrument panel"], correctOptionIndex: 1 },
  { id: 366, text: "Power interlock supplies power to FDR when what condition exists?", options: ["Master switch on", "One engine is started, stops 5 minutes after last engine shutdown", "Aircraft on ground"], correctOptionIndex: 1 },
  { id: 367, text: "Capacitance type fuel quantity systems measure what property of fuel?", options: ["Volume only", "Mass of the fuel", "Level only"], correctOptionIndex: 1 },
  { id: 368, text: "The capacitance probe consists of what?", options: ["Single tube", "Two concentric metal tubes (plates of the capacitor)", "Flat plates"], correctOptionIndex: 1 },
  { id: 369, text: "The capacity of a capacitor depends on what variables?", options: ["Only plate area", "Area of plates, separation between plates, dielectric constant", "Only dielectric constant"], correctOptionIndex: 1 },
  { id: 370, text: "In a capacitance probe, what is the only variable?", options: ["Plate area", "Material between plates (dielectric)", "Plate separation"], correctOptionIndex: 1 },
  { id: 371, text: "Air has a dielectric constant of what?", options: ["0", "One", "Two"], correctOptionIndex: 1 },
  { id: 372, text: "Fuel has a dielectric constant of approximately what?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 373, text: "A compensator is built into the bottom of one tank unit to cancel changes in what?", options: ["Fuel level", "Dielectric constant with temperature changes", "Pressure"], correctOptionIndex: 1 },
  { id: 374, text: "Ultrasonic gauging depends on what phenomenon?", options: ["Electrical capacitance", "Sound energy transmitted through liquid and reflected", "Resistance change"], correctOptionIndex: 1 },
  { id: 375, text: "The velocity of sound in fuel is inversely proportional to what?", options: ["Pressure", "Temperature", "Density"], correctOptionIndex: 1 },
  { id: 376, text: "Ultrasonic fuel gauging depends on what two measurements?", options: ["Pressure and temperature", "Speed of ultrasound through fuel, and round-trip time to fuel surface", "Volume and mass"], correctOptionIndex: 1 },
  { id: 377, text: "The ultrasonic probe transducer features what type of ceramic disk?", options: ["Capacitive", "Piezoelectric", "Magnetic"], correctOptionIndex: 1 },
  { id: 378, text: "Typical resonant frequency of the crystal is between what values?", options: ["100 Hz and 1 kHz", "1 and 10 MHz", "100 MHz and 1 GHz"], correctOptionIndex: 1 },
  { id: 379, text: "The purpose of the stillwell is to do what?", options: ["Measure temperature", "Collimate sound and provide sheltered measurement area", "Heat the fuel"], correctOptionIndex: 1 },
  { id: 380, text: "Older EFIS light aircraft may have how many conventional mechanical standby instruments?", options: ["Two", "Three", "Four"], correctOptionIndex: 1 },
  { id: 381, text: "What is the minimum standby instrument requirement?", options: ["Airspeed and altimeter only", "Airspeed indicator, attitude indicator, altimeter, and heading indicator", "Attitude and heading only"], correctOptionIndex: 1 },
  { id: 382, text: "Standby instruments must operate independently of what?", options: ["Pilot input", "Aircraft power", "Static pressure"], correctOptionIndex: 1 },
  { id: 383, text: "The Trilogy ESI provides backup for what parameters?", options: ["Only attitude", "Attitude, altitude, airspeed, slip/skid, and optional heading", "Only altitude and airspeed"], correctOptionIndex: 1 },
  { id: 384, text: "The Trilogy ESI internal battery provides flight data for how long after power loss?", options: ["30 minutes minimum", "Minimum of one hour (exceeds 30-minute requirement)", "15 minutes"], correctOptionIndex: 1 },
  { id: 385, text: "The Trilogy ESI contains what internally?", options: ["Mechanical gyros", "AHRS", "GPS"], correctOptionIndex: 1 },
  { id: 386, text: "External inputs to the Trilogy ESI are what?", options: ["Only power", "Pitot and static pipelines, and magnetometer", "Only magnetometer"], correctOptionIndex: 1 },
  { id: 387, text: "FMS stands for what?", options: ["Flight Monitoring System", "Flight Management System", "Frequency Management System"], correctOptionIndex: 1 },
  { id: 388, text: "A primary function of FMS is what?", options: ["Engine management", "In-flight management of the flight plan", "Communication management"], correctOptionIndex: 1 },
  { id: 389, text: "The FMS uses various sensors including what to determine position?", options: ["Only VOR", "GPS often backed up by radio navigation", "Only inertial"], correctOptionIndex: 1 },
  { id: 390, text: "The FMS contains what database?", options: ["Aircraft performance database", "Navigation database (NDB)", "Weather database"], correctOptionIndex: 1 },
  { id: 391, text: "How often is the navigation database normally updated?", options: ["Every 14 days", "Every 28 days", "Every 56 days"], correctOptionIndex: 1 },
  { id: 392, text: "The navigation database contains what elements?", options: ["Only airports", "Waypoints, airways, radio navigation aids, airports, runways, SIDs, STARs, IAPs", "Only VOR stations"], correctOptionIndex: 1 },
  { id: 393, text: "SID stands for what?", options: ["Standard Instrument Departure", "Standard Instrument Departure", "Standard Initial Departure"], correctOptionIndex: 0 },
  { id: 394, text: "STAR stands for what?", options: ["Standard Terminal Arrival Route", "Standard Terminal Arrival Route", "Standard Track Arrival Route"], correctOptionIndex: 0 },
  { id: 395, text: "IAP stands for what?", options: ["Instrument Approach Procedure", "Instrument Approach Procedure", "Initial Approach Procedure"], correctOptionIndex: 0 },
  { id: 396, text: "Early EFIS systems used what display technology?", options: ["LCD", "Cathode Ray Tube (CRT)", "LED"], correctOptionIndex: 1 },
  { id: 397, text: "Later EFIS displays use what technology?", options: ["CRT", "Multi-colour liquid-crystal display (LCD)", "Plasma"], correctOptionIndex: 1 },
  { id: 398, text: "A typical EFIS system comprises what two main displays?", options: ["EICAS and ECAM", "PFD and ND", "ADI and HSI"], correctOptionIndex: 1 },
  { id: 399, text: "PFD stands for what?", options: ["Primary Flight Display", "Primary Flight Display", "Pilot Flight Display"], correctOptionIndex: 0 },
  { id: 400, text: "ND stands for what?", options: ["Navigation Display", "Navigation Display", "Nautical Display"], correctOptionIndex: 0 },
  { id: 401, text: "On captain's side, where is the PFD located relative to ND?", options: ["Right of ND", "Left of ND", "Above ND"], correctOptionIndex: 1 },
  { id: 402, text: "On first officer's side, where is the PFD located relative to ND?", options: ["Left of ND", "Right of ND", "Below ND"], correctOptionIndex: 1 },
  { id: 403, text: "The centre of the PFD contains what instrument?", options: ["Airspeed indicator", "Attitude indicator", "Altimeter"], correctOptionIndex: 1 },
  { id: 404, text: "To the left of the attitude indicator on PFD is what?", options: ["Altimeter", "Airspeed indicator", "Heading indicator"], correctOptionIndex: 1 },
  { id: 405, text: "To the right of the attitude indicator on PFD is what?", options: ["Airspeed indicator", "Altimeter", "VSI"], correctOptionIndex: 1 },
  { id: 406, text: "Airspeed and altitude on PFD are usually presented as what?", options: ["Circular dials", "Vertical 'tapes'", "Digital numbers only"], correctOptionIndex: 1 },
  { id: 407, text: "At the bottom of the PFD is what display?", options: ["Altimeter setting", "Heading display", "VSI"], correctOptionIndex: 1 },
  { id: 408, text: "The ND displays what type of data?", options: ["Engine data", "Horizontal situation data", "Vertical profile"], correctOptionIndex: 1 },
  { id: 409, text: "The ND can be superimposed with what overlays?", options: ["Only weather radar", "Weather radar, EGPWS, and/or TCAS", "Only EGPWS"], correctOptionIndex: 1 },
  { id: 410, text: "The ND shows wind direction/speed with respect to what?", options: ["True north only", "True north in numeric and magnetic north in green arrow", "Magnetic north only"], correctOptionIndex: 1 },
  { id: 411, text: "ILS marker beacon on ND flashes what colors?", options: ["Red for all markers", "Blue for outer, amber for middle, white for inner", "Green for all markers"], correctOptionIndex: 1 },
  { id: 412, text: "EICAS was first introduced in which Boeing aircraft?", options: ["737 and 747", "757 and 767", "777 and 787"], correctOptionIndex: 1 },
  { id: 413, text: "ECAM was first introduced in which Airbus aircraft?", options: ["A300", "A310", "A320"], correctOptionIndex: 1 },
  { id: 414, text: "EICAS stands for what?", options: ["Engine Instrument Crew Alert System", "Engine Indicating and Crew Alerting System", "Electronic Instrument Crew Alert System"], correctOptionIndex: 1 },
  { id: 415, text: "ECAM stands for what?", options: ["Electronic Centralized Aircraft Monitor", "Electronic Centralized Aircraft Monitoring", "Engine Centralized Alerting Module"], correctOptionIndex: 1 },
  { id: 416, text: "Basic EICAS system comprises how many display units?", options: ["One", "Two", "Three"], correctOptionIndex: 1 },
  { id: 417, text: "In EICAS, how many computers are designated left and right?", options: ["One computer", "Two computers", "Four computers"], correctOptionIndex: 1 },
  { id: 418, text: "In EICAS, when one computer is in control, the other is in what mode?", options: ["Off", "Standby", "Test"], correctOptionIndex: 1 },
  { id: 419, text: "In EICAS, the upper display unit shows what?", options: ["Secondary engine parameters", "Primary engine parameters (speed, EGT) and warning/caution messages", "System status only"], correctOptionIndex: 1 },
  { id: 420, text: "In EICAS, the lower display unit shows what?", options: ["Primary engine parameters", "Secondary engine parameters and non-engine system status", "Only fuel flow"], correctOptionIndex: 1 },
  { id: 421, text: "Secondary engine parameters include what?", options: ["Only N1 speed", "N2 speed, fuel flow, oil quantity, pressure, temperature, vibration", "Only EGT"], correctOptionIndex: 1 },
  { id: 422, text: "Level A (Warning) messages are displayed in what color?", options: ["Amber", "Red", "Green"], correctOptionIndex: 1 },
  { id: 423, text: "Level B (Caution) messages are displayed in what color?", options: ["Red", "Amber", "White"], correctOptionIndex: 1 },
  { id: 424, text: "Level C (Advisory) messages are displayed in what color?", options: ["Red", "Amber", "Green"], correctOptionIndex: 1 },
  { id: 425, text: "Up to how many messages can be displayed on EICAS?", options: ["5", "11", "20"], correctOptionIndex: 1 },
  { id: 426, text: "To differentiate caution from advisory, advisory messages are how?", options: ["In smaller font", "Indented one space to the right", "In italics"], correctOptionIndex: 1 },
  { id: 427, text: "Pushing the cancel switch removes what messages?", options: ["Warning messages only", "Caution and advisory messages only", "All messages"], correctOptionIndex: 1 },
  { id: 428, text: "ECAM data relates essentially to what?", options: ["Only engine parameters", "Primary systems of the aircraft", "Only flight controls"], correctOptionIndex: 1 },
  { id: 429, text: "ECAM displays information in what format?", options: ["Only numeric", "Checklist and pictorial or synoptic format", "Only graphical"], correctOptionIndex: 1 },
  { id: 430, text: "ECAM has how many display modes?", options: ["Two", "Four", "Six"], correctOptionIndex: 1 },
  { id: 431, text: "The fourth ECAM mode is what?", options: ["Automatic", "Manual", "Test"], correctOptionIndex: 1 },
  { id: 432, text: "In failure-related mode, what happens on ECAM?", options: ["Only aural warning", "Diagram of affected system displayed, corrective action displayed", "Only master caution light"], correctOptionIndex: 1 },
  { id: 433, text: "Level 3 warning on ECAM includes what aural?", options: ["Single chime", "Repetitive chime (overspeed, fire, stall)", "No aural"], correctOptionIndex: 1 },
  { id: 434, text: "Level 2 warning on ECAM has what aural?", options: ["Repetitive chime", "Single chime", "No aural"], correctOptionIndex: 1 },
  { id: 435, text: "ECAM was designed by which manufacturer?", options: ["Boeing", "Airbus", "Bombardier"], correctOptionIndex: 1 },
  { id: 436, text: "EICAS was designed by which manufacturer?", options: ["Airbus", "Boeing", "Embraer"], correctOptionIndex: 1 },
  { id: 437, text: "ECAM data is always displayed in what format?", options: ["Numeric only", "Checklist and schematic format", "Graphical only"], correctOptionIndex: 1 },
  { id: 438, text: "ECAM displays corrective action during failures. Does EICAS have a similar function?", options: ["Yes, identical", "No similar function", "Yes, but different format"], correctOptionIndex: 1 },
  { id: 439, text: "In ECAM, errors are presented and then what happens once resolved?", options: ["Remain displayed", "Disappear", "Change color"], correctOptionIndex: 1 },
];
