export const kinematicsGearTrainsQuestions = [
  {
    id: 1,
    text: "What is the formula for acceleration in straight-line motion?",
    options: ["a = (v + u)/t", "a = (v - u)/t", "a = (v - u) × t"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "If a truck's speed changes from 50 ft/sec to 20 ft/sec in 15 seconds, what is its acceleration?",
    options: ["+2 ft/sec²", "-2 ft/sec²", "0 ft/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "When an object moves in a straight line with constant speed, it is:",
    options: ["Accelerating", "Not accelerating", "Always changing direction"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "In the equations of motion, what does the symbol 's' represent?",
    options: ["Speed", "Time", "Distance covered"],
    correctOptionIndex: 2,
  },
  {
    id: 5,
    text: "Which formula correctly represents v = u + at?",
    options: ["Formula i", "Formula ii", "Formula iii"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "What is the formula for distance when using average velocity?",
    options: ["s = v × t", "s = u × t", "s = Vav × t"],
    correctOptionIndex: 2,
  },
  {
    id: 7,
    text: "If initial velocity is 50 ft/sec, final velocity is 75 ft/sec, and distance is 125 ft, what is the acceleration?",
    options: ["10.5 ft/sec²", "12.5 ft/sec²", "15.0 ft/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "Which formula is used when you have u, v, a, and s?",
    options: ["s = ut + ½at²", "v = u + at", "v² = u² + 2as"],
    correctOptionIndex: 2,
  },
  {
    id: 9,
    text: "What does a negative acceleration indicate?",
    options: ["Object is speeding up", "Object is slowing down", "Object is moving at constant speed"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "The average speed formula when acceleration is constant is:",
    options: ["Vav = (u × v)/2", "Vav = (u + v)/2", "Vav = u + v"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "What are the units of acceleration?",
    options: ["ft/sec", "ft/sec²", "ft²/sec"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "In the formula s = ut + ½at², what does 't' represent?",
    options: ["Temperature", "Time", "Tension"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "How many equations of motion are there for straight-line motion?",
    options: ["2", "4", "6"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "When solving motion problems, what should you do first?",
    options: ["Choose any formula", "Determine which three quantities are given", "Guess the answer"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "What is the SI unit for distance in these equations?",
    options: ["Meters", "Feet", "Both A and B are used"],
    correctOptionIndex: 2,
  },
  {
    id: 16,
    text: "In the formula a = (v - u)/t, if v is less than u, then a is:",
    options: ["Positive", "Negative", "Zero"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "What does the symbol 'u' represent?",
    options: ["Final velocity", "Initial velocity", "Average velocity"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "What does the symbol 'v' represent?",
    options: ["Initial velocity", "Final velocity", "Average velocity"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "Which formula is s = (u + v)t/2?",
    options: ["Formula i", "Formula ii", "Formula iii"],
    correctOptionIndex: 0,
  },
  {
    id: 20,
    text: "If a car travels at an average speed of 50 mph for 6 hours, how far does it travel?",
    options: ["200 miles", "300 miles", "400 miles"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "What is the approximate acceleration due to gravity near Earth's surface in m/sec²?",
    options: ["9.8 m/sec²", "32 m/sec²", "16 m/sec²"],
    correctOptionIndex: 0,
  },
  {
    id: 22,
    text: "What is the approximate acceleration due to gravity near Earth's surface in ft/sec²?",
    options: ["9.8 ft/sec²", "16 ft/sec²", "32 ft/sec²"],
    correctOptionIndex: 2,
  },
  {
    id: 23,
    text: "For how many seconds can an object fall before air resistance becomes significant?",
    options: ["2.5 seconds", "4.5 seconds", "8.0 seconds"],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "From what height can an object fall before air resistance becomes significant?",
    options: ["200 ft", "324 ft", "500 ft"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "What is terminal velocity for a falling object in mph?",
    options: ["98 mph", "115 mph", "150 mph"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "An object dropped from rest falls for 3 seconds. What is its speed?",
    options: ["64 ft/sec", "96 ft/sec", "128 ft/sec"],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "An object dropped from rest falls for 3 seconds. How far does it fall?",
    options: ["96 ft", "144 ft", "192 ft"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "An object thrown upward with 120 ft/sec initial speed. How high does it rise?",
    options: ["180 ft", "200 ft", "225 ft"],
    correctOptionIndex: 2,
  },
  {
    id: 29,
    text: "When an object is thrown upward, what is its acceleration value?",
    options: ["+9.8 m/sec²", "-9.8 m/sec²", "0 m/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "\"Freely falling\" means:",
    options: ["No gravity acting", "Neglecting air resistance", "Falling with parachute"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "Who determined the rate of acceleration of an object falling under gravity?",
    options: ["Galileo", "Sir Isaac Newton", "Einstein"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "Who showed that all masses fall at the same rate?",
    options: ["Newton", "Galileo at Pisa", "Archimedes"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "At what speed does a falling object reach 98 mph?",
    options: ["After 2 seconds", "After 4.5 seconds", "After 8 seconds"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "When an object is rising and decreasing speed, acceleration due to gravity is:",
    options: ["Positive", "Negative", "Zero"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "What happens to speed when fall time increases beyond 8 seconds?",
    options: ["Continues increasing", "Remains constant at terminal velocity", "Decreases"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "A radian is approximately equal to how many degrees?",
    options: ["45°", "57.3°", "90°"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "What is the definition of a radian?",
    options: ["360° of a circle", "Central angle subtending an arc equal to the circle's radius", "Half the diameter"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "What Greek letter represents angular displacement?",
    options: ["ω (omega)", "θ (theta)", "α (alpha)"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "What Greek letter represents angular velocity?",
    options: ["θ (theta)", "ω (omega)", "α (alpha)"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "What Greek letter represents angular acceleration?",
    options: ["θ (theta)", "ω (omega)", "α (alpha)"],
    correctOptionIndex: 2,
  },
  {
    id: 41,
    text: "If angular velocity increases, angular acceleration is:",
    options: ["Positive", "Negative", "Zero"],
    correctOptionIndex: 0,
  },
  {
    id: 42,
    text: "The rotational analogy to v = u + at is:",
    options: ["θ = ω₁t + ½αt²", "ω₂ = ω₁ + αt", "ω₂² = ω₁² + 2αθ"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "A rotating part increases from 3 rev/min to 35 rev/min in 3.5 minutes. What is angular acceleration?",
    options: ["5.14 rev/min²", "9.14 rev/min²", "12.14 rev/min²"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "A propeller starts at 900 rev/min and accelerates at 100 rev/min² for 5 minutes. How many revolutions?",
    options: ["4,500", "5,000", "5,750"],
    correctOptionIndex: 2,
  },
  {
    id: 45,
    text: "A propeller starts at 1,000 rev/min, accelerates at 100 rev/min² through 2,000 revolutions. Final angular velocity?",
    options: ["1,000 rev/min", "1,180 rev/min", "1,500 rev/min"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "The equation s = Rθ requires θ to be in:",
    options: ["Degrees", "Revolutions", "Radians"],
    correctOptionIndex: 2,
  },
  {
    id: 47,
    text: "What is the relationship between tangential velocity and angular velocity?",
    options: ["v = R/ω", "v = Rω", "v = ω/R"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "What is the relationship between tangential acceleration and angular acceleration?",
    options: ["a = Rα", "a = R/α", "a = α/R"],
    correctOptionIndex: 0,
  },
  {
    id: 49,
    text: "A car on a circular track of radius 150 ft sweeps out an angle of 200°. Distance travelled?",
    options: ["423 ft", "523 ft", "623 ft"],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "A racing car travels at 176 ft/sec on a track of radius 500 ft. Angular velocity in rev/min?",
    options: ["2.36 rev/min", "3.36 rev/min", "4.36 rev/min"],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "A car increases speed at 15 ft/sec² on a 4,000 ft radius track. Angular acceleration in rad/sec²?",
    options: ["0.00375 rad/sec²", "0.0375 rad/sec²", "0.375 rad/sec²"],
    correctOptionIndex: 0,
  },
  {
    id: 52,
    text: "The radian is called a:",
    options: ["Dimensional unit", "Dimensionless unit", "Complex unit"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "What type of acceleration is always directed toward the centre of circular path?",
    options: ["Tangential acceleration", "Centripetal acceleration", "Linear acceleration"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "When an object increases speed moving in a circle, how many acceleration vectors exist?",
    options: ["One", "Two", "Three"],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "The conversion factor 6.28 rad appears in problems when converting to:",
    options: ["Degrees", "Revolutions", "Radians per minute"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "What is the formula for centripetal acceleration?",
    options: ["V/R", "V²/R", "R/V²"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "What is the formula for centripetal force?",
    options: ["F = mV/R", "F = mV²/R", "F = mR/V²"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "\"Centripetal\" comes from Latin meaning:",
    options: ["Centre-fleeing", "Centre-seeking", "Circular motion"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "In the Imperial system, what is the unit of mass?",
    options: ["Pound", "Slug", "Newton"],
    correctOptionIndex: 1,
  },
  {
    id: 60,
    text: "In the Metric system, what is the unit of force?",
    options: ["Kilogram", "Newton", "Slug"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "1 newton = ?",
    options: ["1 kg m/sec", "1 kg m/sec²", "1 kg/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "1 pound = ?",
    options: ["1 slug ft/sec", "1 slug ft/sec²", "1 slug/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "A force of 1 lb applied to a mass of 1 slug gives acceleration of:",
    options: ["1 ft/sec", "1 ft/sec²", "32 ft/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "Find acceleration of a 3 slug object acted upon by 1.5 lbs force:",
    options: ["0.25 ft/sec²", "0.5 ft/sec²", "1.0 ft/sec²"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "A 6 kg mass accelerates at 5 m/sec². Find the force:",
    options: ["11 N", "30 N", "60 N"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "Centrifugal force is:",
    options: ["The force toward the centre", "The equal and opposite force to centripetal force", "Always greater than centripetal force"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "According to Newton's first law, a ball whirled in a circle would prefer to:",
    options: ["Move in a circle", "Follow a straight path", "Stop moving"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "When a hammer thrower releases the hammer, it travels:",
    options: ["Toward the centre", "In a circle", "In a straight line at a tangent"],
    correctOptionIndex: 2,
  },
  {
    id: 69,
    text: "Which law connects acceleration and force?",
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "The magnitude of centrifugal force is calculated:",
    options: ["Smaller than centripetal force", "The same way as centripetal force", "Larger than centripetal force"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "What is the formula for the period of a simple pendulum?",
    options: ["T = 2π√(g/L)", "T = 2π√(L/g)", "T = π√(L/g)"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "The period of a pendulum is independent of:",
    options: ["Length", "Mass and initial displacement", "Gravity"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "For small amplitudes, the period formula is accurate for angles of:",
    options: ["A few degrees", "Up to 45°", "Any angle"],
    correctOptionIndex: 0,
  },
  {
    id: 74,
    text: "What is the relationship between frequency and period?",
    options: ["f = T", "f = 1/T", "f = T²"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "In a spring-mass system, natural frequency is given by:",
    options: ["fn = 2π√(k/m)", "fn = (1/2π)√(k/m)", "fn = √(k/m)"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "In the spring-mass formula, 'k' represents:",
    options: ["Mass", "Stiffness of the spring", "Gravity"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "The natural frequency of a spring-mass system is independent of:",
    options: ["Stiffness", "Mass", "Gravity and initial displacement"],
    correctOptionIndex: 2,
  },
  {
    id: 78,
    text: "Simple harmonic motion is described as:",
    options: ["Random motion", "Sinusoidal with constant amplitude", "Linear motion"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "In SHM, where is velocity maximum?",
    options: ["At extremities", "At the centre (undisturbed position)", "Halfway between centre and extremity"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "In SHM, where is velocity zero?",
    options: ["At the centre", "At the extremities", "Nowhere"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "In SHM, where is acceleration maximum?",
    options: ["At the centre", "At the extremities", "Halfway"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "In SHM, where is acceleration zero?",
    options: ["At the centre", "At the extremities", "Never"],
    correctOptionIndex: 0,
  },
  {
    id: 83,
    text: "The general wave relationship is:",
    options: ["V = f/λ", "V = fλ", "V = λ/f"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "Wavelength is represented by:",
    options: ["f", "λ", "T"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "Frequency is measured in:",
    options: ["Seconds", "Hertz", "Meters"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "Vibration refers to:",
    options: ["Linear motion", "Mechanical oscillations about an equilibrium point", "Constant velocity motion"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "Free vibration occurs when:",
    options: ["Continuous force is applied", "System is set off with initial input and allowed to vibrate freely", "External force is always present"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "Forced vibration occurs when:",
    options: ["No force is applied", "An alternating force or motion is applied", "System is left alone"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "Resonance is:",
    options: ["Small amplitude at all frequencies", "Large amplitude vibrations from small periodic driving force", "No vibration at any frequency"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "Resonance frequency is approximately equal to:",
    options: ["Twice the natural frequency", "Natural frequency when damping is small", "Half the natural frequency"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "The Tacoma Narrows Bridge collapsed in:",
    options: ["1930", "1940", "1950"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "What wind speed caused the Tacoma Narrows Bridge collapse?",
    options: ["40 mph", "64 mph", "120 mph"],
    correctOptionIndex: 0,
  },
  {
    id: 93,
    text: "The bridge was designed to withstand winds up to:",
    options: ["64 mph", "120 mph", "150 mph"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "Harmonics are frequencies that are:",
    options: ["Fractions of fundamental", "Multiples of fundamental frequency", "Unrelated to fundamental"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "If fundamental frequency is f, harmonics have frequencies:",
    options: ["f, f/2, f/3", "2f, 3f, 4f", "f, 2f, 4f only"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "In a spring-mass system, energy is stored in:",
    options: ["Mass only", "Spring only", "Mass (kinetic) and spring (potential)"],
    correctOptionIndex: 2,
  },
  {
    id: 97,
    text: "A damper:",
    options: ["Stores energy", "Dissipates energy", "Creates energy"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "If no damping exists, theoretically motion continues to:",
    options: ["Stop", "Infinity", "Decrease"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "A helicopter tail boom with natural frequency of 1 Hz must avoid rotor speed of:",
    options: ["180 RPM", "360 RPM", "540 RPM"],
    correctOptionIndex: 0,
  },
  {
    id: 100,
    text: "With 3 blades, how many pulses per revolution?",
    options: ["1", "2", "3"],
    correctOptionIndex: 2,
  },
  {
    id: 101,
    text: "180 pulses/minute equals how many cycles/second?",
    options: ["1 Hz", "2 Hz", "3 Hz"],
    correctOptionIndex: 2,
  },
  {
    id: 102,
    text: "1 cycle/second equals:",
    options: ["60 cycles/minute", "30 cycles/minute", "120 cycles/minute"],
    correctOptionIndex: 0,
  },
  {
    id: 103,
    text: "\"Flutter\" in aircraft surfaces results from:",
    options: ["Aerodynamic interaction with elasticity", "Engine vibration only", "Landing gear problems"],
    correctOptionIndex: 0,
  },
  {
    id: 104,
    text: "Pushing a child on a swing is an example of:",
    options: ["Free vibration", "Forced vibration and resonance", "Damped vibration"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Vibration is occasionally desirable in:",
    options: ["Engines", "Tuning forks and loudspeakers", "Electric motors"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "Work is defined as:",
    options: ["F × D", "F × cosθ", "F × D × cosθ"],
    correctOptionIndex: 2,
  },
  {
    id: 107,
    text: "When force and displacement are in same direction, work equals:",
    options: ["F/D", "F × D", "D/F"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "Actual Mechanical Advantage (AMA) is:",
    options: ["Fi/Fo", "Fo/Fi", "Di/Do"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "Ideal Mechanical Advantage (IMA) is:",
    options: ["Fo/Fi", "Fi/Fo", "Di/Do"],
    correctOptionIndex: 2,
  },
  {
    id: 110,
    text: "Efficiency formula is:",
    options: ["Wi/Wo", "Wo/Wi", "Fo/Fi"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "A worker raises 300 lbs with 75 lbs force. AMA is:",
    options: ["2", "4", "6"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "Input distance 15 ft, output distance 2.5 ft. IMA is:",
    options: ["4", "6", "8"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "AMA = 8, Efficiency = 78%. IMA is:",
    options: ["6.24", "8.78", "10.3"],
    correctOptionIndex: 2,
  },
  {
    id: 114,
    text: "Load 500 lbs raised 2 ft with 100 lbs force through 12 ft. Efficiency is:",
    options: ["75%", "83%", "90%"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "Velocity ratio is the ratio of:",
    options: ["Output velocity to input velocity", "Input distance to output distance", "Output force to input force"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "No machine is _____ efficient:",
    options: ["50%", "100%", "75%"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "If efficiency is 100%, then:",
    options: ["AMA < IMA", "AMA = IMA", "AMA > IMA"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "Work lost to friction is represented by:",
    options: ["Wo", "Wi", "Wf"],
    correctOptionIndex: 0,
  },
  {
    id: 119,
    text: "Input work is always _____ output work:",
    options: ["Less than", "Greater than", "Equal to"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "Efficiency can be expressed as:",
    options: ["Decimal only", "Percentage only", "Decimal or percentage"],
    correctOptionIndex: 2,
  },
  {
    id: 121,
    text: "For a lever, IMA equals:",
    options: ["Lo/Li", "Li/Lo", "Li × Lo"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "In a first-class lever, the fulcrum is:",
    options: ["At one end", "Between load and applied force", "At the load"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "In a second-class lever, the load is:",
    options: ["Between fulcrum and applied force", "At one end", "Between applied force and fulcrum"],
    correctOptionIndex: 0,
  },
  {
    id: 124,
    text: "In a third-class lever, IMA is:",
    options: ["Greater than 1", "Less than 1", "Equal to 1"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "A claw hammer is an example of:",
    options: ["First-class lever", "Second-class lever", "Third-class lever"],
    correctOptionIndex: 0,
  },
  {
    id: 126,
    text: "A wheelbarrow is an example of:",
    options: ["First-class lever", "Second-class lever", "Third-class lever"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "For a pulley system, IMA equals:",
    options: ["Number of pulleys", "Number of strands supporting the load", "Diameter of pulley"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "A single fixed pulley has IMA of:",
    options: ["1", "2", "3"],
    correctOptionIndex: 0,
  },
  {
    id: 129,
    text: "A single movable pulley has IMA of:",
    options: ["1", "2", "3"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "For a wheel and axle, IMA equals:",
    options: ["r/R", "R/r", "R × r"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "Wheel radius 3.5 ft, axle radius 0.27 ft, efficiency 60%, force 75 lbs. Load lifted?",
    options: ["485 lbs", "585 lbs", "685 lbs"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "For an inclined plane, IMA equals:",
    options: ["h/L", "L/h", "sinθ"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "For an inclined plane, IMA also equals:",
    options: ["sinθ", "cosθ", "1/sinθ"],
    correctOptionIndex: 2,
  },
  {
    id: 134,
    text: "Incline angle 32°, force 50 lbs lifts 90 lbs. Efficiency is:",
    options: ["85%", "90%", "95%"],
    correctOptionIndex: 2,
  },
  {
    id: 135,
    text: "For a screw jack, IMA equals:",
    options: ["p/2πr", "2πr/p", "r/p"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "The pitch of a screw is:",
    options: ["Length of screw", "Distance between adjacent threads", "Diameter of screw"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "A screw jack has _____ efficiency due to friction:",
    options: ["High", "Very low", "100%"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "For a hydraulic press, IMA equals:",
    options: ["r²/R²", "R²/r²", "R/r"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "In a hydraulic press, what remains constant?",
    options: ["Pressure", "Volume", "Both pressure and volume"],
    correctOptionIndex: 2,
  },
  {
    id: 140,
    text: "A hydraulic car jack works on the principle of:",
    options: ["Lever", "Hydraulic press", "Screw jack"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "In a simple gear train with 9-tooth pinion and 18-tooth wheel, velocity ratio is:",
    options: ["2:1", "1:2", "1:1"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "Velocity ratio = ?",
    options: ["Number of driven teeth / Number of driver teeth", "Number of driver teeth / Number of driven teeth", "Driver teeth × driven teeth"],
    correctOptionIndex: 0,
  },
  {
    id: 143,
    text: "In a simple train with idler gear, the idler:",
    options: ["Changes the velocity ratio", "Does not alter the overall velocity ratio", "Doubles the ratio"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "For a compound gear train with A=15 teeth, B=30 teeth, C=18 teeth, D=36 teeth, gear ratio is:",
    options: ["2:1", "3:1", "4:1"],
    correctOptionIndex: 2,
  },
  {
    id: 145,
    text: "Compound gear train ratio formula:",
    options: ["Product of driver teeth / Product of driven teeth", "Product of driven teeth / Product of driver teeth", "Sum of teeth / Difference of teeth"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "In a worm gear, one revolution of worm moves the gear:",
    options: ["One tooth", "One revolution", "Half revolution"],
    correctOptionIndex: 0,
  },
  {
    id: 147,
    text: "Worm gear ratio equals:",
    options: ["Number of teeth on worm", "Number of teeth on wheel", "Worm diameter"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "In epicyclic gears, the ring gear is also called:",
    options: ["Sun gear", "Annulus", "Planet carrier"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "With fixed ring gear and driven sun gear, gear ratio = ?",
    options: ["(Sun + Ring)/Sun", "(Sun + Ring)/Ring", "Ring/Sun"],
    correctOptionIndex: 0,
  },
  {
    id: 150,
    text: "Power turbines can spin up to:",
    options: ["2,000 RPM", "38,500 RPM", "100,000 RPM"],
    correctOptionIndex: 1,
  },
  {
    id: 151,
    text: "Propeller speeds above _____ RPM are considered fast:",
    options: ["1,000 RPM", "2,000 RPM", "5,000 RPM"],
    correctOptionIndex: 1,
  },
  {
    id: 152,
    text: "Two main types of reduction gears are:",
    options: ["Parallel spur and epicyclic", "Worm and helical", "Bevel and rack"],
    correctOptionIndex: 0,
  },
  {
    id: 153,
    text: "In epicyclic gears with fixed annulus, planet carrier rotates:",
    options: ["Opposite direction to sun", "Same direction as sun, slower speed", "Same direction, faster speed"],
    correctOptionIndex: 1,
  },
  {
    id: 154,
    text: "In epicyclic gears with fixed planet carrier, annulus rotates:",
    options: ["Same direction as sun", "Opposite direction to sun", "Doesn't rotate"],
    correctOptionIndex: 1,
  },
  {
    id: 155,
    text: "Epicyclic reduction gears are used in:",
    options: ["Piston engines only", "Turboprop engines", "Electric motors only"],
    correctOptionIndex: 1,
  },
];
