export const part145MaintenanceOrganisationQuestions = [
  {
    id: 1,
    text: "What is Part-145 maintenance organization approval?",
    options: ["A process for licensing individual mechanics", "A regulatory process ensuring organizations meet standards for maintenance, repairs, and inspections", "A certification for aircraft design organizations"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "For which aircraft is Part-145 approval mandatory?",
    options: ["All aircraft regardless of type", "Complex motor-powered aircraft, aircraft used for commercial air transport, and components for them", "Only aircraft over 5,700 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "Who can issue a Certificate of Release to Service (CRS) for complex motor-powered aircraft?",
    options: ["Any licensed mechanic", "Only an organization appropriately approved under Part-145", "The aircraft owner"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "What is Part-CAO?",
    options: ["A regulation for complex aircraft maintenance only", "A set of regulations combining maintenance and maintenance management for non-complex, non-commercial air transport aircraft", "A certification for individual mechanics"],
    correctOptionIndex: 1,
  },
  {
    id: 5,
    text: "How is \"Part-CAO\" pronounced?",
    options: ["Part C-A-O", "Part-cow", "Part-cayo"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "What does Part-CAO combine?",
    options: ["Part-66 and Part-147", "The privileges of a maintenance organization and a continuing airworthiness maintenance organization (CAMO)", "Part-M and Part-145 only"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "For which aircraft is Part-CAO applicable?",
    options: ["All commercial aircraft", "Non-complex, non-commercial air transport aircraft", "Only aircraft over 5,700 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "Who is the competent authority for organizations with their principal place of business in an EASA member state?",
    options: ["EASA directly", "The authority designated by that member state", "ICAO"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "Who is the competent authority for organizations with their principal place of business outside an EASA state?",
    options: ["The national aviation authority of that country", "EASA (the Agency)", "ICAO"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "What is the definition of \"maintenance\" according to Part-145?",
    options: ["Only major repairs and overhauls", "Overhaul, repair, inspection, replacement, modification, or defect rectification except pre-flight inspection", "Only scheduled inspections"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "What is specifically excluded from the definition of maintenance?",
    options: ["Component replacement", "Pre-flight inspection", "Defect rectification"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "What is the definition of a complex motor-powered aircraft (CMPA) aeroplane regarding maximum take-off mass?",
    options: ["Exceeding 3,175 kg", "Exceeding 5,700 kg", "Exceeding 12,500 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "What passenger seating configuration defines a complex motor-powered aircraft aeroplane?",
    options: ["More than 9 passengers", "More than 12 passengers", "More than 19 passengers"],
    correctOptionIndex: 2,
  },
  {
    id: 14,
    text: "What is the maximum take-off mass threshold for a complex helicopter?",
    options: ["Exceeding 2,730 kg", "Exceeding 3,175 kg", "Exceeding 5,700 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "What passenger seating configuration defines a complex helicopter?",
    options: ["More than 4 occupants", "More than 9 occupants", "More than 12 occupants"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "Which aircraft is always classified as complex motor-powered aircraft?",
    options: ["Single-engine piston aircraft", "Tilt-rotor aircraft", "Sailplanes"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "What is line maintenance?",
    options: ["Any maintenance carried out in a hangar", "Any maintenance carried out before flight to ensure the aircraft is fit for the intended flight", "Major structural repairs"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "Which of the following is NOT typically considered line maintenance?",
    options: ["Troubleshooting", "Component replacement", "Extensive in-depth examination requiring extensive disassembly"],
    correctOptionIndex: 2,
  },
  {
    id: 19,
    text: "Under what condition can base maintenance tasks be performed by a line maintenance organization?",
    options: ["Never", "For temporary or occasional cases when accepted by the quality manager", "Only for single-engine aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "Base maintenance is defined as:",
    options: ["Maintenance carried out at the main base only", "Any maintenance tasks falling outside the line maintenance criteria", "Only C and D checks"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "What form is used to apply for Part-145 approval?",
    options: ["EASA Form 1", "EASA Form 2", "EASA Form 3"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "What document must be submitted with the Part-145 application?",
    options: ["Quality manual only", "Maintenance Organisation Exposition (MOE)", "Training records"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "Where are the details of approved classes and ratings found?",
    options: ["In the application form", "On page 2 (approval schedule) of the EASA approval certificate (EASA Form-3)", "In the company brochure"],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "What does Category A Class rating cover?",
    options: ["Engines only", "Aircraft including engines, APU, and components whilst fitted to the aircraft", "Components only"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "What does Category B Class rating cover?",
    options: ["Aircraft", "Engines and APUs", "Components"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "What does Category C Class rating cover?",
    options: ["Aircraft", "Engines", "Components (uninstalled, excluding engines and APUs)"],
    correctOptionIndex: 2,
  },
  {
    id: 27,
    text: "How are Category C Class ratings classified?",
    options: ["By aircraft type", "By ATA Chapter", "By manufacturer"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "Who is responsible for amendments to the capability list for Category C ratings?",
    options: ["The accountable manager", "The quality manager", "The competent authority"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "What must be provided for base maintenance?",
    options: ["Only office accommodation", "Aircraft hangars large enough to accommodate the aircraft", "Only outdoor parking"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "What environmental conditions must be controlled in the working environment?",
    options: ["Only lighting", "Temperature, dust, lighting, and noise", "Only temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "What should happen if temperature, dust, or other contamination exceeds acceptable levels?",
    options: ["Work continues with personal protective equipment", "Maintenance tasks must be suspended until satisfactory conditions are re-established", "Work continues but is documented"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "Are hangars necessary for line maintenance?",
    options: ["Yes, always required", "No, but recommended for inclement weather", "Only for night shifts"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "How must unserviceable components be stored relative to serviceable components?",
    options: ["Together for comparison", "Segregated from serviceable components", "In any available space"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "Who should have access to storage facilities?",
    options: ["All employees", "Only authorized personnel", "Only the quality manager"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "How should serviceable aircraft components be stored?",
    options: ["In any available space", "In clean, well-ventilated areas at constant dry temperature, preferably in protective material", "Outside to save space"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "What is the role of the accountable manager?",
    options: ["To perform maintenance tasks", "To ensure all necessary maintenance can be financed and carried out to Part-145 standards", "To conduct audits only"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "Who signs the front page of the exposition?",
    options: ["The quality manager", "The accountable manager", "The competent authority"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "Does the accountable manager need technical knowledge?",
    options: ["Yes, extensive technical knowledge is required", "No, technical knowledge is not required as the MOE defines maintenance standards", "Only for base maintenance"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "Who typically serves as the accountable manager?",
    options: ["The quality manager", "The chief executive officer of the approved maintenance organization", "The line maintenance manager"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "What are the four management positions that should exist depending on the extent of approval?",
    options: ["Operations manager, finance manager, HR manager, IT manager", "Base maintenance manager, line maintenance manager, workshop manager, and quality manager", "Sales manager, marketing manager, purchasing manager, warehouse manager"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "Who does the quality manager have direct access to?",
    options: ["The line maintenance manager", "The accountable manager", "The workshop manager"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "What is the quality manager responsible for?",
    options: ["Performing maintenance tasks", "Checking continued compliance with Part-145 and maintaining the feedback system", "Ordering parts"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "Who may carry out or control colour-contrast dye-penetrant tests?",
    options: ["Any mechanic", "Personnel qualified in category B1, B3, or L per Part-66", "Only NDT specialists"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "How should personnel qualified for non-destructive tests (NDT) be qualified?",
    options: ["By internal training only", "According to European or equivalent standard recognized by the Agency", "By the quality manager"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "What is the aim of human factors principles?",
    options: ["To increase productivity", "To ensure safe interaction between humans and other system components by considering human performance", "To reduce training costs"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "Within what time should new personnel joining the maintenance organisation receive initial human factors training?",
    options: ["Within 3 months", "Within 6 months", "Within 12 months"],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "How often should human factors continuation training be provided?",
    options: ["Every year", "Every two years (appropriate for each two-year period)", "Every five years"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "Who may receive a limited certification authorization for repetitive pre-flight airworthiness directives?",
    options: ["Any licensed mechanic", "The aircraft commander or flight engineer based on their flight crew license", "The quality manager"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "What experience is required for a person receiving a one-off certification authorization when no appropriate certifying staff is available?",
    options: ["At least 2 years of maintenance experience", "At least 3 years of maintenance experience", "At least 5 years of maintenance experience"],
    correctOptionIndex: 2,
  },
  {
    id: 50,
    text: "Within what time must one-off certifications be reported to the appropriate authority?",
    options: ["Within 24 hours", "Within 3 days", "Within 7 days"],
    correctOptionIndex: 2,
  },
  {
    id: 51,
    text: "What is the minimum age for certifying staff and support staff?",
    options: ["18 years", "21 years", "25 years"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "What recency requirement applies to certifying and support staff?",
    options: ["3 months experience in the last year", "6 months of relevant experience within a consecutive two-year period", "12 months experience in the last 5 years"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "How often must continuation training be provided?",
    options: ["Every year", "Every two years", "Every three years"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "For how long must records of certifying staff be kept after they stop working for the organization?",
    options: ["1 year", "2 years", "At least 3 years"],
    correctOptionIndex: 2,
  },
  {
    id: 55,
    text: "Within what time must certifying staff provide their certification authorization to any authorized person?",
    options: ["Immediately", "Within 24 hours", "Within 7 days"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "What must a Category A license holder complete before certifying on a specific aircraft type?",
    options: ["Only theoretical training", "Relevant Category A aircraft task training", "Type rating examination only"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "Who must conduct Category A task training?",
    options: ["Any maintenance organization", "An organization appropriately approved under Part-145 or Part-147", "The competent authority"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "What experience is required for airworthiness review staff for sailplanes and balloons?",
    options: ["At least 6 months", "At least 1 year", "At least 3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "What experience is required for airworthiness review staff for all other aircraft?",
    options: ["At least 1 year", "At least 2 years", "At least 3 years"],
    correctOptionIndex: 2,
  },
  {
    id: 60,
    text: "What must airworthiness review staff hold?",
    options: ["Only a Part-66 license", "A certifying staff authorisation for the corresponding aircraft", "A university degree only"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "If the manufacturer specifies a particular tool, what must the Part-145 organization use?",
    options: ["Any equivalent tool", "That specific tool or alternative approved by competent authority through exposition procedures", "The cheapest available option"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "How must tools and equipment be controlled and calibrated?",
    options: ["According to company preference", "To an officially recognized standard", "Only when problems occur"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "What must be maintained to indicate when tools are due for calibration?",
    options: ["A verbal reminder", "A clear labeling system", "An email notification only"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "What document accompanies serviceable components?",
    options: ["Purchase order", "EASA Form 1 or equivalent", "Shipping label"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "What are unsalvageable components?",
    options: ["Components that are temporarily unavailable", "Components with non-repairable defects, life-expired parts, or missing records", "Components awaiting inspection"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "What precaution should be taken when disposing of unsalvageable components?",
    options: ["Sell them quickly", "Exercise caution to prevent return to service through misrepresentation", "Donate them to training schools"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "What are standard parts?",
    options: ["Any common hardware", "Parts specified in maintenance data with evidence of conformity traceable to applicable standard", "Parts manufactured locally"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "Is a Part-145 organization allowed to manufacture parts?",
    options: ["No, never", "Yes, a limited set of parts for use during maintenance within its own facilities", "Yes, for commercial sale"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "Do locally manufactured parts qualify for certification on EASA Form-1?",
    options: ["Yes, always", "No, they do not qualify for EASA Form-1", "Only if sold externally"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "What data must locally manufactured parts be fabricated according to?",
    options: ["Any available drawing", "Data provided in overhaul/repair manuals, modification schemes, service bulletins, or drawings approved by competent authority", "Verbal instructions"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "What should happen to components that have exceeded their certified life limit?",
    options: ["They can be used with caution", "They are classified as unsalvageable and should not re-enter the supply system", "They can be sold as spare parts"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "When can life-expired parts re-enter the supply system?",
    options: ["Never", "Only if certified life limits have been extended or a repair solution approved per Part-21", "After visual inspection"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "What must the Part-145 organization do regarding maintenance data?",
    options: ["Keep and use current maintenance data relevant to scope of work and capability list", "Only keep data for reference", "Create their own data"],
    correctOptionIndex: 0,
  },
  {
    id: 74,
    text: "What is included in \"applicable maintenance data\"?",
    options: ["Only airworthiness directives", "Requirements from competent authority, ADs, instructions for continuing airworthiness, and data issued per Part-145", "Only manufacturer manuals"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "What must the Part-145 organization do if maintenance data is inaccurate?",
    options: ["Ignore it", "Have a procedure to report inaccurate, incomplete, or ambiguous data to the author", "Correct it themselves"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "What system must the Part-145 organization have?",
    options: ["Individual work cards for each mechanic", "A common work card or worksheet system used throughout all relevant parts", "No work cards required"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "How quickly must an electronic backup database be updated after updates to the central database?",
    options: ["Immediately", "Within 24 hours", "Within 7 days"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "What must planners be aware of regarding human performance?",
    options: ["Only technical skills", "Upper and lower limits and variations in human performance, including circadian rhythm", "Only training requirements"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "What is required for shift or task handover?",
    options: ["Verbal communication only", "A documented written record of the handover", "No formal process needed"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "What must be carried out after completion of maintenance?",
    options: ["Immediate flight test", "General verification that aircraft is clear of tools and access panels are refitted", "Invoice preparation"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "What must be implemented after performance of any critical maintenance task?",
    options: ["A celebration", "An error-capturing method", "A break"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "When must a certificate of release to service be issued?",
    options: ["Within 24 hours of maintenance", "Before flight, after any maintenance", "At the end of the month"],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "How should CDCCL tasks be marked on the CRS?",
    options: ["With a star", "As \"CDCCL task\"", "With a red stamp"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "What statement should the CRS contain according to AMC?",
    options: ["\"Work completed satisfactorily\"", "\"That the work specified except as otherwise specified was carried out per Part-145, and the aircraft/component is considered ready for release to service\"", "\"Released for flight\""],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "What is EASA Form 1?",
    options: ["An application form", "An authorised release certificate or airworthiness approval tag for components", "A license application"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "When is EASA Form 1 issued?",
    options: ["After any maintenance", "After maintenance on a component while it is not attached to the aircraft", "Only for new components"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "For how long can a component without appropriate release certificate be temporarily fitted if aircraft is grounded?",
    options: ["10 flight hours", "30 flight hours or until return to main base, whichever is sooner", "7 days"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "In what language must EASA Form 1 be written?",
    options: ["Only the local language", "English, and if applicable, the language of the member state concerned", "French only"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "For how long must detailed maintenance records be kept?",
    options: ["1 year from release", "At least 3 years from the date the component was released", "5 years from release"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "Where must computer backups be stored?",
    options: ["In the same location as working copies", "In a separate location from working copies, in an environment ensuring good condition", "At the quality manager's home"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "If a Part-145 organization terminates operations, how long of maintenance records must be distributed to customers?",
    options: ["The last 1 year", "The last 2 years", "The last 3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "What must be kept for each module of gas-turbine engines?",
    options: ["Only total time", "Total time and cycles in-service, maintenance records, mandatory maintenance requirements, and life-limited parts replacements", "Only maintenance records"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "What is defined as an \"occurrence\"?",
    options: ["Any maintenance task", "Any condition that has resulted or may result in an unsafe condition that hazards flight safety seriously", "Any customer complaint"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "Within what time must an occurrence be reported to the competent authority?",
    options: ["Within 24 hours", "Within 72 hours", "Within 7 days"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "To which three entities must an occurrence be reported?",
    options: ["The competent authority, the state where the aircraft is registered, and the aircraft design organization", "The police, the fire department, and the hospital", "The manufacturer, the supplier, and the customer"],
    correctOptionIndex: 0,
  },
  {
    id: 96,
    text: "What should a good occurrence reporting system encourage?",
    options: ["Blaming individuals", "Personnel to report occurrences without fear of punishment or retaliation", "Only reporting major incidents"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "What type of culture should a Part-145 organisation establish for reporting?",
    options: ["A punitive culture", "A just culture", "A secretive culture"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "How often should product sampling be conducted on each product line?",
    options: ["Every 6 months", "Every 12 months", "Every 24 months"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "For how long must audit records be kept after a finding has been cleared?",
    options: ["1 year", "At least 2 years", "3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "Who can carry out audits in a small organization (less than 10 employees)?",
    options: ["Only the accountable manager", "It may be more feasible to contract audits to another Part-145 organization", "No audits are required"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "What is the Maintenance Organisation Exposition (MOE)?",
    options: ["A financial document", "A document outlining scope of work and how organization plans to comply with Part-145", "A training manual"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "What is indirect approval of MOE amendments?",
    options: ["Approval by EASA directly", "When competent authority delegates approval to the quality manager", "Approval by the customer"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "What does the approval number IT.145.0003 indicate?",
    options: ["The aircraft type", "Issuing competent authority is Italy (IT)", "The approval is for 3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "What does the approval number EASA.145.0007 indicate?",
    options: ["The organization is in Germany", "The approving authority is EASA itself", "The approval is for 7 years"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Can a Part-145 organization subcontract work to an unapproved organization?",
    options: ["No, never", "Yes, for specialized processes like plating, heat treatment, painting, welding, and NDT under the quality system", "Only for administrative tasks"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "When can a Part-145 organization not maintain an aircraft?",
    options: ["When it's a weekend", "When all required facilities, equipment, tooling, material, maintenance data, and certifying staff are not available", "When the customer is new"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "What changes must be notified to the competent authority before implementation?",
    options: ["Only changes in staff", "Change in name, main location, accountable manager, Form 4 post holders, or changes affecting approval", "Only changes in facilities"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "How long is a Part-145 approval valid?",
    options: ["2 years", "5 years", "Unlimited duration, subject to continued compliance"],
    correctOptionIndex: 2,
  },
  {
    id: 109,
    text: "By when must all approved Part-145 organizations implement a Safety Management System (SMS)?",
    options: ["2 December 2022", "2 December 2024", "2 December 2025"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "What regulation amended Part-145 to include SMS requirements?",
    options: ["Regulation (EU) 2020/1150", "Regulation (EU) 2021/1963", "Regulation (EU) 2023/989"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "What are the four pillars of the ICAO SMS framework?",
    options: ["Planning, organizing, staffing, controlling", "Safety policy and objectives, safety risk management, safety assurance, and safety promotion", "Design, production, maintenance, operations"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "Who endorses and signs the safety policy?",
    options: ["The quality manager", "The accountable manager", "The competent authority"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "Where must the SMS safety policy be included?",
    options: ["Only in the employee handbook", "In both the MOE and the safety management system manual (SMSM)", "Only on the website"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "What board typically reviews the safety policy annually?",
    options: ["The finance board", "The Safety Review Board (SRB)", "The marketing board"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "What does point 145.A.200 require regarding accountabilities?",
    options: ["Verbal agreements", "Clearly defined accountability and lines of responsibility throughout the organization", "No formal structure"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "What does the compliance monitoring function support?",
    options: ["Only financial auditing", "Key safety management processes and follow-up of safety risk mitigation actions", "Marketing activities"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "What does a positive safety culture rely on?",
    options: ["Strict punishment for all errors", "High trust and respect between personnel and management", "Ignoring minor incidents"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "According to just culture principles, what should not be done with occurrence information?",
    options: ["Share it with authorities", "Attribute blame to front-line personnel for actions commensurate with their experience and training", "Use it for safety improvements"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "Which regulation defines just culture principles to be applied?",
    options: ["Regulation (EU) 2018/1139", "Regulation (EU) No 376/2014", "Regulation (EU) 2021/1963"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "What should hazard identification include in particular?",
    options: ["Only technical issues", "Hazards linked to human factors and hazards from organizational set-up or complex arrangements", "Only weather-related hazards"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "What three approaches should safety risk management ensure?",
    options: ["Past, present, future", "Reactive, proactive, and predictive", "Local, national, international"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "What is the main objective of the internal safety reporting scheme?",
    options: ["To punish those who make mistakes", "To gather information to enhance compliance and safety performance, not to assign blame", "To reduce paperwork"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "What type of loop should the internal safety reporting scheme be?",
    options: ["Open loop", "Closed loop to ensure actions are taken internally to address safety issues", "One-way communication"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "What is a Level 1 finding?",
    options: ["Minor administrative error", "Significant non-compliance that seriously lowers safety standard and seriously hazards flight safety", "Customer complaint"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "What is a Level 2 finding?",
    options: ["No action required", "Non-compliance that could lower safety standard and possibly hazard flight safety", "Commendation"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "What is the initial maximum corrective action period for Level 2 findings?",
    options: ["1 month", "3 months", "6 months"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "What action is taken for Level 1 findings?",
    options: ["Warning letter", "Immediate action to revoke, limit, or suspend approval until corrective action taken", "Fine only"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "What does Class A1 rating cover?",
    options: ["Aeroplanes 5,700 kg and below", "Aeroplanes above 5,700 kg", "Helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "What does Class A2 rating cover?",
    options: ["Aeroplanes above 5,700 kg", "Aeroplanes 5,700 kg and below", "Helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "What does Class A3 rating cover?",
    options: ["Aeroplanes", "Helicopters", "Balloons"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "What does Class B1 rating cover?",
    options: ["Piston engines", "Turbine engines", "APUs"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "What does Class B2 rating cover?",
    options: ["Turbine engines", "Piston engines", "APUs"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "What does Class B3 rating cover?",
    options: ["Turbine engines", "Piston engines", "APUs"],
    correctOptionIndex: 2,
  },
  {
    id: 134,
    text: "Which ATA Chapter corresponds to Class C1 (Air Conditioning and Pressurisation)?",
    options: ["Chapter 21", "Chapter 22", "Chapter 24"],
    correctOptionIndex: 0,
  },
  {
    id: 135,
    text: "Which ATA Chapter corresponds to Class C2 (Auto Flight)?",
    options: ["Chapter 21", "Chapter 22", "Chapter 23"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "Which ATA Chapter corresponds to Class C3 (Comms and Nav)?",
    options: ["Chapter 22", "Chapter 23 and 34", "Chapter 24"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "Which ATA Chapter corresponds to Class C7 (Engine - APU)?",
    options: ["Chapter 49", "Chapter 52", "Chapter 61"],
    correctOptionIndex: 0,
  },
  {
    id: 138,
    text: "Which ATA Chapter corresponds to Class C16 (Propellers)?",
    options: ["Chapter 61", "Chapter 62", "Chapter 63"],
    correctOptionIndex: 0,
  },
  {
    id: 139,
    text: "What document must a Part-CAO organization submit with the application?",
    options: ["MOE", "Combined Airworthiness Exposition (CAE)", "Quality manual only"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "For which aircraft types must the scope of work indicate particular aircraft types in Part-CAO?",
    options: ["All aircraft", "Aeroplanes >2,730 kg MTOM and helicopters >1,200 kg MTOM or >4 occupants", "Only helicopters"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "What is the maximum number of full-time equivalent staff for a small Part-CAO organization regarding maintenance?",
    options: ["5 staff", "10 staff", "15 staff"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "What is the maximum number of full-time equivalent staff for a small Part-CAO organization regarding continuing airworthiness management?",
    options: ["5 staff", "10 staff", "15 staff"],
    correctOptionIndex: 0,
  },
  {
    id: 143,
    text: "What may a small Part-CAO organization replace the quality system with?",
    options: ["No system", "Regular organizational reviews, with competent authority approval", "External consultants"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "Within what time must Part-CAO notify the competent authority of changes?",
    options: ["Before implementation", "Within 15 days of the change", "Within 30 days of the change"],
    correctOptionIndex: 1,
  },
  {
    id: 145,
    text: "What privileges does a Part-CAO organization have?",
    options: ["Only maintenance", "Maintenance, continuing airworthiness management, airworthiness review, and permit to fly", "Only design approval"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "For how long must a Part-CAO retain maintenance records?",
    options: ["1 year from release", "3 years from the date the aircraft or component was released", "5 years from release"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "For how long must continuing airworthiness management records be retained?",
    options: ["1 year from withdrawal", "2 years from the date the aircraft has been permanently withdrawn from service", "3 years from withdrawal"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "What is the alternative experience requirement for airworthiness review staff without a license or degree?",
    options: ["At least 1 year additional", "At least 2 years additional for sailplanes/balloons and 4 years for other aircraft", "At least 5 years additional"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "For how long must Part-CAO retain airworthiness review staff records after they leave?",
    options: ["1 year", "At least 2 years", "3 years"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "How many component system ratings does Part-CAO have?",
    options: ["10", "15", "22 (C1 through C22)"],
    correctOptionIndex: 2,
  },
  {
    id: 151,
    text: "What is Class C21 rating for?",
    options: ["Windows", "Water ballast", "Structural"],
    correctOptionIndex: 1,
  },
  {
    id: 152,
    text: "What is Class C22 rating for?",
    options: ["Propellers", "Propulsion augmentation", "Pneumatic systems"],
    correctOptionIndex: 1,
  },
  {
    id: 153,
    text: "When is an NDT rating necessary for a Part-CAO organization?",
    options: ["Always", "Only when carrying out NDT as a particular task for another organization", "Never"],
    correctOptionIndex: 1,
  },
  {
    id: 154,
    text: "Does an aircraft-rated Part-CAO organization need an NDT rating to perform NDT on products they maintain?",
    options: ["Yes, always", "No, if CAE contains NDT procedures", "Only for complex aircraft"],
    correctOptionIndex: 1,
  },
  {
    id: 155,
    text: "How long is a Part-CAO approval valid?",
    options: ["2 years", "5 years", "Unlimited duration, subject to continued compliance"],
    correctOptionIndex: 2,
  },
  {
    id: 156,
    text: "Which approval requires an SMS?",
    options: ["Part-CAO", "Part-145 (by 2 December 2024)", "Neither"],
    correctOptionIndex: 1,
  },
  {
    id: 157,
    text: "Which approval is designed to simplify organization approval for general aviation?",
    options: ["Part-145", "Part-CAO", "Both equally"],
    correctOptionIndex: 1,
  },
  {
    id: 158,
    text: "Which approval is mandatory for organizations maintaining complex motor-powered aircraft?",
    options: ["Part-145", "Part-CAO", "Either"],
    correctOptionIndex: 0,
  },
  {
    id: 159,
    text: "Which approval combines maintenance and continuing airworthiness management privileges?",
    options: ["Part-145", "Part-CAO", "Part-66"],
    correctOptionIndex: 1,
  },
  {
    id: 160,
    text: "For aircraft operated by a licensed air carrier, what maintenance organization approval is required?",
    options: ["Part-CAO", "Part-145", "Either"],
    correctOptionIndex: 1,
  },
];
