export const physicsStressStrainQuestions = [
  {
    id: 1,
    text: "Mass is a dimensionless quantity representing:",
    options: ["The weight of an object", "The amount of matter in a particle or object", "The gravitational pull on an object"],
    correctOptionIndex: 1,
  },
  {
    id: 2,
    text: "The SI unit of mass is:",
    options: ["Slug", "Kilogram (kg)", "Newton"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "The imperial unit of mass is:",
    options: ["Pound", "Slug", "Ounce"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "One slug equals how many kilograms?",
    options: ["4.45 kg", "14.59 kg", "9.81 kg"],
    correctOptionIndex: 1,
  },
  {
    id: 5,
    text: "Force is described by physicists as:",
    options: ["Only a push", "Any push or pull", "Only a pull"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "A force is a vector quantity, meaning it has:",
    options: ["Only magnitude", "Both size and direction", "Only direction"],
    correctOptionIndex: 1,
  },
  {
    id: 7,
    text: "The metric unit of force is:",
    options: ["Pound", "Newton", "Kilogram"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "The imperial unit of force is:",
    options: ["Newton", "Pound", "Slug"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "The conversion factor from pounds to newtons is:",
    options: ["1 lb = 2.2 N", "1 lb = 4.448 N", "1 lb = 9.81 N"],
    correctOptionIndex: 1,
  },
  {
    id: 10,
    text: "Weight is defined as:",
    options: ["The mass of an object", "The earth's gravitational pull on an object", "The volume of an object"],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    text: "The direction of weight force is toward:",
    options: ["The north pole", "The geometrical centre of the earth", "The equator"],
    correctOptionIndex: 1,
  },
  {
    id: 12,
    text: "The mass of an object is:",
    options: ["Different on different planets", "The same wherever the object is in the universe", "Greater at the equator than at the poles"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "The weight of an object on the moon compared to its weight on earth is:",
    options: ["The same", "Different", "Greater"],
    correctOptionIndex: 1,
  },
  {
    id: 14,
    text: "An object that weighs 57.3 lb at the North Pole would weigh how much at the equator?",
    options: ["57.3 lb", "57.0 lb", "58.0 lb"],
    correctOptionIndex: 1,
  },
  {
    id: 15,
    text: "The equation relating mass and weight is:",
    options: ["m = w × g", "w = mg", "w = m/g"],
    correctOptionIndex: 1,
  },
  {
    id: 16,
    text: "The value of g in imperial units is:",
    options: ["9.8 lb/slug", "32 lb/slug", "4.448 lb/slug"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "The value of g in metric units is:",
    options: ["32 N/kg", "9.8 N/kg", "4.448 N/kg"],
    correctOptionIndex: 1,
  },
  {
    id: 18,
    text: "A packet of sugar labelled 1 kg or 2.2 lb shows that:",
    options: ["1 kg equals 2.2 lb (both are weight)", "1 kg is mass, 2.2 lb is weight", "Both are mass units"],
    correctOptionIndex: 1,
  },
  {
    id: 19,
    text: "The lever arm multiplied by an object's weight gives its:",
    options: ["Force", "Turning effect or moment", "Mass"],
    correctOptionIndex: 1,
  },
  {
    id: 20,
    text: "The formula for moment is:",
    options: ["Moment = F/d", "Moment = F × d", "Moment = d/F"],
    correctOptionIndex: 1,
  },
  {
    id: 21,
    text: "In the moment formula, d represents:",
    options: ["Distance along the force", "Perpendicular distance from the point to the line of action of the force", "Diagonal distance"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "Moments are expressed in units of:",
    options: ["N or lb", "N-m or lb-ft", "N/m or lb/ft"],
    correctOptionIndex: 1,
  },
  {
    id: 23,
    text: "When an object is in equilibrium, the principle of moments states:",
    options: ["Sum of clockwise moments > sum of anticlockwise moments", "Sum of anticlockwise moments = sum of clockwise moments", "Sum of anticlockwise moments < sum of clockwise moments"],
    correctOptionIndex: 1,
  },
  {
    id: 24,
    text: "A couple consists of:",
    options: ["Two forces in the same direction", "Two equal and opposite forces separated by a distance", "A single force"],
    correctOptionIndex: 1,
  },
  {
    id: 25,
    text: "The moment of a couple is calculated by:",
    options: ["F + d", "F × d", "F/d"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "The Greek letter used for torque is:",
    options: ["Alpha (α)", "Tau (τ)", "Beta (β)"],
    correctOptionIndex: 1,
  },
  {
    id: 27,
    text: "The torque equation when θ is not 90° is:",
    options: ["τ = Fd", "τ = Fd sin θ", "τ = Fd cos θ"],
    correctOptionIndex: 1,
  },
  {
    id: 28,
    text: "When θ = 90°, sin 90° equals:",
    options: ["0", "1", "Infinity"],
    correctOptionIndex: 1,
  },
  {
    id: 29,
    text: "Units for torque include all EXCEPT:",
    options: ["lb-ft", "N/m", "Nm"],
    correctOptionIndex: 1,
  },
  {
    id: 30,
    text: "When using a torque wrench with an extension, the scale reading formula is:",
    options: ["Specified torque × (L + X)/L", "Specified torque × L/(L + X)", "Specified torque × X/L"],
    correctOptionIndex: 0,
  },
  {
    id: 31,
    text: "In the torque wrench extension formula, L represents:",
    options: ["Length of extension", "Distance between driving tang and centre of handle", "Total length of assembly"],
    correctOptionIndex: 1,
  },
  {
    id: 32,
    text: "When applying torque, the wrench handle should be gripped:",
    options: ["Tightly", "Lightly", "With both hands firmly"],
    correctOptionIndex: 1,
  },
  {
    id: 33,
    text: "Force should be applied to the torque wrench at:",
    options: ["45° to the axis", "90° to the axis", "180° to the axis"],
    correctOptionIndex: 1,
  },
  {
    id: 34,
    text: "If the extension spanner must diverge more than 15° from straight, substitute in the formula:",
    options: ["L + X", "Direct distance D", "L only"],
    correctOptionIndex: 1,
  },
  {
    id: 35,
    text: "The centre of gravity is the point where:",
    options: ["Weight is maximum", "All the mass can be considered to act", "The object is heaviest"],
    correctOptionIndex: 1,
  },
  {
    id: 36,
    text: "For a symmetrical object, the centre of mass is found:",
    options: ["By suspension", "Where the axes of symmetry cross", "By calculation only"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "To find the centre of mass of an irregular object, you need to suspend it from:",
    options: ["One hole only", "At least two different holes", "The geometric centre"],
    correctOptionIndex: 1,
  },
  {
    id: 38,
    text: "The plumb line is used to mark:",
    options: ["Horizontal lines", "Vertical lines", "Diagonal lines"],
    correctOptionIndex: 1,
  },
  {
    id: 39,
    text: "The point where two marked lines cross when suspending an object is the:",
    options: ["Geometric centre", "Centre of mass", "Suspension point"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "The arm is defined as the:",
    options: ["Weight of an item", "Horizontal distance an item is located from the datum", "Vertical height of an item"],
    correctOptionIndex: 1,
  },
  {
    id: 41,
    text: "Items located forward or to the left of the datum have:",
    options: ["Positive sign (+)", "Negative sign (-)", "Zero sign"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "Items located aft or to the right of the datum have:",
    options: ["Negative sign (-)", "Positive sign (+)", "Zero sign"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "The CG of a whole system equals:",
    options: ["Total mass × total moment", "Total moment ÷ total mass", "Total mass ÷ total moment"],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    text: "An aircraft is balanced if it remains level when suspended from:",
    options: ["Any point", "Its ideal centre of gravity", "The nose"],
    correctOptionIndex: 1,
  },
  {
    id: 45,
    text: "CG limits are specified:",
    options: ["Only longitudinally", "Longitudinally (forward and aft) and laterally (left and right)", "Only laterally"],
    correctOptionIndex: 1,
  },
  {
    id: 46,
    text: "The datum is an imaginary vertical line from which:",
    options: ["All weights are measured", "All horizontal measurements are taken", "All vertical measurements are taken"],
    correctOptionIndex: 1,
  },
  {
    id: 47,
    text: "The datum may be located:",
    options: ["Only at the nose", "At any convenient location by the manufacturer", "Only at the main wheels"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "Weighbridge scales consist of:",
    options: ["A single platform", "A separate weighing platform for each wheel or bogey", "Hydraulic jacks only"],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    text: "Hydrostatic weighing units are based on the principle that:",
    options: ["Weight equals mass", "Fluid pressure in a cylinder depends on piston area and applied load", "Strain gauges change resistance"],
    correctOptionIndex: 1,
  },
  {
    id: 50,
    text: "Electrical weighing equipment uses:",
    options: ["Balance arms", "Strain gauges or metallic resistance elements", "Mercury columns"],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "Strain gauges vary in resistance due to:",
    options: ["Temperature change", "Change in length due to elastic strain", "Magnetic fields"],
    correctOptionIndex: 1,
  },
  {
    id: 52,
    text: "A vector quantity is fully described by:",
    options: ["Magnitude only", "Both magnitude and direction", "Direction only"],
    correctOptionIndex: 1,
  },
  {
    id: 53,
    text: "A scalar quantity is fully described by:",
    options: ["Both magnitude and direction", "Magnitude alone", "Direction alone"],
    correctOptionIndex: 1,
  },
  {
    id: 54,
    text: "Examples of vector quantities include:",
    options: ["Mass and time", "Displacement, velocity, acceleration, and force", "Speed and distance"],
    correctOptionIndex: 1,
  },
  {
    id: 55,
    text: "In a scaled vector diagram, the length of the arrow represents:",
    options: ["Direction", "Magnitude", "Both magnitude and direction"],
    correctOptionIndex: 1,
  },
  {
    id: 56,
    text: "A direction of 40° counterclockwise from east means:",
    options: ["40° clockwise from north", "Vector rotated 40° CCW from due east", "40° west of north"],
    correctOptionIndex: 1,
  },
  {
    id: 57,
    text: "The Pythagorean theorem is useful for adding vectors that are:",
    options: ["Parallel", "At right angles to each other", "In opposite directions"],
    correctOptionIndex: 1,
  },
  {
    id: 58,
    text: "The Pythagorean theorem relates:",
    options: ["All sides of any triangle", "The sides of a right triangle to the hypotenuse", "Angles only"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "SOH CAH TOA is a mnemonic for:",
    options: ["Vector addition rules", "Trigonometric functions", "Moment calculations"],
    correctOptionIndex: 1,
  },
  {
    id: 60,
    text: "The sine function relates:",
    options: ["Adjacent to hypotenuse", "Opposite to hypotenuse", "Opposite to adjacent"],
    correctOptionIndex: 1,
  },
  {
    id: 61,
    text: "The cosine function relates:",
    options: ["Opposite to hypotenuse", "Adjacent to hypotenuse", "Opposite to adjacent"],
    correctOptionIndex: 1,
  },
  {
    id: 62,
    text: "The tangent function relates:",
    options: ["Adjacent to hypotenuse", "Opposite to adjacent", "Opposite to hypotenuse"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "In the head-to-tail method, the resultant is drawn from:",
    options: ["Head of first vector to tail of last vector", "Tail of first vector to head of last vector", "Any point to any point"],
    correctOptionIndex: 1,
  },
  {
    id: 64,
    text: "The resultant is the:",
    options: ["Difference of vectors", "Vector sum of two or more vectors", "Product of vectors"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "The order in which vectors are added:",
    options: ["Affects the magnitude", "Does not affect the resultant", "Affects the direction only"],
    correctOptionIndex: 1,
  },
  {
    id: 66,
    text: "Any vector directed in two dimensions can be thought of as having:",
    options: ["One component", "Two components", "Three components"],
    correctOptionIndex: 1,
  },
  {
    id: 67,
    text: "The process of determining the magnitude of vector components is called:",
    options: ["Vector addition", "Vector resolution", "Vector multiplication"],
    correctOptionIndex: 1,
  },
  {
    id: 68,
    text: "The parallelogram method of vector resolution uses:",
    options: ["Only mathematical formulas", "An accurately drawn, scaled vector diagram", "Only trigonometric functions"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "In the trigonometric method, the vertical component is found using:",
    options: ["Cosine function", "Sine function", "Tangent function"],
    correctOptionIndex: 1,
  },
  {
    id: 70,
    text: "In the trigonometric method, the horizontal component is found using:",
    options: ["Sine function", "Cosine function", "Tangent function"],
    correctOptionIndex: 1,
  },
  {
    id: 71,
    text: "When adding three or more right-angle vectors, you can:",
    options: ["Only use the Pythagorean theorem directly", "Rearrange the order to form a right triangle", "Not use the Pythagorean theorem at all"],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    text: "For non-perpendicular vectors, the trick is to:",
    options: ["Add them directly", "Resolve them into components first", "Ignore one vector"],
    correctOptionIndex: 1,
  },
  {
    id: 73,
    text: "When vector A is resolved into components, A =:",
    options: ["Ax × Ay", "Ax + Ay", "Ax - Ay"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "A tailwind approaches the aeroplane from:",
    options: ["The front", "Behind", "The side"],
    correctOptionIndex: 1,
  },
  {
    id: 75,
    text: "A tailwind increases the aeroplane's:",
    options: ["Mass", "Resulting velocity", "Drag"],
    correctOptionIndex: 1,
  },
  {
    id: 76,
    text: "A headwind approaches the aeroplane from:",
    options: ["Behind", "The front", "The side"],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    text: "A headwind decreases the aeroplane's:",
    options: ["Mass", "Resulting velocity", "Lift"],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    text: "With a side wind, the resultant velocity is found using:",
    options: ["Simple addition", "The Pythagorean theorem", "Subtraction"],
    correctOptionIndex: 1,
  },
  {
    id: 79,
    text: "A member subject to bending is known as a:",
    options: ["Strut", "Beam", "Tie"],
    correctOptionIndex: 1,
  },
  {
    id: 80,
    text: "A member subject to compression is known as a:",
    options: ["Tie", "Strut", "Beam"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "A member subject to tension is known as a:",
    options: ["Strut", "Tie", "Beam"],
    correctOptionIndex: 1,
  },
  {
    id: 82,
    text: "Stress is defined as:",
    options: ["Force × area", "Force ÷ area", "Area ÷ force"],
    correctOptionIndex: 1,
  },
  {
    id: 83,
    text: "Strain is defined as:",
    options: ["Force ÷ original length", "Deformation ÷ original length", "Deformation × original length"],
    correctOptionIndex: 1,
  },
  {
    id: 84,
    text: "The two primary structural stresses are:",
    options: ["Shear and bending", "Tension and compression", "Torsion and shear"],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    text: "Tension tries to:",
    options: ["Squeeze a part together", "Pull an object apart", "Twist an object"],
    correctOptionIndex: 1,
  },
  {
    id: 86,
    text: "Compression tries to:",
    options: ["Pull an object apart", "Squeeze a part together", "Slide an object apart"],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    text: "Shear forces try to:",
    options: ["Pull an object apart", "Slide an object apart", "Twist an object"],
    correctOptionIndex: 1,
  },
  {
    id: 88,
    text: "Torsion is:",
    options: ["A pulling force", "A twisting force", "A squeezing force"],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    text: "Bending force tries to:",
    options: ["Twist an object", "Pull one side apart while squeezing the other together", "Slide an object apart"],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    text: "In flight, the top of a wing spar is under:",
    options: ["Tension", "Compression", "Shear"],
    correctOptionIndex: 1,
  },
  {
    id: 91,
    text: "In flight, the bottom of a wing spar is under:",
    options: ["Compression", "Tension", "Shear"],
    correctOptionIndex: 1,
  },
  {
    id: 92,
    text: "Axial stress is the equivalent of:",
    options: ["Force in a solid", "Pressure in a gas or liquid", "Volume change"],
    correctOptionIndex: 1,
  },
  {
    id: 93,
    text: "Young's Modulus is defined as:",
    options: ["Strain ÷ Stress", "Stress ÷ Strain", "Stress × Strain"],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    text: "Young's Modulus for steel is approximately:",
    options: ["10 × 10⁶ lb/in²", "30 × 10⁶ lb/in²", "15 × 10⁶ lb/in²"],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    text: "Young's Modulus for aluminium is approximately:",
    options: ["30 × 10⁶ lb/in²", "10 × 10⁶ lb/in²", "15 × 10⁶ lb/in²"],
    correctOptionIndex: 1,
  },
  {
    id: 96,
    text: "Strain has no units because:",
    options: ["It is force divided by area", "It is length divided by length", "It is a ratio of forces"],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    text: "A strut is designed to resist:",
    options: ["Tension", "Longitudinal compression", "Bending"],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    text: "A tie is designed to resist:",
    options: ["Compression", "Tension", "Shear"],
    correctOptionIndex: 1,
  },
  {
    id: 99,
    text: "A beam resists load primarily by:",
    options: ["Tension", "Bending", "Compression"],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    text: "A cantilever is supported at:",
    options: ["Both ends", "One end only", "Multiple points"],
    correctOptionIndex: 1,
  },
  {
    id: 101,
    text: "Bulk modulus relates to:",
    options: ["Change in length", "Change in volume due to pressure", "Change in shape"],
    correctOptionIndex: 1,
  },
  {
    id: 102,
    text: "Poisson's Ratio is the ratio of:",
    options: ["Axial strain to transverse strain", "Transverse strain to axial strain", "Stress to strain"],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    text: "Tensile strength describes ability to resist breaking under:",
    options: ["Compressive force", "Tensile (stretching) force", "Shear force"],
    correctOptionIndex: 1,
  },
  {
    id: 104,
    text: "Ultimate tensile strength (UTS) measures:",
    options: ["The elastic limit", "Maximum pulling stress before breaking", "The yield point"],
    correctOptionIndex: 1,
  },
  {
    id: 105,
    text: "Toughness is the ability to resist fracture under:",
    options: ["Constant load", "Impact load", "Gradual load"],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    text: "Elasticity is the ability to:",
    options: ["Retain deformed shape", "Return to original shape after deformation", "Resist scratching"],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    text: "Plasticity is the ability to:",
    options: ["Return to original shape", "Retain any shape imposed by a force", "Resist fracture"],
    correctOptionIndex: 1,
  },
  {
    id: 108,
    text: "Ductility is capacity for plastic deformation under:",
    options: ["Compressive loading", "Tensile loading", "Shear loading"],
    correctOptionIndex: 1,
  },
  {
    id: 109,
    text: "Malleability is capacity for plastic deformation under:",
    options: ["Tensile loading", "Compressive loading", "Impact loading"],
    correctOptionIndex: 1,
  },
  {
    id: 110,
    text: "Brittleness is tendency to fracture with:",
    options: ["Permanent deformation before fracture", "No permanent deformation before fracture", "Gradual warning"],
    correctOptionIndex: 1,
  },
  {
    id: 111,
    text: "A shearing force occurs when a force is applied:",
    options: ["Parallel to the material", "Perpendicular to the material", "At an angle"],
    correctOptionIndex: 1,
  },
  {
    id: 112,
    text: "In a shear force diagram, you start from:",
    options: ["The right side", "The far-left side", "The centre"],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    text: "Bending moment is calculated as:",
    options: ["Force × time", "Perpendicular force × distance from point", "Force ÷ distance"],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    text: "Clockwise bending is taken as:",
    options: ["Positive", "Negative", "Zero"],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    text: "The bending moment at a support should equal:",
    options: ["Maximum value", "Zero", "Half the total load"],
    correctOptionIndex: 1,
  },
  {
    id: 116,
    text: "The most significant forces of attraction between particles are in:",
    options: ["Gases", "Solids", "Liquids"],
    correctOptionIndex: 1,
  },
  {
    id: 117,
    text: "In solids, particles:",
    options: ["Move freely", "Vibrate about fixed positions", "Are widely spaced"],
    correctOptionIndex: 1,
  },
  {
    id: 118,
    text: "Solids have the greatest density because:",
    options: ["Particles are far apart", "Particles are closest together", "Particles have no mass"],
    correctOptionIndex: 1,
  },
  {
    id: 119,
    text: "In liquids, particles:",
    options: ["Are in fixed positions", "Move rapidly but collide frequently", "Have no forces of attraction"],
    correctOptionIndex: 1,
  },
  {
    id: 120,
    text: "Gases have low density because:",
    options: ["Particles are heavy", "Particles are widely spaced", "Particles are tightly packed"],
    correctOptionIndex: 1,
  },
  {
    id: 121,
    text: "Gases are readily compressed because:",
    options: ["Particles are tightly packed", "There is space between particles", "Particles attract each other strongly"],
    correctOptionIndex: 1,
  },
  {
    id: 122,
    text: "Diffusion is fastest in:",
    options: ["Solids", "Gases", "Liquids"],
    correctOptionIndex: 1,
  },
  {
    id: 123,
    text: "Evaporation requires energy to be:",
    options: ["Released to surroundings", "Taken in from surroundings", "Stored in the material"],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    text: "Boiling occurs at:",
    options: ["Any temperature", "A fixed temperature called the boiling point", "Temperatures below freezing"],
    correctOptionIndex: 1,
  },
  {
    id: 125,
    text: "Condensation requires heat to be:",
    options: ["Taken in", "Given out to surroundings", "Stored"],
    correctOptionIndex: 1,
  },
  {
    id: 126,
    text: "Melting is an:",
    options: ["Exothermic process", "Endothermic process", "Isothermal process"],
    correctOptionIndex: 1,
  },
  {
    id: 127,
    text: "Freezing is an:",
    options: ["Endothermic process", "Exothermic process", "Adiabatic process"],
    correctOptionIndex: 1,
  },
  {
    id: 128,
    text: "Sublimation is when a solid becomes:",
    options: ["A liquid", "A gas without becoming liquid", "Another solid"],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    text: "Deposition is when a gas becomes:",
    options: ["A liquid", "A solid without becoming liquid", "Another gas"],
    correctOptionIndex: 1,
  },
  {
    id: 130,
    text: "Pressure is defined as:",
    options: ["Mass × acceleration", "Force ÷ area", "Force × area"],
    correctOptionIndex: 1,
  },
  {
    id: 131,
    text: "The SI unit for pressure is:",
    options: ["Newton", "Pascal (N/m²)", "Joule"],
    correctOptionIndex: 1,
  },
  {
    id: 132,
    text: "One pascal equals:",
    options: ["1 N × m²", "1 N/m²", "1 kg/m²"],
    correctOptionIndex: 1,
  },
  {
    id: 133,
    text: "In meteorology, pressure is measured in:",
    options: ["psi", "Millibar (mb) or hectopascal (hPa)", "Atmosphere"],
    correctOptionIndex: 1,
  },
  {
    id: 134,
    text: "1 mb equals:",
    options: ["100 Pa", "1 hPa", "1000 Pa"],
    correctOptionIndex: 1,
  },
  {
    id: 135,
    text: "Pressure in a fluid acts:",
    options: ["Only downward", "At right angles to any surface", "Only upward"],
    correctOptionIndex: 1,
  },
  {
    id: 136,
    text: "Standard atmospheric pressure at sea level is:",
    options: ["14.7 Pa", "14.7 psi", "101.3 psi"],
    correctOptionIndex: 1,
  },
  {
    id: 137,
    text: "1 atmosphere (ATM) equals:",
    options: ["760 psi", "760 mm Hg", "29.92 mm Hg"],
    correctOptionIndex: 1,
  },
  {
    id: 138,
    text: "1 ATM in pascals is:",
    options: ["14.7 Pa", "101,325 Pa", "1,013 Pa"],
    correctOptionIndex: 1,
  },
  {
    id: 139,
    text: "Atmospheric pressure decreases by approximately 1 psi for every:",
    options: ["1,000 feet", "2,343 feet", "5,000 feet"],
    correctOptionIndex: 1,
  },
  {
    id: 140,
    text: "At about 18,000 ft, pressure is:",
    options: ["One-quarter of sea-level value", "Half the sea-level value", "The same as sea level"],
    correctOptionIndex: 1,
  },
  {
    id: 141,
    text: "Isobars are lines on a weather map joining places of:",
    options: ["Equal temperature", "Equal atmospheric pressure", "Equal wind speed"],
    correctOptionIndex: 1,
  },
  {
    id: 142,
    text: "The closer the isobars are together:",
    options: ["The calmer the weather", "The windier it is", "The higher the temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 143,
    text: "Cabin altitude is a term used to express:",
    options: ["The actual altitude of the aircraft", "Cabin pressure in terms of equivalent altitude above sea level", "The outside air temperature"],
    correctOptionIndex: 1,
  },
  {
    id: 144,
    text: "At a cabin altitude of 8,000 ft, the pressure is approximately:",
    options: ["14.7 psi", "10.92 psi", "2.73 psi"],
    correctOptionIndex: 1,
  },
  {
    id: 145,
    text: "Differential pressure is the difference between:",
    options: ["Inside and outside temperature", "Cabin pressure and atmospheric pressure", "Static and dynamic pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 146,
    text: "Absolute pressure is related to gauge pressure by:",
    options: ["P_abs = P_atm - P_g", "P_abs = P_atm + P_g", "P_abs = P_g - P_atm"],
    correctOptionIndex: 1,
  },
  {
    id: 147,
    text: "psig stands for:",
    options: ["pounds per square inch absolute", "pounds per square inch gauge", "pounds per square inch differential"],
    correctOptionIndex: 1,
  },
  {
    id: 148,
    text: "psia stands for:",
    options: ["pounds per square inch gauge", "pounds per square inch absolute", "pounds per square inch atmospheric"],
    correctOptionIndex: 1,
  },
  {
    id: 149,
    text: "A tyre pressure gauge reading of 0 psi means:",
    options: ["The tyre is completely empty", "The pressure inside equals atmospheric pressure", "There is a vacuum inside"],
    correctOptionIndex: 1,
  },
  {
    id: 150,
    text: "A barometer measures:",
    options: ["Temperature", "Atmospheric pressure", "Humidity"],
    correctOptionIndex: 1,
  },
  {
    id: 151,
    text: "A standard mercury barometer uses:",
    options: ["Water", "Mercury (Hg)", "Alcohol"],
    correctOptionIndex: 1,
  },
  {
    id: 152,
    text: "The standard temperature for reading a mercury barometer is:",
    options: ["20°C", "0°C", "15°C"],
    correctOptionIndex: 1,
  },
  {
    id: 153,
    text: "An aneroid barometer uses:",
    options: ["A column of mercury", "A flexible metal vacuum chamber", "A liquid-filled tube"],
    correctOptionIndex: 1,
  },
  {
    id: 154,
    text: "The aneroid cell is made from:",
    options: ["Steel", "An alloy of beryllium and copper", "Aluminium"],
    correctOptionIndex: 1,
  },
  {
    id: 155,
    text: "The formula relating force, pressure, and area is:",
    options: ["F = A/P", "F = P × A", "F = P/A"],
    correctOptionIndex: 1,
  },
  {
    id: 156,
    text: "The formula for area of a circle is:",
    options: ["A = πd", "A = πr²", "A = 2πr"],
    correctOptionIndex: 1,
  },
  {
    id: 157,
    text: "π is approximately:",
    options: ["2.14", "3.14 or 22/7", "1.57"],
    correctOptionIndex: 1,
  },
  {
    id: 158,
    text: "Pascal's law states that pressure in a fluid:",
    options: ["Acts only downward", "Acts equally in all directions", "Depends on container shape"],
    correctOptionIndex: 1,
  },
  {
    id: 159,
    text: "Pressure in a liquid is:",
    options: ["Independent of depth", "Directly proportional to depth", "Inversely proportional to depth"],
    correctOptionIndex: 1,
  },
  {
    id: 160,
    text: "One cubic foot of water weighs:",
    options: ["62.4 lb", "62.4 lb", "64.4 lb"],
    correctOptionIndex: 0,
  },
  {
    id: 161,
    text: "The pressure at the bottom of a 1 ft column of water is:",
    options: ["0.433 psi", "0.433 psi", "14.7 psi"],
    correctOptionIndex: 0,
  },
  {
    id: 162,
    text: "The formula for pressure due to fluid head is:",
    options: ["P = h/D", "P = hD", "P = D/h"],
    correctOptionIndex: 1,
  },
  {
    id: 163,
    text: "In a hydraulic system with different piston areas, force is:",
    options: ["The same on both pistons", "Proportional to the area of each piston", "Inversely proportional to area"],
    correctOptionIndex: 1,
  },
  {
    id: 164,
    text: "The ratio of output force to input force equals the ratio of:",
    options: ["Input area to output area", "Output area to input area", "Distance moved"],
    correctOptionIndex: 1,
  },
  {
    id: 165,
    text: "The distances pistons move are:",
    options: ["Proportional to their areas", "Inversely proportional to their areas", "Equal regardless of area"],
    correctOptionIndex: 1,
  },
  {
    id: 166,
    text: "A hydraulic jack uses a:",
    options: ["Small output piston and large input piston", "Small input piston and large output piston", "Equal sized pistons"],
    correctOptionIndex: 1,
  },
  {
    id: 167,
    text: "In a hydraulic brake system, pressure from the master cylinder:",
    options: ["Decreases at each wheel cylinder", "Is transmitted undiminished to all wheel cylinders", "Only goes to one wheel"],
    correctOptionIndex: 1,
  },
  {
    id: 168,
    text: "An accumulator stores:",
    options: ["Electrical energy", "Hydraulic fluid under pressure", "Compressed air only"],
    correctOptionIndex: 1,
  },
  {
    id: 169,
    text: "The pre-charge pressure in an accumulator is measured when:",
    options: ["The system is at full pressure", "There is no hydraulic pressure", "The pump is running"],
    correctOptionIndex: 1,
  },
  {
    id: 170,
    text: "Accumulators can supply emergency power for up to:",
    options: ["10 minutes", "One hour", "5 hours"],
    correctOptionIndex: 1,
  },
  {
    id: 171,
    text: "The formula for pressure due to fluid depth is:",
    options: ["P = ρ/h", "P = ρgh", "P = ρg/h"],
    correctOptionIndex: 1,
  },
  {
    id: 172,
    text: "Total pressure on a submerged object equals:",
    options: ["ρgh only", "Atmospheric pressure + ρgh", "Atmospheric pressure only"],
    correctOptionIndex: 1,
  },
  {
    id: 173,
    text: "In water at 10 m depth, pressure experienced by a diver is:",
    options: ["The same as at surface", "Two times atmospheric pressure", "Ten times atmospheric pressure"],
    correctOptionIndex: 1,
  },
  {
    id: 174,
    text: "Archimedes' principle states that an object in a fluid is buoyed up by a force equal to:",
    options: ["The weight of the object", "The weight of the displaced fluid", "The volume of the object"],
    correctOptionIndex: 1,
  },
  {
    id: 175,
    text: "The story of Archimedes involves him discovering the principle while:",
    options: ["Walking in a garden", "Stepping into a bathtub", "Eating dinner"],
    correctOptionIndex: 1,
  },
  {
    id: 176,
    text: "\"Eureka\" is Greek for:",
    options: ["I have found it", "I have found it", "Help me"],
    correctOptionIndex: 0,
  },
  {
    id: 177,
    text: "An object floats if its density is:",
    options: ["Greater than the fluid", "Less than the fluid", "Equal to the fluid"],
    correctOptionIndex: 1,
  },
  {
    id: 178,
    text: "The proportion of a floating object that submerges equals the ratio of:",
    options: ["Object volume to fluid volume", "Object density to fluid density", "Fluid density to object density"],
    correctOptionIndex: 1,
  },
  {
    id: 179,
    text: "The weight density of ocean water is approximately:",
    options: ["62.4 lb/ft³", "64.4 lb/ft³", "54.9 lb/ft³"],
    correctOptionIndex: 2,
  },
  {
    id: 180,
    text: "The weight density of fresh water is approximately:",
    options: ["64.4 lb/ft³", "62.4 lb/ft³", "54.9 lb/ft³"],
    correctOptionIndex: 1,
  },
  {
    id: 181,
    text: "Submarines control depth by:",
    options: ["Changing shape", "Taking on or pumping out water ballast", "Adjusting speed"],
    correctOptionIndex: 1,
  },
  {
    id: 182,
    text: "Buoyant forces also exist in:",
    options: ["Only liquids", "Gases as well as liquids", "Only solids"],
    correctOptionIndex: 1,
  },
  {
    id: 183,
    text: "A hot air balloon rises because:",
    options: ["Hot air is denser than cold air", "The weight of displaced air is greater than the balloon's weight", "There is no gravity"],
    correctOptionIndex: 1,
  },
];
