import type { Question } from "@shared/schema";

export const propulsiveForceReadingPassage = `Theme: Introduction & Propulsive Force
Propellers are one of the primary mechanisms for converting engine power into thrust for aircraft propulsion. The earliest practical aircraft designs used propellers to create thrust, with designs evolving from flat boards to sophisticated aerofoil-shaped blades made from materials such as aluminium alloy and composite materials. A propeller converts engine power into propulsive force by imparting rearward motion to a mass of air, moving a large mass of air rearward at a relatively slow speed compared to gas turbine engines.

Theme: Basic Terms & Blade Geometry
Propeller blades have clearly defined edges: the leading edge and trailing edge. The blade angle is the angle between the propeller's plane of rotation and the chord line. A blade station is a reference position on a blade at a specified distance from the hub centre. Blade pitch represents the distance a propeller section will move forward in one revolution, and pitch distribution describes the gradual twist in the propeller blade from shank to tip.

Theme: Blade Angle, Pitch & Slip
The blade angle comprises two components: the angle of attack and the helix angle. Geometric pitch is the theoretical distance a propeller would move in one revolution if it were 100% efficient, while effective pitch is the actual distance a propeller advances through the air in one revolution. Propeller slip is the difference between geometric pitch and effective pitch.

Theme: The Blade Element & Angle of Attack
The angle of attack for a propeller blade is the acute angle between the chord line and the relative wind. At constant RPM, if the forward velocity of the aircraft increases, the angle of attack decreases. Conversely, if RPM increases, the angle of attack increases. The two airflow components that affect the angle of attack are airflow due to RPM and airflow due to aircraft true airspeed (TAS). In a dive with significantly increased forward velocity, the angle of attack can become negative, causing the propeller to exert a retarding force.

Theme: Blade Twist
Propeller blades are twisted to maintain an efficient angle of attack from root to tip. The optimum angle of attack for maximum propeller efficiency is 4-6 degrees.

Theme: Propeller Configuration
A tractor propeller pulls the airframe and is fitted forward of the mainplane, while a pusher propeller is usually fitted behind the mainplane. A contra-rotating propeller configuration consists of two propellers on one shaft, driven by the same engine, rotating in opposite directions. Counter-rotating propellers on multi-engine aircraft balance the torque effects on the airframe.

Theme: Propeller Solidity
Solidity describes the ability of the propeller to absorb power from the engine. It is defined as the surface area of the propeller divided by the surface area of the propeller disc. Solidity can be increased by increasing the number of blades.

Theme: Propeller Efficiency
Propeller efficiency is calculated as output power divided by input power. The efficiency of a fixed-pitch propeller is limited to a single airspeed because the angle of attack decreases as aircraft velocity increases. At zero forward speed, propeller efficiency is zero. A fixed-pitch propeller designed to be efficient during climb is known as a climb propeller.

Theme: Tip Speed
Helical tip velocity is the vector sum of rotational velocity and translational velocity. Propeller efficiency begins to decrease dramatically when the helical tip velocity exceeds 0.85 Mach. The sudden reduction in efficiency at high tip speeds is caused by compressibility effects and shockwaves.

Theme: Right and Left-Handed Propellers
A right-handed propeller rotates clockwise when viewed from aft looking forward. If a pilot sees the upper blade of the propeller pass the windscreen moving from left to right, it is a right-handed propeller.

Theme: Forces on a Blade Element
On a propeller, the aerodynamic force parallel to the flight path is called thrust. The resistance to motion in the plane of rotation is called torque force.

Theme: Windmilling
During windmilling, the pitch of a variable pitch propeller goes fine. In the windmilling condition, the total reaction on the blade results in thrust in the reverse direction and torque assisting rotation.

Theme: Feathering
The primary purpose of feathering a propeller after an engine failure is to reduce drag to a minimum. A feathered propeller blade is set at approximately 90 degrees to the plane of rotation. A slightly negative angle of attack is used on a feathered propeller blade to prevent the propeller from turning.

Theme: Reverse Thrust
Reverse thrust is obtained by turning the propeller blades to approximately negative 20 degrees. A common use for reverse thrust is as additional braking after landing. On a wet runway, reverse thrust is preferred over wheel brakes because it does not cause the wheels to lock and skid.

Theme: Forces Acting on the Propeller
Centrifugal force puts the greatest stress on a propeller, trying to pull the blades out of the hub. Thrust bending force attempts to bend the propeller blades forward at the tips. Torque bending force is caused by the drag of the blades as they turn through the air.

Theme: Aerodynamic & Centrifugal Twisting Moments
Aerodynamic Twisting Moment (ATM) tries to twist a blade to a higher angle (coarse-seeking). Centrifugal Twisting Moment (CTM) tries to decrease the blade angle (fine-seeking). At operational RPM, Centrifugal Twisting Moment (CTM) is generally greater. Counterweights on a propeller oppose the blade's natural CTM and help move the blade to a higher pitch.

Theme: Turning Moments & Pitch Range
When a propeller is windmilling, ATM reverses and becomes fine-seeking. The total pitch range of a high-performance propeller extends from feathered to reverse. Pitch stops prevent inadvertent operation outside the desired pitch range.

Theme: Handling Effects - Multiple Topics
Various handling effects affect aircraft with propellers, including the Asymmetric Effect (P-Factor) caused by the downward moving blade having a greater angle of attack than the upward moving blade, the Slipstream Effect which causes air to rotate as it passes over the aircraft, Torque Reaction resulting from Newton's third law of motion, and the Gyroscopic Effect (Precession) of a rotating propeller.`;

export const propulsiveForceQuestions: Question[] = [
  { id: 1, text: "According to the text, what did the earliest practical aircraft designs use to create thrust?", options: ["Jet engines", "Propellers", "Rocket motors", "Turbofans", "Electric motors"], correctOptionIndex: 1 },
  { id: 2, text: "What improved propeller design replaced flat boards to create thrust through aerodynamic action?", options: ["Square-shaped blades", "Aerofoil shapes", "Metal rods", "Wooden planks", "Titanium sheets"], correctOptionIndex: 1 },
  { id: 3, text: "What material became widely used for propellers due to its structural strength?", options: ["Composite material", "Wood", "Aluminium alloy", "Steel", "Carbon fiber"], correctOptionIndex: 2 },
  { id: 4, text: "What is the function of a propeller?", options: ["To convert propulsive force into engine power", "To convert engine power into propulsive force", "To stabilize the aircraft in flight", "To control engine RPM", "To cool the engine"], correctOptionIndex: 1 },
  { id: 5, text: "How does a propeller produce a forward force?", options: ["By pulling a small mass of air forward at high speed", "By imparting rearward motion to a mass of air", "By creating a vacuum in front of the blades", "By reducing air pressure", "By deflecting wind upward"], correctOptionIndex: 1 },
  { id: 6, text: "How does a propeller compare to a gas turbine engine in terms of the air it moves?", options: ["It moves a small mass of air rearward at a high speed", "It moves a large mass of air rearward at a relatively slow speed", "It moves the same mass of air at the same speed", "It moves less air forward", "It does not move air"], correctOptionIndex: 1 },
  { id: 7, text: "What are the two main edges of a propeller blade called?", options: ["Upper edge and lower edge", "Leading edge and trailing edge", "Root edge and tip edge", "Front edge and back edge", "Curved edge and flat edge"], correctOptionIndex: 1 },
  { id: 8, text: "What is the blade angle?", options: ["The angle between the chord line and the longitudinal axis of the aircraft", "The angle between the propeller's plane of rotation and the chord line", "The angle between the blade and the oncoming wind", "The angle of the blade at the tip", "The angle of blade curvature"], correctOptionIndex: 1 },
  { id: 9, text: "What is a blade station?", options: ["The point where the blade attaches to the hub", "The tip of the blade", "A reference position on a blade at a specified distance from the hub centre", "The length of the blade", "The width measurement of the blade"], correctOptionIndex: 2 },
  { id: 10, text: "What is blade pitch?", options: ["The angle of the blade relative to the ground", "The distance a propeller section will move forward in one revolution", "The width of the propeller blade", "The rotation speed of the propeller", "The pitch control mechanism"], correctOptionIndex: 1 },
  { id: 11, text: "What is pitch distribution?", options: ["The number of blades on a propeller", "The material used to make the blade", "The gradual twist in the propeller blade from shank to tip", "The distance from hub to tip", "The angle at the blade root"], correctOptionIndex: 2 },
  { id: 12, text: "What two components make up the blade angle?", options: ["The angle of attack and the helix angle", "The drag angle and the lift angle", "The rotational angle and the forward angle", "The pitch angle and the twist angle", "The torque angle and the thrust angle"], correctOptionIndex: 0 },
  { id: 13, text: "What is geometric pitch?", options: ["The actual distance a propeller advances in one revolution", "The theoretical distance a propeller would move in one revolution if it were 100% efficient", "The difference between the effective pitch and the blade angle", "The distance between blade stations", "The maximum pitch the blade can reach"], correctOptionIndex: 1 },
  { id: 14, text: "What is effective pitch?", options: ["The theoretical distance a propeller would move in one revolution", "The actual distance a propeller advances through the air in one revolution", "The angle of the blade relative to the plane of rotation", "The distance from hub to blade root", "The pitch at cruise speed"], correctOptionIndex: 1 },
  { id: 15, text: "What is propeller slip?", options: ["The difference between geometric pitch and effective pitch", "The loss of engine power", "The movement of the blade in the hub", "The unwanted blade vibration", "The twisting of the propeller shaft"], correctOptionIndex: 0 },
  { id: 16, text: "If a propeller has a geometric pitch of 50 inches but only advances 35 inches in one revolution, what is its slip?", options: ["85 inches", "15 inches", "50 inches", "35 inches", "30 inches"], correctOptionIndex: 1 },
  { id: 17, text: "The angle of attack for a propeller blade is the acute angle between the chord line and the:", options: ["Plane of rotation", "Relative wind", "Leading edge", "Fuselage axis", "Ground"], correctOptionIndex: 1 },
  { id: 18, text: "At a constant RPM, if the forward velocity of the aircraft increases, what happens to the angle of attack?", options: ["It increases", "It decreases", "It remains the same", "It becomes negative", "It oscillates"], correctOptionIndex: 1 },
  { id: 19, text: "If the RPM of the propeller increases, what happens to the angle of attack?", options: ["It increases", "It decreases", "It remains the same", "It goes to zero", "It becomes feathered"], correctOptionIndex: 0 },
  { id: 20, text: "In a dive, if the forward velocity increases significantly, the angle of attack can become negative, causing the propeller to:", options: ["Produce maximum thrust", "Exert a retarding force", "Increase its RPM", "Feather automatically", "Reverse direction"], correctOptionIndex: 1 },
  { id: 21, text: "The two airflow components that affect the angle of attack are:", options: ["Lift and drag", "Thrust and torque", "Airflow due to RPM and airflow due to aircraft TAS", "Wind and rain", "Vertical and horizontal flow"], correctOptionIndex: 2 },
  { id: 22, text: "Why are propeller blades twisted?", options: ["To make them look more aerodynamic", "To maintain an efficient angle of attack from root to tip", "To increase the blade's structural strength", "To reduce blade weight", "To increase blade stiffness"], correctOptionIndex: 1 },
  { id: 23, text: "What is the optimum angle of attack for maximum propeller efficiency?", options: ["10-12 degrees", "4-6 degrees", "0-2 degrees", "15-20 degrees", "25-30 degrees"], correctOptionIndex: 1 },
  { id: 24, text: "What is a tractor propeller configuration?", options: ["A propeller that pushes the airframe and is fitted behind the mainplane", "A propeller that pulls the airframe and is fitted forward of the mainplane", "Two propellers on one shaft rotating in opposite directions", "A propeller used for towing operations", "A pusher-type configuration"], correctOptionIndex: 1 },
  { id: 25, text: "A pusher propeller is usually fitted:", options: ["Forward of the mainplane", "Behind the mainplane", "On the wingtips", "Under the fuselage", "On the tail boom"], correctOptionIndex: 1 },
  { id: 26, text: "A contra-rotating propeller configuration consists of:", options: ["Two propellers on separate shafts rotating in the same direction", "Two propellers on one shaft, driven by the same engine, rotating in opposite directions", "Propellers on a multi-engine aircraft rotating in opposite directions", "Multiple single propellers", "A front and rear propeller in sequence"], correctOptionIndex: 1 },
  { id: 27, text: "What is the purpose of counter-rotating propellers on a multi-engine aircraft?", options: ["To increase the total thrust", "To balance the torque effects on the airframe", "To reduce the propeller disc area", "To improve fuel efficiency", "To reduce noise"], correctOptionIndex: 1 },
  { id: 28, text: "What does the term solidity describe in relation to a propeller?", options: ["The strength of the blade material", "The ability of the propeller to absorb power from the engine", "The speed at which the propeller rotates", "The weight of the propeller", "The durability of the blades"], correctOptionIndex: 1 },
  { id: 29, text: "How is solidity defined?", options: ["The surface area of the propeller divided by the surface area of the propeller disc", "The number of blades times the blade length", "The propeller diameter divided by the number of blades", "The blade chord multiplied by blade count", "The blade thickness times blade area"], correctOptionIndex: 0 },
  { id: 30, text: "Which of the following is a way to increase propeller solidity?", options: ["Decreasing the number of blades", "Decreasing the chord of the blades", "Increasing the number of blades", "Reducing blade twist", "Using lighter materials"], correctOptionIndex: 2 },
  { id: 31, text: "What is the formula for propeller efficiency?", options: ["Input power / Output power", "Output power / Input power", "Thrust power / Torque power", "Power × RPM", "Thrust / Torque"], correctOptionIndex: 1 },
  { id: 32, text: "The efficiency of a fixed-pitch propeller is limited to a single airspeed because:", options: ["The blade pitch can be varied in flight", "The angle of attack decreases as aircraft velocity increases", "The engine RPM cannot be changed", "The propeller slip increases", "The blade stalls"], correctOptionIndex: 1 },
  { id: 33, text: "What is the efficiency of a propeller at zero forward speed?", options: ["100%", "Maximum efficiency", "Zero", "50%", "Variable"], correctOptionIndex: 2 },
  { id: 34, text: "A fixed-pitch propeller designed to be efficient during the climb is known as a:", options: ["Cruise propeller", "Climb propeller", "Constant speed propeller", "Heavy-duty propeller", "Performance propeller"], correctOptionIndex: 1 },
  { id: 35, text: "Helical tip velocity is the vector sum of:", options: ["Rotational velocity and translational velocity", "Forward velocity and slipstream velocity", "Blade angle and angle of attack", "Pitch and twist", "RPM and airspeed"], correctOptionIndex: 0 },
  { id: 36, text: "Propeller efficiency begins to decrease dramatically when the helical tip velocity exceeds:", options: ["0.50 Mach", "0.85 Mach", "1.00 Mach", "0.65 Mach", "1.20 Mach"], correctOptionIndex: 1 },
  { id: 37, text: "What aerodynamic effect causes a sudden reduction in efficiency at high tip speeds?", options: ["Compressibility effects and shockwaves", "Increased angle of attack", "Laminar flow separation", "Blade stall", "Centrifugal effects"], correctOptionIndex: 0 },
  { id: 38, text: "A right-handed propeller rotates in which direction when viewed from aft looking forward?", options: ["Anti-clockwise", "Clockwise", "It does not rotate", "Randomly", "Side to side"], correctOptionIndex: 1 },
  { id: 39, text: "If a pilot sees the upper blade of the propeller pass the windscreen moving from left to right, what type of propeller is it?", options: ["Left-handed", "Right-handed", "Contra-rotating", "Fixed-pitch", "Variable-pitch"], correctOptionIndex: 1 },
  { id: 40, text: "On a propeller, the aerodynamic force parallel to the flight path is called:", options: ["Drag", "Torque", "Thrust", "Lift", "Resistance"], correctOptionIndex: 2 },
  { id: 41, text: "On a propeller, the resistance to motion in the plane of rotation is called:", options: ["Torque force", "Thrust force", "Lift force", "Drag force", "Reaction force"], correctOptionIndex: 0 },
  { id: 42, text: "What happens to the pitch of a variable pitch propeller during windmilling?", options: ["It goes coarse", "It goes fine", "It remains constant", "It feathers", "It goes to reverse"], correctOptionIndex: 1 },
  { id: 43, text: "In the windmilling condition, the total reaction on the blade results in:", options: ["Thrust in the forward direction and torque assisting rotation", "Thrust in the reverse direction and torque assisting rotation", "Zero thrust and zero torque", "Maximum thrust", "Negative torque"], correctOptionIndex: 1 },
  { id: 44, text: "What is the primary purpose of feathering a propeller after an engine failure?", options: ["To increase thrust from the failed engine", "To reduce drag to a minimum", "To increase the RPM of the failed engine", "To stop the engine", "To engage reverse thrust"], correctOptionIndex: 1 },
  { id: 45, text: "A feathered propeller blade is set at approximately what angle to the plane of rotation?", options: ["20 degrees", "45 degrees", "90 degrees", "135 degrees", "180 degrees"], correctOptionIndex: 2 },
  { id: 46, text: "Why is a slightly negative angle of attack used on a feathered propeller blade?", options: ["To increase drag", "To prevent the propeller from turning", "To allow the propeller to windmill", "To increase efficiency", "To reduce vibration"], correctOptionIndex: 1 },
  { id: 47, text: "Reverse thrust is typically obtained by turning the propeller blades to approximately:", options: ["Negative 20 degrees", "Positive 45 degrees", "90 degrees", "Negative 45 degrees", "Zero degrees"], correctOptionIndex: 0 },
  { id: 48, text: "What is a common use for reverse thrust?", options: ["To increase climb performance", "As additional braking after landing", "To feather the propeller in flight", "To increase engine power", "To reduce propeller noise"], correctOptionIndex: 1 },
  { id: 49, text: "Why might reverse thrust be preferred over wheel brakes on a wet runway?", options: ["It stops the aircraft faster", "It does not cause the wheels to lock and skid", "It uses less fuel", "It is quieter", "It reduces tire wear"], correctOptionIndex: 1 },
  { id: 50, text: "Which force puts the greatest stress on a propeller, trying to pull the blades out of the hub?", options: ["Thrust bending force", "Torque bending force", "Centrifugal force", "Aerodynamic force", "Shear force"], correctOptionIndex: 2 },
  { id: 51, text: "Which force attempts to bend the propeller blades forward at the tips?", options: ["Torque bending force", "Thrust bending force", "Centrifugal force", "Torsional force", "Lateral force"], correctOptionIndex: 1 },
  { id: 52, text: "Torque bending force is caused by the:", options: ["Lift of the blades", "Drag of the blades as they turn through the air", "Centrifugal force on the counterweights", "Weight of the propeller", "Engine vibration"], correctOptionIndex: 1 },
  { id: 53, text: "Aerodynamic Twisting Moment (ATM) tries to twist a blade to a:", options: ["Lower angle (fine-seeking)", "Higher angle (coarse-seeking)", "Feathered angle", "Reverse angle", "Neutral angle"], correctOptionIndex: 1 },
  { id: 54, text: "Centrifugal Twisting Moment (CTM) tries to:", options: ["Increase the blade angle (coarse-seeking)", "Decrease the blade angle (fine-seeking)", "Feather the blade", "Reverse the blade", "Lock the blade"], correctOptionIndex: 1 },
  { id: 55, text: "At operational RPM, which force is generally greater?", options: ["Aerodynamic Twisting Moment (ATM)", "Centrifugal Twisting Moment (CTM)", "They are equal", "Neither is significant", "It depends on airspeed"], correctOptionIndex: 1 },
  { id: 56, text: "What is the function of counterweights on a propeller?", options: ["To increase the weight of the blade", "To oppose the blade's natural CTM and help move the blade to a higher pitch", "To reduce the propeller's moment of inertia", "To balance vibration", "To assist blade feathering"], correctOptionIndex: 1 },
  { id: 57, text: "When a propeller is windmilling, what happens to the direction of ATM?", options: ["It reverses and becomes fine-seeking", "It remains coarse-seeking", "It cancels out the CTM", "It becomes zero", "It increases"], correctOptionIndex: 0 },
  { id: 58, text: "The total pitch range of a high-performance propeller extends from:", options: ["Fine to coarse", "Feathered to reverse", "Ground fine to flight fine", "Minimum to maximum", "Climb to cruise"], correctOptionIndex: 1 },
  { id: 59, text: "What is the purpose of pitch stops?", options: ["To increase the pitch range", "To prevent inadvertent operation outside the desired pitch range", "To lock the propeller in the feathered position", "To increase propeller efficiency", "To reduce vibration"], correctOptionIndex: 1 },
  { id: 60, text: "The Asymmetric Effect (P-Factor) is caused by:", options: ["The torque reaction of the engine", "The propeller slipstream hitting the fin", "The downward moving blade having a greater angle of attack than the upward moving blade", "Engine imbalance", "Unequal blade length"], correctOptionIndex: 2 },
  { id: 61, text: "For a right-handed propeller in a nose-up attitude, the yawing moment from P-factor will be to the:", options: ["Left", "Right", "Up", "Down", "Neutral"], correctOptionIndex: 0 },
  { id: 62, text: "The slipstream effect, also known as the corkscrew effect, causes the air to:", options: ["Flow straight back from the propeller", "Rotate as it passes over the aircraft", "Compress in front of the propeller", "Expand behind the propeller", "Rise vertically"], correctOptionIndex: 1 },
  { id: 63, text: "An aeroplane with a right-handed propeller will tend to yaw:", options: ["To the left due to the slipstream effect", "To the right due to the slipstream effect", "Not at all", "Up and down", "In a random direction"], correctOptionIndex: 0 },
  { id: 64, text: "Which type of aircraft does not experience a slipstream effect?", options: ["Single-engine aircraft", "Twin-engine aircraft with both propellers rotating the same direction", "Aircraft with contra-rotating propellers", "Pusher-configuration aircraft", "High-performance aircraft"], correctOptionIndex: 2 },
  { id: 65, text: "Torque reaction is a result of:", options: ["Newton's first law of motion", "Newton's third law of motion", "The gyroscopic effect", "Centrifugal force", "Angular momentum"], correctOptionIndex: 1 },
  { id: 66, text: "For a right-handed propeller, the torque reaction will cause the aircraft to:", options: ["Roll to the left", "Roll to the right", "Yaw to the left", "Pitch up", "Pitch down"], correctOptionIndex: 0 },
  { id: 67, text: "How can torque reaction be corrected on some aircraft?", options: ["By offsetting the fin", "By using 'wash in' on the downgoing wing and 'wash out' on the upgoing wing", "By using a heavier propeller", "By increasing engine power", "By adjusting blade pitch"], correctOptionIndex: 1 },
  { id: 68, text: "The gyroscopic effect of a rotating propeller is known as:", options: ["Torque reaction", "P-factor", "Precession", "Yaw effect", "Pitch effect"], correctOptionIndex: 2 },
  { id: 69, text: "If an aircraft with a right-handed propeller is yawed to the right, what gyroscopic effect will it experience?", options: ["A nose-up pitching moment", "A nose-down pitching moment", "A roll to the left", "A roll to the right", "No effect"], correctOptionIndex: 1 },
  { id: 70, text: "On a twin-engine aircraft with both propellers rotating clockwise, which engine is typically the 'critical engine'?", options: ["The right engine", "The left engine", "Both engines are equally critical", "Neither is critical", "The upper engine"], correctOptionIndex: 1 },
  { id: 71, text: "Why is the critical engine more critical?", options: ["Its failure results in a larger yawing moment from the operating engine", "It produces more thrust than the other engine", "It is located closer to the fuselage", "It has a higher compression ratio", "It operates at higher RPM"], correctOptionIndex: 0 },
  { id: 72, text: "Aircraft with counter-rotating propellers typically:", options: ["Have a more critical left engine", "Have a more critical right engine", "Do not have a critical engine defined by the P-factor mechanism", "Have equally critical engines", "Have variable critical engines"], correctOptionIndex: 2 },
  { id: 73, text: "What is a common source of mechanical vibrations in a propeller system?", options: ["Transonic airflow over the tip", "Power pulses from a piston engine", "The gyroscopic effect", "Blade material fatigue", "Excessive engine oil temperature"], correctOptionIndex: 1 },
  { id: 74, text: "What do the red or amber arcs on a tachometer indicate?", options: ["The most efficient operating range", "A critical RPM range that should be avoided for prolonged operation", "The maximum RPM", "The minimum RPM", "The cruise RPM"], correctOptionIndex: 1 },
  { id: 75, text: "Resonance occurs when:", options: ["The blade's natural frequency of vibration matches the frequency of applied forces", "The propeller is in perfect balance", "The aircraft reaches its maximum speed", "The engine is at idle", "The propeller slip is maximum"], correctOptionIndex: 0 },
  { id: 76, text: "On a traditional piston-engine aircraft, the propeller is usually connected to the engine:", options: ["Through a reduction gearbox", "Directly to the output shaft", "Through a hydraulic coupling", "Through a fluid coupling", "Through a magnetic coupling"], correctOptionIndex: 1 },
  { id: 77, text: "A single-shaft turboprop engine is one where the propeller reduction gears are driven by:", options: ["A free turbine independent of the gas generator", "The same shaft that drives the compressor", "An electric motor", "An auxiliary power unit", "A hydraulic pump"], correctOptionIndex: 1 },
  { id: 78, text: "The TPE331 is an example of what type of turboprop engine?", options: ["Free-turbine", "Single-shaft/gear coupled", "Piston engine", "Dual-spool turboprop", "Experimental engine"], correctOptionIndex: 1 },
  { id: 79, text: "A free-turbine engine has a turbine stage on a shaft that is:", options: ["Connected to the compressor shaft", "Independent of the shaft that drives the compressor", "Used only for starting the engine", "Part of the gearbox", "Directly driving the propeller"], correctOptionIndex: 1 },
  { id: 80, text: "What is a key operational difference between the PT6 free-turbine engine and the TPE331 single-shaft engine during shutdown?", options: ["The PT6 propeller goes to feather, while the TPE331 propeller is held against low pitch stops", "The TPE331 propeller goes to feather, while the PT6 is held against low pitch stops", "Both propellers go to reverse", "The PT6 reverses while TPE331 feathers", "There is no difference"], correctOptionIndex: 0 },
  { id: 81, text: "What is ground clearance?", options: ["The clearance between the side of the fuselage and the propeller tip", "The clearance between the propeller tip and the ground when the aircraft is in its normal flying attitude", "The distance from the propeller hub to the ground", "The clearance when the aircraft is on jacks", "The clearance during takeoff rotation"], correctOptionIndex: 1 },
  { id: 82, text: "On a multi-engined aircraft, what is fuselage clearance?", options: ["The clearance between the propeller tip and the ground", "The clearance between the propeller tip and the wingtip", "The clearance between the side of the fuselage and the propeller tip", "The clearance between engines", "The clearance near the tail"], correctOptionIndex: 2 },
  { id: 83, text: "What is the part of the propeller blade that attaches to the hub called?", options: ["The tip", "The shank", "The face", "The root", "The station"], correctOptionIndex: 1 },
  { id: 84, text: "A propeller blade's angle of attack is determined by which two factors?", options: ["Blade pitch and blade length", "Propeller RPM and aircraft forward velocity", "Engine power and altitude", "Wing angle and fuselage trim", "Environmental temperature and pressure"], correctOptionIndex: 1 },
  { id: 85, text: "What limits the length of a propeller blade?", options: ["The weight of the aircraft", "Shockwave effects as tip speed approaches Mach 1", "The material strength of the hub", "Engine power limitations", "Noise regulations"], correctOptionIndex: 1 },
  { id: 86, text: "In a contra-rotating propeller, the rear propeller is usually:", options: ["Of a larger diameter than the front", "Of a smaller diameter than the front", "The same diameter as the front", "Twice the diameter of the front", "Four times larger than the front"], correctOptionIndex: 1 },
  { id: 87, text: "Solidity can be increased by increasing the chord of the blades. What is a disadvantage of this method?", options: ["It increases tip speed", "It reduces blade efficiency due to a lower aspect ratio", "It makes the propeller too heavy", "It creates excessive vibration", "It requires more engine power"], correctOptionIndex: 1 },
  { id: 88, text: "At a constant RPM and TAS, the angle of attack of a fixed-pitch propeller will ______ as aircraft speed increases.", options: ["Increase", "Decrease", "Remain the same", "Oscillate", "Become negative"], correctOptionIndex: 1 },
  { id: 89, text: "What does a propeller governor do?", options: ["It changes the engine power setting", "It maintains a constant propeller RPM regardless of airspeed or power setting", "It increases the propeller's geometric pitch", "It feathers the propeller", "It adjusts blade twist"], correctOptionIndex: 1 },
  { id: 90, text: "The most critical location for vibrational stress on a propeller is:", options: ["At the hub", "At the blade root", "About 6 inches from the propeller tip", "At blade station 50%", "At the leading edge"], correctOptionIndex: 2 },
  { id: 91, text: "Why is a flywheel sometimes used on a piston engine?", options: ["To increase power output", "To further reduce vibration and encourage smooth propeller operation", "To help start the engine", "To store rotational energy", "To dampen oscillations"], correctOptionIndex: 1 },
  { id: 92, text: "In a free-turbine engine like the PT6, what rotates during an engine start?", options: ["Only the gas generator turbine", "The power turbine and propeller", "Both the gas generator and power turbine", "Only the propeller", "Nothing rotates until full power"], correctOptionIndex: 0 },
  { id: 93, text: "A tail-dragger aircraft will experience the most pronounced asymmetric effect during:", options: ["Cruise flight", "The take-off roll", "Landing", "Slow flight", "Descent"], correctOptionIndex: 1 },
  { id: 94, text: "What is one advantage of contra-rotating propellers over a single 6-bladed propeller?", options: ["They are simpler to manufacture", "They reduce disc area while maintaining thrust", "They are more efficient at low speeds", "They reduce engine vibration", "They weigh less"], correctOptionIndex: 1 },
  { id: 95, text: "The property of a gyroscope where a moment produced at right angles to an applied moment is called:", options: ["Precession", "Torque reaction", "P-factor", "Gyroscopic stability", "Angular momentum"], correctOptionIndex: 0 },
  { id: 96, text: "To prevent the selection of reverse pitch while airborne, a propeller system often incorporates:", options: ["A mechanical lock", "A red warning light", "A higher blade angle stop", "An altitude sensor", "A speed switch"], correctOptionIndex: 0 },
  { id: 97, text: "The main difference between a fixed-pitch, two-pitch, and constant-speed propeller is:", options: ["The number of blades", "The ability to change blade angle to maintain efficiency in various flight phases", "The material from which they are made", "The size of the propeller disc", "The direction of rotation"], correctOptionIndex: 1 },
  { id: 98, text: "In the formula for propeller efficiency, 'Output power' is represented by:", options: ["Torque × 2πN/60", "Thrust × TAS", "Shaft power", "RPM × Blade pitch", "Engine power"], correctOptionIndex: 1 },
  { id: 99, text: "The 'plane of rotation' is the plane in which the propeller:", options: ["Is manufactured", "Rotates", "Is mounted", "Produces maximum thrust", "Minimizes drag"], correctOptionIndex: 1 },
  { id: 100, text: "What happens to the centrifugal twisting moment (CTM) at higher RPM?", options: ["It decreases", "It remains constant", "It increases", "It becomes zero", "It reverses direction"], correctOptionIndex: 2 },
  { id: 101, text: "The 'face' of a propeller blade is the:", options: ["Curved side that corresponds to the upper surface of a wing", "Flat side that corresponds to the lower surface of a wing", "Leading edge of the blade", "Trailing edge of the blade", "Root of the blade"], correctOptionIndex: 1 },
  { id: 102, text: "EASA regulation Certification Specification CS-25 specifies requirements for:", options: ["Propeller blade twist", "Minimum propeller clearances", "Propeller material composition", "Engine mounting points", "Fuselage design"] , correctOptionIndex: 1 }
];
