import type { TestConfig } from "@shared/schema";

export const testData: TestConfig = {
  id: "default-test",
  title: "Human Factors",
  description: "Avaliação sobre Human Factors em Aviation Maintenance. Responda todas as 45 questões de revisão sobre factores humanos, desempenho humano e psicologia social. Tempo limite: 45 minutos.",
  durationMinutes: 45,
  questions: [
    {
      id: 1,
      text: "Why must human factors be taken into account in aviation maintenance?",
      options: ["Because maintenance personnel have no impact on system safety.", "To ensure equipment never requires maintenance.", "Because humans are a key point of interaction in systems, and their limitations can affect safety and reliability."],
      correctOptionIndex: 2,
    },
    {
      id: 2,
      text: "Approximately what percentage of aircraft accidents are primarily caused by flight crew actions?",
      options: ["20%", "Over 60%", "4%"],
      correctOptionIndex: 1,
    },
    {
      id: 3,
      text: "In accident statistics, maintenance is identified as the primary cause in what percentage of hull loss accidents?",
      options: ["4%", "12%", "22%"],
      correctOptionIndex: 0,
    },
    {
      id: 4,
      text: "What is one significant financial cost of a maintenance error?",
      options: ["Increased passenger satisfaction", "Flight delays or cancellations", "Reduced training requirements"],
      correctOptionIndex: 1,
    },
    {
      id: 5,
      text: "What is 'human factors' in aviation maintenance?",
      options: ["The study of human capabilities and limitations in the workplace", "Only related to cockpit design and crew resource management", "A term used only for equipment design"],
      correctOptionIndex: 0,
    },
    {
      id: 6,
      text: "Which accident helped bring human factors in maintenance into sharp focus?",
      options: ["Japan Airlines 1985", "Aloha Airlines 1988", "British Airways 1990"],
      correctOptionIndex: 1,
    },
    {
      id: 7,
      text: "What is a unique human factors issue in aviation maintenance?",
      options: ["Maintenance engineers work only in comfortable office environments.", "Maintenance technicians often work in hazardous, confined, or extreme temperature environments.", "Maintenance personnel do not require communication skills."],
      correctOptionIndex: 1,
    },
    {
      id: 8,
      text: "Which type of maintenance task is performed in response to unplanned events?",
      options: ["Scheduled maintenance", "Unscheduled maintenance", "Routine inspection"],
      correctOptionIndex: 1,
    },
    {
      id: 9,
      text: "In the 1985 Japan Airlines Boeing 747 accident, what failed due to a previous repair error?",
      options: ["The rear pressure bulkhead", "The landing gear", "The flight control system"],
      correctOptionIndex: 0,
    },
    {
      id: 10,
      text: "In the Eastern Airlines L-1011 incident, what was missing from the magnetic chip detectors?",
      options: ["O-rings", "Electrical wiring", "Safety tags"],
      correctOptionIndex: 0,
    },
    {
      id: 11,
      text: "What was the primary cause of the Aloha Airlines Boeing 737 accident in 1988?",
      options: ["Failure to detect disbonding and fatigue damage in the fuselage", "Incorrect fuel loading", "Pilot error during takeoff"],
      correctOptionIndex: 0,
    },
    {
      id: 12,
      text: "In the British Airways BAC 1-11 accident, what was the cause of the windscreen blowout?",
      options: ["Incorrect window sealant", "Installation of undersized bolts", "Excessive cabin pressure"],
      correctOptionIndex: 1,
    },
    {
      id: 13,
      text: "In the Air Midwest Beech 1900 accident, what was incorrectly rigged?",
      options: ["Elevator control cables", "Rudder cables", "Aileron controls"],
      correctOptionIndex: 0,
    },
    {
      id: 14,
      text: "What is the 'error chain' in aviation?",
      options: ["A single mechanical failure causing an accident", "A series of human-factor-related errors leading to an accident", "A sequence of automated system warnings"],
      correctOptionIndex: 1,
    },
    {
      id: 15,
      text: "What is Murphy's Law?",
      options: ["'If anything can go right, it will.'", "'If anything can go wrong, it will.'", "'Errors only happen to careless people.'"],
      correctOptionIndex: 1,
    },
    {
      id: 16,
      text: "What part of the eye is responsible for focusing light onto the retina?",
      options: ["Retina", "Lens", "Cornea"],
      correctOptionIndex: 1,
    },
    {
      id: 17,
      text: "What is myopia?",
      options: ["Short-sightedness", "Long-sightedness", "Astigmatism"],
      correctOptionIndex: 0,
    },
    {
      id: 18,
      text: "Where is the blind spot located in the eye?",
      options: ["Where the optic nerve meets the retina", "In the center of the cornea", "At the edge of the iris"],
      correctOptionIndex: 0,
    },
    {
      id: 19,
      text: "Which factor does NOT affect visual acuity?",
      options: ["Age", "Lighting", "Shoe size"],
      correctOptionIndex: 2,
    },
    {
      id: 20,
      text: "What is presbyopia?",
      options: ["A clouding of the lens", "Age-related long-sightedness", "Color blindness"],
      correctOptionIndex: 1,
    },
    {
      id: 21,
      text: "What part of the ear contains the cochlea?",
      options: ["Outer ear", "Middle ear", "Inner ear"],
      correctOptionIndex: 2,
    },
    {
      id: 22,
      text: "What noise level is considered the threshold of pain?",
      options: ["90 dB", "100 dB", "120 dB"],
      correctOptionIndex: 2,
    },
    {
      id: 23,
      text: "What is presbycusis?",
      options: ["Noise-induced hearing loss", "Age-related hearing loss", "Temporary hearing loss from loud noise"],
      correctOptionIndex: 1,
    },
    {
      id: 24,
      text: "Which memory type lasts less than one second?",
      options: ["Sensory memory", "Short-term memory", "Long-term memory"],
      correctOptionIndex: 0,
    },
    {
      id: 25,
      text: "How many items can short-term memory typically hold?",
      options: ["3–4", "7±2", "15–20"],
      correctOptionIndex: 1,
    },
    {
      id: 26,
      text: "What is 'chunking' in memory?",
      options: ["Grouping information into meaningful units", "Repeating information over and over", "Forgetting unnecessary details"],
      correctOptionIndex: 0,
    },
    {
      id: 27,
      text: "Which is NOT a type of attention?",
      options: ["Selective attention", "Divided attention", "Permanent attention"],
      correctOptionIndex: 2,
    },
    {
      id: 28,
      text: "What is confirmation bias?",
      options: ["Ignoring all new information", "Seeking information that confirms existing beliefs", "Always changing your mind"],
      correctOptionIndex: 1,
    },
    {
      id: 29,
      text: "What can help prevent memory-related errors in maintenance?",
      options: ["Using manuals and temporary notes", "Relying only on experience", "Avoiding written procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 30,
      text: "What is situation awareness in maintenance?",
      options: ["Understanding the current system status and predicting future states", "Only knowing your own task", "Memorizing all past procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 31,
      text: "What is claustrophobia?",
      options: ["Fear of heights", "Abnormal fear of enclosed spaces", "Fear of loud noises"],
      correctOptionIndex: 1,
    },
    {
      id: 32,
      text: "What is social loafing?",
      options: ["Working harder in a group", "Reducing effort when working in a group", "Always taking leadership in a team"],
      correctOptionIndex: 1,
    },
    {
      id: 33,
      text: "What is diffusion of responsibility?",
      options: ["Taking full responsibility as an individual", "Feeling less responsible in a group setting", "Assigning tasks clearly in a team"],
      correctOptionIndex: 1,
    },
    {
      id: 34,
      text: "What is the Hawthorne effect?",
      options: ["Improved performance due to increased attention from management", "Reduced performance due to poor lighting", "Peer pressure leading to errors"],
      correctOptionIndex: 0,
    },
    {
      id: 35,
      text: "Which is the highest level in Maslow's hierarchy of needs?",
      options: ["Safety needs", "Esteem needs", "Self-actualization"],
      correctOptionIndex: 2,
    },
    {
      id: 36,
      text: "What is extrinsic motivation?",
      options: ["Motivation driven by external rewards or punishments", "Motivation from personal satisfaction", "Motivation from team recognition only"],
      correctOptionIndex: 0,
    },
    {
      id: 37,
      text: "What did Solomon Asch's conformity experiments demonstrate?",
      options: ["People always make independent judgments.", "People often conform to group opinion even if it's wrong.", "Groups improve decision-making accuracy."],
      correctOptionIndex: 1,
    },
    {
      id: 38,
      text: "What is a 'just culture'?",
      options: ["A no-blame culture where all errors are ignored", "A culture where the line between acceptable and unacceptable behavior is clear", "A culture where all errors are punished"],
      correctOptionIndex: 1,
    },
    {
      id: 39,
      text: "According to Reason, what is a key component of a safety culture?",
      options: ["Ignoring near-misses", "A good reporting culture", "Punishing all errors"],
      correctOptionIndex: 1,
    },
    {
      id: 40,
      text: "What is the 'substitution test' used for?",
      options: ["To determine if an error could have been made by others in the same situation", "To replace faulty equipment", "To test new procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 41,
      text: "Which is NOT one of the 'Big Five' personality traits?",
      options: ["Openness", "Conscientiousness", "Perfectionism"],
      correctOptionIndex: 2,
    },
    {
      id: 42,
      text: "Which personality type is often associated with accident proneness?",
      options: ["Stable introvert", "Unstable extrovert", "Stable extrovert"],
      correctOptionIndex: 1,
    },
    {
      id: 43,
      text: "What is a key element of effective teamwork?",
      options: ["Working in isolation", "Good communication", "Avoiding task delegation"],
      correctOptionIndex: 1,
    },
    {
      id: 44,
      text: "What is a supervisor's role in maintenance?",
      options: ["Only doing hands-on tasks", "Monitoring performance and maintaining safety culture", "Avoiding all management duties"],
      correctOptionIndex: 1,
    },
    {
      id: 45,
      text: "What does MRM stand for?",
      options: ["Maintenance Repair Manual", "Maintenance Resource Management", "Mandatory Regulatory Measures"],
      correctOptionIndex: 1,
    },
  ],
};
