import type { TestConfig } from "@shared/schema";

export const testData: TestConfig = {
  id: "default-test",
  title: "Composite Materials",
  description: "Avaliação sobre Composite Materials e materiais estruturais em aviação. Responda todas as 57 questões sobre compostos, resinas, fibras, estruturas de madeira, propriedades de materiais e tratamentos térmicos. Tempo limite: 60 minutos.",
  durationMinutes: 60,
  questions: [
    {
      id: 1,
      text: "What is the primary reason for using composite materials in aircraft?",
      options: ["Lower production cost", "Weight reduction", "Easier repair"],
      correctOptionIndex: 1,
    },
    {
      id: 2,
      text: "Which of the following is a disadvantage of composites?",
      options: ["High strength-to-weight ratio", "Easy to repair", "Expensive materials and repair"],
      correctOptionIndex: 2,
    },
    {
      id: 3,
      text: "A composite material is typically made up of:",
      options: ["Metal and wood", "Matrix and reinforcing fibres", "Ceramics and elastomers"],
      correctOptionIndex: 1,
    },
    {
      id: 4,
      text: "Which fibre type is known for its high impact resistance and yellow colour?",
      options: ["Glass fibre", "Aramid (Kevlar)", "Carbon fibre"],
      correctOptionIndex: 1,
    },
    {
      id: 5,
      text: "Which fibre is strongest in compression but brittle and corrosive to aluminium?",
      options: ["Glass fibre", "Aramid", "Carbon fibre"],
      correctOptionIndex: 2,
    },
    {
      id: 6,
      text: "Which type of glass fibre is most common for aeronautical GRP?",
      options: ["A-Glass", "E-Glass", "S-Glass"],
      correctOptionIndex: 1,
    },
    {
      id: 7,
      text: "Which resin type is most widely used in aerospace adhesives and composites?",
      options: ["Polyester", "Epoxy", "Phenolic"],
      correctOptionIndex: 1,
    },
    {
      id: 8,
      text: "What is the purpose of a hardener in an epoxy resin system?",
      options: ["To colour the resin", "To initiate the curing reaction", "To reduce viscosity"],
      correctOptionIndex: 1,
    },
    {
      id: 9,
      text: "Which resin type is known for low smoke and toxic gas emissions, making it suitable for cabin interiors?",
      options: ["Epoxy", "Polyurethane", "Phenolic"],
      correctOptionIndex: 2,
    },
    {
      id: 10,
      text: "How must prepreg materials be stored to prevent premature curing?",
      options: ["In a heated cabinet", "In a freezer at -18°C or below", "At room temperature in sealed bags"],
      correctOptionIndex: 1,
    },
    {
      id: 11,
      text: "What is the main advantage of using prepreg materials?",
      options: ["Lower cost", "Controlled resin-to-fibre ratio", "No need for refrigeration"],
      correctOptionIndex: 1,
    },
    {
      id: 12,
      text: "What is the typical shelf life of prepreg repair materials?",
      options: ["1–2 months", "6–12 months", "2–3 years"],
      correctOptionIndex: 1,
    },
    {
      id: 13,
      text: "What is a monolithic composite structure?",
      options: ["A sandwich with a honeycomb core", "Multiple layers of laminate stacked together", "A single layer of fibre only"],
      correctOptionIndex: 1,
    },
    {
      id: 14,
      text: "What is the purpose of a honeycomb core in a sandwich structure?",
      options: ["To increase weight", "To increase stiffness without significant weight gain", "To make the structure flexible"],
      correctOptionIndex: 1,
    },
    {
      id: 15,
      text: "Which of these is a common core material for sandwich structures?",
      options: ["Steel mesh", "Nomex honeycomb", "Rubber foam"],
      correctOptionIndex: 1,
    },
    {
      id: 16,
      text: "What does an autoclave provide during composite curing?",
      options: ["Only heat", "Heat and pressure", "Only vacuum"],
      correctOptionIndex: 1,
    },
    {
      id: 17,
      text: "Which temperature range is typical for curing epoxy resins in an autoclave?",
      options: ["50°C–80°C", "120°C–180°C", "200°C–300°C"],
      correctOptionIndex: 1,
    },
    {
      id: 18,
      text: "What is the purpose of vacuum bagging in composite lay-up?",
      options: ["To add colour to the laminate", "To remove air and excess resin", "To speed up the curing time"],
      correctOptionIndex: 1,
    },
    {
      id: 19,
      text: "Which defect is a hidden failure between layers of fabric in a composite?",
      options: ["Crack", "Delamination", "Dent"],
      correctOptionIndex: 1,
    },
    {
      id: 20,
      text: "Which inspection method uses sound to detect delamination?",
      options: ["Light test", "Coin-tap test", "X-ray"],
      correctOptionIndex: 1,
    },
    {
      id: 21,
      text: "Class 3 damage in composites is defined as:",
      options: ["Major structural damage", "Negligible damage within limits", "Damage requiring immediate repair"],
      correctOptionIndex: 1,
    },
    {
      id: 22,
      text: "What is the common name for polymethyl-methacrylate used in aircraft windows?",
      options: ["PVC", "Perspex/Acrylic", "Teflon"],
      correctOptionIndex: 1,
    },
    {
      id: 23,
      text: "Which plastic is known for its non-stick properties and high chemical resistance?",
      options: ["Polypropylene", "PTFE (Teflon)", "Nylon"],
      correctOptionIndex: 1,
    },
    {
      id: 24,
      text: "What causes crazing in acrylic windows?",
      options: ["Excessive heat only", "Contact with solvents or UV light", "High pressure"],
      correctOptionIndex: 1,
    },
    {
      id: 25,
      text: "Which elastomer is known for high-temperature resistance and is often called Viton?",
      options: ["Nitrile", "Fluoro-elastomer", "Silicone rubber"],
      correctOptionIndex: 1,
    },
    {
      id: 26,
      text: "Which rubber is resistant to phosphate ester hydraulic fluids like Skydrol?",
      options: ["Buna-S", "Neoprene", "Ethylene-propylene rubber"],
      correctOptionIndex: 2,
    },
    {
      id: 27,
      text: "What is the primary use of elastomers in aircraft?",
      options: ["Structural components", "Seals, adhesives, and flexible parts", "Window frames"],
      correctOptionIndex: 1,
    },
    {
      id: 28,
      text: "Which adhesive was first developed during WWII and is still used today?",
      options: ["Epoxy", "Redux", "Polyurethane"],
      correctOptionIndex: 1,
    },
    {
      id: 29,
      text: "What is the primary function of a sealant in aircraft?",
      options: ["To provide electrical insulation", "To prevent air or fluid leakage", "To increase structural strength"],
      correctOptionIndex: 1,
    },
    {
      id: 30,
      text: "Which sealant type vulcanises at room temperature?",
      options: ["Polysulphide", "RTV silicone", "Epoxy paste"],
      correctOptionIndex: 1,
    },
    {
      id: 31,
      text: "Which wood type is traditionally considered best for aircraft construction?",
      options: ["Oak", "Sitka spruce", "Pine"],
      correctOptionIndex: 1,
    },
    {
      id: 32,
      text: "What is the maximum grain slope allowed for Grade A spruce?",
      options: ["1:8", "1:12", "1:15"],
      correctOptionIndex: 2,
    },
    {
      id: 33,
      text: "What defect appears as a separation along the annual rings of wood?",
      options: ["Heart shake", "Ring shake", "Knot"],
      correctOptionIndex: 1,
    },
    {
      id: 34,
      text: "Which glue is waterproof and highly resistant to temperature and chemicals?",
      options: ["Casein", "Resorcinol-formaldehyde", "Urea-formaldehyde"],
      correctOptionIndex: 1,
    },
    {
      id: 35,
      text: "What is the typical taper ratio for a scarf joint in wood?",
      options: ["5:1", "12:1 to 15:1", "20:1"],
      correctOptionIndex: 1,
    },
    {
      id: 36,
      text: "Why should sandpaper not be used on new timber before gluing?",
      options: ["It makes the wood too smooth", "It fills pores with dust and reduces adhesion", "It changes the colour of the wood"],
      correctOptionIndex: 1,
    },
    {
      id: 37,
      text: "What indicates dry rot in wood?",
      options: ["Dark discolouration along the grain", "Crumbling wood patches", "Blue stains"],
      correctOptionIndex: 1,
    },
    {
      id: 38,
      text: "What is compression shake in wood caused by?",
      options: ["Tension overload", "Compression overload along the grain", "Moisture absorption"],
      correctOptionIndex: 1,
    },
    {
      id: 39,
      text: "How can water penetration in a wooden structure be detected?",
      options: ["By tapping the surface", "By checking for corrosion on screws or bolts", "By applying a light coat of varnish"],
      correctOptionIndex: 1,
    },
    {
      id: 40,
      text: "What is aircraft-grade plywood usually made from?",
      options: ["Spruce veneers", "Birch veneers", "Mahogany veneers"],
      correctOptionIndex: 1,
    },
    {
      id: 41,
      text: "How are veneers typically arranged in plywood?",
      options: ["All grains in the same direction", "Grains alternated at 90°", "Random orientation"],
      correctOptionIndex: 1,
    },
    {
      id: 42,
      text: "What is the main advantage of plywood over solid wood?",
      options: ["Lower cost", "Greater strength in multiple directions", "Lighter weight"],
      correctOptionIndex: 1,
    },
    {
      id: 43,
      text: "In the context of aluminum manufacturing, what does \"DC\" stand for in the provided abbreviations list?",
      options: ["Direct Current", "Direct Chili", "Double Coated"],
      correctOptionIndex: 1,
    },
    {
      id: 44,
      text: "Which abbreviation refers to the chemical compound used as a flux in aluminum smelting?",
      options: ["Al₂O₃", "Na₃AlF₃", "CO₂"],
      correctOptionIndex: 1,
    },
    {
      id: 45,
      text: "What density threshold is used to differentiate between lightweight and heavyweight metals in aircraft construction?",
      options: ["3.0 Kg/dm³", "5.0 Kg/dm³", "7.0 Kg/dm³"],
      correctOptionIndex: 1,
    },
    {
      id: 46,
      text: "Which of the following metals has the lowest density among those listed for aircraft structures?",
      options: ["Titanium", "Aluminum", "Magnesium"],
      correctOptionIndex: 2,
    },
    {
      id: 47,
      text: "What is the term for the undesirable property where a metal becomes brittle within a specific high-temperature range?",
      options: ["Cold shortness", "Hot shortness", "Thermal brittleness"],
      correctOptionIndex: 1,
    },
    {
      id: 48,
      text: "Which property describes a material's ability to be readily liquefied by heat for welding?",
      options: ["Fusibility", "Malleability", "Solubility"],
      correctOptionIndex: 0,
    },
    {
      id: 49,
      text: "In the formula for strain, what does \"e\" represent?",
      options: ["Original length", "Change in length", "Elastic modulus"],
      correctOptionIndex: 1,
    },
    {
      id: 50,
      text: "If a stress of 1 hbar is applied to a steel component, what is the resulting strain if Young's modulus for steel is 20,000 hbar?",
      options: ["1/20,000", "1/2,000", "1/200"],
      correctOptionIndex: 0,
    },
    {
      id: 51,
      text: "Which of the following is NOT listed as a typical load contributing to fatigue in aircraft structures?",
      options: ["Atmospheric gusts", "Engine start-up cycles", "Taxiing"],
      correctOptionIndex: 1,
    },
    {
      id: 52,
      text: "What microscopic feature is NOT cited as a potential initiation site for fatigue cracks?",
      options: ["Voids", "Grain boundaries", "Inclusion particles"],
      correctOptionIndex: 1,
    },
    {
      id: 53,
      text: "In the historical context provided, which civilization first perfected reliable steel manufacturing around AD 200?",
      options: ["Romans", "Celts", "Chinese"],
      correctOptionIndex: 1,
    },
    {
      id: 54,
      text: "What is the primary purpose of the blast furnace in iron production?",
      options: ["To cast iron into final shapes", "To convert iron ore into molten iron", "To refine steel into alloys"],
      correctOptionIndex: 1,
    },
    {
      id: 55,
      text: "Which alloying element, when added in approximately 35%, gives steel a nearly-zero expansion coefficient?",
      options: ["Nickel", "Chromium", "Cobalt"],
      correctOptionIndex: 0,
    },
    {
      id: 56,
      text: "Which element is noted for increasing steel's resistance to shock and fatigue, even when added in very low percentages?",
      options: ["Vanadium", "Tungsten", "Manganese"],
      correctOptionIndex: 0,
    },
    {
      id: 57,
      text: "In the cyanide hardening process, what is the typical temperature used?",
      options: ["750°C", "900°C", "1,000°C"],
      correctOptionIndex: 1,
    },
  ],
};
    {
      id: 2,
      text: "Approximately what percentage of aircraft accidents are primarily caused by flight crew actions?",
      options: ["20%", "Over 60%", "4%"],
      correctOptionIndex: 1,
    },
    {
      id: 3,
      text: "In accident statistics, maintenance is identified as the primary cause in what percentage of hull loss accidents?",
      options: ["4%", "12%", "22%"],
      correctOptionIndex: 0,
    },
    {
      id: 4,
      text: "What is one significant financial cost of a maintenance error?",
      options: ["Increased passenger satisfaction", "Flight delays or cancellations", "Reduced training requirements"],
      correctOptionIndex: 1,
    },
    {
      id: 5,
      text: "What is 'human factors' in aviation maintenance?",
      options: ["The study of human capabilities and limitations in the workplace", "Only related to cockpit design and crew resource management", "A term used only for equipment design"],
      correctOptionIndex: 0,
    },
    {
      id: 6,
      text: "Which accident helped bring human factors in maintenance into sharp focus?",
      options: ["Japan Airlines 1985", "Aloha Airlines 1988", "British Airways 1990"],
      correctOptionIndex: 1,
    },
    {
      id: 7,
      text: "What is a unique human factors issue in aviation maintenance?",
      options: ["Maintenance engineers work only in comfortable office environments.", "Maintenance technicians often work in hazardous, confined, or extreme temperature environments.", "Maintenance personnel do not require communication skills."],
      correctOptionIndex: 1,
    },
    {
      id: 8,
      text: "Which type of maintenance task is performed in response to unplanned events?",
      options: ["Scheduled maintenance", "Unscheduled maintenance", "Routine inspection"],
      correctOptionIndex: 1,
    },
    {
      id: 9,
      text: "In the 1985 Japan Airlines Boeing 747 accident, what failed due to a previous repair error?",
      options: ["The rear pressure bulkhead", "The landing gear", "The flight control system"],
      correctOptionIndex: 0,
    },
    {
      id: 10,
      text: "In the Eastern Airlines L-1011 incident, what was missing from the magnetic chip detectors?",
      options: ["O-rings", "Electrical wiring", "Safety tags"],
      correctOptionIndex: 0,
    },
    {
      id: 11,
      text: "What was the primary cause of the Aloha Airlines Boeing 737 accident in 1988?",
      options: ["Failure to detect disbonding and fatigue damage in the fuselage", "Incorrect fuel loading", "Pilot error during takeoff"],
      correctOptionIndex: 0,
    },
    {
      id: 12,
      text: "In the British Airways BAC 1-11 accident, what was the cause of the windscreen blowout?",
      options: ["Incorrect window sealant", "Installation of undersized bolts", "Excessive cabin pressure"],
      correctOptionIndex: 1,
    },
    {
      id: 13,
      text: "In the Air Midwest Beech 1900 accident, what was incorrectly rigged?",
      options: ["Elevator control cables", "Rudder cables", "Aileron controls"],
      correctOptionIndex: 0,
    },
    {
      id: 14,
      text: "What is the 'error chain' in aviation?",
      options: ["A single mechanical failure causing an accident", "A series of human-factor-related errors leading to an accident", "A sequence of automated system warnings"],
      correctOptionIndex: 1,
    },
    {
      id: 15,
      text: "What is Murphy's Law?",
      options: ["'If anything can go right, it will.'", "'If anything can go wrong, it will.'", "'Errors only happen to careless people.'"],
      correctOptionIndex: 1,
    },
    {
      id: 16,
      text: "What part of the eye is responsible for focusing light onto the retina?",
      options: ["Retina", "Lens", "Cornea"],
      correctOptionIndex: 1,
    },
    {
      id: 17,
      text: "What is myopia?",
      options: ["Short-sightedness", "Long-sightedness", "Astigmatism"],
      correctOptionIndex: 0,
    },
    {
      id: 18,
      text: "Where is the blind spot located in the eye?",
      options: ["Where the optic nerve meets the retina", "In the center of the cornea", "At the edge of the iris"],
      correctOptionIndex: 0,
    },
    {
      id: 19,
      text: "Which factor does NOT affect visual acuity?",
      options: ["Age", "Lighting", "Shoe size"],
      correctOptionIndex: 2,
    },
    {
      id: 20,
      text: "What is presbyopia?",
      options: ["A clouding of the lens", "Age-related long-sightedness", "Color blindness"],
      correctOptionIndex: 1,
    },
    {
      id: 21,
      text: "What part of the ear contains the cochlea?",
      options: ["Outer ear", "Middle ear", "Inner ear"],
      correctOptionIndex: 2,
    },
    {
      id: 22,
      text: "What noise level is considered the threshold of pain?",
      options: ["90 dB", "100 dB", "120 dB"],
      correctOptionIndex: 2,
    },
    {
      id: 23,
      text: "What is presbycusis?",
      options: ["Noise-induced hearing loss", "Age-related hearing loss", "Temporary hearing loss from loud noise"],
      correctOptionIndex: 1,
    },
    {
      id: 24,
      text: "Which memory type lasts less than one second?",
      options: ["Sensory memory", "Short-term memory", "Long-term memory"],
      correctOptionIndex: 0,
    },
    {
      id: 25,
      text: "How many items can short-term memory typically hold?",
      options: ["3–4", "7±2", "15–20"],
      correctOptionIndex: 1,
    },
    {
      id: 26,
      text: "What is 'chunking' in memory?",
      options: ["Grouping information into meaningful units", "Repeating information over and over", "Forgetting unnecessary details"],
      correctOptionIndex: 0,
    },
    {
      id: 27,
      text: "Which is NOT a type of attention?",
      options: ["Selective attention", "Divided attention", "Permanent attention"],
      correctOptionIndex: 2,
    },
    {
      id: 28,
      text: "What is confirmation bias?",
      options: ["Ignoring all new information", "Seeking information that confirms existing beliefs", "Always changing your mind"],
      correctOptionIndex: 1,
    },
    {
      id: 29,
      text: "What can help prevent memory-related errors in maintenance?",
      options: ["Using manuals and temporary notes", "Relying only on experience", "Avoiding written procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 30,
      text: "What is situation awareness in maintenance?",
      options: ["Understanding the current system status and predicting future states", "Only knowing your own task", "Memorizing all past procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 31,
      text: "What is claustrophobia?",
      options: ["Fear of heights", "Abnormal fear of enclosed spaces", "Fear of loud noises"],
      correctOptionIndex: 1,
    },
    {
      id: 32,
      text: "What is social loafing?",
      options: ["Working harder in a group", "Reducing effort when working in a group", "Always taking leadership in a team"],
      correctOptionIndex: 1,
    },
    {
      id: 33,
      text: "What is diffusion of responsibility?",
      options: ["Taking full responsibility as an individual", "Feeling less responsible in a group setting", "Assigning tasks clearly in a team"],
      correctOptionIndex: 1,
    },
    {
      id: 34,
      text: "What is the Hawthorne effect?",
      options: ["Improved performance due to increased attention from management", "Reduced performance due to poor lighting", "Peer pressure leading to errors"],
      correctOptionIndex: 0,
    },
    {
      id: 35,
      text: "Which is the highest level in Maslow's hierarchy of needs?",
      options: ["Safety needs", "Esteem needs", "Self-actualization"],
      correctOptionIndex: 2,
    },
    {
      id: 36,
      text: "What is extrinsic motivation?",
      options: ["Motivation driven by external rewards or punishments", "Motivation from personal satisfaction", "Motivation from team recognition only"],
      correctOptionIndex: 0,
    },
    {
      id: 37,
      text: "What did Solomon Asch's conformity experiments demonstrate?",
      options: ["People always make independent judgments.", "People often conform to group opinion even if it's wrong.", "Groups improve decision-making accuracy."],
      correctOptionIndex: 1,
    },
    {
      id: 38,
      text: "What is a 'just culture'?",
      options: ["A no-blame culture where all errors are ignored", "A culture where the line between acceptable and unacceptable behavior is clear", "A culture where all errors are punished"],
      correctOptionIndex: 1,
    },
    {
      id: 39,
      text: "According to Reason, what is a key component of a safety culture?",
      options: ["Ignoring near-misses", "A good reporting culture", "Punishing all errors"],
      correctOptionIndex: 1,
    },
    {
      id: 40,
      text: "What is the 'substitution test' used for?",
      options: ["To determine if an error could have been made by others in the same situation", "To replace faulty equipment", "To test new procedures"],
      correctOptionIndex: 0,
    },
    {
      id: 41,
      text: "Which is NOT one of the 'Big Five' personality traits?",
      options: ["Openness", "Conscientiousness", "Perfectionism"],
      correctOptionIndex: 2,
    },
    {
      id: 42,
      text: "Which personality type is often associated with accident proneness?",
      options: ["Stable introvert", "Unstable extrovert", "Stable extrovert"],
      correctOptionIndex: 1,
    },
    {
      id: 43,
      text: "What is a key element of effective teamwork?",
      options: ["Working in isolation", "Good communication", "Avoiding task delegation"],
      correctOptionIndex: 1,
    },
    {
      id: 44,
      text: "What is a supervisor's role in maintenance?",
      options: ["Only doing hands-on tasks", "Monitoring performance and maintaining safety culture", "Avoiding all management duties"],
      correctOptionIndex: 1,
    },
    {
      id: 45,
      text: "What does MRM stand for?",
      options: ["Maintenance Repair Manual", "Maintenance Resource Management", "Mandatory Regulatory Measures"],
      correctOptionIndex: 1,
    },
  ],
};
