export const theoryOfFlightQuestions = [
  { id: 101, text: "The word 'canard' is French for:", options: ["Bird", "Duck", "Wing"], correctOptionIndex: 1 },
  { id: 102, text: "In a canard configuration, the forward horizontal surface is called the:", options: ["Main wing", "Canard or foreplane", "Stabilizer"], correctOptionIndex: 1 },
  { id: 103, text: "A canard design tends to be less controllable than a conventional design because:", options: ["It has no rudder", "Ailerons may be subject to turbulence from canards at different angles of attack", "It has no elevator"], correctOptionIndex: 1 },
  { id: 104, text: "The two main classes of canard designs are:", options: ["Forward and rearward canards", "Lifting-canard and control-canard", "High and low canards"], correctOptionIndex: 1 },
  { id: 105, text: "In a lifting-canard configuration:", options: ["Only the main wing carries weight", "Weight is shared between main wing and canard wing", "Only the canard carries weight"], correctOptionIndex: 1 },
  { id: 106, text: "In a lifting-canard, the CG is significantly aft, at approximately:", options: ["25% chord", "50% chord", "75% chord"], correctOptionIndex: 1 },
  { id: 107, text: "A lifting-canard generates:", options: ["A download", "An upload", "No lift"], correctOptionIndex: 1 },
  { id: 108, text: "A conventional aft-tail normally generates:", options: ["Upload", "Negative lift (download)", "No lift"], correctOptionIndex: 1 },
  { id: 109, text: "Pitch stability flight safety requirements dictate that the canard must:", options: ["Never stall", "Stall before the main wing", "Stall after the main wing"], correctOptionIndex: 1 },
  { id: 110, text: "The first powered aeroplane to fly, the Wright Flyer, was:", options: ["Pitch stable", "Pitch unstable", "Directionally unstable"], correctOptionIndex: 1 },
  { id: 111, text: "In a control-canard configuration:", options: ["The canard carries most of the weight", "Most weight is carried by main wing, canard used primarily for longitudinal control", "Both surfaces share weight equally"], correctOptionIndex: 1 },
  { id: 112, text: "In a control-canard, the canard is usually at:", options: ["High angle of attack", "Zero angle of attack, carrying no weight in normal flight", "Negative angle of attack"], correctOptionIndex: 1 },
  { id: 113, text: "Combat aircraft of canard configuration typically have a:", options: ["Lifting-canard", "Control-canard", "Fixed canard"], correctOptionIndex: 1 },
  { id: 114, text: "In the close-coupled canard, the foreplane is located:", options: ["Far ahead of the main wing", "Just above and forward of the main wing", "Behind the main wing"], correctOptionIndex: 1 },
  { id: 115, text: "At high angles of attack, a close-coupled canard directs airflow:", options: ["Away from the wing", "Downwards over the wing", "Upwards away from the wing"], correctOptionIndex: 1 },
  { id: 116, text: "A 'moustache' is a:", options: ["Type of flap", "Small, high aspect ratio foreplane of close-coupled configuration", "Type of rudder"], correctOptionIndex: 1 },
  { id: 117, text: "The 'moustache' foreplane is typically:", options: ["Fixed permanently extended", "Retractable at high speed, deployed only for low-speed flight", "Always deployed"], correctOptionIndex: 1 },
  { id: 118, text: "Aircraft such as the B-1 Lancer incorporate small canard surfaces for:", options: ["Increased lift", "Active vibration damping", "Improved roll control"], correctOptionIndex: 1 },
  { id: 119, text: "One benefit obtainable from a control-canard is:", options: ["Increased drag", "Avoidance of pitch-up", "Reduced stability"], correctOptionIndex: 1 },
  { id: 120, text: "A close-coupled canard is very useful for:", options: ["Low-speed aircraft only", "Supersonic delta wing design", "Conventional straight-wing aircraft"], correctOptionIndex: 1 },
  { id: 121, text: "High lift devices are incorporated to:", options: ["Increase takeoff and landing distance", "Reduce distance required for takeoff and landing", "Increase stalling speed"], correctOptionIndex: 1 },
  { id: 122, text: "Takeoff and landing distance depends on:", options: ["Engine power only", "Speed involved, related to stalling speed", "Aircraft weight only"], correctOptionIndex: 1 },
  { id: 123, text: "All high lift devices increase the:", options: ["Drag coefficient only", "Coefficient of lift of the wing", "Stalling speed"], correctOptionIndex: 1 },
  { id: 124, text: "A plain flap is:", options: ["A leading edge device", "An aerofoil section hinged down from trailing edge", "A spoiler"], correctOptionIndex: 1 },
  { id: 125, text: "A split flap hinges down from:", options: ["The upper surface of trailing edge", "The under surface of trailing edge", "The leading edge"], correctOptionIndex: 1 },
  { id: 126, text: "An advantage of a split flap is:", options: ["It increases upper surface camber", "Camber of upper surface is not disturbed", "It produces no drag"], correctOptionIndex: 1 },
  { id: 127, text: "A slotted flap has a small slot between:", options: ["The flap and the fuselage", "The trailing edge of wing and leading edge of flap", "The flap and aileron"], correctOptionIndex: 1 },
  { id: 128, text: "The slot in a slotted flap acts as a:", options: ["Brake", "Venturi, speeding up air", "Spoiler"], correctOptionIndex: 1 },
  { id: 129, text: "A Fowler flap, in addition to moving downwards, also:", options: ["Rotates", "Moves rearwards", "Moves upwards"], correctOptionIndex: 1 },
  { id: 130, text: "A Krueger flap is a:", options: ["Trailing edge flap", "Leading-edge flap", "Wing tip device"], correctOptionIndex: 1 },
  { id: 131, text: "A drooped leading-edge flap increases:", options: ["Only wing area", "Camber of the wing", "Only drag"], correctOptionIndex: 1 },
  { id: 132, text: "A Krueger flap extends:", options: ["Rearward from trailing edge", "Out ahead of the leading edge", "Downward from wing tip"], correctOptionIndex: 1 },
  { id: 133, text: "The effect of lowering a flap is to:", options: ["Decrease overall camber", "Increase overall camber", "Decrease coefficient of lift"], correctOptionIndex: 1 },
  { id: 134, text: "Some types of flap also increase:", options: ["Only camber", "Wing area", "Only drag"], correctOptionIndex: 1 },
  { id: 135, text: "At large flap angles, air tends to separate away from flap upper surface. This can be minimized by:", options: ["Increasing flap angle further", "Putting a small slot between wing trailing edge and flap leading edge", "Reducing flap size"], correctOptionIndex: 1 },
  { id: 136, text: "The slot speeds up air, giving it more:", options: ["Pressure", "Kinetic energy", "Temperature"], correctOptionIndex: 1 },
  { id: 137, text: "Fowler flaps result in:", options: ["Small increase in lift coefficient", "Very large increase in lift coefficient", "No change in lift coefficient"], correctOptionIndex: 1 },
  { id: 138, text: "The part on the leading-edge for high lift is called a:", options: ["Flap", "Slat", "Spoiler"], correctOptionIndex: 1 },
  { id: 139, text: "The part on the trailing edge for high lift is called a:", options: ["Slat", "Flap", "Spoiler"], correctOptionIndex: 1 },
  { id: 140, text: "Moving flaps aft and slats forward increases:", options: ["Only camber", "Wing area and effective camber", "Only drag"], correctOptionIndex: 1 },
  { id: 141, text: "The stall angle with flaps only:", options: ["Increases", "Reduces", "Remains the same"], correctOptionIndex: 1 },
  { id: 142, text: "The reason for decrease in stall angle with flaps is:", options: ["Decreased camber", "Local increase in angle of attack at flap location and increased camber moving separation point forward", "Increased airspeed"], correctOptionIndex: 1 },
  { id: 143, text: "Deploying slats with flaps restores the stall angle and:", options: ["Decreases it below no-flap position", "Increases it beyond no-flap position", "Has no effect"], correctOptionIndex: 1 },
  { id: 144, text: "On larger airliners, slats are always deployed:", options: ["Before flaps", "With flaps, often automatically", "After flaps"], correctOptionIndex: 1 },
  { id: 145, text: "Slat deployment usually begins:", options: ["Before first stage of flap deployment", "Only after the first stage of flap deployment", "Independently of flaps"], correctOptionIndex: 1 },
  { id: 146, text: "Deployment of slats with flaps results in:", options: ["Small increase in lift coefficient", "Large increase in lift coefficient", "Decrease in lift coefficient"], correctOptionIndex: 1 },
  { id: 147, text: "When a flap is deployed, the bulk of the lift moves to:", options: ["Leading edge of wing", "Trailing edge of wing at flap location", "Wing tips"], correctOptionIndex: 1 },
  { id: 148, text: "Flap deployment produces a nose-down moment on the wing itself, but the overall effect:", options: ["Is always nose-down", "Depends on aircraft configuration", "Is always nose-up"], correctOptionIndex: 1 },
  { id: 149, text: "When flap is deployed, there is significant increase in:", options: ["Angle of upwash", "Angle of downwash of airflow leaving wing trailing edge", "Angle of incidence"], correctOptionIndex: 1 },
  { id: 150, text: "Mounting tailplane high on vertical fin helps prevent:", options: ["Increased lift", "Nose-up moment from downwash", "Drag increase"], correctOptionIndex: 1 },
  { id: 151, text: "Spoilers are used to:", options: ["Increase lift", "Disrupt airflow and greatly reduce lift", "Improve laminar flow"], correctOptionIndex: 1 },
  { id: 152, text: "Spoilers allow a pilot to:", options: ["Gain altitude without increasing speed", "Lose altitude without gaining excessive airspeed", "Increase speed"], correctOptionIndex: 1 },
  { id: 153, text: "Spoilers are sometimes called:", options: ["Lift increases", "Lift dumps", "Speed increases"], correctOptionIndex: 1 },
  { id: 154, text: "Spoiler deployment causes:", options: ["Small increase in drag and small decrease in lift", "Large increase in drag and large decrease in lift", "No change in drag or lift"], correctOptionIndex: 1 },
  { id: 155, text: "Spoilers are located on:", options: ["Lower surface of wing", "Upper surface of wing", "Leading edge of wing"], correctOptionIndex: 1 },
  { id: 156, text: "Lift dumps (ground spoilers) deploy upon:", options: ["Takeoff", "Touchdown on the runway", "Climb"], correctOptionIndex: 1 },
  { id: 157, text: "Ground spoilers place aircraft weight on wheels to:", options: ["Increase lift", "Accomplish braking after touchdown", "Reduce drag"], correctOptionIndex: 1 },
  { id: 158, text: "Speed brakes are designed to:", options: ["Increase lift", "Increase drag while making little change to lift", "Decrease drag"], correctOptionIndex: 1 },
  { id: 159, text: "Speed brakes differ from spoilers in that spoilers:", options: ["Only increase drag", "Greatly reduce lift-to-drag ratio", "Only reduce speed"], correctOptionIndex: 1 },
  { id: 160, text: "Reverse thrust is also used to:", options: ["Increase speed after landing", "Help slow aircraft after landing", "Increase lift"], correctOptionIndex: 1 },
  { id: 161, text: "A fixed trim tab is a:", options: ["Pilot-controlled device", "Small sheet-metal tab on trailing edge of rudder", "Hydraulic device"], correctOptionIndex: 1 },
  { id: 162, text: "A fixed trim tab is bent so it will:", options: ["Increase control forces", "Deflect the rudder to counteract unbalanced condition", "Decrease stability"], correctOptionIndex: 1 },
  { id: 163, text: "A tab on the rudder corrects a wing-heavy flight condition by:", options: ["Directly lifting the heavy wing", "Forcing aircraft to fly in just enough yaw to create lift difference needed", "Increasing drag on light wing"], correctOptionIndex: 1 },
  { id: 164, text: "If an aircraft has a tendency to yaw to the left, the rudder trim tab would be positioned:", options: ["To the right", "To the left", "Neutral"], correctOptionIndex: 1 },
  { id: 165, text: "Positioning rudder trim tab to the left deflects the rudder:", options: ["To the left", "To the right", "Remains neutral"], correctOptionIndex: 1 },
  { id: 166, text: "An adjustable trim tab is hinged to:", options: ["Fixed stabilizer", "Trailing edge of the elevator", "Wing tip"], correctOptionIndex: 1 },
  { id: 167, text: "The adjustable trim tab has a jackcrew mechanism that allows:", options: ["Tab to be removed", "Length of actuating rod to be varied in flight", "Tab to be locked"], correctOptionIndex: 1 },
  { id: 168, text: "Longitudinal balance is most affected by:", options: ["Fuel weight", "Airspeed variations in normal flight", "Passenger movement"], correctOptionIndex: 1 },
  { id: 169, text: "A servo tab is connected directly to:", options: ["The main control surface", "Pilot's control yoke or rudder pedals", "The wing structure"], correctOptionIndex: 1 },
  { id: 170, text: "When the pilot deflects a servo tab, aerodynamic forces then:", options: ["Have no effect", "Move the control surface in opposite direction from servo tab movement", "Move the control surface in same direction as servo tab"], correctOptionIndex: 1 },
  { id: 171, text: "A distinctive feature of servo-tab controlled surfaces is that when stationary:", options: ["Controls are perfectly streamlined", "Ailerons and elevator hang down below neutral position", "Controls lock in place"], correctOptionIndex: 1 },
  { id: 172, text: "As aircraft accelerates, airflow over servo-tab controlled surfaces pushes them:", options: ["Further down", "Into neutral position", "Upwards"], correctOptionIndex: 1 },
  { id: 173, text: "The speed at which servo-tab controlled surfaces become neutral is:", options: ["Above takeoff speed", "Below takeoff speed", "At stall speed"], correctOptionIndex: 1 },
  { id: 174, text: "A disadvantage of servo-tab method was:", options: ["Too much control response", "Control response at low speed was rather sluggish", "Control surfaces wouldn't move"], correctOptionIndex: 1 },
  { id: 175, text: "Note: The name 'servo tab' in the USA is reserved for the device known as:", options: ["Trim tab in UK/Europe", "Balance tab in UK/Europe", "Anti-balance tab in UK/Europe"], correctOptionIndex: 1 },
  { id: 176, text: "A balance tab provides:", options: ["Download on tail", "Aerodynamic force aiding pilot in moving control surface", "Increased drag"], correctOptionIndex: 1 },
  { id: 177, text: "In a balance tab, the actuator rod may be adjusted for:", options: ["Fixed tab deflection at all times", "A given deflection of tab when elevator is streamlined", "No tab movement"], correctOptionIndex: 1 },
  { id: 178, text: "When the tab moves in the direction opposite the control:", options: ["It hinders pilot movement", "A pressure differential aids pilot in moving control against aerodynamic loads", "No effect is produced"], correctOptionIndex: 1 },
  { id: 179, text: "An anti-balance tab is also called a:", options: ["Servo tab", "Leading tab", "Trim tab"], correctOptionIndex: 1 },
  { id: 180, text: "Anti-balance tabs move in:", options: ["Opposite direction to the surface", "Same direction as the surface", "No relation to surface movement"], correctOptionIndex: 1 },
  { id: 181, text: "Anti-balance tabs counteract:", options: ["Low control forces", "Extreme sensitivity caused by hinge line location of stabilator", "Trim changes"], correctOptionIndex: 1 },
  { id: 182, text: "When control wheel is pulled back on a stabilator with anti-balance tab:", options: ["Tab moves down", "Trailing edge of stabilator moves up, anti-servo tab also moves up", "Tab remains neutral"], correctOptionIndex: 1 },
  { id: 183, text: "An anti-balance tab produces aerodynamic force in direction needed to:", options: ["Move trailing edge of stabilator up further", "Move trailing edge of stabilator down", "Keep stabilator neutral"], correctOptionIndex: 1 },
  { id: 184, text: "A spring tab is needed because:", options: ["Control forces are low at all speeds", "At high speeds, force required to move surface becomes excessive", "At low speeds, forces are too high"], correctOptionIndex: 1 },
  { id: 185, text: "The spring tab solves the need for:", options: ["Constant control assistance", "Varying amount of control assistance", "No assistance"], correctOptionIndex: 1 },
  { id: 186, text: "At low speeds with a spring tab:", options: ["Spring is activated", "Surface is moved directly by control rod", "Tab moves instead of surface"], correctOptionIndex: 1 },
  { id: 187, text: "At high speeds with a spring tab:", options: ["Spring remains inactive", "Torsion bar twists or spring collapses and tab is deflected", "Only tab moves, surface doesn't"], correctOptionIndex: 1 },
  { id: 188, text: "The tab moves in direction opposite the aileron to:", options: ["Decrease control effectiveness", "Provide aerodynamic boost to help pilot move control", "Increase drag"], correctOptionIndex: 1 },
  { id: 189, text: "The speed at which spring just starts to be activated is called:", options: ["Activation speed", "Break-out speed", "Spring speed"], correctOptionIndex: 1 },
  { id: 190, text: "An anti-balance tab is called an anti-servo tab in:", options: ["UK/Europe", "USA", "Both regions"], correctOptionIndex: 1 },
  { id: 191, text: "Horn balance is the simplest form of:", options: ["Mass balance", "Aerodynamic assistance in control movement", "Trim device"], correctOptionIndex: 1 },
  { id: 192, text: "Inset hinges are hinges that are:", options: ["Located at trailing edge", "Set back so airflow striking surface in front of hinge assists control movement", "Located at leading edge"], correctOptionIndex: 1 },
  { id: 193, text: "Generally, amount of control surface forward of hinge line is about:", options: ["10% of overall control surface area", "20% of overall control surface area", "50% of overall control surface area"], correctOptionIndex: 1 },
  { id: 194, text: "An aerodynamic balance panel divides the compartment ahead of aileron into:", options: ["One compartment", "Two smaller compartments", "Three compartments"], correctOptionIndex: 1 },
  { id: 195, text: "The balance panel provides more assistance as:", options: ["Airspeed decreases", "Surface deflection increases", "Surface deflection decreases"], correctOptionIndex: 1 },
  { id: 196, text: "Control surface mass balance prevents:", options: ["Control surface movement", "Control surface flutter", "Trim changes"], correctOptionIndex: 1 },
  { id: 197, text: "Mass balance adds a specific mass some distance:", options: ["Behind the control surface hinge line", "Ahead of the control surface hinge line", "At the trailing edge"], correctOptionIndex: 1 },
  { id: 198, text: "Control surface bias on some aeroplanes gives:", options: ["Nose-up tendency", "Nose-down tendency", "Neutral tendency"], correctOptionIndex: 1 },
  { id: 199, text: "Spades on ailerons serve to:", options: ["Increase control forces", "Reduce effort needed on stick and bring center of mass forward of hinge line", "Increase flutter tendency"], correctOptionIndex: 1 },
  { id: 200, text: "According to CS25.173, stick force must increase with aeroplane speed, and the increase may not be less than:", options: ["2 N for each 6 kts", "4 N for each 6 kts", "6 N for each 6 kts"], correctOptionIndex: 1 },
  { id: 201, text: "The key objective of boundary layer control is to:", options: ["Let boundary layer stagnate", "Prevent boundary layer from stagnating by adding energy when needed", "Remove all boundary layer"], correctOptionIndex: 1 },
  { id: 202, text: "By accepting a turbulent boundary layer rather than laminar:", options: ["All problems are solved", "Price is more friction and drag, thus higher fuel consumption", "Fuel consumption decreases"], correctOptionIndex: 1 },
  { id: 203, text: "Boundary layer suction is:", options: ["Commonly used on all aircraft", "An experimental method removing stagnating boundary layer", "A type of flap"], correctOptionIndex: 1 },
  { id: 204, text: "Laminar flow aerofoils have highest thickness at:", options: ["10-20% of chord", "40-60% of chord", "70-80% of chord"], correctOptionIndex: 1 },
  { id: 205, text: "Laminar flow aerofoils require much more attention to:", options: ["Engine power", "Cleanness (surface conditions) of wing skin", "Weight distribution"], correctOptionIndex: 1 },
  { id: 206, text: "The first aircraft to operate with laminar flow principle was:", options: ["Spitfire", "P51 Mustang", "B17 Flying Fortress"], correctOptionIndex: 1 },
  { id: 207, text: "Vortex generators are rows of:", options: ["Large wings", "Small vertically attached fins", "Flaps"], correctOptionIndex: 1 },
  { id: 208, text: "The height of a vortex generator extends:", options: ["Only through boundary layer", "Through boundary layer and up into free air stream", "Only into free air stream"], correctOptionIndex: 1 },
  { id: 209, text: "The vortex generator is effectively a:", options: ["Low aspect ratio wing", "Very high aspect ratio wing (short and stubby) positioned vertically", "Flat plate"], correctOptionIndex: 1 },
  { id: 210, text: "The tip vortex draws:", options: ["Low pressure air into boundary layer", "High pressure air from free stream into boundary layer", "Boundary layer away from wing"], correctOptionIndex: 1 },
  { id: 211, text: "Leading-edge slots allow:", options: ["Air to flow from upper to lower surface", "High pressure air from lower side to flow to upper side", "Boundary layer to stagnate"], correctOptionIndex: 1 },
  { id: 212, text: "Automatic slats extend by way of aerodynamics when needed. They are sometimes called:", options: ["Krueger flaps", "Handley-Page slats", "Fowler flaps"], correctOptionIndex: 1 },
  { id: 213, text: "Fixed slots are sometimes used on:", options: ["High-speed aircraft", "Specialist low-speed aircraft", "All aircraft"], correctOptionIndex: 1 },
  { id: 214, text: "Trailing edge slots in flaps allow high-pressure air to:", options: ["Escape from wing", "Flow through into boundary layer on top of flap, re-energising it", "Increase pressure on top of flap"], correctOptionIndex: 1 },
  { id: 215, text: "Boundary layer blowing uses:", options: ["External air", "Engine bleed air", "Ram air"], correctOptionIndex: 1 },
  { id: 216, text: "The Blackburn Buccaneer used:", options: ["Only flaps", "Boundary layer blowing", "Only slats"], correctOptionIndex: 1 },
  { id: 217, text: "Wing fences are also referred to as:", options: ["Vortex generators", "Boundary layer fences or potential fences", "Spoilers"], correctOptionIndex: 1 },
  { id: 218, text: "The purpose of wing fences is to:", options: ["Increase spanwise flow", "Obstruct spanwise airflow along the wing", "Decrease chordwise flow"], correctOptionIndex: 1 },
  { id: 219, text: "Wing fences help prevent:", options: ["Lift increase", "Entire wing from stalling at once", "Drag decrease"], correctOptionIndex: 1 },
  { id: 220, text: "A strake is generally:", options: ["Shorter than it is wide", "Longer than it is wide", "Equal in length and width"], correctOptionIndex: 1 },
  { id: 221, text: "A leading-edge root extension (LERX) generates at high angles of attack:", options: ["Low-speed airflow", "A high-speed vortex that attaches to top of wing", "Stagnant air"], correctOptionIndex: 1 },
  { id: 222, text: "Vortilon is a contraction of the words:", options: ["Vortex and aileron", "Vortex and pylon", "Vortex and spoiler"], correctOptionIndex: 1 },
  { id: 223, text: "Vortilons are attached to:", options: ["Upper surface of wing near trailing edge", "Underside of wing near leading edge", "Fuselage"], correctOptionIndex: 1 },
  { id: 224, text: "Stall wedges (stall strips) are placed on:", options: ["Trailing edge of wing in tip area", "Leading edge of wing in root area", "Fuselage nose"], correctOptionIndex: 1 },
  { id: 225, text: "Stall wedges ensure that wing stalls:", options: ["From tip to root", "Progressively from root out to tip", "Simultaneously across whole wing"], correctOptionIndex: 1 },
];
