export const tvRemoteElectromagneticSpectrumQuestions = [
  {
    id: 1,
    text: "What does a traditional TV remote commonly use to send commands?",
    options: ["Infrared light", "Water waves", "Visible green light"],
    correctOptionIndex: 0,
  },
  {
    id: 2,
    text: "What happens when a button on a remote is pressed?",
    options: ["The screen changes color inside the remote", "A small circuit closes", "The TV battery charges"],
    correctOptionIndex: 1,
  },
  {
    id: 3,
    text: "What part of the remote recognizes the pressed button?",
    options: ["The speaker", "The microchip", "The plastic case"],
    correctOptionIndex: 1,
  },
  {
    id: 4,
    text: "What does the microchip do with the command?",
    options: ["Turns it into a coded signal", "Turns it into heat only", "Turns it into water vapor"],
    correctOptionIndex: 0,
  },
  {
    id: 5,
    text: "What component usually emits the infrared signal?",
    options: ["Battery", "Infrared LED", "Volume button"],
    correctOptionIndex: 1,
  },
  {
    id: 6,
    text: "The infrared LED is usually located:",
    options: ["At the front/tip of the remote", "Inside the TV screen", "Under the sofa"],
    correctOptionIndex: 0,
  },
  {
    id: 7,
    text: "Why do we usually not see the remote's infrared light?",
    options: ["It is too loud", "It is outside normal human vision", "It is made of metal"],
    correctOptionIndex: 1,
  },
  {
    id: 8,
    text: "What part of the TV receives the infrared signal?",
    options: ["HDMI cable", "Infrared sensor", "Speaker magnet"],
    correctOptionIndex: 1,
  },
  {
    id: 9,
    text: "After receiving the code, the TV:",
    options: ["Interprets it and executes the command", "Sends it to the batteries", "Turns it into paper"],
    correctOptionIndex: 0,
  },
  {
    id: 10,
    text: "Which action can be controlled by a TV remote?",
    options: ["Increasing volume", "Cooking food", "Producing rain"],
    correctOptionIndex: 0,
  },
  {
    id: 11,
    text: "Why do many infrared remotes need to be pointed toward the TV?",
    options: ["Infrared behaves like light and needs a path to the sensor", "The remote uses smell", "The buttons only work upward"],
    correctOptionIndex: 0,
  },
  {
    id: 12,
    text: "What powers a basic remote control circuit?",
    options: ["The TV antenna", "The batteries", "The room light"],
    correctOptionIndex: 1,
  },
  {
    id: 13,
    text: "In a simplified remote circuit, the button acts as:",
    options: ["A switch", "A camera", "A motor"],
    correctOptionIndex: 0,
  },
  {
    id: 14,
    text: "A correct simplified sequence inside a remote is:",
    options: ["Batteries → button → microchip → infrared LED", "TV screen → sofa → battery → air", "Speaker → water → button → lamp"],
    correctOptionIndex: 0,
  },
  {
    id: 15,
    text: "What does the infrared signal carry?",
    options: ["A coded command", "Liquid electricity", "Visible ink"],
    correctOptionIndex: 0,
  },
  {
    id: 16,
    text: "The TV changes channel after receiving:",
    options: ["A random light pulse", "A recognized code", "A sound from the remote"],
    correctOptionIndex: 1,
  },
  {
    id: 17,
    text: "What is the function of the TV processor after the sensor receives the signal?",
    options: ["Interpret the command", "Recharge the remote", "Change the battery type"],
    correctOptionIndex: 0,
  },
  {
    id: 18,
    text: "Which remotes may not need to be pointed directly at the TV?",
    options: ["Bluetooth or Wi-Fi remotes", "Paper remotes", "Wooden remotes"],
    correctOptionIndex: 0,
  },
  {
    id: 19,
    text: "Bluetooth and Wi-Fi remotes use communication by:",
    options: ["Radio waves", "Visible paint", "Water pressure"],
    correctOptionIndex: 0,
  },
  {
    id: 20,
    text: "Traditional infrared communication from remote to TV is mostly:",
    options: ["One-way command transmission", "Mechanical pulling", "Chemical reaction"],
    correctOptionIndex: 0,
  },
  {
    id: 21,
    text: "What does \"infra\" mean?",
    options: ["Above", "Below", "Around"],
    correctOptionIndex: 1,
  },
  {
    id: 22,
    text: "\"Infrared\" literally means:",
    options: ["Below red", "Above blue", "Inside violet"],
    correctOptionIndex: 0,
  },
  {
    id: 23,
    text: "Infrared is located near which visible color?",
    options: ["Green", "Violet", "Red"],
    correctOptionIndex: 2,
  },
  {
    id: 24,
    text: "Infrared is part of the:",
    options: ["Electromagnetic spectrum", "Sound spectrum only", "Periodic table only"],
    correctOptionIndex: 0,
  },
  {
    id: 25,
    text: "Infrared radiation is usually:",
    options: ["Visible as purple", "Invisible to human eyes", "A mechanical wave"],
    correctOptionIndex: 1,
  },
  {
    id: 26,
    text: "Which device commonly uses infrared?",
    options: ["TV remote", "Pencil", "Spoon"],
    correctOptionIndex: 0,
  },
  {
    id: 27,
    text: "Infrared can be used in:",
    options: ["Thermal cameras", "Paper notebooks", "Wooden chairs"],
    correctOptionIndex: 0,
  },
  {
    id: 28,
    text: "Infrared can be detected by:",
    options: ["Suitable infrared sensors", "Only human ears", "Only ordinary paper"],
    correctOptionIndex: 0,
  },
  {
    id: 29,
    text: "Infrared has a frequency generally:",
    options: ["Lower than visible red", "Higher than gamma rays", "Equal to X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 30,
    text: "Infrared has a wavelength generally:",
    options: ["Shorter than ultraviolet", "Longer than visible red", "Equal to violet light"],
    correctOptionIndex: 1,
  },
  {
    id: 31,
    text: "The remote's infrared signal is like:",
    options: ["Invisible coded light", "Visible rope", "Sound only"],
    correctOptionIndex: 0,
  },
  {
    id: 32,
    text: "A phone camera may sometimes show infrared because:",
    options: ["Some cameras can detect near-infrared better than human eyes", "The remote produces smoke", "The TV creates water vapor"],
    correctOptionIndex: 0,
  },
  {
    id: 33,
    text: "Infrared comes before visible red when moving from:",
    options: ["Lower to higher frequency", "Higher to lower energy", "Gamma rays to X-rays only"],
    correctOptionIndex: 0,
  },
  {
    id: 34,
    text: "Infrared is not normally seen because human eyes are sensitive mainly to:",
    options: ["Visible light", "Radio waves", "X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 35,
    text: "Infrared is electromagnetic radiation, not:",
    options: ["A sound wave", "Light outside visible range", "A form of energy transfer"],
    correctOptionIndex: 0,
  },
  {
    id: 36,
    text: "Is visible light made of only 6 colors?",
    options: ["Yes, exactly 6", "No, it is a continuous range", "No, it has no colors"],
    correctOptionIndex: 1,
  },
  {
    id: 37,
    text: "The common main colors of visible light are:",
    options: ["Red, orange, yellow, green, blue, indigo, violet", "Radio, microwave, infrared", "Black, white, gray"],
    correctOptionIndex: 0,
  },
  {
    id: 38,
    text: "Why do some lists show 6 colors instead of 7?",
    options: ["Indigo is sometimes grouped with blue or violet", "Red is not visible", "Yellow is infrared"],
    correctOptionIndex: 0,
  },
  {
    id: 39,
    text: "From red to violet, frequency:",
    options: ["Decreases", "Increases", "Disappears"],
    correctOptionIndex: 1,
  },
  {
    id: 40,
    text: "From red to violet, energy:",
    options: ["Increases", "Decreases", "Becomes zero"],
    correctOptionIndex: 0,
  },
  {
    id: 41,
    text: "From red to violet, wavelength:",
    options: ["Increases", "Decreases", "Is unchanged"],
    correctOptionIndex: 1,
  },
  {
    id: 42,
    text: "Which visible color has a longer wavelength?",
    options: ["Violet", "Red", "Blue"],
    correctOptionIndex: 1,
  },
  {
    id: 43,
    text: "Which visible color has higher frequency?",
    options: ["Red", "Orange", "Violet"],
    correctOptionIndex: 2,
  },
  {
    id: 44,
    text: "Which has higher energy?",
    options: ["Violet light", "Red light", "Orange light"],
    correctOptionIndex: 0,
  },
  {
    id: 45,
    text: "Which has lower energy?",
    options: ["Red light", "Violet light", "Ultraviolet"],
    correctOptionIndex: 0,
  },
  {
    id: 46,
    text: "The visible spectrum lies between:",
    options: ["Infrared and ultraviolet", "Radio and microwaves", "X-rays and gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 47,
    text: "White light is best described as:",
    options: ["Absence of light", "A mixture of many visible colors", "Only one red wavelength"],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    text: "Black, from the viewpoint of light reaching the eyes, means:",
    options: ["Little or no visible light", "A mixture of all strong visible light", "Only blue light"],
    correctOptionIndex: 0,
  },
  {
    id: 49,
    text: "A white object appears white because it:",
    options: ["Reflects many visible colors", "Absorbs all visible colors", "Emits only gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 50,
    text: "A black object appears black because it:",
    options: ["Reflects all light perfectly", "Absorbs most visible light and reflects little", "Produces ultraviolet only"],
    correctOptionIndex: 1,
  },
  {
    id: 51,
    text: "White and black are not separate spectrum bands because they depend on:",
    options: ["Mixture, reflection, or absence of light", "Only radio frequency", "Only magnetic metal"],
    correctOptionIndex: 0,
  },
  {
    id: 52,
    text: "A prism can separate white light into:",
    options: ["Different visible colors", "Only radio waves", "Only sound waves"],
    correctOptionIndex: 0,
  },
  {
    id: 53,
    text: "Sunlight can appear white because it contains:",
    options: ["Many visible wavelengths", "Only infrared", "Only gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 54,
    text: "The color \"indigo\" is also called:",
    options: ["Anil", "Infrared", "Gamma"],
    correctOptionIndex: 0,
  },
  {
    id: 55,
    text: "The visible range is only a small part of the:",
    options: ["Electromagnetic spectrum", "Mechanical spectrum", "Chemical spectrum"],
    correctOptionIndex: 0,
  },
  {
    id: 56,
    text: "Electromagnetic waves are produced by oscillations of:",
    options: ["Electric and magnetic fields", "Water and soil", "Sound and air only"],
    correctOptionIndex: 0,
  },
  {
    id: 57,
    text: "Electromagnetic waves can propagate through:",
    options: ["Space", "Only water", "Only wood"],
    correctOptionIndex: 0,
  },
  {
    id: 58,
    text: "Visible light is:",
    options: ["A mechanical wave only", "An electromagnetic wave", "A chemical liquid"],
    correctOptionIndex: 1,
  },
  {
    id: 59,
    text: "Radio waves are:",
    options: ["Electromagnetic waves", "Sound waves only", "Water waves only"],
    correctOptionIndex: 0,
  },
  {
    id: 60,
    text: "Microwaves are:",
    options: ["Electromagnetic waves", "Mechanical ropes", "Solid particles only"],
    correctOptionIndex: 0,
  },
  {
    id: 61,
    text: "Electromagnetic waves are characterized by:",
    options: ["Frequency, wavelength, and energy", "Taste, smell, and weight only", "Price, size, and shape only"],
    correctOptionIndex: 0,
  },
  {
    id: 62,
    text: "Frequency and wavelength are generally:",
    options: ["Directly proportional", "Inversely related", "Unrelated"],
    correctOptionIndex: 1,
  },
  {
    id: 63,
    text: "If wavelength decreases, frequency usually:",
    options: ["Increases", "Decreases", "Disappears"],
    correctOptionIndex: 0,
  },
  {
    id: 64,
    text: "If wavelength increases, frequency usually:",
    options: ["Increases", "Decreases", "Turns into mass"],
    correctOptionIndex: 1,
  },
  {
    id: 65,
    text: "If frequency increases, photon energy generally:",
    options: ["Increases", "Decreases", "Becomes zero"],
    correctOptionIndex: 0,
  },
  {
    id: 66,
    text: "If frequency decreases, energy generally:",
    options: ["Decreases", "Increases", "Becomes infinite"],
    correctOptionIndex: 0,
  },
  {
    id: 67,
    text: "The formula connecting speed, wavelength, and frequency is:",
    options: ["c = λ · f", "c = λ + f", "c = λ − f"],
    correctOptionIndex: 0,
  },
  {
    id: 68,
    text: "In c = λ · f, λ means:",
    options: ["Frequency", "Wavelength", "Energy"],
    correctOptionIndex: 1,
  },
  {
    id: 69,
    text: "In c = λ · f, f means:",
    options: ["Frequency", "Force only", "Color name"],
    correctOptionIndex: 0,
  },
  {
    id: 70,
    text: "If the same electromagnetic wave has the same wavelength in the same medium, its frequency is:",
    options: ["Also the same", "Always different", "Zero"],
    correctOptionIndex: 0,
  },
  {
    id: 71,
    text: "The speed c is approximately the speed of:",
    options: ["Electromagnetic radiation in vacuum", "A car", "A battery"],
    correctOptionIndex: 0,
  },
  {
    id: 72,
    text: "In electromagnetic waves, higher frequency usually means:",
    options: ["Shorter wavelength", "Longer wavelength", "No wavelength"],
    correctOptionIndex: 0,
  },
  {
    id: 73,
    text: "In electromagnetic waves, shorter wavelength usually means:",
    options: ["Lower energy", "Higher frequency", "No energy"],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    text: "Electromagnetic waves do not require:",
    options: ["A material medium like air or water", "Electric and magnetic fields", "Frequency"],
    correctOptionIndex: 0,
  },
  {
    id: 75,
    text: "Light is electromagnetic radiation within a certain:",
    options: ["Frequency and wavelength range", "Chemical temperature only", "Sound intensity only"],
    correctOptionIndex: 0,
  },
  {
    id: 76,
    text: "The electromagnetic spectrum is:",
    options: ["The full range of electromagnetic radiation", "Only visible colors", "Only radio stations"],
    correctOptionIndex: 0,
  },
  {
    id: 77,
    text: "The simplified order from lower frequency to higher frequency is:",
    options: ["Radio → microwave → infrared → visible → ultraviolet → X-rays → gamma rays", "Gamma rays → radio → visible → infrared", "Visible → radio → X-rays → microwave"],
    correctOptionIndex: 0,
  },
  {
    id: 78,
    text: "In that order, frequency:",
    options: ["Increases", "Decreases", "Stops"],
    correctOptionIndex: 0,
  },
  {
    id: 79,
    text: "In that order, energy:",
    options: ["Increases", "Decreases", "Disappears"],
    correctOptionIndex: 0,
  },
  {
    id: 80,
    text: "In that order, wavelength:",
    options: ["Increases", "Decreases", "Is not present"],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    text: "Which comes after radio waves in the simplified spectrum?",
    options: ["Microwaves", "Gamma rays", "Visible light"],
    correctOptionIndex: 0,
  },
  {
    id: 82,
    text: "Which comes after microwaves?",
    options: ["Infrared", "Gamma rays", "X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 83,
    text: "Which comes after infrared?",
    options: ["Visible light", "Radio waves", "Gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 84,
    text: "Which comes after visible light as frequency increases?",
    options: ["Ultraviolet", "Infrared", "Microwaves"],
    correctOptionIndex: 0,
  },
  {
    id: 85,
    text: "Which comes after ultraviolet?",
    options: ["X-rays", "Radio waves", "Infrared"],
    correctOptionIndex: 0,
  },
  {
    id: 86,
    text: "Which comes after X-rays?",
    options: ["Gamma rays", "Microwaves", "Visible red"],
    correctOptionIndex: 0,
  },
  {
    id: 87,
    text: "Which has the lowest frequency in the simplified list?",
    options: ["Radio waves", "Visible light", "Gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 88,
    text: "Which has the highest frequency in the simplified list?",
    options: ["Microwaves", "Infrared", "Gamma rays"],
    correctOptionIndex: 2,
  },
  {
    id: 89,
    text: "Which has the highest energy in the simplified list?",
    options: ["Gamma rays", "Radio waves", "Infrared"],
    correctOptionIndex: 0,
  },
  {
    id: 90,
    text: "Which has the longest wavelength in the simplified list?",
    options: ["Radio waves", "X-rays", "Gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 91,
    text: "Which has shorter wavelength than visible light?",
    options: ["Ultraviolet", "Infrared", "Microwaves"],
    correctOptionIndex: 0,
  },
  {
    id: 92,
    text: "Which has longer wavelength than visible light?",
    options: ["Infrared", "Ultraviolet", "X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 93,
    text: "X-rays are commonly used in:",
    options: ["Medical imaging", "Remote-control buttons", "Radio AM broadcasting"],
    correctOptionIndex: 0,
  },
  {
    id: 94,
    text: "Gamma rays are:",
    options: ["Very high-energy electromagnetic radiation", "Low-frequency sound waves", "Water waves"],
    correctOptionIndex: 0,
  },
  {
    id: 95,
    text: "It is technically correct to call radio waves \"radiation\" because they are:",
    options: ["Electromagnetic radiation", "Mechanical waves only", "Chemical liquids"],
    correctOptionIndex: 0,
  },
  {
    id: 96,
    text: "In everyday language, \"radiation\" is often used more for:",
    options: ["Higher-frequency waves like ultraviolet, X-rays, and gamma rays", "Only AM radio", "Only visible green light"],
    correctOptionIndex: 0,
  },
  {
    id: 97,
    text: "Higher-frequency electromagnetic radiation can have stronger effects on matter because it has:",
    options: ["More energy", "No wavelength", "No electric field"],
    correctOptionIndex: 0,
  },
  {
    id: 98,
    text: "The electromagnetic spectrum can be imagined as:",
    options: ["A large \"ruler\" of radiation types", "A type of battery", "A sound machine"],
    correctOptionIndex: 0,
  },
  {
    id: 99,
    text: "The human eye detects directly mainly:",
    options: ["Visible light", "Radio waves", "Gamma rays"],
    correctOptionIndex: 0,
  },
  {
    id: 100,
    text: "Infrared is between:",
    options: ["Microwaves and visible light", "X-rays and gamma rays", "Ultraviolet and X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 101,
    text: "Sensors can detect electromagnetic radiation depending on its:",
    options: ["Frequency or wavelength range", "Taste", "Nationality"],
    correctOptionIndex: 0,
  },
  {
    id: 102,
    text: "A radar sensor is mainly related to:",
    options: ["Radio or microwave radiation", "Visible yellow only", "Water waves only"],
    correctOptionIndex: 0,
  },
  {
    id: 103,
    text: "An infrared sensor detects:",
    options: ["Infrared radiation", "Only X-rays", "Only sound"],
    correctOptionIndex: 0,
  },
  {
    id: 104,
    text: "A visible-light sensor detects:",
    options: ["Visible light", "Long radio waves only", "Mechanical vibration only"],
    correctOptionIndex: 0,
  },
  {
    id: 105,
    text: "A UV sensor detects:",
    options: ["Ultraviolet radiation", "Infrared only", "AM radio only"],
    correctOptionIndex: 0,
  },
  {
    id: 106,
    text: "An X-ray detector detects:",
    options: ["X-rays", "Bluetooth signals only", "Water waves"],
    correctOptionIndex: 0,
  },
  {
    id: 107,
    text: "A TV infrared receiver is an example of:",
    options: ["A sensor for infrared radiation", "A gamma-ray source", "A microwave oven"],
    correctOptionIndex: 0,
  },
  {
    id: 108,
    text: "A sensor designed for one range may not detect another range well because different waves have different:",
    options: ["Frequencies and wavelengths", "Flavors", "Smells"],
    correctOptionIndex: 0,
  },
  {
    id: 109,
    text: "A microwave sensor is designed to detect:",
    options: ["Microwave radiation", "Only visible violet", "Only mechanical pressure"],
    correctOptionIndex: 0,
  },
  {
    id: 110,
    text: "Sensors convert detected radiation into:",
    options: ["Electrical information or signals", "Only paper", "Water"],
    correctOptionIndex: 0,
  },
  {
    id: 111,
    text: "Compared with visible light, radio waves generally have:",
    options: ["Longer wavelengths and lower frequencies", "Shorter wavelengths and higher frequencies", "No wavelength"],
    correctOptionIndex: 0,
  },
  {
    id: 112,
    text: "Radio waves are mainly used for:",
    options: ["Communication", "Freezing light", "Producing only X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 113,
    text: "Radio waves can include:",
    options: ["Long waves, medium waves, short waves, VHF, UHF, microwaves", "Red, yellow, violet only", "X-rays and gamma rays only"],
    correctOptionIndex: 0,
  },
  {
    id: 114,
    text: "Long waves have approximately:",
    options: ["10 km to 1 km", "1 m to 1 mm", "1 cm to 1 nm"],
    correctOptionIndex: 0,
  },
  {
    id: 115,
    text: "Medium waves have approximately:",
    options: ["1 km to 100 m", "1 mm to 1 μm", "10 cm to 1 mm"],
    correctOptionIndex: 0,
  },
  {
    id: 116,
    text: "Short waves have approximately:",
    options: ["100 m to 10 m", "1 m to 10 cm", "1 mm to 1 nm"],
    correctOptionIndex: 0,
  },
  {
    id: 117,
    text: "VHF has approximately:",
    options: ["10 m to 1 m", "10 km to 1 km", "1 mm to 1 μm"],
    correctOptionIndex: 0,
  },
  {
    id: 118,
    text: "UHF has approximately:",
    options: ["1 m to 10 cm", "100 m to 10 m", "1 km to 100 m"],
    correctOptionIndex: 0,
  },
  {
    id: 119,
    text: "Microwaves have approximately:",
    options: ["1 m to 1 mm", "10 km to 1 km", "100 km to 10 km"],
    correctOptionIndex: 0,
  },
  {
    id: 120,
    text: "Long waves are associated with:",
    options: ["Maritime communication and navigation", "Only visible violet", "Only X-ray imaging"],
    correctOptionIndex: 0,
  },
  {
    id: 121,
    text: "Medium waves are associated with:",
    options: ["AM radio", "Gamma-ray astronomy only", "Ultraviolet light only"],
    correctOptionIndex: 0,
  },
  {
    id: 122,
    text: "Short waves are useful for:",
    options: ["Long-distance communication", "Only cooking food", "Only remote-control LEDs"],
    correctOptionIndex: 0,
  },
  {
    id: 123,
    text: "VHF can be used for:",
    options: ["FM radio, television, aeronautical communication", "X-rays only", "Gamma rays only"],
    correctOptionIndex: 0,
  },
  {
    id: 124,
    text: "UHF can be used for:",
    options: ["Digital TV, mobile phones, Wi-Fi, Bluetooth", "Only ultraviolet tanning", "Only X-ray scans"],
    correctOptionIndex: 0,
  },
  {
    id: 125,
    text: "Microwaves can be used for:",
    options: ["Radar, satellites, microwave ovens, wireless networks", "Only paper printing", "Only pencils"],
    correctOptionIndex: 0,
  },
  {
    id: 126,
    text: "Long waves generally have:",
    options: ["Lower frequency than UHF", "Higher frequency than gamma rays", "No frequency"],
    correctOptionIndex: 0,
  },
  {
    id: 127,
    text: "UHF generally has:",
    options: ["Higher frequency than VHF", "Lower frequency than long waves", "No wavelength"],
    correctOptionIndex: 0,
  },
  {
    id: 128,
    text: "VHF means:",
    options: ["Very High Frequency", "Very Heavy Field", "Visible High Flame"],
    correctOptionIndex: 0,
  },
  {
    id: 129,
    text: "UHF means:",
    options: ["Ultra High Frequency", "Universal Heat Force", "Under Hidden Field"],
    correctOptionIndex: 0,
  },
  {
    id: 130,
    text: "Radio waves in the broad sense form:",
    options: ["A large family of electromagnetic waves", "A single exact wave only", "A type of sound only"],
    correctOptionIndex: 0,
  },
  {
    id: 131,
    text: "In a broad technical sense, microwaves are:",
    options: ["A type of radio wave", "A type of visible light", "A type of sound"],
    correctOptionIndex: 0,
  },
  {
    id: 132,
    text: "Which statement is correct?",
    options: ["Every microwave is a radio wave, but not every radio wave is a microwave", "Every radio wave is a microwave", "No microwave is a radio wave"],
    correctOptionIndex: 0,
  },
  {
    id: 133,
    text: "Microwaves have, compared with many ordinary radio waves:",
    options: ["Higher frequency and shorter wavelength", "Lower frequency and longer wavelength", "No frequency"],
    correctOptionIndex: 0,
  },
  {
    id: 134,
    text: "In school diagrams, radio waves and microwaves may appear:",
    options: ["As neighboring separate regions", "As sound waves", "As chemical elements"],
    correctOptionIndex: 0,
  },
  {
    id: 135,
    text: "The apparent contradiction about microwaves and radio waves is solved by understanding:",
    options: ["Different classification conventions", "Different colors of plastic", "Different battery brands"],
    correctOptionIndex: 0,
  },
  {
    id: 136,
    text: "In the broad classification, radio waves include:",
    options: ["Microwaves", "X-rays only", "Visible colors only"],
    correctOptionIndex: 0,
  },
  {
    id: 137,
    text: "In the simplified school classification, radio waves and microwaves can be shown:",
    options: ["Separately", "As non-electromagnetic", "As the same as sound"],
    correctOptionIndex: 0,
  },
  {
    id: 138,
    text: "The fruit analogy says radio waves are like:",
    options: ["The large family", "Only one mango", "A stone"],
    correctOptionIndex: 0,
  },
  {
    id: 139,
    text: "The fruit analogy says microwaves are like:",
    options: ["A subgroup inside the larger family", "Something outside the family", "The absence of fruit"],
    correctOptionIndex: 0,
  },
  {
    id: 140,
    text: "\"Every mango is a fruit, but not every fruit is a mango\" explains:",
    options: ["Every microwave is a radio wave, but not every radio wave is a microwave", "Every color is black", "Every X-ray is visible light"],
    correctOptionIndex: 0,
  },
  {
    id: 141,
    text: "Microwaves are special radio waves because they occupy:",
    options: ["Higher-frequency, shorter-wavelength radio ranges", "Lower-frequency visible ranges", "Sound ranges"],
    correctOptionIndex: 0,
  },
  {
    id: 142,
    text: "The term \"microwave\" refers to waves with:",
    options: ["Relatively short wavelengths compared with many radio waves", "No wavelength", "Only visible colors"],
    correctOptionIndex: 0,
  },
  {
    id: 143,
    text: "Microwaves are not:",
    options: ["Mechanical sound waves", "Electromagnetic waves", "A radio-frequency category in broad sense"],
    correctOptionIndex: 0,
  },
  {
    id: 144,
    text: "A microwave oven uses:",
    options: ["Microwave electromagnetic radiation", "Gamma rays only", "Visible violet only"],
    correctOptionIndex: 0,
  },
  {
    id: 145,
    text: "Radar often uses:",
    options: ["Microwaves", "Only red visible light", "Only sound in air"],
    correctOptionIndex: 0,
  },
  {
    id: 146,
    text: "Long waves were matched with:",
    options: ["10 km to 1 km", "1 m to 1 mm", "1 cm to 1 nm"],
    correctOptionIndex: 0,
  },
  {
    id: 147,
    text: "Medium waves were matched with:",
    options: ["1 km to 100 m", "1 mm to 1 μm", "10 cm to 1 mm"],
    correctOptionIndex: 0,
  },
  {
    id: 148,
    text: "Short waves were matched with:",
    options: ["100 m to 10 m", "1 m to 10 cm", "1 mm to 1 nm"],
    correctOptionIndex: 0,
  },
  {
    id: 149,
    text: "VHF was matched with:",
    options: ["10 m to 1 m", "10 km to 1 km", "1 mm to 1 μm"],
    correctOptionIndex: 0,
  },
  {
    id: 150,
    text: "UHF was matched with:",
    options: ["1 m to 10 cm", "100 m to 10 m", "1 km to 100 m"],
    correctOptionIndex: 0,
  },
  {
    id: 151,
    text: "Microwaves were matched with:",
    options: ["1 m to 1 mm", "10 km to 1 km", "100 km to 10 km"],
    correctOptionIndex: 0,
  },
  {
    id: 152,
    text: "Long waves were matched with frequency:",
    options: ["30 kHz to 300 kHz", "300 MHz to 3 GHz", "300 GHz to 3 THz"],
    correctOptionIndex: 0,
  },
  {
    id: 153,
    text: "Medium waves were matched with frequency:",
    options: ["300 kHz to 3 MHz", "3 GHz to 30 GHz", "30 GHz to 300 GHz"],
    correctOptionIndex: 0,
  },
  {
    id: 154,
    text: "Short waves were matched with frequency:",
    options: ["3 MHz to 30 MHz", "300 MHz to 3 GHz", "30 GHz to 300 GHz"],
    correctOptionIndex: 0,
  },
  {
    id: 155,
    text: "VHF was matched with frequency:",
    options: ["30 MHz to 300 MHz", "300 Hz to 3 kHz", "300 GHz to 3 THz"],
    correctOptionIndex: 0,
  },
  {
    id: 156,
    text: "UHF was matched with frequency:",
    options: ["300 MHz to 3 GHz", "30 kHz to 300 kHz", "3 Hz to 30 Hz"],
    correctOptionIndex: 0,
  },
  {
    id: 157,
    text: "Microwaves were matched with frequency:",
    options: ["300 MHz to 300 GHz", "30 Hz to 300 Hz", "10 kHz to 20 kHz"],
    correctOptionIndex: 0,
  },
  {
    id: 158,
    text: "A wavelength of 1 m corresponds roughly to:",
    options: ["300 MHz", "300 GHz", "30 kHz"],
    correctOptionIndex: 0,
  },
  {
    id: 159,
    text: "A wavelength of 10 cm corresponds roughly to:",
    options: ["3 GHz", "3 kHz", "30 GHz"],
    correctOptionIndex: 0,
  },
  {
    id: 160,
    text: "A wavelength of 1 cm corresponds roughly to:",
    options: ["30 GHz", "30 MHz", "300 kHz"],
    correctOptionIndex: 0,
  },
  {
    id: 161,
    text: "A wavelength of 1 mm corresponds roughly to:",
    options: ["300 GHz", "300 MHz", "30 Hz"],
    correctOptionIndex: 0,
  },
  {
    id: 162,
    text: "As wavelength changes from 1 m to 10 cm, frequency changes from:",
    options: ["300 MHz to 3 GHz", "30 kHz to 300 kHz", "30 GHz to 300 GHz"],
    correctOptionIndex: 0,
  },
  {
    id: 163,
    text: "As wavelength changes from 1 m to 1 mm, frequency changes from approximately:",
    options: ["300 MHz to 300 GHz", "300 Hz to 3 kHz", "3 MHz to 30 MHz"],
    correctOptionIndex: 0,
  },
  {
    id: 164,
    text: "A frequency of 3 GHz corresponds roughly to:",
    options: ["10 cm", "10 km", "1 μm"],
    correctOptionIndex: 0,
  },
  {
    id: 165,
    text: "A frequency of 30 GHz corresponds roughly to:",
    options: ["1 cm", "10 m", "100 m"],
    correctOptionIndex: 0,
  },
  {
    id: 166,
    text: "UHF has approximately which wavelength range?",
    options: ["1 m to 10 cm", "10 km to 1 km", "1 mm to 1 μm"],
    correctOptionIndex: 0,
  },
  {
    id: 167,
    text: "Microwaves have approximately which wavelength range?",
    options: ["1 m to 1 mm", "100 km to 10 km", "10 m to 1 m only"],
    correctOptionIndex: 0,
  },
  {
    id: 168,
    text: "The wavelength overlap between UHF and microwaves is:",
    options: ["1 m to 10 cm", "10 km to 1 km", "1 mm to 1 μm"],
    correctOptionIndex: 0,
  },
  {
    id: 169,
    text: "The frequency overlap between UHF and microwaves is:",
    options: ["300 MHz to 3 GHz", "30 kHz to 300 kHz", "30 GHz to 300 GHz only"],
    correctOptionIndex: 0,
  },
  {
    id: 170,
    text: "In the overlap, the same wave can be called:",
    options: ["UHF and microwave", "X-ray and sound", "Visible red and gamma ray"],
    correctOptionIndex: 0,
  },
  {
    id: 171,
    text: "In the overlap, the difference is mainly:",
    options: ["Classification convention", "Physical destruction of the wave", "A change into matter"],
    correctOptionIndex: 0,
  },
  {
    id: 172,
    text: "In the overlap from 1 m to 10 cm, is there a physical wavelength difference between the labels UHF and microwave?",
    options: ["No", "Yes, always", "Only at night"],
    correctOptionIndex: 0,
  },
  {
    id: 173,
    text: "In the overlap from 300 MHz to 3 GHz, is there a physical frequency difference between the labels UHF and microwave?",
    options: ["No", "Yes, always", "Frequency disappears"],
    correctOptionIndex: 0,
  },
  {
    id: 174,
    text: "The overlap in wavelength corresponds exactly to:",
    options: ["The overlap in frequency", "No frequency range", "Only visible colors"],
    correctOptionIndex: 0,
  },
  {
    id: 175,
    text: "Between 10 cm and 1 m, a wave may be classified as:",
    options: ["Both UHF and microwave", "Only gamma ray", "Only ultraviolet"],
    correctOptionIndex: 0,
  },
  {
    id: 176,
    text: "UHF is best described as:",
    options: ["A radio-frequency band", "A visible color", "A type of battery"],
    correctOptionIndex: 0,
  },
  {
    id: 177,
    text: "Microwaves are best described as:",
    options: ["A broader category that includes part of UHF in this classification", "A smaller exact channel only", "A color between blue and violet"],
    correctOptionIndex: 0,
  },
  {
    id: 178,
    text: "In terms of wavelength, UHF is:",
    options: ["A smaller part of the broader microwave range", "Bigger than all microwaves", "Unrelated to microwaves"],
    correctOptionIndex: 0,
  },
  {
    id: 179,
    text: "In the overlap, what changes when we say \"UHF\" or \"microwave\"?",
    options: ["The label/classification", "The physical wave itself", "The speed of light in vacuum"],
    correctOptionIndex: 0,
  },
  {
    id: 180,
    text: "The sentence \"the difference is not physical; it is classification\" means:",
    options: ["The same wave can receive different category names", "The wave has no frequency", "The wave is fake"],
    correctOptionIndex: 0,
  },
  {
    id: 181,
    text: "UHF occupies which part of the microwave range?",
    options: ["The longer-wavelength/lower-frequency beginning", "The gamma-ray end", "The visible-light section"],
    correctOptionIndex: 0,
  },
  {
    id: 182,
    text: "Microwaves continue beyond UHF toward:",
    options: ["Smaller wavelengths and higher frequencies", "Larger wavelengths and lower frequencies only", "No wavelengths"],
    correctOptionIndex: 0,
  },
  {
    id: 183,
    text: "If a wave is 50 cm, it falls within:",
    options: ["The overlap of UHF and microwaves", "Only gamma rays", "Visible light"],
    correctOptionIndex: 0,
  },
  {
    id: 184,
    text: "If a wave is 5 cm, it is:",
    options: ["In the microwave range but outside UHF by the simplified ranges", "In long waves", "In visible light"],
    correctOptionIndex: 0,
  },
  {
    id: 185,
    text: "If a wave is 2 m, it is:",
    options: ["Outside UHF and outside microwaves by the simplified ranges", "In gamma rays", "In visible violet"],
    correctOptionIndex: 0,
  },
  {
    id: 186,
    text: "Photon energy increases when:",
    options: ["Frequency increases", "Frequency decreases", "Wavelength increases without limit"],
    correctOptionIndex: 0,
  },
  {
    id: 187,
    text: "Longer radio waves generally have:",
    options: ["Lower photon energy", "Higher photon energy than gamma rays", "No electromagnetic field"],
    correctOptionIndex: 0,
  },
  {
    id: 188,
    text: "Microwaves generally have more photon energy than long radio waves because they have:",
    options: ["Higher frequency", "Lower frequency", "No frequency"],
    correctOptionIndex: 0,
  },
  {
    id: 189,
    text: "Gamma rays have very high energy because they have:",
    options: ["Very high frequency", "Very long wavelength only", "No oscillation"],
    correctOptionIndex: 0,
  },
  {
    id: 190,
    text: "The key relationship is:",
    options: ["Higher frequency means shorter wavelength and higher energy", "Higher frequency means longer wavelength and lower energy", "Frequency, wavelength, and energy are unrelated"],
    correctOptionIndex: 0,
  },
  {
    id: 191,
    text: "Energy values in the table were expressed approximately in:",
    options: ["eV", "kg", "meters only"],
    correctOptionIndex: 0,
  },
  {
    id: 192,
    text: "UHF photon energy is very low compared with:",
    options: ["X-rays or gamma rays", "AM radio only", "Long waves only"],
    correctOptionIndex: 0,
  },
  {
    id: 193,
    text: "A wave at 300 GHz has more photon energy than one at 300 MHz because:",
    options: ["It has higher frequency", "It has lower frequency", "It has no wavelength"],
    correctOptionIndex: 0,
  },
  {
    id: 194,
    text: "A wave with shorter wavelength generally has:",
    options: ["Higher photon energy", "Lower photon energy", "No relationship to energy"],
    correctOptionIndex: 0,
  },
  {
    id: 195,
    text: "A wave with longer wavelength generally has:",
    options: ["Lower frequency and lower photon energy", "Higher frequency and higher energy", "No electric field"],
    correctOptionIndex: 0,
  },
  {
    id: 196,
    text: "Technically, radio waves are:",
    options: ["Electromagnetic radiation", "Sound radiation only", "Chemical radiation only"],
    correctOptionIndex: 0,
  },
  {
    id: 197,
    text: "Technically, microwaves are:",
    options: ["Electromagnetic radiation", "Mechanical vibrations only", "Liquid waves"],
    correctOptionIndex: 0,
  },
  {
    id: 198,
    text: "Technically, visible light is:",
    options: ["Electromagnetic radiation", "Sound only", "A chemical solution"],
    correctOptionIndex: 0,
  },
  {
    id: 199,
    text: "The word \"radiation\" is often associated with high-frequency waves because they:",
    options: ["Have higher energy and stronger effects", "Have no energy", "Are always visible"],
    correctOptionIndex: 0,
  },
  {
    id: 200,
    text: "Ultraviolet, X-rays, and gamma rays are often called radiation in everyday speech because they are:",
    options: ["Higher-frequency and more energetic", "Lower-frequency than AM radio", "Not electromagnetic"],
    correctOptionIndex: 0,
  },
  {
    id: 201,
    text: "It is incorrect to say radio waves are not radiation because:",
    options: ["They are electromagnetic radiation too", "They are made of water", "They are sound waves"],
    correctOptionIndex: 0,
  },
  {
    id: 202,
    text: "The safer statement is:",
    options: ["All electromagnetic waves are radiation, but people often emphasize the word for high-energy waves", "Only gamma rays are electromagnetic radiation", "Radio waves are mechanical waves"],
    correctOptionIndex: 0,
  },
  {
    id: 203,
    text: "Visible light is electromagnetic radiation within a certain:",
    options: ["Frequency and wavelength interval", "Taste and smell interval", "Weight and color-price interval"],
    correctOptionIndex: 0,
  },
  {
    id: 204,
    text: "Radio waves are electromagnetic waves within certain:",
    options: ["Frequency and wavelength intervals", "Temperature-only intervals", "Chemical intervals"],
    correctOptionIndex: 0,
  },
  {
    id: 205,
    text: "Microwaves are electromagnetic waves within certain:",
    options: ["Frequency and wavelength intervals", "Sound-only intervals", "Mechanical pressure intervals"],
    correctOptionIndex: 0,
  },
  {
    id: 206,
    text: "In order of increasing frequency and energy, infrared comes:",
    options: ["After microwaves and before visible light", "After gamma rays", "Before radio waves"],
    correctOptionIndex: 0,
  },
  {
    id: 207,
    text: "In order of increasing frequency and energy, ultraviolet comes:",
    options: ["After visible light and before X-rays", "Before radio waves", "Between radio and microwaves"],
    correctOptionIndex: 0,
  },
  {
    id: 208,
    text: "The colors red, orange, yellow, green, blue, indigo, and violet are part of:",
    options: ["Visible light", "Radio waves", "X-rays"],
    correctOptionIndex: 0,
  },
  {
    id: 209,
    text: "From red to violet, the wavelength:",
    options: ["Decreases", "Increases", "Becomes unrelated to frequency"],
    correctOptionIndex: 0,
  },
  {
    id: 210,
    text: "The final main idea about UHF and microwaves is:",
    options: ["From 1 m to 10 cm, the same wave can be called UHF or microwave depending on convention", "UHF and microwaves are always physically different in the overlap", "Microwaves are visible colors"],
    correctOptionIndex: 0,
  },
];
